### ISSUE TITLE
Make reth-network-types leaner again

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10005]
### Describe the feature

in recent prs we moved a few things around and ended up with types in this crate that really don't belong in there because this crate is intended as light weight crate that defines types that are used as standalone types not necessarily when interacting with the network implementation directly

## TODO
* remove p2p crate dependency, this is backwards and types should not depend on it https://github.com/paradigmxyz/reth/blob/c71c8130329596990b9597958daef8b9773d1bdd/crates/net/network-types/Cargo.toml#L22-L22
* move network specific types back to network or API crate this includes
  *  https://github.com/paradigmxyz/reth/blob/c71c8130329596990b9597958daef8b9773d1bdd/crates/net/network-types/src/peers/handle.rs#L13-L13
  * https://github.com/paradigmxyz/reth/blob/c71c8130329596990b9597958daef8b9773d1bdd/crates/net/network-types/src/peers/cmd.rs#L12-L12
  * https://github.com/paradigmxyz/reth/blob/c71c8130329596990b9597958daef8b9773d1bdd/crates/net/network-types/src/peers/mod.rs#L24-L24

**Comment by emhane** [comment]
new `reth-network-primitves` crate instead? for the standalone types

**Comment by mattsse** [comment]
I don't think this is necessary, network-api should be sufficient

**Comment by emhane** [comment]
what's the argument from having a different pattern than `reth-rpc-eth-api` and `reth-rpc-eth-types` here?

**Comment by mattsse** [comment]
smaller crate, the lowest in the stack that defines things we can use without pulling in more of the network stuff.
