### ISSUE TITLE
Improve connecting downloaded blocks

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10017]
ref #10015 

with #10014 we try to connect blocks that a child blocks of the executed block:

https://github.com/paradigmxyz/reth/blob/d5d46a86110eff5d48920027fb02f52d4f585e08/crates/engine/tree/src/tree/mod.rs#L1275-L1275

there are more scenarios where we can execute more blocks, since we're mixing, basically everytime we insert a new executed block, there's a chance that it has child blocks that are already buffered.

we previously solved this in the blockchain tree when we appended a new chain we always tried to connect.

https://github.com/paradigmxyz/reth/blob/d5d46a86110eff5d48920027fb02f52d4f585e08/crates/blockchain-tree/src/blockchain_tree.rs#L442-L445

## TODO
* find an appropriate solution for this in the new design, it could be as simple as also trying to connect the just inserted new payload:
https://github.com/paradigmxyz/reth/blob/d5d46a86110eff5d48920027fb02f52d4f585e08/crates/engine/tree/src/tree/mod.rs#L1707-L1707

**Comment by emhane** [comment]
this queue data structure I implemented can be used here https://github.com/paradigmxyz/reth/pull/7414
