### ISSUE TITLE
Add to the peers or network handler the ability to (re)connect  to a peer

### ISSUE THREAD

**Issue by rwlockbg** [paradigmxyz/reth#10016]
### Describe the feature

I see that if I use the network handler I could both remove peer and disconnect from peer:

`network_clone.remove_peer(peer_id, PeerKind::Basic)`

`network_clone.disconnect_peer(peer_id)`

In the first case we remove the peer from the peers list.  In the latter , we disconnect the peer physically. 

I need either the network or the peer handler to give us the chance to re-connect to a peer that I have just disconnected with. 

I presume reth could do the automatic re-connection once a peer that was originally added to the peers list gets physically disconnected. Can you also confirm that ?

**Comment by mattsse** [comment]
we can manually trigger this with a new command:

similar to

https://github.com/paradigmxyz/reth/blob/d5d46a86110eff5d48920027fb02f52d4f585e08/crates/net/network/src/manager.rs#L590-L592

that adds a peer and starts dialing it

**Comment by rwlockbg** [comment]
> we can manually trigger this with a new command:
> 
> similar to
> 
> https://github.com/paradigmxyz/reth/blob/d5d46a86110eff5d48920027fb02f52d4f585e08/crates/net/network/src/manager.rs#L590-L592
> 
> that adds a peer and starts dialing it

@mattsse Any ETA when you guys can add this ?

**Comment by mattsse** [comment]
opened this as good first issue and this feature is easy to add and should get picked up shortly

**Comment by varun-doshi** [comment]
Hi @mattsse 
I would like to take this up.

Thank you

**Comment by mattsse** [comment]
hey @varun-doshi this is already wip on #10028
