### ISSUE TITLE
[feature] op-reth container image

### ISSUE THREAD

**Issue by jgresham** [paradigmxyz/reth#10054]
### Describe the feature

A published `op-reth` container would be helpful for users wanting to run `op-reth` as a container along with their other node clients and services. Currently, `op-reth` is just available as a binary.

### Additional context
Or if it makes more sense, op-reth included with reth container?

_No response_

**Comment by 8times4** [comment]
You should be able to use their gchr.io container image via `ghcr.io/paradigmxyz/op-reth`, it's just not documented for op-reth, but it's within the same GitHub Actions workflow. 
See docs for the default `reth`: https://reth.rs/installation/docker.html?highlight=ghcr#github (logic is the same for `op-reth`)

**Comment by jgresham** [comment]
> You should be able to use their gchr.io container image via `ghcr.io/paradigmxyz/op-reth`, it's just not documented for op-reth, but it's within the same GitHub Actions workflow. See docs for the default `reth`: https://reth.rs/installation/docker.html?highlight=ghcr#github (logic is the same for `op-reth`)

works. thanks!

**Comment by Rjected** [comment]
we have this now, closing
