### ISSUE TITLE
add devmode launcher implementation

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10104]
with the new orchestrator trait design, we can now implement a proper devmode orchestrator directly on top of the auto-seal-consensus implementation and we no longer need to mimic the engine API internally:

https://github.com/paradigmxyz/reth/blob/eda161af2c4cb3457eed9d3b81b9b2e5f55db313/crates/consensus/auto-seal/src/task.rs#L159-L163

## TODO
* Add `DevOrchestrator` implementation that drives the MiningTask and advances the node
https://github.com/paradigmxyz/reth/blob/eda161af2c4cb3457eed9d3b81b9b2e5f55db313/crates/consensus/auto-seal/src/task.rs#L83-L89
* This should start as a duplicated implementation of `MiningTask` that emits new `ExecutedBlock`
* the `DevOrchestrator` then uses that block to advance the chain by persisting the block, similar to 

https://github.com/paradigmxyz/reth/blob/eda161af2c4cb3457eed9d3b81b9b2e5f55db313/crates/engine/tree/src/tree/mod.rs#L541-L544

see for reference:

https://github.com/paradigmxyz/reth/blob/eda161af2c4cb3457eed9d3b81b9b2e5f55db313/crates/ethereum/node/src/launch.rs#L259-L259

**Comment by malik672** [comment]
@mattsse assign me

**Comment by mattsse** [comment]
@malik672 do you still have the capacity to work on this?

**Comment by malik672** [comment]
@mattsse yes I do, was already working on it but stopped, it's kinda hard ngl

**Comment by mattsse** [comment]
hehe it is

please open a draft pr and I can provide more directions

**Comment by mattsse** [comment]
completed
