### ISSUE TITLE
Support custom EvmConfig for ethereumpayload builder

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10103]
### Describe the feature

as https://github.com/paradigmxyz/reth/issues/9962 surfaced, the default eth payloadbuilder always uses the default evm config: 

https://github.com/paradigmxyz/reth/blob/f8e6e2e3d4bb0f97d588c634185d22acb41a56a9/crates/ethereum/node/src/node.rs#L199-L199

we already have this for OP but forgot to do the same for ethereum:

https://github.com/paradigmxyz/reth/blob/f8e6e2e3d4bb0f97d588c634185d22acb41a56a9/crates/optimism/node/src/node.rs#L214-L214

https://github.com/paradigmxyz/reth/blob/f8e6e2e3d4bb0f97d588c634185d22acb41a56a9/crates/optimism/node/src/node.rs#L246-L247

## TODO

* mirror `OptimismPayloadBuilder` for ethereumpayloadbuilder and configure properly in the custom-evm example, but perhaps the ethereumpayloadbuilder should instead get an instance of `ConfigureEvm`

fyi @igor-ritual

**Comment by igor-ritual** [comment]
I applied the builder change from the example here https://github.com/paradigmxyz/reth/pull/10117 but I am still experiencing the bad block issue. Also, this other example needs to be updated as well: https://github.com/paradigmxyz/reth/blob/8d07bdb81a6f8616afcddd9b821312f52241c81b/examples/stateful-precompile/src/main.rs#L248
