### ISSUE TITLE
Enable the GitHub Slack integration

### ISSUE THREAD

**Issue by Madhulearn6** [paradigmxyz/reth#10108]
### Describe the feature

Hello Team,

I’m reaching out on behalf of [Lisk](https://lisk.com/). We’re currently a member of the [OP Superchain ecosystem](https://www.superchain.eco/ecosystem-chains/lisk).

We currently have the [lisk-node](https://github.com/LiskHQ/lisk-node) repo which currently allows operators to conveniently run their nodes on Lisk L2.

To help our integration partners operate their nodes on the Lisk L2 we currently have the [lisk-node](https://github.com/LiskHQ/lisk-node) repo. Based on our recent challenges with the Fjord upgrade, we have established an internal process to keep ourselves up-to-date based on your repo updates. An integral part of the long-term solution involves setting up notifications on our Slack channels which cannot be achieved without you enabling the integration on your GitHub repo.

So, could we please request you to enable the [GitHub Slack integration](https://github.com/integrations/slack) on your repo to help us be more efficient?
FYR, the [ethereum-optimism/optimism](https://github.com/ethereum-optimism/optimism) repo already supports this integration.

Kindly let us know if you need any further information from our end.
We anticipate your support and thank you in advance.

Best regards,
Lisk Team

**Comment by ShantelPeters** [comment]
Hello @Madhulearn6 can I be assigned to this issue please ?

**Comment by Madhulearn6** [comment]
@ShantelPeters, for my surprise the assigning option is not enabled to me. Could you try self assigning please

**Comment by sameersubudhi** [comment]
Hello @mattsse @Rjected @onbjerg ,

Could you please have a look at it? We would really appreciate your support 🙏
The OP team also enabled the support on op-geth as well with https://github.com/ethereum-optimism/op-geth/issues/356.

**Comment by onbjerg** [comment]
I'm not sure why we need to enable the app for you to be able to subscribe, the API is open and the repository is public. Could you please provide some more context on why this is needed? As far as I can see, if you use Slack and you have the app installed, you should be able to just do `/github subscribe https://github.com/paradigmxyz/reth`?

**Comment by sameersubudhi** [comment]
Hello @onbjerg,

Thank you for responding to our request.

To let us subscribe, you'll need to install the Slack app on the repository.
Trying to subscribe at our end results in the following error. Hence, we reached out to you.

<img width="688" alt="Screenshot 2024-08-23 at 13 38 58" src="https://github.com/user-attachments/assets/d01ce7d0-f0ce-42e0-8969-0dd16141ed28">

**Comment by gakonst** [comment]
Hi folks -- the app is now installed on the repo.
