### ISSUE TITLE
Improve OP docs for discovery 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10111]
### Describe the feature

ref https://github.com/paradigmxyz/reth/pull/10110#pullrequestreview-2219938303

this section should highlight OP specific discovery defaults compared to regular reth

https://github.com/paradigmxyz/reth/blob/eda161af2c4cb3457eed9d3b81b9b2e5f55db313/book/run/optimism.md#L59-L59

by default discv5 is enabled, and discv4 disabled (same as op-geth), whereas reth has discv4 enabled and discv4 disabled by default

**Comment by ShantelPeters** [comment]
Hi @mattsse can I work on this?
