### ISSUE TITLE
Ensure persistence receiver is dropped when value is received

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10115]
this currently does not ensure the oneshot rx is dropped when we receive a value:

https://github.com/paradigmxyz/reth/blob/443f7d56ac1317caa29178decd087561828967dd/crates/engine/tree/src/tree/mod.rs#L613-L613

this can be rewritten by doing `let tx = self.persistence_state.rx.take()` and only reassign it if `TryRecvError::Empty`

after the latest refactor, we can now also return an error with this function that should terminate the run loop

https://github.com/paradigmxyz/reth/blob/443f7d56ac1317caa29178decd087561828967dd/crates/engine/tree/src/tree/mod.rs#L592-L592

https://github.com/paradigmxyz/reth/blob/443f7d56ac1317caa29178decd087561828967dd/crates/engine/tree/src/tree/mod.rs#L559-L559

**Comment by mvares** [comment]
:shipit:

**Comment by ShantelPeters** [comment]
Hi @mattsse can I jump on this?
