### ISSUE TITLE
Reuse available in-memory trie nodes in MemoryOverlayStateProvider

### ISSUE THREAD

**Issue by mvares** [paradigmxyz/reth#10116]
Currently, we don't reuse available in-memory trie nodes here:

https://github.com/paradigmxyz/reth/blob/61500238fb25a6f3c3bbe8e56efad0e57a83f333/crates/chain-state/src/memory_overlay.rs#L88-L113

### Todo

- Make it able use in-memory trie nodes for operations

**Comment by mvares** [comment]
@mattsse, if possible, assigns it for me 👊🏻

**Comment by ShantelPeters** [comment]
Hello @mvares can I work on this? 
This would be my first time contributing to this ecosystem

**Comment by rkrasiuk** [comment]
duplicate of #9706
