### ISSUE TITLE
Execute transaction on past state

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1012]
### Describe the feature

Have the ability to execute transactions on past state. More like utility if somebody wants to execute solidity getters on past state, this can potentialy be useful (mostly for inspection of past state).

 I don't know how useful this would be but it shouldn't be a big problem to add and have. 

### Additional context

Blocked by HistoryProvider: https://github.com/paradigmxyz/reth/issues/816

**Comment by gakonst** [comment]
What do we need here, given we now have #816 and historical state factories? @rakita @mattsse

**Comment by rakita** [comment]
Mostly to define how a user can call it. and glue all parts together.

**Comment by onbjerg** [comment]
I think we have this

**Comment by gakonst** [comment]
Yes - it's in the Historical providers
