### ISSUE TITLE
remove EngineApiTreeHandler trait

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10123]
this trait isn't actually used 

https://github.com/paradigmxyz/reth/blob/08158e444953b2bef998d50335967e3550fb403c/crates/engine/tree/src/tree/mod.rs#L334-L335

and we can unify the OP implementation here anyway so we can remove this and convert the functions into regular functions

**Comment by mvares** [comment]
👊🏻

**Comment by mvares** [comment]
@mattsse, what's the OP implementation that you are speaking?

**Comment by mattsse** [comment]
initially we assumed we need an optimism specific implementation, but we don't so this trait is redundant and we can reuse one implementation for both optimism and eth

**Comment by mvares** [comment]
Grateful for explanation 👍🏻 

Well, the functions of `EngineApiTreeHandler` can become regular, but they have few dependencies. What do you think we integrate these functions as method from `EngineApiTreeHandlerImpl`?

[Reference (Methods)](https://github.com/paradigmxyz/reth/blob/58a5d2646967dba803b4ce6d02fbe42f97f3d612/crates/engine/tree/src/tree/mod.rs#L1673C40-L1915)

https://github.com/paradigmxyz/reth/blob/58a5d2646967dba803b4ce6d02fbe42f97f3d612/crates/engine/tree/src/tree/mod.rs#L310-L348

**Comment by mvares** [comment]
Sounds like a plan 🥷
