### ISSUE TITLE
Support FillTxEnv on the transaction type level 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10129]
### Describe the feature

currently the `FillTxEnv` is still feature gated

https://github.com/paradigmxyz/reth/blob/06e7afbd2d898b6f95ff7b757f53327d189e2048/crates/primitives/src/transaction/compat.rs#L4-L10

because the trait is implemented directly for the `TransactionSigned` type

we can get rid of this feature in various ways, the best way would be to offload this to the individual tx variants so we can easily reuse this code for a dedicated optimism and ethereum implementation of `FillTxEnv`

**Comment by malik672** [comment]
@mattsse assign me
