### ISSUE TITLE
Block builder

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1013]
### Describe the feature

Have the ability to take transactions from txpool, execute them against current plain state until block gas limit and calculate all headers roots

**Comment by rakita** [comment]
> agree with what @onbjerg said. also, i think, this is blocked by #662

I think we are going in this direction: We are moving sidechain complexity from pipeline and db tables to Downloader and in memory structures. The reason why this is possible is that every blockchain (not just eth) has a finality.

**Comment by gakonst** [comment]
Assigning to @rkrasiuk given he's taken point on Engine API.

**Comment by rakita** [comment]
Just a info here, executing the block and building the block are two different functions.

We have `StateProvider` trait that wraps database access.

The algorithm for building the block if I remember correctly is all about filling block gas to the max.
You have a list of transactions that you iterate on and then:
```rust
let block_remaining_gas = eip1559(gas_limit);
for tx in txs {
     if tx.gas_limit > block_remaining_gas {
             continue
      }
      ...
      let res revm::execute(tx) // with revm 3.0.0 if it is Return::Err this tx is invalid and needs to be skipped.
      commit(res)
      ....
      block_remaining_gas -= res.gas_used; 
}
//calculate all roots( state root, receipt root,etc.)
```

changesets can probably be returned as they can be reused.

**Comment by gakonst** [comment]
Unassigning given we'll go for the builder later and is not a blocker for full-sync.

**Comment by joroshiba** [comment]
For a project I'm working on, we will need something related to this: we have a separate sequencer for transactions, but we need to get the correct executed header. Given that we are using Rust, would like to use REVM, and Reth aims to be a framework for other EVMs, would rather contribute than do home cooking.

What we need: given the current DB state, take a set of `PayloadAttributes`, a list of transactions, and execute to return an `ExecutionPayload`. 

I believe this can function as a part of this broader issue: while block building requires logic around picking the transactions, maximizing gas fees... you also need to execute to get header data.

If this is functionality the team agrees would be useful, the broader question is where it should be contributed to. My gut feeling is that this should be on the `executor` crate, but I haven't been directly working on the project just observing thus far. I’m envisioning a function defined as such:  

```rust
pub fn gen_execution_payload<DB: StateProvider>(
    payloadAttrs: &PayloadAttributes,
    transactions: &[TransactionSignedEcRecovered],
    db: &mut SubState<DB>,
) -> Result<ExecutionPayload, Error>
```

I think this is also like related to https://github.com/paradigmxyz/reth/issues/1105 and https://github.com/paradigmxyz/reth/issues/1104 let me know if this is best directed there.

**Comment by gakonst** [comment]
Yeah I think this is related to 1104. Your API seems to make sense, would try to not leak the SubState type like we do in the executor. 

But yeah I would expose that as a method on the executor, and we can do the logic around which txs to pick separate. you should probably also return how much profit there is in that payload?

**Comment by mattsse** [comment]
I believe this issue is now covered with 

https://github.com/paradigmxyz/reth/pull/2161

and 

https://github.com/paradigmxyz/reth/pull/2161

so vote to close

**Comment by gakonst** [comment]
Agree, nice work. The out-of-process builder for MEV etc. is a separate topic.
