### ISSUE TITLE
Convert pending block to a watch channel

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10157]
it is beneficial to have a listener for the pending block:

https://github.com/paradigmxyz/reth/blob/7486d5bafe235d25311fa347d9c790abd666121f/crates/chain-state/src/in_memory.rs#L50-L51

like we do with the latest as well:

https://github.com/paradigmxyz/reth/blob/7486d5bafe235d25311fa347d9c790abd666121f/crates/chain-state/src/chain_info.rs#L141-L144

## TODO
* convert RwLock into a watch channel

This will be useful for https://github.com/paradigmxyz/reth/issues/5617

**Comment by mvares** [comment]
👊🏻

**Comment by mattsse** [comment]
hey @mvares this one's already taken by @jenpaff

perhaps I can interest you in https://github.com/paradigmxyz/reth/issues/7490

**Comment by jenpaff** [comment]
Not related to this issue, but since it's my one, wanted to raise some questions:
- Small nit pick, but I noticed you don't have a `rust-toolchain.toml` and was wondering is there a reason? 
- 2 tests in `lockfile.rs` are still failing locally for me on main, will debug, I suppose that's on my end

**Comment by mattsse** [comment]
> but I noticed you don't have a rust-toolchain.toml and was wondering is there a reason

can't remember why, likely because we never needed it

> 2 tests in lockfile.rs are still failing locally for me on main, will debug, I suppose that's on my end

It could be because there are some issues if they are run in the same process via `cargo t` in CI this isn't an issue with cargo nextest
