### ISSUE TITLE
Support --build.interval in milliseconds

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10167]
### Describe the feature

currently the builder timeout is in seconds

https://github.com/paradigmxyz/reth/blob/9ad7ebbbc6facd7ef2165508ffe8d9dfd453ce51/crates/node/core/src/args/payload_builder.rs#L24-L26

this is not ideal for OPstack with lower block times or when a job should be triggered immediately

## TODO 
* support ms parsing on CLI level

**Comment by Parikalp-Bhardwaj** [comment]
Hey @mattsse,  I can take this
