### ISSUE TITLE
validate EOF bytecode on Genesis.

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#10172]
### Describe the feature

If there ar EOF bytecodes in the Genesis file we should validate those bytes so that only valid EOF bytecodes are found in the state.

The function is found in `use revm::interpreter::analysis::validate_raw_eof_inner` and it needs to be `CodeType::ReturnOrStop` type (Will renaming it to `ContainerKind::Runtime`)

### Additional context

It does not affect mainnet, it is a guard for new chains that have EOF enabled from the start.

**Comment by danielcdz** [comment]
Hello @rakita Can I help with this one?

**Comment by rakita** [comment]
> Hello @rakita Can I help with this one?

Go for it

**Comment by danielcdz** [comment]
Hello @rakita can you give me more context about this? Is a validation that needs to be moved from to a different function?

**Comment by emnul** [comment]
Hey @danielcdz any updates on your progress here? Happy to take over if you haven't been able to get around to it

**Comment by danielcdz** [comment]
Hello! @emnul I definitely need some help here, can you provide me more context about the issue?

**Comment by emnul** [comment]
I think this will help https://github.com/ipsilon/eof/blob/main/spec/eof.md. Although, I'm not sure what "Genesis" refers to in description here. I would reach out to the telegram or open a discussion for more information / clarification.

**Comment by danielcdz** [comment]
@emnul thank you! do yo have the link to the telegram?

**Comment by emnul** [comment]
> @emnul thank you! do yo have the link to the telegram?

Check the README.md file

**Comment by emnul** [comment]
I believe genesis file in the description refers the `genesis.json` file which is a JSON-formatted file used to define the initial state of the blockchain at the time of its creation. Here's a good usage [example](https://github.com/paradigmxyz/reth/blob/main/examples/polygon-p2p/src/chain_cfg.rs). The struct definition of a [Genesis](https://docs.rs/alloy-genesis/latest/alloy_genesis/struct.Genesis.html) block. I'm not sure if the [extra_data](https://docs.rs/alloy-genesis/latest/alloy_genesis/struct.Genesis.html#structfield.extra_data) field is what needs to be validated or if it's the [code](https://docs.rs/alloy-genesis/latest/alloy_genesis/struct.GenesisAccount.html#structfield.code) field of the [GenesisAccounts](https://docs.rs/alloy-genesis/latest/alloy_genesis/struct.GenesisAccount.html) listed in the [alloc](https://docs.rs/alloy-genesis/latest/alloy_genesis/struct.Genesis.html#structfield.alloc) field. Need to do more research.

**Comment by emnul** [comment]
Hey @rakita is this not already validated on this [line](https://github.com/paradigmxyz/reth/blob/5254f16e07965686ebf2b906c1e6fc7b04863f3e/crates/storage/db-common/src/init.rs#L163)? Bytecode::new_raw has [EOF validation built-in](https://docs.rs/revm-primitives/8.0.0/src/revm_primitives/bytecode.rs.html#83). Or was the intention here to perform validation in the [ChainSpecBuilder](https://github.com/paradigmxyz/reth/blob/main/crates/chainspec/src/spec.rs#L825) or somewhere else? Please clarify

**Comment by rakita** [comment]
> Hey @rakita is this not already validated on this [line](https://github.com/paradigmxyz/reth/blob/5254f16e07965686ebf2b906c1e6fc7b04863f3e/crates/storage/db-common/src/init.rs#L163)? Bytecode::new_raw has [EOF validation built-in](https://docs.rs/revm-primitives/8.0.0/src/revm_primitives/bytecode.rs.html#83). Or was the intention here to perform validation in the [ChainSpecBuilder](https://github.com/paradigmxyz/reth/blob/main/crates/chainspec/src/spec.rs#L825) or somewhere else? Please clarify

Hey, was on vacation last week. This looks like a good place but the function that needs to be called is `Bytecode::new_raw_checked` and the error needs to be propagated as invalid json.

**Comment by emnul** [comment]
> This looks like a good place but the function that needs to be called is Bytecode::new_raw_checked and the error needs to be propagated as invalid json.

Gotcha, so to be clear, @danielcdz should modify the [insert_state](https://github.com/paradigmxyz/reth/blob/ec31b247e9ba927a5efd15b22340cf8abab749a2/crates/storage/db-common/src/init.rs#L151) function in [reth/crates/storage/db-common/src/init.rs](https://github.com/paradigmxyz/reth/blob/main/crates/storage/db-common/src/init.rs) to use `Bytecode::new_raw_checked` and with added error handling such that the error is propagated as invalid json?

**Comment by emnul** [comment]
@danielcdz feel free to reach out if you run into any other blockers.

**Comment by danielcdz** [comment]
Hey @emnul and @rakita I really appreciate your help and clarifications here, I'll be working on this and if a get stuck I'll let you guys know!

**Comment by danielcdz** [comment]
Hey @emnul I opened a PR for this, I don't know if it is good at all, but I would appreciate it if you take a look and provide feedback.
