### ISSUE TITLE
Make `BlockchainProvider2` ChangeSetReader aware of in-memory state

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#10184]
Similar to https://github.com/paradigmxyz/reth/issues/10181

This method needs to also be aware of in-memory canonical state:
https://github.com/paradigmxyz/reth/blob/a7062066958f45665f41de58d94b1bc5c6d68c57/crates/storage/provider/src/providers/blockchain_provider.rs#L1157-L1167

**Comment by malik672** [comment]
@Rjected assign me

**Comment by fgimenez** [comment]
> @Rjected assign me

@malik672 done!

**Comment by malik672** [comment]
@fgimenez thank you

**Comment by shekhirin** [comment]
hey @malik672, we need this fixed ASAP, so I'm going to take over! Also check other issues that we have open 🙂

**Comment by malik672** [comment]
@shekhirin ok, no p, was planning on doing it tomorrow
