### ISSUE TITLE
Only mark propagated txs as seen

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10213]
### Describe the feature

currently we're marking txs as seen

https://github.com/paradigmxyz/reth/blob/71bf575a4e60b8e14b590094f3b7f767dbd1fa61/crates/net/network/src/transactions/mod.rs#L435-L436

before we're truncating the hashes or full transactions:

https://github.com/paradigmxyz/reth/blob/71bf575a4e60b8e14b590094f3b7f767dbd1fa61/crates/net/network/src/transactions/mod.rs#L460-L462

https://github.com/paradigmxyz/reth/blob/71bf575a4e60b8e14b590094f3b7f767dbd1fa61/crates/net/network/src/transactions/mod.rs#L473-L473

## TODO
* only check if `!.contains` and only insert actually propagated txs into `seen_transactions`

**Comment by SkandaBhat** [comment]
Hey @mattsse could I pick this up?
