### ISSUE TITLE
Properly bubble up `InsertBlockFatalError`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#10219]
ref https://github.com/paradigmxyz/reth/pull/10217#pullrequestreview-2228744443

We need to introduce a way to handle any fatal errors that were encountered when calling `insert_block`.

This happens in two places not already handled, first in `on_downloaded_block`:
https://github.com/paradigmxyz/reth/blob/0ee689f3577048bebf3b97d642af69cded17a9c0/crates/engine/tree/src/tree/mod.rs#L1638-L1643

And in `try_connect_buffered_blocks`:
https://github.com/paradigmxyz/reth/blob/0ee689f3577048bebf3b97d642af69cded17a9c0/crates/engine/tree/src/tree/mod.rs#L1394-L1396

`on_backfill_sync_finished` calls `try_connect_buffered_blocks` here:
https://github.com/paradigmxyz/reth/blob/0ee689f3577048bebf3b97d642af69cded17a9c0/crates/engine/tree/src/tree/mod.rs#L502

The other call to `try_connect_buffered_blocks` is here:
https://github.com/paradigmxyz/reth/blob/0ee689f3577048bebf3b97d642af69cded17a9c0/crates/engine/tree/src/tree/mod.rs#L1628

However, we need to bubble the error in this method anyways or include it in `TreeEvent` somehow, because we call `insert_block` here and need to handle the error:
https://github.com/paradigmxyz/reth/blob/0ee689f3577048bebf3b97d642af69cded17a9c0/crates/engine/tree/src/tree/mod.rs#L1638-L1643

**Comment by martinezjorge** [comment]
Is anyone on this? Could I take a stab at it?

**Comment by Rjected** [comment]
> Is anyone on this? Could I take a stab at it?

sure! let me know if you have any questions or need review

**Comment by rkrasiuk** [comment]
@Rjected emitting a fatal event is not ideal. we should properly bubble it up. @martinezjorge feel free to change the return types of methods in the flow in question
