### ISSUE TITLE
track persistence duration

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10220]
ref #9794

we want metrics how long persistence took and should track this two fold:

1. with a histogram here https://github.com/paradigmxyz/reth/blob/c4aae6db361d2ac33fed18f25bb50158907723ee/crates/engine/tree/src/tree/metrics.rs#L9-L9 how long this took: https://github.com/paradigmxyz/reth/blob/c4aae6db361d2ac33fed18f25bb50158907723ee/crates/engine/tree/src/tree/mod.rs#L1980-L1980 this can be done by also storing an `Instant` together with the receiver.
2. and actual metrics for how long these took https://github.com/paradigmxyz/reth/blob/c4aae6db361d2ac33fed18f25bb50158907723ee/crates/engine/tree/src/persistence.rs#L63-L63 which should be stored in there own metrics struct

**Comment by malik672** [comment]
@mattsse assign me

**Comment by mattsse** [comment]
for 2. the persistence metrics, we should wait for #10221 otherwise there'll be conflicts

**Comment by malik672** [comment]
> for 2. the persistence metrics, we should wait for #10221 otherwise there'll be conflicts

can I solve #10221 together

**Comment by malik672** [comment]
@mattsse I will go ahead and solve both prs

**Comment by mattsse** [comment]
you can do 1. in pr and once we have #10221 the rest, I assume 10221 is already wip
