### ISSUE TITLE
extract persistence event handling into standalone functions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10221]
for readability it would be nice to have this code in standalone functions

https://github.com/paradigmxyz/reth/blob/c4aae6db361d2ac33fed18f25bb50158907723ee/crates/engine/tree/src/persistence.rs#L63-L73

like `on_remove_blocks`, `on_save_blocks` etc.

**Comment by mvares** [comment]
@mattsse, can we maintain these functions within impl?

**Comment by mattsse** [comment]
yes
