### ISSUE TITLE
remove usage of PeerCount type 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10270]
### Describe the feature

we only use `PeerCount` type here:

https://github.com/paradigmxyz/reth/blob/af85c133d165d7fcd46e44ed712bd2579d2433d8/crates/rpc/rpc/src/net.rs#L40-L40

we can get rid of this type and instead replace the response type to `U64` 

ref https://github.com/alloy-rs/alloy/pull/1140#pullrequestreview-2233540222

### Additional context

FYI @tcoratger 

_No response_

**Comment by mvares** [comment]
👌🏻

**Comment by mattsse** [comment]
@mvares @tcoratger already claimed this via alloy :)

**Comment by mvares** [comment]
> @mvares @tcoratger already claimed this via alloy :)

yeah, I saw here 🔥
