### ISSUE TITLE
Abstract `Chainspec`

### ISSUE THREAD

**Issue by klkvr** [paradigmxyz/reth#10272]
### Describe the feature

Current `Chainspec` is pretty much Ethereum-specifc https://github.com/paradigmxyz/reth/blob/af85c133d165d7fcd46e44ed712bd2579d2433d8/crates/chainspec/src/spec.rs#L282-L282

We should turn it into a trait instead, making all functions into trait methods and getting rid of `Arc<Chainspec>` usage across codebase

**Comment by mvares** [comment]
@klkvr this makes total sense. finally, methods as like:
```rust
    pub fn is_optimism(&self) -> bool {
        self.chain.is_optimism() || self.hardforks.get(OptimismHardfork::Bedrock).is_some()
    }
    
```
  will be only of a specific trait
