### ISSUE TITLE
Move ReputationChangeKind to network-api

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1028]
### Describe the feature

Currently `ReputationChangeKind` resides in network crate:

https://github.com/paradigmxyz/reth/blob/93194e8a0cd6cec99cd1254e901b618e65e531bf/crates/net/network/src/peers/reputation.rs#L40-L42

this should be part of the public network API so reputation changes can be applied.

## TODO

* add `network-api/src/reputation.rs`
* move `ReputationChangeKind` to that new file

**Comment by leruaa** [comment]
I would like to take this on
