### ISSUE TITLE
Add Txpool functions to retrieve txs by state and origin

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10294]
### Describe the feature

we have functions to retrieve txs by state:

https://github.com/paradigmxyz/reth/blob/8a802dab600cd9a2dc0470eeeb22d1a0ccc30d8a/crates/transaction-pool/src/traits.rs#L274-L274

we also want convenience functions to get txs by origin `TransactionOrigin`

## TODO
* add convenience functions similar to 
https://github.com/paradigmxyz/reth/blob/8a802dab600cd9a2dc0470eeeb22d1a0ccc30d8a/crates/transaction-pool/src/traits.rs#L347-L350
but for `pending` or `queued`

**Comment by mvares** [comment]
@mattsse can you say me if already exists a enum that incorporates this? (pending, queued...)

**Comment by mvares** [comment]
@mattsse, I'm having one problem:
```rust
    pub(crate) fn get_pending_tx(
        &self,
        origin: TransactionOrigin,
    ) -> Vec<Arc<ValidPoolTransaction<<V as TransactionValidator>::Transaction>>> {
        self.pending_transactions().iter().filter(|tx| tx.origin == origin).collect()
    }
   ```
    
  my IDE is hiting an error about the result type. I think is about `collect()`

**Comment by mattsse** [comment]
I think just `Self::Transaction` is sufficient

but this be implemented natively for perf reasons
