### ISSUE TITLE
should we update the recommended hardware in the installation page?

### ISSUE THREAD

**Issue by bap2pecs** [paradigmxyz/reth#10307]
### Describe the change

the reth book [here](https://reth.rs/installation/installation.html#what-hardware-can-i-get) recommended `s2.small.x86`:

<img width="855" alt="image" src="https://github.com/user-attachments/assets/235134ac-86cd-4a23-a2a1-8d18a9a2f3be">

but latitude has already deprecated this box:

<img width="921" alt="image" src="https://github.com/user-attachments/assets/61b6b985-3316-4649-a86a-1f0f3514483c">

the new ones available are:

<img width="901" alt="image" src="https://github.com/user-attachments/assets/90ab8e1f-838f-48ba-9114-aa58b36fc11c">

should we upgrade to c3.small.x86? if now and using the legacy version is still the recommended one, I think we can add some notes in the reth book to avoid confusion

**Comment by shekhirin** [comment]
Yeah, let's recommend the `c3.small.x86` for pruned/full nodes.

**Comment by bap2pecs** [comment]
https://github.com/paradigmxyz/reth/pull/10313 out for review
