### ISSUE TITLE
Improve op-node installation docs

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10312]
### Describe the change

currently we have the rethdb build tag as the default example, however this feature is unstable.

we should instead not start with the rethdb example and instead introduce this as an experimental option

https://github.com/paradigmxyz/reth/blob/97e153ab64c807fcc9860d37368e43a51f8f058b/book/run/optimism.md#L45-L45

## TODO
* add instructions for regular op-node installations and move rethdb feature to its own section

**Comment by PabloVillaplana** [comment]
Hey @mattsse  Can I help with this one? ☝️

**Comment by mattsse** [comment]
yes please!

**Comment by shekhirin** [comment]
hey @PabloVillaplana, are you still working on this? `rethdb-reth` has been removed completely, so we need to remove the mentions of it from the doc altogether https://github.com/ethereum-optimism/optimism/pull/11706
