### ISSUE TITLE
Integrate TaskManager in reth main

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1036]
### Describe the feature

The `tasks` crate provides `TaskManager` and `TaskExecutor`

The `TaskExecutor` is used for spawning new tasks (can be critical tasks, e.g. network tasks, or regular, like p2p session tasks)

The `TaskManager` is notified when a critical task has panicked, which can be used as an exit condition.

It's intended that the `TaskManager` is the main entry point when launching the node.

For example, this will run until a critical task has panicked

```rust
let panicked = manager.next().await;

// this will terminate _all_ tasks spawned via an executor
drop(manager)
```

The shutdown process needs some additional work, I guess ideally we want to listen for ctrl-c -> shutdown tasks

https://github.com/paradigmxyz/reth/blob/main/crates/tasks/src/lib.rs

### Additional context

ref #807

**Comment by literallymarvellous** [comment]
I would like to take this.

Currently, ``` cargo run --bin reth node``` is returning a ```Could not load config error.```

**Comment by mattsse** [comment]
appreciate it, but this would do more harm atm, since there's a bunch of work underway for the CLI

blocked by
#1017 
#963 

If you want to take on something that's slightly more challenging but can be done incrementally https://github.com/paradigmxyz/reth/issues/1037 would be a good start

I believe the config error is due to #1046

**Comment by literallymarvellous** [comment]
Alright, I'll take 1037.

**Comment by onbjerg** [comment]
Should no longer be blocked

**Comment by literallymarvellous** [comment]
Alright, will still like to take this.

Concerning making TaskManager optional, how would that work? Does reth main run without the task manager by default,  maybe have a cli flag for the task manager functionality?

**Comment by mattsse** [comment]
same as:

https://github.com/paradigmxyz/reth/blob/e8d7c051cab95a383f9bcd34c00bec3ea47adfa1/crates/net/network/src/config.rs#L70-L71

I think we need a helper type for `Option<TaskExecutor>`
perhaps `MaybeTaskManager(Option<TaskExecutor>)`

**Comment by onbjerg** [comment]
Blocked by #1079 now, sorry

**Comment by literallymarvellous** [comment]
Ok, so what we've to do is set it here:
https://github.com/paradigmxyz/reth/blob/e8d7c051cab95a383f9bcd34c00bec3ea47adfa1/bin/reth/src/node/mod.rs#L133-L143 Cause it's None by default.
