### ISSUE TITLE
Configure RPC endpoints specific to transports

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1037]
### Describe the feature

Currently, the `RpcModuleBuilder` only has one `build` function

https://github.com/paradigmxyz/reth/blob/c23a2215b0ddb7660c45b2f32bd422491f03c3c9/crates/net/rpc-builder/src/lib.rs#L92-L95

However, we need to configure endpoints for a specific means of transport, for example `--http.api eth,debug --ws-.api eth`

This is configured via:

https://github.com/paradigmxyz/reth/blob/c23a2215b0ddb7660c45b2f32bd422491f03c3c9/crates/net/rpc-builder/src/lib.rs#L125

Which will be configured via `ServerBuilder`

https://github.com/paradigmxyz/reth/blob/c23a2215b0ddb7660c45b2f32bd422491f03c3c9/crates/net/rpc-builder/src/lib.rs#L166

So the ideal workflow would be `ServerBuilder -> RpcModuleBuilder` where `ServerBuilder` knows what to enable per transport.

`RpcModuleBuilder::build` needs to be refactored that it can return an `RpcModule` per transport if enabled

**Comment by mattsse** [comment]
@literallymarvellous please lmk if you need some pointers

please also have a look at this example
https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/proc_macro.rs
that shows how to configure a server

**Comment by mattsse** [comment]
this does not need to be fully working, just fletching out the API, 
you might also have a look at #857 which is somewhat related to this.

**Comment by literallymarvellous** [comment]
Alright, thanks for the link, that's really helpful.
