### ISSUE TITLE
Erroneous response is always reported as BadMessage

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1038]
### Describe the bug

if a response is `Err` it is always returned as

https://github.com/paradigmxyz/reth/blob/c23a2215b0ddb7660c45b2f32bd422491f03c3c9/crates/net/network/src/fetch/mod.rs#L240-L246

which does not distinguish between timeouts, channel related errors

## TODO

* extend `EthResponseValidator` with function `fn reputation_change_err(&self) -> Option<ReputationChangeKind>` based on the error variant.
* used that function for determine the reputation to report here: https://github.com/paradigmxyz/reth/blob/c23a2215b0ddb7660c45b2f32bd422491f03c3c9/crates/net/network/src/fetch/mod.rs#L240-L246

### Steps to reproduce

-

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by leruaa** [comment]
I would like to take this on
