### ISSUE TITLE
remove usage of RichBlock 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10389]
### Describe the feature

this type isn't useful anymore

https://github.com/paradigmxyz/reth/blob/56e1448dbdcbddc6e45a3dad5b4cf81028bf9b96/crates/rpc/rpc-eth-api/src/core.rs#L393-L393

## TODO
* replace with regular Block type

**Comment by Vid201** [comment]
@mattsse I can take this

**Comment by mvares** [comment]
@Vid201 how's the task?

**Comment by mvares** [comment]
@mattsse, there's still some work left to do. My PR was towards the issue but didn't address it.

**Comment by Vid201** [comment]
> @mattsse, there's still some work left to do. My PR was towards the issue but didn't address it.

I saw your PR and thought addressed this issue entirely. What's still missing? Replacing in all places in the code?
