### ISSUE TITLE
feat(rpc): expose execution pre-images

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#10404]
## Description

Expose the map `hashed key => pre-image` for all accounts and slots accessed within a block.

There are 2 ways to achieve this:
1) extend [`debug_executionWitness`](https://github.com/paradigmxyz/reth/blob/72ed7a9b0812fb03b87be9e3877713dc06b7dc91/crates/rpc/rpc-api/src/debug.rs#L136-L146) additional boolean parameter `includePreImages`
2) create new `debug_executionPreImages` endpoint that returns pre-image map

**Comment by 1010adigupta** [comment]
@shekhirin @rkrasiuk has reth enabled this prototype of pre-verkle, stateless execution by Peter: [peter's recent cross-client validation proposal](https://gist.github.com/karalabe/47c906f0ab4fdc5b8b791b74f084e5f9) or @clabby has any work started on this from L2 side, related to pre-verkle stateless execution?

**Comment by 1010adigupta** [comment]
@rkrasiuk can I help in contributing to this issue, I think this will help me familiarise myself with witness and it's use in execution, this may help me in my reth-verkle project, which I am doing for my protocol fellowship project
