### ISSUE TITLE
Return exact gasUsed for eth_createAccessList

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10416]
### Describe the feature

currently we're failing eth_getTransactionReceipt/get-access-list:

https://hivetests2.ethdevops.io/suite.html?suiteid=1724234283-97d383360f6fb3acb2dcc0e447b02aca.json&suitename=rpc-compat#test-22

due to a gasUsed mismatch

> gasUsed: A hexadecimal string representing the approximate gas cost for the transaction if the access list is included.

the issue is likely this estimate call:

https://github.com/paradigmxyz/reth/blob/1f5fb90bc83dd48d38e2f376790125d68ba92f3e/crates/rpc/rpc-eth-api/src/helpers/call.rs#L283-L284

which isn't `gasUsed` but estimates `gas`

## TODO
* change this estimate call to another transact call with the set `accessList` of the txEnv after tracing, similar to:

https://github.com/paradigmxyz/reth/blob/1f5fb90bc83dd48d38e2f376790125d68ba92f3e/crates/rpc/rpc-eth-api/src/helpers/call.rs#L262-L262

but with `self.transact` after setting `env.txEnv.accessList`

**Comment by malik672** [comment]
@mattsse assign me
