### ISSUE TITLE
Configurable bad block hook in new tree

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#10425]
ref https://github.com/paradigmxyz/reth/issues/10405

We currently do not have a good way of inspecting block output if it is a bad block. We cannot call RPC methods like `debug_executionWitness` or `debug_traceBlock` because the block failed validation. Instead, we need a way to run a user-defined method after a block errors because it is an invalid block.

If we wanted to be exhaustive, the hook would be run after this line:
https://github.com/paradigmxyz/reth/blob/e27ad1a2bec91e06d80bcc11b0507955a1826e7c/crates/engine/tree/src/tree/mod.rs#L1797

However, then we would not be able to use the outputs of the block. Instead, we should run it if validation fails here:
https://github.com/paradigmxyz/reth/blob/e27ad1a2bec91e06d80bcc11b0507955a1826e7c/crates/engine/tree/src/tree/mod.rs#L1740

Or here:
https://github.com/paradigmxyz/reth/blob/e27ad1a2bec91e06d80bcc11b0507955a1826e7c/crates/engine/tree/src/tree/mod.rs#L1730

It should be possible for the hook to re-execute the block with traces and get the witness + witness preimages.

**Comment by malik672** [comment]
@Rjected assign me

**Comment by Rjected** [comment]
> @Rjected assign me

Thanks, but I will actually be taking this issue

**Comment by Rjected** [comment]
This was completed with #10432
