### ISSUE TITLE
Add PayloadBuilder Implementation that supports two types of builders

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10438]
The PayloadBuilder trait defines the interface for a basic payloadbuilder:

https://github.com/paradigmxyz/reth/blob/a0a2f357b1241e258d8f03ff90162cc0f46cfc6f/crates/payload/basic/src/lib.rs#L792-L792

it would be nice if we would have a type that supports two kinds of builders:

```rust
struct PayloadBuilderStack<L,R> {}
```

this way we could easily integrate multiple builder types, e.g. rpc pending block _and_ regular CL

**Comment by tolu0x** [comment]
@mattsse assign me

**Comment by garwahl** [comment]
Hey @tolu0x are you still working on this? Happy to pick this up as I'm doing some work with `PayloadBuilder` at the moment

**Comment by tolu0x** [comment]
Hey @garwahl, i've not been able to complete my implementation due to my exams. If you can take it on, i'd be delighted to see your solution. LGTM
