### ISSUE TITLE
Extend PayloadBuilder Attributes with pool settings

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10437]
This type is the input type for the payload builder service

https://github.com/paradigmxyz/reth/blob/a0a2f357b1241e258d8f03ff90162cc0f46cfc6f/crates/ethereum/engine-primitives/src/payload.rs#L154-L154

currently, this uses all kinds of transactions from the pool
https://github.com/paradigmxyz/reth/blob/a0a2f357b1241e258d8f03ff90162cc0f46cfc6f/crates/ethereum/payload/src/lib.rs#L289-L292

it would be nice to provide the builder with additional settings that restricts what transactions can be included, for example if we want to reuse this for rpc then we want to exclude private transactions.

**Comment by greged93** [comment]
hey @mattsse, I'm down to try this
