### ISSUE TITLE
Extend BuiltPayload type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10436]
currently the BuiltPayload type returns the block:

https://github.com/paradigmxyz/reth/blob/a0a2f357b1241e258d8f03ff90162cc0f46cfc6f/crates/payload/primitives/src/traits.rs#L18-L20

ideally this type should be required to also serve the receipts

this would be required so that this can be reused in RPC

**Comment by malik672** [comment]
@mattsse how do i get the receipts for the payload?

**Comment by malik672** [comment]
@mattsse is this required for the optimism payload also?
