### ISSUE TITLE
Use `alloy_network::Network::ReceiptResponse` instead of `AnyTransactionReceipt` in RPC

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#10452]
### Describe the feature

Replace all usage of `AnyTransactionReceipt` in RPC with `<EthApiTypes::NetworkTypes as alloy_network::Network>::ReceiptResponse`.

https://github.com/paradigmxyz/reth/blob/7d8196e29ca8427f48f18516963a6a5c3356ef44/crates/rpc/rpc-eth-api/src/core.rs#L104-L109

Follow the pattern used for transaction, i.e. add another generic to `EthApi` trait for receipt

https://github.com/paradigmxyz/reth/blob/7d8196e29ca8427f48f18516963a6a5c3356ef44/crates/rpc/rpc-eth-api/src/core.rs#L46-L49

as such

```rust
pub trait EthApi<T: RpcObject, B: RpcObject, R: RpcObject> {
```

**Comment by malik672** [comment]
@emhane assign me

**Comment by malik672** [comment]
@emhane should I restrict the changes to the core.rs file alone or I should make the changes in other files where EthApi is used

**Comment by emhane** [comment]
> @emhane should I restrict the changes to the core.rs file alone or I should make the changes in other files where EthApi is used

try and restrict it to _core.rs_ first is a good idea. this should be possible by constraining the `alloy_network::Network::ReceiptResponse` type to concrete type for now, as such
```rust
/// Network specific `eth` API types.
pub trait EthApiTypes: Send + Sync + Clone {
    /// Extension of [`EthApiError`], with network specific errors.
    type Error: Into<jsonrpsee_types::error::ErrorObject<'static>>
        + FromEthApiError
        + AsEthApiError
        + FromEvmError
        + Error
        + Send
        + Sync;
    /// Blockchain primitive types, specific to network, e.g. block and transaction.
    // todo: remove restriction `reth_rpc_types::Transaction`
    // todo: remove restriction `reth_rpc_types::AnyTransactionReceipt`
    type NetworkTypes: Network<TransactionResponse = Transaction, ReceiptResponse = AnyTransactionReceipt>;
}
```

**Comment by malik672** [comment]
@emhane I'm not really getting it, can I pull a draft so you can look at it
