### ISSUE TITLE
Remove constraint of hardcoded RPC tx type

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#10450]
### Describe the feature

Remove constraint that `alloy_network::Network::TransactionResponse` must be type `reth_rpc_types::Transaction`.

This depends on new alloy release, for example extending all `alloy_rpc_types_eth::SubscriptionResult` implementations from default `SubscriptionResult` to generic over transaction `SubscriptionResult<T>`.

https://github.com/paradigmxyz/reth/blob/7d8196e29ca8427f48f18516963a6a5c3356ef44/crates/rpc/rpc-eth-api/src/types.rs#L21-L23

**Comment by malik672** [comment]
@emhane assign me

**Comment by emhane** [comment]
appreciate the enthusiasm @malik672 , but this one is blocked, so won't assign anyone until it becomes unblocked

**Comment by malik672** [comment]
@nkysg nah, you do it

**Comment by emhane** [comment]
thanks for heads up @nkysg

**Comment by emhane** [comment]
closed by https://github.com/paradigmxyz/reth/pull/9774
