### ISSUE TITLE
Modify `can_serde_config` test to reduce maintenance burden

### ISSUE THREAD

**Issue by MegaRedHand** [paradigmxyz/reth#1046]
### Describe the bug

After some recent changes, the test fails with a message similar to:

```
thread 'config::tests::can_serde_config' panicked at 'called `Result::unwrap()` on an `Err` value: 
BadTomlData(Error { inner: ErrorInner { kind: Custom, line: Some(40), col: 0, at: Some(792), 
message: "missing field `downloader_batch_size`", key: ["stages", "headers"] } })', 
crates/staged-sync/src/config.rs:156:51
```

This can be solved by deleting the config file manually, but it can reappear when changing configuration structs (for example, adding an attribute to `BodiesConfig`). Because of this, I propose changing the test to check if the file exists and deleting it before loading. This should fix this for once and for all.

### Steps to reproduce

1. delete one of the lines in the file (e.g. `commit_threshold = 10000`)

- Linux: `$XDG_DATA_HOME/rs.test/default-config.toml` or `$HOME/.local/share/rs.test/default-config.toml`
- Windows: `{FOLDERID_RoamingAppData}/rs.test/default-config.toml`
- macOS: `$HOME/Library/Application Support/rs.test/default-config.toml`

2. run the tests with `cargo test --all --all-features`

### What version/commit are you on?

d6bd075e7bfb37339bea2caafeef303d2bfcedd5

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by fkrause98** [comment]
I can work on this.
