### ISSUE TITLE
Make `reth_chainspec::ChainSpec` generic over hard fork

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#10468]
### Describe the feature

Make `ChainSpec` generic over the hard fork type. This eventually allows removing optimism feature from `reth-chainspec`.

Many OP feature gated methods on `ChainSpec`, can be sunk a level to hard forks.

### Additional context

Makes sense to re-model `OptimismHardfork` type to have a variant `OptimismHardfork::Eth(EthereumHardfork)`, to reuse logic implemented on `EthereumHardfork`.

_No response_

**Comment by ShantelPeters** [comment]
@emhane please assign me

**Comment by emhane** [comment]
> @emhane please assign me

alright @ShantelPeters , pls stick to only addressing following in the pr
> Make ChainSpec generic over the hard fork type. This eventually allows removing optimism feature from reth-chainspec.

other tasks mentioned in description are better handled as separate issues but have been provided for context to help think about making ChainSpec generic over hard fork

**Comment by mattsse** [comment]
hmm, sceptical that this is something we want to do, so please hold off on this for now @ShantelPeters

**Comment by emhane** [comment]
helps construction of op chain spec type, avoiding redundant code
