### ISSUE TITLE
Remove special module handling for eth_callBundle

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10483]
### Describe the feature

when we introduced this we weren't sure if we should consider this part of the regular eth namespace and opted for an additional config:

https://github.com/paradigmxyz/reth/blob/603e39ab74509e0863fc023461a4c760fb2126d1/crates/rpc/rpc-server-types/src/module.rs#L258-L262

but now we can simply consider this part of the regular eth_ namespace and enable it by default because useful

## TODO
* remove `EthCallBundle` module and install ethcallbundle if `Eth` is enabled

**Comment by rutefig** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/reth).

### My background and how it can be leveraged
Working currently with another project in Rust in the Ethereum Ecossystem, I want to contribute more for meaningful projects on the Ecosystem.
