### ISSUE TITLE
Improve rpc error for nonce too low

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10498]
### Describe the feature

ref https://github.com/paradigmxyz/reth/issues/10464

the current error isn't very helpful: `nonce too low`

ideally we want:

> nonce too low: next nonce 72, tx nonce 71

the revm type even has this already:

```
    NonceTooLow {
        tx: u64,
        state: u64,
    },
```

so it's just a matter of integrating this in the rpc error:

https://github.com/paradigmxyz/reth/blob/8df9efd6ca745886a349d350011a354de56b0bef/crates/rpc/rpc-eth-types/src/error.rs#L265-L267

### Additional context

cc @ShantelPeters

_No response_

**Comment by i-sangh** [comment]
Hey mattsse!
Can I have a try solving this. 
Would be my first time contribution, so looking for some guidance around!

**Comment by mattsse** [comment]
cool, assigned,

if you're stuck, please open a draft pr and we can take it from there

**Comment by i-sangh** [comment]
Hey mattsse,
I have send a PR, I was receiving a message saying 
"Merging is blocked
Merging can be performed automatically with 1 approving review."
Don't know much about it, but for the issue #10498 tried my best!

**Comment by PanGan21** [comment]
Hi guys, I saw that this issue is still open and I thought to continue the work of #10464  since it is closed.
I added some part of it in #10711  pr. Please let me know what you think.

**Comment by mattsse** [comment]
thank you
