### ISSUE TITLE
Use TransactionInfo type for rpc transaction construction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10494]
### Describe the feature

these function accept the blockcontext/txinfo as input:

https://github.com/paradigmxyz/reth/blob/a7a9f9f3b349c7fd41bb3c7bb8e4d051fd63a4d6/crates/rpc/rpc-types-compat/src/transaction/mod.rs#L19-L22

https://github.com/paradigmxyz/reth/blob/a7a9f9f3b349c7fd41bb3c7bb8e4d051fd63a4d6/crates/rpc/rpc-types-compat/src/transaction/mod.rs#L35-L35

we have a type for this: `TransactionInfo`: https://github.com/alloy-rs/alloy/blob/8a06509c3f85885ecfab110af0819b354d794b68/crates/rpc-types-eth/src/transaction/common.rs#L10-L10

## TODO
* use that type instead of individual fields

**Comment by SkandaBhat** [comment]
Please assign @mattsse!
