### ISSUE TITLE
Move optimism rpc types to op-alloy

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10509]
### Describe the feature

we have a few optimism rpc types:

https://github.com/paradigmxyz/reth/blob/c788b6a585bbbd7ed92aabc42cb612a6a804daff/crates/optimism/rpc/src/api.rs#L12-L12

that should be moved to https://github.com/alloy-rs/op-alloy/tree/main/crates/rpc-types

## TODO
* move op rpc types to op-alloy

### Additional context

ref https://github.com/paradigmxyz/op-rs/pull/25

**Comment by Redidacove** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/reth).

### My background and how it can be leveraged
I am a student and into Ethereum for a while now participating in Ethereum as a permissionless fellow for implementation of EIP 7732 with potuz and terence as mentors and working on Prysm so can understand the issue well enough.

### How I plan on tackling this issue
It's simple refactoring problem just needs to open a pr in op-alloy after adding types in it and then another pr in reth after the first gets merged importing the given types.

**Comment by Redidacove** [comment]
@mattsse This will be closed by my pr which is currently blocked until next op-alloy release as  mentioned by @emhane
