### ISSUE TITLE
Extremely high churn of peers

### ISSUE THREAD

**Issue by jonasbostoen** [paradigmxyz/reth#1051]
### Describe the bug

I have been running 11 instances of reth over the last 24 hours, and unfortunately peering was still not easy. Here are the peer counts across that timeframe:

![image](https://user-images.githubusercontent.com/32879610/214817048-1943f175-0388-4a38-b340-eaa43a7332d9.png)
(Max peer count: 400, max outbound 3/4, max inbound 1/4)

Comparing that to geth, which can get up to 400 peers in about 6 hours (new node ID), this is very slow. I started collecting all sorts of metrics and one that immediately caught my attentention was the number of disconnects and their reasons. Looking at the graph below, we can see that we have an incredibly high amount of disconnects, specifically with the `None` reason:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/32879610/214818010-33ac58e3-1c62-4e45-8611-1e41f6686fcc.png">

Turns out that when we're the ones requesting a disconnect, the event that it registered is `none`, so it's definitely on our side. Digging into the logs I found that this happens in the transaction exchange mechanism. 

Peers send both full transaction messages and pooled transaction hashes as part of the gossip protocol. When we don't have those hashes in our txpool, we should request them. After running a peering connection for a while, we invariably run into timeouts on the req/resp model. These adaptible timeouts (https://github.com/paradigmxyz/reth/pull/789) result in reputation changes, and after just 4 timeout reputation changes, the peer gets banned and we disconnect:
```
2023-01-26T10:35:36.982095Z TRACE net::peers: applied reputation change repuation=-16384 banned=false
2023-01-26T10:35:36.983991Z TRACE net::peers: applied reputation change repuation=-32768 banned=false
2023-01-26T10:35:36.984112Z TRACE net::peers: applied reputation change repuation=-49152 banned=false
2023-01-26T10:35:36.985138Z TRACE net::peers: applied reputation change repuation=-65536 banned=true
```

I think we should either increase the timeouts or decrease the resulting reputation change, or else it's going to be hard to stay connected.

### Steps to reproduce

Run the reth p2p networking stack for long enough

### Platform(s)

Linux (x86)

### What version/commit are you on?

Latest main

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> When we don't have those hashes in our txpool, we should request them. 

they are useless during syncing, no? so imo we should not request them.

**Comment by jonasbostoen** [comment]
I should clarify that I'm running the reth p2p stack as a relay for a fully synced node, so in this case it should. Also when a reth full node is done syncing it will run into this issue as well

**Comment by mattsse** [comment]
> full node is done syncing it will run into this issue as well

yes, that's correct

thanks for the context, this is very useful.

So it looks like we're too aggressive with the timeout for transaction-related requests and how we punish missed timeouts.

we also want to reward good peers over time I think, for example we don't want to disconnect from a node that was response for a long time just because it missed a couple of requests in a row (perhaps due to heavy load etc..)

I guess we could also modify the weights for reputations if we're fully synced

The timeout function also needs some work I think.

cc @akirillo

**Comment by jonasbostoen** [comment]
I think the latency based reputation is a great idea, but just to give an example, this even happens for peers with which we have an extremely low rtt:

![image](https://user-images.githubusercontent.com/32879610/214826705-3ea0fb97-71f3-45a2-ae60-a2b86c7a1097.png)

In this example we have sub millisecond rtt latency to the peer and we're still getting timeouts. I think if we're going to punish timeouts here they should be punished very mildly. This probably also points to the fact that the dynamic timeout function is not ideal yet.

**Comment by mattsse** [comment]
> This probably also points to the fact that the dynamic timeout function is not ideal yet.

agree, will take a closer look at this, and yeah timeouts are too harsh.

we're also working on #908 . would appreciate your feedback there as well!

**Comment by jonasbostoen** [comment]
Will look into it!

**Comment by akirillo** [comment]
> So it looks like we're too aggressive with the timeout for transaction-related requests and how we punish missed timeouts.

Yeah, two quick thoughts here:
1. I mention this in #908, but AFAICT we use timeout, not RTT, to drop the peer. This isn't great because even if a peer's RTT goes down, timeout never does, so it can only get closer to being dropped this way. This is part of the refactor slated in #908.
2. It'd be helpful to have some context into the ongoing request when calculating timeout - e.g. be more lenient when requesting TXs as opposed to TX bodies

**Comment by akirillo** [comment]
> This isn't great because even if a peer's RTT goes down, timeout never does

Ah, have been interpreting it wrong, timeout is adaptive based on RTT (@jonasbostoen your graphs in #1054 are very helpful!)

**Comment by jonasbostoen** [comment]
@mattsse, disabling the timeouts did wonders for maintaining peers:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/32879610/215422576-d722b945-8fce-4605-8042-bbbb028827b4.png">

**Comment by mattsse** [comment]
we removed timeout reporting from inside the session via #1099 and increased minimum timeout #1078 

vote to close @jonasbostoen

**Comment by jonasbostoen** [comment]
Confirmed that the fixes work
