### ISSUE TITLE
Move `OptimismHardfork` to `reth-optimism-chainspec`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#10518]
### Describe the feature

Move `reth_ethereum_forks::OptimismHardfork` into new crate `reth-optimism-chainspec`

**Comment by ShantelPeters** [comment]
I’ll love to work on this

**Comment by emhane** [comment]
thanks @ShantelPeters, it's blocked rn though, so pls pick another issue until that label disappears!
