### ISSUE TITLE
Move function `reth_primitives::proofs::calculate_receipt_root_optimism` to `reth-optimism-ptimitves`.

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#10514]
### Describe the feature

Move function into new module _proofs.rs_ in `reth-optimism-primitives`, along with tests.

https://github.com/paradigmxyz/reth/blob/dfcfe8d27166124324ba907d487ab7c27163373d/crates/primitives/src/proofs.rs#L40-L71

**Comment by greged93** [comment]
@emhane can I take this one?

**Comment by mattsse** [comment]
I think this is taken care of by #10520
