### ISSUE TITLE
some metrics are missing or incompatible  when switching to new engine

### ISSUE THREAD

**Issue by yutianwu** [paradigmxyz/reth#10521]
### Describe the bug

For example, some metrics are missing or incompatible with the original grafana dashboard, for example, the canonical chain height.

<img width="719" alt="image" src="https://github.com/user-attachments/assets/0a1346bd-b84c-4fc4-9fca-250f539546fd">

Not sure if we need to add new panels or if there is an issue with the metrics.

### Steps to reproduce

1. restart the reth node with the new eingine
2. check the grafana dashboard

### Node logs

```text
na
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

v1.0.5

### What database version are you on?

Current database version: 2
Local database version: 2

### Which chain / network are you on?

opBNB

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by ShantelPeters** [comment]
Can I please be assigned to this issue ?
