### ISSUE TITLE
Update dynamic timeout calculation

### ISSUE THREAD

**Issue by jonasbostoen** [paradigmxyz/reth#1054]
### Describe the feature

Ref: https://github.com/paradigmxyz/reth/issues/1051

I've done some calculations with the current dynamic timeout parameters and they seem a bit tight:
https://github.com/paradigmxyz/reth/blob/f9de425ad895279c24a72977ffd0c6973afaf90e/crates/net/network/src/session/active.rs#L80-L89

With these parameters we very quickly come close the the average RTT of the session (params in title):

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/32879610/214857651-332b793c-1cda-4717-92c6-0feb1cf54925.png">

I propose increasing `TIMEOUT_SCALING` to 10, to make sure we never come too close to the average RTT. (10 times the average RTT). `SAMPLE_IMPACT` at 0.1 looks good to me. Here is what that would look like:

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/32879610/214858650-81d19b41-b9d7-43ab-9a69-a3b14e7901a0.png">

We might also have to decrease the reputation decrease on these timeouts, I'll test that as well.
Will open PR after feedback!

cc @mattsse

**Comment by gakonst** [comment]
Closed in https://github.com/paradigmxyz/reth/pull/1078
