### ISSUE TITLE
Create witness comparison tool

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#10549]
ref https://github.com/paradigmxyz/reth/issues/10425

If we want to compare witness output from a "bad" node, from that of a "good" node, we need a way to easily compare witnesses.

This should take the output of `debug_executionWitness` (or the variant with preimages), and output a nice, human readable diff.

**Comment by 0xalpharush** [comment]
Prior art https://github.com/0xPolygonZero/zk_evm/tree/develop/mpt_trie/src/debug_tools
