### ISSUE TITLE
Make `remove_before` finalized-aware

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#10558]
Currently `remove_before` prunes all blocks below a specific block number:
https://github.com/paradigmxyz/reth/blob/498ced8be9d1340a9a79f2dbd84e676dc2381888/crates/engine/tree/src/tree/mod.rs#L179-L205

This currently works by iterating through each block number we need to remove, cleaning up each block associated with that number from the `TreeState` maps.

If we have a sidechain, this method will remove the root of the sidechain. Instead, this method needs to take two arguments:
* `upper_bound`, and
* `finalized_hash`, which will be an `Option<B256>` (in case there is no finalized hash)

This method needs to remove in the following way:
* If the block is part of the canonical chain, and has a block number `<= upper_bound`, remove the block
* If the block is _not_ part of the canonical chain, is lower than the finalized hash, and has a block number `<= upper_bound`, remove it. If the root of the sidechain is lower than the finalized hash, then we need to remove the entire fork sidechain.

**Comment by nabarun-19** [comment]
Can i do this?
