### ISSUE TITLE
Lockfile tests failing

### ISSUE THREAD

**Issue by emnul** [paradigmxyz/reth#10567]
### Describe the bug

The following tests in `lockfile::tests::test_drop_lock` and `lockfile::tests::test_lock` in crates/storage/db/src/lockfile.rs are failing.

### Steps to reproduce

Run `make test` on `main` branch. Observe the following error:
```
failures:

---- lockfile::tests::test_drop_lock stdout ----
thread 'lockfile::tests::test_drop_lock' panicked at crates/storage/db/src/lockfile.rs:198:9:
assertion failed: lock_file.exists()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- lockfile::tests::test_lock stdout ----
thread 'lockfile::tests::test_lock' panicked at crates/storage/db/src/lockfile.rs:153:54:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }


failures:
    lockfile::tests::test_drop_lock
    lockfile::tests::test_lock

test result: FAILED. 39 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.65s
```

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

1.0.5-dev

### What database version are you on?

N/A

### Which chain / network are you on?

N/A

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tcoratger** [comment]
I think, at least for `test_drop_lock `, this is because of the following line:

https://github.com/paradigmxyz/reth/blob/b1d6e27e3f147678243423a35593c8357a6dabaa/crates/storage/db/src/lockfile.rs#L37-L38

as we don't use 

```rust
Ok(Self(Arc::new(StorageLockInner::new(file_path)?)))
```

I imagine because of the comment (ef tests overload) so that it does not creates the lock file/writes into it.

**Comment by emhane** [comment]
seems like locally there is issues with clean up, possibly also with concurrency running different tests @Rjected

**Comment by emhane** [comment]
we should probably re-write the `make test` command to run nextest instead @mattsse ? ref https://github.com/paradigmxyz/reth/pull/9403

**Comment by Thegaram** [comment]
It seems that the issue is related to this PR: https://github.com/paradigmxyz/reth/pull/8753

With this change in [testing/ef-tests/Cargo.toml](https://github.com/paradigmxyz/reth/blob/main/testing/ef-tests/Cargo.toml) `cargo test --workspace` passes:
```diff
- reth-db = { workspace = true, features = ["mdbx", "test-utils", "disable-lock"] }
+ reth-db = { workspace = true, features = ["mdbx", "test-utils"] }
```
