### ISSUE TITLE
split validate_block_pre_execution into hardfork specific functions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10568]
### Describe the feature

we currently apply all checks in a single function

https://github.com/paradigmxyz/reth/blob/7df7bc2c1a83df550c24e3f4a26c067c4690b9eb/crates/consensus/common/src/validation.rs#L40-L49

ideally all those hardfork checks are available as function and `validate_block_pre_execution` would then call all of them

## TODO
* extract hardfork checks into separate functions:

https://github.com/paradigmxyz/reth/blob/7df7bc2c1a83df550c24e3f4a26c067c4690b9eb/crates/consensus/common/src/validation.rs#L63-L102

**Comment by willco-1** [comment]
feel free to assign this to me!
