### ISSUE TITLE
Make `mmap` size requested by `libmdbx` configurable

### ISSUE THREAD

**Issue by guidanoli** [paradigmxyz/reth#10585]
### Describe the feature

I would like there to be a configuration for changing the amount of memory requested upfront by `libmdbx` through `mmap`. It is 4TB as of now.

### Additional context

Currently, `reth` requests 4TB of memory with `mmap`, which fails in Linux environments compiled with `no4lvl` boot argument. I can see why that would be necessary for production, but I only need to run `reth` in dev mode, and wouldn't require as much memory.

My use case is running `reth` in a deterministic RISC-V virtual machine. The application name is [Bug Buster](https://github.com/crypto-bug-hunters/bug-buster).

**Comment by guidanoli** [comment]
@shekhirin Hey!
It would be good if the step was also configurable.
From what I understand from the code base, it's at 4 GB.
https://github.com/paradigmxyz/reth/blob/main/crates/storage/db/src/implementation/mdbx/mod.rs#L281-L289

**Comment by guidanoli** [comment]
I'm running reth in a really constrained environment. In my use case, I would set the total size to something like 8 MB, and the growth step to something like 4 KB.

**Comment by mattsse** [comment]
I think we can make this work, sorry for not bumping prio on this.

need to track a few other things for this first before we can expose via cli

**Comment by mattsse** [comment]
marking this as completed because this can now be configured
