### ISSUE TITLE
Monitor discv4 packets

### ISSUE THREAD

**Issue by akirillo** [paradigmxyz/reth#1059]
### Describe the feature

It would be nice to have a sense of discv4 traffic exposed via `metrics`.
Proposed approach here is to increment a counter every time a packet is read over the UDP socket exposed for discv4.

### Additional context

A `MeteredSender` was developed in #726, but is yet unused in the codebase.
An implementation path worth considering here is to adapt the `MeteredSender` to work for anything that implements `Sink`, and either extend it for anything that implements `Stream` or have another metrics type similar to `MeteredSender` for this.

Then, we could convert `UdpSocket`s into `UdpFramed`s which implement `Sink` and `Stream` & tally packets that way.

**Comment by onbjerg** [comment]
Still relevant @mattsse?

**Comment by mattsse** [comment]
no longer relevant, has been stable since
