### ISSUE TITLE
Prune section outdated

### ISSUE THREAD

**Issue by eiabea** [paradigmxyz/reth#10645]
### Describe the change

Currently the `[prune]` section uses `parts`. This got renamed/refactored to `segments`. Using `parts` results in a crash at startup

### Additional context

https://github.com/paradigmxyz/reth/blob/main/book/run/config.md#example-of-the-custom-pruning-configuration

**Comment by GROOOOAAAARK** [comment]
Hi!

If this issue is still available I'd like to apply to it.

I'm gonna check the reference and apply the needed changes on the ˋprune` section
