### ISSUE TITLE
Update generic name in payload crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10663]
### Describe the feature

previously this generic was bound to `EngineTypes`, hence the `Engine:` 

this is no longer the case and we should update the generics to just `T: PayloadTypes`

https://github.com/paradigmxyz/reth/blob/d58cf538500288af27e7e8d0303be7dbd56aff39/crates/payload/builder/src/service.rs#L34-L34

## TODO
* replace `Engine: PayloadTypes` with `T: PayloadTypes`

**Comment by malik672** [comment]
@mattsse assign me
