### ISSUE TITLE
op-reth syncing Optimism mainnet error

### ISSUE THREAD

**Issue by xivanc** [paradigmxyz/reth#10662]
### Describe the bug

I try to sync OP mainnet following this guide https://reth.rs/run/sync-op-mainnet.html#1-import-blocks , during the pprocess I get several errors.

### Steps to reproduce

following steps in this guide https://reth.rs/run/sync-op-mainnet.html

### Node logs

```text
importing blocks:


2024-09-02T16:20:41.149243Z  INFO Finished stage pipeline_stages=5/5 stage=Finish checkpoint=1166777 target=1166777
2024-09-02T16:20:50.609533Z  INFO Importing chain file chunk
2024-09-02T16:20:50.619352Z  INFO Chain file chunk read
Error: unable to import non canonical blocks

Location:
    /project/crates/optimism/cli/src/commands/build_pipeline.rs:42:9

```

importing receipts:

```
INFO Importing receipt file chunk first_receipts_block=104896808 total_receipts_chunk=338255
2024-09-02T12:51:46.561079Z ERROR Receipts were partially imported total_decoded_receipts=105235062 total_imported_receipts=1666771 total_filtered_out_dup_txns=6
2024-09-02T12:51:46.561093Z ERROR Receipts inconsistent with transactions total_imported_receipts=1666771 total_imported_txns=1166772
2024-09-02T12:51:46.561099Z ERROR Height of receipts inconsistent with transactions highest_block_receipts=105235062 highest_block_transactions=1166777
2024-09-02T12:51:46.561104Z  INFO Receipt file imported total_imported_receipts=1666771 total_decoded_receipts=105235062 total_filtered_out_dup_txns=6
```

syncing to the --debug.tip 0xefa00f071a2ce2b94b446654a2a46049647f8dab94e485c1065f7c4008638079

```

reth-optimism-node-reth-1  | 2024-09-02T16:04:24.741259Z ERROR Stage encountered a fatal error: database integrity error occurred: nippy jar error: failed to open file "/root/.local/share/reth/optimism/static_files/static_file_receipts_1000000_1499999.conf": No such file or directory (os error 2) stage=Execution
reth-optimism-node-reth-1  | 2024-09-02T16:04:24.741343Z ERROR shutting down due to error
reth-optimism-node-reth-1  | Error: database integrity error occurred: nippy jar error: failed to open file "/root/.local/share/reth/optimism/static_files/static_file_receipts_1000000_1499999.conf": No such file or directory (os error 2)
reth-optimism-node-reth-1  |
reth-optimism-node-reth-1  |
reth-optimism-node-reth-1  | Caused by:
reth-optimism-node-reth-1  |     nippy jar error: failed to open file "/root/.local/share/reth/optimism/static_files/static_file_receipts_1000000_1499999.conf": No such file or directory (os error 2)
reth-optimism-node-reth-1  |
reth-optimism-node-reth-1  |
reth-optimism-node-reth-1  | Location:
reth-optimism-node-reth-1  |     /project/crates/node/builder/src/launch/mod.rs:443:28
```
```


### Platform(s)

Linux (x86)

### What version/commit are you on?

op-reth:v1.0.6

### What database version are you on?

Current database version: 2
Local database version: 2

### Which chain / network are you on?

--chain optimism

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by xivanc** [comment]
this issue is possibly related to [this one ](https://github.com/paradigmxyz/reth/issues/10580)

**Comment by emhane** [comment]
haven't verified myself, but could be that the import receipts command works at this commit 6ddba28d1. note that receipts must be exported starting from block 1 to bedrock block, not from genesis block. @xivanc

**Comment by xivanc** [comment]
> note that receipts must be exported starting from block 1 to bedrock block, not from genesis block. @xivanc

And what about blocks, do they need to be exported as well from 1 or from 0?

Thank you.

**Comment by emhane** [comment]
import receipts solved by https://github.com/paradigmxyz/reth/pull/11216. pls re-open the issue if it still doesn't work for you.

**Comment by xivanc** [comment]
I was able to successfully upload the blocks, receipts and state, then synchronised to the latest OP mainnet block. But when I try to fetch pre-bedrock receipts or use debug trace methods with pre-bedrock block numbers, I get errors. 
(fyi `eth_getBlockByNumber` works fine even for pre-bedrock block numbers)

examples:
1)
**request:**
`curl -H "Content-type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockReceipts","params":["0x1"],"id":1}' http:/my_reth_endpoint`
**result**
`{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"could not get L1 block info from L2 block: \"unexpected l1 block info tx calldata length found\""}}`

2)
**request**
`curl -H "Content-type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"debug_traceBlockByHash","params":["0xbee7192e575af30420cae0c7776304ac196077ee72b048970549e4f08e875453", {"tracer": "callTracer"}],"id":1}' http:/my_reth_endpoint`
**result**
`{"jsonrpc":"2.0","id":1,"error":{"code":-32003,"message":"nonce too high"}}`

**Comment by xivanc** [comment]
@emhane 

I was able to successfully upload the blocks, receipts and state, then synchronised to the latest OP mainnet block without further issues. But when I try to fetch pre-bedrock receipts or use debug trace methods with pre-bedrock block numbers, I get errors. 
(fyi some methods like`eth_getBlockByNumber` works fine even for pre-bedrock block numbers)

examples:
1)
**request:**
`curl -H "Content-type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockReceipts","params":["0x1"],"id":1}' http:/my_reth_endpoint`
**result**
`{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"could not get L1 block info from L2 block: \"unexpected l1 block info tx calldata length found\""}}`

2)
**request**
`curl -H "Content-type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"debug_traceBlockByHash","params":["0xbee7192e575af30420cae0c7776304ac196077ee72b048970549e4f08e875453", {"tracer": "callTracer"}],"id":1}' http:/my_reth_endpoint`
**result**
`{"jsonrpc":"2.0","id":1,"error":{"code":-32003,"message":"nonce too high"}}`

**Comment by mattsse** [comment]
right, we don't have any pre-bedrock checks, hence the failing eth_getBlockReceipts

tracing pre-bedrock is not possible because we only have the state at the transition block

**Comment by xivanc** [comment]
Ahh ok, I was not aware of that. So not all standard Ethereum methods (and non-standard debug methods) work on pre-bedrock data?

**Comment by mattsse** [comment]
anything that requires state at a specific pre bedrock block won't work, like tracing or anything that accepts a BlockId
