### ISSUE TITLE
Return executedBlock in ethereum payloadbuilder

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10715]
### Describe the feature

just like https://github.com/paradigmxyz/reth/pull/10162

but for the eth payload builder

https://github.com/paradigmxyz/reth/blob/98b214f63dcbe11a357ec85532306c3756552eba/crates/ethereum/payload/src/lib.rs#L268-L276

**Comment by estensen** [comment]
pls assign!
