### ISSUE TITLE
Add dev ChainOrchestrator / Service

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10714]
### Describe the feature

for #7131 we need dev version of 

https://github.com/paradigmxyz/reth/blob/98b214f63dcbe11a357ec85532306c3756552eba/crates/node/builder/src/launch/engine.rs#L208-L223

the thing that drives the chain forward, for dev mode, this is similar to the 

https://github.com/paradigmxyz/reth/blob/98b214f63dcbe11a357ec85532306c3756552eba/crates/consensus/auto-seal/src/task.rs#L24-L24

but acts similar to:

https://github.com/paradigmxyz/reth/blob/98b214f63dcbe11a357ec85532306c3756552eba/crates/engine/tree/src/tree/mod.rs#L402-L402 or rather the persistence stuff

like a task that polls a local payload builder based on some mining mode and appends a new block

All of this should go into a new crate under engine, this should reuse the payload builder stack and not roll custom block building like the auto-seal-consensus does

**Comment by greged93** [comment]
@mattsse can I take this?
