### ISSUE TITLE
Optimize peers for mempool transactions or sync (--peer-mode flag)

### ISSUE THREAD

**Issue by NicolasWent** [paradigmxyz/reth#10716]
### Describe the feature

Hello,

I recently realized that my node is not efficient when it comes to capturing mempool transactions.

Someone on Telegram suggested that I should try and experiment with multiple peers so that I can find the one that propagate me the transactions the fastest.

My suggestion here would be to make a feature that would automatically search and select the best peers to get mempool transactions the fastest and the most amount of them.

### Additional context

Maybe a flag like: `--peer-mode` could be great.

It would look like this:
WHen you first sync your node, you would do:
--peer-mode=optimize-sync

Once your node is synced you can switch to:
--peer-mode=optimize-mempool

**Comment by mattsse** [comment]
could you please elaborate on what these modes are supposed to do?

WHen you first sync your node, you would do:
--peer-mode=optimize-sync

Once your node is synced you can switch to:
--peer-mode=optimize-mempool
