### ISSUE TITLE
`reth-network::it requests::test_get_header` is flaky

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1071]
### Describe the bug

Similar to #911

When running tests locally, `test_get_header` fails, but on CI it passes.

### Steps to reproduce

Running the tests locally should reproduce the error: `cargo nextest run`
What's interesting here is that `cargo test --workspace --all-features` does not reproduce the error.

### Node logs

```text
Canceling due to test failure: 9 tests still running
        PASS [   0.036s]                             reth-codecs tests::fuzz_test_TestStruct_fuzz::auto_generate
        FAIL [   0.579s]                        reth-network::it requests::test_get_header

--- STDOUT:                                     reth-network::it requests::test_get_header ---

running 1 test
test requests::test_get_header ... FAILED

failures:

failures:
    requests::test_get_header

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 12 filtered out; finished in 0.57s


--- STDERR:                                     reth-network::it requests::test_get_header ---
thread 'requests::test_get_header' panicked at 'assertion failed: res.is_ok()', crates/net/network/tests/it/requests.rs:116:9
stack backtrace:
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by rakita** [comment]
Try to enable logs I have seen that it get triggered a little bit more often with `RUST_LOG=trace` but didn't run it a lot to be conclusive.
