### ISSUE TITLE
Move more optimism receipt checks to optimism crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10713]
### Describe the feature

with #10520 we moved some optimism receipt root functions to optimism consensus crate

we still have some in primitives that should be moved:

https://github.com/paradigmxyz/reth/blob/98b214f63dcbe11a357ec85532306c3756552eba/crates/primitives/src/proofs.rs#L90-L91

this has some side-effects on other code, mainly:

https://github.com/paradigmxyz/reth/blob/98b214f63dcbe11a357ec85532306c3756552eba/crates/primitives/src/receipt.rs#L112-L114

https://github.com/paradigmxyz/reth/blob/98b214f63dcbe11a357ec85532306c3756552eba/crates/evm/execution-types/src/execution_outcome.rs#L207-L208

those should be moved as well, and perhaps converted to a trait

**Comment by garwahl** [comment]
I can take this @mattsse

**Comment by garwahl** [comment]
Hey @mattsse where should `Receipts::optimism_root_slow()` be moved to? Do you have a preference?

**Comment by garwahl** [comment]
Appears blocked by https://github.com/paradigmxyz/reth/issues/7649 according to https://github.com/paradigmxyz/reth/pull/10932#issuecomment-2359582465cc @emhane

**Comment by klkvr** [comment]
didn't notice deeper discussion here before opening https://github.com/paradigmxyz/reth/pull/11230, happy to keep this open, PR pretty much just moves things around
