### ISSUE TITLE
remove load_trusted_setup_from_bytes 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10718]
## TODO
1. remove
https://github.com/paradigmxyz/reth/blob/c267c1caf79b8ecbc6e93214ec350ab651d3f20a/crates/primitives/src/constants/eip4844.rs#L18-L18

this isn't used and also not useful because we assume if you need different points you have them as constants

**Comment by estensen** [comment]
I can take this one ✋🏻
