### ISSUE TITLE
Improve Genesis to Chainspec conversion

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10725]
### Describe the feature

this from impl is super messy and lacks test coverage for json -> chainspec

https://github.com/paradigmxyz/reth/blob/7fd16914a43551952ce1dfa6e9a86f0c75ec1825/crates/chainspec/src/spec.rs#L597-L598

ref https://github.com/paradigmxyz/reth/pull/10724

first, this function should be split into two, one for op one for regular eth, ideally with some additional tests.

**Comment by greged93** [comment]
hey @mattsse, down to clean and add some test coverage
