### ISSUE TITLE
Make ConfigureEvm Independent of consensus types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10746]
Currently 

https://github.com/paradigmxyz/reth/blob/3ec5d373c10577efa3cbd4f313fafd68b15c728d/crates/evm/src/lib.rs#L112-L112

requires Header and Transaction as input types, those should be associated types instead

**Comment by emhane** [comment]
we are better of unifying these as one associated type `type Primitives: NodePrimitives`
