### ISSUE TITLE
reth-primitives crate import audit

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10749]
### Describe the feature

reth-primitives re-exports a ton of stuff.
we're making significant changes to primitive types and should do a cleanup pass first, shifting imports to the re-exported crates:
* reth-primitive-traits (Account,Header..)
* alloy-primitives

## TODO
* replace reth-primitive imports where possible

starting with
- [ ] reth-trie (import from alloy-primitives directly) https://github.com/paradigmxyz/reth/blob/3ec5d373c10577efa3cbd4f313fafd68b15c728d/crates/trie/trie/Cargo.toml#L2-L2

**Comment by Constantine234** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/reth).

### My background and how it can be leveraged
I am a python programmer and my skills and talents will be of great help in this project thank you 

### How I plan on tackling this issue
I can use Python programming to create the import aspect of this project

**Comment by stevencartavia** [comment]
Hi, can I work on this?

**Comment by mattsse** [comment]
marking this as completed now, I think we're good on this now
