### ISSUE TITLE
Update docs for history indexing stages

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#1074]
### Describe the feature

[`IndexAccountHistoryStage`](https://github.com/paradigmxyz/reth/blob/main/crates/stages/src/stages/index_account_history.rs) and [`IndexStorageHistoryStage`](https://github.com/paradigmxyz/reth/blob/main/crates/stages/src/stages/index_storage_history.rs) have incorrect docs that should be updated to reflect:

1. What the stages do
2. What tables they touch (both inputs and outputs)

**Comment by rakita** [comment]
fixed https://github.com/paradigmxyz/reth/pull/1070
