### ISSUE TITLE
use alloy `Signature` type

### ISSUE THREAD

**Issue by klkvr** [paradigmxyz/reth#10750]
### Describe the feature

with https://github.com/alloy-rs/core/pull/719 we can now use `Signature` to store arbitrary signatures.

first step might be to replace `SignatureWithParity`: https://github.com/paradigmxyz/reth/blob/3ec5d373c10577efa3cbd4f313fafd68b15c728d/crates/primitives/src/transaction/signature.rs#L231

and after that `Signature`:
https://github.com/paradigmxyz/reth/blob/3ec5d373c10577efa3cbd4f313fafd68b15c728d/crates/primitives/src/transaction/signature.rs#L30

we'll need to make sure to correctly implement decoding. right now for legacy transactions we expect `v` to be 27 or 28, however alloy's signature will succesfully decode any of 0, 1, 27 or 28 which is incorrect rlp

**Comment by leruaa** [comment]
I can take this on.
