### ISSUE TITLE
Consensus crate refactor

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#1075]
### Describe the feature

The consensus crate needs some love:

- [ ] `BeaconConsensus` should be moved to its own module
- [ ] The `Consensus` trait should be in `consensus.rs`
- [ ] The `engine` module should be moved into the RPC crates

On that last one: the Engine API should have a way to communicate with `BeaconConsensus`, since the engine API (on the RPC side) needs to send fork choice updates to `BeaconConsensus` using `BeaconConsensus::notify_fork_choice_state`. Ideally, the engine API module on the RPC side should just be given the sender side of the `ForkchoiceState` watcher channel.

The `engine` module also has some unfortunate naming:

1. The main struct is called `EthConsensusEngine` which is not descriptive: it is just the engine API in the RPC.
2. The trait (which I don't think is needed?) in the `engine` module is called `ConsensusEngine` which is confusing since we already have a trait for consensus engines called `Consensus`

**Comment by rkrasiuk** [comment]
@onbjerg wdym by `The Consensus trait should be in consensus.rs`? do you want to move it to `consensus` module?

**Comment by onbjerg** [comment]
There is a `consensus.rs` file in the consenus crate, but it contains `BeaconConsensus` and not the trait itself, which doesn't make a lot of sense to me

**Comment by rkrasiuk** [comment]
uderstood. i'll move `BeaconConsensus`, but `Consensus` trait should stay in `reth-interfaces` imo

**Comment by rkrasiuk** [comment]
extracted the note regarding beacon consensus forchoice state to a separate point in scope of `BeaconConsensus` builder #1093
