### ISSUE TITLE
Rename downloaders

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#1076]
### Describe the feature

The downloaders have not been renamed since their refactor. Both of them should get new names which reflect what data they download and that they download over the network.

The reason for the network distinction is that a file-backed "downloader" will be implemented as part of #877

**Comment by mattsse** [comment]
supportive, also not happy with the naming rn

**Comment by leruaa** [comment]
I can take this on

**Comment by leruaa** [comment]
First let's summarize what we have now (docs copied below):

`HeaderDownloader` (trait)
---
A downloader capable of fetching and yielding block headers.

A downloader represents a distinct strategy for submitting requests to download block headers,
while a `HeadersClient` represents a client capable of fulfilling these requests.

A `HeaderDownloader` is a `Stream` that returns batches for headers.

`LinearDownloader` (impl)
---
Downloads headers concurrently.

This `HeaderDownloader` downloads headers using the configured `HeadersClient`.
Headers can be requested by hash or block number and take a `limit` parameter. This downloader
tries to fill the gap between the local head of the node and the chain tip by issuing multiple
requests at a time but yielding them in batches on `Stream::poll_next`.

*Note:* This downloader downloads in reverse, see also `HeadersDirection::Falling`, this means
the batches of headers that this downloader yields will start at the chain tip and move towards
the local head: falling block numbers.

`BodyDownloader` (trait)
---
A downloader capable of fetching and yielding block bodies from block headers.

A downloader represents a distinct strategy for submitting requests to download block bodies,
while a `BodiesClient` represents a client capable of
fulfilling these requests.

`ConcurrentDownloader` (impl)
---
Downloads bodies in batches.

All blocks in a batch are fetched at the same time.

_to be continued..._

**Comment by gakonst** [comment]
Let's just call it `ReverseHeadersDownloader` and `BodiesDownloader`. And we'll call any forward downloaders we implement in the future `ForwardHeadersDownloader` or something.
