### ISSUE TITLE
Promote Rpc to a node component

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10769]
this part is slightly confusing:

https://github.com/paradigmxyz/reth/blob/e7defb23345491297f35865b135ed03b29abfb5b/crates/node/api/src/node.rs#L94-L110

this is more like a helper trait to create the ethapi component.

atm the rpc is not stateful:

https://github.com/paradigmxyz/reth/blob/e7defb23345491297f35865b135ed03b29abfb5b/crates/ethereum/node/src/node.rs#L76-L82

we should make this stateful similar to a `trait RpcBuilder`, like we do with:

https://github.com/paradigmxyz/reth/blob/e7defb23345491297f35865b135ed03b29abfb5b/crates/ethereum/node/src/node.rs#L89-L96

this way the rpc setup can be customized entirely, not only the ethapi part.

this also allows us to separate engine server setup from regular rpc.

First we can make the Addons stateful

**Comment by emhane** [comment]
ref https://github.com/paradigmxyz/reth/issues/8987

**Comment by mattsse** [comment]
with #11532 we now have this
