### ISSUE TITLE
Move BlobAndProofV1 to alloy_eips 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10788]
### Describe the feature

for convenience this type `BlobAndProofV1`

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-types/src/lib.rs#L69-L69 blocked by 

should be moved to alloy_eips crate blocked by https://github.com/paradigmxyz/reth/pull/9723

for blob serialization we can use

https://github.com/alloy-rs/alloy/blob/4492c25f1a666881d18367dc47d0040fc05b17ae/crates/rpc-types-beacon/src/sidecar.rs#L104-L114

and also move to eips crate

**Comment by mvares** [comment]
@mattsse, shouldn't this issue be moved to the alloy repository?

**Comment by mattsse** [comment]
yeah, but we also need to use it here once release, so doesn't really matter
