### ISSUE TITLE
Create guide on how to add and update grafana panels

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#10794]
It's extremely easy to add new metrics (example: https://github.com/paradigmxyz/reth/pull/10728), and it's also generally very useful.

However, we often have grafana panels that become out of date, or we add new metrics without adding panels, which hurts observability for us, and for users.

To add to this, the grafana panel json objects have lots of different fields that are usually generated, making it difficult to contribute to the dashboard by manually editing the dashboard json.

The recommended way, then, is to use the grafana GUI to create new panels. Creating new panels is fairly easy as long as there is a grafana instance running! This has a few problems however:
* The workflow for setting up a reth grafana instance is undocumented
* It's not typically clear to contributors, how they can turn an updated panel into a PR that updates the `overview.json`
  * Proper instructions for exporting an updated panel are needed

We need to create a small tutorial on how to add panels, with the following details:
1. How to set up a grafana instance, assuming a node with the metrics is running
2. How to add a panel using the GUI, and visualize a new metric
3. How to export the panel and prepare a PR

**Comment by 0xkrane** [comment]
can take this on

**Comment by Rjected** [comment]
@0xkrane assigned!

**Comment by greged93** [comment]
@Rjected let me know if I can take over

**Comment by Rjected** [comment]
@greged93 assigned!
