### ISSUE TITLE
Hi there what is the main different between OP-Reth and Reth?

### ISSUE THREAD

**Issue by AJStonewee** [paradigmxyz/reth#10811]
### Describe the feature

Hi there what is the main different between OP-Reth and Reth?

**Comment by Rjected** [comment]
Hi, the op-reth binary runs the L2 execution layer client for optimism chains, and the reth binary runs the L1 execution layer client. See more here: https://reth.rs/run/optimism.html

Also, usually issues are for bugs and feature requests, not general questions. Feel free to post questions in either our telegram chat (linked in the README), or in our discussion section: https://github.com/paradigmxyz/reth/discussions
