### ISSUE TITLE
Make block download metric more accurate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10816]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/5614a0260a75936eec36636e26db500917d2010e/crates/engine/tree/src/download.rs#L164-L167

blocks can either be downloaded as single blocks or as range of blocks:

https://github.com/paradigmxyz/reth/blob/5614a0260a75936eec36636e26db500917d2010e/crates/engine/tree/src/download.rs#L59-L62

this update function should first count all the blocks, this is
len(inflight_full_block_requests) + inflight_block_range_requests.iter().map(|r|r.count).sum()

https://github.com/paradigmxyz/reth/blob/5614a0260a75936eec36636e26db500917d2010e/crates/net/p2p/src/full_block.rs#L375-L375

**Comment by stevencartavia** [comment]
Hi @mattsse, can I work on this?

**Comment by diegoTech14** [comment]
Hey, @droserasprout, I would love to help with this issue, you can check my OD profile here: https://app.onlydust.com/u/diegoTech14

**Comment by diegoTech14** [comment]
Hey, @mattsse, I would love to help with this issue, you can check my OD profile here: https://app.onlydust.com/u/diegoTech14

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/reth).

### My background and how it can be leveraged
Given my background, I believe I'm well-suited to handle this project effectively. I’ve been working in blockchain development for over 4 years, building on a wide range of chains—both EVM-compatible like CELO, BSC, and Polygon, as well as non-EVM chains such as NEAR and Tezos.

In addition to blockchain work, I’ve also gained significant experience in Rust development, working on projects that involve creating efficient, secure systems. I’ve used Rust to build robust, high-performance applications that are optimized for blockchain environments.

Whether it's managing on-chain interactions, building with Rust, or ensuring smooth protocol integration, I’m confident in my ability to deliver a solution that’s both reliable and scalable.

### How I plan on tackling this issue
Step by step approach:

1. Understand the Current System by reviewing the current block download metric implementation and understanding the block synchronization process.

2. Define Metric Improvements by identifying areas to improve accuracy (e.g., download speed, retries) and specifying new metrics to track (e.g., download time, peer performance).

3. Modify the Codebase by adding new data points for tracking enhanced metrics and updating data structures to store additional information.

4. Testing the Feature by writing unit and integration tests for the new metrics and testing the feature under different network conditions.
