### ISSUE TITLE
Fix new test clippy lints

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10827]
### Describe the feature

with nightly-2024-09-10 a ton of new (missing_docs) lints appeared for testing code.

to reproduce:
rustup update
cargo clippy --workspace --lib --examples --tests --benches --all-features --locked

## TODO
* fix lints by allowing missing docs for all test modules: `#![allow(missing_docs)]`

**Comment by caglaryucekaya** [comment]
I'd like to work on this one

**Comment by diegoTech14** [comment]
Hey @mattsse, I'm new on this project and would love to help with this issue. You can check my OD profile: https://app.onlydust.com/u/diegoTech14

Kind regards, 

Diego Duarte Fernández
