### ISSUE TITLE
Use derive-more Error for deriving error

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10828]
### Describe the feature

according to 
https://docs.rs/derive_more/latest/derive_more/derive.Error.html

this should work in no-std with 1.81 now

since we already have msrv 1.81 we can try using that instead of manual error derives

eg:

https://github.com/paradigmxyz/reth/blob/f6b20214404c8bbd85ce43d0b918ef04094cd16d/crates/consensus/consensus/src/lib.rs#L398-L406

this should be done crate by crate

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/reth).

### My background and how it can be leveraged
With over four years of experience in blockchain development, I have worked across multiple blockchain ecosystems. My expertise spans the entire development lifecycle—from project conceptualization and smart contract design to managing on-chain interactions, seamless protocol integration, and implementing strong security practices.

This enables me to handle both on-chain and off-chain infrastructure, ensuring the development of reliable, scalable blockchain applications.

**Comment by mattsse** [comment]
closing because this could become quite messy
