### ISSUE TITLE
Integrate net IF IP resolution into `NatResolver`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#10832]
### Describe the feature

Integrate IP resolution by reading network interface address, into new variant of `reth_net_nat::NatResolver`.
https://github.com/paradigmxyz/reth/blob/6764f7bc96a91d1adf4b4e1346e4f751ed8f6d6a/crates/net/nat/src/net_if.rs#L22-L38

This should change signature of `reth_net_nat::external_addr_with` to return a result
```rust
pub async fn external_addr_with(resolver: NatResolver) -> Result<Option<IpAddr>>
```

**Comment by garwahl** [comment]
@emhane I can take this, feel free to assign me
