### ISSUE TITLE
Spawn only one thread per `SenderRecoveryStage` run

### ISSUE THREAD

**Issue by joshieDo** [paradigmxyz/reth#10835]
```
this should be fine and overhead is negligible since our batches are very large,
but could be optimized away by spawning one thread for this for all batches that receives the chunks from every batch
```

_Originally posted by @mattsse in https://github.com/paradigmxyz/reth/pull/10810#discussion_r1753539779_

while respecting

https://github.com/paradigmxyz/reth/blob/5b3c115704c870de672a4238590790a6df03998d/crates/stages/stages/src/stages/sender_recovery.rs#L23-L29

**Comment by 0xkrane** [comment]
is anyone working on this?

**Comment by mahmudsudo** [comment]
Can i be assigned to this ?

**Comment by mattsse** [comment]
this has been completed with #11385

**Comment by mahmudsudo** [comment]
Can I be assigned to another instead ?
