### ISSUE TITLE
replace std feature gate alloc imports with extern crate alloc

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10853]
### Describe the feature

we have no-std support on a few crates,

alloc types, are currently feature gated like:

https://github.com/paradigmxyz/reth/blob/875cee27aca747315af1ef2a9dcdf29e058b33e7/crates/chainspec/src/spec.rs#L3-L4

this can be avoided by not feature gating 

https://github.com/paradigmxyz/reth/blob/875cee27aca747315af1ef2a9dcdf29e058b33e7/crates/chainspec/src/lib.rs#L12-L13
and always use `use alloc::`

## TODO
* replace feature gated alloc usage with extern crate alloc

**Comment by wadkhlemshem** [comment]
I can take a stab at this

**Comment by Tranduy1dol** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/reth).

### My background and how it can be leveraged
I have 1 year experience in Cairo language, Rust, Dojo Engine. Additionally, I have problem solving skills, self-learning skills, and some soft skills.
