### ISSUE TITLE
std: fix `std::thread_local` dep for no-std config

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#10871]
### Describe the feature

At the moment, we are using `std::thread_local`

https://github.com/paradigmxyz/reth/blob/817b1527e9daf30e838e14b49171db86be266219/crates/primitives/src/compression/mod.rs#L1

but unfortunately, the `thread_local` is not available for no-std config so that to unify stuffs, we need to find an alternative that works both for std and no-std configurations.

Related https://github.com/paradigmxyz/reth/pull/10861#discussion_r1756903379

**Comment by nadtech-hub** [comment]
https://github.com/paradigmxyz/reth/blob/cd10cbf4ff8b1ff35573c06dfe1bf2cb629716e1/crates/primitives/src/compression/mod.rs#L15
My intent is to replace static declarations with const ones. They would be inlined and dropped automatically.

**Comment by nadtech-hub** [comment]
@tcoratger I've reviewed your commits. Why did you keep std::thread_local?

**Comment by nadtech-hub** [comment]
Another suggestion is to write a few fns instantiating RefCell<_>

**Comment by nadtech-hub** [comment]
I was also looking to introduce RTIC to mimic LTS behavior. Would you mind it?

**Comment by nadtech-hub** [comment]
I created PR a couple of days ago. Can this issue be assigned to me?

**Comment by nadtech-hub** [comment]
The or was merged a while ago. Can this be marked as resolved?
