### ISSUE TITLE
ci: Integrate miri job

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1088]
### Describe the feature

add a [miri](https://github.com/rust-lang/miri) ci job to check for undefined behaviour

See also:

https://github.com/rust-lang/miri#running-miri-on-ci

or tokio's miri job:

https://github.com/tokio-rs/tokio/blob/88b1eb54fb66461b9f3524f4b5316241a019279a/.github/workflows/ci.yml#L193-L211

**Comment by xqft** [comment]
I could take this

**Comment by DaniPopes** [comment]
Components which extensively use `unsafe` for performance reasons were extracted to separate repos (such as [`nybbles`](https://github.com/alloy-rs/nybbles), [`trie`](https://github.com/alloy-rs/trie)), and remaining `unsafe` usages are trivial or FFI related, which miri cannot test.
