### ISSUE TITLE
inconsistent JSON RPC API responses: eth_getTransactionCount(address, 'pending') returns used nonce

### ISSUE THREAD

**Issue by perekopskiy** [paradigmxyz/reth#10881]
### Describe the bug

When running reth in dev mode with a small block-time (e.g. 300ms) JSON RPC API returns inconsistent results. After transaction with nonce X is included in the block (node returns receipt for it with blockNumber set) node may still return nonce X as a response for `eth_getTransactionCount(address, 'pending')`.

### Steps to reproduce

Here is [repo](https://github.com/perekopskiy/reth-race-example) with a small script that reproduces the issue. It sends transactions in loop from a single address. The script fails after some time with "nonce has already been used" error. It's better to run it on a resource-constrained machine and/or make all the CPUs busy so it reproduces faster.

### Platform(s)

Linux (x86), Linux (ARM), Mac (Apple Silicon)

### What version/commit are you on?

reth Version: 1.0.6
Commit SHA: c228fe15808c3acbf18dc3af1a03ef5cbdcda07a
Build Timestamp: 2024-08-29T18:34:24.773465330Z
Build Features: asm_keccak,jemalloc
Build Profile: maxperf

### What database version are you on?

Error: Datadir does not exist: "/root/.local/share/reth/mainnet"

### Which chain / network are you on?

dev

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
I see, we should swap the logic for pending and do the pool lookup after the disk lookup to rule this out

https://github.com/paradigmxyz/reth/blob/74c733d22dc6fc27cd9fa38ba6f7db7db648ce2e/crates/rpc/rpc-eth-api/src/helpers/state.rs#L272-L282

because the pool update can happen later

**Comment by perekopskiy** [comment]
@mattsse it reproduces for me with 1.0.7

**Comment by mattsse** [comment]
do you mean this is still happening?

**Comment by perekopskiy** [comment]
yes

**Comment by popzxc** [comment]
@mattsse do you have any ideas on what may be causing this? We found a workaround for our setup, but it's not pretty and it doesn't always work.

**Comment by mattsse** [comment]
do you also run with a custom setup?

**Comment by popzxc** [comment]
Not really, you can see it [here](https://github.com/matter-labs/zksync-era/blob/main/docker-compose.yml#L16). Basically, it's just vanilla reth with block time set to 300ms. Don't mind the fact that it's still 1.0.6 -- we didn't bump it, because we tested that the problem reproduces with it.

Our current workaround is a [custom retry provider](https://github.com/matter-labs/zksync-era/blob/b5dca41c3234a27c90c467f98df0aa81fa547a5c/core/tests/ts-integration/src/l1-provider.ts#L65), which is suboptimal.

**Comment by mattsse** [comment]
ah okay, finally found the reason why this happens
