### ISSUE TITLE
replace block fields with BlockBody

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10907]
### Describe the feature

currently Block has a flattened blockbody as its fields:

https://github.com/paradigmxyz/reth/blob/97cc9dd8ecaaf7ebfa0b401ed080da28dc791376/crates/primitives/src/block.rs#L40-L47

https://github.com/paradigmxyz/reth/blob/97cc9dd8ecaaf7ebfa0b401ed080da28dc791376/crates/primitives/src/block.rs#L557-L566

if we want to abstract a block as 

```rust
trait Block {type Body;}
```

then we need to use the container type

see also:

https://github.com/paradigmxyz/reth/blob/97cc9dd8ecaaf7ebfa0b401ed080da28dc791376/crates/primitives/src/block.rs#L301-L306

## TODO
* replace fields with `BlockBody`

### Additional context

fyi @refcell 

https://github.com/alloy-rs/alloy/issues/1290

**Comment by roynalnaruto** [comment]
@mattsse can I take this up?

In addition to the above, may be some methods can be moved to the `BlockBody`, for instance `has_blob_transactions`, `has_eip7702_transactions`, and a few others. With `Block` dereferencing to `BlockBody` for those ?

**Comment by PoulavBhowmick03** [comment]
@mattsse I am a new contributor to reth. I would love to work on this!

**Comment by roynalnaruto** [comment]
@mattsse I have some preliminary work here, let me know if it generally looks good
