### ISSUE TITLE
Create `BeaconConsensus` builder

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#1093]
### Describe the feature

1. Create a simple beacon consensus builder
 https://github.com/paradigmxyz/reth/blob/f771e23f9a3e4238bb413a55f02d1536126a0ea1/bin/reth/src/node/mod.rs#L156

2. Decouple and extract the sender part of the forkchoice state channel from the `BeaconConsensus`.

**Comment by onbjerg** [comment]
@rkrasiuk See https://github.com/paradigmxyz/reth/pull/1119#pullrequestreview-1279177915
