### ISSUE TITLE
Move `PayloadBuilderHandle` methods out to new trait

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#10956]
### Describe the feature

Move `PayloadBuilderHandle` methods out to new trait

https://github.com/paradigmxyz/reth/blob/0cde0724539962b80bc2eea390afbbfea501becd/crates/payload/builder/src/service.rs#L103-L200

**Comment by greged93** [comment]
Is this free for grabs @emhane ?

**Comment by varun-doshi** [comment]
I'd like to take this up if its okay with @greged93

**Comment by greged93** [comment]
sorry already working on it :/
