### ISSUE TITLE
Add helper function to ConfigureEvmEnv for the next block

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10950]
### Describe the feature

#10510 highlighted an issue where we can't easily get a cfg and block env for the next block.

this is inconvenient and we should move this into ConfigureEvmEnv instead

## TODO
* introduce `fill_next_cfg_and_block_env` similar to

https://github.com/paradigmxyz/reth/blob/abd4642d65b07be08debb67d2b5e9a5b3a403f32/crates/evm/src/lib.rs#L159-L167

but without the total difficulty, because we assume we only need this for block building

**Comment by mattsse** [comment]
@garwahl this is now a blocker, do you have bandwidth to work on this right away?

**Comment by garwahl** [comment]
Yeah I can get something up in the next day, if this is urgent feel free to take it

**Comment by mattsse** [comment]
since this is a blocker, I'll try to get this over the line asap, but this will unlock additional todos, will ping you on them
