### ISSUE TITLE
 Miscalculation of Effective Gas Price in `revm_utils.rs`

### ISSUE THREAD

**Issue by enitrat** [paradigmxyz/reth#10964]
### Describe the bug

The current implementation of `get_effective_gas_price` function contains a miscalculation of the effective gas price when `max_fee_per_gas` is provided. This calculation doesn't align with the Ethereum specification and may result in incorrect gas prices being used for transactions (im not sure where this is _actually_ used - and given that Reth is a major client, I doubt this has any effect on the tx processing)

In execution_specs, which is a simple implementation of the EVM that follows the specification for each fork, in the case of EIP1559 transactions, the effective gas price is computed as: ` priority_fee_per_gas + base_fee_per_gas`, where
`priority_fee_per_gas = min(tx.max_priority_fee_per_gas, tx.max_fee_per_gas - base_fee_per_gas)`

https://github.com/ethereum/execution-specs/blob/07f5747a43d62ef7f203d41d77005cb15ca5e434/src/ethereum/cancun/fork.py#L385-L402

In reth, the current implementation does'n't compute the _actual_ priority fee, but uses the _max_ priority fee

```rust
Ok(min(
    max_fee,
    block_base_fee.checked_add(max_priority_fee_per_gas).ok_or_else(|| {
        EthApiError::from(RpcInvalidTransactionError::TipVeryHigh)
    })?,
))
```

Should the correct implementation be:

```rust
let priority_fee_per_gas = min(
    max_priority_fee_per_gas,
    max_fee.saturating_sub(block_base_fee)
);
Ok(block_base_fee.checked_add(priority_fee_per_gas).ok_or_else(|| {
    EthApiError::from(RpcInvalidTransactionError::TipVeryHigh)
})?)
```

### Steps to reproduce

see: 
https://github.com/paradigmxyz/reth/blob/7a20b413f544d6d9660ab921dc400d80ffc9a514/crates/rpc/rpc-eth-types/src/revm_utils.rs#L114-L147

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

0746479e3c873e0f83c533871598dd1d749d0041

### What database version are you on?

unrelated

### Which chain / network are you on?

unrelated

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> I doubt this has any effect on the tx processing

this is only used for eth_call
