### ISSUE TITLE
update txpool max block gas limit

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10987]
### Describe the feature

currently the block gas limit is fixed

https://github.com/paradigmxyz/reth/blob/94c15c00742e4d69581740a38d2dd83ab65fc0db/crates/transaction-pool/src/pool/txpool.rs#L920-L921

and is used to enforce:

https://github.com/paradigmxyz/reth/blob/94c15c00742e4d69581740a38d2dd83ab65fc0db/crates/transaction-pool/src/pool/txpool.rs#L1336-L1337

we need to update this value to the new tip's gas limit:

https://github.com/paradigmxyz/reth/blob/94c15c00742e4d69581740a38d2dd83ab65fc0db/crates/transaction-pool/src/traits.rs#L634-L635

when we update the pool:

https://github.com/paradigmxyz/reth/blob/94c15c00742e4d69581740a38d2dd83ab65fc0db/crates/transaction-pool/src/traits.rs#L447-L447

@greged93 

ref #10985

**Comment by greged93** [comment]
will work on this next then!
