### ISSUE TITLE
JWT to authenticate external CL against Reth

### ISSUE THREAD

**Issue by 0xMelkor** [paradigmxyz/reth#1098]
### Describe the feature

I propose Reth to adhere the JWT standard to setup a trust relationship with an external CL.

Given the current code base and available libraries I'd suggest to create a `tower::Layer` to cope with JWT authentication.
At a first glance the code could look like this:

```rust
   // Read these args from CLI
   // --authrpc.addr=0.0.0.0
   // --authrpc.port=8551
   // --authrpc.jwtsecret=/etc/jwt/jwtsecret

    // Read these from CLI
    const AUTH_JWT: &str = "/etc/jwt/jwtsecret"; 
    const AUTH_PORT: u32 = 8551; 
    const AUTH_ADDR: &str = "0.0.0.0";

    // RPC layer communicates with the implemented logic
    // through an unbounded channel
    let (tx, rx) = unbounded_channel();
   
    let chain_spec = MAINNET.clone();
    let client = Arc::new(MockEthProvider::default()); // Here we should provide a real Client implementation

    // EthConsensusEngine is already implemented as an endless future
    // that listens on the rx part of the channel. 
    // Let's spawn a task.
    tokio::spawn(EthConsensusEngine {
        client: client.clone(),
        chain_spec: chain_spec.clone(),
        local_store: Default::default(),
        rx: UnboundedReceiverStream::new(rx),
    });

    // We need to implement JwtLayer as a `tower::Layer`.
    // This layer checks a valid JWT is provided in CL HTTP requests
    let jwt_layer = JwtLayer::new(AUTH_JWT)?; // Invalid JWT make this fail
    let jwt_middleware = tower::ServiceBuilder::default().layer(jwt_layer);
    
    let server = ServerBuilder::default()
        .set_middleware(jwt_middleware)
        .build(format!("{AUTH_ADDR}:{AUTH_PORT}").parse::<SocketAddr>()?)
        .await?;

    let rpc = EngineApi { engine_tx: tx }.into_rpc();
    let handle = server.start(rpc)?;
```

What do you guys think?

### Additional context

I suppose all this stuff applies if Reth is built with `feature = "client"`

**Comment by 0xMelkor** [comment]
I guys, are you ok if I take this up?
I'd love to jump in

**Comment by mattsse** [comment]
this is great,

We definitely need an auth middleware that verifies the jwt. 

please go for it.

**Comment by onbjerg** [comment]
@0xMelkor Please note that this should only apply to the engine API, which is the `eth_` and `engine_` namespaces. These are required to run on a different port since these APIs have different security assumptions.

**Comment by 0xMelkor** [comment]
> Please note that this should only apply to the engine API, which is the `eth_` and `engine_` namespaces. 

Hi @onbjerg,
afaik the JWT check applies only to inbound CL calls, at the "Engine API" boundary (`engine_` namespace). The `eth_` namespace is not reserved for CL, and belongs to the "JSON-RPC API".

Maybe I'm missing something, can you clarify this?
