### ISSUE TITLE
Add support for FlatCallTracer

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10991]
### Describe the feature

ref #201 might require some helper for `TracingConfig`

blocked by #10989

we now have a new variant:

https://github.com/paradigmxyz/reth/blob/c42d5447a443e95ae92437e4d91f7dc06e253e70/crates/rpc/rpc/src/debug.rs#L392-L396

that behaves exactly as the parity tracer, so we can reuse that impl:

https://github.com/paradigmxyz/reth/blob/c42d5447a443e95ae92437e4d91f7dc06e253e70/crates/rpc/rpc/src/trace.rs#L341-L358

**Comment by 0xkrane** [comment]
can take this

**Comment by mattsse** [comment]
unblocked now
