### ISSUE TITLE
node --instance <N> does not produce N number of ipcs 

### ISSUE THREAD

**Issue by wasiek** [paradigmxyz/reth#11001]
### Describe the bug

I'm trying to start node and communicate with it via ipc.
Because of performance reasons I would like to spread the load across multiple files.
As described in the topic I have an issue with accomplishing it.
I must admit node is not in sync.

### Steps to reproduce

Execute: 
```
reth node --instance 3 
```
Produces:
```
ls /tmp
reth.ipc-3
```
While I would expect
```
ls /tmp
reth.ipc-1
reth.ipc-2
reth.ipc-3
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 1.0.5
Commit SHA: 603e39ab74509e0863fc023461a4c760fb2126d1
Build Timestamp: 2024-08-12T14:15:11.150189859Z
Build Features: asm_keccak,jemalloc
Build Profile: maxperf

### What database version are you on?

2024-09-18T20:07:37.505596Z  INFO Initialized tracing, debug log directory: /root/.cache/reth/logs/mainnet
Error: Datadir does not exist: "/root/.local/share/reth/mainnet"

Location:
    /project/crates/cli/commands/src/db/mod.rs:71:9

### Which chain / network are you on?

tried with main, but seems it is not related to the issue

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
This is not the intended behavior for the `--instance` flag. It does not produce N IPCs or RPCs, it just changes the IPC path / RPC endpoint so it doesn't conflict with another reth instance on the same machine.

For example you would run
```
reth --instance 1
reth --instance 2
```

And it would run two reth nodes, with two IPC paths. If you have a particular application that is currently saturating IPC throughput and is now bottlenecked by IPC, then it would be interesting to know what that application is, or how we could support it. But that would be another issue for a different feature.
