### ISSUE TITLE
Support `skip` attribute in RlpEncodable derive macro

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1102]
### Describe the feature

There are use cases where being able to skip fields during rlp encoding is useful:

https://github.com/paradigmxyz/reth/issues/1101

Currently, we don't support this in the `RlpEncodable` derive macro.

## TODO

add `rlp(skip)` field attribute support for `RlpEncodable` macro that should work the same as `serde(skip)`.

**Comment by leruaa** [comment]
I would like to take this on

**Comment by mattsse** [comment]
I guess we'd need `rlp(default)` as well for the `RlpDecodeable` macro

**Comment by leruaa** [comment]
Yeah, I found that: https://github.com/paradigmxyz/reth/blob/d86c9890bdf9d12a08d8e163a5a21a4ccbc97da4/crates/common/rlp-derive/src/lib.rs#L12-L16

but looks like it's not implemented at all.

Do we just need `rlp(default)`, or also `rlp(default = "path")` like in Serde?

**Comment by mattsse** [comment]
yeh I believe this was not implemented before the fork.
imo `rlp(default)` should be sufficient, `path` would be nice though.

**Comment by leruaa** [comment]
I will see how to add `path`, I guess #1116 can be merged in the meantime.
