### ISSUE TITLE
Split MevApi trait into two

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11036]
### Describe the feature

this currently has both an eth_call like endpoint and a send endpoint:

https://github.com/paradigmxyz/reth/blob/03e89b1af6c5ee28aa1c47b4d74371d3114c45aa/crates/rpc/rpc-api/src/mev.rs#L9-L9

we have the same situation here:

https://github.com/paradigmxyz/reth/blob/03e89b1af6c5ee28aa1c47b4d74371d3114c45aa/crates/rpc/rpc-eth-api/src/bundle.rs#L14-L30

so we can split this into two traits as well, so one can impl simBundle without supporting sendBundle

**Comment by 0xriazaka** [comment]
Can i take this?
