### ISSUE TITLE
Replace Tasks generic with `Box<dyn TaskExecutor>`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11037]
### Describe the feature

currently we have a few places where we use `Tasks` as generic,
we can get rid of this by using `Box<dyn>`

including:

https://github.com/paradigmxyz/reth/blob/668807802b9120343a084963005fbda7ece314f6/crates/node/builder/src/builder/mod.rs#L185-L185

**Comment by estensen** [comment]
Taking a small break from https://github.com/paradigmxyz/reth/issues/10749, pls assign me this one

**Comment by mattsse** [comment]
lets focus on the nodebuilder first, this could potentially flag a few limitations in the launch impls

**Comment by mattsse** [comment]
for example, I think this isn't part of the trait

https://github.com/paradigmxyz/reth/blob/668807802b9120343a084963005fbda7ece314f6/crates/tasks/src/lib.rs#L494-L494

actually, perhaps we hold off on NodeBuilder first and try tackling the generics in the rpc stack

**Comment by estensen** [comment]
Sorry, won't have the bandwidth this week. Feel free to assign to someone else.

**Comment by mattsse** [comment]
this turned out to be a bad idea because as a lot of limitations
