### ISSUE TITLE
Improve test coverage for 4844 rlp transactions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11032]
### Describe the feature

we're lacking a few rlp tests for pooled 4844 transactions, which would have caught:

https://github.com/paradigmxyz/reth/pull/11031

getting raw blob transactions isn't trivial because blobs are deleted...
blob transactions can be fetched from https://api.blobscan.com/ 

this could be helpful: https://github.com/foundry-rs/block-explorers/tree/main/crates/blob-explorers

## TODO
* get valid encoded 4844 with sidecar
* and additional roundtrip tests

**Comment by aroralanuk** [comment]
Can I pick this one up?
