### ISSUE TITLE
BlockchainTree sidechain/pending block inmemory  structure

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1104]
In reth we are moving to have pending state and sidechains inside the memory. This decisions coupled with blockchains having the finality of N block seem reasonable but pull some additional changes that we need to implement inside the client. 

The table for the latest/pending and sidechain blocks where the whole block is going to be saved, it is needed as a system of crash recovery, on startup Blockchain tree can be regenerated from it.

```mermaid
flowchart BT
    subgraph canonical chain
        CanonState:::state
        block0canon:::canon -->block1canon:::canon -->block2canon:::canon -->block3canon:::canon --> block4canon:::canon --> block5canon:::canon
    end
    block5canon --> block6pending1:::pending --> block7pending1:::pending
    block5canon --> block6pending2:::pending 
    subgraph sidechain2
        S2State:::state
        block3canon --> block4s2:::sidechain --> block5s2:::sidechain
    end
    subgraph sidechain1
        S1State:::state
        block2canon --> block3s1:::sidechain --> block4s1:::sidechain --> block5s1:::sidechain --> block6s1:::sidechain
    end
    classDef state fill:#1882C4
    classDef canon fill:#8AC926
    classDef pending fill:#FFCA3A
    classDef sidechain fill:#FF595E
```

Mermaid flowchart represents all blocks that can appear in blockchain.
Green blocks belong to canonical chain and are saved inside database table, they are our main
chain. Pending blocks and sidechains are found in memory inside [`BlockchainTree`].
Both pending and sidechains have same mechanisms only difference is when they got committed to
database. For pending it is just append operation but for sidechains they need to move current
canonical blocks to BlockchainTree and flush sidechain to the database to become canonical chain.

As all pending block are already executed and we have data, when it gets decided that block is canonical, changes can be flushed directly to database. We need to be aware of seting pipeline stages progress.

For unwinding canonical chain from database, data saved in database can be reused and stored in memory, pipeline unwind would just remove it.  Still need to be aware of pipeline stages progress.

**Comment by rakita** [comment]
> This also plays a role here #1105 right?

Yeah it does, idea is that rpc can find any pending state/block that was not canonicalized in this place.

**Comment by gakonst** [comment]
How do the downloaders relate to this? Do we send them a new command on each reorg to download a diff range?

**Comment by rakita** [comment]
> How do the downloaders relate to this? Do we send them a new command on each reorg to download a diff range?

The assumption is that consensus and we have all the needed blocks in the tree to do the reorgs, that is why we are saving them. If some problem happens and we don't have needed blocks, we need to fetch it from p2p and depending on if it is the fork block (by engine API) that we are missing we should call pipeline.

**Comment by rakita** [comment]
Did some scaffolding and worked on core structures (Tree and Chain): https://github.com/paradigmxyz/reth/tree/rakita/blockchain_tree

**Comment by gakonst** [comment]
> If some problem happens and we don't have needed blocks, we need to fetch it from p2p and depending on if it is the fork block (by engine API) that we are missing we should call pipeline.

How does Geth / Erigon do it?

**Comment by rakita** [comment]
> > If some problem happens and we don't have needed blocks, we need to fetch it from p2p and depending on if it is the fork block (by engine API) that we are missing we should call pipeline.
> 
> How does Geth / Erigon do it?

That is the only way to fetch them if we for any reason don't receive blocks from the consensus layer

**Comment by joshieDo** [comment]
Wondering how much memory would this occupy for chains which can have deep re-orgs (and so multiple sidechains?)... Or even with shallow ones. To me, having it all in memory seems wasteful? If in the future, we wish to have as much (canonical) plain state in memory , this seems to detract from that.

Another loose idea: could we just write/read this kind of data to `redb`. Would it be overly complex/slow? It could be a way to gain experience with it and evaluate pros/cons against libmdbx

**Comment by rakita** [comment]
> Wondering how much memory would this occupy for chains which can have deep re-orgs (and so multiple sidechains?)... Or even with shallow ones. To me, having it all in memory seems wasteful? If in the future, we wish to have as much (canonical) plain state in memory , this seems to detract from that.
> 
> Another loose idea: could we just write/read this kind of data to `redb`? Would it be overly complex/slow? It could be a way to gain experience with it and evaluate pros/cons against libmdbx

Had the same concern that I wrote to gakons: `I have good feeling about BlockchainTree, only concern there is i need to make it slim as to not take a lot of RAM.`

Was thinking about reorgs for a while, and with the finality that every chain has, deep reorgs that PoW had is a thing of the past. We can expect only N number of reorgs: https://twitter.com/rakitadragan/status/1615666501440212993

Reasons and my thinking why is it this way:  It is easier to do all in memory, atm Ethereum have small reorg depth,  there is a small benefit of pending/best blocks being in memory for researchers (which can be achieved with good cache), adding db in the mix is always the option if we notice that in memory footprint is too big.

Using `redb` seems like a good idea.

**Comment by gakonst** [comment]
Let's go with all in-memory initially and assume smol reorgs, let's keep our focus on getting things done "right" for Ethereum and expand from there. I don't think it'll be a big change to use a disk-backed backend.

**Comment by rakita** [comment]
Have a good structure on what needs to be implemented.
Tree atm will have three main functionalities
```
/// * insert_block: insert block inside tree. Execute it and save it to t.
/// * finalize_block: Flush chain that joins to finalized block.
/// * make_canonical: Check if we have the hash of block that we want to finalize and commit it to db. Do reorg if needed.
```

The next thing is handling the finalization of the block and pruning the tree for obsolete blocks/sidechains.

Opened draft PR: https://github.com/paradigmxyz/reth/pull/1212

**Comment by rakita** [comment]
Sharing diagram from last week about interconnections of reth components: https://mermaid.live/edit#pako:eNqNU02P0zAQ_Ssjn0BKqzRfm-bAobBHJAQVB9SLG09ai8SObGfb0vS_M4nbLGyXFTk54zfvPc-zz6zUAlnBqlofyj03DlbrjQL61scvWtcwm80-QBu1vkiLa8XoJynQ-PKq1uXPVSdrqvh93-13H9VOKvT1fjugQOEBtkMTyIp-EAWKAFDtCHeQdQ0WlQDpwGlwBrH_S8LTWsd3aD2t0AdVaz7JT4bvnfV4xLJzCNpAw09bhM4iGHxqQKv61MPjuC-1upe5nfqd2AIng7d_-_4e-wbNR63ofLaz33ktBX8GTT3_HDJlJNWaJvK_iBc2XoO84efP5EASii5IS9FItfP52f4F5SuNFHGlDUG0LBGkBaUdVbohYTXGG0jlJKdM7EmV42QrdOUe3B4bqIxuIGrb_jpDr_C1LSfbo04_3SnrGSbJ_mqHBaxB03Ap6MKfB5oNGxRwwwpaCqx4V7sN26gLQXnn9DeywwpnOgxY19Jk8JPkO8ObW7HlihVndmRFlM-zLI_TJE-XiyQOk4eAnVixyKP5MsujMEzjRRYlSXwJ2C-tiSGcP-TLNM2jeJHHYbrMlgFDIZ02n_2bHJ_mqPFjbBgkL78BE580rA

**Comment by rakita** [comment]
Did finalization and discarding of block/sidechain that are not valid. Will start next on block execution found in `Chain`, substate integrating and changesets. 

Will use executor interface trait to allow better testing: https://github.com/paradigmxyz/reth/blob/4cbd1990163a005e0bca0b3e1f94ccd28dbf2e04/crates/interfaces/src/executor.rs#L7

**Comment by rakita** [comment]
Worked on substate and substate with provider structure that would allow us to plug in necessary provider while substate data is standalone.:
https://github.com/paradigmxyz/reth/blob/rakita/blockchain_tree/crates/executor/src/substate.rs#L9
https://github.com/paradigmxyz/reth/blob/rakita/blockchain_tree/crates/executor/src/substate.rs#L40

Worked on block hashes as we need last 256 block hashes for execution: https://github.com/paradigmxyz/reth/blob/e04e743f1fd5dea925bf3da5f8b66ef00636b12b/crates/executor/src/blockchain_tree/mod.rs#L122

Next step is to use all of that and start executing block in `Chain` and generating changesets.

**Comment by rakita** [comment]
Execution fit nicely with providers, started doing revert of substate with changesets (needed for chain joints). and handling of edgecases as multiple selfdestructs/creates of same account in one chain (decided to handle it with counter). Will continue working on that.

**Comment by gakonst** [comment]
> started doing revert of substate with changesets (needed for chain joints)

Is this in case: A -> B,  but you need to reorg to A -> C, meaning you need to revert B and then re-apply C?

> . and handling of edgecases as multiple selfdestructs/creates of same account in one chain (decided to handle it with counter)

:+1:

**Comment by rakita** [comment]
> > > started doing revert of substate with changesets (needed for chain joints)
> > 
> > 
> > Is this in case: A -> B, but you need to reorg to A -> C, meaning you need to revert B and then re-apply C?
> 
> Yeah exactly like that, it is more impactful if you have `G -> A -> B` and you want state of `G->A` so you can add C to it to have `G->A->C`
> 
> Worked on applying and reverting of changesets in substate, and they seem okay. Next in line is splitting of the chain (as in if just half of chain gets commited for any reason), and saving last 256 block hashes in memory (last 256 hashes are needed for BLOCKHASH opcode).
> 
> After that, I am left with `commit_canonical` and `revert_canonical` functions that flush the data to `tables` and I can start writing tests.

**Comment by gakonst** [comment]
Sweet 🔥

**Comment by rakita** [comment]
Switched priority today and focused on `commit_canonical` and needed refactoring of staged. https://github.com/paradigmxyz/reth/pull/1474  (have a few todo's to go over.)
With one function we will have one atomic commit of the whole block.

For `revery_canonical` I am intending to read necessary fields from the database and use `Pipeline` to revert needed things.

chain split and the last 256 block hashes tasks are still there.

**Comment by rakita** [comment]
Finished #1474 we now have one function to push all change atomically to tables.

Did split of chain, some missing functions for executing block on canonical blocks, fixes by using proper history/latest provider depending on chain canonical joint.

**Comment by rakita** [comment]
Insert of past canonical hashes are added and update mechanism. Some renaming. Was focused on sync switch defining the flow and covering all potential edge cases. 

I want to add a function that would receive the last finalised block and update the tree and its chains. This is needed if pipeline gets switched and some unknown hashes gets updated. After this I would start `revert_canonical` function that would read changed from db and write it as a separate Tree chain.

**Comment by rakita** [comment]
Added function that would update all canonical hashes `update_canonical_hashes` it loads hashes from table, update indices and  allows us to discard chains that got obsolete: https://github.com/paradigmxyz/reth/pull/1212/files#diff-da421ad20396586d4353900a678502398a54cab502db71d125a0bd269959889cR326-R354

Added `SealedBlockWithSenders` that can probably be reused in other places. Added provider getter that would get a range of `SealedBlockWithSenders`. Still need to add getter for `ExecutionResult` it will probably miss some fields as receipts are not saved.
https://github.com/paradigmxyz/reth/pull/1212/files#diff-243938712a9e652b6ba6409f45b6e71101f6f30fe7ec9f153c33b14a3dc61e69R507

Still missing things are unwinding of tables on canonical chain reorg, update of pipeline progress, tests.

What can be potentially left for later is buffering of blocks that we don't know the parent and we can try to reinsert the if `update-canonical_hashes` comes.

**Comment by rakita** [comment]
Mostly worked on the function for getting and unwinding blocks from tables, Extractng execution result was tricky one but I am close to finishing that. And I need to call `Index`, `Hashing`,`Merkle` stages unwind  to finish unwinding.

And after it, it is mostly testing.

**Comment by gakonst** [comment]
Will start reviewing this closer tomorrow.

**Comment by rakita** [comment]
Did a little bit of cleanup and refactoring and wrote execution result extraction from db. unwind part refactor is still needed.

**Comment by rakita** [comment]
Updated pipeline tables on commit/revert paths. It will iterate over `SyncStatus` table and update block number to last commits/reverted. Reverted state to the previous block. Tied those function in BlockchainTree.

Refactored `Indexing`/`Hashing` stages and moved functionality to Provider.

I think that is that on functionality and I can start testing. I will try to refactor execution in some way so it is easier to mock.

**Comment by rakita** [comment]
squashed a few bugs in transactions and wrote some tests there that checks insert/take Transaction functionality.

Moving to test blockchain tree, will refactor executor so we could handle mock execution.

**Comment by rakita** [comment]
Created `ExecutorFactory` #1661  and integrated it inside Tree.
Writing tests and squashing bugs inside BlockchainTree.

**Comment by rakita** [comment]
writing tests and squashing bugs,
the latest problem is a revert of the canonical chain (when reorging) leaves wrong root hash inside db.
Test cases can be found here: https://github.com/paradigmxyz/reth/blob/06575285544330e0ef6f5f9aa18e099424fa4048/crates/executor/src/blockchain_tree/mod.rs#L745-L755

**Comment by rakita** [comment]
merkle root problem was related to the wrong order of ExecutorResults in the test suite. Added few more tests and made it ready for review.
