### ISSUE TITLE
Add Pending State provider|Executor 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1105]
### Describe the feature

on rpc tag "pending" we need to execute against the pending state.

This needs access to 
* the latest state
* pending block config settings like next basefee?
* the best transaction of the pool (`TransactionPool::best_transaction`)
* An EVM executor

**Comment by onbjerg** [comment]
Imo this should be part of #627 (see #1095)

**Comment by mattsse** [comment]
does that mean the transaction pool is not even involved here?

**Comment by onbjerg** [comment]
Txpool is part of local block building since we need to build a block from the best transactions in the pool

**Comment by rakita** [comment]
Pending blocks will be found in BlockchainTree: https://github.com/paradigmxyz/reth/issues/1104

It can be build periodically BlockBuilder https://github.com/paradigmxyz/reth/issues/1013 and flushed to `BlockchainTree` as tree already need to have ability to have the latest state for consensus pending blocks or sidechain so it is good for executing on the pending state.

**Comment by gakonst** [comment]
> Imo the interface of this should be part of #627 (see #1095)
> 
> Generally we need:
> 
> 1. A way to get the pending block (which is part of block building)
> 2. A way to execute like so:
>    
>    1. Execute the pending block on top of the current latest state
>    2. Execute whatever we got from RPC on top of the state from 1.

A common request from searchers has been to allow them to override the block env parameters when tracing, so yeah we def want some way to override the state from 1.

If there are multiple pending blocks, which is the one we should be using?

**Comment by mattsse** [comment]
closing this because we now have payload building and pending state ##2294
