### ISSUE TITLE
Improve `debug_traceBlock` performance

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11066]
### Describe the feature

currently, trace_block is a loop over transactions and that invoke trace_transaction:

https://github.com/paradigmxyz/reth/blob/08bdec9efa26c6a97a2c0467469727b61c9b5dfc/crates/rpc/rpc/src/debug.rs#L107-L118

note how this clones the opts:

https://github.com/paradigmxyz/reth/blob/08bdec9efa26c6a97a2c0467469727b61c9b5dfc/crates/rpc/rpc/src/debug.rs#L119-L119

this results in some overhead:
* opts -> TracingConfig conversion https://github.com/paradigmxyz/reth/blob/08bdec9efa26c6a97a2c0467469727b61c9b5dfc/crates/rpc/rpc/src/debug.rs#L708-L710
* Inspector is not reused: for block level tracing we can reuse the Inspector by `fusing` it
https://docs.rs/revm-inspectors/latest/revm_inspectors/tracing/struct.TracingInspector.html#method.fuse
and because most geth trace results don't consume the traces, we can keep the allocated memory in TracingInspector

https://docs.rs/revm-inspectors/latest/revm_inspectors/tracing/struct.TracingInspector.html#method.geth_builder

## TODO
* this should be improved in such a way that the allows us to reuse the internals

this could perhaps be done with a helper type for block tracing that keeps the TracingInspector or similar

**Comment by JosepBove** [comment]
Ready for review
