### ISSUE TITLE
Remove `BlockNumHash` index, tables will contain canonical blocks only

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1107]
As with the latest discussion we talked about moving sidechains and pending blocks to their separate table and not polluting current tables that would contain canonical blocks.

 This would make changed to these tables:
```
Remove:    ( CanonicalHeaders ) BlockNumber | HeaderHash
Remove:    ( NonCanonicalTransactions ) BlockNumHashTxNumber | TransactionSigned
Change index to number:    ( HeaderTD ) BlockNumHash | CompactU256
Change index to number:    ( Headers ) BlockNumHash | Header
Change index to number:    ( BlockBodies ) BlockNumHash | StoredBlockBody
Change index to number:    ( BlockOmmers ) BlockNumHash | StoredBlockOmmers
```

`NonCanonicalTransaction` was never used, and `CanonicalHeader` are not needed as we only save canonical blocks inside `Headers` table

related to this effort to move pending/sidechaind block to BlockchainTree: https://github.com/paradigmxyz/reth/issues/1104

**Comment by rkrasiuk** [comment]
@rakita i'm a bit split on removing the `CanonicalHeaders` table since it acts as a cache for header hash calculation. Maybe renaming it is enough? Alternatevily we could store the hash alongside the header in the `Headers` table

**Comment by rakita** [comment]
> @rakita i'm a bit split on removing the `CanonicalHeaders` table since it acts as a cache for header hash calculation. Maybe renaming it is enough? Alternatevily we could store the hash alongside the header in the `Headers` table

If it is used and it is helpful leave it, and just do renaming to not have confusion about what it is.
