### ISSUE TITLE
Custom JS tracers default disabled

### ISSUE THREAD

**Issue by dallonby** [paradigmxyz/reth#11086]
### Describe the bug

_I believe this is a divergence from geth / erigon where these are default enabled._

At present, custom JS tracers seem to require a change to Cargo.toml

```
diff --git a/Cargo.toml b/Cargo.toml
index 189681e32..b82602c22 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -377,7 +377,7 @@ reth-provider = { path = "crates/storage/provider" }
 reth-prune = { path = "crates/prune/prune" }
 reth-prune-types = { path = "crates/prune/types" }
 reth-revm = { path = "crates/revm" }
-reth-rpc = { path = "crates/rpc/rpc" }
+reth-rpc = { path = "crates/rpc/rpc", features = ["js-tracer"]}
 reth-rpc-api = { path = "crates/rpc/rpc-api" }
 reth-rpc-api-testing-util = { path = "crates/rpc/rpc-testing-util" }
 reth-rpc-builder = { path = "crates/rpc/rpc-builder" }
```

### Steps to reproduce

Compile Release build and JS tracers are disabled and inaccessible without recompile.

### Platform(s)

Linux (x86)

### What version/commit are you on?

HEAD

### What database version are you on?

NA

### Which chain / network are you on?

NA

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
ah shoot... 
features...
