### ISSUE TITLE
Move Requests type to alloy

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11082]
### Describe the feature

this type exists as a helper

https://github.com/paradigmxyz/reth/blob/95d65dc022117318bb0b1a915d840cfe30857953/crates/primitives-traits/src/request.rs#L30-L30

because the rlp encoding is slightly different

## TODO

* move this type to alloy where `Request` is defined

**Comment by 0xriazaka** [comment]
Can i take this?

**Comment by varun-doshi** [comment]
I'd like to work on this

**Comment by PanGan21** [comment]
I believe this issue is blocked until the next alloy release

**Comment by refcell** [comment]
Ref: https://github.com/alloy-rs/alloy/pull/1326

**Comment by mattsse** [comment]
with recen pectra changes this wont be necessary anymore
