### ISSUE TITLE
Make `ExecutionOutcome` generic over receipt collection type

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#11108]
### Describe the feature

Make `ExecutionOutcome` generic over receipt collection. Require trait bound `ExecutionOutcome<T: Receipts>` in `AutoSealBuilder`, in order to remove optimism feature from the `AutoSealBuilder`. Somehow the `ExecutionOutcome` must be linked to the `Executor` so it can be customised at sdk level instead, probably requiring trait bound `Executor<Output: Into<ExecutionOutcome<T: Receipts>>>`. 

The trait `Receipts` doesn't exist yet, and needs to be smthg like 
```rust
pub trait Receipts {
    fn receipts_root_slow(&self) -> Result<Option<B256>, Self::Error>;
}
```

so the optimism receipts collection would have to look smthg like 

```rust
struct OpReceipts<'a> {
    timestamp: u64,
    block_number: u64,
    chain_spec: &'a ChainSpec,
    receipts: Vec<ReceiptWithBloom<OpReceipt>>,
}
```

and simple ethereum type

```rust
struct Receipts {
    block_number: u64,
    receipts: Vec<ReceiptWithBloom<Receipt>>,
}
```

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10713
```

**Comment by emhane** [comment]
garwhal, if this description makes sense to you, you're very welcome to implement it and close https://github.com/paradigmxyz/reth/pull/10932

**Comment by garwahl** [comment]
@emhane I'm sure it'll make more sense as I dig in 😅 I can give it a crack, I'm sure I'll have more questions as I go

**Comment by emhane** [comment]
hey @garwahl did you start with this? will scope this out into smaller issues otherwise.

would like to point out that the sketch of the solution in the description uses a vector of receipts with bloom, when it should actually be a vector of vectors of receipts (without bloom).

**Comment by garwahl** [comment]
> hey @garwahl did you start with this? will scope this out into smaller issues otherwise.
> 
> would like to point out that the sketch of the solution in the description uses a vector of receipts with bloom, when it should actually be a vector of vectors of receipts (without bloom).

Hey not yet, no worries feel free to break it up into smaller tasks and I'll jump on those

**Comment by emhane** [comment]
closed by https://github.com/paradigmxyz/reth/pull/11230

**Comment by greged93** [comment]
@emhane is this still ongoing? Happy to take a look into it

**Comment by emhane** [comment]
will need @mattsse input here since he closed https://github.com/paradigmxyz/reth/pull/11314 which solved this
