### ISSUE TITLE
Copy tests in `reth_execution_types::chain` to `reth-evm-optimism`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#11111]
### Describe the feature

Copy tests with optimism feature in `reth_execution_types::chain` into `reth-evm-optimism`. Remove the optimism feature gated code form the original tests (and remove code feature gated by `#[cfg(not(feature = "optimism"))]` in the `reth-evm-optimism` copy).

This will likely cause issues in CI, for now the original tests will have to be feature gated with `#[cfg(not(feature = "optimism"))]`

**Comment by 0xriazaka** [comment]
Can i work on this?
