### ISSUE TITLE
primitives: remove `BlockHeader` and `Header` reexport

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#11127]
### Describe the feature

After the merge of https://github.com/alloy-rs/alloy/pull/1302 and its inclusion over the next release of alloy, we can completely remove `BlockHeader` trait and `Header` reexport here

https://github.com/paradigmxyz/reth/blob/ed1de8996d1ff3082268b6f6da5669f9a664aea4/crates/primitives-traits/src/header/mod.rs#L12-L73

We can then import everything from alloy directly when needed around the codebase.

**Comment by 0xkrane** [comment]
can take a stab at this

**Comment by mattsse** [comment]
we likely want a smaller trait for this because we only need a subset from this alloy trait
