### ISSUE TITLE
Deposit receipt version in OP RPC transaction

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#11164]
### Describe the feature

What should we be setting the deposit receipt version field to in an `op_alloy_rpc_types::Transaction`? 

https://github.com/paradigmxyz/reth/blob/f606b70b7fd7ce01d7c501f86fc2d72658dd0306/crates/optimism/rpc/src/eth/transaction.rs#L115

**Comment by aroralanuk** [comment]
Can I take this?
