### ISSUE TITLE
Move op storage tests into new crate `reth-optimism-storage`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#11172]
### Describe the feature

Move test to new crate `reth-optimism-storage`. Just keep the test in a a test module in the _lib.rs_ file. Most likely this crate will be filled with more code soon, otherwise we can reconsider its existence (and if test should be moved into another op crate) in the future.

https://github.com/paradigmxyz/reth/blob/d3114b4eec39790fb5b1c567fe095d2d65c24bfd/crates/storage/db-api/src/models/mod.rs#L349-L375

```[tasklist]
### Tasks
```

**Comment by SkandaBhat** [comment]
@emhane I can take this up. Could you please assign it to me?
