### ISSUE TITLE
remove unused derives from alloy compat types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11199]
### Describe the feature

these types are private and only used for conversions:

https://github.com/paradigmxyz/reth/blob/2b20a0dbfcbc57322702404cf016476e58aa34cf/crates/storage/codecs/src/alloy/mod.rs#L1-L11

we can reduce a lot of derives, some things are used for testing (serde I believe) so these should be cfg for test

## TODO

* remove unused derives and cfg things only used for testing (serde)

eg:

https://github.com/paradigmxyz/reth/blob/2b20a0dbfcbc57322702404cf016476e58aa34cf/crates/storage/codecs/src/alloy/withdrawal.rs#L10-L13

**Comment by greged93** [comment]
I think this can be closed no?
