### ISSUE TITLE
Port BlockBody functions to alloy

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11208]
### Describe the feature

we can reuse alloy's BlockBody type that is now identical to:

https://github.com/paradigmxyz/reth/blob/1e0a35e744633e605cf6ddd24f4b1c9d73b198c2/crates/primitives/src/block.rs#L577-L674

if we remove as many functions there as possible:

https://github.com/alloy-rs/alloy/blob/241bc6ea91042c2e43dc95cf39427622be179b59/crates/consensus/src/block.rs#L28-L37

some of them must be restricted to `Transaction` trait.

some might not be possible rn

**Comment by PanGan21** [comment]
Hi! I was looking at this issue. I think new alloy release is required for this right?

**Comment by Abhishekkochar** [comment]
@mattsse don't we need to have the latest version of alloy for this? we can import BlockBody at current implemented version.

**Comment by mahmudsudo** [comment]
Hello! Can I get assigned on this one?
