### ISSUE TITLE
rpc: modify `ReceiptBuilder` `build` method

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#11219]
### Describe the feature

At the moment, the `build` method of `ReceiptBuilder` returns a `AnyTransactionReceipt` which is basically a `WithOtherFields`:

https://github.com/paradigmxyz/reth/blob/dba6c012955c3e84efde8b2d6eca97c481226588/crates/rpc/rpc-eth-types/src/receipt.rs#L121-L125

In order to unlock https://github.com/paradigmxyz/reth/issues/11165 and use `alloy_network::Ethereum` in `EthApiTypes` implementation for `EthApi`, we need to modify this in order to return something like:

```rust
/// Builds a receipt response from the base response body, and any set additional fields.
    pub fn build(self) -> TransactionReceipt {
        let Self { base, other } = self;
        base
    }
```

without the `WithOtherFields` wrapper. Related https://github.com/paradigmxyz/reth/pull/11192#discussion_r1774902826.

**Comment by edisontim** [comment]
Hey, I think I could do this, could I be assigned?
