### ISSUE TITLE
Move trie functions to alloy

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11211]
### Describe the feature

ref #11208

these are beneficial and can be used for things like txroot withdrawals root, etc:

https://github.com/paradigmxyz/reth/blob/1e0a35e744633e605cf6ddd24f4b1c9d73b198c2/crates/trie/common/src/root.rs#L21-L30

imo we can move these to alloy-trie or somewhere else @DaniPopes ?

**Comment by c0np4nn4** [comment]
Hello @mattsse, Can I take this one?

**Comment by DaniPopes** [comment]
Why not in alloy-trie?

**Comment by mattsse** [comment]
right, lets do alloy-trie @c0np4nn4

**Comment by c0np4nn4** [comment]
Hi, @mattsse 

I am planning to proceed with the following steps:

1. I will create a PR in the alloy-trie repository (https://github.com/alloy-rs/trie) to move all the code currently implemented under crates/trie into a new location.

2. In the reth repository, I will refer to the above PR and update the code to reference alloy-trie instead.

I plan to submit the PR for alloy-trie first. Could you please confirm if this approach is correct? If so, I will proceed immediately.

Thank you!

**Comment by c0np4nn4** [comment]
@mattsse 
I made a PR at [alloy-trie, #53](https://github.com/alloy-rs/trie/pull/53). 
Please check it out and let me know if there are any corrections needed, and I'll address them ASAP.
