### ISSUE TITLE
Consensus Factory

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#1122]
Create `ConsensusFactory` to allow initializing different consensus implementations (beacon, clique ...) at runtime.

cc @onbjerg

**Comment by ryanorendorff** [comment]
@rkrasiuk is the idea behind this feature to enable reth to be a client that starts a PoA clique network?

**Comment by onbjerg** [comment]
No longer relevant I think, maybe we revisit later (cc @rkrasiuk)
