### ISSUE TITLE
A pre-configured trusted peer will not be retried if it is banned at startup.

### ISSUE THREAD

**Issue by alexgao001** [paradigmxyz/reth#11244]
### Describe the bug

Currently, when running the Reth Node with the flags

` --disable-discovery
   --trusted-only
   --trusted-peers  `. 

the node communicates exclusively with trusted peers. If a handshake with a trusted peer fails, the peer may be added to a ban list. However, even if a banned peer is later evicted, it cannot be selected again for a handshake, which can lead to the node getting stuck.

### Steps to reproduce

1. Start a node with the following flags:

` --disable-discovery
   --trusted-only
   --trusted-peers  `.

Also, adjust the configuration values:

```
[peers]
ban_duration = "30s"
```

```
[peers.backoff_durations]
low = "30s"
medium = "30s"
high = "30s"
max = "30s"
```

2. Simulate an invalid handshake https://github.com/paradigmxyz/reth/blob/353fd60d29ed9b1dac752b8d9eaed7da4b6118a2/crates/net/ecies/src/stream.rs#L85 resulting in the trusted peer being banned.

3. As a result, the node may become stuck.

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

v1.0.6

### What database version are you on?

v1.0.6

### Which chain / network are you on?

BSC

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> even if a banned peer is later evicted, it cannot be selected again for a handshake

can you elaborate on this a bit more?

https://github.com/paradigmxyz/reth/blob/65f26644719231949f9701d6d3b884b387487c97/crates/net/network/src/peers.rs#L906-L911

**Comment by alexgao001** [comment]
@mattsse Sure, for the previously banned peer that is evicted now, it will not be selected to make the outbound connection.
https://github.com/paradigmxyz/reth/blob/3a255a1cabd1f19399b42c1fe9bdcc130ac61c2e/crates/net/network/src/peers.rs#L846

**Comment by mattsse** [comment]
oh I think I've found it
