### ISSUE TITLE
Add Testing support for EthApi RPC handler

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1125]
### Describe the feature

now that the `EthApi` handler only depends on traits we can easily implement testing support.

## TODO
* start with test for #1123
1. create an `EthApi` instance with a Pool and Client (perhaps not even required if we optimize trait bounds for impl Block)
2. submit raw transaction to EthApi -> Hash
3. fetch transaction from pool via hash

**Comment by naviechan** [comment]
First time contributor here, will be a bit slow but I am happy to take this one on.

**Comment by mattsse** [comment]
awesome! happy to help, simply open a draft and we go from there.
