### ISSUE TITLE
all ecies error are treated as fatal

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11259]
### Describe the feature

discovered during #11244 and #11254

https://github.com/paradigmxyz/reth/blob/2e05ec008a85576c146afb8325cfc48e1785da10/crates/net/network/src/error.rs#L217-L217

these include various variants that are not "fatal"

https://github.com/paradigmxyz/reth/blob/2e05ec008a85576c146afb8325cfc48e1785da10/crates/net/ecies/src/error.rs#L26-L87

## TODO
we need more detailed matching here and only treat hard crypto errors as fatal.

see https://github.com/paradigmxyz/reth/blob/2e05ec008a85576c146afb8325cfc48e1785da10/crates/net/network/src/error.rs#L123-L123

**Comment by caglaryucekaya** [comment]
Hey, I'd like to work on this
