### ISSUE TITLE
Remove unsafe from `impl Compact for ClientVersion`

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#11294]
### Describe the feature

Remove unsafe calls to `String::from_utf8_unchecked` in `impl Compact for ClientVersion`.
Done by implementing `Compact` for `String`, and using `String::from_compact` instead.
The compact implementation should just delegate to `Vec<u8>` and call `String::from_utf8().unwrap()`

**Comment by 0xriazaka** [comment]
Can i work on this?

**Comment by DaniPopes** [comment]
Sure!
