### ISSUE TITLE
Format Pool errors in RPC response the same way geth does

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1131]
### Describe the feature

if submitting a transactions to the pool fails, we get a `PoolError`, this error is then converted to an RPC error response.

The message should mirror geth's error messages.

It is intended that this type does some format conversion:

https://github.com/paradigmxyz/reth/blob/1642d77dcd2cf2190f99189ba690ce3403989b55/crates/net/rpc/src/eth/error.rs#L26-L30

so we can mirror geth's error messages

https://github.com/ethereum/go-ethereum/blob/5d8bff1d7261aed1a68235b0223d44a4fb4fb259/core/txpool/txpool.go#L58-L90

**Comment by chirag-bgh** [comment]
I would like to take this.
