### ISSUE TITLE
Add `account_code` helper function to `AccountProvider`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1132]
### Describe the feature

fetching the code of an account requires two steps:
1. fetch account via `basic_account`
2. fetch code_by_hash if account's code hash is not `KECCAK_EMPTY` (code is stored separately)

**Comment by chirag-bgh** [comment]
Hey @mattsse , how to fetch code_by_hash using account's bytecode_hash? I'm stuck at this thing.

**Comment by mattsse** [comment]
I guess we'd need to combine some traits for this
I believe we already have a trait that Has code_by_hash which perhaps should be moved to accountProvider
