### ISSUE TITLE
Use `MeteredSender` for ActiveSession Sender Half

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1133]
### Describe the feature

Wrap the bounded session message channel into a `MeteredSender` so we can monitor messages sent from the sessions.

https://github.com/paradigmxyz/reth/blob/1642d77dcd2cf2190f99189ba690ce3403989b55/crates/net/network/src/session/mod.rs#L92-L94

https://github.com/paradigmxyz/reth/blob/1642d77dcd2cf2190f99189ba690ce3403989b55/crates/net/network/src/session/active.rs#L76-L77

## TODO
* add Clone to `MeteredSender`
* use `MeteredSender` in SessionManager and ActiveSession with dynamic scope `network_active_session`

**Comment by leruaa** [comment]
I would like to take this on.

**Comment by leruaa** [comment]
This issue should have been closed by the PR #1150, I forgot the "Closes #1133" mention
