### ISSUE TITLE
Add execution witness codes support 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11347]
### Describe the feature

with https://github.com/alloy-rs/alloy/pull/1390

we now can set the ap of all contract codes (created / accessed) to their preimages that were required during the execution of the block:

https://github.com/paradigmxyz/reth/blob/6d57b9eaac0c093feb453f8f4d2bef90e28e8993/crates/rpc/rpc/src/debug.rs#L670-L670

## TODO

* populate codes field

**Comment by YashBit** [comment]
@mattsse I can try this out. A little hesitant, wanted to start with a good first issue. But they seem to be taken away quite quickly!

**Comment by mattsse** [comment]
actually this was solved already
