### ISSUE TITLE
Simplify BlockState to (Sealed)BlockWithSenders

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11342]
### Describe the feature

currently we do this a lot:

https://github.com/paradigmxyz/reth/blob/24b6341205dcc3f421875d7b2be6d90d68220d28/crates/storage/provider/src/providers/blockchain_provider.rs#L619-L621

we could simplify this with a function on BlockState that is

```rust
fn block_with_senders(&self) -> BlockWithSenders
```

this will require internal clones but this is fine

**Comment by greged93** [comment]
hey can I work on this?
