### ISSUE TITLE
Add atomic range API for `get_state`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#11356]
ref https://github.com/paradigmxyz/reth/pull/11265#issuecomment-2383947440

We should create a range-based atomic API for `get_state`, since the current API requires the user to run it in a loop if they want to get N different `ExecutionOutcome`s. We should provide a block-range API that can be called outside the tree, similar to the other recently added atomic range APIs:
https://github.com/paradigmxyz/reth/pull/11332
https://github.com/paradigmxyz/reth/pull/11340

**Comment by aroralanuk** [comment]
Not 100% sure I can close this off but I can give it a go over the weekend. Can you assign this to me?

Also related to https://github.com/paradigmxyz/reth/issues/11497
