### ISSUE TITLE
Unify StateProviderFactory StateProvider types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1137]
### Describe the feature

Currently, the factory has two different types for accessing State

https://github.com/paradigmxyz/reth/blob/1642d77dcd2cf2190f99189ba690ce3403989b55/crates/storage/provider/src/traits/state.rs#L20-L27

Which makes sense, since we need two different implementations I suppose? (@rakita)

eventually, we also need a Pending state.

in RPC it'd be more convenient to return a single type.

we could either replace `LatestSP` and `HistorySP` with a single associated type.
or add something like

```rust
enum StateProvider<H,L,P> {
 History(H),
 Latest(L),
 Pending(P)
}
```

But unsure how an implementation of `History` would differ from `Latest`

**Comment by rakita** [comment]
`Latest` touches `PlainState` tables while `History` touches `HistoryIndex`/`Changesets`/`PlainState` to get the needed past state. `Latest` is simpler and faster. 

`Pending` is going to be added after work on BlockchainTree is finished.

Could you maybe cast them to `StateProvider` trait (with generic or box them), they are different structures but implement the same trait?
