### ISSUE TITLE
Trigger graceful NetworkManager shutdown in

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11386]
### Describe the feature

we already have the relevant logic to gracefully disconnect peers:

https://github.com/paradigmxyz/reth/blob/86f12b7f535b649b4b78e4881db106c96d0d6114/crates/net/network/src/manager.rs#L605-L612

and usually the network is polled like:

https://github.com/paradigmxyz/reth/blob/86f12b7f535b649b4b78e4881db106c96d0d6114/crates/net/network/src/manager.rs#L956-L957

which drops the network on completion, we can gracefully shutdown the network before we invoke the hook:

https://github.com/paradigmxyz/reth/blob/86f12b7f535b649b4b78e4881db106c96d0d6114/crates/net/network/src/manager.rs#L973-L973

## TODO
* extract shutdown logic into a standalone function
* call this right before the `shutdown_hook` is invoked

**Comment by varun-doshi** [comment]
I'd like to take this up

**Comment by garwahl** [comment]
Ah apologies @varun-doshi I had an old instance of this issue open and didn't see you had this assigned

**Comment by varun-doshi** [comment]
Wow...okay
