### ISSUE TITLE
remove op Genesis conversions from reth-chainspec

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11396]
we still have

https://github.com/paradigmxyz/reth/blob/9c9b1fdf849992f0fa277e5135be3cbf8feb0139/crates/chainspec/src/spec.rs#L591-L603

now that we have chainspec abstracted we can remove this conversion and replace with standalone op function which is used:

https://github.com/paradigmxyz/reth/blob/9c9b1fdf849992f0fa277e5135be3cbf8feb0139/crates/optimism/cli/src/chainspec.rs#L20-L20

## TODO
* extract optimism specific From Genesis to optimism chainspec

we likely should do #11397 first, or maybe we need to this in one go

cc @greged93

**Comment by greged93** [comment]
will tal!
