### ISSUE TITLE
Reorder all `serde_bincode_compat` module definitions

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#11416]
### Describe the feature

We have a bunch of `serde_bincode_compat` modules across the crates, and most of them are defined after the `tests` module. It's weird and we should reorder it, so that `mod tests` goes last.

For example: https://github.com/paradigmxyz/reth/blob/a07efa7b5b83b9821631a9191e225a8c0bc42f0b/crates/primitives/src/transaction/mod.rs#L1970-L1982

**Comment by varun-doshi** [comment]
I can take this up
