### ISSUE TITLE
Possible wrong transaction hash on `eth_getLogs` during a reorg

### ISSUE THREAD

**Issue by joshieDo** [paradigmxyz/reth#11427]
This can happen in both the new and old engine when a `eth_getLogs` call is being processed while a reorg happens.

[logs_for_filter](https://github.com/paradigmxyz/reth/blob/b66e4f5ad32973e10eb31823e439dc9ba3335a95/crates/rpc/rpc/src/eth/filter.rs#L374C14-L374C29) will call the provider/cache to obtain all `logs` for a specific  block hash or range. (`view1`)

Eventually [append_matching_block_logs](https://github.com/paradigmxyz/reth/blob/b66e4f5ad32973e10eb31823e439dc9ba3335a95/crates/rpc/rpc-eth-types/src/logs_utils.rs#L102) will take these logs and query the provider (`view2`) by transaction number to obtain the corresponding transaction hash to fill in the `Log` field.

However, if between `view1` and `view2` there's a reorg, the transaction that we're matching the `Log` with is most likely wrong since we match it by `TxNum`

**Comment by malik672** [comment]
@joshieDo how should this be handled, should it throw an error?

**Comment by mattsse** [comment]
closing this like #11553
