### ISSUE TITLE
Populate requests in `get_state`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#11437]
Right now `get_state` does not populate requests:
https://github.com/paradigmxyz/reth/blob/0bf59eea514c3a8e24ebcece3fadf2d236e45389/crates/storage/provider/src/providers/database/provider.rs#L889-L895

The `RequestsProvider` method requires a timestamp which is not fetched in this method, so we may need to either refactor `get_state` (and the trait API), get the timestamp some other way, or refactor the `RequestsProvider` API.

**Comment by mattsse** [comment]
this might no longer be necessary depending on whether we actually need to store requests 
cc @onbjerg

**Comment by onbjerg** [comment]
still needed for rpc

**Comment by mattsse** [comment]
we no longer store them
