### ISSUE TITLE
`streams_bodies_in_order_after_range_reset` is flaky

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1144]
### Describe the bug

`bodies::bodies::tests::streams_bodies_in_order_after_range_reset` occasionally fails on main. A failure can be seen in CI here:
https://github.com/paradigmxyz/reth/actions/runs/4077743007/jobs/7027133041#step:8:203

### Steps to reproduce

Sometimes this can be reproduced locally with `cargo nextest run --workspace --locked --all-features`

### Node logs

```text
--- STDERR:              reth-downloaders bodies::bodies::tests::streams_bodies_in_order_after_range_reset ---
thread 'bodies::bodies::tests::streams_bodies_in_order_after_range_reset' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `7`', crates/net/downloaders/src/bodies/bodies.rs:616:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   Canceling due to test failure: 0 tests still running
```

### What version/commit are you on?

66aa947

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by gakonst** [comment]
cc @rkrasiuk

**Comment by rkrasiuk** [comment]
noted. will tackled first thing in the morning
