### ISSUE TITLE
Cleanup prepare_call_env function

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11464]
### Describe the feature

this currently accepts a gas limit field:

https://github.com/paradigmxyz/reth/blob/f1aae36c6950fb7c0f99d9b10f6743a515f097f0/crates/rpc/rpc-eth-api/src/helpers/call.rs#L1102-L1102

however we only call this with the configured call gas limit:

https://github.com/paradigmxyz/reth/blob/f1aae36c6950fb7c0f99d9b10f6743a515f097f0/crates/rpc/rpc-eth-api/src/helpers/call.rs#L448-L451

so this arg is kinda pointless.

also we should not disable gas_limit, because that's an anvil relict where this is safe.

## TODO:
* remove gas_limit arg
* remove disable gas_limit setting

**Comment by varun-doshi** [comment]
I can take this one
