### ISSUE TITLE
Integrate new tx type metrics in grafana dashboard

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11475]
### Describe the feature

new metrics introduce #11403

should be included in a new panel, next to https://github.com/paradigmxyz/reth/blob/399192c3471d6a88157236a0ab02b6facf45102c/etc/grafana/dashboards/reth-mempool.json#L516-L516

**Comment by No0key** [comment]
I can do this

**Comment by aroralanuk** [comment]
This issue should be closed cc @mattsse @emhane?
