### ISSUE TITLE
Add metrics for failed deliveries to grafana dashboard

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11470]
### Describe the feature

new metrics added #11456

## TODO
* integrate in a new panel, after `Engine API getPayloadBodies Latency` panel

**Comment by Parikalp-Bhardwaj** [comment]
@mattsse I can do this

**Comment by mattsse** [comment]
ref

https://github.com/paradigmxyz/reth/blob/ab069979867087b72c1dfe24b535cd997b3b5f4b/etc/grafana/dashboards/overview.json#L5732-L5732
