### ISSUE TITLE
Remove rlp support for sealed types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11484]
### Describe the feature

ref https://github.com/paradigmxyz/reth/issues/11123

we have rlp support for sealed types

https://github.com/paradigmxyz/reth/blob/b537672886e44e969bcb1af5820e2d6f3ef264a3/crates/primitives-traits/src/header/sealed.rs#L75-L98

this should never be used because the hash is recovered and never encoded in any payload

## TODO
* remove rlp support from sealed types, seems pointless, especially if there's a deref and the type should be created via `decode + seal`

### Additional context
cc @greged93 @emhane 

ref https://github.com/alloy-rs/core/pull/754

_No response_

**Comment by Parikalp-Bhardwaj** [comment]
Hii @mattsse, assign me

**Comment by edisontim** [comment]
Hello, can I take this one ?

**Comment by mattsse** [comment]
assigned

**Comment by mattsse** [comment]
oh actually I changed my mind about this after looking at the rlpdecode impl

because this is actually nice to have
