### ISSUE TITLE
Add helper to TransactionPool to obtain the highest Transaction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11489]
### Describe the feature

we have

https://github.com/paradigmxyz/reth/blob/d5ddb4129d3464d0f5cbfdd7547528bdb278cd59/crates/transaction-pool/src/traits.rs#L331-L335

but often we just want to know the highest transaction:

https://github.com/paradigmxyz/reth/blob/d5ddb4129d3464d0f5cbfdd7547528bdb278cd59/crates/rpc/rpc-eth-api/src/helpers/state.rs#L282-L286

## TODO

* add a helper function that does this `get_highest_transaction_by_sender`

because this function is called a lot, it's worth implementing this manually via the multiple pool layers, this will safe a smol amount of alloc and clone

like this:

https://github.com/paradigmxyz/reth/blob/d5ddb4129d3464d0f5cbfdd7547528bdb278cd59/crates/transaction-pool/src/pool/txpool.rs#L388-L394

**Comment by edisontim** [comment]
hey, can I work on this one?

**Comment by edisontim** [comment]
gm @mattsse, I linked a PR to close this. Is it what you had in mind?
