### ISSUE TITLE
reexport relevant crates from `op-reth`

### ISSUE THREAD

**Issue by ewoolsey** [paradigmxyz/reth#11493]
### Describe the feature

The `reth` crate reexports all/most of it's dependencies from a `lib.rs`. For users building on `op-reth` the same could be useful. 

I'd be happy to submit a PR if it would be welcome!

**Comment by mattsse** [comment]
reasonable

**Comment by mattsse** [comment]
do you want to take this?

**Comment by ewoolsey** [comment]
Yep, I'm on it! Thanks!

**Comment by ewoolsey** [comment]
Do you think it's wise to have 
```rust
pub use reth::*;
```
in lib.rs?

Essentially this would mean the `op-reth` reexports everything that `reth` does and would essentially be a superset. It's nice because it means less duplication of all the reexport code. Then for the optimism crates you can just prefix them like this:

```rust
pub mod optimism_payload {
    pub use reth_optimism_payload_builder::*;
}

```

**Comment by ewoolsey** [comment]
Additionally, how do you feel about reexporting all of the alloy/op-alloy types from reth/op-reth respectively?

users could use like this:
```rust
use reth::alloy::rpc_types::*;
use op_reth::op_alloy::rpc_types::*;
```

This would be pretty nice as it would prevent consumers from having to respecify all their alloy dependencies in their tomls (and having to match versions).
