### ISSUE TITLE
Reversion in behavior of debug_traceCallMany

### ISSUE THREAD

**Issue by dallonby** [paradigmxyz/reth#11494]
### Describe the bug

Hello,

The behaviour of debug_traceCallMany appears to have been broken.

Sending payload `{ "id": 6, "jsonrpc": "2.0", "method": "debug_traceCallMany", "params": [ [ { "transactions": [ { "from": "0x5203f3EcD1E2c3A31F0be85FC70d544A9045FB71", "to": "0x5203f3EcD1E2c3A31F0be85FC70d544A9045FB71", "value": 0 } ] } ] ] } ` results in...

`error: { code: -32000, message: 'intrinsic gas too high' }`

Trying again with reth v1.0.3 results in expected behavior.

### Steps to reproduce

Send payload to RPC endpoint

`{ "id": 6, "jsonrpc": "2.0", "method": "debug_traceCallMany", "params": [ [ { "transactions": [ { "from": "0x5203f3EcD1E2c3A31F0be85FC70d544A9045FB71", "to": "0x5203f3EcD1E2c3A31F0be85FC70d544A9045FB71", "value": 0 } ] } ] ] } `

### Platform(s)

Linux (x86)

### What version/commit are you on?

v1.0.8

### What database version are you on?

NA

### Which chain / network are you on?

mainnet

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by dallonby** [comment]
V1.0.6 also **doesnt** exhibit this behavior

**Comment by mattsse** [comment]
thanks for flagging, sorry about this...

fixed in #11505
