### ISSUE TITLE
Add helper function to replace one rpc function

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11492]
### Describe the feature

we already have:

https://github.com/paradigmxyz/reth/blob/d5ddb4129d3464d0f5cbfdd7547528bdb278cd59/crates/rpc/rpc-builder/src/lib.rs#L1868-L1868

and

https://github.com/paradigmxyz/reth/blob/d5ddb4129d3464d0f5cbfdd7547528bdb278cd59/crates/rpc/rpc-builder/src/lib.rs#L1809-L1812

a nice use case is to replace one specific function, so we'd like to have something like

```rust
fn replace_configured(&mut self, impl Into<Methods>)
```

the method name to remove we get from `Methods::method_names`

we also want this for individual transports ws,HTTP,ipc

**Comment by varun-doshi** [comment]
I can take this one
