### ISSUE TITLE
Add helper for consistent db and in-memory state access

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#11497]
Right now, in `BlockchainProvider::get_state` for example, we create many database transactions. If used outside of the tree, the in-memory state that is accessed during the life of the method may also change.

This means, if the `get_state` provider method is called outside of the tree, it could return inconsistent results or even fail. To solve this, we should add some helpers that acquires a read lock / transaction on the in-memory state, and the database. These helpers should allow methods like `get_state` to be implemented without opening multiple db transactions, while accessing a single view of the in-memory chain state.

**Comment by kdonthi** [comment]
Can you assign me to this?
