### ISSUE TITLE
Add a helper NetworkBuilder that allows overriding certain settings

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11504]
### Describe the feature

the NetworkBuilder is responsible for building the network instance:

https://github.com/paradigmxyz/reth/blob/72865f1d8344b192ec7af1a672384800bcb060d5/crates/optimism/node/src/node.rs#L330-L339

currently we don't have an easy way to simply override certain settings, e.g. in config.

A helper type that contains certain settings of NetworkArgs would be beneficial here, without having to reimplement the entire thing.

### Additional context
https://github.com/paradigmxyz/alphanet/issues/134

FYI @onbjerg 

_No response_

**Comment by onbjerg** [comment]
Is this resolved in #11506 and #11507 or is there more left?
