### ISSUE TITLE
Base op-reth Archival Node: Can't sync

### ISSUE THREAD

**Issue by DaveWK** [paradigmxyz/reth#11512]
### Describe the bug

I have attempted on a few different setups, but it does not appear I am able to sync an archival node (without --full)  and keep it in sync on AWS.
I am using a io2 storage (20k iops) with an r7a.2xlarge (64 gigs of ram, 8 AMD EPYC 9R14 cores) and it seems to keep looping through the pipeline stages but never catching up.. It seems like the culprit is MerkelExecute, and I cans ee from the performance that it is not a CPU-bound problem; the single core (since I assume this is a serlialized, single-thread step) is not maxed out, however my disk iops and utilization is always at 100%.. Also the amount of data being transferred is pretty small, so even with 20k iops I am only read/writing around 8 megs of data.

My suspicion is the mdbx file is too "sparse" and it needs some kind of online compaction or "defrag" but don't know how to debug this. Running mdbx_copy is not really a solution since it takes 5 hours to run  (and is not an online operation) and I am not able to sync from the available reth-base archive snapshot.

### Steps to reproduce

1. Download the base-reth archive
2. make op-maxperf
3.  `exec op-reth node --chain=base \
	--rollup.sequencer-http https://mainnet-sequencer.base.org \
	--http --http.port 8545 --ws --ws.port 8546 \
        --http.api=web3,debug,eth,net,txpool \
        --ws.api=web3,debug,eth,net,txpool \
	--metrics=127.0.0.1:9001 \
        --ws.origins="*" \
        --http.corsdomain="*" \
	--rollup.discovery.v4 \
	--engine.experimental \
	--authrpc.jwtsecret ${HOME}/jwt.hex \
	--datadir ${HOME}/oprethdata`
4. Wait around 5-ish hours and see that indeed it keeps looping through the pipeline and never catching up. The longest step regardless of number of blocks seems to be MerkleExec, which always takes around 2-3 hours.

### Platform(s)

Linux (x86)

### What version/commit are you on?

v1.0.8

### What database version are you on?

2

### Which chain / network are you on?

base mainnet

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

n/a

### If you've built Reth from source, provide the full command you used

make maxperf-op

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by DaveWK** [comment]
for the record, without `--engine.experimental` the performance is even worse

**Comment by mattsse** [comment]
same as https://github.com/paradigmxyz/reth/issues/11306

we haven't tried to reproduce this from the snapshot yet, but resynced base entirely on similar infrastructure as yours without any issues.
I wonder if this has anything to do with the most recent snapshot itself, will check.

resyncing base archive takes ~48hrs, so currently I'd recommend this

**Comment by DaveWK** [comment]
I tried to sync over the weekend "from scratch" by using the `db drop`  but still the same -- never catches up and keeps looping over the steps. I am trying now by just using `rm -rf db`  to see if that gets it in sync..

Should doing a `db drop` reset ALL indexes/counters/locks in mdbx? 

My working theory is that something is using a non-deterministic hash as some kind of "foreign key relation" and it's re-inserting or updating the same records over and over again, and it never does a true checkpoint.. Perhaps a table is using "wall clock time" as an index and diverges because an old record with another "wall clock time" but same hash exists?

Other suspicion: does MDBX have the concept of iterators such that an index/key and isn't being reset (or contains gaps in records?) 

Other thing of note "my safe db_hash"  reported by op-node is always 0x0000000000000 or whatever an all-zero record would be.. is something broken since it never sets a "safe" hash for a checkpoint?

**Comment by Rjected** [comment]
> My working theory is that something is using a non-deterministic hash as some kind of "foreign key relation" and it's re-inserting or updating the same records over and over again, and it never does a true checkpoint.. Perhaps a table is using "wall clock time" as an index and diverges because an old record with another "wall clock time" but same hash exists?

This is definitely not it, but I wonder if this is because of how op-node chooses ranges to sync, combined with poor / high latency disk

**Comment by DaveWK** [comment]
thanks for the clarification on that -- I think the disk latency may be symptomatic rather than a root cause -- I have 20k provisoned iops on an aws io2 volume and it's saturating the iops but only reading/writing less than 10 megs total..

This log from op-node seems to be wonky but can't tell if it's just a bad log message:

```t=2024-10-07T15:34:03+0000 lvl=info msg="Sync progress" reason="new chain head block" l2_finalized=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_safe=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_pending_safe=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_unsafe=0xb09fad979d89096372aadd19969428526cdee2e2959dd676f987d0b5abefdbbe:20762948 l2_backup_unsafe=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_time=1728315243```

the fact that the finalized/safe/pending_safe never changes would support the theory that it's resyncing the same ranges every time, but could also just be bad logging

**Comment by DaveWK** [comment]
Also curious if safe/finalized should ever actually be `0x00` since it would seem that having the genesis block values be the "lowest" a node can wind back to would at least prevent these null/zero variable issues.

**Comment by bix29** [comment]
I encountered the same issue, when I tried to do the initail sync from the `Base mainnet` arhive snapshot with` --syncmode=execution-layer`
1. the `MerkleExecute` stage of op-reth is slow, seems cannot catchup the latest block forever
`ts=2024-10-18T01:00:11.571181174Z level=info target=reth::cli message=Status connected_peers=30 stage=MerkleExecute checkpoint=21195263 target=21204568 stage_progress=87.39% stage_eta="32m 12s"`
2. `t=2024-10-18T01:02:57+0000 lvl=info msg="Sync progress" reason="new chain head block" l2_finalized=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_safe=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_pending_safe=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_unsafe=0x3d813e78926bbdefe1fc5cb7a87470de1216c0393ab13c5d860ce54a6d1ab665:21212015 l2_backup_unsafe=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_time=1729213377`

**Comment by bix29** [comment]
seems when the progress of `MerkleExecute` reaches 51.1%, the stage will hang for a long time, 1~2 hours
