### ISSUE TITLE
Copy OP execution outcome tests

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#11534]
### Describe the feature

Copy all tests that have an `optimism` feature gate inside, into optimism evm crate. For the copies, remove the optimism feature gate. For the originals, remove the optimism feature gated code completely.

https://github.com/paradigmxyz/reth/blob/6a1ec0d1a20436a79aee612c68749abc3411ec6b/crates/evm/execution-types/src/execution_outcome.rs#L365-L891

**Comment by Parikalp-Bhardwaj** [comment]
hi @emhane, assign me please

**Comment by Parikalp-Bhardwaj** [comment]
hi @emhane, assign me
