### ISSUE TITLE
Define trait `TxType`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#11531]
### Describe the feature

Define trait `reth_primitives_traits::TxType`. This trait should implement behaviour of `reth_primitives::TxType` and hence  doesn't seem to need any trait methods. It should take as super traits all the `From`/`TryFrom` impls for `TxType` (and those `From<TxType>`/`TryFrom<TxType>` impls that translate to `Into<T>`/`TryInto<T>` impls). Additionally it should take as super traits all the trait bounds on `alloy_consensus::Network::TxType

https://github.com/alloy-rs/alloy/blob/48be08ff0bea3ce49f09ac2d60aaaa3c850dda0b/crates/network/src/lib.rs#L39-L54

**Comment by 0xriazaka** [comment]
assign me
