### ISSUE TITLE
Copy OP evm chain tests

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#11535]
### Describe the feature

Copy all tests that have an `optimism` feature gate inside, into optimism evm crate. For the copies, remove the optimism feature gate. For the originals, remove the optimism feature gated code completely.

https://github.com/paradigmxyz/reth/blob/6a1ec0d1a20436a79aee612c68749abc3411ec6b/crates/evm/execution-types/src/chain.rs#L631-L846

**Comment by 0xriazaka** [comment]
Can i work on this?

**Comment by emhane** [comment]
duplicate of https://github.com/paradigmxyz/reth/issues/11111
