### ISSUE TITLE
Define trait `Transaction`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#11533]
### Describe the feature

Define trait `reth_primitives_traits::Transaction`. This trait should implement behaviour of `reth_primitives::Transaction` and have as supertrait `alloy_consensus::Transaction`, as well as any traits implemented on `reth_primitives::Transaction` e.g. `From`/`TryFrom` impls for `reth_primitives::Transaction` (and those `From<reth_primitives::Transaction>`/`TryFrom<reth_primitives::Transaction>` impls that translate to `Into<T>`/`TryInto<T>` impls).

Many of the methods implemented on `reth_primitives::Transaction` overlap with `alloy_consensus::Transaction`, so make sure to not include those in the new trait.

**Comment by edisontim** [comment]
Hey @emhane can I get assigned on this one?
