### ISSUE TITLE
`debug_traceCallMany` returns unexpected result

### ISSUE THREAD

**Issue by geomad** [paradigmxyz/reth#11541]
### Describe the bug

In the past `debug_traceCallMany` with  `tracer: 'prestateTracer'` and `tracerConfig: { diffMode: true }` would return the addresses inside `post` and `pre` in lowercase.
Since the latest release those addresses are checksumed.

### Steps to reproduce

`debug_traceCallMany`

### Platform(s)

Linux (x86)

### What version/commit are you on?

Commit SHA: ab069979867087b72c1dfe24b535cd997b3b5f4b

### What database version are you on?

2

### Which chain / network are you on?

mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
yeah Address now serializes as checksumed address, which is still valid hex, so this is likely a no-fix

**Comment by geomad** [comment]
> yeah Address now serializes as checksumed address, which is still valid hex, so this is likely a no-fix

Aren't we aiming though to standarize  / be as close as possible on the api as the other clients? I believe erigon returns lowercase (as reth did), unless they changed it as well, since I have not used them for a long time.

Geths `debug_traceCall` with `{ tracer: 'prestateTracer', tracerConfig: { diffMode: true  } }` args also returns everything in lowercase.

In my case, my scripts were broken with that change.

**Comment by dallonby** [comment]
This was a breaking change for me too.  Erigon and geth both return the keys lowercased.

**Comment by mattsse** [comment]
ref https://github.com/alloy-rs/core/pull/765
