### ISSUE TITLE
Add OpChainSpecBuilder type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11561]
### Describe the feature

OpChainSpec on ChainSpec are now separate types, we also need to separate the builder type:

https://github.com/paradigmxyz/reth/blob/5e288b2469e889b41e5df16ce01951fedf4b2b55/crates/chainspec/src/spec.rs#L727-L727

so that we can get rid of 

https://github.com/paradigmxyz/reth/blob/5e288b2469e889b41e5df16ce01951fedf4b2b55/crates/chainspec/src/spec.rs#L879-L934

this new OpChainSpec builder type can follow a similar patter as `OpChainSpec` and simply wrap the `ChainSpec` builder and introduce the op specific functions

**Comment by greged93** [comment]
Hey Matt, can I work on this?
