### ISSUE TITLE
EIP-4844 RPC receipt for Optimism

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#11619]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/076b1a2c226732591b0743b02dbfbfff070b5e4d/crates/optimism/rpc/src/eth/receipt.rs#L259-L262

https://github.com/paradigmxyz/reth/pull/11617#discussion_r1793811935

**Comment by mattsse** [comment]
marking this as completed because in reality unreachable and will go away naturally once we have network specific tx types
