### ISSUE TITLE
Use budgeted poll macro 

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#11649]
### Describe the feature

Use existing pattern for budgeted poll of sub streams + remove magic number for budget in https://github.com/paradigmxyz/reth/pull/11647

For example as has been done in the transactions manager
https://github.com/paradigmxyz/reth/blob/1ba631ba9581973e7c6cadeea92cfe1802aceb4a/crates/net/network/src/transactions/mod.rs#L1257-L1264

A macro without use of metrics also exists
https://github.com/paradigmxyz/reth/blob/1ba631ba9581973e7c6cadeea92cfe1802aceb4a/crates/net/network/src/budget.rs#L45-L71

**Comment by Rjected** [comment]
rather than a macro, could we extract the macro functionality to a struct somehow? macros can be hard to debug / make it harder to read and understand what's actually going on

**Comment by ayoubed** [comment]
I can take this.

**Comment by mattsse** [comment]
I think we have this everywhere where we can/want to use this
