### ISSUE TITLE
Persist most recent safe block

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11644]
### Describe the feature

same as 

https://github.com/paradigmxyz/reth/blob/d027b7b9389a9e8ab88f9f7171490696ad423a36/crates/storage/db/src/tables/mod.rs#L417-L418

but for the safe block

## TODO

* add variant
* extend and rename trait: 

https://github.com/paradigmxyz/reth/blob/d027b7b9389a9e8ab88f9f7171490696ad423a36/crates/storage/provider/src/traits/finalized_block.rs#L4-L16

store safe block same as 

https://github.com/paradigmxyz/reth/blob/d027b7b9389a9e8ab88f9f7171490696ad423a36/crates/engine/tree/src/tree/mod.rs#L2375-L2382

but for

https://github.com/paradigmxyz/reth/blob/d027b7b9389a9e8ab88f9f7171490696ad423a36/crates/engine/tree/src/tree/mod.rs#L2404-L2406

**Comment by Benjtalkshow** [comment]
@mattsse 
Can I be assigned to this issue? I will tackle it as soon as possible. Thanks

**Comment by devcollinss** [comment]
Can I  be assigned this issue?

**Comment by mattsse** [comment]
this was more urgent, so I took it, ty
