### ISSUE TITLE
Add `TransactionSigned::decode_enveloped`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1165]
### Describe the bug

The reason for this is because the encoded transaction (eth_sendRawTransaction) input is not valid rlp.

instead, it is an rlp list enveloped with the transaction type for typed transactions.

we want a separate function to keep it separate from the `rlp::Decodeable` impl and need to make this very clear in the docs.

### Steps to reproduce

-

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by literallymarvellous** [comment]
I'd like to take this. 

For the better context, we're adding a decode_enveloped() to ```TransactionSigned``` that decodes a eth_sendRawTransaction input which is of type ```Bytes``` to itself.

ie. ```decode_enveloped(self, raw: Bytes) -> TransactionSigned```

**Comment by mattsse** [comment]
it should mirror the rlp decode implementation:

https://github.com/paradigmxyz/reth/blob/ba70b3b7ef7776770cb675f2cb9fd927bb5646be/crates/primitives/src/transaction/mod.rs#L643

This part is basically already the decode_enveloped impl for typed transactions

https://github.com/paradigmxyz/reth/blob/ba70b3b7ef7776770cb675f2cb9fd927bb5646be/crates/primitives/src/transaction/mod.rs#L650-L691

but we need also a check for legacy transaction, like:

https://github.com/foundry-rs/foundry/blob/master/anvil/src/eth/api.rs#L783

**Comment by gakonst** [comment]
Where is this function going to be used?

**Comment by mattsse** [comment]
rpc

the `sedRawTransaction` bytes blob is not rlp but `[id, rlp(typedtx)]`
