### ISSUE TITLE
Add testing with persistence mocks

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11676]
we now have a way to mock long running db ops

https://github.com/paradigmxyz/reth/blob/5e1bd04941604156c9c212f19174044592410d37/crates/storage/db/src/lib.rs#L77-L80

and we should use this for engine tree tests

https://github.com/paradigmxyz/reth/blob/5e1bd04941604156c9c212f19174044592410d37/crates/engine/tree/src/tree/mod.rs#L2644-L2644

this requires some changes so that the type also works with a real db

scenarios we should cover:

* long running disk io during
* + reorgs

**Comment by nadtech-hub** [comment]
Do you mind if I do it?
