### ISSUE TITLE
Disable read tx timeout on long-running RPCs

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#11672]
If you run reth with a long eth proof window, and try to call e.g.:
* `eth_getProof`, or
* `debug_executionWitness`

Then you may run into a read tx timeout if trying to fetch a witness that is very far back. The read tx timeout should be disabled when calling these
```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/11760
- [ ] https://github.com/paradigmxyz/reth/issues/11758
```

**Comment by 0x00101010** [comment]
@Rjected I believe this is done by https://github.com/paradigmxyz/reth/pull/11856

**Comment by Rjected** [comment]
yep, thx
