### ISSUE TITLE
Improve P2PStream sink logic

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11677]
### Describe the feature

in #11658 was optimistically reverted with the hope that this fixes #11675

however, the previous solution was slightly better as it tried to make better use of the underlying framed buffer, but only ever writing one item prior flush.

we should change this starting from the how we advance the sink.

as @emhane pointed out in #9498 we should really leverage the buffer more and therefore need to change:

https://github.com/paradigmxyz/reth/blob/5e1bd04941604156c9c212f19174044592410d37/crates/net/network/src/session/active.rs#L552-L569

so that we do 
poll_read -> send
flush last

**Comment by emhane** [comment]
> but only ever writing one item prior flush
that was the original solution prior to https://github.com/paradigmxyz/reth/pull/9498

> so that we do
poll_read -> send
flush last

that's what https://github.com/paradigmxyz/reth/pull/9498 did

**Comment by emhane** [comment]
do we want to look at the sink implementations for higher layers too? like `EthStream`?
