### ISSUE TITLE
extend txpool remove_txs utility

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11684]
### Describe the feature

this isn't used by any component but is a nice utility:

https://github.com/paradigmxyz/reth/blob/43fe46f0d340fdf27e6b1b51916d0ecf9f6c314b/crates/transaction-pool/src/traits.rs#L294-L302

but I consider

https://github.com/paradigmxyz/reth/blob/43fe46f0d340fdf27e6b1b51916d0ecf9f6c314b/crates/transaction-pool/src/traits.rs#L296-L296

a footgun.
there should be two functions for this behavior:
* one that only pops the tx by hashes
* one that pops the tx by hashes and their dependent transactions

**Comment by caglaryucekaya** [comment]
Hi, I'd like to work on this

**Comment by caglaryucekaya** [comment]
@mattsse I need some help here. It looks like the implementation of `remove_transactions` only removes the transactions with the given hashes, and no other dependent transactions. Am I missing something?

**Comment by mattsse** [comment]
could be that the docs are wrong -.-

in that case we also want something like remove_transactions_and_dependents

**Comment by caglaryucekaya** [comment]
@mattsse Another question: Is a dependent transaction a transaction that follows the given transaction and has the same sender? Like what the `descendant_txs_exclusive` and `descendant_txs_inclusive` methods are returning?
