### ISSUE TITLE
base chain: op-reth nonce returns an error when getting transaction data

### ISSUE THREAD

**Issue by rayn316** [paradigmxyz/reth#11708]
### Describe the bug

The nonce value is inconsistent with the actual user nonce

### Steps to reproduce

Use the request request node to view the nonce in the returned data and compare it with the browser.

curl --location --request POST 'http://127.0.0.1:21601' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--data-raw '{
	"jsonrpc":"2.0",
	"method":"eth_getTransactionByBlockHashAndIndex",
	"params":[
		"0xd75603fddf8651d797bf4c7c6f36e404726a6a9771b6fd66b4337bd0207f5a9d", 
		"0x0"
	],
	"id":1
}'

### Platform(s)

Linux (x86)

### What version/commit are you on?

v1.1.0

### What database version are you on?

2024-10-14T08:30:26.080146Z  INFO Initialized tracing, debug log directory: /root/.cache/reth/logs/dev
Current database version: 2
Local database version: 2

### Which chain / network are you on?

base

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
could you please elaborate, 
what error is returned, what is inconsistent?

**Comment by rayn316** [comment]
> could you please elaborate, what error is returned, what is inconsistent?

This account obviously has a lot of transactions, nonce should not be 0x0.
https://basescan.org/address/0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001

result info, 
```
    "nonce": "0x0",
``` 
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/dcd017f2-d546-44da-9547-80c4223b776d">

**Comment by emhane** [comment]
the missing deposit receipt version is solved by a pretty big change which is making `TransactionCompat` stateful (adding ref to self as arg to `TransactionCompat::fill`), as mentioned in https://github.com/paradigmxyz/reth/pull/11440#issuecomment-2405081663

**Comment by rayn316** [comment]
Do I need to resynchronize the node for this to take effect? ​​After upgrading the software to v1.1.1, the nonce returned by the transaction request has not changed.
Nonce still returns 0x0
```
curl -s -X POST -H "Content-Type":application/json --data '{"method":"eth_getTransactionByHash","params":["0x0089734ba94159246d3c343b72b44fe034b053075c32f764b2816c342e62946e"],"id":1,"jsonrpc":"2.0"}' http://127.0.0.1:21601 |jq
```
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/ec151565-ce27-47ca-999e-5452c5bbc6c8">

**Comment by rayn316** [comment]
Or is it because of the huge transaction volume of this address?  https://basescan.org/address/0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001
Return normal Nonce when querying other users' transactions

**Comment by mattsse** [comment]
for rpc, the noce field is the  tx receipt's nonce field

**Comment by mattsse** [comment]
looks like we just need to use the nonce here

https://github.com/paradigmxyz/reth/blob/3a337cd7d4ad8c14569d20141fdcc2b1c54dbdf3/crates/optimism/rpc/src/eth/transaction.rs#L111-L111

I believe we already had this at some point
