### ISSUE TITLE
trace_filter returns random results

### ISSUE THREAD

**Issue by s1na** [paradigmxyz/reth#11711]
### Describe the bug

I am using `trace_filter` to check the txes to/from an account. Reth is returning results that do not involve that address in any way.

### Steps to reproduce

Query:

```terminal
curl -X POST --data '{"jsonrpc":"2.0","id":1,"method":"trace_filter","params":[{"fromBlock":"0x13f7ab5","toBlock":"0x13f7ad3","toAddress":["0x897a96Deb94291B785fAfF64088f7202A019f38e"],"after":100,"count":100}]}' -H 'Content-Type: application/json'
```

This should return an empty result as does Erigon. This is because of the `after` being set to 100.

### Platform(s)

Linux (x86)

### What version/commit are you on?

I am not running the node myself. Is it possible to get this via API?

### What database version are you on?

I am not running the node myself. Is it possible to get this via API?

### Which chain / network are you on?

Ethereum mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by greged93** [comment]
@shekhirin can I help out on this? I think it's just because we never use the `from_address` and `to_address` filters.
https://github.com/paradigmxyz/reth/blob/b6371018944e8cba6f5b4c56e76ff211b9e820b1/crates/rpc/rpc/src/trace.rs#L255

**Comment by mattsse** [comment]
@jsvisa I believe this matching change is responsible for this https://github.com/alloy-rs/alloy/commit/338b5b94daddbf8a5bedff3dfc5f4f5c4fcdf177

because this will now match anything by default because it treats empty lists as matches, which makes single toAddresss OR fromAddress filters pretty much useless unless mode is intersection

@s1na could you try with `"mode": "intersection"` ?

**Comment by s1na** [comment]
@mattsse Yep the "mode": "intersection" makes it return result for the correct address. However the "after" field is basically not doing anything. "after: 0" returns the same as "after: 1000"

**Comment by mattsse** [comment]
hmm, tbh I don't really know what 

> The offset trace number

is even supposed to be, I think rn this removes the first `after` traces from the result
