### ISSUE TITLE
Move block traits to reth-primitivie-traits

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11725]
these files aren't even in use

https://github.com/paradigmxyz/reth/blob/9f9de0fab96712761944806120b1764cf1bee0eb/crates/primitives/src/traits/mod.rs#L1-L1

they should be moved to reth-primitive-traits

**Comment by vandenbogart** [comment]
I can take this as a first issue

**Comment by vandenbogart** [comment]
The `Block` and `BlockBody` traits have a number of dependencies on other types in `reth-primitives`. Adding that as a dependency to `reth-primitives-traits` creates a circular dependency. Is there a simple way to resolve this that I don't know about?

**Comment by mattsse** [comment]
hmm, good point, need to look into this first

**Comment by Rjected** [comment]
Duplicate: https://github.com/paradigmxyz/reth/issues/11757
Solved by: https://github.com/paradigmxyz/reth/pull/11780
