### ISSUE TITLE
Replace receipt envelope encoded with trait

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11737]
this should be a trait impl:

https://github.com/paradigmxyz/reth/blob/0b6397217ca47fe7cd7f5d30963564f8e63dead8/crates/primitives/src/receipt.rs#L208-L228

`Encodable2718` instead

## TODO
* replace envelope fns with trait impl

**Comment by TropicalDog17** [comment]
Can i work on this @mattsse?

**Comment by mahmudsudo** [comment]
can i take on this ?
