### ISSUE TITLE
Introduce trait for OpTransaction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11736]
we have extra helpers for deposit functions:

https://github.com/paradigmxyz/reth/blob/0b6397217ca47fe7cd7f5d30963564f8e63dead8/crates/primitives/src/transaction/mod.rs#L485-L519

these should be converted into a trait on https://github.com/alloy-rs/op-alloy and implemented on 

https://github.com/alloy-rs/op-alloy/blob/56f636e8f624164fdea9c5356ee59b40af8f5e9d/crates/consensus/src/transaction/deposit.rs#L15-L15

**Comment by hoank101** [comment]
hi @mattsse Can i work on this?
