### ISSUE TITLE
Add txpool function to find the next free nonce 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11739]
### Describe the feature

we need a function that given an on chain nonce it should return the next missing nonce by an address

this is similar to 

https://github.com/paradigmxyz/reth/blob/0b6397217ca47fe7cd7f5d30963564f8e63dead8/crates/transaction-pool/src/traits.rs#L353-L357

but should also accept a nonce and return the highest transaction without a nonce gap

**Comment by kien6034** [comment]
i would like to work on this

**Comment by onbjerg** [comment]
Thanks! I've assigned you to the issue. If you feel stuck, open up a draft PR with your questions and someone will help you. If you are prevented from solving the issue, let me know and I will unassign you :smile:

**Comment by kien6034** [comment]
thank you
