### ISSUE TITLE
Use next free nonce in `eth_sendTransaction`

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#11740]
### Describe the feature

Currently we use the highest nonce in the pool or on disk, whichever is higher, in `eth_sendTransaction`, but this can lead to nonce gaps. Instead we should use the next free nonce:

https://github.com/paradigmxyz/reth/blob/5e386130da0b123e107f5eb5a9a3a3622bc50129/crates/rpc/rpc-eth-api/src/helpers/transaction.rs#L366-L370

Depends on https://github.com/paradigmxyz/reth/issues/11739

**Comment by caglaryucekaya** [comment]
Can I take this one?
