### ISSUE TITLE
Introduce new that represents the variants of all versioned payload types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11748]
### Describe the feature

currently both op and eth have the same payload types, 

https://github.com/paradigmxyz/reth/blob/5e386130da0b123e107f5eb5a9a3a3622bc50129/crates/engine/primitives/src/lib.rs#L34-L35

hence we're able to do use:

https://github.com/paradigmxyz/reth/blob/5e386130da0b123e107f5eb5a9a3a3622bc50129/crates/payload/primitives/src/payload.rs#L8-L11

with https://github.com/alloy-rs/alloy/pull/1480 this will no longer be the case and we need helpers to make this work

## TODO
* introduce an enum that is generic over `EngineTypes` and has 4 variants

```rust
enum ExecutionPayload<T: EngineTypes> {
 V1(T::ExecutionPayloadV1),
 ...
}
// and a ref type that takes &'a as variant values
enum ExecutionPayloadRef
```

* replace https://github.com/paradigmxyz/reth/blob/5e386130da0b123e107f5eb5a9a3a3622bc50129/crates/payload/primitives/src/payload.rs#L5-L11 with `T: EngineTypes` and use that type instead

ref https://github.com/alloy-rs/alloy/pull/1480
cc @cody-wang-cb

**Comment by PanGan21** [comment]
Nice, it seems though that if `EngineTypes` is imported in `reth-payload-primitives` there will be a cyclic dependency issue.
What would be a good way to work around this issue?

**Comment by YashBit** [comment]
@mattsse Please can you assign this to me.
