### ISSUE TITLE
remove &self from update_estimated_gas_range

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11754]
### Describe the feature

this should be a standalone function instead:

https://github.com/paradigmxyz/reth/blob/5e386130da0b123e107f5eb5a9a3a3622bc50129/crates/rpc/rpc-eth-api/src/helpers/call.rs#L915-L922

## TODO
* remove self

**Comment by greged93** [comment]
Hey Matt can I take this?
