### ISSUE TITLE
Add flag for disabling read tx timeout on `BlockchainProvider`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#11760]
We need a flag on the legacy blockchain provider that will disable the database transaction timeout whenever a transaction is created. This should cause it to call the `disable_long_read_transaction_safety` method whenever new db providers are created, like we do for state root in the old engine:
https://github.com/paradigmxyz/reth/blob/47efb604ede2487c722b7af6ba567686b171068a/crates/blockchain-tree/src/blockchain_tree.rs#L1240

This should allow long running RPCs to be called without timing out when the legacy engine is used.

**Comment by mattsse** [comment]
I assume this should only affect the StateProviders?

**Comment by Rjected** [comment]
> I assume this should only affect the StateProviders?

If possible, yes

**Comment by mattsse** [comment]
I think we can solve this with a function on StateProvider?

**Comment by Rjected** [comment]
> I think we can solve this with a function on StateProvider?

It would be fine if we did that on the state provider structs, but all the `ProviderFactory` methods that return state providers, return `StateProviderBox`

**Comment by Rjected** [comment]
fixed by https://github.com/paradigmxyz/reth/pull/11856
