### ISSUE TITLE
replace `ChainSpec` usage with traits

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11763]
### Describe the feature

we still use the specific `ChainSpec` type as argument:

https://github.com/paradigmxyz/reth/blob/7b1b1fcb3b632d8c877a3e761a77ae4d513c0c2a/crates/payload/primitives/src/lib.rs#L301-L302

which is also used by optimism:

https://github.com/paradigmxyz/reth/blob/7b1b1fcb3b632d8c877a3e761a77ae4d513c0c2a/crates/optimism/node/src/engine.rs#L140-L142

this arg should be converted to smth that is `T: EthereumHardforks`

like it is here already:

https://github.com/paradigmxyz/reth/blob/7b1b1fcb3b632d8c877a3e761a77ae4d513c0c2a/crates/payload/primitives/src/lib.rs#L51-L52

**Comment by stevencartavia** [comment]
🙋🏽‍♂️
