### ISSUE TITLE
Integrate ChainSpec(Parser) into RethCli

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11770]
Currently we rely on:

https://github.com/paradigmxyz/reth/blob/7b1b1fcb3b632d8c877a3e761a77ae4d513c0c2a/crates/cli/commands/src/node.rs#L24-L25

if we want to integrate more things that should come with a default but we wan to override we need to expand this functionality

for this we should first integrate the chainspec parser into `RethCli` type as associated type.

 https://github.com/paradigmxyz/reth/blob/7b1b1fcb3b632d8c877a3e761a77ae4d513c0c2a/crates/cli/cli/src/lib.rs#L24-L24

**Comment by aroralanuk** [comment]
@mattsse I just made a PR for this issue!
