### ISSUE TITLE
Move optimism_deposit_signature to op-alloy

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11781]
### Describe the feature

we mostly need this for rpc responses or as a placeholder:

https://github.com/paradigmxyz/reth/blob/d4be773f5f71b49e7e40de3dd747a80af18daf74/crates/optimism/chainspec/src/lib.rs#L181-L185

this constant should be moved to op-alloy/consensus

https://github.com/alloy-rs/op-alloy

**Comment by caglaryucekaya** [comment]
Hey, I'd like to work on this

**Comment by caglaryucekaya** [comment]
I opened a [PR](https://github.com/alloy-rs/op-alloy/pull/174) on `op-allow` as part of this issue
