### ISSUE TITLE
primitives: use alloy `Withdrawals`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#11798]
### Describe the feature

At the moment, we have defined a `Withdrawals` structure inside the primitive-traits crate:

https://github.com/paradigmxyz/reth/blob/eec861fe9fc787900c18fc2d080f73c89620f5e3/crates/primitives-traits/src/withdrawal.rs#L35

After the merge of https://github.com/alloy-rs/alloy/pull/1462, this definition could be removed in reth and replaced by a simple import of the equivalent  alloy type.

**Comment by Gerson2102** [comment]
Seems not too hard, can I work on it? What do you think? @tcoratger

**Comment by tcoratger** [comment]
> Seems not too hard, can I work on it? What do you think? @tcoratger

I think it could be a good first issue wdyt @mattsse? Maybe we can provide some guidance if needed :) Happy to help. This is blocked by https://github.com/alloy-rs/alloy/pull/1462 at the moment

**Comment by tcoratger** [comment]
Should be unlocked by new alloy release https://github.com/alloy-rs/alloy/commit/3117f7625e508c50353e60b9026b26e810610371

**Comment by Gerson2102** [comment]
Ready to work on this one if it is possible @mattsse.
