### ISSUE TITLE
Make block_interval argument an Option

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11791]
## TODO

this should be an Option

https://github.com/paradigmxyz/reth/blob/248b6b5905e9c44b5e0c2af6abae450898801beb/crates/node/core/src/args/pruning.rs#L19-L21

so we can easily do 

https://github.com/paradigmxyz/reth/pull/11546

**Comment by Gerson2102** [comment]
Hey, this one seems pretty easy. Can I work on it?
