### ISSUE TITLE
Investigate how ExEx WAL should work with `reth db drop` CLI

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#11803]
### Describe the feature

Should we clear the WAL when the database is dropped?

**Comment by 0xurb** [comment]
Is WAL related to datadir, right?
So, if yes, we can add clean on `reth db drop` by  passing directory remove at WAL path on DbTool’s drop fn

Maybe also with `reth db clear` and `Wal` subcommand

**Comment by 0xurb** [comment]
This may to close the issue https://github.com/paradigmxyz/reth/pull/11855

**Comment by shekhirin** [comment]
@0xurb yep, that would work, but there's a catch that an ExEx can have its own state maintained in a separate DB, and it's unclear whether cleaning the WAL is expected on `reth db drop`. Because if an ExEx had a head block at height 10, and there's no notification in the WAL for such height, we would report an error about an inconsistent WAL.

So I think a proper solution here would be to address this https://github.com/paradigmxyz/reth/issues/11884.

**Comment by 0xurb** [comment]
Quick look to it, will be good to have smith like verbose canonical check error/result:

```rust
enum CanonicalCheckResult {
    Success,
    MissedNotification { block_hash: B256 },
    ExexIsAhead,
}
```

then add a logic for
```rust
/// If the head block is ahead of the node head,
/// we wait until the first notification with the tip greater than the ExEx head comes,
/// and do the canonical check.
if self.exex_head.block.number > self.node_head.number {
    return CanonicalCheckResult::ExexIsAhead;
}
```

and on `ExExNotificationsWithHead`'s future polling just match this error/result enum and return `Poll::Pending` in case of this.
