### ISSUE TITLE
Move  state_change code to reth-evm crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11818]
### Describe the feature

this no longer fits into the revm crate which now only contains revm specific helpers

https://github.com/paradigmxyz/reth/blob/82862fabd762f2a2b00dd77d140c2c6f5b63cadf/crates/revm/src/lib.rs#L19-L20

should be moved to

https://github.com/paradigmxyz/reth/blob/82862fabd762f2a2b00dd77d140c2c6f5b63cadf/crates/evm/Cargo.toml#L2-L2

**Comment by Gerson2102** [comment]
Hey, can I work on this one please?

**Comment by Gerson2102** [comment]
Hello @mattsse. I dont know if I'm understanding this, i was thinkin about creating another `state_change.rs` file inside of the `reth/crates/evm` with all the contents from the `state_change.rs` file from the first path, is that correct?
