### ISSUE TITLE
feat: create `reth dump-stage-db` tool for benchmarking stages easily

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#1183]
# Motivation

We want to easily be able to test each stage in certain ranges so that we can check for bugs or . Ideally, this will be done with as-real data as possible for later stages (vs our current random loads for [txlookup/senders](https://github.com/paradigmxyz/reth/blob/main/crates/stages/benches/criterion.rs)). 

This means that we need a way to dump "slices" of a node's synced database to a new database which will be distributed somehow to machines which run the benchmarks.

# Proposed Solution

Write a tool, say, `reth dump-stage-db --from M --to N --from-db /my/local/db --to-db ./new-db-path StageName` which does the following:
1. Snapshots a slice of the tables corresponding to `StageName` for the range of blocks `M` and `N`
2. Dumps these to a new database file

It should then be possible for `reth stage --from M --to N --db ./new-db-path StageName` to run successfully.

This needs to be tailored per-stage unfortunately.

In a followup, we should introduce benchmarks for these stages.

To make this performant, it is recommended to use MDBX Cursors without encoding/decoding the data.

Alternatively, write `reth dump-table <table name> --from=key --to=key` as well as any necessary CLI helpers for creating the keys correctly for dumping a range. Each table can then be loaded in a database via `mdbx_load`.

## Execution Stage

Here's a sketch for the `ExecutionStage`.

In order to run execution from block `M` to `N` we need read access to the following tables:
* The `PlainAccountState` and `PlainStorageState` at M (the pre-state)
* The following tables contents from `M` to `N` (the data necessary to run execution):
  - CanonicalHeaders
  - Headers
  - BlockBodies
  - BlockOmmers
  - TxSenders
  - BlockTransitionIndex
  - (Optional) AccountChangeSet
  - (Optional) StorageChangeset

We'd dump all the tables above in a new DB, and ideally, execution from M to N should be able to work with the pre-state and all the txs.

**Comment by onbjerg** [comment]
Seems this was closed too soon? ref #1328
