### ISSUE TITLE
Rename associated types in `EngineTypes` to reflect that they are envelopes

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#11866]
### Describe the feature

The associated types in `EngineTypes` are named e.g. `ExecutionPayloadV3`, but we don't actually specify the payload types here, we specify the envelope types. Since Pectra does not have an `ExecutionPayloadV4`, but does have a new envelope, I think this is confusing and the associated types should be renamed to e.g. `ExecutionPayloadEnvelopeV3` or similar. See e.g.

https://github.com/paradigmxyz/reth/blob/dfcaad4608797ed05a8b896fcfad83a83a6292af/crates/ethereum/engine-primitives/src/lib.rs#L39-L50

cc @mattsse wdyt?

**Comment by mattsse** [comment]
yeah, I had this issue in a draft somewhere already. we should def do that

**Comment by rkdud007** [comment]
i can take this one, just to be clear does it mean simply like this or am i missing something

```
impl<T: PayloadTypes> EngineTypes for EthEngineTypes<T>
where
    T::BuiltPayload: TryInto<ExecutionPayloadV1>
        + TryInto<ExecutionPayloadEnvelopeV2>
        + TryInto<ExecutionPayloadEnvelopeV3>
        + TryInto<ExecutionPayloadEnvelopeV4>,
{
    type ExecutionPayloadV1 = ExecutionPayloadV1;
    type ExecutionPayloadEnvelopeV2 = ExecutionPayloadEnvelopeV2;
    type ExecutionPayloadEnvelopeV3 = ExecutionPayloadEnvelopeV3;
    type ExecutionPayloadEnvelopeV4 = ExecutionPayloadEnvelopeV4;
}
```

**Comment by mattsse** [comment]
it is, but this should wait for https://github.com/paradigmxyz/reth/pull/11865 to avoid a bunch of conflicts

**Comment by Rjected** [comment]
ah i have a pr for this already https://github.com/paradigmxyz/reth/pull/11812
