### ISSUE TITLE
RETH ignores prune settings in .toml with -full flag

### ISSUE THREAD

**Issue by sahfd4eiugf** [paradigmxyz/reth#11871]
### Describe the bug

As most people will go for snap/full node instead of archive, I understand that reth applies automatic prune settings when launched with -full flag. But then history doesn't go much far away and this is a problem when running a L2. Most importantly the .toml settings should have priority.

Once the default full/snap node is synced, the main issue is that it's not possible "unprune" states and blocks. As I understand it, the database has to be erased and the whole sync restarted from scratch WITHOUT the -full flag so that prune settings in the .toml can be used.

### Steps to reproduce

- change prune settings in .toml file
- launch reth with -full flag
- .toml prune settings are ignored

### Platform(s)

Linux (x86)

### What version/commit are you on?

1.1.0

### What database version are you on?

2-2

### Which chain / network are you on?

ETH

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
which settings are ignored?
