### ISSUE TITLE
RPC API virtual hosts filtering

### ISSUE THREAD

**Issue by 0xMelkor** [paradigmxyz/reth#1187]
### Describe the feature

Extend the RPC middleware stack to support `--http.vhosts` and `--authrpc.vhosts` CLI arguments.
According to Geth specs vhosts will be a:
```
Comma separated list of virtual hostnames from which to accept requests (server enforced). 
Accepts '*' wildcard. (default: "localhost")
```
Build this on the same structure as #1127, implementing the `AuthValidator` trait (maybe renaming it) to check
the `Host` header of incoming Http requests.

We can mimic the same validation rules we find in Geth:
```golang
	if r.Host == "" {
		h.next.ServeHTTP(w, r)
		return
	}
	host, _, err := net.SplitHostPort(r.Host)
	if err != nil {
		// Either invalid (too many colons) or no port specified
		host = r.Host
	}
	if ipAddr := net.ParseIP(host); ipAddr != nil {
		// It's an IP address, we can serve that
		h.next.ServeHTTP(w, r)
		return
	}
	// Not an IP address, but a hostname. Need to validate
	if _, exist := h.vhosts["*"]; exist {
		h.next.ServeHTTP(w, r)
		return
	}
	if _, exist := h.vhosts[host]; exist {
		h.next.ServeHTTP(w, r)
		return
	}
	http.Error(w, "invalid host specified", http.StatusForbidden)
```

**Comment by mattsse** [comment]
sorry I'm unfamiliar with this setting a bit confused by this:

> Comma separated list of virtual hostnames from which to accept requests (server enforced). 
Accepts '*' wildcard. (default: "localhost")

what does this do exactly?

**Comment by 0xMelkor** [comment]
This sentence is reported in the [Geth CLI](https://geth.ethereum.org/docs/fundamentals/command-line-options) docs and briefly described [here](https://geth.ethereum.org/docs/getting-started/consensus-clients). I think the description is quite misleading and imprecise, since "virtual host" is a concept of the server and its deployment, not a client's attribute.

"Virtual host" is a web hosting concept, for which you can serve your application  on a network under different host names, all resolving to the same IP address. 

This policy is generally enforced by Web servers and reverse proxies, but  Geth and Erigon support it by their own.
I don't know if it is part of a more formal spec.

**Comment by onbjerg** [comment]
I'm not sure if there is any reason we should support this directly given you can set this up much more flexibly with a load balancer. Wdyt?

**Comment by mattsse** [comment]
I'm still not sure what should be enforced by this setting.

**Comment by onbjerg** [comment]
@mattsse Essentially you check the `Host` header against the specified values

**Comment by 0xMelkor** [comment]
With this setting you can configure a CL to reach Reth on `engine.reth.com` enforcing this at the EL layer.
This feature looks more like sugar than a real requirement, and as @onbjerg said there are systems explicitly designed to do this even better.

When talking about EL, Geth is somehow considered as a standard, so I wanted to discuss this. 
Feel free to close this issue.

**Comment by onbjerg** [comment]
Your engine API should never be exposed to the public, and routing using vhosts is not possible on the same interface without an overlay network afaik, which is something we cannot manage. The different requirements/setups make me think this is better left to external systems
