### ISSUE TITLE
Make payload_builder function accept BestTxterator directly

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11889]
### Describe the feature

Currently we create the iterator like this:

https://github.com/paradigmxyz/reth/blob/a4126b3a53f900483fe8946c8067aade68cf5cad/crates/ethereum/payload/src/lib.rs#L155-L158

in:
https://github.com/paradigmxyz/reth/blob/a4126b3a53f900483fe8946c8067aade68cf5cad/crates/ethereum/payload/src/lib.rs#L126-L136

it would be nicer if this would accept any iterator

we can make this easily work by changing the requested type of the pool

https://github.com/paradigmxyz/reth/blob/a4126b3a53f900483fe8946c8067aade68cf5cad/crates/ethereum/payload/src/lib.rs#L135-L135

which should not be `TxPool` but something that returns a new `BestTransactionsIter` given a `BestTransactionsAttributes`, so something like

```
Pool: FnOnce(BestTransactionsAttributes) -> BestTransactionsIter
```

see also:

https://github.com/paradigmxyz/reth/pull/11890

**Comment by edisontim** [comment]
Hello! Can I get assigned on this one?

**Comment by mahmudsudo** [comment]
Hello! Can I get assigned on this one?

**Comment by edisontim** [comment]
Hey @mattsse, I'm wondering if this is possible as we need the pool later on for ?https://github.com/paradigmxyz/reth/blob/a4126b3a53f900483fe8946c8067aade68cf5cad/crates/ethereum/payload/src/lib.rs#L379
Maybe I'm missing something, apologize if that's the case

**Comment by mattsse** [comment]
I see, then we need this as extra argument instead
