### ISSUE TITLE
Peers not connecting to each other

### ISSUE THREAD

**Issue by birozuru** [paradigmxyz/reth#11906]
### Describe the bug

We are experiencing an issue with our customized Reth binary where nodes fail to connect to each other as pairs in a distributed network setup. Interestingly, when the nodes are set up on a single VM, they connect successfully. 
All firewall rules and networking rules checkout. When the peers are added manually they still return an empty array of peers on query.

cc: @0xBEEFCAF3

### Steps to reproduce

- Deploy customized Reth binary on multiple machines in the network.
- Configure nodes with appropriate network settings.
- Attempt to establish connections between node pairs.

### Expected Behavior
Nodes should successfully connect to each other as pairs in the distributed network

### Actual Behavior
Nodes fail to establish connections with each other when distributed across different machines 

### Node logs

```text
2024-10-20T13:00:58.655949Z DEBUG tower::buffer::worker: service.ready=true processing request
2024-10-20T13:00:58.656229Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(65), flags: (0x4: END_HEADERS) }
2024-10-20T13:00:58.656306Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(65) }
2024-10-20T13:00:58.656337Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(65), flags: (0x1: END_STREAM) }
2024-10-20T13:00:58.656932Z DEBUG Connection{peer=Client}: h2::codec::framed_read: received frame=Headers { stream_id: StreamId(65), flags: (0x5: END_HEADERS | END_STREAM) }


The above log line shows that the federation peers are acknowledged by the node but still returns an empty peer list.
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 1.0.5-dev
Commit SHA: da1ef10e8d2754b255da2a7e2906aa1c8dded2e2

### What database version are you on?

null

### Which chain / network are you on?

botanix_testnet

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this isn't much to go on really

> When the peers are added manually they still return an empty array of peers on query.
is this done via rpc or via cli

can you check whether that ip/enode is reachable? you can use the `devp2p rlpx ping` command for example

if this is a dialing issue, could you perhaps share some logs from the `net` target?

**Comment by birozuru** [comment]
It's done over rpc
> this isn't much to go on really
> 
> > When the peers are added manually they still return an empty array of peers on query.
> > is this done via rpc or via cli


The command `devp2p rlpx ping enode_url` returns a connection timed out response
> > can you check whether that ip/enode is reachable? you can use the `devp2p rlpx ping` command for example

Would share them now
> if this is a dialing issue, could you perhaps share some logs from the `net` target?

**Comment by mattsse** [comment]
sorry but this doesn't contain any useful data and stops right after a new outbound connection is attempted

**Comment by birozuru** [comment]
This was an internal misconfiguration issue. 
Thanks @mattsse
