### ISSUE TITLE
primitives: unify `TxType`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#11914]
#### Current Situation
The `TxType` enum in reth represents various transaction types using `isize`, including Deposit transactions under the `optimism` feature flag. 

https://github.com/paradigmxyz/reth/blob/0270128d4f7a9f6fad27dff69273095abdfa7452/crates/primitives/src/transaction/tx_type.rs#L46-L61

However, this enum also exists in alloy repositories with similar characteristics, which leads to confusion:
- **alloy**: [`TxType` in alloy](https://github.com/alloy-rs/alloy/blob/ffc9921ef2adce563938b503884366ee3512c781/crates/consensus/src/transaction/envelope.rs#L24-L35) (does not include Deposit transaction type since it lacks the `optimism` feature flag).
- **op-alloy**: [`TxType` in op-alloy](https://github.com/alloy-rs/op-alloy/blob/c21a87ffcfc76aaa7e00583525ece1ea840fddfb/crates/consensus/src/transaction/envelope.rs#L26-L42) (includes all variants, including the Deposit transaction type for optimism).

#### Proposal
To reduce confusion and maintain consistency across repositories, I suggest removing the redundant `TxType` implementation from the `reth` primitives. Instead, we could import the `TxType` enum from `op-alloy`, which contains all the necessary variants.

**Comment by hoank101** [comment]
can i do it?

**Comment by tcoratger** [comment]
> I don't think we should do this - we should not be importing things from op-alloy into reth primitives, and the existing feature flag works. Long-term we will need to figure out a proper abstraction so that op-reth can use the deposit tx type, and reth can use the regular type enum, without reliance on a feature flag.

Maybe we could find something and open an issue on alloy because I've used this and sometimes like here or other examples 

https://github.com/kkrt-labs/kakarot-rpc/blob/8f028784a57dcd1abaf5fe6c3347ce5820cd7fa6/tests/tests/debug_api.rs#L257

it leads to back and forth to try to convert an alloy `TxType` back to a reth `TxType` (or the opposite direction).

**Comment by tcoratger** [comment]
@Rjected Yeah both could be good for sure we can:
1. Add some conversions for now in rpc-types-compat
2. Scope something for the long term :)
