### ISSUE TITLE
Load dynamic ExExes in the node builder

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#11919]
### Macro

[libloading](https://docs.rs/libloading/latest/libloading/) seems to be the most widely used crate for dynamically loading the libraries. It's also [possible](https://github.com/nagisa/rust_libloading/issues/114#issuecomment-1306134759) to return a `Future` from a `libloading`-powered function when using the Rust ABI, so let's stick with it.

Dynamically loaded ExEx should have the same interface as a regular ExEx: main entrypoint is an async function that accepts the `ExExContext` and returns a `Future` that will be polled by the `ExExManager`.

First, we need to define a macro that ExEx developers will use. This macro should expose an unmangled function `_launch_exex` that calls into the user function. The definition for this function should be something like
```rust
extern fn _launch_exex(ctx: ExExContext) -> impl Future<Output = eyre::Result<impl Future<impl Future<Output = eyre::Result<()>> + Send>> + Send {
   /// call user function
}
```

I propose to define this macro in the same `reth-exex` crate, because users need to import it anyway to use `ExExContext`.

### Node Builder integration

Then, on node startup, in `ExExLauncher` before initializing the `ExExManager`, we should look into the `DATADIR/exex/libs` directory and using `libloading` try to load each file as a dynamic library that exposes the aforementioned function and push it into the `extensions` vector https://github.com/paradigmxyz/reth/blob/bdad91b7002913a8bb6ec08982752685b2c5b604/crates/node/builder/src/launch/exex.rs#L43-L49

The `ExExLauncher` should only call into some function that gathers all the dynamic ExExes from the specified directory and loads them as dynamic libraries. We can put this function into the `reth-exex` crate.

When the node starts, we will walk two sets of ExExes:

1. Those that are installed via the Node Builder and `install_exex` method (as it works now)
2. Dynamically loaded

From this point, there should be no difference between an ExEx that’s installed via `install_exex` and a one that’s dynamically loaded, so we can get stuff like `ExExManager` integration and metrics for free.

### Tests

We need to write unit and integration tests for this feature:
1. Load a simple function with `libloading` that does nothing and is exposed via our macro. Await it, verify the output.
2. Dynamic ExExes loader from the `reth-exex` crate. Verify that it walks the directory and loads all the files.

**Comment by 0xurb** [comment]
ready to do

**Comment by 0xurb** [comment]
@shekhirin on user's library `_launch_exex` will be like `define_exex!(user_exex_fn)`
ExEx lib design will be

```rust
async fn exex_init<C>(
    ctx: C,
) -> eyre::Result<impl std::future::Future<Output = eyre::Result<()>>> {
    Ok(exex(ctx))
}

// Create a user function to produce ExEx logic
async fn exex<C>(ctx: C) -> eyre::Result<()> {
	Ok(())
}

// Use the macro to generate the unmangled _launch_exex function
define_exex!(exex_init);
```

So, we need to implement Node components and an ExEx context, since user's function must take it as a param. Am I missed something about 

> don't need to import the whole reth-exex dependency.

**Comment by shekhirin** [comment]
@0xurb ah, you're right, `ExExContext` is exportde from `reth-exex`, so you'd need to import it anyway. Then, I think we can put the macro right into the `reth-exex` crate 👍

Adjusted the issue, thanks.

**Comment by 0xurb** [comment]
I think better to separate PRs

- [ ]  macro

- [ ]  node builder integration

**Comment by 0xurb** [comment]
@shekhirin two things to make it work

- seems we’re not able to pass generic node on `_launch_exex`. It will compile, but without symbol(dlsym). So, we can e.g construct node adapter for eth and op.
- it will be needed to instantiate loader to boxed  launched exex to match types, I think we will need to move this type from node builder to exex crate

**Comment by shekhirin** [comment]
1. Makes sense, maybe we can avoid generics by introducing an `ExExContextDyn` type mirroring the `ExExContext` but having `Box<dyn T>` in several places?
2. Are you sure it's needed if we extends the list of `extensions` in `launch/exex.rs` file? `BoxedLaunchExEx` is implemented for `F: FnOnce(ExExContext<Node>) -> Fut + Send`, so it should work fine.

**Comment by 0xurb** [comment]
> 1. Makes sense, maybe we can avoid generics by introducing an `ExExContextDyn` type mirroring the `ExExContext` but having `Box<dyn T>` in several places?

`FullNodeComponents` isn't object-safe

**Comment by 0xurb** [comment]
> 2. Are you sure it's needed if we extends the list of `extensions` in `launch/exex.rs` file? `BoxedLaunchExEx` is implemented for `F: FnOnce(ExExContext<Node>) -> Fut + Send`, so it should work fine.

You're right it can be done, lit bit not obvious way, I was confused since Box::from_raw casting possible issues, but it's possible :)

**Comment by 0xurb** [comment]
> > 1. Makes sense, maybe we can avoid generics by introducing an `ExExContextDyn` type mirroring the `ExExContext` but having `Box<dyn T>` in several places?
> 
> `FullNodeComponents` isn't object-safe

I think about this also
```rust
pub struct ExExContextDyn {
    pub head: Head,
    pub config: ???,
    pub reth_config: reth_config::Config,
    pub events: UnboundedSender<ExExEvent>,
    pub notifications: Pin<Box<dyn Stream<Item = eyre::Result<ExExNotification>>>>,
    pub components: ???,
}
```

**Comment by 0xurb** [comment]
@shekhirin 

We can represent notifications as a pinned boxed stream. But I don’t see the graceful way to make dynamic ExExContext.
Maybe make components abstraction for eth and op? Cause it’s a lot of underlying  assoc type traits, under the `FullNodeComponents` trait. `config` field is also related to node for chain spec type (either op or eth)

**Comment by shekhirin** [comment]
> > 1. Makes sense, maybe we can avoid generics by introducing an `ExExContextDyn` type mirroring the `ExExContext` but having `Box<dyn T>` in several places?
> 
> `FullNodeComponents` isn't object-safe

I see... Let's start with just the notifications stream, and then extend the object safety to components in `FullNodeComponents`?

It can get quiet verbose because we will need to define new object-safe traits that wrap the existing ones, but it shouldn't be impossible, something like this

```rust
/// A trait for reading the current chainspec.
#[auto_impl::auto_impl(&, Arc)]
pub trait ChainSpecProvider: Send + Sync {
    /// The chain spec type.
    type ChainSpec: EthChainSpec + 'static;

    /// Get an [`Arc`] to the chainspec.
    fn chain_spec(&self) -> Arc<Self::ChainSpec>;
}

pub trait ChainSpecProviderDyn: Send + Sync {
    fn chain_spec(&self) -> Box<dyn EthChainSpec + 'static>;
}

impl<ChainSpec: EthChainSpec + 'static> ChainSpecProviderDyn
    for dyn ChainSpecProvider<ChainSpec = ChainSpec>
{
    fn chain_spec(&self) -> Box<dyn EthChainSpec + 'static> {
        Box::new(self.chain_spec())
    }
}

pub struct Test {
    chain_spec: Box<dyn ChainSpecProviderDyn>,
}
```

**Comment by shekhirin** [comment]
> We can represent notifications as a pinned boxed stream.

yep, let's start with that. And then we can also introduce a trait that has these methods to be able to convert to a stream with/without head https://github.com/paradigmxyz/reth/blob/8b1dfcca3fd1edcbf574e969ce30493f997e6d19/crates/exex/exex/src/notifications.rs#L56-L113

**Comment by 0xurb** [comment]
Alright. Let’s do atomically

**Comment by 0xurb** [comment]
@shekhirin how you are with solution like `AnyFullNodeComponents`?
Can be smth like:

```rust
struct ExExContextDyn {
    components: Box<dyn AnyFullNodeComponents>,
}

struct ExExContext<Node: FullNodeComponents> {
    components: Node,
}

trait FullNodeComponents: Clone {
    type Pool;
    type Executor;
    // etc. assoc types
    
    fn pool(&self) -> &Self::Pool;
    fn executor(&self) -> &Self::Executor;
}

trait AnyFullNodeComponents {
    fn pool_dyn(&self) -> &dyn std::any::Any;
    fn executor_dyn(&self) -> &dyn std::any::Any;
}

impl<T> AnyFullNodeComponents for T
where
    T: FullNodeComponents,
    <T as FullNodeComponents>::Pool: 'static,
    <T as FullNodeComponents>::Executor: 'static
{
    fn pool_dyn(&self) -> &dyn std::any::Any {
        self.pool() as _
    }
    
    fn executor_dyn(&self) -> &dyn std::any::Any {
        self.executor() as _
    }
}

#[derive(Clone)]
struct EthereumNode;

impl FullNodeComponents for EthereumNode {
    type Pool = ();
    type Executor = ();
    
    fn pool(&self) -> &Self::Pool { &() }
    fn executor(&self) -> &Self::Executor { &() }
}

fn main() {
    let components = EthereumNode;
    let dyn_components: Box<dyn AnyFullNodeComponents> = Box::new(components.clone());
    
    let dyn_ctx = ExExContextDyn { components: dyn_components };
    let ctx = ExExContext { components };
}
```

**Comment by 0xurb** [comment]
@shekhirin 

Made some abstractions for context - now its dyn config and only one thing need to be clarified - what to do with engine types and DB (for `FullNodeComponents` abstraction). Maybe we can setup kinda default engine and `Arc<DatabaseEnv>` for `NodeTypesWithDB` (and mock for tests)?
 https://github.com/paradigmxyz/reth/pull/11983#issue-2606372048

**Comment by 0xurb** [comment]
@shekhirin to make node abstraction we are need to do full node types & node components to be dyn compatible. 

That means for e.g let’s look full node types, we are need `NodeTypesWithDB`, `NodeTypesWithEngine` to be dyn compatible -> `EngineTypes`, `NodeTypes`. This traits hasn’t functions to obtain self assoc types. So, in general, we need to modify 

```rust
trait Foo {
    type Bar;
}
```

to be

```rust
trait Foo {
    type Bar;

    fn bar(&self) -> Self::Bar;
}
```

or either if we have adapters for all assoc type traits without functions, we can do abstraction with assistance of `NodeAdapter` and underlying generics. Then we also need abstractions for `EngineTypes` and `NodeTypes`

**Comment by shekhirin** [comment]
@0xurb let's start with only the notifications trait and the `ExExContextDyn` that has the `notifications` field, and then add components one by one

**Comment by shekhirin** [comment]
@0xurb now that https://github.com/paradigmxyz/reth/pull/11983 is getting merged, we can go back to the Node Builder integration

**Comment by 0xurb** [comment]
@shekhirin it's still doesn't contain the components on `ExExContextDyn`, but we can change the macro to take `ExExContextDyn` and do integration anyway
