### ISSUE TITLE
Support rpc request level Ratelimiter service

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11932]
### Describe the feature

Currently we rate limit memory expensive call (e.g. trace) on execution level:

https://github.com/paradigmxyz/reth/blob/7119bb1fe000dbd7cb58e0fcd5a66c549538e9a2/crates/rpc/rpc/src/debug.rs#L940-L940

but this permit goes out of scope once the trace is executed, however the trace result must still be sent to the client. Trace responses can be quite large (>100MB of json) so we might be executing faster than we send over HTTP or WS.

we should also rate limit on a per request basis.

The way jsonrpsee work is that there are two types of middleware
1. on HTTP level
2. and on json rpc request level  (e.g. https://github.com/paradigmxyz/reth/blob/7119bb1fe000dbd7cb58e0fcd5a66c549538e9a2/crates/rpc/rpc-builder/src/metrics.rs#L24-L24)

this makes it non-trivial to share state (e.g. a per-request counter) on the HTTP level because there we don't know the request type yet.

to improve concurrent trace request rate-limiting, we first need a new `RequestRateLimiting` service, similar to:

https://github.com/paradigmxyz/reth/blob/7119bb1fe000dbd7cb58e0fcd5a66c549538e9a2/crates/rpc/rpc-builder/src/metrics.rs#L103-L109 

that on `call` delays more incoming trace requests using a `tokio::Semaphore` for example.
Like `if the rpc method should be rate limiting, acquire a semaphore permit first` before invoking the call:
ref:
https://github.com/paradigmxyz/reth/blob/7119bb1fe000dbd7cb58e0fcd5a66c549538e9a2/crates/rpc/rpc-builder/src/metrics.rs#L103-L122

## TODO
* introduce `RpcServiceT` ratelimiter service and layer (the layer creates new services so it must hold the the semaphor)
* by default all heavy request types should be rate limited (debug_, trace_) this can either be done with a hashmap of all method names or like a filter trait that decides whether the rate limit should apply.
* the we can integrate this type in the rpc server setup, like we do with metrics, ref:
https://github.com/paradigmxyz/reth/blob/7119bb1fe000dbd7cb58e0fcd5a66c549538e9a2/crates/rpc/rpc-builder/src/lib.rs#L1561-L1563

there are still some limitation when it comes to enforcing this on HTTP level holistically but we likely need to solve this in jsonrpsee internally

**Comment by kamiyaa** [comment]
I can pick up this issue

**Comment by jenpaff** [comment]
> I can pick up this issue

assigned !

**Comment by kamiyaa** [comment]
> that on call delays more incoming trace requests using a tokio::Semaphore for example.
Like if the rpc method should be rate limiting, acquire a semaphore permit first before invoking the call:
ref:

Would the semaphore be hardcoded with a certain number of permits? Or will the value be derived from a config or elsewhere? And will it depend on which request types? (ie. `trace_` vs `debug_` rate limits are different)

**Comment by kamiyaa** [comment]
> that on call delays more incoming trace requests using a tokio::Semaphore for example.

I'm a little unsure how to make use of tokio's Semaphore when none of the functions are `async` :thinking: 
Did you want me to create a `tokio::runtime::Runtime`? But I feel like this will cause issues when users try to use it inside their own `async` function.

**Comment by kamiyaa** [comment]
Can this be closed now?
