### ISSUE TITLE
Mismatched types H256, expected struct `H256`, found struct `TxHash`

### ISSUE THREAD

**Issue by irisdv** [paradigmxyz/reth#1194]
### Describe the bug

There are 2 types H256 in reth_primitives and reth_primitives::rpc but they don't overlap. See example below. 
Would it be possible to fix this ? Or is there a way to avoid these kind of issues ? 

### Steps to reproduce

```
use reth_primitives::{
    rpc::H256,
    H256 as PrimitiveH256
};

async fn get_transaction_receipt(
        &self,
        hash: H256,
    ) -> Result<Option<TransactionReceipt>, LightClientError> {
         let hash_felt = hash_to_field_element(hash)?;
}
```

```
pub fn hash_to_field_element(hash: H256) -> Result<FieldElement, LightClientError> {}
```

Which results in error : `mismatched types, expected struct `H256`, found struct `TxHash``

### Platform(s)

Mac (Apple Silicon)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
`rpc::H256` is reexported from ethers-rs and should not be used.

use the main `reth_primitives::H256` type instead which is ruint::H256

why do you need both?

**Comment by irisdv** [comment]
For instance when doing: `let block_id = BlockId::Hash(_hash);`
`reth_primitives::rpc::BlockId::Hash` expects a H256 of type `rpc::H256`. That's why I was importing both, otherwise I get a mismatch error.

**Comment by mattsse** [comment]
ah yes, we need to replace this type.
for now you can use `U256::from(val.0)`

**Comment by mattsse** [comment]
closing in favor of https://github.com/paradigmxyz/reth/issues/1195
