### ISSUE TITLE
Add reth native BlockId type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1195]
### Describe the feature

ref https://github.com/paradigmxyz/reth/issues/1194#issuecomment-1419187671

the current BlockId is reexported from ethers which uses `primitives_types::U256` and not ruint::u256

## TODO

roll our own `BlockId` type.

**Comment by xqft** [comment]
I found `reth_primitives::BlockHashOrNumber` which seems to be analogous to `rpc::BlockId`, it uses the crate's `H256` type. Would this solve the issue?

**Comment by mattsse** [comment]
not quite because `BlockId` is `number|hash|tag`

**Comment by mattsse** [comment]
also relevant https://github.com/gakonst/ethers-rs/issues/2084

**Comment by xqft** [comment]
I see, would it be better to make a new `BlockId` entirely or rename the existing `BlockHashOrNumber` and work from there?

**Comment by mattsse** [comment]
`BlockHashOrNumber` is an entirely separate thing because this only supports `u64|H256`. Note that the `BlockNumber` type in `BlockId` is not u64 but an enum for the RPC type.

we need to roll our own `BlockId` enum, with reth H256 hash type, and also add support for

https://github.com/gakonst/ethers-rs/issues/2084

**Comment by xqft** [comment]
Great thank you, I'll take this issue then, sorry if I'm being a bit slow on understanding things

**Comment by mattsse** [comment]
tysm!

Please don't hesitate to ask :) 
no worries!

**Comment by xqft** [comment]
in [gakonst/ethers-rs#2084](https://github.com/gakonst/ethers-rs/issues/2084) you mentioned that a new `BlockId` variant should be made for the `requireCanonical` field, would this apply with reth too? since right now the project uses ethers' implementation, maybe the native could afford to support the field and gradually replace the other one?
