### ISSUE TITLE
ignore discovered peers with tcp port 0

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12014]
### Describe the feature

it can be the case that new discovered peers have TCP port 0 (e.g. discovery bootnodes) only.

because the p2p stack operates on `NodeRecord` we should filter those out and simply skip them

https://github.com/paradigmxyz/reth/blob/57a21fcb9efc274675ea00a644ebbfa627940c6d/crates/net/network/src/discovery.rs#L216-L216

## TODO
* ignore TCP with port 0

**Comment by stevencartavia** [comment]
🙋🏽‍♂️
