### ISSUE TITLE
rpc: rm `from_primitive_with_hash` in `rpc-types-compat`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#12011]
### Describe the feature

As long as https://github.com/alloy-rs/alloy/pull/1532 is merged, we can wait the next release of alloy and use this conversion implementation

https://github.com/alloy-rs/alloy/blob/31a5cf22a470452877221c4ef5c6940532e4ca7b/crates/rpc-types-eth/src/block.rs#L179-L233 

instead of `from_primitive_with_hash` in `rpc-types-compat`:

https://github.com/paradigmxyz/reth/blob/b73261936ee0995818030d696ad1c8778ecd449a/crates/rpc/rpc-types-compat/src/block.rs#L104-L155

**Comment by nadtech-hub** [comment]
Could you assign it to me?

**Comment by mattsse** [comment]
we have since removed this
