### ISSUE TITLE
Integrate BlockExecutor and TraceExt into one type for RPC

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12023]
### Describe the feature

tracing now is no longer just executing transactions:

https://github.com/paradigmxyz/reth/pull/11845

and also now requires system calls which we already have in the `BlockExecutor` types.

All of this should be integrated into a new rpc tracing specific type that unifies this with the trace and call trait:

https://github.com/paradigmxyz/reth/blob/7a06298cf70fec4338cb5014f12a6a561d7962f2/crates/rpc/rpc-eth-api/src/helpers/call.rs#L657-L657

https://github.com/paradigmxyz/reth/blob/7a06298cf70fec4338cb5014f12a6a561d7962f2/crates/rpc/rpc-eth-api/src/helpers/trace.rs#L24-L24

**Comment by malik672** [comment]
@mattsse can I open a draft for this
