### ISSUE TITLE
Return result from `TransactionCompat::fill`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12020]
### Describe the feature

Add AT `TransactionCompat::Error` and change signature of `TransactionCompat::fill` to return a result wrapping `TransactionCompat::Error` in error variant.

https://github.com/paradigmxyz/reth/blob/7a06298cf70fec4338cb5014f12a6a561d7962f2/crates/rpc/rpc-types-compat/src/transaction/mod.rs#L78-L80

This error should then be propagated, instead of converting to option here

https://github.com/paradigmxyz/reth/blob/d7f08cd8762dbe81c7c83655f7f94d5ce628daa3/crates/optimism/rpc/src/eth/transaction.rs#L115

**Comment by Gerson2102** [comment]
@emhane can you bring me some guidance here? I dont get where are you taking the `TransactionCompat::fill` there is nothing about that in the code. I dont get it.

**Comment by Gerson2102** [comment]
There is the signature of the function. But I dont know what do you want me to do with that, maybe change what we are returning?
