### ISSUE TITLE
Free Optimism Payload if no txpool txs requested

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12032]
### Describe the feature

if the OP payload attributes don't request txpool args:

https://github.com/paradigmxyz/reth/blob/0df3148357cbfb9b811fd04da6a69fca24e59be2/crates/optimism/payload/src/builder.rs#L327-L327

then the block is deterministic.

with https://github.com/paradigmxyz/reth/pull/11790 we now have

https://github.com/paradigmxyz/reth/blob/0df3148357cbfb9b811fd04da6a69fca24e59be2/crates/payload/basic/src/lib.rs#L762-L763

which allows the builder to stop building, which would be redundant at this point.

we can use this if no no_tx_pool is true

## TODO
* if op payloadattributes no_tx_pool is true, return `BuildOutcome::Freeze`

**Comment by edisontim** [comment]
Gm! Can I do this?
