### ISSUE TITLE
Change log target of `discv5` logs from `net::discv5` to `discv5`

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#12043]
### Describe the feature

Our current disv4 implementation just logs to `discv4`, but our discv5 implementation logs to `net::discv5`. This should be consistent, so we should replace any occurence where `net::discv5` is the log target with just simply `discv5`. This allows more granular filtering of logs.

**Comment by PanGan21** [comment]
Hi, I see that `discv4` is only being used from reth's implementation of `discv4`. Should this still be changed then to use `discv5 `?

**Comment by PanGan21** [comment]
Hi I made a quick pr for this in #12045 . Let me know if it works for this ticket 🙂
