### ISSUE TITLE
feat: introduce a method on `NodeConfig` for replacing the generic chainspec to dynamic `EthChainSpec`.

### ISSUE THREAD

**Issue by 0xurb** [paradigmxyz/reth#12040]
### Describe the feature

Since `EthChainSpec` is an object-safe trait now, implement mapping from `NodeConfig<ChainSpec>` to `NodeConfig<Box<dyn EthChainSpec>>` as a function on `NodeConfig` :

https://github.com/paradigmxyz/reth/blob/bea6e278dfdb052ce7bbcec5d42349221aa04b84/crates/node/core/src/node_config.rs#L141

**Comment by greged93** [comment]
hey @0xurb can I take this?

**Comment by 0xurb** [comment]
cc @mattsse
