### ISSUE TITLE
rpc: use alloy `uncle_from_header`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#12060]
### Describe the feature

At the moment, in reth we have `uncle_block_from_header` implemented here

https://github.com/paradigmxyz/reth/blob/ba78e439385469925c6fc9df36444f1ef5a6a1bc/crates/rpc/rpc-types-compat/src/block.rs#L184-L196

After the merge of https://github.com/alloy-rs/alloy/pull/1554 and the next alloy release, we can replace this by the alloy counterpart.

**Comment by nadtech-hub** [comment]
I can do this task

**Comment by mattsse** [comment]
we've completed this
