### ISSUE TITLE
Add requests as additional field to EthBuiltPayload

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12070]
### Describe the feature

currently we extract the requests from the optional ExecutedBlock data:

https://github.com/paradigmxyz/reth/blob/5a5ec73c37d2f84e27db7bc86d5c7893f641ca87/crates/ethereum/engine-primitives/src/payload.rs#L149-L152

this is problematic because the `ExecutedBlock` is optional and not strictly required by the builder:

https://github.com/paradigmxyz/reth/blob/5a5ec73c37d2f84e27db7bc86d5c7893f641ca87/crates/ethereum/engine-primitives/src/payload.rs#L29-L30

## TODO
* add requests as an optional field instead and set when creating `EthBuiltPayload::new`

**Comment by greged93** [comment]
Hey matt, I'm down to work on this
