### ISSUE TITLE
Make serde dependencies optional via features

### ISSUE THREAD

**Issue by MegaRedHand** [paradigmxyz/reth#1207]
### Describe the feature

We have _serde_ dependencies and dependency-features in various crates. For example:

https://github.com/paradigmxyz/reth/blob/115e623ae630b3c1841841dfe192a8cc63505786/crates/net/discv4/Cargo.toml#L42

https://github.com/paradigmxyz/reth/blob/55d1db0c1d457770cfa2a3d98c177a17026b439f/crates/net/network/Cargo.toml#L88

Ideally, this should be behind a _serde_ feature (see https://github.com/paradigmxyz/reth/pull/653) in each crate.

**Comment by mattsse** [comment]
reasonable

**Comment by MegaRedHand** [comment]
I'll be working on this
