### ISSUE TITLE
Add version to BeaconEngineMessage Forkchoice Updated

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12071]
### Describe the feature

To fix https://github.com/paradigmxyz/reth/pull/11730

we need to track the version of the endpoint that received the FCU:

https://github.com/paradigmxyz/reth/blob/5a5ec73c37d2f84e27db7bc86d5c7893f641ca87/crates/consensus/beacon/src/engine/message.rs#L153-L161

## TODO
* add an additional field `version: EngineApiMessageVersion` tot he message variant

https://github.com/paradigmxyz/reth/blob/5a5ec73c37d2f84e27db7bc86d5c7893f641ca87/crates/payload/primitives/src/lib.rs#L326-L328

**Comment by stevencartavia** [comment]
🙋🏽‍♂️
