### ISSUE TITLE
op-reth unable to finish initial sync

### ISSUE THREAD

**Issue by qedgardo** [paradigmxyz/reth#12073]
### Describe the bug

I'm running a Base mainnet node with `op-reth` as the execution client. The node specs are the same as those of an Ethereum mainnet node (running with `reth`): 8 vCPU, 64 GB RAM. I synced the node from a Base snapshot (https://docs.base.org/tutorials/run-a-base-node/#snapshots).

The node is unable to finish the initial sync
```
$: curl -X POST http://127.0.0.1:8545 -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' | jq

{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "startingBlock": "0x1468437",
    "currentBlock": "0x1468437",
    "highestBlock": "0x1468437",
    "warpChunksAmount": null,
    "warpChunksProcessed": null,
    "stages": [
      {
        "name": "AccountHashing",
        "block": "0x1480bd7"
      },
      {
        "name": "Bodies",
        "block": "0x1480bd7"
      },
      {
        "name": "Execution",
        "block": "0x1480bd7"
      },
      {
        "name": "Finish",
        "block": "0x1468437"
      },
      {
        "name": "Headers",
        "block": "0x1480bd7"
      },
      {
        "name": "IndexAccountHistory",
        "block": "0x1480bd7"
      },
      {
        "name": "IndexStorageHistory",
        "block": "0x1480bd7"
      },
      {
        "name": "MerkleExecute",
        "block": "0x1480bd7"
      },
      {
        "name": "MerkleUnwind",
        "block": "0x1480bd7"
      },
      {
        "name": "Prune",
        "block": "0x1468437"
      },
      {
        "name": "PruneSenderRecovery",
        "block": "0x1480bd7"
      },
      {
        "name": "SenderRecovery",
        "block": "0x1480bd7"
      },
      {
        "name": "StorageHashing",
        "block": "0x1480bd7"
      },
      {
        "name": "TransactionLookup",
        "block": "0x1480bd7"
      }
    ]
  }
}
```

### Steps to reproduce

Run a node with the following args in an ubuntu-noble-24.04 server:

op-reth args:

op-reth node \
    --chain base \
    --rollup.sequencer-http https://mainnet-sequencer.base.org \
    --datadir /base/data \
    --http \
    --http.addr 0.0.0.0 \
    --http.port 8545 \
    --http.api web3,debug,eth,net,reth \
    --ws \
    --ws.addr 0.0.0.0 \
    --ws.port 8546 \
    --ws.api web3,debug,eth,net,reth \
    --authrpc.addr 127.0.0.1 \
    --authrpc.port 8551 \
    --authrpc.jwtsecret=/var/lib/base/jwt.txt \
    --metrics 0.0.0.0:6060 \
    --engine.experimental \
    --log.file.max-files 0 \
    --enable-discv5-discovery \
    --rollup.disable-tx-pool-gossip 

op-node args:

op-node \
    --l2.enginekind=reth \
    --l1.trustrpc \
    --l1.rpckind=basic \
    --l1=<l1-rpc-endpoint> \
    --l1.beacon=<l1-beacon-endpoint> \
    --l2=http://127.0.0.1:8551 \
    --rpc.addr=127.0.0.1 \
    --rpc.port=9545 \
    --l2.jwt-secret=/base/jwt.txt \
    --network=base-mainnet \
    --p2p.advertise.ip=<public-ip> \
    --rollup.load-protocol-versions=true \
    --syncmode=execution-layer \
    --rollup.halt=major

### Node logs

```text
I didn't find error logs, just:

Consensus client (op-node) logs:

op-node: t=2024-10-22T15:14:15+0000 lvl=info msg="Sync progress" reason="new chain head block" l2_finalized=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_safe=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_pending_safe=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_unsafe=0x7fc2a9d25d585d3666f16ee94526ac4262f13121a12b4f403fdd213fed606a6f:21410354 l2_backup_unsafe=0x0000000000000000000000000000000000000000000000000000000000000000:0 l2_time=1729610055

Execution client logs:

Oct 25 10:18:39 m-base-02 op-reth[2727348]: 2024-10-25T10:18:39.016828Z  INFO Committed stage progress pipeline_stages=13/14 stage=Prune checkpoint=21398583 target=21498839
Oct 25 10:18:42 m-base-02 op-reth[2727348]: 2024-10-25T10:18:42.273655Z  INFO Preparing stage pipeline_stages=13/14 stage=Prune checkpoint=21398583 target=21498839
Oct 25 10:18:42 m-base-02 op-reth[2727348]: 2024-10-25T10:18:42.273695Z  INFO Executing stage pipeline_stages=13/14 stage=Prune checkpoint=21398583 target=21498839
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

op-reth --version
reth-optimism-cli Version: 1.1.0
Commit SHA: 1ba631ba9581973e7c6cadeea92cfe1802aceb4a
Build Timestamp: 2024-10-14T18:00:59.446775093Z
Build Features: asm_keccak,jemalloc,optimism
Build Profile: release

### What database version are you on?

reth db version
2024-10-25T10:16:40.868899Z  INFO Initialized tracing, debug log directory: /var/lib/base/.cache/reth/logs/dev
Current database version: 2
Local database version: 2

### Which chain / network are you on?

base (mainnet)

### What type of node are you running?

Pruned with custom reth.toml config

### What prune config do you use, if any?
```
[prune]
# Minimum pruning interval measured in blocks
# https://github.com/paradigmxyz/reth/pull/8308
block_interval = 500_000

[prune.parts]
# Sender Recovery pruning configuration
sender_recovery = { distance = 1_300_000 } # Prune all transaction senders before the block `head-100000`, i.e. keep transaction senders for the last 100001 blocks

# Transaction Lookup pruning configuration
transaction_lookup = { distance = 1_300_000 } # Prune all TxNumber => TxHash mappings

# Receipts pruning configuration. This setting overrides `receipts_log_filter`.
receipts = { distance = 1_300_000 } # Prune all receipts from transactions before the block 1920000, i.e. keep receipts from the block 1920000

# Account History pruning configuration
account_history = { distance = 1_300_000 } # Prune all historical account states before the block `head-100000`

# Storage History pruning configuration
storage_history = { distance = 1_300_000 } # Prune all historical storage states before the block `head-100000`
```

### If you've built Reth from source, provide the full command you used

make install-op maxperf-op

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> The node is unable to finish the initial sync:

could you please elaborate a bit

do you mean there's no more progress after
> Oct 25 10:18:42 m-base-02 op-reth[2727348]: 2024-10-25T10:18:42.273695Z  INFO Executing stage pipeline_stages=13/14 stage=Prune checkpoint=21398583 target=21498839

?

**Comment by qedgardo** [comment]
Thanks for your quick reply @mattsse . I'm sorry the node is not stuck, it still running the pruning stage, due to the provided configuration. Will close this issue and wait until the whole process ends.
