### ISSUE TITLE
Introduce `NetworkConnectionState::Hibernate` state while IO heavy stages are active

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1208]
### Describe the feature

during initial sync, once bodies have been downloaded we no longer require the network (peers) since all operations are IO+Disk bound.

Currently, we're still trying to fill all slots when the sender recovery stage is active, even though we don't need peers until we reenter the download stages, taking away valuable resources.

https://github.com/paradigmxyz/reth/blob/ee413da924c18ab839de7dea962e9d613d3eab97/crates/net/network/src/peers/manager.rs#L573-L578

This would mainly benefit the sender recovery stage since this can operate in parallel with max CPU.

By adding a new `NetworkConnectionState::Hibernate` we could switch of attempts for new outgoing connections since currently useless.

**Comment by gakonst** [comment]
Maybe the hashing stages as well

**Comment by 1010adigupta** [comment]
@mattsse can you describe more about this issue, if I understood it correctly, I will take up this issue

**Comment by mattsse** [comment]
this should basically work as a switch that prevents new outbound connection attempts

**Comment by 1010adigupta** [comment]
okay, I willl take up this issue

**Comment by loocapro** [comment]
Hi @1010adigupta, can I jump on this?

**Comment by mattsse** [comment]
assigned @loocapro
