### ISSUE TITLE
Simplify `optimism` feature?

### ISSUE THREAD

**Issue by hai-rise** [paradigmxyz/reth#12099]
### Describe the feature

Currently, library users must define the `optimism` feature for several `optimism`-specific packages, which is quite unintuitive. Example [from Odyssey](https://github.com/ithacaxyz/odyssey/blob/aa1bf0af3327d8405396be8929b14e48beb6aebd/Cargo.toml#L169-L177):
```
reth-optimism-node = { git = "https://github.com/paradigmxyz/reth.git", rev = "e98a050", features = [
    "optimism",
] }
reth-optimism-cli = { git = "https://github.com/paradigmxyz/reth.git", rev = "e98a050", features = [
    "optimism",
] }
reth-optimism-rpc = { git = "https://github.com/paradigmxyz/reth.git", rev = "e98a050", features = [
    "optimism",
] }
```

I may be missing something, but isn't it better to remove these:
```rust
// The `optimism` feature must be enabled to use this crate.
#![cfg(feature = "optimism")]
```

And replace this pattern:
```rust
optimism = [
	"reth-optimism-cli/optimism",
	"reth-optimism-node/optimism",
	"reth-optimism-consensus/optimism",
	"reth-optimism-evm/optimism",
	"reth-optimism-payload-builder/optimism",
	"reth-optimism-rpc/optimism",
	"reth-provider/optimism"
]
```

with `default = ["reth-provider/optimism"]` better?

### Additional context

Can work on this if approved.

**Comment by greged93** [comment]
I think this was flagged here https://github.com/paradigmxyz/reth/issues/11116

**Comment by mattsse** [comment]
we can't do this just yet, because this would break workspace level builds

closing as dup öf #11116

**Comment by hai-rise** [comment]
@greged93 @mattsse Thanks, guys! Will do some homework before opening issues next time 🙏.
