### ISSUE TITLE
`PayloadConfig`: Downsize `parent_block` to `parent_header`

### ISSUE THREAD

**Issue by hai-rise** [paradigmxyz/reth#12103]
### Describe the feature

"Standard" payload-building implementations (like `default_ethereum_payload` & `optimism_payload`) only need the parent header for `ConfigureEvmEnv::next_cfg_and_block_env` and filling the new header. Fetching the full block in `PayloadJobGenerator::new_payload_job` is an unwanted performance cost, especially for L2s with small block time but many transactions per block. 

On the other hand, sophisticated users who need the full parent block would likely provide their own `PayloadServiceBuilder`, `PayloadJobGenerator`, `PayloadJob`, and payload building implementation anyway. 

p/s: We don't even use `PayloadConfig` but inline the parent header and attributes directly into the `RisePayloadJob` 😅 .

### Additional context

Can work on this if approved.

**Comment by mattsse** [comment]
makes sense

**Comment by lean-apple** [comment]
Hello, I would like to work on this issue.

**Comment by mattsse** [comment]
assigned @lean-apple

**Comment by hai-rise** [comment]
@mattsse @lean-apple #12159 was great but it missed the key optimization, which is only fetching the header (`latest_header`/`sealed_header_by_hash`/etc) instead of the full block in `new_payload_job` 😅 .
