### ISSUE TITLE
convert EthApiError directly to RpcError

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1211]
### Describe the feature

some RPC errors require specific error codes.

instead of using

https://github.com/paradigmxyz/reth/blob/27b07f57f0d8c2e86d5507c3730e023f25441960/crates/rpc/rpc/src/eth/error.rs#L24

we need to manually convert `EthApiError` to `RpcError` via `From<EthApiError> for RpcError` which gives us moe flexibility.

**Comment by leruaa** [comment]
I would like to take this on.
