### ISSUE TITLE
Unify `BlockReceipts` structures

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#12111]
### Describe the feature

Currently, it seems that two different `BlockReceipts` structures are defined in the code

- In the rpc crate:

https://github.com/paradigmxyz/reth/blob/0c516091b8f45f07cf4d76879153d3cd90015363/crates/rpc/rpc-eth-types/src/cache/mod.rs#L544-L547

- In the evm crate:
https://github.com/paradigmxyz/reth/blob/0c516091b8f45f07cf4d76879153d3cd90015363/crates/evm/execution-types/src/chain.rs#L455-L462

But it seems that these two structures provide the same information. Maybe it would be worth unifying them under a single `BlockReceipts` structure in the evm crate.

**Comment by greged93** [comment]
Hey @tcoratger, down to work on this

**Comment by tcoratger** [comment]
@mattsse Can you confirm this is relevant (or not)?
