### ISSUE TITLE
Add version byte to PayloadBuilderAttributes::try_new

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12135]
## TODO
* add version: u8 as argument to
https://github.com/paradigmxyz/reth/blob/0d07d27f3c5eea7b3ab9dedecf786fcc78954b1f/crates/payload/primitives/src/traits.rs#L85-L88

we want byte here because then this doesn't bake in `EngineApi`

cc @0xOsiris

**Comment by edisontim** [comment]
hello! Happy to work on this!

**Comment by MohamadSafi** [comment]
I'd love to work on this!
