### ISSUE TITLE
debug_traceBlockByHash returns insufficient funds on eth mainnet

### ISSUE THREAD

**Issue by AntonieDavid** [paradigmxyz/reth#12171]
### Describe the bug

I'm trying to query this method `debug_traceBlockByHash` on eth mainnet and the reth nodes return the following:
`{"jsonrpc":"2.0","id":0,"error":{"code":-32003,"message":"insufficient funds for gas * price + value: have 1414044108792614043 want 1414044806692614043"}}`. Same query seems to work on geth nodes.

### Steps to reproduce

`curl -X POST reth-rpc-endpoint -H "Content-Type: application/json" -d '{
  "id": 0,
  "jsonrpc": "2.0",
  "method": "debug_traceBlockByHash",
  "params": [
    "0x7b8fb2bcf8922a0a5bf2081fb79bedc8a0cb689193a6d5c1bd47d3ab65cea266",
    {
      "tracer": "callTracer",
      "tracerConfig": {
        "onlyTopCall": false,
        "withLog": false
      }
    }
  ]
}'`

### Platform(s)

Linux (x86)

### What version/commit are you on?

v.1.1.0

### What database version are you on?

.

### Which chain / network are you on?

eth mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
closed by https://github.com/paradigmxyz/reth/pull/12030
