### ISSUE TITLE
OVM block file codec

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12184]
### Describe the feature

Make a block file codec specifically for OVM import. This is identical to the `reth_downloaders::BlockFileCodec`, except that it needs the op feature gated logic removed in https://github.com/paradigmxyz/reth/pull/12181. 

Since op has transitioned from OVM to EVM, and OVM is in the past, this code will never have to be maintained with new hard forks. So we don't mind that it's double up from the original block decoding logic.

**Comment by lean-apple** [comment]
Hello, I would like to work on it @emhane.

**Comment by lean-apple** [comment]
Hello, I would like to work on it @emhane.

**Comment by stevencartavia** [comment]
🙋🏽‍♂️
