### ISSUE TITLE
Copy `FillTxEnv::fill_tx_env` into `SignedTransaction` trait

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12182]
### Describe the feature

Copy`FillTxEnv::fill_tx_env` to `SignedTransaction` and its implementation to impl of `SignedTransaction` for  `TransactionSigned` and `OpTransactionSigned` respectively, the latter is blocked by https://github.com/paradigmxyz/reth/pull/11433.

https://github.com/paradigmxyz/reth/blob/734c78fdfb46cc5a97971450ed74c6cbdf62d5af/crates/primitives/src/transaction/compat.rs#L9-L10

The trait `FillTxEnv` will be removed when `SignedTransaction` trait is integrated into codebase.

**Comment by garwahl** [comment]
Hey @emhane I can take this
