### ISSUE TITLE
Add helper to filter pending transactions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12199]
### Describe the feature

similar to:

https://github.com/paradigmxyz/reth/blob/ff9a42ae8fbf441f4fb9ca8dcea84c765b284721/crates/transaction-pool/src/traits.rs#L355-L359

but should accept a predicate `FnMut(&ValidPoolTransaction<Self::Transaction>>>) -> bool`

**Comment by lakshya-sky** [comment]
can I take this?

**Comment by lakshya-sky** [comment]
@mattsse what would be the use case for this proposed function. does it make sense to add similar function to `TxPool` so that `get_pending_transactions_by_sender` can use the newly added function?

**Comment by mattsse** [comment]
not quite, lookup by sender is faster,

what this new function should do instead is essentially a `iter().filter().collect()`

**Comment by gakonst** [comment]
Is there a next step which integrates these with the PayloadBuilder trait, so that one can build customized payload builder strategies from the txpool?
