### ISSUE TITLE
Unify Optimism naming

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12192]
### Describe the feature

op-alloy settled on `Op` prefix, our crates still use `Optimism`

we should rename our types here to `Op` as well.

this should happen type by type, e.g: `OptimismPayloadBuilderAttributes` -> `OpPayloadBuilderAttributes`

**Comment by stevencartavia** [comment]
🙋🏽‍♂️

**Comment by mattsse** [comment]
cool, let's wait until this pr is merged:

https://github.com/paradigmxyz/reth/pull/11887

**Comment by mattsse** [comment]
@stevencartavia if you want, you can also look into https://github.com/alloy-rs/op-alloy/issues/204

**Comment by stevencartavia** [comment]
> @stevencartavia if you want, you can also look into https://github.com/alloy-rs/op-alloy/issues/204

sure! :)

**Comment by mattsse** [comment]
marking this as completed thansk @stevencartavia
