### ISSUE TITLE
Add rlp support for EthVersion

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12195]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/93a9b8a218309a296d96d5841df4f4b7b60701cd/crates/net/eth-wire-types/src/version.rs#L18-L18

ideally we want to replace https://github.com/paradigmxyz/reth/blob/93a9b8a218309a296d96d5841df4f4b7b60701cd/crates/net/eth-wire-types/src/status.rs#L20-L22

with `EthVersion` entirely, so that we don't have to do:

https://github.com/paradigmxyz/reth/blob/93a9b8a218309a296d96d5841df4f4b7b60701cd/crates/net/eth-wire-types/src/status.rs#L125-L125

**Comment by lean-apple** [comment]
Hello, may I like to work on it ?

**Comment by mattsse** [comment]
assigned, ty
