### ISSUE TITLE
replace DisplayHardforks with `Box< dyn Display>`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12208]
### Describe the feature

The DisplayHardforks type bakes in certain output based on the currently supported hardfork types.
we'd like to make this independent of any hardfork types.
and this is only used for output logging
https://github.com/paradigmxyz/reth/blob/755fac08ddeec0f4260fa5565bac72d6cb392348/crates/chainspec/src/api.rs#L41-L42

## TODO
* change type to `Box<dyn Display>` instead

**Comment by stevencartavia** [comment]
🙋🏽‍♂️
