### ISSUE TITLE
Integrate RPC in CLI

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1221]
### Describe the feature

Add args for transports, modules

ref https://github.com/paradigmxyz/reth/pull/1213

**Comment by literallymarvellous** [comment]
I'd like to take this.

Just read #1203. The api is really good.

**Comment by mattsse** [comment]
great, I'd suggest you focus on CLI argument bindings first, mirroring geth's CLI.

Ideally all arguments are encapsulated in a standalone parser type that is then flattened into the node `Command`, similar to 

https://github.com/paradigmxyz/reth/blob/314ea0883b1062375ad86577be1fccc39233739d/bin/reth/src/lib.rs#L26

So to summarize I first would like a PR for an `RpcServerOpts` type 

ty 🙏
