### ISSUE TITLE
Open read-only transactions metric does not work properly for read-only transactions

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#12211]
I currently see the following in the grafana dashboard:
![Screenshot 2024-10-30 at 2 45 52 PM](https://github.com/user-attachments/assets/f4c7f4e3-9afe-4399-a76c-a928b642d38f)

When there are definitely many open transactions. This could be one of two things:
1. The metric is not being updated properly
2. The metric increments / decrements too quickly, and as a result stays at zero.

If 1) is true, the metric should just be fixed.
If 2) is true rather than 1), we might benefit from instead incrementing a counter for cumulative opened transactions, and cumulative closed / aborted transactions. This would also let us track how many read-only transactions are opened in a given time period, for example.

Note: this node was using `--engine.experimental`

**Comment by hoank101** [comment]
can i do it

**Comment by Rjected** [comment]
yep! assigned
