### ISSUE TITLE
Track time diff between newPayload and FCU

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12212]
### Describe the feature

we expect that newPayload and FCU requests are performed sequentially.

we're interested in the time diff between the the previous newpayload response and the FCU arrival time.

we can do this in the engine API request handler:

https://github.com/paradigmxyz/reth/blob/755fac08ddeec0f4260fa5565bac72d6cb392348/crates/rpc/rpc-engine-api/src/engine_api.rs#L45-L47

this cloned per request, so what we need to do to track the diff is
store an `Instant` when we're returning the newPayload response, eg:

https://github.com/paradigmxyz/reth/blob/755fac08ddeec0f4260fa5565bac72d6cb392348/crates/rpc/rpc-engine-api/src/engine_api.rs#L197-L197

in an `Mutex<Option<Instant>>` for example.

then on FCU, we take that instant and store the elapsed time in a histogram 

https://github.com/paradigmxyz/reth/blob/755fac08ddeec0f4260fa5565bac72d6cb392348/crates/rpc/rpc-engine-api/src/metrics.rs#L22-L22

**Comment by stevencartavia** [comment]
🙋🏽‍♂️
