### ISSUE TITLE
Add one more digits to Database growth panel

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12226]
### Describe the feature

this only uses 2 digits which isn't very useful if the second digit is already 10GBs

<img width="649" alt="image" src="https://github.com/user-attachments/assets/10ebd3ff-741e-4111-80af-82e2bb11c8f6">

we should either track single GBs or probably even more.

for example this is 24hrs:
<img width="1240" alt="image" src="https://github.com/user-attachments/assets/5d624791-6779-4f2a-9cd7-2d6326595cac">

### Additional context

https://github.com/paradigmxyz/reth/blob/76c5aef911d909161be47113cd88b7ea36fafffd/etc/grafana/dashboards/overview.json#L2006-L2006

_No response_

**Comment by edisontim** [comment]
Hey, can I work on this? :)
