### ISSUE TITLE
Add TransportRpcModules::rename

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12230]
### Describe the feature

we now have:

https://github.com/paradigmxyz/reth/blob/1f1dcc950dc2f1b3bee5a562a1c2c7cd9db04fff/crates/rpc/rpc-builder/src/lib.rs#L1822-L1825

and 

https://github.com/paradigmxyz/reth/blob/1f1dcc950dc2f1b3bee5a562a1c2c7cd9db04fff/crates/rpc/rpc-builder/src/lib.rs#L1902-L1905

but what's missing is `rename` which is basically remove + merge

## TODO
* introduce new `rename` function variants

**Comment by h3lio5** [comment]
can I work on this please?
