### ISSUE TITLE
Add docs for etherscan cli in the book

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#12232]
In this page, we describe how to use `--debug.tip` for syncing without a consensus client available:
https://github.com/paradigmxyz/reth/blob/0c39704950e370c3c97acd4253f52eca5a57a94c/book/run/mainnet.md#L86

We should do the same thing for `--debug.etherscan`

**Comment by kien6034** [comment]
I can do this

**Comment by Rjected** [comment]
assigned!
