### ISSUE TITLE
Add Database helper type: `Either`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12233]
### Describe the feature

under some circumstances it might be useful to use two different `Database` implementations.
we currently don't have an `Either` type for this

eventually this should be upstreamed to revm directly, but we can introduce this here first

https://github.com/paradigmxyz/reth/blob/460e26cc51c1902cac88b7287c7491976478ca18/crates/revm/src/lib.rs#L15-L15

## TODO
* add new modules `mod either ` and enum `Either` that implements `Database` if both variants implement database.

```rust
pub enum Either<L, R> {
    /// A value of type `L`.
    Left(L),
    /// A value of type `R`.
    Right(R),
}
```

**Comment by Parikalp-Bhardwaj** [comment]
Hi @mattsse 🙌
