### ISSUE TITLE
Combine RPC http and ws server

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1223]
### Describe the feature

because we need to configure modules on a per transport basis, we currently use one Server for HTTP and WS, however this does not quite work since both now listen on the same address.

Instead we need to merge both of them and add a custom middleware that calls handles the request depending on the transport.

**Comment by literallymarvellous** [comment]
I can take this too since it covers rpc.

**Comment by mattsse** [comment]
this is a bit tricky and I started working on this, but #1224 would be an easy pick off instead.

**Comment by literallymarvellous** [comment]
Alright.
