### ISSUE TITLE
Add more RPC module tests

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1224]
### Describe the feature

With https://github.com/paradigmxyz/reth/pull/1222
we have helper functions for launching RPC server bindings via the Client traits

we need to cover every available module

## TODO

* replicate the `test_call_<module>_functions_<transport>` functions for other modules

some of them (like tracing/debug) are not implemented yet, responses should be checked for the corresponding rpc error instead.

**Comment by naviechan** [comment]
I can take this one on

**Comment by mattsse** [comment]
@literallymarvellous did you start working on this or is this still up for grabs?
