### ISSUE TITLE
Move cachedDb to reth-revm crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12249]
### Describe the feature

this entire file 

https://github.com/paradigmxyz/reth/blob/537bdee27f9276999141dfdf5ea3cc7540d5238e/crates/payload/builder/src/database.rs#L1-L1

can be moved and renamed to src/crates/revm/cached.rs instead

**Comment by lean-apple** [comment]
Hello, may I work on it ?
