### ISSUE TITLE
replace BuilderBlockValidationRequestV3 with alloy type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12251]
### Describe the feature

# TODO
replace
https://github.com/paradigmxyz/reth/blob/8d31b652425d0e67be1577d41be77331028b93d6/crates/rpc/rpc-api/src/validation.rs#L11-L16
after we've bumped alloy

**Comment by Paulius0112** [comment]
Hi @mattsse , can I work on this?

**Comment by mattsse** [comment]
sure, but this is blocked until #12215
