### ISSUE TITLE
Integrate new queued_outgoing_messages in dashboard

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12254]
### Describe the feature

with #12220 we have a new useful metric that tracks buffered outgoing messages.

we need this in a new panel, this can be added next to:

https://github.com/paradigmxyz/reth/blob/c6b740801fda7963baeb33ac395227032825bb7e/etc/grafana/dashboards/reth-mempool.json#L1493-L1493

**Comment by syjn99** [comment]
Hi, I'd like to take this for my first contribution!
