### ISSUE TITLE
Introduce a standalone gas estimate type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12250]
### Describe the feature

with 

https://github.com/paradigmxyz/reth/blob/bd8c4eceb20c39c6e501d06cf906469329340bb9/crates/rpc/rpc-eth-api/src/node.rs#L12-L12

we now have a way to plugin additional logic into the rpc stack:

for example: 

https://github.com/paradigmxyz/reth/blob/bd8c4eceb20c39c6e501d06cf906469329340bb9/crates/rpc/rpc-eth-api/src/helpers/spec.rs#L17-L18

we can use this as the entrypoint to abstract away more evm specific logic, for example gas estimation:

https://github.com/paradigmxyz/reth/blob/bd8c4eceb20c39c6e501d06cf906469329340bb9/crates/rpc/rpc-eth-api/src/helpers/call.rs#L51-L59

which has a very simple interface

but perhaps it would be simpler if we introduce a new trait and type like `EthApiCore {type Estimator;}` so that it can plugged into the rpc stack by implementing 

so we can do `trait Call: EthApiCore< Estimator: impl trait GasEstimator>` or similar.

this can then be plugged into the rpc type like

https://github.com/paradigmxyz/reth/blob/bd8c4eceb20c39c6e501d06cf906469329340bb9/crates/optimism/rpc/src/eth/mod.rs#L116-L116

this means we need to convert this into a standalone type first:

https://github.com/paradigmxyz/reth/blob/bd8c4eceb20c39c6e501d06cf906469329340bb9/crates/rpc/rpc-eth-api/src/helpers/call.rs#L684-L703

**Comment by stevencartavia** [comment]
🙋🏽‍♂️

**Comment by mattsse** [comment]
@stevencartavia before we make any trait changes, lets first introduce a standalone estimate type

**Comment by stevencartavia** [comment]
> @stevencartavia before we make any trait changes, lets first introduce a standalone estimate type

got it! 😁
