### ISSUE TITLE
Use CachedReads for builder validations

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12266]
### Describe the feature

We expect multiple request against the same state

https://github.com/paradigmxyz/reth/blob/a911104fe9ccb04c0946e0b11ac14337eec6b7e0/crates/rpc/rpc/src/validation.rs#L67-L67

https://github.com/paradigmxyz/reth/blob/a911104fe9ccb04c0946e0b11ac14337eec6b7e0/crates/rpc/rpc/src/validation.rs#L170-L171

the likelihood that multiple submissions access similar account/storage is likely high. We can use a pair of (Hash, CachedReads) that we clone before the request and merge after the the request, this additional overhead should be negligible compared to doing more disk io

see also:

https://github.com/paradigmxyz/reth/blob/a911104fe9ccb04c0946e0b11ac14337eec6b7e0/crates/revm/src/cached.rs#L32-L32
https://github.com/paradigmxyz/reth/blob/a911104fe9ccb04c0946e0b11ac14337eec6b7e0/crates/revm/src/cached.rs#L47-L47

**Comment by lean-apple** [comment]
Hello, can I work on this issue and the https://github.com/paradigmxyz/reth/issues/12267 ?
