### ISSUE TITLE
Use global secp256k1 context for tests

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12260]
### Describe the feature

this is predominately used by tests: 

https://github.com/search?q=repo%3Aparadigmxyz%2Freth%20%22secp256k1%3A%3Anew%22&type=code

but we can use the global context `SECP256K1` instead, this requires `global-context` feature if not enabled

**Comment by Jonatan-Chaverri** [comment]
Can I work on this one?

**Comment by mattsse** [comment]
assigned
