### ISSUE TITLE
Use Arc<ChainSpec> in SystemCaller

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12264]
### Describe the feature

This must be an `Arc<ChainSpec>` so that we enforce cheap clones 
https://github.com/paradigmxyz/reth/blob/166a2346dcd2a9c8d5fea6995a9fc5e6426c62bb/crates/evm/src/system_calls/mod.rs#L49-L49

and can prevent this issue where we clone the arced type -.-

https://github.com/paradigmxyz/reth/blob/166a2346dcd2a9c8d5fea6995a9fc5e6426c62bb/crates/ethereum/evm/src/execute.rs#L92-L101

**Comment by stevencartavia** [comment]
🙋🏽‍♂️

**Comment by mattsse** [comment]
cool, this has higher prio so prio this before others
