### ISSUE TITLE
Add `CachedReads::extend`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12267]
### Describe the feature

for #12266 it's beneficial to merge two `CachedReads` instances

https://github.com/paradigmxyz/reth/blob/a911104fe9ccb04c0946e0b11ac14337eec6b7e0/crates/revm/src/cached.rs#L32-L32

this should simply do a `a.extend(b)` on all the fields

**Comment by mattsse** [comment]
assigning @lean-apple 

(can't assign without any interaction first -.-)

**Comment by lean-apple** [comment]
> assigning @lean-apple
> 
> (can't assign without any interaction first -.-)

Thanks (Ah sorry I wasn't aware)

**Comment by lean-apple** [comment]
I will do probably push a PR for this one before the https://github.com/paradigmxyz/reth/issues/12266, if there is no issue.
