### ISSUE TITLE
Memory leak when metrics endpoint is enabled, but not scraped

### ISSUE THREAD

**Issue by mikroskeem** [paradigmxyz/reth#12283]
### Describe the bug

When metrics endpoint is enabled with e.g. `--metrics=127.0.0.1:2112` flag, memory usage keeps growing if endpoint is not being actively scraped.

### Steps to reproduce

1. Start node with `--metrics` flag, e.g. `--metrics=127.0.0.1:2112`
2. Leave it running for a few days
3. See Reth memory usage grow significantly (up to ~20GiB RSS in 3-4 days)
4. Scrape endpoint (e.g. via curl, or start Prometheus) and see endpoint taking long time to generate a response
5. See Reth memory usage drop

### Node logs

```text
N/A
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 1.1.0
Commit SHA: 1ba631ba9581973e7c6cadeea92cfe1802aceb4a
Build Timestamp: 2024-10-10T18:21:22.096485546Z
Build Features: asm_keccak,jemalloc
Build Profile: maxperf

### What database version are you on?

Current database version: 2
Local database version: 2

### Which chain / network are you on?

mainnet

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by jafar75** [comment]
@mikroskeem I have a similar problem, not sure related to metrics. did you test running the node without setting `--metrics` ? if yes, what happend?

**Comment by mattsse** [comment]
unfamiliar with the internals of metrics, is this perhaps an issue with histograms @rkrasiuk
