### ISSUE TITLE
Add CORS domain support

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1230]
### Describe the feature

Since the HTTP server is accessible from any local application, additional protection has been built into the server to prevent misuse of the API from web pages.

To enable access to the API from a web page (for example, to use the online IDE Remix), the server must be configured to accept cross-origin requests.

## TODO
* add `http.corsdomain` CLI args ref #1221 
* Integrate CORS layer in rpc-builder ref https://github.com/paritytech/jsonrpsee/blob/f6f4a0845d7c94dfb9befe625b2a779b3a40a127/examples/examples/cors_server.rs

**Comment by Tirthnp** [comment]
I would try doing this one
