### ISSUE TITLE
op-reth Optimism execution mode --bootnodes parameter with bad enodes block op-reth from finding peers

### ISSUE THREAD

**Issue by CRossel87a** [paradigmxyz/reth#12309]
### Describe the bug

When starting op-reth with the --bootnodes flag, if the provided bootnodes are outdated, invalid, or non-functional, reth fails to report the issue and stalls indefinitely without connecting to any peers at all.

### Steps to reproduce

op-node --syncmode=execution-layer --l2.enginekind=reth --l1.trustrpc

First (bugged):
op-reth node -vvvv --datadir /root/optimism --engine.experimental --log.file.filter debug --authrpc.addr 127.0.0.1 --authrpc.port 8551 --authrpc.jwtsecret /root/reth-auth-jwt --ipcpath ipc --http.addr 127.0.0.1 --http.api debug,eth,trace --ws.api debug,eth,trace --http --ws --chain optimism --rollup.sequencer-http https://mainnet-sequencer.optimism.io/ --rollup.disable-tx-pool-gossip --enable-discv5-discovery --bootnodes enode://ca2774c3c401325850b2477fd7d0f27911efbf79b1e8b335066516e2bd8c4c9e0ba9696a94b1cb030a88eac582305ff55e905e64fb77fe0edcd70a4e5296d3ec@34.65.175.185:30305,enode://dd751a9ef8912be1bfa7a5e34e2c3785cc5253110bd929f385e07ba7ac19929fb0e0c5d93f77827291f4da02b2232240fbc47ea7ce04c46e333e452f8656b667@34.65.107.0:30305,enode://c5d289b56a77b6a2342ca29956dfd07aadf45364dde8ab20d1dc4efd4d1bc6b4655d902501daea308f4d8950737a4e93a4dfedd17b49cd5760ffd127837ca965@34.65.202.239:30305 --full

then:

Second (works):
op-reth node -vvvv --datadir /root/optimism --engine.experimental --full --log.file.filter debug --authrpc.addr 127.0.0.1 --authrpc.port 8551 --authrpc.jwtsecret /root/reth-auth-jwt --ipcpath ipc --http.addr 127.0.0.1 --http.api debug,eth,trace --ws.api debug,eth,trace --http --ws --chain optimism --rollup.sequencer-http https://mainnet-sequencer.optimism.io --rollup.disable-tx-pool-gossip --enable-discv5-discovery

### Platform(s)

Linux (x86)

### What version/commit are you on?

Commit SHA: 0475af8bdb605ef8deadeb3452a59f9d71373d49
Build Timestamp: 2024-11-04T12:37:50.187593408Z
Build Features: asm_keccak,jemalloc,optimism
Build Profile: maxperf

### What database version are you on?

main

### Which chain / network are you on?

Optimism

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> if the provided bootnodes are outdated, invalid, or non-functional

can you clarify what invalid means here, invalid enodes?

**Comment by CRossel87a** [comment]
> > if the provided bootnodes are outdated, invalid, or non-functional
> 
> can you clarify what invalid means here, invalid enodes?

Yeah sorry about that. I think those bootnodes above are Discovery V5 bootnodes for Optimism, which may not work with the param. Were you able to replicate the bug?

**Comment by mattsse** [comment]
> Were you able to replicate the bug?

what's the bug?

> can you clarify what invalid means here, invalid enodes?

still unclear

**Comment by CRossel87a** [comment]
> > Were you able to replicate the bug?
> 
> what's the bug?
> 
> > can you clarify what invalid means here, invalid enodes?
> 
> still unclear

The bug is the node not finding peers on its own if bootnodes are provided. They should function as helpers
