### ISSUE TITLE
trie: replace `TrieAccount` by alloy `Account`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#12318]
### Describe the feature

At the moment, in the trie crate, we have a `TrieAccount` structure

https://github.com/paradigmxyz/reth/blob/d5f01036016263fbad6a3af9dc3707b2701adc1d/crates/trie/common/src/account.rs#L10-L21

which seems to contain the same information as its alloy counterpart:

https://github.com/alloy-rs/alloy/blob/f2f1001c9122703a35378dcdf20c5af42af2bc63/crates/consensus/src/account.rs#L5-L20

To avoid code duplication, it could be nice to remove the reth definition and directly import the alloy `Account` structure when needed around the reth codebase.

**Comment by edisontim** [comment]
Hey @tcoratger, correct me if I'm wrong but this doesn't seem too hard to do, could I work on this if so?

**Comment by tcoratger** [comment]
Should not be that difficult yep :), @mattsse can you confirm this is relevant?

**Comment by mattsse** [comment]
yeah these are indeed the same

**Comment by chungquantin** [comment]
Hi, I'm interested to work on this. Could you assign it to me? Expected time to deliver a PR will be tomorrow.

**Comment by mattsse** [comment]
dupe #13397
