### ISSUE TITLE
Support different addresses for http/ws

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1231]
### Describe the feature

geth default is 8546 for ws and 8545 for HTTP.

atm we're using a single address for both.

## TODO

Split this into two separate addresses:

https://github.com/paradigmxyz/reth/blob/f56bb5a022f182009622a33407820976dd4f185f/crates/rpc/rpc-builder/src/lib.rs#L418-L419

**Comment by tomarST** [comment]
I would like to attempt this one
