### ISSUE TITLE
`SignedTransaction` should provide a way to avoid recalculating transaction hash

### ISSUE THREAD

**Issue by joshieDo** [paradigmxyz/reth#12325]
```
should we add some version of this with hash? recalculating the hash seems wasteful. 
i took a peek at the codebase and it seems like we do this even when the type already has an hash .

.eg 
impl TryFrom<WithOtherFields<alloy_rpc_types::Transaction>> for TransactionSigned {


or adding a `maybe_tx_hash() -> Option<TxHash>` to the trait, that can be checked here
```

_Originally posted by @joshieDo in https://github.com/paradigmxyz/reth/pull/12187#discussion_r1828702979_

**Comment by PanGan21** [comment]
Hi @joshieDo , I am checking this issue. Do you know what is the best way to check if a `Transaction` has a hash?
I can currently see that provided method `signature_hash` is a heavy operation that calculates the hash so I believe this is not the way to just perform the check.

**Comment by emhane** [comment]
> Hi [@joshieDo](https://github.com/joshieDo) , I am checking this issue. Do you know what is the best way to check if a `Transaction` has a hash? I can currently see that provided method `signature_hash` is a heavy operation that calculates the hash so I believe this is not the way to just perform the check.

bring the `alloy_network_primitives::TransactionResponse` trait into scope makes method `tx_hash` accessible for the rpc transaction
