### ISSUE TITLE
Support binding ws and http rpc server to same port

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1232]
### Describe the feature

while http and ws default ports are different, we need to support binding HTTP and ws to the same port.

The tricky part with this with jsonrpsee is that this would require an additional middleware to support different modules (RpcModule) via HTTP and ws because they need to be handled by the same socket.

**Comment by literallymarvellous** [comment]
I know you wanted to work on this but I can get started & set the ball rolling here.

**Comment by mattsse** [comment]
great!
this would require some research on the http/ws `Server` internals first, because I'm currently not sure if even possible. My first thought was to try this with a custom Middleware or even write a custom server that can handle two different `Methods`.

**Comment by literallymarvellous** [comment]
The current implementation involves spinning up different servers for each transport so just a middleware might not work. 

This is a bit more complex than I thought. I'll look into http/ws ```Server``` internals & see if I can come up with a custom server that might work.

**Comment by mattsse** [comment]
perhaps this is even something we can upstream to jsonrpsee

**Comment by literallymarvellous** [comment]
I'm reading the jsonrpsee sever.rs & just realised it allows both ws/http requests on the same sever. 

A custom sever with modules for each transport registered  with a middleware layer that handles the modules selection. 
```Http/ws request```  - > ```Single server with https/ws enabled``` -> ```MiddleWare with a Hashmap<transport, rpcModuleConfig>``` checks if transport has module/method configured, returns Error if not, returns Ok otherwise.

**Comment by mattsse** [comment]
> I'm reading the jsonrpsee sever.rs & just realised it allows both ws/http requests on the same sever.

yes this is supported on the same port.

> A custom sever with modules for each transport registered with a middleware layer that handles the modules selection.
Http/ws request - > Single server with https/ws enabled -> MiddleWare with a Hashmap<transport, rpcModuleConfig> checks if transport has module/method configured, returns Error if not, returns Ok otherwise.

if this is possible then this is the ideal feature

**Comment by literallymarvellous** [comment]
I'll give it a go & see if it's feasible.
