### ISSUE TITLE
bug(BlockchainProvider): CanonStateSubscriptions

### ISSUE THREAD

**Issue by 0xDmtri** [paradigmxyz/reth#12341]
### Describe the bug

On the standalone `BlockchainProvider`, `trait CanonStateSubscriptions` does not work as expected. Both, [CanonStateNotificationStream](https://reth.rs/docs/reth/providers/struct.CanonStateNotificationStream.html) and Receiver<[CanonStateNotification](https://reth.rs/docs/reth/providers/enum.CanonStateNotification.html)> futures never return and are just stuck on `.await`. 

I narrowed down the problem to `reth::blockchain_tree::BlockchainTree` and the method `subscribe_canon_state` has the same never returning future.

P.S. I tried several versions for both, crate as a lib and the node itself: 1.1.1, 1.1.0, 1.0.8. As well as ```--engine.legacy``` for the node flag.

### Steps to reproduce

```Rust
use std::{path::Path, sync::Arc};

use eyre::Result;

use reth_beacon_consensus::EthBeaconConsensus;
use reth_blockchain_tree::{BlockchainTree, BlockchainTreeConfig, TreeExternals};
use reth_chainspec::ChainSpecBuilder;
use reth_db::{open_db_read_only, DatabaseEnv};
use reth_node_ethereum::{EthExecutorProvider, EthereumNode};
use reth_node_types::NodeTypesWithDBAdapter;
use reth_provider::{providers::StaticFileProvider, ProviderFactory};

const NODE_PATH: &str = "/storage/reth/mainnet";

#[tokio::main]
async fn main() -> Result<()> {
    let db_path = NODE_PATH.to_string();
    let db_path = Path::new(&db_path);
    let db = open_db_read_only(&db_path.join("db"), Default::default())?;
    let spec = Arc::new(ChainSpecBuilder::mainnet().build());

    let provider_factory =
        ProviderFactory::<NodeTypesWithDBAdapter<EthereumNode, Arc<DatabaseEnv>>>::new(
            db.into(),
            spec.clone(),
            StaticFileProvider::read_only(db_path.join("static_files"), true)?,
        );

    let tree_externals = TreeExternals::new(
        provider_factory.clone(),
        Arc::new(EthBeaconConsensus::new(spec.clone())),
        EthExecutorProvider::mainnet(),
    );

    let tree_config = BlockchainTreeConfig::default();

    let blockchain_tree = BlockchainTree::new(tree_externals, tree_config)?;

    let mut rx = blockchain_tree.subscribe_canon_state();

    while let Ok(notification) = rx.recv().await {
        match notification {
            reth_provider::CanonStateNotification::Reorg { old, new } => {
                dbg!(old);
                dbg!(new);
            }
            reth_provider::CanonStateNotification::Commit { new } => {
                dbg!(new);
            }
        }
    }

    Ok(())
}
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 1.1.1
Commit SHA: 15c230bac20e2b1b3532c8b0d470e815fbc0cc22
Build Timestamp: 2024-11-05T19:31:40.894690335Z
Build Features: asm_keccak,jemalloc
Build Profile: maxperf

### What database version are you on?

2

### Which chain / network are you on?

mainnet ethereum

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
so you're running this without a CL?

then there are no new block events emitted, because there's nothing that handles new FCU in your setup

**Comment by 0xDmtri** [comment]
> so you're running this without a CL?
> 
> then there are no new block events emitted, because there's nothing that handles new FCU in your setup

Totally makes sense, i thought of it, are there any straight forward ways to add it into BlockchainProvider that is ran externally?
