### ISSUE TITLE
Replace `thiserror-no-std` with `thiserror` v2

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#12349]
### Describe the feature

`thiserror` released version 2 which includes no_std support: https://github.com/dtolnay/thiserror/releases/tag/2.0.0

`thiserror` must also be added with `default-features = false`

**Comment by kien6034** [comment]
I want to take this

**Comment by ryzen-xp** [comment]
I'd like to take this issue.
Please assign me

**Comment by kien6034** [comment]
@ryzen-xp please work on this, i tried but got problem with the CI.
