### ISSUE TITLE
Add benchmarks for MerkleStage

### ISSUE THREAD

**Issue by MegaRedHand** [paradigmxyz/reth#1234]
### Describe the feature

The stage was introduced in https://github.com/paradigmxyz/reth/pull/994, and is a good target for optimization, but first we need benchmarks.

**Comment by gakonst** [comment]
See how these synthetic data benchmarks work: https://github.com/paradigmxyz/reth/blob/main/crates/stages/benches/criterion.rs

**Comment by MegaRedHand** [comment]
Continued in https://github.com/paradigmxyz/reth/pull/1497
