### ISSUE TITLE
Remove trait bound on `TxType`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12346]
### Describe the feature

Remove trait bound `From<alloy_consensus::TxType>` off of 
https://github.com/paradigmxyz/reth/blob/d8edf9c80ec2a339486c8b678642c90a59756a12/crates/primitives-traits/src/tx_type.rs#L6-L28

**Comment by ftupas** [comment]
Hi may I take this one?

**Comment by Rjected** [comment]
@ftupas assigned!
