### ISSUE TITLE
Request to add a CLI parameter to specify the broadcast channel capacity of `PendingPool`

### ISSUE THREAD

**Issue by kien-rise** [paradigmxyz/reth#12368]
### Describe the feature

By default, the capacity is 200, which is not enough for our use case.

Currently, we have to fork and manually increase it to 100000:

```diff
// crates/transaction-pool/src/pool/pending.rs
impl<T: TransactionOrdering> PendingPool<T> {
    /// Create a new pool instance.
    pub fn new(ordering: T) -> Self {
-       let (new_transaction_notifier, _) = broadcast::channel(200);
+       let (new_transaction_notifier, _) = broadcast::channel(100000);
```

It will be great if there is a CLI parameter to specify this value.

**Comment by mattsse** [comment]
this should be done by adding a new field to 

https://github.com/paradigmxyz/reth/blob/37e1f77047b6790f19de500e32e5908a1ca73ac3/crates/transaction-pool/src/config.rs#L32-L32

just like 

https://github.com/paradigmxyz/reth/blob/37e1f77047b6790f19de500e32e5908a1ca73ac3/crates/transaction-pool/src/config.rs#L54-L55

and then exposing a new cli arg:

https://github.com/paradigmxyz/reth/blob/37e1f77047b6790f19de500e32e5908a1ca73ac3/crates/node/core/src/args/txpool.rs#L85-L88

**Comment by stevencartavia** [comment]
🙋🏽‍♂️
