### ISSUE TITLE
Phase out alloy-rpc-types usage

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12390]
### Describe the feature

the alloy-rpc-types just re-exports a bunch of stuff, we can replace this with the crates that we actually want

Same as https://github.com/paradigmxyz/reth/pull/12389 but for all crates where we use `alloy-rpc-types.workspace`

**Comment by edisontim** [comment]
Hey Matt, can I get assigned on this one?

**Comment by pheobeayo** [comment]
Can I tackle this one?
