### ISSUE TITLE
Make eth p2p types generic 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12401]
### Describe the feature

currently all eth-wire-types are pinned to reth-primitives:

https://github.com/paradigmxyz/reth/blob/f373efe01d1e79751a7619d22be2221537d33f28/crates/net/eth-wire-types/src/blocks.rs#L45-L48

we want to support different types there as well, so we need to make these generic.

the easiest first step is introducing a generic with the reth-primitives type as default

```rust
struct BlockHeaders<T = Header>(...)
```

**Comment by glowly29** [comment]
can i pick this issue @mattsse? Thanks!
