### ISSUE TITLE
Support custom sets of tables

### ISSUE THREAD

**Issue by klkvr** [paradigmxyz/reth#12402]
### Describe the feature

ref https://github.com/paradigmxyz/reth/issues/12386

With https://github.com/paradigmxyz/reth/pull/12400 we now can use generics for existing tables to integrate custom primitive types. However we still rely on concrete `Tables` enum for tables creation and metrics collection. 

We need some kind of abstraction for a set of tables which is basically a more strongly-typed `Database`.

Just a high-level idea of how it could look like
```rust
/// General trait for defining the set of tables
/// Used to initialize database
trait TableSet {
    fn table_names(&self) -> Vec<&'static str>;
    fn is_dupsort(&self, idx: usize) -> bool
}

/// Type-safe tables set consumed by chain-specific provider implementations
trait EthTables<N: NodePrimitives>: TableSet {
    type Headers: Table<Key = BlockNumber, Value = H::Header>
    type Transactions: Table<Key = BlockNumber, Value = N::Transactions>
    ...
}
```

**Comment by mattsse** [comment]
first we should only introduce the TableSet trait and implement it on the current `Tables` enum

https://github.com/paradigmxyz/reth/blob/e6a6fc4c2e188c71b6dc67e67549cf38d0bb1d46/crates/storage/db/src/tables/mod.rs#L162-L162

**Comment by lakshya-sky** [comment]
I am understanding that we first need `TableSet` to be implemented for `Tables` enum, I have questions that will help me understand the problem better. what does `idx` in is_dupsort supposed to be? and How this trait will be used?

> /// General trait for defining the set of tables
> /// Used to initialize database
> trait TableSet {
>     fn table_names(&self) -> Vec<&'static str>;
>     fn is_dupsort(&self, idx: usize) -> bool
> }
