### ISSUE TITLE
Convey more information about an invalid transaction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12405]
### Describe the feature

currently we have

https://github.com/paradigmxyz/reth/blob/9f6f63d45a1a5b9edf3087a9210e6a9170e4c1ec/crates/transaction-pool/src/traits.rs#L755-L760

which is usually invoked for several reasons:

* exceeds gas
https://github.com/paradigmxyz/reth/blob/9f6f63d45a1a5b9edf3087a9210e6a9170e4c1ec/crates/ethereum/payload/src/lib.rs#L226-L229

* invalid transaction
https://github.com/paradigmxyz/reth/blob/9f6f63d45a1a5b9edf3087a9210e6a9170e4c1ec/crates/ethereum/payload/src/lib.rs#L268-L271

we can add this info as additional context via an enum to mark_invalid

## TODO
* introduce an enum like `InvalidKind { ExceedsGasLimit, InvalidTransaction(Err),... }`

**Comment by lean-apple** [comment]
Hello, is it possible to work on it ?
