### ISSUE TITLE
debug_traceBlockByNumber using flatCallTracer incorrectly returns parentHash instead of blockHash

### ISSUE THREAD

**Issue by jamesstanleystewart** [paradigmxyz/reth#12415]
### Describe the bug

When running a debug_traceBlockByNumber using flatCallTracer the returned result incorrectly includes each transaction's block's parentHash instead of hash.

I imagine this has something to do with loading the parents state to re-run/trace each transaction.

### Steps to reproduce

Eg. Ethereum Mainnet
```
curl -X POST -H "Content-Type: application/json" -d '{"id": 1, "jsonrpc": "2.0", "method": "debug_traceBlockByNumber", "params": ["0x142A98D",{"tracer": "flatCallTracer"}]}' localhost:8545
```

returns results with:

```
"blockHash":"0xf6c28939baac650b17585fd7f151ae9bfbb8987c14d42f503403c719692454b7", <- this is the blocks parentHash
"blockNumber":21145997
```

where it should return results with:

```
"blockHash":"0x096604aedd32b33ed533f0e5f4ca528e5aa990f34a96ec8d3698736cf3b9fc1a",
"blockNumber":21145997
```

Reference: https://etherscan.io/block/21145997

Similarly on Base Mainnet

```
curl -X POST -H "Content-Type: application/json" -d '{"id": 1, "jsonrpc": "2.0", "method": "debug_traceBlockByNumber", "params": ["0x151F018",{"tracer": "flatCallTracer"}]}' localhost:8545
```

Traces have
```
          "blockHash": "0xce271f018751cab1c07fa9ef88cd8e1967d8e3e1329e98a8069ae249f886abf0", <- this is the blocks parentHash
          "blockNumber": 22147096,
```

the correct trace would have 
```
          "blockHash": "0xa505ff4c3015aff3e04ee9c9fb0d9fe3090e74d67b794d91bbf002a65d3dc726",
          "blockNumber": 22147096,
```
https://basescan.org/block/22147096

### Node logs

```text

```

### Platform(s)

Linux (x86)

### What version/commit are you on?

latest docker release:

reth Version: 1.1.1
Commit SHA: 15c230bac20e2b1b3532c8b0d470e815fbc0cc22
Build Timestamp: 2024-11-05T12:39:46.613054379Z
Build Features: asm_keccak,jemalloc
Build Profile: maxperf

### What database version are you on?

Current database version: 2
Local database version: 2

### Which chain / network are you on?

Tested on Base Mainnet and Ethereum Mainnet using op-reth and reth.

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

Archive

### Code of Conduct

- [x] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks, this has been fixed by https://github.com/paradigmxyz/reth/pull/12360 as drive by

**Comment by jamesstanleystewart** [comment]
@mattsse thanks for that, good timing 😁 any idea when the next release will be?
