### ISSUE TITLE
Move NetworkOpts, RpcServerOpts to standalone `args` module

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1243]
### Describe the feature

atm some helper `Args` are in `lib.rs`

## TODO

* move https://github.com/paradigmxyz/reth/blob/9470943babf8afe98a10db729954a374470afcb7/bin/reth/src/lib.rs#L30 to `src/args/network_args.rs`
* move https://github.com/paradigmxyz/reth/blob/9470943babf8afe98a10db729954a374470afcb7/bin/reth/src/lib.rs#L64 to `src/args/rpc_server_args.rs`
* rename types `Opts -> Args` to follow clap's naming
* make all fields `pub`

**Comment by leruaa** [comment]
I would like to take this on.

**Comment by chirag-bgh** [comment]
Hey @leruaa , I started working on this and opened a PR for the same. I should have mentioned here earlier apologises for the same.
