### ISSUE TITLE
Replace BTreeMap with HashMap for block number to hash mapping

### ISSUE THREAD

**Issue by malik672** [paradigmxyz/reth#12466]
### Describe the feature

currently in InMemoryState uses a btreemap for mapping but the thing is there's no need for that because there's no need for the ordering (there's not) and even if we there's, Block Numbers are already quite sequential in nature (there might be a sparse tbh)
```
pub(crate) struct InMemoryState {
    /// All canonical blocks that are not on disk yet.
    blocks: RwLock<HashMap<B256, Arc<BlockState>>>,
    /// Mapping of block numbers to block hashes.
    numbers: RwLock<BTreeMap<u64, B256>>,  // <-- Target for optimization
    /// The pending block that has not yet been made canonical.
    pending: watch::Sender<Option<BlockState>>,
    /// Metrics for the in-memory state.
    metrics: InMemoryStateMetrics,
}
```

why hashmaps: removals(reorgs), lookups are better suited to an hashmap,

**Comment by mattsse** [comment]
there is and we want this sorted

**Comment by malik672** [comment]
> there is and we want this sorted

because of the traversal?
