### ISSUE TITLE
Define `OpTransaction`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12473]
### Describe the feature

Define type `reth_optimism_primitives::OpTransaction`, which should implement `reth_primitives_traits::Transaction` and `reth_codecs::Compact`

**Comment by edisontim** [comment]
Hey @emhane! Would love to work on this one!

**Comment by edisontim** [comment]
hey @emhane, do you want me to completely implement the `OpTransaction`? If so, is there another struct I could get some inspiration regarding the fields it should contain? 
I've got the skeleton of the implementation done right now with trait methods as todos

**Comment by emhane** [comment]
> hey [@emhane](https://github.com/emhane), do you want me to completely implement the `OpTransaction`? If so, is there another struct I could get some inspiration regarding the fields it should contain? I've got the skeleton of the implementation done right now with trait methods as todos

good question! it should just be a wrapper type
```rust
pub struct OpTransaction(op_alloy_consensus::OpTypedTransaction)
```
