### ISSUE TITLE
Remove TransactionSignedNoHash type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12471]
### Describe the feature

this type is just

https://github.com/paradigmxyz/reth/blob/c44edf5ce26cb326002169ec666f22ff4819bbeb/crates/primitives/src/transaction/mod.rs#L1050-L1050

without the hash. the reason this exists is that for some operations we don't need to fetch the hash from disk.

but we can solve this by converting the hash field into a `LazyLock<Hash>` instead, which is then initialized with the hash if missing.

This should be solved in multiple steps:
1. convert hash to LazyLock
2. convert all provider functions to TransactionSigned (from TransactionSignedNoHash)
3. remove TransactionSignedNoHash

**Comment by stevencartavia** [comment]
🙋🏽‍♂️
