### ISSUE TITLE
Add scaffold impl of EthFilter API handler

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1247]
### Describe the feature

Similar to #982 , just scaffolding, no impls yet

## TODO
Add handler structs and impl corresponding server trait for `EthFilter`
* EthFilter

similar to:

https://github.com/paradigmxyz/reth/blob/9470943babf8afe98a10db729954a374470afcb7/crates/rpc/rpc/src/eth/pubsub.rs#L10-L17

**Comment by leruaa** [comment]
I would like to take this on.
