### ISSUE TITLE
Move more provider traits into storage-api crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12478]
### Describe the feature

we still have a few traits defined in the reth-provider crate that are independent of reth-provider internals, like

https://github.com/paradigmxyz/reth/blob/e6a6fc4c2e188c71b6dc67e67549cf38d0bb1d46/crates/storage/provider/src/traits/history.rs#L10-L10

all of those should be moved to https://github.com/paradigmxyz/reth/blob/e6a6fc4c2e188c71b6dc67e67549cf38d0bb1d46/crates/storage/storage-api/Cargo.toml#L2-L2

ideally, trait by trait to make review easy.
can be re-exported from reth-provider to not break a ton of stuff

**Comment by PanGan21** [comment]
Hi @mattsse started with #12480  and I can continue on this depending on the recommended length of each pr!

**Comment by mattsse** [comment]
cool, ty!

**Comment by mattsse** [comment]
this one we can move as well

https://github.com/paradigmxyz/reth/blob/cef7ec80c13acac11ac4c2b93bf6bd19f4298d8c/crates/storage/provider/src/traits/header_sync_gap.rs#L31-L31

**Comment by PanGan21** [comment]
I had a look again on this and it seems it is used here:
https://github.com/paradigmxyz/reth/blob/cef7ec80c13acac11ac4c2b93bf6bd19f4298d8c/crates/storage/provider/src/providers/database/provider.rs#L1202

Do you still consider that it should be moved to storage-api crate?

**Comment by mattsse** [comment]
hmm, actually not sure about this one because this is kinda p2p, so we can keep this particular one for now

**Comment by PanGan21** [comment]
> hmm, actually not sure about this one because this is kinda p2p, so we can keep this particular one for now

Cool. What else do you think is necessary to close this ticket?

**Comment by mattsse** [comment]
marking this as closed
