### ISSUE TITLE
Node can no longer synchronize with latest versions of op-node and op-reth

### ISSUE THREAD

**Issue by MrFrogoz** [paradigmxyz/reth#12482]
### Describe the bug

https://github.com/ethereum-optimism/optimism/issues/12897

### Steps to reproduce

https://github.com/ethereum-optimism/optimism/issues/12897

### Node logs

```text

```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth-optimism-cli Version: 1.1.1
Commit SHA: 15c230bac20e2b1b3532c8b0d470e815fbc0cc22
Build Timestamp: 2024-11-05T12:40:14.182399522Z
Build Features: asm_keccak,jemalloc,optimism
Build Profile: maxperf

### What database version are you on?

latest

### Which chain / network are you on?

optimism and base

### What type of node are you running?

Archive (default)

### Code of Conduct

- [x] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
hmm, this seems similar to #12470

**Comment by mattsse** [comment]
thanks for flagging,
somehow we never Hit this on our infra...
sorry about this, expediting new release with fix #12520 in the meantime please use 1.1.0

**Comment by mattsse** [comment]
really, sorry about this
expect 1.1.2 monday
