### ISSUE TITLE
Spawn validation requests as blocking

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12504]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/c1c64ebe45ee3b0c4b5365a6bb93d889f080d322/crates/rpc/rpc/src/validation.rs#L371-L371

and 

https://github.com/paradigmxyz/reth/blob/c1c64ebe45ee3b0c4b5365a6bb93d889f080d322/crates/rpc/rpc/src/validation.rs#L402-L402

are blocking and should be spawned as such, for example:

https://github.com/paradigmxyz/reth/blob/c1c64ebe45ee3b0c4b5365a6bb93d889f080d322/crates/rpc/rpc-eth-api/src/helpers/call.rs#L699-L703

this means that the API type needs a spawner `Box<dyn TaskSpawner>`

https://github.com/paradigmxyz/reth/blob/c1c64ebe45ee3b0c4b5365a6bb93d889f080d322/crates/rpc/rpc/src/eth/core.rs#L240-L241

**Comment by ftupas** [comment]
Hi may I take this?
