### ISSUE TITLE
Extract Header-only methods of `Consensus` to a separate trait

### ISSUE THREAD

**Issue by klkvr** [paradigmxyz/reth#12522]
### Describe the feature

With #12451 `Consensus` is now generic over header and body
https://github.com/paradigmxyz/reth/blob/e686fccb99103ff6a0abb8ba0dcc631db687b1e3/crates/consensus/consensus/src/lib.rs#L47

However, in components which only know the header type we can't provide Consensus with Body generic, e.g https://github.com/paradigmxyz/reth/blob/e686fccb99103ff6a0abb8ba0dcc631db687b1e3/crates/net/downloaders/src/headers/reverse_headers.rs#L70

To address this, we'll need a separate trait which is alike `Consensus` but only operates on headers. 

Steps:
1. Inroduce trait `trait HeaderValidator<H = Header>` and move `Consensus` methods which only need header to it. Those include `validate_header`, `validate_header_against_parent`, `validate_header_range`, `validate_header_with_total_difficulty`
2. Inroduce bound `Consensus<H = Header, B = Body>: HeaderValidator<H>`
3. Fix trait impls and import `HeaderValidator` where needed

**Comment by 0xriazaka** [comment]
Can i work on this?

**Comment by 0xriazaka** [comment]
> hey [@0xriazaka](https://github.com/0xriazaka) do you need any pointers for this?

check #12648
