### ISSUE TITLE
Use unnamed argument for `reth import` path

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1255]
### Describe the feature

Currently `reth import` takes its primary argument, a path to a chain file, as `reth import --path <path to file>`. Instead, it should have the following UX:

`reth import <path to file>`

**Comment by PatStiles** [comment]
Interested in taking this on!

**Comment by Rjected** [comment]
awesome, I'll assign it to you! let me know if you have any questions

**Comment by Rjected** [comment]
@PatStiles how's it going? let me know if you need help!

**Comment by PatStiles** [comment]
#1553

**Comment by Rjected** [comment]
Completed in #1553 ty @PatStiles !
