### ISSUE TITLE
Ensure matching genesis hash in `init_genesis`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1256]
let's add a follow-up good-first-issue for a 3rd party contributor to refactor this into the function

_Originally posted by @gakonst in https://github.com/paradigmxyz/reth/pull/877#discussion_r1099708178_
      
This would involve creating creating either an assert or returning an error from the `init_genesis` function if the genesis hash from the chainspec, and the genesis hash from the db, do not match:

https://github.com/paradigmxyz/reth/blob/440718288dc5bdabbf475a2f5ffe3f7e60b1058b/crates/staged-sync/src/utils/init.rs#L23-L55

**Comment by PatStiles** [comment]
Interested in taking this on!
