### ISSUE TITLE
Unify builder argument order

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1257]
### Describe the feature

The `ReverseHeadersDownloadBuilder` and the `BodiesDownloaderBuilder` are the primary builder types that we use to construct downloaders in the CLI and in tests.
The header downloader builder has the following signature:
```rust
    /// Build [ReverseHeadersDownloader] with provided consensus
    /// and header client implementations
    pub fn build<H>(
        self,
        consensus: Arc<dyn Consensus>,
        client: Arc<H>,
    ) -> ReverseHeadersDownloader<H>
    where
        H: HeadersClient + 'static
```

And the bodies downloader has the following signature:
```rust
    /// Consume self and return the concurrent donwloader.
    pub fn build<B, DB>(
        self,
        client: Arc<B>,
        consensus: Arc<dyn Consensus>,
        db: Arc<DB>,
    ) -> BodiesDownloader<B, DB>
    where
        B: BodiesClient + 'static,
        DB: Database
```

The `client` and `consensus` fields should be changed to be in the same order for both downloaders

**Comment by literallymarvellous** [comment]
I'd like take this. 

Is there an added benefit to this in terms of speed or something else, just curious?

**Comment by Rjected** [comment]
Just consistency in the code, no performance motivation here!
