### ISSUE TITLE
Add utility trait methods to `Transaction`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12571]
### Describe the feature

Add methods as trait methods for `reth_primitives_traits::Transaction`
https://github.com/paradigmxyz/reth/blob/56826cbdbbf84ccbea41ff6ac049b27b024d5a48/crates/primitives/src/transaction/mod.rs#L465-L533

for the `is_` methods, add default implementations as such 
```rust
fn is legacy(&self) -> bool {
    matches!(self.ty() == LEGACY_TX_TYPE_ID)
}
```

**Comment by ftupas** [comment]
Hi may I take this one?

**Comment by emhane** [comment]
how is it going with this @ftupas ?

**Comment by ftupas** [comment]
hi there, something came up over the weekend - will finish it by today/tomorrow is that alright?
