### ISSUE TITLE
`InMemorySize` super trait

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12589]
### Describe the feature

Add `InMemorySize` as super trait for `reth-primitives-traits` traits: `Receipt`, `SignedTransaction` and `TxType`.

**Comment by Gerson2102** [comment]
Hey I would like to work on this one.

**Comment by Gerson2102** [comment]
You guys should moderate a little when someone is just opening a PR when the issue is not assigned to them. @emhane

**Comment by tuantran1702** [comment]
> You guys should moderate a little when someone is just opening a PR when the issue is not assigned to them. [@emhane](https://github.com/emhane)

It’s open source environment, anyone can open a PR and you have no right to complain unless they steal your code.
