### ISSUE TITLE
Introduce method for running pipeline only once

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1259]
We want to run the pipeline for all the imported blocks. Perhaps we need to add a new `exit_after_loop` or something that only runs each stage to completion once

_Originally posted by @onbjerg in https://github.com/paradigmxyz/reth/pull/877#discussion_r1101531246_

**Comment by literallymarvellous** [comment]
I'd like to take this.

Wouldn't this be similar to 
https://github.com/paradigmxyz/reth/blob/b731bb9bb3862559370cbd6520af82ce6cf784d7/crates/stages/src/pipeline/mod.rs#L136-L153
 but without the ```loop {}```

**Comment by Rjected** [comment]
I think this is resolved by #1540 with the `--debug.terminate` flag
