### ISSUE TITLE
primitives: use alloy `BlockWithParent`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#12606]
### Describe the feature

Now that https://github.com/alloy-rs/alloy/pull/1650 has been merged, after the next release of alloy, we will be able to use directly the `BlockWithParent` alloy type and remove the redundant definition from reth here

https://github.com/paradigmxyz/reth/blob/d9ed07a367f593605b76e9360c7e8711c6f7c041/crates/primitives-traits/src/header/sealed.rs#L14-L21

**Comment by aroralanuk** [comment]
With the v0.7 of alloy, this is not blocked anymore here (https://github.com/alloy-rs/alloy/releases/tag/v0.7.0) but alloy_eips needs a matching verison for alloy_consensus which has a new field `target_blobs_per_block` in Header which breaks here: https://github.com/paradigmxyz/reth/blob/88bde87f7045a44ec384ed65cc1d97e57ea2c87f/crates/storage/codecs/src/alloy/header.rs#L111
