### ISSUE TITLE
Emit a WARN log if the ExEx WAL grows beyond a certain number of blocks

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#12626]
### Describe the feature

If an ExEx doesn't emit `FinishedHeight` events, the WAL will never be cleared and will grow indefinitely https://github.com/paradigmxyz/reth/blob/4b4f9cf40626c8714f0a0caa152a970fa6e5dfa0/crates/exex/exex/src/manager.rs#L348-L367

To help prevent this user error, we can emit a WARN log in `ExExManager::finalize_wal` if the WAL contains more than 128 blocks after a call to `self.wal.finalize()`.

To do that, we need to add a method to `Wal` that will return the number of blocks in the WAL.

**Comment by htiennv** [comment]
could i take this @shekhirin, thank you!
