### ISSUE TITLE
replace struct inits with function

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12654]
### Describe the feature

we use this a lot https://github.com/paradigmxyz/reth/blob/496bf0bf715f0a1fafc198f8d72ccd71913d1a40/crates/chain-state/src/in_memory.rs#L622-L622

which makes it very hard to refactor

## TODO
* replace all inits with 
https://github.com/paradigmxyz/reth/blob/496bf0bf715f0a1fafc198f8d72ccd71913d1a40/crates/primitives/src/block.rs#L508-L508

**Comment by htiennv** [comment]
I would like to do this, thanks @mattsse!
