### ISSUE TITLE
Make `reth-blockchain-tree` generic over receipt

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12662]
### Describe the feature

Make `reth-blockchain-tree` generic over receipt

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/12752
```

**Comment by emhane** [comment]
blocking for anticipated changes to block chain tree, cc @Rjected

**Comment by mattsse** [comment]
this won't be necessary because we'll deprecate this instead
