### ISSUE TITLE
Use generic receipt in `InvalidBlockWitnessHook` impl

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12675]
### Describe the feature

Replace `reth_primitives::Receipt` with `reth_primitives_traits::ReceiptTy<P::Primitives>` in `InvalidBlockWitnessHook` impl by adding additional trait bound `P: NodeTypes` to impl body.
https://github.com/paradigmxyz/reth/blob/3408059393bcf03f6727f790ec52f28114e25d02/crates/engine/invalid-block-hooks/src/witness.rs#L40-L297

**Comment by emhane** [comment]
something you are keen on @tcoratger ? hang on till merged....https://github.com/paradigmxyz/reth/pull/12674

**Comment by tcoratger** [comment]
> something you are keen on [@tcoratger](https://github.com/tcoratger) ? hang on till merged....[#12674](https://github.com/paradigmxyz/reth/pull/12674)

This also requires a modification of the `InvalidBlockHook` trait then like

```rust
/// An invalid block hook.
pub trait InvalidBlockHook<P>: Send + Sync
where
    P:,
{
    /// Invoked when an invalid block is encountered.
    fn on_invalid_block(
        &self,
        parent_header: &SealedHeader,
        block: &SealedBlockWithSenders,
        output: &BlockExecutionOutput<ReceiptTy<P::Primitives>>,
        trie_updates: Option<(&TrieUpdates, B256)>,
    );
}
```

is it really what we want?

**Comment by emhane** [comment]
we are generalising traits and types separately, the reason being to keep scope of prs small and the change to the trait spreads to a lot of crates since it was decided to use an associated type on the trait for primitive types, instead of a generic, and as you know default AT is not stable, cc @klkvr

**Comment by emhane** [comment]
something you want to look at @htiennv ?

**Comment by htiennv** [comment]
yes, can you assign to me? Thanks.
