### ISSUE TITLE
Make `PostExectuionInput` generic over receipt

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12671]
### Describe the feature

Make `PostExecutionInput` (including its impl generic over receipt type). Set default of generic to `reth_primitives::Receipt`.
https://github.com/paradigmxyz/reth/blob/3408059393bcf03f6727f790ec52f28114e25d02/crates/consensus/consensus/src/lib.rs#L31-L38

**Comment by 0xriazaka** [comment]
👋
