### ISSUE TITLE
Install missing `eth_` handlers if eth module is selected

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1268]
### Describe the feature

with https://github.com/paradigmxyz/reth/pull/1267 we now have EthPubSub and EthFilter handlers for the eth namespace, which are currently not installed if the eth module is selected.

## TODO

install all eth handlers.

Currently only the `EthApi` handler is installed

https://github.com/paradigmxyz/reth/blob/a58cf8ac6090d6a280b7e330ffb5881105823df6/crates/rpc/rpc-builder/src/lib.rs#L400

if we add multiple handlers per namespace, this will break the `reth_methods` function because now we need to return multiple `Methods`.

we should refactor this:

https://github.com/paradigmxyz/reth/blob/a58cf8ac6090d6a280b7e330ffb5881105823df6/crates/rpc/rpc-builder/src/lib.rs#L379-L390

so that `reth_methods` takes `impl Iterator<RethRpcModule>` and returns a `Vec<Methods>` instead.

cc @leruaa

**Comment by leruaa** [comment]
I can work on this :)
