### ISSUE TITLE
Add trait bound `MaybeArbitrary` to `NodePrimitives` ATs

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12680]
### Describe the feature

Add trait bound `MaybeArbitrary` to all ATs on `NodePrimitives`

**Comment by emhane** [comment]
blocked until closed https://github.com/paradigmxyz/reth/issues/12582

**Comment by zitup** [comment]
Would like to work on this after https://github.com/paradigmxyz/reth/issues/12582 closes :)
