### ISSUE TITLE
Replace reth ReceiptWithBloom type with alloy's ReceiptWithBloom

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12701]
### Describe the feature

in reth we have 

https://github.com/paradigmxyz/reth/blob/3b120283192f276562de4f9019e6c3b59dc1efc4/crates/primitives/src/receipt.rs#L196-L201

in alloy we have almost the identical type:

https://github.com/alloy-rs/alloy/blob/b959ea621453d4b4a953b9d04e21faffc921b127/crates/consensus/src/receipt/receipts.rs#L125-L131

we can't easily unify those just yet because alloy's type is generic over logs, we first need to change alloy's type to be generic over receipt and change the default to `T = Receipt<Log>`

so this issue is two-fold,
1. unblock via changes on alloy
2. migrate reth to alloy's type

**Comment by royvardhan** [comment]
Would love to take this one @mattsse

**Comment by mimisavage** [comment]
I’d like to work on this.

**Comment by cicadaweb3** [comment]
> I’d like to work on this.

Hi, I am already half way through with two prs merged for this on alloy and op-alloy. Will open the final pr today.

**Comment by royvardhan** [comment]
> I’d like to work on this.

Hi, I am already half way through with two prs merged for this on alloy and op-alloy. Will open the final pr today.
