### ISSUE TITLE
Use generic header and body in `BeaconConsensusEngine`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12724]
### Describe the feature

Use the adapters introduced in https://github.com/paradigmxyz/reth/pull/12723 `HeaderTy<N>` and `BodyTy<N>`, to pass the primitives on `N: EngineNodeTypes` to `SealedBlock` and `SealedHeader` in `BeaconConsensusEngine` impl body

https://github.com/paradigmxyz/reth/blob/0c5984179e0304c11ad4c5bc0057508b65441338/crates/consensus/beacon/src/engine/mod.rs#L227-L1787

Blocked by https://github.com/paradigmxyz/reth/pull/12723

**Comment by emhane** [comment]
keen on this one too @tcoratger ?

**Comment by mgiagante** [comment]
If @tcoratger is not available, I'd like to take this one.

**Comment by mgiagante** [comment]
@emhane I've been giving this a look and I want to make sure I'm approaching it correctly.

- The scope of these changes is the `impl` block of `BeaconConsensusEngine`.
- What needs to be done is to replace all references to `SealedBlock` and `SealedHeader` by `SealedBlock<HeaderTy<N>, BodyTy<N>>` and `SealedHeader<HeaderTy<N>>`.

As I see it the concept of those types being "sealed" is that one needs to explicitly `.unseal()` them before being able to modify them, so I guess we still want to continue using the sealed types, but now built from the generic header and body types as opposed to their defaults `Header` and `BlockBody` at `crates/primitives/src/block.rs`:
```
pub struct SealedBlock<H = Header, B = BlockBody> {
    /// Locked block header.
    #[deref]
    #[deref_mut]
    pub header: SealedHeader<H>,
    /// Block body.
    pub body: B,
}
```
is this correct?
Thanks

**Comment by mimisavage** [comment]
I'd like to handle this task.

**Comment by mgiagante** [comment]
I'll be sending a PR for it soon.

**Comment by mgiagante** [comment]
@emhane Draft PR sent. Thanks
