### ISSUE TITLE
perf: use constant genesis hash if known chain

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1272]
### Describe the feature

currently, the `genesis_hash` is computed 3 times:

https://github.com/paradigmxyz/reth/blob/a58cf8ac6090d6a280b7e330ffb5881105823df6/crates/net/eth-wire/src/types/status.rs#L75-L77

https://github.com/paradigmxyz/reth/pull/1271 will bring it down to 2 times

however computing the genesis hash takes pretty long ~300ms in debug on my machine

Ideally we should use constants if possible and also bring it down to 1 call by initializing the underlying `Status` directly because the `Default` impl also computes the genesis

**Comment by mattsse** [comment]
I don't think has been fixed yet?

**Comment by literallymarvellous** [comment]
Hi, I've opened a pr for this.
