### ISSUE TITLE
Inherit header type in `BlockchainProvider2` impl

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12753]
### Describe the feature

Replace concrete type `Header`/`SealedHeader` with `reth_node_types::HeaderTy<N>` in impl of `BlockchainProvider2` where possible.
https://github.com/paradigmxyz/reth/blob/f8d683e80ee08412e19cc212a4c2bf8ebeca245b/crates/storage/provider/src/providers/blockchain_provider.rs#L47-L756

 To do this, probably the generic `N` on `BlockchainProvider2`'s type definition, will have to be passed to `CanonicalInMemoryState` first.
https://github.com/paradigmxyz/reth/blob/f8d683e80ee08412e19cc212a4c2bf8ebeca245b/crates/storage/provider/src/providers/blockchain_provider.rs#L58

**Comment by emhane** [comment]
blocked by https://github.com/paradigmxyz/reth/pull/12723

**Comment by lakshya-sky** [comment]
can I take this?

**Comment by mattsse** [comment]
I think we can hold off on this for bit longer until we have an abstraction for block bodies

**Comment by mimisavage** [comment]
Is it okay if I take this?

**Comment by klkvr** [comment]
Resolved by https://github.com/paradigmxyz/reth/pull/13030
