### ISSUE TITLE
Replace TransactionSigned struct inits with new functions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12769]
### Describe the feature

with https://github.com/paradigmxyz/reth/pull/12768 we have additional `new` fns to create a TransactionSigned

we need to replace all of these inits 

https://github.com/paradigmxyz/reth/blob/7d24aa40e82dab393cff77dffaf976f059153f83/crates/net/network/tests/it/big_pooled_txs_req.rs#L29-L33

with calls to the corresponding new fn

**Comment by syjn99** [comment]
I'd like to take this one
