### ISSUE TITLE
`Pool::pooled_transactions_max` is as slow as `Pool::pooled_transactions`

### ISSUE THREAD

**Issue by kien-rise** [paradigmxyz/reth#12767]
### Describe the bug

Currently, `pooled_transactions_max` calls `self.pooled_transactions()`. As a result, the running time is the same, regardless how big the argument `max` is.

https://github.com/paradigmxyz/reth/blob/f211aacf551afbf707b7fb6a40d17c8d2264110e/crates/transaction-pool/src/lib.rs#L408-L413

The same issue happens for `pooled_transaction_hashes_max`.

-------

**Suggestion**

Define a fn to `PoolInner`:

```
pub(crate) fn pooled_transactions_max(&self, max: usize) -> Vec<Arc<ValidPoolTransaction<T::Transaction>>> {
    self.get_pool_data().all().transactions_iter().filter(|tx| tx.propagate).take(max).collect()
}
```

### Steps to reproduce

N/A

### Node logs

```text

```

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

v1.1.0

### What database version are you on?

N/A

### Which chain / network are you on?

N/A

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

N/A

### Code of Conduct

- [x] I agree to follow the Code of Conduct

**Comment by kien-rise** [comment]
1. Shall I create a PR?
2. In our use case, we want to add `pending_transactions_max` also. May I add this fn in the same PR?

**Comment by hai-rise** [comment]
This is critical for performance chains as `best_transactions` is basically unusable for small block time: https://github.com/paradigmxyz/reth/issues/12412#issuecomment-2492909196.

**Comment by mattsse** [comment]
I see, yeah please open a pr that impl this natively on poolinner

**Comment by kien-rise** [comment]
> I see, yeah please open a pr that impl this natively on poolinner

I just opened a PR: https://github.com/paradigmxyz/reth/pull/12856
