### ISSUE TITLE
Add developer chain

### ISSUE THREAD

**Issue by grantkee** [paradigmxyz/reth#1280]
### Describe the feature

The cli's node module uses `chain_spec_value_parser` for parsing values. I would like to add the `Dev` chain from `ethers_core::types::Chain`. 

```sh
$ reth node --chain dev
```

### Additional context
I want to use reth as a foundation for creating another blockchain. I've been working with parity's frontier, but find it too heavy for what I'm trying to accomplish

**Comment by gakonst** [comment]
closing this for now, same reason as i mentioned in #1281
