### ISSUE TITLE
Generic header in `ForkChoiceNotifications`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12819]
### Describe the feature

Make `ForkChoiceNotifications` generic over header type, adding `alloy_consensus::Header` as default generic
```rust
pub struct ForkChoiceNotifications<T = alloy_consensus::Header>(pub watch::Receiver<Option<SealedHeader<T>>>);
```

**Comment by PelleKrab** [comment]
Should `SealedHeader` be made generic to support `ForkChoiceNotifications` being generic over the header type, as rn `SealedHeader` doesnt support generics?

**Comment by emhane** [comment]
yes @PelleKrab

**Comment by PelleKrab** [comment]
> yes [@PelleKrab](https://github.com/PelleKrab)

Ive almost got `SealedHeader` to be generic but I am running into an issue with deriving `Compact`, since it too doesnt support generics. I believe this can be fixed through manual implementation of `Compact` in `SealedHeader` or adding native support to `Compact` for generics.  Both seem kinda messy though, so is there a better way to do this?

**Comment by emhane** [comment]
> > yes [@PelleKrab](https://github.com/PelleKrab)
> 
> Ive almost got `SealedHeader` to be generic but I am running into an issue with deriving `Compact`, since it too doesnt support generics. I believe this can be fixed through manual implementation of `Compact` in `SealedHeader` or adding native support to `Compact` for generics. Both seem kinda messy though, so is there a better way to do this?

`SealedHeader` is already generic over header on main

**Comment by PelleKrab** [comment]
> > > yes [@PelleKrab](https://github.com/PelleKrab)
> > 
> > 
> > Ive almost got `SealedHeader` to be generic but I am running into an issue with deriving `Compact`, since it too doesnt support generics. I believe this can be fixed through manual implementation of `Compact` in `SealedHeader` or adding native support to `Compact` for generics. Both seem kinda messy though, so is there a better way to do this?
> 
> `SealedHeader` is already generic over header on main

Sorry that took so long, my fork was very messed up.
