### ISSUE TITLE
Replace header and body in impl of `CanonicalInMemoryState`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12816]
### Describe the feature

Replace use of `SealedHeader` with `SealedHeader<N::BlockHeader>`, and `SealedBlock` with `SealedBlock<N::BlockHeader, N::BlockBody>` in
https://github.com/paradigmxyz/reth/blob/9b289351b6835774b7398afcbcb66e7c2ef6e7f7/crates/chain-state/src/in_memory.rs#L169-L575

**Comment by syjn99** [comment]
Can i take this one?

**Comment by syjn99** [comment]
@emhane Hey I pushed a commit for this work, but I wonder I'm doing well. First, I made `ChainInfoTracker` generic for compatibility with `CanonicalInMemoryState`, and second I added constraints like following.

```rust
impl<N> CanonicalInMemoryState<N>
where
    N: NodePrimitives<
        BlockHeader = alloy_consensus::Header,
        BlockBody = reth_primitives::BlockBody,
    >,
```

I'm afraid that these constraints are too tight for generic. Is it okay to open this PR?
