### ISSUE TITLE
Inherit block type in `CanonStateNotification`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12818]
### Describe the feature

Replace use of `SealedBlock` with `SealedBlock<N::BlockHeader, N::BlockBody>` in
https://github.com/paradigmxyz/reth/blob/9b289351b6835774b7398afcbcb66e7c2ef6e7f7/crates/chain-state/src/notifications.rs#L96-L141

**Comment by htiennv** [comment]
Hi @emhane, I would like take this issue. Thanks!

**Comment by htiennv** [comment]
hi @emhane, i don't see use of `SealedBlock` in the code you mentioned. Did you mean to make `SealedBlockWithSenders` generic right?

**Comment by emhane** [comment]
yes @htiennv , thanks

**Comment by htiennv** [comment]
Hi @emhane , seems this issue was done by [12857](https://github.com/paradigmxyz/reth/pull/12857/files). Please check again!
