### ISSUE TITLE
`BeaconConsensusEngineEvent` generic data prims

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12822]
### Describe the feature

Make `BeaconConsensusEngineEvent` generic over primitive types as `BeaconConsensusEngineEvent<N: NodePrimitives = reth_primitives::EthPrimitives>`. Pass generics `N::BlockHeader` and `N::BlockBody`, to the contained `SealedHeader` and `SealedBlock`. Update the impl body accordingly.
https://github.com/paradigmxyz/reth/blob/6695d07c656e7461efeb8cd5e76d54628b1cce20/crates/consensus/beacon/src/engine/event.rs#L11-L57

**Comment by programskillforverification** [comment]
Can I take this one?
