### ISSUE TITLE
Generic data prims `EngineSyncController`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12825]
### Describe the feature

In `EngineSyncController` type definition, replace `BeaconConsensusEngineEvent` with `BeaconConsensusEngineEvent<N::Primitives>`, and `OrderedSealedBlock` with `OrderedSealedBlock<reth_node_types::HeaderTy<N>, reth_node_types::BodyTy<N>>`. Update the impl body accordingly.
https://github.com/paradigmxyz/reth/blob/6695d07c656e7461efeb8cd5e76d54628b1cce20/crates/consensus/beacon/src/engine/sync.rs#L27-L344

blocked by https://github.com/paradigmxyz/reth/issues/12824, https://github.com/paradigmxyz/reth/issues/12823 and https://github.com/paradigmxyz/reth/issues/12822

**Comment by loocapro** [comment]
Can I get this?

**Comment by 0xriazaka** [comment]
🙋‍♂️

**Comment by 0xshikhar** [comment]
Hey @emhane  , would like to work on this task - can you assign me that. Could you clarify the remaining tasks for this issue? Any additional context would be appreciated. Thanks!

**Comment by emhane** [comment]
FCFS

**Comment by mimisavage** [comment]
Can I try solving this issue?
