### ISSUE TITLE
Generic data prims `EngineSyncEvent`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12824]
### Describe the feature

Make `EngineSyncEvent` generic over data primitives, with `reth_primitives::EthPrimitives` as default generic, as `EngineSyncEvent<N: NodePrimitives = reth_primitives::EthPrimitives>`. Update the use of `SealedBlock` with `SealedBlock<N::BlockHeader, N::BlockBody>`.
https://github.com/paradigmxyz/reth/blob/6695d07c656e7461efeb8cd5e76d54628b1cce20/crates/consensus/beacon/src/engine/sync.rs#L362-L385

**Comment by htiennv** [comment]
Hi, i would like to take this issue. Thanks @emhane
