### ISSUE TITLE
Replace `Consensus` generics with generic aggregate

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12821]
### Describe the feature

1) Replace generics for header and body on `Consensus` trait with generic aggregate `N: NodePrimitives`.
2) Pass `N::Receipt` as generic to `PostExecutionInput`

https://github.com/paradigmxyz/reth/blob/9b289351b6835774b7398afcbcb66e7c2ef6e7f7/crates/consensus/consensus/src/lib.rs#L47-L82

**Comment by lakshya-sky** [comment]
@emhane can I take this?

**Comment by mattsse** [comment]
@lakshya-sky I'd like to hold off on this for bit longer

**Comment by JoshdfG** [comment]
can i work on this?

**Comment by klkvr** [comment]
Resolved by https://github.com/paradigmxyz/reth/pull/13026
