### ISSUE TITLE
Profile tx hash fetching

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12842]
### Describe the feature

this section appears to eat up the entire poll duration of the service

https://github.com/paradigmxyz/reth/blob/02824da4fcd0794d45442adbdbf6b953be04d4f3/crates/net/network/src/transactions/mod.rs#L1403-L1414

I assume this is the bottleneck

https://github.com/paradigmxyz/reth/blob/02824da4fcd0794d45442adbdbf6b953be04d4f3/crates/net/network/src/transactions/fetcher.rs#L426-L430

To narrow down improvements, we want to profile this, for this we'd need some test setup, similar to this setup

https://github.com/paradigmxyz/reth/blob/02824da4fcd0794d45442adbdbf6b953be04d4f3/crates/net/network/benches/bench.rs#L20-L20

with a `Testnet` and transactions and profile (via [samply](https://github.com/mstange/samply)) where we spent the most time, and ideally derive improvement suggestions from that.

## TODO
* mock txpool and gossip
* profile `TransactionsManager::poll` hash fetching

see metrics
https://reth.paradigm.xyz/d/d47d679c-c3b8-40b6-852d-cbfaa2dcdb37/reth-transaction-pool?orgId=1&refresh=30s&viewPanel=200

### Additional context

#12838

_No response_

**Comment by hai-rise** [comment]
We found this bad boy in DHAT last week too:
![Image](https://github.com/user-attachments/assets/84a9dafd-eebc-4e98-b620-d649405bf202)

`on_fetch_pending_hashes` allocates 17GB in a few minutes for a chain under load. Not familiar with the code base so still in our backlog at the moment 😅.

**Comment by mattsse** [comment]
yeah, this doesn't look right:

https://github.com/paradigmxyz/reth/blob/02824da4fcd0794d45442adbdbf6b953be04d4f3/crates/net/network/src/transactions/fetcher.rs#L435-L436

**Comment by Elvis339** [comment]
Hello! Can I take this issue?

**Comment by Elvis339** [comment]
Hello, can I take this issue?

**Comment by Elvis339** [comment]
Hello! 

Yesterday while I was working on this I was running into chicken and egg problem because I didn't understand the scope;
- Should the benchmark focus mostly on the `on_fetch_pending_hashes` phase, or should it include the entire lifecycle? I guess it should because it will help us test @mattsse assumption.

After reading this: https://github.com/ethereum/devp2p/blob/master/caps/eth.md#transaction-exchange
I figured this might be one of the many approaches for benchmarking scenario:
- Use the `Testnet` struct to spin up multiple peers, each with a transaction pool.
- Fill `Peer A’s` pool with `TxSet1` and `Peer B’s` pool with `TxSet2` (no overlap initially).
- Simulate transaction gossip:
    - `Peer A` announces `TxSet1` to `Peer B` via `NewPooledTransactionHashes`.
    - `Peer B` buffers these hashes and fetches the transactions (`GetPooledTransactions`).  

Let me know what you think, I would appreciate nudge in the right direction regarding the scenario.

**Comment by mattsse** [comment]
> I guess it should

yeah, testing the entire TestNet <-> TestNet would be nice to have

this scenario sgtm.

because we want to check requesting hashes, you likely need to tune a few settings, for example I believe setting the 

https://github.com/paradigmxyz/reth/blob/9d2e04c77efbf92292fde1652e2564153bfc7708/crates/net/network/src/transactions/config.rs#L35-L46

to `Max(0)` would be beneficial here because this will ensure that we only broadcast hashes and then enter the request hashes logic.

to actually broadcast txs, you can take a look at this setup:

https://github.com/paradigmxyz/reth/blob/9d2e04c77efbf92292fde1652e2564153bfc7708/crates/net/network/tests/it/txgossip.rs#L38-L40

**Comment by mattsse** [comment]
this scenario is very similar to

https://github.com/paradigmxyz/reth/blob/9d2e04c77efbf92292fde1652e2564153bfc7708/crates/net/network/tests/it/txgossip.rs#L16-L16

but more advanced with an emphasis on entering the tx fetch path, likely that we need a `TestNet` with a few more peers

**Comment by mattsse** [comment]
this looks great!

could you please open this as a PR?

interesting, so this never triggers fetching?

perhaps installing tracing helps with debugging, and converting this into a test so it's easier to run

**Comment by Elvis339** [comment]
Thank you @mattsse, so, I was able to trigger fetching from the test case: https://github.com/paradigmxyz/reth/blob/c10c3f4ccbb6f9804c437451ecbf8f023c35076e/crates/net/network/src/test_only.rs

Which I added to PR as a showcase only I will delete it later.

I see logs like: 
```
2024-11-28T16:17:27.905303Z DEBUG net::tx: requesting hashes that were stored pending fetch from peer peer_id="0x47c9…bf8d" hashes={0x8147aeca38c016228f04c28d53d9150961c19778dc515d112c72b7878adcbf11, 0xdde1f4db8205cb6be399da2daecc308c957c77a94b5c58b402eb18cd0e8004a2, 0x61fa8891c228623507a60cb888ea4e68ff53ced63799036ccaafff16b94c19c0, 0xbc8e793ded5d2cf370c502b99391ec7ab16868413680102fd4a5c7ef0aab24b9} conn_eth_version=Eth68
```

But I'm having massive issues with samply on my machine, I will boot up my old Linux machine and try CPU profiling there.
