### ISSUE TITLE
Split NetworkEventListenerProvider into two

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12861]
### Describe the feature

currently https://github.com/paradigmxyz/reth/blob/82eb38312c04bbc08332500fe0b8e0477140f648/crates/net/network-api/src/events.rs#L21-L21

returns a non generic:

https://github.com/paradigmxyz/reth/blob/82eb38312c04bbc08332500fe0b8e0477140f648/crates/net/network-api/src/events.rs#L35-L64

but we need this to be generic, but only in a few places.
we can make this more convenient if we convert these fields (minus `messages`) into a standalone type `SessionInfo`:

https://github.com/paradigmxyz/reth/blob/82eb38312c04bbc08332500fe0b8e0477140f648/crates/net/network-api/src/events.rs#L44-L59

and then introduce a new trait `NetworkPeersEvents` that only returns the non generic events while `NetworkEventListenerProvider` becomes `NetworkEventListenerProvider: NetworkPeersEvents`

## TODO
* 1. introduce `SessionInfo`
* 2. introduce `NetworkPeersEvents` with stream and event type

**Comment by lean-apple** [comment]
Hello, can I work on it ?

**Comment by mattsse** [comment]
assigned
