### ISSUE TITLE
Configure RpcServer from RpcServerArgs

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1287]
### Describe the feature

`RpcServerArgs`contains all settings for the RPC server

https://github.com/paradigmxyz/reth/blob/afb6671a0f8c681e1fc3b3d13d6a33f30c954dd2/bin/reth/src/args/rpc_server_args.rs#L12

the RPC server needs to be configured from the RpcServerArgs

## TODO
* essentially move this section https://github.com/paradigmxyz/reth/blob/afb6671a0f8c681e1fc3b3d13d6a33f30c954dd2/bin/reth/src/node/mod.rs#L143-L151 to RpcServerArgs
* add `RpcServerArgs::server` function that returns `RpcServer`, same trait bounds as the `launch` function

server builder needs some changes so it mirrors the cli args: ref #1231

**Comment by GrapeBaBa** [comment]
can I try it?

**Comment by mattsse** [comment]
please go for it

**Comment by GrapeBaBa** [comment]
wait for #1323

**Comment by GrapeBaBa** [comment]
@mattsse two questions.
1. should we build `RpcServerConfig` with `RpcServerArgs`? I found right now it just use `default`.
2. I can't create a test easily since `Network` has no `default` function or other simple constructor, what is your suggestion here? Use mock or just add `default` function.
