### ISSUE TITLE
Add ratelimiting to OpWitness API

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12871]
### Describe the feature

currently this rpc endpoint is unbounded

https://github.com/paradigmxyz/reth/blob/1b4048e47d42c0053ea9ba216281ceb513d70bc4/crates/optimism/rpc/src/witness.rs#L54-L54

we should add internal ratelimiting because this is fairly expensive:

https://github.com/paradigmxyz/reth/blob/1b4048e47d42c0053ea9ba216281ceb513d70bc4/crates/optimism/rpc/src/witness.rs#L78-L78

## TODO
* make function async (requires adding async_trait macro for DebugExecutionWitnessApiServer) and make this async: https://github.com/paradigmxyz/reth/blob/1b4048e47d42c0053ea9ba216281ceb513d70bc4/crates/rpc/rpc-api/src/debug.rs#L404-L404
* Introduce a new tokio semaphor
* add `Box<dyn TaskSpawner>` to https://github.com/paradigmxyz/reth/blob/1b4048e47d42c0053ea9ba216281ceb513d70bc4/crates/optimism/rpc/src/witness.rs#L78-L78 so we can spawn as blocking
needs update here https://github.com/paradigmxyz/reth/blob/1b4048e47d42c0053ea9ba216281ceb513d70bc4/crates/optimism/node/src/node.rs#L236-L236

**Comment by stevencartavia** [comment]
🙋🏽‍♂️

**Comment by mimisavage** [comment]
I’d like to help with this.
