### ISSUE TITLE
move eip1186 conversion helpers to reth-trie-common proofs

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12886]
### Describe the feature

we currently have these extra functions:

https://github.com/paradigmxyz/reth/blob/83af493179393c81dc2c48374306f2b88cc075db/crates/rpc/rpc-types-compat/src/proof.rs#L7-L16

now that there's a serde feature for 

https://github.com/paradigmxyz/reth/blob/83af493179393c81dc2c48374306f2b88cc075db/crates/trie/common/src/proofs.rs#L174-L176

we can easily move those functions there if we feature gate them behind a `eip1186` feature

## TODO
* convert standalone functions into native ones with features

**Comment by Abeeujah** [comment]
Hi, Can I attempt this issue?
