### ISSUE TITLE
Add Latest State TransactionValidator implementation

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1289]
### Describe the feature

the transaction pool requires a `TransactionValidator`

https://github.com/paradigmxyz/reth/blob/afb6671a0f8c681e1fc3b3d13d6a33f30c954dd2/crates/transaction-pool/src/validate.rs#L30

which is supposed to validate the transaction against protocol specs and the latest state.

It returns an outcome that includes the latest nonce and balance

https://github.com/paradigmxyz/reth/blob/afb6671a0f8c681e1fc3b3d13d6a33f30c954dd2/crates/transaction-pool/src/validate.rs#L15-L19

## TODO

* Add an implementation of this that takes an `AccountProvider` and implements basic transaction checks

**Comment by chirag-bgh** [comment]
I can take this.

**Comment by seroze** [comment]
@mattsse  just to cross check my understanding. 

>which is supposed to validate the transaction against protocol specs and the latest state.

we have to fetch the latest state of the sender account and verify if the current_balance >=  transaction_amount and if txn_nonce matches with last_txn_nonce+1. Are there any more checks that Iam missing ?

>Add an implementation of this that takes an AccountProvider and implements basic transaction checks

How do we fetch the latest state of Account. I couldn't find any class with name AccountProvider ? Is the expectation to implement this class as well ?

**Comment by mattsse** [comment]
>  couldn't find any class with name AccountProvider

this is not fully implemented yet, but we abstract everything over the traits so all impls should be generic over the traits.

> we have to fetch the latest state of the sender account and verify if the current_balance >= transaction_amount and if txn_nonce matches with last_txn_nonce+1.

not necessarily, we need to fetch current balance and nonce which is then used by the pool to update internals.
but we need to ensure nonce > last_txn_nonce because  nonce < last_txn_nonce would be invalid.

**Comment by chirag-bgh** [comment]
@mattsse for what type should be the trait ```TransactionValidator``` implemented?

**Comment by mattsse** [comment]
It should be something like

```rust
pub struct EthTransactionValidator<Client: AccountPorivider> {
   /// This type fetches account info from the db
   client: Client,
   /// whether shanghai is enabled.
   shanghai: bool,
}
```
