### ISSUE TITLE
Change `evm_env_cache` to header cache

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12902]
### Describe the feature

This currently bakes in the `revm` environments into caching: https://github.com/paradigmxyz/reth/blob/51afa4cdc94fc29909cb2b6eda1c30c11e102c00/crates/rpc/rpc-eth-types/src/cache/mod.rs#L240-L241

this will no longer with with upcoming revm changes where these settings will be generic, or if we want to support something that is not revm, like a different kind of execution.

The environment settings are derived from the header:

https://github.com/paradigmxyz/reth/blob/51afa4cdc94fc29909cb2b6eda1c30c11e102c00/crates/evm/src/provider.rs#L28-L37

so what we can do here is:
first change the cache from caching env objects to `Header` and convert the environments on demand

this is only called here:
https://github.com/paradigmxyz/reth/blob/51afa4cdc94fc29909cb2b6eda1c30c11e102c00/crates/rpc/rpc-eth-api/src/helpers/state.rs#L238-L238

so as a first step we can do is change the cache to `Header`,
and move this step:

https://github.com/paradigmxyz/reth/blob/51afa4cdc94fc29909cb2b6eda1c30c11e102c00/crates/rpc/rpc-eth-types/src/cache/mod.rs#L441-L453

**Comment by lakshya-sky** [comment]
@mattsse I would like to work on this?

**Comment by mattsse** [comment]
cool, assigned

**Comment by lakshya-sky** [comment]
How do you to handle the code below. should I deplicate the same logic from above as well?

https://github.com/paradigmxyz/reth/blob/51afa4cdc94fc29909cb2b6eda1c30c11e102c00/crates/rpc/rpc-eth-types/src/cache/mod.rs#L477C29-L482C30
```
                            if let Some(queued) = this.evm_env_cache.remove(&block_hash) {
                                // send the response to queued senders
                                for tx in queued {
                                    let _ = tx.send(res.clone());
                                }
                            }
```
