### ISSUE TITLE
Pass generic header and body in `SealedBlock` to `validate_cancun_gas`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12919]
### Describe the feature

Make `SealedBlock` into `SealedBlock<H, B>` where `H: alloy_consensus::BlockHeader`
https://github.com/paradigmxyz/reth/blob/00c5b69af46f4a781b1b15afd7587592443e91a0/crates/consensus/common/src/validation.rs#L58-L76

**Comment by emhane** [comment]
@0xshikhar do you want to try this?

**Comment by hoank101** [comment]
hi @emhane i can do it

**Comment by 0xshikhar** [comment]
> [@0xshikhar](https://github.com/0xshikhar) do you want to try this?

i can work on that

**Comment by mimisavage** [comment]
Can I tackle this one?

**Comment by hoank101** [comment]
can issign it to me?

**Comment by emhane** [comment]
@hoank101 would be great if you can impl this since it isn't your first sdk related issue

**Comment by klkvr** [comment]
Resolved by https://github.com/paradigmxyz/reth/issues/13236
