### ISSUE TITLE
Pass generic header and body to `validate_shanghai_withdrawals`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12918]
### Describe the feature

Make function generic over header type that impl `H: alloy_consensus::BlockHeader` and body type that impl `B: reth_primitives_traits::BlockBody`, so that `SealedBlock<H, B>`
https://github.com/paradigmxyz/reth/blob/00c5b69af46f4a781b1b15afd7587592443e91a0/crates/consensus/common/src/validation.rs#L38-L56

**Comment by htiennv** [comment]
Hi @emhane , can you assign to me this task? Thanks
