### ISSUE TITLE
Generic data primitives `TreeState`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12920]
### Describe the feature

Make `TreeState` generic over data primitives as `TreeState<N: NodePrimitives = reth_primitives::EthPrimitives`. Generic `N` should be passed to `ExecutedBlock`. Fix the `TreeState` impl accordingly if possible (may return some types that are yet to be made generic over all data primitives or a subset thereof).
https://github.com/paradigmxyz/reth/blob/47245642ca481c58da60e698381981c1edcbb264/crates/engine/tree/src/tree/mod.rs#L86-L388

**Comment by emhane** [comment]
@htiennv do you want to do this?

**Comment by htiennv** [comment]
Thanks!
