### ISSUE TITLE
Generic data primitives `PersistenceAction`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12939]
### Describe the feature

Make `PersistenceAction` generic over data primitives as `PersistenceAction<N: NodePrimitives = reth_primitives::EthPrimitives`. `N` should also be passed to the `ExecutedBlock` contained in one of the variants.
https://github.com/paradigmxyz/reth/blob/47245642ca481c58da60e698381981c1edcbb264/crates/engine/tree/src/persistence.rs#L170-L191

**Comment by lean-apple** [comment]
Hello, may I work in this one ?
