### ISSUE TITLE
Generic data primitives `EngineApiEvent`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12938]
### Describe the feature

Make `EngineApiEvent` generic over data primitives as `EngineApiEvent<N: NodePrimitives = reth_primitives::EthPrimitives`. `N` should also be passed to `BeaconConsensusEngineEvent` contained in one of the variants. Fix the implementations of `EngineApiEvent` accordingly.
https://github.com/paradigmxyz/reth/blob/47245642ca481c58da60e698381981c1edcbb264/crates/engine/tree/src/engine.rs#L271-L294

**Comment by emhane** [comment]
for you @hoank101 ?

**Comment by hoank101** [comment]
yes, please assign to me
