### ISSUE TITLE
Generic node types `PersistenceService`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12941]
### Describe the feature

Full-end making `PersistenceService` generic over data primitives by passing `N::Primitives` to `PersistenceAction` as `PersistenceAction<N::Primitives>`. Update impl bodies accordingly.
https://github.com/paradigmxyz/reth/blob/47245642ca481c58da60e698381981c1edcbb264/crates/engine/tree/src/persistence.rs#L25-L156

Blocked by https://github.com/paradigmxyz/reth/issues/12939

**Comment by lean-apple** [comment]
Sure, thanks :)

**Comment by mimisavage** [comment]
I’d like to work on this.
