### ISSUE TITLE
Configure Shanghai chainspec for Sepolia/Mainnet/Goerli 

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#1298]
## Points of integration

Need to add a new `HardFork::Shanghai` variant, and handle it in all corresponding match statements

* https://github.com/search?q=repo%3Aparadigmxyz%2Freth%20paris&type=code
* https://github.com/search?q=repo%3Aparadigmxyz%2Freth+hardfork&type=code

## Timestamps

| Network | Timestamp  | Date & Time (UTC)  | Fork Hash    | Beacon Chain Epoch |
|---------|------------|---------------|--------------| ---------- |
| Sepolia | `1677557088` | 2/28/2023, 4:04:48 AM | `0xf7f9bc08` | 56832 
| Goerli  | TBA | TBA |  TBA | TBA 
| Mainnet | TBA | TBA |  TBA | TBA 

https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md

**Comment by leruaa** [comment]
I would like to take this on

**Comment by onbjerg** [comment]
Thanks! I've assigned you to the issue. If you feel stuck, open up a draft PR with your questions and someone will help you. If you are prevented from solving the issue, let me know and I will unassign you :smile:
