### ISSUE TITLE
Add support for removing and replacing rpc handlers for the auth module

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#12986]
### Describe the feature

we currently have

https://github.com/paradigmxyz/reth/blob/aea56135d577b0e32b306577f4ed4a89f99e376d/crates/rpc/rpc-builder/src/auth.rs#L214-L222

in the AuthRpcModule, but it would be nice to have if we've had remove+replace as well:

similar to the regular transport modules:

https://github.com/paradigmxyz/reth/blob/aea56135d577b0e32b306577f4ed4a89f99e376d/crates/rpc/rpc-builder/src/lib.rs#L2239-L2243

## TODO
* add remove + replace functions on AuthRpcModule

**Comment by lakshya-sky** [comment]
@mattsse can I take this?

**Comment by mattsse** [comment]
we need this urgently, same with the other pr
so please, only if you have capacity for this

appreciate it, ty

**Comment by hossamanany** [comment]
I’d like to help with this.
I've taken a good look on the code and I can implement this with ease.
