### ISSUE TITLE
Introduce EthMessage variant to NetworkHandleMessage

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13003]
### Describe the feature

we have an event variant for requests:

https://github.com/paradigmxyz/reth/blob/88bde87f7045a44ec384ed65cc1d97e57ea2c87f/crates/net/network/src/network.rs#L477-L483

broadcast messages have their own event variant, like:

https://github.com/paradigmxyz/reth/blob/88bde87f7045a44ec384ed65cc1d97e57ea2c87f/crates/net/network/src/manager.rs#L575-L578

it would be nice to have a way to send `PeerMessage` directly

## TODO

* add new `NetworkHandleMessage::EthMessage` variant

**Comment by tnv1** [comment]
Hi @mattsse, can i take this issue? Thanks

**Comment by mattsse** [comment]
cool, assigned

**Comment by JoshdfG** [comment]
Can I take this from here?
