### ISSUE TITLE
Support sending raw capability messages

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13005]
### Describe the feature

this is currently unimplemented https://github.com/paradigmxyz/reth/blob/88bde87f7045a44ec384ed65cc1d97e57ea2c87f/crates/net/network/src/session/active.rs#L279-L281

but would be nice to have so we can cheaply forward transactions for example.

in order to implement this we need to make a few changes because the connection currently only operates on `EthMessage`, which doesn't have a way to send raw eth messages.

https://github.com/paradigmxyz/reth/blob/88bde87f7045a44ec384ed65cc1d97e57ea2c87f/crates/net/network/src/session/conn.rs#L18-L18

https://github.com/paradigmxyz/reth/blob/88bde87f7045a44ec384ed65cc1d97e57ea2c87f/crates/net/eth-wire/src/ethstream.rs#L305-L305

but what we can do is add a helper function to `EthStream` and `RlpxSatelliteStream` that accepts a `RawCapabilityMessage`

## TODO
* 1. add support for sending `RawCapabilityMessages` in EthStream + RlpxSatelliteStream with an additional function. This likely needs some `encode` fn on `RawCapabilityMessage`, see also https://github.com/paradigmxyz/reth/blob/88bde87f7045a44ec384ed65cc1d97e57ea2c87f/crates/net/eth-wire/src/ethstream.rs#L333-L333
* 2. handle outgoing raw cap messages: https://github.com/paradigmxyz/reth/blob/88bde87f7045a44ec384ed65cc1d97e57ea2c87f/crates/net/network/src/session/active.rs#L280-L280

**Comment by mimisavage** [comment]
Can I contribute to this one?
