### ISSUE TITLE
Rely on upstream `Decodable` and `Encodable` implementation for `OpTxType` wrapper

### ISSUE THREAD

**Issue by ozgunozerk** [paradigmxyz/reth#13031]
### Describe the feature

When https://github.com/paradigmxyz/reth/issues/12333 was addressed by https://github.com/paradigmxyz/reth/pull/12443, the upstream code did not have `Encodable` and `Decodable` traits implemented for `OpTxType`. 

Now that the upstream code has matured, we should rely on their implementations instead of duplicating the code which may potentially result in inconsistencies in the future.

**Comment by mattsse** [comment]
we can get rid of the wrapper type entirely #12715
