### ISSUE TITLE
[Feature] Make `CacheAction` generic over `NodePrimitives`

### ISSUE THREAD

**Issue by klkvr** [paradigmxyz/reth#13048]
### Describe the feature

We need to add `NodePrimitives` generic to https://github.com/paradigmxyz/reth/blob/890f082453490828258dbb9d84e131f55f65cb25/crates/rpc/rpc-eth-types/src/cache/mod.rs#L498-L529

It needs to be added to the struct impl and passed to all variants fields. This will require making some other types generic over Block/NodePrimitives (e.g. `ChainChange` would need entire NodePrimitives and `BlockWithSendersResponseSender` just `Block`)

**Comment by klkvr** [comment]
@htiennv sure! assigned

**Comment by htiennv** [comment]
Thanks @klkvr

**Comment by mimisavage** [comment]
I'd love to work on this!

**Comment by klkvr** [comment]
hey @htiennv do you need any help here?

**Comment by klkvr** [comment]
@htiennv sorry, we're blocked by this so taking this over in https://github.com/paradigmxyz/reth/pull/13146

**Comment by htiennv** [comment]
Hi @klkvr, I have some things to do so I haven't been online often in the past few days. Sorry for the delay
