### ISSUE TITLE
Use `arbitrary/proptest` instead of `rand` on generating random values

### ISSUE THREAD

**Issue by joshieDo** [paradigmxyz/reth#1306]
### Describe the feature

Currently we're using `rand` on [`crates/interfaces/src/test_utils/generators.rs`](https://github.com/paradigmxyz/reth/blob/main/crates/interfaces/src/test_utils/generators.rs).

We should change them for their `arbitrary/proptest` implementation. If the type cannot be truly random, then their arbitrary implementation should be done manually on its type. (eg. [TransactionSigned](https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/transaction/mod.rs#L747-L788))

**Comment by i-m-aditya** [comment]
I will pick this one.

**Comment by m-trellis** [comment]
@i-m-aditya Are you still working on this?

**Comment by peyha** [comment]
Would it be possible to take this task if there is no progress right now ?

**Comment by m-trellis** [comment]
> Would it be possible to take this task if there is no progress right now ?

Yep, feel free to take this one.

**Comment by samtvlabs** [comment]
@m-trellis still picking this up ? I would love to help

**Comment by justcode740** [comment]
it seem this issue hasn't been taken for couple months now i will take it then.
@joshieDo could u clarify bit on what's the issue with current impl?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Can I take this

**Comment by joshieDo** [comment]
this has since evolved into a more complex issue, and i'm not sure on the benefit anymore. closing for the time being
