### ISSUE TITLE
Use --builder.gaslimit cli argument for payload building

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13128]
### Describe the feature

this field is currently unused:

https://github.com/paradigmxyz/reth/blob/53243a29f30021ee6061f1b11cb3560de1cd9ac2/crates/node/core/src/args/payload_builder.rs#L19-L21

we need to wire this to the 

https://github.com/paradigmxyz/reth/blob/53243a29f30021ee6061f1b11cb3560de1cd9ac2/crates/ethereum/payload/src/lib.rs#L59-L59

during setup:

https://github.com/paradigmxyz/reth/blob/53243a29f30021ee6061f1b11cb3560de1cd9ac2/crates/ethereum/node/src/node.rs#L256-L256

for this we should introduce a new `Config` container type

**Comment by v121kwehqfjkwewuief** [comment]
Can I tackle this one?

**Comment by mattsse** [comment]
assigned

**Comment by rkrasiuk** [comment]
https://github.com/paradigmxyz/reth/issues/3233 was not actually resolved
