### ISSUE TITLE
Move PruneLimiter to prune crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13149]
### Describe the feature

This type currentl resides in the prune/types crate but we only need this in prune crate:

https://github.com/paradigmxyz/reth/blob/08c9df8cb37300b45fdc107fe37163f04429e833/crates/prune/types/src/limiter.rs#L9-L9

we should move this because we need this for #13041

and we also need to flip this function:

https://github.com/paradigmxyz/reth/blob/08c9df8cb37300b45fdc107fe37163f04429e833/crates/prune/types/src/pruner.rs#L105-L105

and impl this for Prunelimiter instead

same here:

https://github.com/paradigmxyz/reth/blob/08c9df8cb37300b45fdc107fe37163f04429e833/crates/prune/types/src/pruner.rs#L132-L132

**Comment by lean-apple** [comment]
Hello :), may I work on it ?

**Comment by mattsse** [comment]
assigned, 

I'm only 80% sure we can easily do this, in case this becomes a mess we need to reevaluate
