### ISSUE TITLE
Register tasks that can be shutdown in TaskManager

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1315]
### Describe the feature

the TaskManager sends a signal to terminate all tasks spawned via its context.
The tokio runtime not necessarily waits for all tasks to finish.

# TODO
add `taskmanager::shutdown` function that
* sends an additional shutdown signal to tasks that need get notified
* spawn `taskmanager::shutdown` after ctrl-c was received

ref #1314

**Comment by mattsse** [comment]
now integrated

**Comment by seroze** [comment]
Hi @mattsse is this done ?

**Comment by mattsse** [comment]
still useful,
do you want to take this?

**Comment by seroze** [comment]
Yeah, I'll take a look into this.

**Comment by seroze** [comment]
I have few doubts regarding this.
> add taskmanager::shutdown function that
>       - sends an additional shutdown signal to tasks that need get notified 

The shutdown function should do two things. 
1. wait till shutdown signal is received
2. after we receive the shutdown signal, notify to all tasks managed by TaskExecutor to shutdown. 

Based on this I'm expecting the code to be something like the below. 

```
    /// deals with an external shutdown command via CTRL+C
    pub async fn shutdown(self) {

        let _  = self.on_shutdown.clone().await ; //this line waits till we receive a shutdown signal 
        
        //this will trigger all tasks to shutdown
        self._signal.fire();
    }
```

Is this what you are expecting ?

**Comment by mattsse** [comment]
> wait till shutdown signal is received

no, it fires the shutdown signal and awaits all tasks that are spawned with a listener

**Comment by seroze** [comment]
@mattsse apologies for delayed work on this. Iam a bit new to tokio stuff. I was spending some time offline to understand the mechanics.

> The shutdown function should do two things.
> 
> 1. wait till shutdown signal is received
> 2. after we receive the shutdown signal, notify to all tasks managed by TaskExecutor to shutdown.

I think 2 should be something like this, lemme know if it's incorrect. 
```
    pub async fn shutdown(self)  -> {
        self._signal.fire(); // notify tasks, i.e once you send the message via channel the senders dead 
        self.on_shutdown.clone().await ; // awaiting until all the senders/signal's  are dead 
    }
```

Few things i want to understand from the codebase. 

```
3. Whenever sender(aka signal) drops or sends message. the receivers will get terminated too 
and hence the shutdown future will terminate so `shutdown.await` will wait till it gets terminated and 
it makes sense

/// A Future that resolves when the shutdown event has been fired.
#[derive(Debug, Clone)]
pub struct Shutdown(Shared<oneshot::Receiver<()>>);

impl Future for Shutdown {
    type Output = ();

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let pin = self.get_mut();
        if pin.0.is_terminated() || pin.0.poll_unpin(cx).is_ready() {
            Poll::Ready(())
        } else {
            Poll::Pending
        }
    }
}

```

> 1. wait till shutdown signal is received
https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/runner.rs#L38 says that drop(task_manager) will fire the shutdown signal. So we can just add a custom drop impl here in which we trigger the shutdown function. I think this should be sufficient. 

https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/runner.rs#L159  has the logic of waiting till CTRL+C is pressed, so we need not implment anything extra for this

**Comment by supernovahs** [comment]
I can take this
