### ISSUE TITLE
Add DelegatedPool implementation

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13179]
### Describe the feature

there are usecases where the pool is extended with additional fields:

https://github.com/mattsse/rbuilder/blob/39f4903805f61af8e73cfe84237f80e98e15e867/crates/transaction-pool-bundle-ext/src/bundle_supported_pool.rs#L111-L113

we can add support for this via a single helper trait, something like this should work:
```rust
trait PoolDelegate {
  
 fn pool(&self) -> Pool
}

impl<T: PoolDelegate> TransactionPool for T { ... }
```

+ a few additional bounds hehe

**Comment by hoank101** [comment]
i @mattsse i can do it

**Comment by mattsse** [comment]
@hoank101 I'm only like 80% sure this works though

**Comment by royvardhan** [comment]
@hoank101 Hi, are you still working on this?

**Comment by vic-Gray** [comment]
I'd like to handle this task.

**Comment by mattsse** [comment]
realized this isn't possible because of the auto_impl
