### ISSUE TITLE
Reuse `alloy_trie::TrieAccount`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13175]
### Describe the feature

we moved this type to alloy-trie

https://github.com/paradigmxyz/reth/blob/242bbaa9c460d90b5a307926d9810a22d1585cfc/crates/trie/common/src/account.rs#L10-L12

and we can phase it out now.

this conversion is now also natively supported:

https://github.com/paradigmxyz/reth/blob/242bbaa9c460d90b5a307926d9810a22d1585cfc/crates/trie/common/src/account.rs#L30-L30

this we need to flip to:

https://github.com/paradigmxyz/reth/blob/242bbaa9c460d90b5a307926d9810a22d1585cfc/crates/primitives-traits/src/account.rs#L32-L32

this will result in an issue:

https://github.com/paradigmxyz/reth/blob/242bbaa9c460d90b5a307926d9810a22d1585cfc/crates/trie/common/src/account.rs#L64-L64

but we can add a helper fn for this conversion instead.

**Comment by hoank101** [comment]
hi @mattsse i can do it

**Comment by vic-Gray** [comment]
Can I work on this, please?
