### ISSUE TITLE
Cannot sync latest version from genesis

### ISSUE THREAD

**Issue by MysticRyuujin** [paradigmxyz/reth#13217]
### Describe the bug

There appears to be a problem with the following transaction:

```text
ERROR Stage encountered an execution error: EVM reported invalid transaction (0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060): transaction validation error: lack of funds (0) for max fee (1050000000000031337) stage=Execution bad_block=46147
```

I see that something is off with this transaction as it's referenced in both #3514 and #11934 - I'm not sure what it is about this transaction that causes it to show up in multiple issues, but here it is again.

### Steps to reproduce

Start syncing a node from genesis.

### Node logs

```text
2024-12-08T00:49:38.472063Z  INFO Finished stage pipeline_stages=3/12 stage=SenderRecovery checkpoint=21346405 target=21346405 stage_progress=100.00% stage_eta=unknown
2024-12-08T00:49:38.586162Z  INFO Preparing stage pipeline_stages=4/12 stage=Execution checkpoint=0 target=21346405
2024-12-08T00:49:38.586289Z  INFO Executing stage pipeline_stages=4/12 stage=Execution checkpoint=0 target=21346405
2024-12-08T00:49:54.896862Z  INFO Status connected_peers=57 stage=Execution checkpoint=0 target=21346405
2024-12-08T00:50:03.624298Z ERROR Stage encountered an execution error: EVM reported invalid transaction (0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060): transaction validation error: lack of funds (0) for max fee (1050000000000031337) stage=Execution bad_block=46147
2024-12-08T00:50:03.624888Z  INFO Unwinding{stage=Finish}: Starting unwind from=0 to=0 bad_block=Some(46147)
```

### Platform(s)

Linux (x86)

### Container Type

Docker

### What version/commit are you on?

`ghcr.io/paradigmxyz/reth:v1.1.2`

### What database version are you on?

whatever v1.1.2 defaults to

### Which chain / network are you on?

mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [x] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
hmm, odd

can't reproduce on v1.1.2 via `--debug.tip 0x3cfe659ca32eaa84ae366efa02d9d3725cb9aef9bbe3abc8706a595dfead40f2`  https://etherscan.io/block/46150

syncs past that block just fine

> INFO Finished stage pipeline_stages=12/12 stage=Finish checkpoint=46150 target=46150

**Comment by MysticRyuujin** [comment]
I think there's something wrong with my storage drive

**Comment by mrabino1** [comment]
out of curiosity, what hw are running this on? (emphasis on cpu)

**Comment by MysticRyuujin** [comment]
5950X

**Comment by mrabino1** [comment]
interesting... 

background is that when i had the initial issue i have the same initial sync (general) on the same hw over and over... i have two other machines with similar hw specs (nucs i7) but neither of those had the same sync issue. 

With zero evidence rather just intuition, i think the issue may be down to a processor variant and how the code is executed. Something like this was seen a few years ago with prysm which impacted on a small subset of hw users that had that specific variant of chip.

**Comment by MysticRyuujin** [comment]
Sounds plausible, but I'm afraid that I may have storage issues stemming from a bad motherboard, and it would be a waste of time to use my current hardware to diagnose. My NVMe drives occasionally drop out, and it's [somewhat of a known issue](https://www.reddit.com/r/gigabytegaming/comments/e99wc0/x570_aorus_elite_and_nvme_m2_disappearing/) so I'm gonna bite the bullet and buy a new motherboard cuz I've been having this issue on and off for a while now. However, I will try again and re-open if the issue persists.
