### ISSUE TITLE
Use relaxed SealedBlock in txpool API

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13223]
### Describe the feature

the update fn currently expects a specific block type

https://github.com/paradigmxyz/reth/blob/d68d7c8da0f13acfa356284c4ecf54047f964c25/crates/transaction-pool/src/validate/mod.rs#L209-L209

we can either solve this introducing a new associated type on the validator trait, or provide the generics on the function.
the latter would be easier but would not allow for type specific validator impls, but this should likely be fine and we can still change it later.

## TODO
* make `SealedBlock` arg generic over header+body

**Comment by stevencartavia** [comment]
🙋🏽‍♂️
