### ISSUE TITLE
Relax txpool maintain functions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13225]
### Describe the feature

this currently still pins types to specific reth-primitives

https://github.com/paradigmxyz/reth/blob/13302ca655d3d21422be683881a4248499f0f1d2/crates/transaction-pool/src/maintain.rs#L73-L84

we can likely move away from them already and only rely on traits

### Additional context

ref #13223

**Comment by stevencartavia** [comment]
🙋🏽‍♂️
