### ISSUE TITLE
Generic data primitives block builder test framework

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#13239]
### Describe the feature

Make block building test framework generic over data primitives. The type `TestBlockBuilder` is already generic over data primitives, hence its implementation needs to be extended to the generic type (not just implemented for the default type as is now).

https://github.com/paradigmxyz/reth/blob/3af2afe99528750dc7465433c4248fd1435bf3e0/crates/chain-state/src/test_utils.rs#L65-L330

**Comment by tnv1** [comment]
Hi @emhane , can you assign me? Thanks

**Comment by emhane** [comment]
how is it going @tnv1 ? if you need any help, suggest opening a draft pr

**Comment by hoank101** [comment]
hi @emhane please help me review
