### ISSUE TITLE
Add dropaware Sender new type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13242]
### Describe the feature

the way the rpc cache works is a single loop over actions:

https://github.com/paradigmxyz/reth/blob/3af2afe99528750dc7465433c4248fd1435bf3e0/crates/rpc/rpc-eth-types/src/cache/mod.rs#L345-L345

disk lookups also reuse that single channel and send actions back to that sender:

https://github.com/paradigmxyz/reth/blob/3af2afe99528750dc7465433c4248fd1435bf3e0/crates/rpc/rpc-eth-types/src/cache/mod.rs#L360-L360

in the meantime the oneshot response senders wait for that action:

https://github.com/paradigmxyz/reth/blob/3af2afe99528750dc7465433c4248fd1435bf3e0/crates/rpc/rpc-eth-types/src/cache/mod.rs#L222-L225

these response channels remain in the lru until the action arrives in the mainloop.

This is problematic if the spawned task panics because then nothing is emitted back to the mainloop.
for example if this operation panics
https://github.com/paradigmxyz/reth/blob/3af2afe99528750dc7465433c4248fd1435bf3e0/crates/rpc/rpc-eth-types/src/cache/mod.rs#L365-L372
no action is generated by that task.

we can solve this by introducing a drop aware sender wrapper that sends an action on drop, if not consumed:

like:

https://github.com/paradigmxyz/reth/blob/3af2afe99528750dc7465433c4248fd1435bf3e0/crates/rpc/rpc-eth-types/src/cache/mod.rs#L373-L376

```rust
struct ActionSender {
  blockhash: B256,
  tx: Option<UnboundedSender<...>
}

impl ActionSender {
  fn send_block(self,...)
}

impl Drop for ActionSender {
  if let Some(tx)
   ... send error
}
```

**Comment by coxmars** [comment]
Hi @mattsse I would like to help you in this one. I will open a PR asap 🫡

**Comment by mattsse** [comment]
ty, assigned

**Comment by ABD-AZE** [comment]
Hey @mattsse,
Can I work on this PR?
