### ISSUE TITLE
Replace hardcoded data primitives in `EngineApiTreeHandler` impl

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#13244]
### Describe the feature

Replace hardcoded data primitives in method signatures in `EngineApiTreeHandler` impl. Use associated types on generic `N: NodePrimitives` on `EngineApiTreeHandler` to replace hard coded types, e.g. replace use of `alloy_consensus::Header` with `N::BlockHeader`.
https://github.com/paradigmxyz/reth/blob/c7c84f2d3fc59cbec2288f6a097dc029c9fb0375/crates/engine/tree/src/tree/mod.rs#L544-L2611

**Comment by aguzmant103** [comment]
Can I take this one? @emhane

**Comment by mattsse** [comment]
this is a bit to complex atm for a good first issue so
