### ISSUE TITLE
Always use constructor functions for block types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13247]
### Describe the feature

having this fields pub is very horrible:

https://github.com/paradigmxyz/reth/blob/3c132958d1932fd3038ee27fd66cfe39d75a078d/crates/primitives/src/block.rs#L159-L161

we need to move away from that, 
first we need to replace all inits with new functions, like:

https://github.com/paradigmxyz/reth/blob/3c132958d1932fd3038ee27fd66cfe39d75a078d/crates/ethereum/evm/src/execute.rs#L625-L628

**Comment by faheelsattar** [comment]
can i pick this @mattsse ?

**Comment by mattsse** [comment]
assigned

**Comment by vic-Gray** [comment]
I'd love to work on this!
