### ISSUE TITLE
Support eth/68

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#1326]
### Describe the feature

We're missing the eth/68 protocol implementation.
1. Spec: https://eips.ethereum.org/EIPS/eip-5793
2. Geth PR https://github.com/ethereum/go-ethereum/pull/25980

**Comment by jinsankim** [comment]
I'd like to take this on.

**Comment by gakonst** [comment]
Go for it. (cc @rkrasiuk would like you to review this work, should be simple and get you some visibility on the p2p code)
