### ISSUE TITLE
Make `MemoryOverlayStateProvider` a type alias for the ref one

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#13280]
### Describe the feature

`MemoryOverlayStateProvider` is the exact same type as `MemoryOverlayStateProviderRef<'static>`.

Make it a type alias, and the inline the `impl_state_provider` macro.

### Additional context

https://github.com/paradigmxyz/reth/blob/37f3933db2d8a5a909323cf8eca58646d0f1e04b/crates/chain-state/src/memory_overlay.rs#L24

**Comment by vic-Gray** [comment]
May I take this issue on?

**Comment by codeWhizperer** [comment]
can I work on this?
