### ISSUE TITLE
Remove manual implementations of `core::error::Error`

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#13284]
### Describe the feature

Remove manual implementations of `core::error::Error` in favor of using `thiserror` v2, which includes support for `no_std`.

`From<>` implementation must be moved to `#[from]` where applicable.

You can search for "core::error::Error for" in the codebase to find all of the relevant instances.

**Comment by lean-apple** [comment]
Hello, can I work on it ?

**Comment by PelleKrab** [comment]
I can take.

**Comment by DaniPopes** [comment]
Thanks! Assigning you
