### ISSUE TITLE
Remove total difficulty from rpc

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13297]
### Describe the feature

total difficulty has been deprecated https://github.com/ethereum/execution-apis/pull/570

and we can start removing it, starting with rpc:

https://github.com/paradigmxyz/reth/blob/1602baef6d08932a723139ad53f57d2923218bd5/crates/rpc/rpc-eth-api/src/helpers/block.rs#L67-L76

## TODO
* simplify rpc block functions by removing total difficulty

**Comment by mvares** [comment]
@mattsse here needs more something? If not, close this
