### ISSUE TITLE
Generic data primitives `BeaconConsensusEngine`.

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#13319]
### Describe the feature

Make `BeaconConsensusEngine` generic over data primitives.

https://github.com/paradigmxyz/reth/blob/5b19badd9b652d9ebf53826954e488436e983753/crates/consensus/beacon/src/engine/mod.rs#L104-L1788

The nested type `BeaconConsensusEngineEvent` must be generalised to `BeaconConsensusEngineEvent<N::Primitives>`.

Then the signatures of the impl body must be fixed accordingly, i.e. where `SealedHeader` is used, we want to use `SealedHeader<reth_node_types::HeaderTy<N>>`. To make this possible, we need to constraint the generic `N: EngineNodeTypes` on `BeaconConsensusEngine` to `N: EngineNodeTypes<Primitives = EthPrimitives>` for now. Add any new adapters type aliases sides `reth_node_types::HeaderTy` that are needed and aren't defined yet in `reth-node-types`.

**Comment by emhane** [comment]
@htiennv do you want to implement this?

**Comment by emhane** [comment]
blocked by https://github.com/paradigmxyz/reth/issues/13320

**Comment by klkvr** [comment]
This type is only used by legacy engine which we're planning to remove soon, so I think we don't need this?
