### ISSUE TITLE
Use generic block in `CanonicalStateUpdate`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#13328]
### Describe the feature

Use generic block, use default generic `reth_primitives::Block`
https://github.com/paradigmxyz/reth/blob/c553b1e86d8200effda90fff5711870fb25642d1/crates/transaction-pool/src/traits.rs#L711-L737

**Comment by emhane** [comment]
@hoank101 encourage you to finish the pr, it's on the right track :)

**Comment by mattsse** [comment]
completed
