### ISSUE TITLE
Generic block in tx pool

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#13327]
### Describe the feature

Use generic block
https://github.com/paradigmxyz/reth/blob/328d4937f2bf11e8c9580758e64d4ce9c8251286/crates/transaction-pool/src/validate/mod.rs#L153-L210

**Comment by nadtech-hub** [comment]
✋

**Comment by emhane** [comment]
how is it going @nadtech-hub ?

**Comment by mattsse** [comment]
this has been completed

**Comment by nadtech-hub** [comment]
who did make it?
