### ISSUE TITLE
Outdated stages docs

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1333]
### Describe the feature

parts of https://github.com/paradigmxyz/reth/blob/main/docs/repo/crates/stages.md are no longer accurate, for example the Pipeline struct

probably a good idea to reduce/remove code here.

**Comment by matias-gonz** [comment]
Hey I can work on this 🤓

**Comment by gakonst** [comment]
@matias-gonz the ideal solution would be to start moving all these notes into the code comments! that way we don't need to maintain outdated code in the docs
