### ISSUE TITLE
Gas limit does not increase with --builder.gaslimit 50000000

### ISSUE THREAD

**Issue by sandakersmann** [paradigmxyz/reth#13344]
### Describe the bug

Gas limit does not increase on blocks made with Reth running with the **--builder.gaslimit 50000000** flag.

### Steps to reproduce

1. Start client with --builder.gaslimit 50000000
2. Create block
3. Block made with a 30M gas limit

### Node logs

```text

```

### Platform(s)

Linux (x86)

### Container Type

Not running in a container

### What version/commit are you on?

v1.1.2

### What database version are you on?

N/A

### Which chain / network are you on?

Ethereum

### What type of node are you running?

Full via --full flag

### What prune config do you use, if any?

N/A

### Code of Conduct

- [x] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
closing as dup #13128

is prio though, cc @rkrasiuk
