### ISSUE TITLE
use batch tx validation in eth validator

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#13383]
we currently create a new state provider per tx:

https://github.com/paradigmxyz/reth/blob/fb649977a1f7c3faeab6809fe0b89b3d083cf4c4/crates/transaction-pool/src/validate/eth.rs#L348-L352

this could be optimized if we validate txs in batches and only open the latest state once.

this needs some changes so that we can cache the provider when iterating over a list of txs

cc @hai-rise 

              btw @hai-rise a similar problem exists here:

https://github.com/paradigmxyz/reth/blob/fb649977a1f7c3faeab6809fe0b89b3d083cf4c4/crates/transaction-pool/src/validate/eth.rs#L66-L83

this could use the same provider for all txs, could easily do this if we flip these

_Originally posted by @mattsse in https://github.com/paradigmxyz/reth/issues/13382#issuecomment-2541430597_

**Comment by Elvis339** [comment]
Hey! This seems nice, can I take this?

**Comment by PedroRosalba** [comment]
May I take this issue on?
