### ISSUE TITLE
Display hardforks on startup

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#1343]
### Describe the feature

On startup, the hardforks should be displayed. Example:

```
Hardforks:
- Homestead: Block 0
- London: Block 1
- Paris: TTD 1000
- Shanghai: Timestamp 203023214012
```

**Comment by literallymarvellous** [comment]
I'd like to take this on

**Comment by brendanwenzel** [comment]
@literallymarvellous are you still working on this? I'd be interested in picking this up, if not.

**Comment by literallymarvellous** [comment]
Nah, go ahead.

**Comment by brendanwenzel** [comment]
@onbjerg Is this what you have in mind? 

![Image](https://user-images.githubusercontent.com/222824/227652227-d6a43221-0bae-4f62-8864-f9aea0f68e84.png)

**Comment by mattsse** [comment]
that'd be great.

ideally we have a type or util type that takes all `Hardforks` and emits this table via `Display` impl

**Comment by seroze** [comment]
Hi @mattsse , Is anyone working on this ?

**Comment by mattsse** [comment]
this is still up for grabs

**Comment by seroze** [comment]
yep

**Comment by onbjerg** [comment]
Please note that we prob don't want the full link to the upgrade spec itself (too verbose imo)
