### ISSUE TITLE
Remove `const_format` dependency

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#13496]
### Describe the feature

Its only usage is when formatting version specifiers, e.g. https://github.com/paradigmxyz/reth/blob/de477ba91a95e0e339f1b111788818e37de22800/crates/node/core/src/version.rs#L19

We can move this logic into the build script which makes it more readable and removes the dependency.

This practically means replacing the const_format calls with `env!("NAME")`, and moving the formatting logic to build.rs with `println!("cargo:rustc-env=NAME={value}")`

**Comment by stevencartavia** [comment]
🙋🏽‍♂️

**Comment by aniketch07** [comment]
Is this issue still available?

**Comment by ekumamatthew** [comment]
Would love to tackle this!

**Comment by mattsse** [comment]
this will be completed in #13504
