### ISSUE TITLE
Investigate sccache

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#1350]
### Describe the feature

[sccache] has an integration with the GitHub actions cache, so it might be worth considering using this for builds.

The main advantage of sccache over the cache we use now is that sccache is safely shareable across different workflows and branches, since caching is done per dependency/build flags pair. A bit of investigation is needed to figure out if this is still the case with GitHub's cache, or if an external cache would be needed

[sccache]: https://github.com/mozilla/sccache

**Comment by mattsse** [comment]
I use it locally and it greatly speeds up related builds ethers,foundry,reth

I guess we need to set RUST_WRAPPER and configure a cache https://github.com/mozilla/sccache/blob/main/docs/GHA.md

**Comment by onbjerg** [comment]
@mattsse The main question is mostly how it works with GH cache isolation. I use it locally too

Currently each job that requires building takes anywhere between 2-5 minutes *per job* just to build, and this is with our current cache. That adds up!

**Comment by onbjerg** [comment]
No definite improvement (other than the cache on GH being smaller because it was deduplicated)
