### ISSUE TITLE
Add `seek_exact` equivalent for `seek_by_key_subkey`

### ISSUE THREAD

**Issue by MegaRedHand** [paradigmxyz/reth#1352]
### Describe the feature

It would be useful to have a `seek_exact` equivalent for the `seek_by_key_subkey` method, that returns `None` when the entry doesn't exist. This reduces the checks for when we need to conditionally delete an entry. An example:
https://github.com/paradigmxyz/reth/blob/a6c8178d7f863c360e6d24e60073b34c713705b4/crates/stages/src/stages/execution.rs#L363-L366

Also, I propose renaming `seek_by_key_subkey` to `seek_dup`, so that it's consistent with all the `*_dup` methods.

**Comment by literallymarvellous** [comment]
I'd like to take this.
