### ISSUE TITLE
Make `SubscriptionId`compatible with client proc macro for EthFilter

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1353]
### Describe the feature

https://github.com/paradigmxyz/reth/pull/1320 modified the `eth_filter` trait and added the `jsonrpsee::SubscriptionId` type as argument. however the client derive macro does not like the `<'_>` lifetime and the server derive macro does not like the `'static` lifetime...

## TODO

make both macros compile by either:
* figure out how to compile both 
* replace `SubscriptionId` with a new type `FilterId` that can be converted to `SubscriptionId` (we need `SubscriptionId` because this used used by the `idProvider`)

**Comment by leruaa** [comment]
I would like to take this on
