### ISSUE TITLE
Make benchmark inputs deterministic

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#13535]
### Describe the feature

there are a few benchmarks that use default proptest to generate their inputs, however this is not ideal because the randomness creates a lot of noise on codspeed

these should be changed to use the deterministic proptest runner (TestRunner::deterministic()) or rng (TestRng::deterministic_rng) when creating inputs

 you can find all occurences by searching for "proptest" under benches/ paths

**Comment by hoank101** [comment]
hi @DaniPopes i can do it

**Comment by rutefig** [comment]
May I pick this up?

**Comment by aidenwong812** [comment]
Can I attempt this issue?

**Comment by ekumamatthew** [comment]
Can I be assigned to this?

**Comment by Rjected** [comment]
@ekumamatthew @aidenwong812 @rutefig there are more benches to make deterministic after #13436, feel free to submit PRs!

**Comment by VyuduInc** [comment]
I’d love to work on this task.

**Comment by DaniPopes** [comment]
Thanks everyone!
