### ISSUE TITLE
Save peers as enr isntead of NodeRecord

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1384]
### Describe the feature

On drop we're saving a file with all `NodeRecords`:

https://github.com/paradigmxyz/reth/blob/c415221876110914699366a85bfd4fb2e72a62b8/bin/reth/src/node/mod.rs#L391-L394

https://github.com/paradigmxyz/reth/blob/c415221876110914699366a85bfd4fb2e72a62b8/crates/net/network/src/manager.rs#L299-L301

however, some peers announce a fork id in discovery which we should also save

https://github.com/paradigmxyz/reth/blob/c415221876110914699366a85bfd4fb2e72a62b8/crates/net/network/src/peers/manager.rs#L755-L756

## TODO

* convert `Peer -> Enr` with "eth" field, ref https://github.com/paradigmxyz/reth/blob/c415221876110914699366a85bfd4fb2e72a62b8/crates/net/discv4/src/lib.rs#L443-L455

* ideally, move this conversion to new function in `NodeRecord` `fn int_enr_builder(self) -> EnrBuilder`
* update file reading code in `NetworkConfig`

**Comment by leruaa** [comment]
I would like to take this on

**Comment by leruaa** [comment]
@mattsse I think we won't be able to persist peers as `Enr` because when the node record is updated, the signature need to be updated as well, and when a `Enr` is decoded from rlp the signature is verified: https://github.com/sigp/enr/blob/79d2df3cf2727386fc42f9233181af7ea17b2386/src/lib.rs#L1020

**Comment by gakonst** [comment]
Just read through the issue. This makes sense, closing.
