### ISSUE TITLE
Native `Log` type does not match ethers-rs Log type

### ISSUE THREAD

**Issue by irisdv** [paradigmxyz/reth#1396]
### Describe the bug

I'd like to use `Log` type but right now the native `Log` type does not match ethers-rs Log type. 
Using Log from `reth_primitives::rpc` result in mismatched types with H256 and Bytes because `topics` expects a Vec of H256 from `reth_primitives::rpc::H256` and `data` expects a struct `reth_primitives::rpc::Bytes`.

Is there a native type that matches `reth_primitives::rpc::Log` or a workaround to make it work ? 

```
reth_primitives::rpc::Log {
    pub address: Address,
    pub topics: Vec<H256>,
    pub data: Bytes,
    pub block_hash: Option<H256>,
    pub block_number: Option<U64>,
    pub transaction_hash: Option<H256>,
    pub transaction_index: Option<U64>,
    pub log_index: Option<U256>,
    pub transaction_log_index: Option<U256>,
    pub log_type: Option<String>,
    pub removed: Option<bool>,
}
```

```
reth_primitives::Log {
    pub address: Address,
    pub topics: Vec<H256>,
    pub data: Bytes,
}
```

### Steps to reproduce

```
use reth_primitives::{
    rpc::Log,
    H256, Bytes
};

let topics : H256 = H256::from(&topic.to_bytes_be()));
let data : Bytes = vec_felt_to_bytes(event.data);

let log = Log {
       address: H160::from_slice(&contract_address.0),
       topics,
        data,
        block_hash: None,
        block_number: None,
        transaction_hash: None,
         transaction_index: None,
         log_index: None,
         transaction_log_index: None,
         log_type: None,
         removed: None,
};
```

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

c41c343

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by gakonst** [comment]
@mattsse assigning as the expectation would be that ethers <> reth logs should be compatible

**Comment by onbjerg** [comment]
While I understand the frustration with this issue, I think optimistically closing it is the right path to go, as it requires multiple changes to the primitives types in reth. Alloy is currently being built out (https://github.com/alloy-rs) and the thought is that we'd re-use the primitives of Alloy for reth, both in terms of the core primitives and the RPC primitives. This will take a while, though.

For now, you have to resort to converting the types

**Comment by gakonst** [comment]
https://github.com/SorellaLabs/ethers-reth this has conversion bindings from reth to ethers FWIW until we have finished the migration of our codebases to alloy types
