### ISSUE TITLE
Validate that withdrawal index is monotonically increasing 

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#1399]
Ref https://github.com/paradigmxyz/reth/pull/1322#discussion_r1108319581

Validate that the index of the first withdrawal is monotonically increasing in relation to the last processed withdrawal (in the previous block or earlier).

This check should be added in `validate_block_regarding_chain` function
https://github.com/paradigmxyz/reth/blob/main/crates/consensus/src/validation.rs#L295-L302

It also requires adding a `WithdrawalProvider` in order to look up the last processed withdrawal.

**Comment by GrapeBaBa** [comment]
Let me try it.
