### ISSUE TITLE
Add metered channel abstractions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#140]
Different parts of the codebase will exchange information via (unbounded)channels.

The benefit of an unbounded channel is that a `send` will always succeed, this is important if we want to ensure that a value will arrive as long as the channel is not closed.

Values will be buffered, however, which makes the system memory the implicit upper bound of channels. A stalled channel could cause issues here. For debugging/testing purposes we could write abstractions that keep track of how many values are being sent/received via a global counter or even via `metrics`.

**Comment by akirillo** [comment]
#707 introduces a `MeteredStream` that tracks inbound & outbound bytes for any types that implement `AsyncRead` and/or `AsyncWrite`, that should apply to all unbounded channels, right? In which case, I'm happy to take a stab at this issue as it will build on top of #707

**Comment by akirillo** [comment]
Drafting an approach to this in #726, my main concern is that if we need multiple instances of the metrics struct (one per metered stream), in which case we'd need to describe them separately (i think?)

**Comment by mattsse** [comment]
what we want here are custom Channel types that have the same API as `tokio::sync::mpsc::Sender`, but increase some metrics value on send success/error

something like:

```rust
struct MeteredSender {
  metrics,
  sender: tokio::sync::mpsc::Sender
}
```

**Comment by akirillo** [comment]
Gotchaa, let me take a stab at this

**Comment by akirillo** [comment]
Seems like this has little to no reliance on #707, if we just care about messages sent / dropped. Or do we want to monitor bandwidth in terms of # of bytes as well?
