### ISSUE TITLE
RPC - Implement account related handlers

### ISSUE THREAD

**Issue by MegaRedHand** [paradigmxyz/reth#1419]
### Describe the feature

```[tasklist]
## Endpoints related to accounts
- [X] eth_accounts (already implemented)
- [x] eth_getBalance
- [x] eth_getStorageAt
- [x] eth_getTransactionCount
- [X] eth_getCode (already implemented)
- [ ] eth_getProof
```

### Additional context

Related tracking issue: https://github.com/paradigmxyz/reth/issues/1225

I can start work on these

**Comment by mattsse** [comment]
closing, since accomplished.
following up with eth_getproof separately

**Comment by MegaRedHand** [comment]
Opened another issue for `eth_getProof`: https://github.com/paradigmxyz/reth/issues/1507
