### ISSUE TITLE
 RPC - Implement block related handlers 

### ISSUE THREAD

**Issue by fkrause98** [paradigmxyz/reth#1423]
### Describe the feature

List of endpoints related to blocks:

```[tasklist]
- [x] eth_getBlockByHash
- [x] eth_getBlockByNumber
- [x] eth_getBlockTransactionCountByHash
- [x] eth_getBlockTransactionCountByNumber
```

### Additional context

Related tracking issue: https://github.com/paradigmxyz/reth/issues/1225

I can start working on these endpoints

**Comment by mattsse** [comment]
awesome, tysm for taking this on!

**Comment by gakonst** [comment]
@fkrause98 do you guys have a draft by any chance? `eth_getBlockByNumber` seems to be everywhere in Hive and would love if we could have a quick PR that impls it

**Comment by gakonst** [comment]
Bump @fkrause98 if you can push the current progress, we'd like to get unblocked on this ASAP and ideally have @mattsse take over as it's a blocker

**Comment by fkrause98** [comment]
Sorry, just saw this. I see that block_by_hash and block_by_number were implemented on the linked PR, I can continue with the [TODO here](https://github.com/paradigmxyz/reth/blob/cc5e5cab3c425ca5a911893a055619f06e854812/crates/rpc/rpc/src/eth/api/block.rs#L20) and the other 3 endpoints if that's ok.

**Comment by mattsse** [comment]
this has been completed

**Comment by gakonst** [comment]
@fkrause98 yep go for that TODO :+1:
