### ISSUE TITLE
`SealedHeader::from<Block>` drops several important fields which invalidate RLP encoding

### ISSUE THREAD

**Issue by TomAFrench** [paradigmxyz/reth#1442]
### Describe the bug

I was looking to use the `reth-primitives` crate in a project which requires me to get the RLP encoded block header as of a certain block. This RLP encoded header is then passed elsewhere and hashed however I ran into the issue of none of the hashes matching.

The root of the issue seems to be that `SealedHeader::from<Block>` drops a number of fields from `Block` which go into the RLP encoded form (e.g. tx root, parent hash, etc.) despite those fields existing on `Header`.
 https://github.com/paradigmxyz/reth/blob/5c2f96ed659222e58b93bf2934f355c5fcacabce/crates/primitives/src/header.rs#L311-L331
 
 Are these dropped for performance reasons? Ideally we'd copy across all the fields included in the block's header (happy to make a PR), but at least we should document that this conversion is lossy.

### Steps to reproduce

```
// Set up a provider

let blk: Block = anvil_provider
    .get_block(BlockNumber::Number(8509764u64.into()))
    .await
    .unwrap()
    .unwrap();

let blk_header = SealedHeader::from(blk);

let mut block_header_rlp = Vec::new();
blk_header.encode(&mut block_header_rlp);

assert_eq!(blk_header.hash(), BlockHash::from(keccak256(block_header_rlp)))
```

### Node logs

```text
N/A
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

5c2f96e

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
hi!
> Are these dropped for performance reasons? Ideally we'd copy across all the fields included in the block's header (happy to make a PR), but at least we should document that this conversion is lossy.

nope, most likely just an oversight! Feel free to PR with any fields that exist on `reth_primitives::Header`

**Comment by TomAFrench** [comment]
Cool, yeah I was really unsure why that would be done as it's only a few small fields. Will let @mattsse take over as he's already gotten started on it (thanks!).
