### ISSUE TITLE
`reth db list SyncStage` keys should be strings

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#1456]
### Describe the feature

Currently, we type [`StageId = Vec<u8>`](https://github.com/paradigmxyz/reth/blob/main/crates/storage/db/src/tables/mod.rs#L308)

This has the unfortunate effect that the keys when doing [`reth db list SyncStage`](https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/db/mod.rs#L153-L154) are printed as vec u8 array, which is not helpful. 

![image](https://user-images.githubusercontent.com/17802178/219990070-b9b272ed-71a8-44dd-81e4-bda9f403277c.png)

Solutions:
1. Explore converting StageId to String
2. Explore converting `T::Key` to a nicely displayed value on the list method

**Comment by GrapeBaBa** [comment]
I can take this one.
