### ISSUE TITLE
Refactor Error types in Stages

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1458]
### Describe the feature

There are multiple wrappers of standard errors in stages
  `PipelineError`, ` StageError` and `TransactionError` (Now in provider) we should probably reuse one error type already in interface `Error` or stages error if needed can be moved there. This would unify all errors.

**Comment by onbjerg** [comment]
Each of these have different variants with different meanings though, e.g. pipeline specific errors. If we made them all the same error type we would have to match on every variant for errors that can never be thrown in some parts of the code, no?

**Comment by rakita** [comment]
There is a lot of overlap, now you have DbError that is included in all of those errors as example.

We can reuse main `Error` from here: 
https://github.com/paradigmxyz/reth/blob/cc5e5cab3c425ca5a911893a055619f06e854812/crates/interfaces/src/error.rs#L5-L22

And add additional errors that pipeline needs.

**Comment by onbjerg** [comment]
That doesn't solve the problem, this would mean that you would have to handle `Error::Network` when using `reth-stages` even though you might never be able to hit that error leading to dead code

**Comment by rakita** [comment]
> That doesn't solve the problem, this would mean that you would have to handle `Error::Network` when using `reth-stages` even though you might never be able to hit that error leading to dead code

It does solve the problem of bubbling up the errors, and we probably don't want to handle error by error as it can be brittle but a group of them. The problem comes if you now wrap again the `PipelineError` to something else and then again to `RPCError` or whatever is returned back to the user.

**Comment by onbjerg** [comment]
Closing this, let me know if there are still changes we should make here.
