### ISSUE TITLE
fix all clippy warnings

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1462]
### Describe the feature

there are clippy warnings:

```
cargo +nightly clippy --all --all-features
```

## TODO

fix all obvious clippy warnings

**Comment by onbjerg** [comment]
I don't see any clippy warnings, was this addressed?

**Comment by mattsse** [comment]
oh my bad they're not warning but suggestions:

```
cargo +nightly clippy --fix --all-features -Z unstable-options
```

**Comment by tomarST** [comment]
I can try this one

**Comment by tomarST** [comment]
> oh my bad they're not warning but suggestions:
> 
> ```
> cargo +nightly clippy --fix --all-features -Z unstable-options
> ```

I just tried doing this but not getting any suggestions, not sure if I am doing it right. Do you have any suggestions?

**Comment by mattsse** [comment]
ah sorry, forgot to add the `--all` argument as well...

it should be

```
cargo +nightly clippy --fix --all --all-features -Z unstable-options
```
