### ISSUE TITLE
TD is appended even after paris

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1470]
### Describe the feature

After Paris hardfork Total difficulty is not used and it is always zero

Should move insertion to else? https://github.com/paradigmxyz/reth/blob/main/crates/stages/src/stages/total_difficulty.rs#L100

**Comment by onbjerg** [comment]
Total difficulty is used in the RPC. See https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getblockbyhash

**Comment by rakita** [comment]
> Total difficulty is used in the RPC. See https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getblockbyhash

If this is the only place, we can check if block number is >Paris block and return zero. In general, a small thing

**Comment by gakonst** [comment]
> If this is the only place, we can check if block number is >Paris block and return zero. In general, a small thing

Yes. Let's move the `append` to an `else` block, and let's also ensure that any RPC response has `#[serde(default)]` / is initialized with difficulty 0

**Comment by onbjerg** [comment]
Is this still relevant? cc @rakita
