### ISSUE TITLE
Support soft limit in NewPooledTransactions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1484]
### Describe the feature

The soft limit for NewPooledTransactionhashes is 4096
https://github.com/ethereum/devp2p/blob/master/caps/eth.md#newpooledtransactionhashes-0x08

this is mostly an issue for the first newpooledHashes message:

https://github.com/paradigmxyz/reth/blob/3c41807f0f7e92df1ebd5f5ebc2ffa4d542185dc/crates/net/network/src/transactions.rs#L341-L342

which fetches _all_ hashes from the pool

## TODO
* enforce soft limit for NewPooledTransactions

blocked by #1483 #1482

### Additional context

https://github.com/paradigmxyz/reth/pull/1483

**Comment by Tirthnp** [comment]
I would like attempt doing this

**Comment by mattsse** [comment]
hey @Tirthnp great!

I realized, this is very closely related to #1485 and #1485 should happen before this one, can I assign #1485 to you?

**Comment by Tirthnp** [comment]
> hey @Tirthnp great!
> 
> I realized, this is very closely related to #1485 and #1485 should happen before this one, can I assign #1485 to you?

I just saw that it is already assigned but thank you for asking :)

**Comment by mattsse** [comment]
once this lands we can enforce this by limiting this to 4096 for eth66, for eth68 I think we can stick with 4096 as well for now, 128kb+overhead is still small enough.
but for eth68 we need #1485 to make this more performant.
we could get the length already by encoding the tx but this is pretty wasteful.

**Comment by Tirthnp** [comment]
> once this lands we can enforce this by limiting this to 4096 for eth66, for eth68 I think we can stick with 4096 as well for now, 128kb+overhead is still small enough but please take a look at how geth behaves here.
> 
> but for eth68 we need #1485 to make this more performant. we could get the length already by encoding the tx but this is pretty wasteful.

I was looking at https://github.com/ethereum/go-ethereum/blob/ee530c0d5aa70d2c00ab5691a89ab431b73f8165/eth/fetcher/tx_fetcher.go#L379, seems like we want to do something like this?
