### ISSUE TITLE
Extend PoolTransaction trait with tx_type and length

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1485]
### Describe the feature

with eth68 newPooledTransaction Hashes (#1482) we also need to send the type and encoded length of the transaction.

This can already be obtained by converting `PoolTransaction -> TransactionSigned` and then get the length by encoding the transaction.
however, this is pretty wasteful because we need to reencode the transaction everytime it is requested or announced.

## TODO
* extend PoolTransaction trait with two more functions:
    *  `fn tx_type() -> u8` returns the type of the transaction
    *  `fn encoded_length() -> usize` returns the length of the rlp encoded object. This is then cached in the `ValidPoolTransaction` type as a field.

**Comment by chirag-bgh** [comment]
I would like to take this.

**Comment by mattsse** [comment]
unblocked now
