### ISSUE TITLE
`eth_getBlockByNumber` header num has leading zeros

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1486]
### Describe the bug

The `ethereum/sync` test fails because our rpc output is not able to be parsed:
```
can't query chain head: json: cannot unmarshal hex number with leading zero digits into Go struct field Header.number of type *hexutil.Big
```

### Steps to reproduce

Run the `ethereum/sync` hive tests on latest main, see the hive workflow: https://github.com/paradigmxyz/reth/actions/runs/4234007156/jobs/7356032570#step:7:8

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
This is caused by:
https://github.com/recmo/uint/issues/224
and tracked in reth with:
https://github.com/paradigmxyz/reth/issues/1465

**Comment by gakonst** [comment]
Remco is away on parental leave for another month I think, so would recommend using a custom deserializer.

**Comment by mattsse** [comment]
we'd need to use different types everywhere which would be a pain
perhaps we can patch with this fix instead https://github.com/recmo/uint/pull/225?

**Comment by gakonst** [comment]
I'm down to just patch dep `ruint` until then yeah.
