### ISSUE TITLE
incorrect hashes in genesis smoke test 

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1489]
### Describe the bug

The `smoke/genesis` hive tests currently only pass 3/6 genesis hash tests:
https://github.com/paradigmxyz/reth/actions/runs/4236576075/jobs/7361666233#step:6:37

This is usually due to one of two main things:
 - incorrectly parsing the genesis
 - incorrectly encoding the genesis header before hashing

### Steps to reproduce

Run the `smoke/genesis` hive test suite on latest main

### Simulator logs

```text
genesis hash 0x433d0b859a77a29753d2a6df477c971dcc6300af33f9d64d821a1d490b4148b1
genesis hash 0x433d0b859a77a29753d2a6df477c971dcc6300af33f9d64d821a1d490b4148b1
genesis hash 0xde42b08524283455b79fa69cb2f91041124c7182ec2815c127844e498e30e8e6
wrong genesis hash, want 0x5ae31c6522bd5856129f66be3d582b842e4e9faaa87f21cce547128339a9db3c
genesis hash 0x40e5c5994b9da4eb3ecb11859a8889eba7ef149c9e8453e581315c575c7602f0
wrong genesis hash, want 0x1b5dc4bd86f9209e6261d43dd3085034d3a502c3823903a417a95320caccaebf
genesis hash 0xf6df6eb772235f4f193b1a514f34bc5e4e9ce747a83732d4e8fced78ba2e939c
genesis hash 0x8ada0c5bc4f1aca7b9af9137d43c3f76cbe451ba31c244a0fa3ae287d6d7124a
wrong genesis hash, want 0x251e6c3c84531a8b59a62535db474d0b5967f6f4ec82e47d62e70497ccdde6a7
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by fkrause98** [comment]
I'd like to work on this.

Any tips on how to approach this? 😄

**Comment by Rjected** [comment]
@fkrause98 Cool! just assigned you, here are some things to start:

To figure out whether or not we are properly parsing the genesis file, I'd check out the simulator logs, which show the `genesis.json` being passed to reth:
https://github.com/paradigmxyz/reth/actions/runs/4236576075/jobs/7361666233#step:8:18

Then, it would be useful to create tests that mirror hive, which would use `serde_json` to deserialize the json into `AllGenesisFormats`, which can be converted into a `ChainSpec`:
https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/chain/spec.rs#L303

If we properly parse each field, this would just involve calculating the genesis hash from a `ChainSpec`, and figuring out how we are incorrectly calculating the hash. Let me know if you have any questions or are stuck one something!

**Comment by fkrause98** [comment]
@Rjected 
I've checked the parsing of the genesis file and it seems to be working fine, you've also mentioned to check out the
"incorrectly encoding the genesis header before hashing". What files/modules are in charge of doing so? I've checked out 
the encode function on genesis.rs on the primitives crate and [changed the closure on line 85](https://github.com/paradigmxyz/reth/blob/df6e3143c3bf3b7d46a185ff6fa950b69f429c08/crates/primitives/src/genesis.rs#L85) to:
```
            .map_or(EMPTY_ROOT, |storage| {
                let storage_values =
                    storage.iter().filter(|(_k, &v)| v != H256::zero()).map(|(&k, v)| {
                        let v256 = reth_rlp::encode_fixed_size(&(U256::from_be_bytes(*v.as_fixed_bytes())));
                        (k, v256)
                    });

                sec_trie_root::<KeccakHasher, _, _, _>(storage_values)
            })
```
As I think that is how It's supposed to be encoded.

But still, the tests fail.

Any ideas? 😄

**Comment by Rjected** [comment]
@fkrause98 I'm not sure! mind making a draft PR including an example of parsing a failing genesis? It would be really useful, so we can help and debug

**Comment by fkrause98** [comment]
@Rjected 
Sure!
I've added a test here https://github.com/paradigmxyz/reth/pull/1530.

Please tell me if this isn't what you mean with "an example of parsing"!
