### ISSUE TITLE
Store receipts

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1523]
### Describe the feature

How do we want to approach this? We can:
* Save the whole receipt.
* Save logs, used gas, is_success of receipt (Omit bloom). As they are used in range block searches.
* Dont save anything.

All receipts can be regenerated on the fly when needed but this is a slower operation. The reason, why we don't store them whole, is that they take up a lot of space.

**Comment by gakonst** [comment]
Curious if @mattsse has thoughts on how we can make this more efficient, but @rakita I think let's start with the "dumb" way of storing everything. Unless you think there's low-hanging fruit stuff to avoid storing everything?

**Comment by rakita** [comment]
Had some time to think about this, and the second way is best. Will close this issue as a duplicate of https://github.com/paradigmxyz/reth/issues/1724
