### ISSUE TITLE
Add async caching service to Eth RPC api

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1532]
### Describe the feature

it will be the case that the same state (block, evm env) is requested concurrently.
to reduce disk lookups we can add a caching layer on top of the provider:

this will look like the `BackendHandler` used in foundry
https://github.com/foundry-rs/foundry/blob/d09be021460fe2b28fc9a6e338f3db42894d7e21/evm/src/executor/fork/backend.rs#L82

requests send messages to an independent Task that bundles lookups for the same data and an LRU cache for fetched data.

eg:
1. send `GetBlock(oneshot::Sender<Block>)` message to task
2. check LRU cache
3. if not present check waiting area
    * if lookup in progress: add to Vec<Sender>
    * else spawn another lookup task that then sends the result to the task
4. task receives lookup result: respond to all senders in waiting area

This has the benefit that we don't need an `RwLock` around a cache and can be async instead (ideal for RPC) 

### Additional context

ref https://github.com/paradigmxyz/reth/pull/1511#discussion_r1115481605

**Comment by gakonst** [comment]
Fire. Yeah and we should be deduping things eg if somebody spams us with the same eth_call that might take a long time to execute we should only run it once even if two requests arrived simultaneously
