### ISSUE TITLE
Can't find primitives::SHANGHAI when building

### ISSUE THREAD

**Issue by odyslam** [paradigmxyz/reth#1544]
### Describe the bug

<img width="980" alt="image" src="https://user-images.githubusercontent.com/13405632/221190772-4b915544-c518-4062-b01a-3696bc6ce777.png">

It may belong to the REVM repo. 🤔

### Steps to reproduce

- Use reth as a dependency on a rust project; track main
- run `cargo check`

### Platform(s)

Mac (Apple Silicon)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by rkrasiuk** [comment]
@odyslam do you have a separate revm dependency?

**Comment by odyslam** [comment]
@rkrasiuk negative

**Comment by rkrasiuk** [comment]
@odyslam no, this is us. we patched revm to master here
https://github.com/paradigmxyz/reth/blob/dc57fbad0751eb025840f1d0882facf0e7b11ef8/Cargo.toml#L45-L46

**Comment by onbjerg** [comment]
`Cargo.lock` pins `revm` to 8e6f4f26173a245d9c3c19fd2317cd8bfd1c56a9 which definitely has the constant available.

**Comment by odyslam** [comment]
In my `Cargo.lock:

```toml
[[package]]
name = "revm"
version = "3.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "284747ad0324ed0e805dcf8f412e2beccb7a547fbd84f0607865001b8719c515"
dependencies = [
 "auto_impl 1.0.1",
 "revm-interpreter",
 "revm-precompile",
]
```

**Comment by rkrasiuk** [comment]
@onbjerg i'm not sure Cargo.lock is respected

**Comment by odyslam** [comment]
So what's the best way forward @rkrasiuk ? 

- Use a rev of reth before this issue was introduced. Might be acceptable depending on when the features I am using where introduced (mainly infra like the CLI and task manager)

**Comment by rkrasiuk** [comment]
@odyslam just copy the patch lines over to your Cargo.toml, that should work
