### ISSUE TITLE
Implemented `is syncing` subscription handler 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1556]
## TODO

implement

https://github.com/paradigmxyz/reth/blob/305e992eedef97f7c4ca5927c68571f593d2b4a2/crates/rpc/rpc/src/eth/pubsub.rs#L107-L108

use `ChainEventSubscriptions` block subscription and check the `Network::is_syncing`

this should be implemented as new spawned task
1. get new block subscription
2. send 1 response if `Network::is_syncing`: `PubSubSyncStatus::Detailed` else `PubSubSyncStatus::Simple(false)`
3. await on all new blocks (while let Some()) and check `Network::is_syncing` if `is_syncing` changed send another response

**Comment by chirag-bgh** [comment]
I would like to take this. 

@mattsse how to fetch  SyncStatusMetadata which is needed for ```PubSubSyncStatus::Detailed```

**Comment by mattsse** [comment]
starting_block should be 0
current_block is via `chain_info().best` and we can leave highest_block None. or perhaps it would be the latest header, in the headers table, but we can leave it None
