### ISSUE TITLE
401 Unauthorized in hive engine test suite

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1578]
Currently all `ethereum/engine` tests fail with the following message:
```
401 Unauthorized: The provided signature is invalid
```

This can be seen for example in the following run:
https://github.com/paradigmxyz/reth/actions/runs/4272628614/jobs/7438032242#step:7:297

This occurs when the hive engine API client sends requests to reth.

## To reproduce

Run hive tests using [these instructions](https://github.com/paradigmxyz/reth/issues/851) to run hive tests locally

**Comment by mattsse** [comment]
the engine api requires jwt.
how's the setup for engine api access in hive?

**Comment by Rjected** [comment]
Ah, the JWT section of the reth client script was commented in hive 😅

fixed with https://github.com/paradigmxyz/hive/pull/6, will track other engine errors now
