### ISSUE TITLE
Cannot sync without passing `--debug.tip`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1580]
Currently we cannot sync without passing `--debug.tip`, which is typically obtained from the consensus layer. However, there is no consensus layer present in hive tests, so we need to be able to sync without a set end block number or tip.

**Comment by onbjerg** [comment]
What tests specifically? Some of the tests use clique, and some of them definitely have CL clients running (or mocks) that post fork choice updates

**Comment by Rjected** [comment]
> What tests specifically? Some of the tests use clique, and some of them definitely have CL clients running (or mocks) that post fork choice updates

Sorry should have specified, _just_ the `ethereum/sync` simulator, which does not run a mock CL or use clique, and does two main things:
 - Import a `chain.rlp` on one client
 - Spin up a second client, peering with the first client, and wait for the second client to finish syncing. The simulator does this by checking the latest block of the second client over RPC.

**Comment by onbjerg** [comment]
How are we supposed to sync w no CL at all? Is it PoW?

**Comment by Rjected** [comment]
> How are we supposed to sync w no CL at all? Is it PoW?

Yes, the `chain.rlp` is a PoW chain, and geth passes this simulator because it supports the legacy PoW sync strategy without a tip

**Comment by Rjected** [comment]
> I wonder if we should just not do that one then, since it would require implementing PoW and possibly a lot of changes to both of the downloaders, since we need to probably keep multiple competing chains in-memory and pick the heaviest one. I imagine the ethereum/sync simulator also checks for these scenarios, so we would fail those too.

Hmmm, well the test only checks that the head hash post-sync is correct. For example, passing `--debug.tip` with the tip from the `chain.rlp` file causes the test suite to pass with reth. But I agree, we should not implement PoW sync. I wonder if it's possible to pass the tip in a way that isn't too hacky.

**Comment by onbjerg** [comment]
That's odd, if that is the case then we have a bug. The latest synced block is defined by the `Finish` stage, and that block number *should* be loaded when the node is booted and set as status messages etc. and used by the RPC. I guess the RPC doesn't account for this?

**Comment by onbjerg** [comment]
Ah, never mind -- I thought you had run `reth import` and then started the node, after which it reported an incorrect head unless you passed `--debug.tip`. I did not catch on to the fact that you are talking about two separate reth instances (one that has done `reth import` and one that does `--debug.tip`)
