### ISSUE TITLE
devp2p `TestTransaction` hive test fails

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1581]
### Describe the bug

Currently the `devp2p/eth` hive test `TestTransaction` fails with the following logs:
```
not ok 13 TestTransaction
# Testing tx propagation 0: sending tx 0x35ac5799d8bd35fcfcd474015abca116d808d6da7f4afc6a5f613791199e6fba 1000000 21000
# send successful tx test failed: unexpected message in sendSuccessfulTx: (*ethtest.Error)(could not read from connection: read tcp 172.17.0.3:41294->172.17.0.4:30303: i/o timeout)
# 
```

This test is implemented in geth here:
https://github.com/ethereum/go-ethereum/blob/c155c8e179519888fce575b276091923af19ffbe/cmd/devp2p/internal/ethtest/suite.go#L438

We are probably disconnecting from the hive peer

### Steps to reproduce

Run the hive tests using the instructions in #851, running the `devp2p/eth` suite.

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this could be because we're not actually running the real txpool atm,

will enable once #1498 merged

**Comment by gakonst** [comment]
#1498 is in
