### ISSUE TITLE
devp2p `TestLargeTxRequest` hive test fails

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1582]
### Describe the bug

Currently the `devp2p/eth` hive test `TestLargeTxRequest` fails with the following logs:
```
not ok 15 TestLargeTxRequest
# failed to send next block: failed to announce block: unexpected: (*ethtest.Error)(could not read from connection: read tcp 172.17.0.3:43840->172.17.0.4:30303: i/o timeout)
# 
```

The `TestLargeTxRequest` is implemented here:
https://github.com/ethereum/go-ethereum/blob/c155c8e179519888fce575b276091923af19ffbe/cmd/devp2p/internal/ethtest/suite.go#L454

This is ultimately due to the fact that we disconnect peers that send us block announcements, and do not process block announcements. However, that is not related to what is being tested.

### Steps to reproduce

Run the hive tests using the instructions in #851, running the `devp2p/eth` simulator.

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> failed to send next block: failed to announce block

this is again due to unsupported block announcements.
tbh unsure how to proceed here because I don't think we'll actually need block announcements anymore.

**Comment by Rjected** [comment]
>  tbh unsure how to proceed here because I don't think we'll actually need block announcements anymore.

Yeah, I'm also not sure. One thing we could do is disable the test, and use our own integration tests to test this behavior.

If we really want to use hive to test this behavior, maybe we could change the test? These changes would need to be upstreamed, but it would be changing these lines:
https://github.com/ethereum/go-ethereum/blob/c155c8e179519888fce575b276091923af19ffbe/cmd/devp2p/internal/ethtest/suite.go#L455-L459

To something else, maybe a RPC call to `eth_syncing`?

WDYT?

**Comment by mattsse** [comment]
I think we can skip this test, adding block propagation just for this is not worth it, at least now.

we should port the other test logic for the actual large tx test to a rust nativ test though

**Comment by Rjected** [comment]
removed this test - creating an issue for the rust native test though
