### ISSUE TITLE
Cannot parse JWT claim with no `exp` field

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1587]
### Describe the bug

The `ethereum/engine` hive tests fail with the following logs:
```
Start test (reth): Invalid Terminal Block in ForkchoiceUpdated
Randomness seed: 1677602552
>> (96ae7a20) {"jsonrpc":"2.0","id":1,"method":"engine_forkchoiceUpdatedV1","params":[{"headBlockHash":"0x67ead97eb79b47a1638659942384143f36ed44275d4182799875ab5a87324055","safeBlockHash":"0x67ead97eb79b47a1638659942384143f36ed44275d4182799875ab5a87324055","finalizedBlockHash":"0x67ead97eb79b47a1638659942384143f36ed44275d4182799875ab5a87324055"},null]}
<< (96ae7a20) JWT decoding error Error(Json(Error("missing field `exp`", line: 1, column: 18)))
DEBUG (Invalid Terminal Block in ForkchoiceUpdated): Failed `Expect*` routine called from: file=/source/suites/engine/tests.go, line=1213
FAIL (Invalid Terminal Block in ForkchoiceUpdated): Unexpected error on EngineForkchoiceUpdatedV1: 401 Unauthorized: JWT decoding error Error(Json(Error("missing field `exp`", line: 1, column: 18))), expected=<None>
End test (reth): Invalid Terminal Block in ForkchoiceUpdated
```

So it looks like the claim is missing the `exp` field, so it fails to deserialize. From the engine authentication spec:
> ## JWT Claims
>
> This specification utilizes the following list of JWT claims:
>
> - Required: `iat` (issued-at) claim. The execution layer client **SHOULD** only accept `iat` timestamps which are within +-60 seconds from the current time.
> - Optional: `id` claim. The consensus layer client **MAY** use this to communicate a unique identifier for the individual consensus layer client.
> - Optional: `clv` claim. The consensus layer client **MAY** use this to communicate the consensus layer client type/version.
> 
> Other claims **MAY** be included in the JWT payload. If the execution layer client sees claims it does not recognize, these **MUST** be ignored.

So the `exp` field should probably be optional:
https://github.com/paradigmxyz/reth/blob/dc2f6047db71ef77eb4b599199f3a0bf7595f22e/crates/rpc/rpc/src/layers/jwt_secret.rs#L166

### Steps to reproduce

Run hive tests for `ethereum/engine` using instructions from #851 to test locally

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
the exp field isn't acutally used it is kinda redundant because iat enforces this via the 60s window?

so should make opional
