### ISSUE TITLE
Bytecode cleanup on revert, add bytecode table counter

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1588]
### Describe the feature

Currently, bytecode table is just `bytecode_hash -> bytecode` while there is possibility that there would be multiple accounts that point to same bytecode we should introduce counter to handle that. Bytecode are not cleaned in reorg or in unwind of blocks.

Additionally on Execution unwind counter needs to be decremented and on execution execute it needs to be incremented or initialized to one.

Creating of the bytecode is always done in `AccountInfoChangeSet::Create` enum.

**Comment by MegaRedHand** [comment]
I can work on this!

**Comment by gakonst** [comment]
Yeah - go for it @MegaRedHand !

**Comment by MegaRedHand** [comment]
Sorry! I can't take it now 😞. Although I'll leave here some info I have from when I looked into it.

Recently [a PR](https://github.com/paradigmxyz/reth/pull/1640) added a `Bytecode` struct in `crates/primitives/src/account.rs`. We could add a reference counter to this struct, and update it on each modification to the `Bytecodes` table.

**Comment by gakonst** [comment]
cc @joshieDo re: state clear EIP, in case related. @rakita is this related to Erigon's incarnations table by any chance?

**Comment by supernovahs** [comment]
I can look into this if it's available.

**Comment by emnul** [comment]
Hey team is this issue still relevant? cc @mattsse @emhane 

If so, I'd like to take a crack at it.

**Comment by mattsse** [comment]
the entire bytecode table is just 12GB so imo we can live with this and not cleanup reorged bytecodes
