### ISSUE TITLE
perf: pin ForkCondition::TTD block+value in chainspec

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1600]
### Describe the feature

we need TTD when populating rpc response data (e.g. Block)
ideally, we have a function in `ChainSpec` that pins the (`ForkCondition::TTD`) so it can be accessed easily and  then the `header_td(BlockNumber)` impl of `ShareableDatabase` can check if the BlockNumber is past TTD which saves a lookup.

wdyt @onbjerg 

### Additional context

https://github.com/paradigmxyz/reth/blob/14811dae4063f32264acd67c6e21fe5fc486955d/crates/primitives/src/chain/spec.rs#L183-L191

**Comment by onbjerg** [comment]
I'm not entirely sure what the idea is here, can you not just clone the return value of `chain_spec.fork(Hardfork::London)`?

https://github.com/paradigmxyz/reth/blob/14811dae4063f32264acd67c6e21fe5fc486955d/crates/primitives/src/chain/spec.rs#L174-L176

This would give you either `Hardfork::TTD` or `Hardfork::Never` - remember, it is not always the case that TTD is a thing on the network

**Comment by mattsse** [comment]
> can you not just clone the return value of chain_spec.fork(Hardfork::London)?

I guess the additional lookup is negligible

**Comment by mattsse** [comment]
decided against this, not worth it, for rpc, all this is is already cached via the cache service
