### ISSUE TITLE
Port geth tracing types from ethers to reth

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1617]
### Describe the feature

copy geth types from

https://github.com/gakonst/ethers-rs/tree/master/ethers-core/src/types/trace/geth

to 

https://github.com/paradigmxyz/reth/tree/main/crates/rpc/rpc-types/src/eth/trace

Note: this should be considered a temp fix, I believe the best solution long term is to introduce a new crate  in ethers that only provides types and a compat feature for primitive types and ruint

**Comment by truedem0n** [comment]
I'd like to try this one.

**Comment by mattsse** [comment]
completed
