### ISSUE TITLE
Removal of TxTransitionId table

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1641]
### Describe the feature

@onbjerg already noticed that having a full Table of `Tx->TransitionId` seems like a waste as transaction and transition ids are mostly "same" as in incremental.

I am writing this so as to not forget it.

Current tables:
```
Transitions: TransitionId -> Changeset
BlockTransitionId: BlockNumber -> TransitionId
TxTransitionId: TxNumber -> TransitionId 
```

What we can do is use BlockBody to get to transition count and then tx Transition would be `BLockTransitionId+count`.

This would remove a needs or `TxTransitionId` table but would require `TransactionBlock` table that can be reused for other things.

Just idea for now, seems possible

**Comment by rakita** [comment]
very nicely works with: #1699

**Comment by onbjerg** [comment]
Closing this as I don't think it's relevant anymore? Let me know though cc @rakita
