### ISSUE TITLE
Old Merkle root stays in db

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1644]
While testing the insertion and unwinding of blocks in `Transaction` i notices that when inserting and then unwinding block old state root stays in database.

Account root: https://github.com/paradigmxyz/reth/blob/92a0ebbf04cb9a82d77061a4e875def4ee13a941/crates/storage/provider/src/trie/mod.rs#L297-L300
And storage root: 
https://github.com/paradigmxyz/reth/blob/92a0ebbf04cb9a82d77061a4e875def4ee13a941/crates/storage/provider/src/trie/mod.rs#L337-L340

Roots, if I am reading this correctly, are never removed and they should be?

**Comment by MegaRedHand** [comment]
🤔 Seems like a bug on `cita_trie`. Except for the root, they clean up every unused node in the DB. Fix LGTM. It shouldn't bring any surprises as this was the assumed behavior.
