### ISSUE TITLE
Implement eth_sign RPC calls

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1648]
### Describe the feature

ref #1225 

similar to anvil's signer impl:

https://github.com/foundry-rs/foundry/blob/master/anvil/src/eth/sign.rs

## TOD
* add sign trait
* impl signer endpoints

**Comment by mattsse** [comment]
yeh, for signtypeddata, we probably need to use some ethers types.

and for `eth_signTransaction` I'd appreciate a separate PR that basically converts a CallRequest into a signed typed tx.

**Comment by fkrause98** [comment]
Ok, so if I understood correctly, ideally this issue would be split in
2 prs? 🙂 
- 1 PR for eth_sign + eth_signedTypedData
- 1 PR for eth_signTransaction, which turns a CallRequest into a Signed Typed Tx?

**Comment by fkrause98** [comment]
I've Opened a draft to check if I'm on the right track on implementing this and to get some feedback :slightly_smiling_face:

**Comment by mattsse** [comment]
closed via #1665
