### ISSUE TITLE
Enforce transaction soft limit / message limit when propagating transactions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1659]
### Describe the feature

when new transactions are added to the pool they are propagated to connected peers.

atm we're not enforcing 
* soft limit (4096) for hashes
* messages limit for full tx objects

TODO:
- [x] enforce soft limit for hashes
- [ ] enforce payload len for tx: this is a bit tricky because we'd need to encode everything first which is expensive, perhaps we can instead use the num bytes of the data field to keep track of max message size instead. And send multiple messages instead.

https://github.com/paradigmxyz/reth/blob/e06d0a4a0bffcd1faddb600da1a99ae8e0e492ca/crates/net/network/src/transactions.rs#L243-L256

**Comment by tomarST** [comment]
I would like to attempt this one!

**Comment by mattsse** [comment]
sg, please have a look at #1660 first

I think we should solve this by splitting the message into several messages if it exceeds size limit.

also worth having a look at how geth handles this
