### ISSUE TITLE
Move Access to precompile addresses to EvmProvider trait

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1668]
### Describe the feature

In https://github.com/paradigmxyz/reth/pull/1652 this was added:

https://github.com/paradigmxyz/reth/blob/77d108660e78660d32aa3a35fc664fd5fbfdf985/crates/rpc/rpc/src/eth/api/call.rs#L333

since precompile addresses are chain specific, we should put this to the EvmProvider trait and add a way to configure this. 
default impl should be the existing code, which can be simplified with: https://github.com/bluealloy/revm/pull/408

cc @MegaRedHand

**Comment by MegaRedHand** [comment]
I'm gonna leave this one for the taking. Thanks for your patience! 😄

**Comment by Tirthnp** [comment]
I can try doing this one

**Comment by mattsse** [comment]
no longer needed since refactored revm-reth crate
