### ISSUE TITLE
Improve revm::Halt::OutOfGas error handling

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1669]
### Describe the feature

currently we only have:

https://github.com/paradigmxyz/reth/blob/77d108660e78660d32aa3a35fc664fd5fbfdf985/crates/rpc/rpc/src/eth/error.rs#L177-L179

which is used like:

https://github.com/paradigmxyz/reth/blob/77d108660e78660d32aa3a35fc664fd5fbfdf985/crates/rpc/rpc/src/eth/api/call.rs#L193

this is not ideal since OutOfGas error can be multiple things:

https://github.com/bluealloy/revm/blob/17207294839e8906cfa6483400794052463a878a/crates/primitives/src/result.rs#L154

## TODO

better conversion from revm::OutofGasError (likely more error variants in `InvalidTransactionError`)

check also geth errors for compact:

https://github.com/ethereum/go-ethereum/blob/ee530c0d5aa70d2c00ab5691a89ab431b73f8165/core/vm/errors.go#L26-L26

**Comment by GianfrancoBazzani** [comment]
I would like to contribute, can I take it?

**Comment by GianfrancoBazzani** [comment]
It is really necessary to handle revm's MemoryLimitOOG error? Do the reth's revm have memory expansion limits?

**Comment by GianfrancoBazzani** [comment]
I don't understand why InvalidOperand error is of type OOG in revm. Should be handled? And which error message I should write?
