### ISSUE TITLE
Extract rpc<->revm specific code from rpc

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1689]
### Describe the feature

atm some code in https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/api/call.rs

like:

https://github.com/paradigmxyz/reth/blob/d164a16be7481ebeeda70bad0069a84bb11163c3/crates/rpc/rpc/src/eth/api/call.rs#L391 

is useful on its own and should not be tied to the rpc impl.

it should be moved either to:
a) rpc-type with feature gated revm dep 
b) revm with featured gated rpc dep

I think, the former makes more sense.

The main motivation for this is, so that other consumers of the rpc-types can get access to the revm helpers as well (e.g. anvil eventually)

**Comment by chirag-bgh** [comment]
I can take this.

**Comment by chirag-bgh** [comment]
@mattsse  I think this is also blocked unless we move `InvalidTransaction` to interfaces?

**Comment by mattsse** [comment]
this will be possible after #1697

I'd appreciate if we could get #1562 over the line first

**Comment by chirag-bgh** [comment]
should we change the return type of `create_txn_env` to return only `TxEnv` instead of `EthResult`? 
Because if not then i think we need to move `EthApiError` as well to `rpc-types` which will lead to cyclic deps for `Internal(#[from] reth_interfaces::Error)`

**Comment by mattsse** [comment]
> should we change the return type of create_txn_env to return only TxEnv instead of EthResult?

we should add a new error instead with all the required variants, in rpc we can implement a conversion.

also relevant for this PR #1732 which is an intermediate step for this issue.

**Comment by gakonst** [comment]
Overall making it really easy to go from ethers-rs/reth-rpc style types into "execute this inside revm" would be super impactful for anyone building e.g. simulation services on top of reth

**Comment by mattsse** [comment]
closing ref https://github.com/paradigmxyz/reth/pull/1818#pullrequestreview-1348319663

rpc-types should be self contained
