### ISSUE TITLE
Remove duplicate Logs table

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1724]
### Describe the feature

we have a duplicate Logs/Receipts table:
https://github.com/paradigmxyz/reth/blob/1846f2d73c7793423f5987d36905e1b13100428f/crates/storage/db/src/tables/mod.rs#L158-L166

currenlty unused, should remove `Logs`

**Comment by rakita** [comment]
Receipt should be saved without Bloom filter as it can be regenerated on fly with logs, it will save some space and from ACD talk it is probable that blooms are going to be removed in Cancun (or when ssz gets introduced)
