### ISSUE TITLE
chore: Add method name to PRC handler implementation

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1728]
### Describe the change

RPC is split up in
* api: defines traits
* rpc: implements traits

It's usually hard to navigate from rpc to the traits because of proc-macros.

To make it easier to search in the file for a specific function we should add the exact method name to the impl, like:

```rust
    /// Handler for `trace_transaction`
    fn transaction_traces(&self, _hash: H256) -> Result<Option<Vec<LocalizedTransactionTrace>>> {
        Err(internal_rpc_err("unimplemented"))
    }
```

See also: https://github.com/paradigmxyz/reth/pull/1727

**Comment by chirag-bgh** [comment]
I will take this.
