### ISSUE TITLE
Make `DBTrieLoader` receive the current root on constructor

### ISSUE THREAD

**Issue by MegaRedHand** [paradigmxyz/reth#1743]
Make the `DBTrieLoader` receive the current root on instantiation in a similar way to the database wrappers we use inside the module (i.e. with `new(root)` and `empty()` methods).

_See: https://github.com/paradigmxyz/reth/pull/1515#discussion_r1132454953_

**Comment by onbjerg** [comment]
No longer relevant (`DBTrieLoader` doesn't exist)
