### ISSUE TITLE
Add tests for state clear EIP

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#1758]
### Describe the feature

In https://github.com/paradigmxyz/reth/pull/1747 @joshieDo identified a bug in our logic around accounts being cleared post eip161. It seems like we don't cover that part of the code with tests. We should add a test to ensure that this happens properly, to save us from future bugs e.g. if we do any refactors.

**Comment by GrapeBaBa** [comment]
I would like to try this one.

**Comment by gakonst** [comment]
sweet - assigned it to you! thanks!

**Comment by onbjerg** [comment]
We have a lot of tests around selfdestruct now in poststate, so I think we can close this
