### ISSUE TITLE
Improve blocking behavior for long running PRC calls

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1766]
### Describe the feature

some RPC handler impls require a mix of async code and sync evm exec code, which should be executed in context which is allowed to block (tokio::task::spawn_blocking).

## TODO

* extend `TaskSpawner` trait with a `TaskSpawner::spawn_blocking(BoxFuture)` function

**Comment by i-m-aditya** [comment]
I will take this.
