### ISSUE TITLE
Move rlp impl for Enr to discv4 crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1770]
### Describe the feature

currently we have the reth-rlp impls for `Enr` in rlp crate via feature.

This is only used by discv4, so we should move it there instead.
we need a new type `struct EnrWrapper(Enr)` for that.

## TODO

* move reth-rlp `Enr` impls to discv4 crate and use a new type wrapper (we need this because otherwise we can't impl the traits for an external type)

**Comment by his-dudenesss** [comment]
Can I have this one?

**Comment by mattsse** [comment]
of course!

**Comment by gakonst** [comment]
closed #1803 ! thank you
