### ISSUE TITLE
Implement large transaction integration test

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1778]
In #1582, it was discovered that the hive test `ethereum/devp2p eth/TestLargeTxRequest` relied on p2p block announcements, which we do not have plans on supporting. Instead, a separate rust integration test should be written which tests the same behavior.

Fundamentally, the test ensures the node can accept a p2p request for `2000` transactions after sending the full transactions to the node.

The test is implemented in geth here:
https://github.com/ethereum/go-ethereum/blob/master/cmd/devp2p/internal/ethtest/suite.go#L454

**Comment by jackthequack** [comment]
thinking of taking this on as a first issue.  Should the test be written in the reth/testing directory?

**Comment by mouseless-eth** [comment]
I can take this, almost done with the implementation

**Comment by supernovahs** [comment]
I can take this?

**Comment by mouseless-eth** [comment]
Running into an issue with verifying if all requested tx hashes have been served. The issue is due to the response transaction object having a difference txhash from that requested, more details in the pr.

**Comment by supernovahs** [comment]
Can I take this

**Comment by emhane** [comment]
@Rjected can this be closed?
