### ISSUE TITLE
`eth_getStorage` successfully parses index that is too long

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1784]
### Describe the bug

The `eth_getStorage/get-invalid-key-too-large` test in the `rpc-compat` test suite currently fails:

```
>>  {"jsonrpc":"2.0","id":12,"method":"eth_getStorageAt","params":["0xaa00000000000000000000000000000000000000","0x00000000000000000000000000000000000000000000000000000000000000000","latest"]}
<<  {"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000000","id":12}
response differs from expected:
 {
   "id": 12,
   "jsonrpc": "2.0",
-  "result": "0x0000000000000000000000000000000000000000000000000000000000000000"
+  "error": {
+    "code": -32000,
+    "message": "hex string of odd length"
+  }
 }
```

This is because we successfully parse `0x00000000000000000000000000000000000000000000000000000000000000000`, which is 67 characters long, or 65 characters excluding the `0x`. Instead, this should be disallowed in `U256` deserialization, and we should return the error `hex string of odd length` with code `-32000`.

### Steps to reproduce

Run the steps in #851, building the docker image from the branch `dan/hive-ci`.

The command to run the `eth_getStorageAt/get-invalid-key-too-large` test:
```
./hive --client reth --sim ethereum/rpc-compat --sim.limit "/eth_getStorage/get-storage-invalid-key-too-large"
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this is actually a `U256::deserialize` bug, right?

**Comment by Rjected** [comment]
> this is actually a U256::deserialize bug, right?

Yeah, will open an issue and track there

**Comment by Rjected** [comment]
fixed in https://github.com/paradigmxyz/uint/pull/3

**Comment by mattsse** [comment]
https://github.com/recmo/uint/issues/389
