### ISSUE TITLE
`eth_getStorageAt` returns incorrect error for an invalid index

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1785]
### Describe the bug

The `eth_getStorageAt/get-storage-invalid-key` test in the `rpc-compat` suite fails because we return the wrong error:

```
>>  {"jsonrpc":"2.0","id":11,"method":"eth_getStorageAt","params":["0xaa00000000000000000000000000000000000000","0xasdf","latest"]}
<<  {"jsonrpc":"2.0","error":{"code":-32602,"message":"invalid value: string \"asdf\", expected a 32 byte hex string at line 1 column 8"},"id":11}
response differs from expected:
 {
   "error": {
-    "code": -32602,
+    "code": -32000,
-    "message": "invalid value: string "asdf", expected a 32 byte hex string at line 1 column 8"
+    "message": "invalid hex string"
   },
   "id": 11,
   "jsonrpc": "2.0"
 }
```

Instead, of returning `"message": "invalid value: string "asdf", expected a 32 byte hex string at line 1 column 8"`, we should return `"message": "invalid hex string"`

### Steps to reproduce

Run the setup for hive mentioned in #851, making sure to build the docker image from the `dan/hive-ci` branch.

The command for running the `eth_getStorageAt/get-storage-invalid-key` test:
```
./hive --client reth --sim ethereum/rpc-compat --sim.limit "/eth_getStorage/get-storage-invalid-key"
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this is kinda cursed, because the server automatically answers with `-32602: INVALID_PARAMS` when it failed to deserialize

**Comment by onbjerg** [comment]
Assuming we fixed this?
