### ISSUE TITLE
TransitionId refactor

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1794]
### Describe the feature

Refactor how and where we save block and transaction transition.

The main problem is that most of the time we need a range of transitions but `BlockTransitionId` table saved only one value of it, because of that we are doomed to have `(parent_block_transition,present_block_transtion]` or `[parent_block_transition,present_block_transition)`(this is the present way) and is not intuitive to think about. 

By merging BlockBody, BlockTransationId and removing TxTransitionId, we are getting all needed information to create the range of transition that we need. And TxTransitionId would be replaced with a combo index of https://github.com/paradigmxyz/reth/issues/1641 and https://github.com/paradigmxyz/reth/issues/1699 

Removal of `TxTransitionId` is desirable as it saved database space and the same information can be extracted with one more additional database get.

Refactored `BlockBody` would look like this:
```
pub struct BlockBody {
   tx_num: TxNumber, //number of first transaction. Or first of next block if count is zero.
   transition_id: TransitionId, // number of first transition.As it is easier to have [transition_id..transition_id+tx_count). Or first of next block if count is zero (same behaviour as tx_num).

   tx_count: u16, //Transaction id. Can be used with both `tx_num`/`transition_id`.
   has_block_change: bool, // if it has block reward or withdrawal
}
```

This is not urgent to start, it is sensitive as we handle indices, and it will break the database layout in a few places.

**Comment by gakonst** [comment]
With this format, how would somebody query for a transaction with a certain transition id?

**Comment by rakita** [comment]
You have `TxNumber` and From `table::TransactionBlock` get `BlockNumber`.
with `BlockNumber` from `table::BlockBody` get `transition_id` and `tx_num`.

And calculate TxTransition as `block_body.transition_id+(TxNumber-block_body.tx_num)`

This is from transaction to transition, and this will be used mostly. But if needed it can be done in reverse with the same idea.
