### ISSUE TITLE
Save database in chain specific subfolder

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1820]
If someone is switching the network database data would be incorrect as old network data will not be separated.

By adding subfolders we can mitigate this.

The subfolder name should be a known network name or if not known, its chain_id (as this is network specific identifier).

**Comment by chrisdoc** [comment]
I tried a naive implementation here https://github.com/paradigmxyz/reth/pull/1846

**Comment by mattsse** [comment]
we have this now
