### ISSUE TITLE
`--db <path>` argument unintuitive in `db` subcommand

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1825]
### Describe the feature

`reth db --db ../mainnet stats`

is a bit weird, I'd expect that `reth db stats --db <path>` would work, but it doesn't

it's because of this:

https://github.com/paradigmxyz/reth/blob/d65cab9132e84e02e3e3bb7c5b04efce420ef663/bin/reth/src/db/mod.rs#L25-L36

I'd like to move the --db arg to the subcommands instead

wdyt @onbjerg

**Comment by onbjerg** [comment]
Just set `global` instead to avoid duplicating code.

https://docs.rs/clap/4.1.8/clap/builder/struct.Arg.html#method.global (outdated link because their docs broke on latest)
