### ISSUE TITLE
Introduce RPC for Block state witness generation

### ISSUE THREAD

**Issue by seunlanlege** [paradigmxyz/reth#1830]
### Describe the feature

This would be a custom RPC endpoint specific to reth alone, that allows users to generate the state witness of a block. This state witness can then be used in things like stateless clients, fraud provers for Optimistic L2s or trustless bridges.

**Comment by onbjerg** [comment]
Can you expand on this more? Preferably if there are existing discussions on this (e.g. in reference to later network upgrades) please include those as well.

**Comment by lead4good** [comment]
turbo-geth has a block witness implementation:
[Witness Builder](https://github.com/ledgerwatch/erigon/blob/devel/turbo/trie/witness_builder.go)
[Formal Spec](https://github.com/ledgerwatch/erigon/blob/devel/docs/programmers_guide/witness_formal_spec.md)
[Format](https://github.com/ledgerwatch/erigon/blob/devel/docs/programmers_guide/witness_format.md)

**Comment by flyq** [comment]
https://github.com/ethereum/go-ethereum/pull/30069
