### ISSUE TITLE
Add CallStepTrace to `VmTrace` and `StateDiff` conversion

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1862]
### Describe the feature

progress started: https://github.com/paradigmxyz/reth/pull/1861

need to conversions for parity's `VmTrace` and `StateDiff` objects in the `ParityTraceBuilder`

**Comment by PatStiles** [comment]
interested!

**Comment by mattsse** [comment]
great.

we need this:

https://github.com/paradigmxyz/reth/blob/72f59d222b39dd213a97aa009689dd576ff79c37/crates/revm/revm-inspectors/src/tracing/builder/parity.rs#L86-L91

the `TranscationTrace` vec we have already:

https://github.com/paradigmxyz/reth/blob/72f59d222b39dd213a97aa009689dd576ff79c37/crates/revm/revm-inspectors/src/tracing/builder/parity.rs#L95

this we can reuse but we need to combine the iterator with the other two types.

it's likely that the existing Call/Step types lack some info, in which case we need to revise them as well.

**Comment by m-trellis** [comment]
@PatStiles Are you currently working on this? If not, I wouldn't mind taking this.

**Comment by PatStiles** [comment]
I am :)

**Comment by mattsse** [comment]
hey @PatStiles 

This will become a blocker shortly as we try to fix all the hive tests. Are you still planning to work on it? feel free to open a draft even if unfinished.

**Comment by mattsse** [comment]
@chirag-bgh perhaps you're interested in this as well?
this one would be very valuable

**Comment by mattsse** [comment]
any update on this?
