### ISSUE TITLE
Move receipt root/bloom verification to its own stage

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1875]
### Describe the feature

Discussion point about moving receipts root/bloom verification to a separate stage. Receipt root calculation is around ~10% of execution without any optimizations.

Reasons for the move:
It splits the responsibility of calculating bloom and receipts root to the separate stage and allows us to optimise it and not affect the execution stage. (Can argue that optimization can be done inside ExecutionStage)

Reasons why move can be not desirable: 
Leaving it inside Execution stage allows us to catch the possible bugs in the node faster as execution stage takes longest to run and checking receipts right after executed block allows us to shortcircuit the path. (Can argue that pipeline is used to sync on already finalized blocks so shortcircuiting is not that effective)

**Comment by onbjerg** [comment]
>(Can argue that pipeline is used to sync on already finalized blocks so shortcircuiting is not that effective)

On one specific consensus mechanism 😄
