### ISSUE TITLE
MerkleTrie root in BlockchainTree

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#1876]
### Describe the feature

Add marketization of substate inside blockchain tree

**Comment by gakonst** [comment]
Is this because in `chain.rs` we only call `validate_and_execute` w/o any further verification? 

https://github.com/paradigmxyz/reth/blob/c5f197dd957255e9999e39a3d6c365d2f0ef15a6/crates/executor/src/blockchain_tree/chain.rs#L180-L198
