### ISSUE TITLE
Reth config which dumps the default reth.toml to stdout

### ISSUE THREAD

**Issue by aktary** [paradigmxyz/reth#1897]
### Describe the feature

Title pretty much captures it.

### Additional context

Based on @gakonst 's [request](https://t.me/paradigm_reth/2317) in Telegram

**Comment by gakonst** [comment]
We have that in foundry as well in "forge Config" it's an easy way to dump default Configs to customize things, or to quickly remember the format. Would like to have it even tho you can cat the one which you may have modified in your path.
