### ISSUE TITLE
`eth_call` fails with intrinsic gas too high

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1898]
### Describe the feature

see https://github.com/paradigmxyz/reth/issues/1785 for how to reproduce

error:
```
>>  {"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"from":"0xaa00000000000000000000000000000000000000","to":"0xaa00000000000000000000000000000000000000"},"latest"]}
<<  {"jsonrpc":"2.0","error":{"code":-32000,"message":"intrinsic gas too high"},"id":1}
response differs from expected:
 {
-  "error": {
-    "code": -32000,
-    "message": "intrinsic gas too high"
-  },
   "id": 1,
   "jsonrpc": "2.0"
+  "result": "0x"
 }
```

this is likely a misconfig of `env.tx.gas_price` and `env.tx.gas_limit` before the call is executed.

**Comment by mattsse** [comment]
likely an issue with tx env config or env config in general

https://github.com/paradigmxyz/reth/blob/2bc4da5eaa19bf3361444c83101a342dd12622dd/crates/rpc/rpc/src/eth/api/call.rs#L85-L88

**Comment by Rjected** [comment]
hmm, after doing some tracing it looks like the env is being set correctly, but the account has zero balance

**Comment by Rjected** [comment]
might also be related to why `eth_getBalance` is currently failing, since it reports the same account's balance as `0`, instead of `1`

**Comment by Rjected** [comment]
Fixed with #1997

**Comment by chen4903** [comment]
I meet `intrinsic gas too high` in cli.
I start a private network: `reth node -d --chain genesis.json --datadir /opt/reth_data/ --auto-mine --http`.
But when I send some ether to the other account ,it fails: 
```
levi@levi:/opt/reth_data$ cast balance 0xd143C405751162d0F96bEE2eB5eb9C61882a736E
89800000000000000000000000
levi@levi:/opt/reth_data$ cast send     --from 0xd143C405751162d0F96bEE2eB5eb9C61882a736E       --value 1 --legacy --private-key     0xcece4f25ac74deb1468965160c7185e07dff413f23fcadb611b05ca37ab0a52e       0x944fDcD1c868E3cC566C78023CcB38A32cDA836E
Error: 
(code: -32000, message: intrinsic gas too high, data: None)
```
my reth:
```
reth Version: 0.2.0-beta.5
Commit SHA: VERGEN_IDEMPOTENT_OUTPUT
Build Timestamp: 2024-04-14T10:50:23.293075558Z
Build Features: jemalloc
Build Profile: debug
```

**Comment by chen4903** [comment]
fixed by change the gaslimit in the genesis.json:
```
"gasLimit": "0x1388", // not work: (code: -32000, message: intrinsic gas too high, data: None)
"gasLimit": "0x2fefd8" // works
```
