### ISSUE TITLE
`eth_call` returns `insufficient funds` in call-simple-transfer test

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1907]
### Describe the bug

The `rpc-compat` test `eth_call/call-simple-transfer` returns insufficient funds:

```diff
>>  {"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"from":"0xaa00000000000000000000000000000000000000","gas":"0x186a0","to":"0x0100000000000000000000000000000000000000"},"latest"]}
<<  {"jsonrpc":"2.0","error":{"code":-32003,"message":"Insufficient funds for gas * price + value"},"id":1}
response differs from expected:
 {
-  "error": {
-    "code": -32003,
-    "message": "Insufficient funds for gas * price + value"
-  },
   "id": 1,
   "jsonrpc": "2.0"
+  "result": "0x"
 }
```

### Steps to reproduce

Run hive (#851):
```
./hive --client reth --sim ethereum/rpc-compat --sim.limit "/eth_call/call-simple-transfer"
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
blocked by #1959

see description for the new error

**Comment by gakonst** [comment]
@Rjected I wonder if this is also related to https://github.com/paradigmxyz/reth/issues/1951#issuecomment-1482093752?

**Comment by Rjected** [comment]
@gakonst it is related, and fails from insufficient funds because of the same code path. After the `HistoricalStateProvider` fix, the test fails due to `sender not an eoa`
