### ISSUE TITLE
Fill missing fields TransactionRequest fields 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1909]
### Describe the feature

In https://github.com/paradigmxyz/reth/pull/1774 we added `send_transaction` impl.

we're missing some updates after we converted the request to properly fill in missing fields here:

https://github.com/paradigmxyz/reth/blob/5987ecb1949604b0e8acb5fa18ec0591460aca0a/crates/rpc/rpc/src/eth/api/transactions.rs#LL175

Basically same as:

https://github.com/foundry-rs/foundry/blob/da2392e58bb8a7fefeba46b40c4df1afad8ccd22/anvil/src/eth/api.rs#L2209-L2236

**Comment by bharath-123** [comment]
Can take this up. Please do assign it to me

**Comment by mattsse** [comment]
#1774 is merged

**Comment by bharath-123** [comment]
awesome. so i m not blocked on anything then. Will work on it

**Comment by mattsse** [comment]
only the `gas_price` setting, because we don't have an oracle for that yet, but we should use the base fee for that
