### ISSUE TITLE
parse_socket_address does not actually parse the port

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1916]
### Describe the bug

hardcoded to 9000

https://github.com/paradigmxyz/reth/blob/8ac2b84c016ca52052c9d3999ee4e89c1245b3df/crates/staged-sync/src/utils/mod.rs#L51-L62

This function should not use any default port.

logic should be:
if starts with `:` strip `:`
     try parse as u16, return err on failure
try parse as u16
if not ok: try parse as socket addr

also I'd like this to return a custom error instead of eyre::Report

### Steps to reproduce

-

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by i-m-aditya** [comment]
I will pick this.
