### ISSUE TITLE
Fill missing Tx receipt info

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1922]
### Describe the feature

#1919 added transaction receipt.

some things are missing or incorrect atm:

* `gas_used` this can be calculated by comparing the cumulative_gas_used of transaction
* remaining log fields still need to be filled
* state root needs to be set (unsure how)

cc @chirag-bgh

**Comment by chirag-bgh** [comment]
on it!

**Comment by mattsse** [comment]
sick!
I'll merge #1919 in the meantime

**Comment by mattsse** [comment]
@chirag-bgh also, I do believe the

https://github.com/paradigmxyz/reth/blob/b44391776eca11a8de4039b8fb7b2c463acdb8bc/crates/rpc/rpc-types/src/eth/log.rs#L20-L21

is not actually part of the spec, at least not used by geth if I read that correctly:

https://github.com/ethereum/go-ethereum/blob/ee530c0d5aa70d2c00ab5691a89ab431b73f8165/core/types/log.go#L31-L31

https://ethereum.org/en/developers/docs/apis/json-rpc/
