### ISSUE TITLE
Improve rpc server launch error diagnostic

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1940]
### Describe the feature

launching the RPC server(s) (ws, http for auth or regular) can fail if the address is already in use. The current error message makes this part clear, but does not provide any context about which server reth was trying to open a socket for.

```
Error: Address already in use (os error 98
```

We want meaningful error messages for this (most common) error.

We can add this via custom error types that wraps the `jsonrpsee::Error` and adds additional variants, for example:

```rust
#[derive(thiserror::Error)]
pub enum RpcError {
    #[error(transparent)]
    RpcError(jsonrpsee::core::Error),
    #[errr("")] // TODO
    AddressAlreadyInUse {
        error: io::Error,
        transport: (), // TODO add transport enum, WS,Http
        address: SocketAddr
    }
}

// we need a helper function here that converts the type and checks the `jsonrpsee::core::Error::Transport` variant for the io error and maps to AddressAlreadyInUse 
```

**Comment by jawilk** [comment]
Hi, I would like to give this a try if possible!

**Comment by mattsse** [comment]
awesome, 
if you have any questions please open a draft PR and we go from there
