### ISSUE TITLE
add TransactionPool::pooled_transaction_max

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1950]
The only purpose of this function is to return the hashes for the initial exchange on an existing session

Ref

> Also, I think we want a `pooled_transaction_max(limit)` because this getter returns _all_ transactions in the pool even though we only need 4096 max

_Originally posted by @mattsse in https://github.com/paradigmxyz/reth/pull/1949#pullrequestreview-1355780365_

**Comment by chirag-bgh** [comment]
I can take this.

**Comment by chirag-bgh** [comment]
I think we need `pooled_transaction_max` that should return ` Vec<Arc<ValidPoolTransaction<Self::Transaction>>> ` instead of `TxHash`?

**Comment by mattsse** [comment]
we need hash for the use case mentioned above.
the other call would also be useful though
