### ISSUE TITLE
Add method for optionally disabling EIP-3607 for `eth_call` and `eth_estimateGas`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1959]
### Describe the feature

The hive test `eth_call/call-simple-transfer` sends an `eth_call` RPC with a `from` parameter of an account that has deployed code.

The call:
```
{"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"from":"0xaa00000000000000000000000000000000000000","gas":"0x186a0","to":"0x0100000000000000000000000000000000000000"},"latest"]}
```

The account (`0xaa00000000000000000000000000000000000000`):
https://github.com/ethereum/execution-apis/blob/main/tests/genesis.json#L34-L44

This motivates a way to optionally disable EIP-3607.

[EIP-3607](https://eips.ethereum.org/EIPS/eip-3607) notes:
> Clients might choose to disable this rule for RPC calls like eth_call and eth_estimateGas as some Multi-Sig contracts use these calls to create transactions as if they originated from the multisig contract itself.

### Additional context

Once #1958 is in, it should be easy to test support by [running the hive test](#851):
```
./hive --client reth --sim ethereum/rpc-compat --sim.limit "/eth_call/call-simple-transfer"
```

Output:
```diff
>>  {"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"from":"0xaa00000000000000000000000000000000000000","gas":"0x186a0","to":"0x0100000000000000000000000000000000000000"},"latest"]}
<<  {"jsonrpc":"2.0","error":{"code":-32003,"message":"sender not an eoa"},"id":1}
response differs from expected:
 {
-  "error": {
-    "code": -32003,
-    "message": "sender not an eoa"
-  },
   "id": 1,
   "jsonrpc": "2.0"
+  "result": "0x"
 }
```

**Comment by gakonst** [comment]
Here's how we did it in foundry https://github.com/search?q=repo%3Afoundry-rs%2Ffoundry%20eip-3607&type=code

Revm has an option called [`disable_eip3607`](https://github.com/search?q=repo%3Abluealloy%2Frevm%203607&type=code) behind an `optional_eip3607` feature flag.
