### ISSUE TITLE
Consistent RPC Responses

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#1960]
### Describe the bug

From [this](https://github.com/paradigmxyz/reth/actions/runs/4506302691/jobs/7933000926?pr=1348) Hive CI run, we can see that our RPC responses are not right, and we should match the expected response by Hive.

```
-    "message": "hex string without 0x prefix at line 1 column 3"
+    "message": "invalid argument 0: hex string without 0x prefix"
```

I am less sure what to do with this. Do we really need to match this Golang-style error? Ideally we just need to return the correct error code

```
-  "result": "0x"
+  "error": {
+    "code": -32602,
+    "message": "invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type common.Hash"```

**Comment by mattsse** [comment]
tbh I don't think we should manually map the error message:

> invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type common.Hash"

because

> into Go value of type common.Hash

this would not be correct.

**Comment by onbjerg** [comment]
Closing ref @mattsse's comment, let me know if we should still consider this @gakonst
