### ISSUE TITLE
Add eth rpc helper function to fetch current sender nonce

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#1978]
### Describe the feature

for eth_sendTransaction we need to populate the nonce field if unset.

this needs to check:
* txpool for existing tx from sender
* OR on chain nonce

## TODO
- [ ] add new function to TransactionPool trait to fetch transactions by sender, similar to https://github.com/paradigmxyz/reth/blob/d07a0b9d2e9d81e1c7cb6b9a7da457d5ddc1783e/crates/transaction-pool/src/traits.rs#L131-L132 but with address as argument, also relevant: https://github.com/foundry-rs/foundry/blob/master/anvil/src/eth/backend/mem/mod.rs#L1964-L1978
- [ ] Integrate in `get_transaction_count` with Pending block, that checks pool

ref #1976

**Comment by bharath-123** [comment]
@mattsse would love to pick this up since this is going to be an extension to my current work
