### ISSUE TITLE
Make EthApi accessors public

### ISSUE THREAD

**Issue by Gaon3** [paradigmxyz/reth#1987]
### Describe the feature

Hello,
I want to use EthApi in standalone (for example make an ethers-rs Middleware which uses Reth's database) and I want to add my own custom methods but accessors are private so I'm limited to using standard RPC methods. 
Making the accessors (all methods which EthApi implements) public would allow for more customization in a standalone usage.
https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/api/mod.rs#L60

**Comment by mattsse** [comment]
This is a reasonable request and makes sense to make them public since these return the generic types. 
I'd accept a PR for this client,network,pool

**Comment by Gaon3** [comment]
@mattsse What about state accessors ?
