### ISSUE TITLE
Implement `trace_replayTransaction` + `trace_replayBlockTransactions``

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2010]
### Describe the feature

ref #1225 

The `trace_replayTransaction` is unimplemented:

https://github.com/paradigmxyz/reth/blob/8987f4e8be60b92d596acc21a2b27ecc4ede9f1a/crates/rpc/rpc/src/trace.rs#L227-L228

This can be implemented together with `trace_replayBlockTransactions` because for `trace_replayTransaction` we need to replay the block until the target transaction anyways.

## TODO
* fetch block + block's `env`
* execute all transactions (with inspector or without)

I believe some parts can be reused after some modifications:

https://github.com/paradigmxyz/reth/blob/8987f4e8be60b92d596acc21a2b27ecc4ede9f1a/crates/rpc/rpc/src/trace.rs#L71-L81

**Comment by chirag-bgh** [comment]
I would like to implement this.

**Comment by mattsse** [comment]
nice, this will be a bit more challenging, so feel free to open PR as soon as questions arise, and we go from there.
