### ISSUE TITLE
Improve network with txpool test coverage

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2014]
### Describe the feature

https://github.com/paradigmxyz/reth/pull/1901 surfaced several bugs in the network <-> pool integration that went unnoticed until #2004

to catch these, test coverage with installed txpool service needs to be improved

see existing tests in https://github.com/paradigmxyz/reth/tree/main/crates/net/network/tests/it

## TODO

* add new `network` integration tests with txpool task
* ensure transactions can be exchanged properly

**Comment by i-m-aditya** [comment]
I will pick this.

**Comment by mattsse** [comment]
awesome, lmk if you need some additional input/pointers
