### ISSUE TITLE
RLP unit test data does not match linked source data

### ISSUE THREAD

**Issue by perama-v** [paradigmxyz/reth#2032]
### Describe the bug

Receipts in the `primitives` crate are being evaluated against test data that is different from the reference test data.
This suggests that the implementation is being tested incorrectly. 

This discrepancy was noted when trying to resolve a decoding issue of a separate test, which was passing with two non-trin clients and failing with trin (with reth primitives under the hood). It remains possible that the issue lies elsewhere.  Context: https://github.com/ethereum/trin/pull/613

I note that this may also be the source of the following potentially related issue:
- https://github.com/paradigmxyz/reth/issues/1625

### Steps to reproduce

1. Note RLP bytes used in the unit tests: 
a. https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/receipt.rs#L210, 
b. https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/receipt.rs#L246

```
"f901668001b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f85ff85d940000000000000000000000000000000000000011f842a0000000000000000000000000000000000000000000000000000000000000deada0000000000000000000000000000000000000000000000000000000000000beef830100ff"
```
2. Note the "rlp" field value of type "ReceiptsPacket66" (https://eips.ethereum.org/EIPS/eip-2481) is different:
```
"0xf90172820457f9016cf90169f901668001b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f85ff85d940000000000000000000000000000000000000011f842a0000000000000000000000000000000000000000000000000000000000000deada0000000000000000000000000000000000000000000000000000000000000beef830100ff"
```

The EIP test case has an additional: `f90172820457f9016cf90169` (a 96-bit integer) at the start as compared to the Reth test case. The remaining bytes are identical.
```
0xf90172820457f9016cf90169< >f901668001b9010000000000000...
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
Hi!

> Note the "rlp" field value of type "ReceiptsPacket66" (https://eips.ethereum.org/EIPS/eip-2481) is different:
> ``` 
> 0xf90172820457f9016cf90169f901668001b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f85ff85d940000000000000000000000000000000000000011f842a0000000000000000000000000000000000000000000000000000000000000deada0000000000000000000000000000000000000000000000000000000000000beef830100ff
> ```

The EIP-2481 test vector is an encoding of the entire `Receipts` packet, including the `eth/66` request ID.

Our test case which exactly matches that RLP string is here, because we use the `RequestPair::<Receipts>` type to represent `ReceiptsPacket66`:
https://github.com/paradigmxyz/reth/blob/efbaf6474c2eae0d8300069a7339a4aa6e7f3c59/crates/net/eth-wire/src/types/receipts.rs#L123-L130

> The EIP test case has an additional: `f90172820457f9016cf90169` (a 96-bit integer) at the start as compared to the Reth test case. The remaining bytes are identical.

From the [eth/66 spec](https://github.com/ethereum/devp2p/blob/master/caps/eth.md#receipts-0x10):
> Receipts (0x10)
> `[request-id: P, [[receipt₁, receipt₂], ...]]`

This represents the `[ request id: P, [[` portion of the packet from the test case for `RequestPair::<Receipts>`.
```
            request id
            |
[          1111 [       [
f9 0172 82 0457 f9 016c f9 0169
^  ^    ^  ^    ^  ^    ^  ^
| |     |  |    |  |    |  list len (361 bytes)
| |     |  |    |  |    |
| |     |  |    |  |    list header (len of len = 2)
| |     |  |    |  |
| |     |  |    |  list len (364 bytes)
| |     |  |    |
| |     |  |    list header (len of len = 2)
| |     |  |
| |     |  request_id (0x0457 = 1111)
| |     |
| |     string header (len = 2 bytes)
| |
| list len (370 bytes)
|
List header (len of len = 2)
```
Because the EIP-2481 test vector includes only a single receipt, we reuse the test data following this string for testing the underlying `Receipt` encoding.

> Note RLP bytes used in the unit tests:
> a. https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/receipt.rs#L210,
> b. https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/receipt.rs#L246

The string `f90172820457f9016cf90169` is the right thing to remove from these test cases because with `reth_primitives::Receipt`, we are only testing the encoding of the individual receipt, not the entire `Receipts` packet from the wire protocol.

Additional failing test vectors are always appreciated though, if there are any discovered from https://github.com/ethereum/trin/pull/613!

**Comment by perama-v** [comment]
Ok, that looks sound. Thank you for the explanation and the encoding layout.
