### ISSUE TITLE
No events logged for the reth::cli=info target in Execution Stage

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2034]
### Describe the bug

when transitioning from SenderRecovery to Execution, default cli logs are stuck at:

> 2023-03-29T21:02:50.056149Z  INFO Stage committed progress stage=SenderRecovery checkpoint=3185000

however, it moved into Execution Stage

when restarting the node the last thing logged is

> INFO Starting consensus engine

seems like there's no reporting from execution that is logged to stdout

this is possibly a dup of #2000

### Steps to reproduce

-

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Gaon3** [comment]
Is it possible that the new thread spawned at every iteration of the stage (https://github.com/paradigmxyz/reth/blob/main/crates/stages/src/stages/execution.rs#L211) blocks the notifications' receivers ? Because logs internal to the stage such as `2023-03-27T20:50:04.147287Z  INFO sync::stages::execution: Sync iteration finished stage_progress=5125000 done=false` are written to file.

**Comment by mattsse** [comment]
> notifications' receivers

what do you mean exactly?

**Comment by Gaon3** [comment]
https://github.com/paradigmxyz/reth/blob/main/crates/stages/src/pipeline/event.rs#L65
Well there is only one listener (the node)

**Comment by mattsse** [comment]
I assume this is an issue with this section

https://github.com/paradigmxyz/reth/blob/6261262a203b35870ad52f22585f14e51adbd7a0/bin/reth/src/node/events.rs#L33-L51

but I don't fully understand the `is notable` logic yet.

perhaps @rkrasiuk or @onbjerg can yet

in any case, event reporting during execution stage is definitely broken

**Comment by Gaon3** [comment]
In my written logs, last message about SenderRecovery is 
>2023-03-27T20:49:27.158652Z  INFO execute{stage=SenderRecovery}: sync::stages::sender_recovery: Sync iteration finished stage_progress=16921047 done=true
>2023-03-27T20:49:27.158659Z  INFO execute{stage=SenderRecovery}: sync::pipeline: Stage made progress stage=SenderRecovery stage_progress=16921047 done=true

At this point a PipelineEvent::Ran is sent to the listeners and result.done is true (as in the log), so a message announcing that the SenderRecovery stage has finished should be printed independently of the Execution stage

**Comment by onbjerg** [comment]
@mattsse I cannot reproduce this locally on commit 7263c9a644203d94aeec127221e9484052a44058 and before, so it is something recent. My best guess is that it is most likely that the channel we use here to get the events from the pipeline no longer exists/is broken on some sync controller state changes? I.e. if the pipeline is suspended by the sync controller and then resumed later on

**Comment by Gaon3** [comment]
@onbjerg The next commit is this one https://github.com/paradigmxyz/reth/commit/1ecbd55d45431e32f243d3f2156f1702b9ac8972 and even though I don't have the knowledge to understand what's really going on the modifications may be the cause of what's blocking the pipeline events.
