### ISSUE TITLE
Handle reorgs in txpool

### ISSUE THREAD

**Issue by dancoombs** [paradigmxyz/reth#2040]
### Describe the feature

The current implementation of `TxPool` ignores chain reorganization events.

https://github.com/paradigmxyz/reth/blob/78470f7bf7723aee69b3a6b6847d0b3f53bc7844/crates/transaction-pool/src/pool/txpool.rs#L168

Transactions that are were previously included in the prior fork, but are no longer included in the new canonical fork are lost as they are discarded when originally being included.

To properly handle reorgs these transactions should be added back to the pool. The `TxPool` needs access to a cache of historical blocks so that it can compare transactions from those blocks to determine transactions to add back to the pool.

### Additional context

Inspiration can be taken from Geth's handling here: https://github.com/ethereum/go-ethereum/blame/2d1492821d058a3488b4da2c1f62906eaf6d7c95/core/txpool/txpool.go#L1296

Open questions:

1. When a new canonical fork is chosen will the `TxPool::on_new_block()` method be called for each new block on the fork? Or will it be required to rewind back to a common block, and diff transactions starting from that block height?
2. How should the `TxPool` get access to the cache of blocks? Should it maintain its own cache up to some maximal reorg height? Or can it just be given direct access to a block database and query blocks by hash (similar to Geth's implementation)?

**Comment by gakonst** [comment]
Ty for the issue @dancoombs, we'll handle this!
