### ISSUE TITLE
Insert transactions received via new payload into pool

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2100]
### Describe the feature

NewPayload with encoded transactions is received here:

https://github.com/paradigmxyz/reth/blob/b7395a89a5520f739a09826374ac957410ccecfc/crates/rpc/rpc-engine-api/src/engine_api.rs#L66-L69

ideally all of them should be inserted into the pool

I think this should happen here and not in BeaconEngine, wdyt @rkrasiuk?

**Comment by rkrasiuk** [comment]
i think it should be done either in the engine or in the blockchain tree. the thing is, we want to make sure that the payload is valid **and** that it is a part of the canonical chain

**Comment by rkrasiuk** [comment]
@mattsse actually, should we insert any transactions regardless of whether it's a canonical chain or not?
