### ISSUE TITLE
Implement CallTracer

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2110]
### Describe the feature

> The callTracer tracks all the call frames executed during a transaction, including depth 0. The result will be a nested list of call frames, resembling how EVM works. They form a tree with the top-level call at root and sub-calls as children of the higher levels. Each call frame has the following fields:

ref https://geth.ethereum.org/docs/developers/evm-tracing/built-in-tracers

all of this should already be supported by the 

https://github.com/paradigmxyz/reth/blob/c0a17d655bca2e240efe540ab7cee79d1152fe99/crates/revm/revm-inspectors/src/tracing/mod.rs#L36-L36

but need a way to transform the result into a `CallFrame`

## TODO

* add new builder function like: 
https://github.com/paradigmxyz/reth/blob/c0a17d655bca2e240efe540ab7cee79d1152fe99/crates/revm/revm-inspectors/src/tracing/builder/geth.rs#L83-L89
but create a `CallFrame` type instead

**Comment by chirag-bgh** [comment]
I can take this.

**Comment by bharath-123** [comment]
hey @mattsse want to pick this up. I am working on the capabilities related issue but this seems simpler can i give it a shot?

**Comment by mattsse** [comment]
sure, ty!

**Comment by bharath-123** [comment]
hey @mattsse looks like callFrame type is already there in the struct except without revertReason. But it is not being constructed anywhere. looks like we can build the builder for this type.

**Comment by mattsse** [comment]
that sounds reasonable, 
do you have a draft for this?

**Comment by mattsse** [comment]
awesome! tysm

**Comment by bharath-123** [comment]
hey @mattsse could you check this draft out of call tracer implementation!
