### ISSUE TITLE
Call for checklist for features and release system. 

### ISSUE THREAD

**Issue by nagatoism** [paradigmxyz/reth#2155]
### Describe the change

Hi We are search a good high perf open source eth client to do some modification and we found reth.
It would be nice to quickly know how close this project is ready for production use, or at least knowing the progression. 

Currently there is no checklist about the features which have been shipped by this project.

So here is my wish list.

1 A checklist for progression of major features
2 a release system with version control.

**Comment by onbjerg** [comment]
We are not production ready in the sense that we are fully stable and w/o bugs, but we have released our first alpha today :)

https://www.paradigm.xyz/2023/06/reth-alpha

**Comment by nagatoism** [comment]
Hi I have already shared this with our people. Great work!
