### ISSUE TITLE
Add MinerArgs for CLI

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2160]
### Describe the feature

add a clap container type for `--miner.*` args, see `--debug.*` for reference:

https://github.com/paradigmxyz/reth/blob/cf18edb0fe45abc36325dec905e8efec7800773c/bin/reth/src/args/debug_args.rs#L6-L9

see also `geth --help`

**Comment by i-m-aditya** [comment]
I will pick this.

**Comment by mattsse** [comment]
awesome, 

for first PR a simple struct def is sufficient
