### ISSUE TITLE
Make extradata verification optional

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2176]
### Describe the feature

This is not always true:

https://github.com/paradigmxyz/reth/blob/2df16021bfdfaf6565662dc8afece6a5f2143ff7/crates/consensus/common/src/validation.rs#L36-L40

on goerli for example extradata can be larger (clique consensus)

this is only enforced in beacon + ethash consensus 

https://github.com/ethereum/go-ethereum/blob/2adce0b06640aa665706d014a92cd06f0720dcab/consensus/clique/clique.go#L246-L246

but not in clique:

https://github.com/ethereum/go-ethereum/blob/2adce0b06640aa665706d014a92cd06f0720dcab/consensus/ethash/consensus.go#L270-L272

## TODO 

make this configurable, perhaps via ChainSpec pre merge?

**Comment by gakonst** [comment]
`ChainSpec` works
