### ISSUE TITLE
Use an explicit root data dir to contain all reth data

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#2179]
### Describe the feature

Currently the `reth node` command accepts many different path arguments which share a root directory by default. The directory structure has to be recreated and explicitly specified if the user wants a separate root directory.

We should move to this type of directory structure, enabled by a `--datadir` flag:
```
$HOME/.local/share/
    reth/
        goerli/
            reth.toml
            db/
            net/
                known-peers.json
            p2p/
            ...
        mainnet/
            reth.toml
            db/
            ...
        4949494/
            reth.toml
            db/
            ...
```
Currently, when flags are not specified, the root data directory is determined by `data_dir`:
https://github.com/paradigmxyz/reth/blob/54fc809a4c2249c6843ee00be14ce9ba5c913f01/bin/reth/src/dirs.rs#L10-L15

We should use this as a default if no `data_dir` is provided, and otherwise use the provided directory. A `Chain` should be required, and appended to the root datadir, similar to #1846 

Methods should be reusable enough to allow all reth commands (`init`, `node`, etc.) to use this structure

**Comment by mattsse** [comment]
Agree,
--datadir is also used by other clients.

atm data_dir is same path for all chains, which is bad.

> We should use this as a default if no data_dir is provided, and otherwise use the provided directory. A Chain should be required, and appended to the root datadir, similar to https://github.com/paradigmxyz/reth/pull/1846

yes

**Comment by gakonst** [comment]
For completeness, here's how it looks like now:

```
➜  reth pwd
/Users/georgios/Library/Application Support/reth
➜  reth tree
.
├── goerli
│   ├── db
│   │   ├── mdbx.dat
│   │   └── mdbx.lck
│   └── reth.toml
├── jwtsecret
│   └── jwt.hex
├── net
│   ├── goerli
│   └── sepolia
│       └── known-peers.json
├── p2p
│   └── secret
└── sepolia
    ├── db
    │   ├── mdbx.dat
    │   └── mdbx.lck
    └── reth.toml

9 directories, 9 files
```

**Comment by ruuderie** [comment]
@gakonst @mattsse @Rjected I'm taking a look at this.

**Comment by gakonst** [comment]
Assigned! Thank you!
