### ISSUE TITLE
Only serialize `Block::withdrawals` if withdrawals root is set

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2239]
### Describe the feature

The `withdrawals` fields is always serialized:

https://github.com/paradigmxyz/reth/blob/0b9621cfaa48b5b220bedb03dd7e3f5ec2a71b08/crates/rpc/rpc-types/src/eth/block.rs#L81-L83

this should only be serialized if the block's `header.withdrawal_root` is set.

ref https://github.com/ethereum/go-ethereum/blob/4a9fa31450d3cdcea84735b68cd5a0a8450473f8/internal/ethapi/api.go#L1256-L1258

## TODO

The type should be changed to an Option<Vec> and skip serialize if None

**Comment by i-m-aditya** [comment]
I will pick this.
