### ISSUE TITLE
Remove reth-network-api dependency from rpc-types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2241]
### Describe the feature

rpc-types should be a standalone crate

It currently depends on two types defined in the reth-network-api crate for the admin namespace

https://github.com/paradigmxyz/reth/blob/0b9621cfaa48b5b220bedb03dd7e3f5ec2a71b08/crates/rpc/rpc-types/src/admin.rs#L1-L1

## TODO

move type defs from

https://github.com/paradigmxyz/reth/blob/0b9621cfaa48b5b220bedb03dd7e3f5ec2a71b08/crates/net/network-api/src/lib.rs#L97-L124

to rpc-types and reverse dependencies: reth-network-api depends on rpc-types

**Comment by i-m-aditya** [comment]
I will pick this
