### ISSUE TITLE
Hardcode Merge blocks for each chain

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#2255]
### Describe the feature

# Problem

When you start a Reth node with a Consensus Layer, Reth is waiting for an `engine_forkChoiceUpdated` (FCU) message from the CL to start downloading headers.

However, the CL will not send `engine_forkChoiceUpdated` unless reth is nearing the merge block. If no FCU sent, nothing happens in the beacon engine, the pipeline is not run, the node is idle

The reason it worked out of the box on Sepolia is because the Merge is enabled from the start.

# Solution

Let's hardcode the Merge block hash for each chain:
1. Mainnet: https://etherscan.io/block/15537393
2. Goerli: https://goerli.etherscan.io/block/7382818

(the Merge activates in the next block actually, so maybe it should be the next block instead of the one i wrote above?)

Then, if we detect that we're before that block, we will simulate a FCU, just how we do with `--debug.tip`. That gets us at the merge, and then the CL will send us more FCUs, problem solved.

**Comment by rkrasiuk** [comment]
The misconception about the need for hardcoding the merge block came from the expectation that the CL should start issuing FCUs while syncing in a non-checkpoint mode. This issue is no longer relevant
