### ISSUE TITLE
Rework how progress is reported

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#2260]
### Describe the feature

Currently, our stage progress is block number based. 

This works for reporting progress on Bodies but it really doesn't do that well elsewhere:
1. Headers: Due to the reverse downloader progress only is reported at the end of the stage, so this is useless atm
2. SendersRecovery: Some blocks are more empty than others, meaning we don't have a "uniform" load resulting in subpar parallelism. Ideally, since we have the tx id -> block number index, we could make the batch sizes more consistent in terms of the number of recoveries we perform. What if the threshold was instead # of transactions to recover, and the stage tries to approach that number using the tx id -> block num index? In that case, how would it report progress back?
3. Hashing / Merkle Stages: They do not really operate over a block range, they are walking the DB. How do we properly report that back?

# Solution

Include more information in the checkpoint about where we've progressed to. 
* What about skipping a stage? Each stage itself can decide whether it should be skipped or not.
* What about metrics? We'd need to rework a bit how our Grafana dashboards look like 

Maybe something like this, per @rkrasiuk suggestion:

```rust
struct Checkpoint {
  max_processed_block: BlockNumber
  max_processed_unit: Option<CheckpointUnit>
}

enum CheckpointUnit {
  Transaction(TxId),
  Transition(TransitionId),
  Address(Address),
  Storage(Address, Storage)
}
```

@rkrasiuk @onbjerg please share your thoughts on this, cc @mattsse as it relates to the broader pipeline

**Comment by gakonst** [comment]
@shekhirin will take this

**Comment by shekhirin** [comment]
@gakonst I think we can close this as completed. 

1. Headers stage is now reporting progress in % and shows in Grafana dashboard
2. Senders Recovery and Transaction Lookup stages now have tx-based commit logic and progress reporting
3. Hashing and Merkle stages are now reporting progress in % as number of entries walked

> What about skipping a stage? Each stage itself can decide whether it should be skipped or not.

Not sure about this one

**Comment by gakonst** [comment]
I think we can close, yes.
