### ISSUE TITLE
Phase out EthersGenesis in primitives

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2293]
### Describe the feature

we currently use two genesis types (ethers,reth)

Used by chainspec:

https://github.com/paradigmxyz/reth/blob/0761bb42f7c2425d2d4d18f4e5ea991d13a72ef2/crates/primitives/src/chain/spec.rs#L9-L9

during serde

## TODO

* get rid of `EthersGenesis` entirely
* add missing ChainConfig to `reth::Genesis`

**Comment by i-m-aditya** [comment]
I will take this.
