### ISSUE TITLE
Use caching layer when fetching blocks for logs

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2302]
### Describe the feature

This:

https://github.com/paradigmxyz/reth/blob/5eef3c5fc6c3ad2ecfbc2ebdcd45a0838bc77d4c/crates/rpc/rpc/src/eth/filter.rs#L188-L188

should use the caching layer

same as for

https://github.com/paradigmxyz/reth/blob/5eef3c5fc6c3ad2ecfbc2ebdcd45a0838bc77d4c/crates/rpc/rpc/src/eth/filter.rs#L191-L191

## TODO

* replace sync DB lookups with async lookups from `EthStateCache `

See `PubSub` impl for reference:

https://github.com/paradigmxyz/reth/blob/5eef3c5fc6c3ad2ecfbc2ebdcd45a0838bc77d4c/crates/rpc/rpc/src/eth/pubsub.rs#L174-L175

**Comment by chirag-bgh** [comment]
i can take this
