### ISSUE TITLE
Difference in default block reward and clique block reward

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#2307]
> > @Rjected how much is block reward in clique, it is probably the problem.
> 
> Looks like there is no block reward: https://github.com/ethereum/go-ethereum/blob/4a9fa31450d3cdcea84735b68cd5a0a8450473f8/consensus/clique/clique.go#L574
> 
> ```
> 	// No block rewards in PoA, so the state remains as is
> ```
> 
> It seems like this is more related to the gas calculation for the transaction, might just be an environment issue

Then this is a problem if we want to support clique. block rewards are now always added here: https://github.com/paradigmxyz/reth/blob/9e8d9883d14989822e7c922f6219f7040e2b2e9e/crates/revm/src/executor.rs#L508

_Originally posted by @rakita in https://github.com/paradigmxyz/reth/issues/2178#issuecomment-1504243497_

We might want to look into the differences in the goerli and default block reward, because we seem to handle it differently than clique.

**Comment by gakonst** [comment]
@rkrasiuk @rakita is this still relevant after this https://github.com/paradigmxyz/reth/pull/2377?

**Comment by rakita** [comment]
@gakonst it fixed here: https://github.com/paradigmxyz/reth/pull/2484
