### ISSUE TITLE
Add new Overdraft transaction check

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2308]
### Describe the feature

Add new error variant and check if a transaction would cause the sender's balance to go negative

required for consistent RPC response errors

ref https://github.com/ethereum/go-ethereum/blob/3768b0074791169441ca5eb3a7c73c7b9e74c24a/core/txpool/txpool.go#L97

TODO
* add error variant: https://github.com/paradigmxyz/reth/blob/534d23eed8798807de9bfe6b5f9027bd5c7e6eb0/crates/rpc/rpc/src/eth/error.rs#L314-L317
* add corresponding check in pool impl

**Comment by chirag-bgh** [comment]
I can take this.

**Comment by chirag-bgh** [comment]
@mattsse 
I believe we've to add this new check added in geth https://github.com/ethereum/go-ethereum/blob/3768b0074791169441ca5eb3a7c73c7b9e74c24a/core/txpool/txpool.go#L672-L685
What does this block do here?
```
if repl := list.txs.Get(tx.Nonce()); repl != nil {
            // Deduct the cost of a transaction replaced by this
            sum.Sub(sum, repl.Cost())
        }
```

I think we're fetching the tx from the pending transactions in the txpool which would be replaced by the tx which we are validating by checking for the same nonce.
So shouldn't be the check actually for ` balance > sum + tx.Cost() ` [here](https://github.com/ethereum/go-ethereum/blob/3768b0074791169441ca5eb3a7c73c7b9e74c24a/core/txpool/txpool.go#L680) ?

**Comment by mattsse** [comment]
hmm,
If I read this correctly, then this is always enforced and doesn't require the new tx to be a replacement transaction, right?

https://github.com/ethereum/go-ethereum/blob/3768b0074791169441ca5eb3a7c73c7b9e74c24a/core/txpool/txpool.go#L674-L684

**Comment by chirag-bgh** [comment]
Okay got it my bad the tx.Cost() is added to `sum` already


> hmm, If I read this correctly, then this is always enforced and doesn't require the new tx to be a replacement transaction, right?

So this checks if there is an existing transaction with the same nonce as the new transaction. If there is, it means the new transaction is meant to replace the existing one right?

**Comment by seroze** [comment]
>add corresponding check in pool impl

@mattsse  where should this check be added exactly  in `txpool.rs` ?
