### ISSUE TITLE
Add task for inserting charge history cache items on new blocks

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2315]
### Describe the feature

With fee history cache: https://github.com/paradigmxyz/reth/pull/2083

we can populate the cache when new blocks are added to the chain to prefill cache

first attempt #1408

## TODO
* add async function that takes (similar to https://github.com/paradigmxyz/reth/pull/2298/files#diff-68a2e4de65bc0a443115d572955f805de540909c44bebbf605abe6f4e3eb7601R14)
  * the history cache
  * Stream of CanonStateNotfications
* for every new block insert an item in the cache, See `eth_feeHistory` impl

we likely need to extract some parts of the `fee_history` function to standalone functions

**Comment by i-m-aditya** [comment]
I will take this.

**Comment by supernovahs** [comment]
Is this still relevant?

**Comment by mattsse** [comment]
we have this already
