### ISSUE TITLE
Buffer future blocks while pipeline is syncing

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2336]
### Describe the feature

As described in #2326

currently, we're not inserting any additional payloads if pipeline is syncing.

this leads to problems where the engine has problems to follow the CL and always lags behind.

For example current behavior:
1. FCU missing block (block `n)` -> pipeline starts syncing
2. new payload (candidate for `n+1`)-> pipeline is syncing -> ingore payload
3. pipeline finished syncing to `n`
4. FCU with head `n+1` -> missing in tree because never inserted in 2. -> pipeline starts syncing to `n+1`
5. repeat...

https://github.com/paradigmxyz/reth/blob/6b0135965c52dafe132be6fa33c77aec23f9cb91/crates/consensus/beacon/src/engine/mod.rs#L383-L385

we can improve this by buffering future payloads (block number > pipeline target) and execute them (make them part of the tree) once the pipeline has finished

the range of buffered blocks should be restricted, similar to `max_blocks_in_chain` I suppose

**Comment by rakita** [comment]
closed with https://github.com/paradigmxyz/reth/pull/2397
