### ISSUE TITLE
Add base fee argument to `best_transactions`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2337]
### Describe the feature

The iterator will only adhere to the current basefee of the pool

https://github.com/paradigmxyz/reth/blob/dfc63e524aad416a44807a24fb839c57d2c775e3/crates/transaction-pool/src/traits.rs#L102-L107

This may or may not be the same basefee of the block that the payload builder might target.

## TODO

* add another Iterator type that applies the base fee update on a copy of the subpools so the basefee condition is respected, but does not commit changes to the txpool itself.

perhaps this could even work by cloning the pending pool first, then applying updates similar to:

https://github.com/paradigmxyz/reth/blob/600f3eac8c494dfc10b628527ff87513e2381b7f/crates/transaction-pool/src/pool/txpool.rs#L131-L135
and then convert it into iterator

**Comment by shawnharmsen** [comment]
would like to take this please, will add pr shortly

**Comment by tcoratger** [comment]
Is there something left to do here as there is already a `best_transactions_with_base_fee` function that is implemented in the same trait, surely since the issue was created?

**Comment by mattsse** [comment]
right, this can be closed now
