### ISSUE TITLE
Add small / big Variants and impls for stages that spawn

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2339]
### Describe the feature

some stages, like recovery,tx loop make use of rayon parallelization which is not efficient if the batch size is small, for example, if the pipeline needs to re-sync only 1,2 or 3 blocks, then rayon overhead is not ideal.

the `futures::join_all` does something similar where, depending on the size, it uses a different impl:

https://docs.rs/futures-util/0.3.28/src/futures_util/future/join_all.rs.html#119

we could mirror this easily and have a rayon and a sync impl

**Comment by Gaon3** [comment]
Is something like `if last_tx_num - first_tx_num > MAX_TXS_BEFORE_PARALLELIZATION { ... } else { ... }` enough or do you expect something more sophisticated ?
