### ISSUE TITLE
Add `best_number` call to BlockIdProvider

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2351]
### Describe the feature

we currently use 

https://github.com/paradigmxyz/reth/blob/370c39525a4ae18894e9681f9b6660f9385f76b2/crates/storage/provider/src/traits/block_id.rs#L8-L9

a lot when looking up the best_number like:

https://github.com/paradigmxyz/reth/blob/370c39525a4ae18894e9681f9b6660f9385f76b2/crates/rpc/rpc/src/eth/filter.rs#L219-L220

this currently reads from disk, we can optimize reads by adding dedicated impl for best block number

## TODO
* add extra call like https://github.com/paradigmxyz/reth/blob/370c39525a4ae18894e9681f9b6660f9385f76b2/crates/storage/provider/src/providers/mod.rs#L114-L114

**Comment by i-m-aditya** [comment]
I will pick this.
