### ISSUE TITLE
Add payload builder panels to the Grafana dashboard

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#2365]
### Describe the feature

Add new panels for all the metrics added in the PRs linked to #2345. These should probably live in a new section on the dashboard, like we have sections for the downloaders, network, execution stage etc.

**Small guide**

1. Import the Grafana dashboard ([here](https://github.com/paradigmxyz/reth/blob/main/etc/grafana/dashboards/overview.json))
2. Make all the changes, adding panels, moving stuff around etc.
3. Click the Save icon at the top of the page
4. Click the Share icon on the top left of the page, select Export and check the "Export for sharing externally" box
5. Copy the JSON model and paste it over the current one in the repository

### Additional context

Depends on https://github.com/paradigmxyz/reth/issues/2345

**Comment by i-m-aditya** [comment]
I will do this.
