### ISSUE TITLE
Discuss: How to handle block reward to miner

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#237]
If there is transactions present inside block we could just add block reward (2eth) to last transaction change set.

The problem is how to handle it if there are no transactions inside block, we still need index for transaction to index validator account balance change.

Do we always include +1 transaction changeset for validator block reward? In that case index of transactions would always be `body.len()+1`. This could probably work but want others to be aware of it if we do it this way.

**Comment by onbjerg** [comment]
We ended up building separate block and tx indexes as outlined in https://github.com/paradigmxyz/reth/blob/main/docs/design/database.md#table-design
