### ISSUE TITLE
Add peer reputation management features

### ISSUE THREAD

**Issue by jonasbostoen** [paradigmxyz/reth#2384]
### Describe the feature

The features requested here are the following:
* Add a method to request the current reputation of a peer to the network handle and its APIs: `reputation_by_id`
* Add `ReputationChangeKind::Reset` to reset a peer's reputation to 0

If you guys approve this I can create a PR :)

**Comment by mattsse** [comment]
supportive of this

**Comment by jonasbostoen** [comment]
@mattsse yes but that would require turning it into an async trait, because we'll have to go through some channels, is that ok?

**Comment by mattsse** [comment]
this is fine
