### ISSUE TITLE
Goerli sync `receipt root is different than expected` redux

### ISSUE THREAD

**Issue by yorickdowne** [paradigmxyz/reth#2408]
### Describe the bug

reth built from commit `a7b37493121426a67176374b84de5a3e01df8401` with Lighthouse 4.1.0, attempt to sync Goerli, execution stage fails on block 6001754.

### Steps to reproduce

Sync reth with Lighthouse on Goerli

Parameters the same as issue #2371

### Node logs

```text
reth-test-execution-1  | 2023-04-26T12:32:00.926872Z ERROR execute{stage=Execution}: Stage encountered a fatal error: Stage encountered a execution error in block 6001754: Receipt root 0x4b4fc726e0f28a9c673309e3b8366cbd545b61fc9d82e04da327f1d03a2f4468 is different than expected 0x236d7605769ca00fc2fc01dcec453e4f0161ecb5816448752f595c473e5d3556... stage=Execution
reth-test-execution-1  | Error: A stage encountered an irrecoverable error.
reth-test-execution-1  | 
reth-test-execution-1  | Caused by:
reth-test-execution-1  |    0: Stage encountered a execution error in block 6001754: Receipt root 0x4b4fc726e0f28a9c673309e3b8366cbd545b61fc9d82e04da327f1d03a2f4468 is different than expected 0x236d7605769ca00fc2fc01dcec453e4f0161ecb5816448752f595c473e5d3556..
reth-test-execution-1  |    1: Receipt root 0x4b4fc726e0f28a9c673309e3b8366cbd545b61fc9d82e04da327f1d03a2f4468 is different than expected 0x236d7605769ca00fc2fc01dcec453e4f0161ecb5816448752f595c473e5d3556.
reth-test-execution-1  | 
reth-test-execution-1  | Location:
reth-test-execution-1  |     bin/reth/src/node/mod.rs:345:9
reth-test-execution-1 exited with code 1
reth-test-execution-1  | 2023-04-26T12:32:01.930757Z  INFO reth 0.1.0 starting
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

a7b37493121426a67176374b84de5a3e01df8401

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by rkrasiuk** [comment]
@yorickdowne #2484 _might_ fix the issue, will resync goerli to make sure

**Comment by rkrasiuk** [comment]
Execution is past the block in question
<img width="858" alt="Screenshot 2023-04-30 at 20 32 08" src="https://user-images.githubusercontent.com/25429261/235367501-dde878ce-d00c-4977-b87d-0641d9091589.png">

**Comment by yorickdowne** [comment]
Testing here as well. Unhappy with this PR on the existing DB, so I'm syncing fresh

**Comment by yorickdowne** [comment]
Can confirm fix works here, as well.
`Stage made progress stage=Execution stage_progress=6660000`

**Comment by gakonst** [comment]
Amazing :)
