### ISSUE TITLE
Sync stall w/ Nimbus

### ISSUE THREAD

**Issue by yorickdowne** [paradigmxyz/reth#2409]
### Describe the bug

Sync Reth with checkpoint-synced Nimbus on Goerli, sync can stall

Placeholder issue. Will revisit when Lighthouse:Reth can sync Goerli.

### Steps to reproduce

Not entirely sure yet. It might be just a straight sync or maybe Nimbus needs to be restarted for this to show.

### Platform(s)

Linux (x86)

### What version/commit are you on?

a7b37493121426a67176374b84de5a3e01df8401

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by rakita** [comment]
There are two improvements that are probably going to help with this.

We are now buffering block that are send from CL so reth transition is better (merged on main): https://github.com/paradigmxyz/reth/pull/2397

And this is something that I noticed on prysm node, the block status of the old finalized block was not returned properly, it is not of big importance but it should help with CL-EL interaction: https://github.com/paradigmxyz/reth/pull/2462

**Comment by yorickdowne** [comment]
I'll retest on Nimbus once #2408 is fixed and it can sync with Lighthouse. One thing at a time :)

**Comment by gakonst** [comment]
@yorickdowne is this still an issue?

**Comment by yorickdowne** [comment]
Unknown. I never got to a fully successful sync on Goerli with Lighthouse, so didn’t test Nimbus again.

I can repeat this test.

**Comment by gakonst** [comment]
Please do - Goerli + LH should work now.

**Comment by yorickdowne** [comment]
Can confirm it synced. Has an issue once at head, but that's separate.

```
reth-test-execution-1  | 2023-05-24T11:02:15.147553Z  INFO try_insert_block{block=(9055076, 0xc90e1077d18c2f454338c9966699583133044850e9cbf25ef5a185842e4173d0)}: return=Ok(Disconnected)
reth-test-execution-1  | 2023-05-24T11:02:16.120205Z  INFO make_canonical{block_hash=0xc90e1077d18c2f454338c9966699583133044850e9cbf25ef5a185842e4173d0}: Block hash not found in block indices block_hash=0xc90e1077d18c2f454338c9966699583133044850e9cbf25ef5a185842e4173d0
reth-test-execution-1  | 2023-05-24T11:02:16.120256Z  WARN Error canonicalizing the head hash error=Execution(BlockHashNotFoundInChain { block_hash: 0xc90e1077d18c2f454338c9966699583133044850e9cbf25ef5a185842e4173d0 }) state=ForkchoiceState { head_block_hash: 0xc90e1077d18c2f454338c9966699583133044850e9cbf25ef5a185842e4173d0, safe_block_hash: 0xe1c0700357cc1a46ec8313ffd6f48f31b62fe08e3f3101a4ab3505f78790e6a0, finalized_block_hash: 0x1449c26c05d4e5c7ea7c3e10c068f828f987e7cc55d531d0fd68fa7495a6e233 }
```

**Comment by mattsse** [comment]
nice,

this is indeed separate and happens when reth misses the a block in order to canonicalize the chain and needs to fetch that first, we're working on improvements rn
