### ISSUE TITLE
Retain peer reputation in the backoff process

### ISSUE THREAD

**Issue by jonasbostoen** [paradigmxyz/reth#2410]
### Describe the bug

Currently, backing off from a peer uses the same mechanism as banning a peer (slashing reputation under the threshold), but with a shorter duration. The problem is that when peers are unbanned, their reputation is reset to 0. This means that any reputation assigned to the peer before that will be lost (wether positive or negative).

I propose using a separate mechanism for backing off from peers. I see 2 ways to do this:
1. Don't modify the `Peer` reputation, but put them in the `BanList`. `fill_outbound_slots` (responsible for dialing new peers), can then just check if the peer is in the `BanList`. **Downside**: performance hit on additional map lookups cc @mattsse.
2. Add a field to `Peer` to keep track of backoffs: `backed_off: bool`. We also keep a `HashMap<PeerId, std::time::Duration>` in `PeerManager`, that we can use to keep track of backoff deadlines. We can then check this map on every `unban_interval` expiring.

I can submit a PR for this based on your feedback.

### Steps to reproduce

-

### What version/commit are you on?

main

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
That's a reasonable request, I just haven't thought about it in detail.

Option 2 is more suitable because `fn best_unconnected` is a hot path and we need to do this as efficiently as possible.
