### ISSUE TITLE
Downloader stuck penalising the same peer

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#2425]
During live sync after the engine started running the pipeline, the header downloader was penalizing the same peer for a couple of minutes. Restart fixed the issue

<img width="874" alt="Screenshot_2023-04-27_at_11 08 38" src="https://user-images.githubusercontent.com/25429261/234806055-7b25c0c0-094a-441a-898f-0afd6a8cfbd9.png">

No additional context atm

**Comment by gakonst** [comment]
Have we encountered this again?

**Comment by onbjerg** [comment]
No
