### ISSUE TITLE
proxy node penalizes other nodes for already seen transactions until they are banned 

### ISSUE THREAD

**Issue by TovarishFin** [paradigmxyz/reth#2451]
### Describe the bug

Based on an earlier chat in the telegram channel, it seems like you guys haven’t really had much of a chance to see how the tx pool works irl. Is this correct? I am mostly done with building a proxy node using reth crates and believe i have run into a possible implementation issue. I have found that its very hard to find peers due to my node penalizing all of the other nodes until they are each finally banned. I am pretty sure there are several issues:

txs not getting cleared out of the tx pool (talked about the other day). This results in the node thinking there are tons of spam accounts and penalizing other nodes for giving these “spamming” txs.

already seen txs being imported from other nodes. It seems that this happens rather often and also results in bans. This could be an issue with my implementation… but have been thinking about it for a few days and have not found anything.

So I guess my main question is how much thought went into the penalty system? And was it tested on some public chain?

This could be something I could help with relatively quickly since I am already focused on this at the moment.

I was able to trace the source of these penalties and it seemed to come from line 450 and 317 in crates/net/network/src/transactions.rs

### Steps to reproduce

n/a

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by TovarishFin** [comment]
#2450 does not resolve this issue. it is caused by bans resulting from already seen txs rather than false spam txs.

**Comment by TovarishFin** [comment]
@mattsse was planning on checking a full node's behavior with peers after fully syncing in order to ensure that this is not a proxy node issue. Additionally #2452 will help with tracking this in case there are some relaxed spec implementations on other nodes which result in this behavior.

**Comment by mattsse** [comment]
reopened,
added some logs and new metrics for this in #2467

**Comment by gakonst** [comment]
How should we proceed here? Did Matt's PRs make this better?

**Comment by TovarishFin** [comment]
I just pulled the latest changes and am still having issues with this. though this of course could be something on my side. Does the vanilla client not have any issue finding peers?

**Comment by TovarishFin** [comment]
i just pulled the latest changes and this still does not seem to help out from my side. it could be come implementation detail of my proxy. do the vanilla nodes have no issues getting and maintaining peers?

**Comment by gakonst** [comment]
It might be hard for us to help you debug this w/o a repro :/ Do you have an OSS version of your proxy? Or a minimal example?

**Comment by mattsse** [comment]
this is no longer penalized because apparently not all impls do follow this
