### ISSUE TITLE
Add missing `block.nonce == beaconNonce == 0` in consensus validation

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2455]
### Describe the feature

the default block nonce in the beacon consensus is 0, which is currently not enforced in

https://github.com/paradigmxyz/reth/blob/eb37bc7b37b853d9bd11b98ea78652e575fd9466/crates/consensus/common/src/validation.rs#L13-L17

## TODO

add check for block nonce

ref https://github.com/ethereum/go-ethereum/blob/8f373227ac481685148019b21ef9e1478d3ba609/consensus/beacon/consensus.go#L232-L235

**Comment by rakita** [comment]
The check is here: https://github.com/paradigmxyz/reth/blob/ec7a10b57e3cf97ce6d12414e2f2266338d61351/crates/consensus/beacon/src/beacon_consensus.rs#L40-L80

The check is related to TD and because of that it is separate.

**Comment by rakita** [comment]
Will close this, as check is present.

**Comment by mattsse** [comment]
ah, overlooked that!
