### ISSUE TITLE
Mention consensus in Running Reth section of book

### ISSUE THREAD

**Issue by sslivkoff** [paradigmxyz/reth#2458]
### Describe the change

The running reth section of the book should make it clear that reth requires an external consensus client. It should also give the minimal example of specifying (or maybe even setting up) this client using cli

https://paradigmxyz.github.io/reth/getting_started/running.html

**Comment by gakonst** [comment]
Reworked that here: https://paradigmxyz.github.io/reth/run/mainnet.html #2566
