### ISSUE TITLE
`apt install build-essential` in installation instructions

### ISSUE THREAD

**Issue by sslivkoff** [paradigmxyz/reth#2459]
### Describe the change

On a fresh Ubuntu 22.04 installation I needed to `apt install build-essential` in addition to the other packages listed in the Ubuntu section

I don't know if `build-essential` is present or necessary in other Ubuntu versions. But 22.04 is probably the most common version people will use for the next couple years

https://paradigmxyz.github.io/reth/getting_started/installation.html

**Comment by gakonst** [comment]
Have added build essential here https://paradigmxyz.github.io/reth/installation/source.html since #2566 - will also link to that in the README
