### ISSUE TITLE
insert new blocks into cache 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2485]
### Describe the feature

This is very similar to #2315

but should insert new blocks directly onto the caching layer so they're instantly available

https://github.com/paradigmxyz/reth/blob/1651009c191bc5ba4e7cf394f15d7209302f3221/crates/rpc/rpc/src/eth/cache.rs#L80-L80

**Comment by i-m-aditya** [comment]
I will take this.
