### ISSUE TITLE
`----p2p-secret-key` silently reverts to default location if file is not found

### ISSUE THREAD

**Issue by petertdavies** [paradigmxyz/reth#2498]
### Describe the bug

If you provide a non-existent file as `--p2p-secret-key`, it will silently revert to the default location. It should either create a new random key in the specified location or fail with a "File not found" error.

### Steps to reproduce

1. Setup Reth so that the default location for the p2p secret key is not accessible (e.g. systemd `ProtectHome=True`).
2. Set `--p2p-secret-key` to a non existent file.

This results in the following very confusing failure:

```
2023-05-01T10:40:03.457843Z  INFO reth 0.1.0 starting
2023-05-01T10:40:03.458121Z  INFO Configuration loaded path=/var/lib/ethereum/r>
2023-05-01T10:40:03.458128Z  INFO Opening database path=/var/lib/ethereum/reth
2023-05-01T10:40:03.458564Z  INFO Database opened
2023-05-01T10:40:03.479680Z  INFO Transaction pool initialized
2023-05-01T10:40:03.479699Z  INFO Connecting to P2P network
Error: An I/O error occurred: Permission denied (os error 13)
Caused by:
    Permission denied (os error 13)
Location:
    bin/reth/src/node/mod.rs:223:13
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

a887557019210ded4b75f1c5beab154577f181d4

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks for flagging.

looks like the current behavior allows fallback on error, but we should fail.

> or fail with a "File not found" error.

yes that should be the correct behaviour

**Comment by mightypenguin** [comment]
@mattsse 
Can I be assigned this issue please?

**Comment by mightypenguin** [comment]
I believe this issue OBE and should be closed.

**Comment by Rjected** [comment]
This is fixed now, closing
