### ISSUE TITLE
Remove remaining `--db` options from cli commands

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#2528]
#2495 Modified the reth directory structure to use `--datadir` for all reth data, instead of having different possible paths for the db, config, jwt secret, etc. Previously the main way users would override a data directory was from the `--db` flag.

There are still a few remaining `--db` flags, which should not be necessary any more. For example:
https://github.com/paradigmxyz/reth/blob/ec7a10b57e3cf97ce6d12414e2f2266338d61351/bin/reth/src/chain/init.rs#L24-L27

https://github.com/paradigmxyz/reth/blob/ec7a10b57e3cf97ce6d12414e2f2266338d61351/bin/reth/src/db/mod.rs#L32-L35

These arguments should be removed and replaced with the directory set by the `--datadir` flag.

**Comment by leovct** [comment]
I'd like to work on this one :)

**Comment by Rjected** [comment]
@leovct awesome! assigned :)

**Comment by Rjected** [comment]
This was fixed in #2575
