### ISSUE TITLE
Remove references to transition ids

### ISSUE THREAD

**Issue by petertdavies** [paradigmxyz/reth#2536]
### Describe the change

Transition ids were abolished and replaced with block numbers in #2275. However references to them still exist in docstrings and comments, which is quite confusing. For example the word "transition" appears 9 times in `crates/storage/provider/src/post_state.rs`.

**Comment by gakonst** [comment]
Yep - working on this next week.

**Comment by mattsse** [comment]
@onbjerg is this still the case?

**Comment by onbjerg** [comment]
Not in that file specifically, but transition IDs are still mentioned in function names and docs, e.g. here:

https://github.com/paradigmxyz/reth/blob/600f3eac8c494dfc10b628527ff87513e2381b7f/crates/storage/provider/src/providers/database/provider.rs#L258

https://github.com/paradigmxyz/reth/blob/600f3eac8c494dfc10b628527ff87513e2381b7f/crates/storage/provider/src/providers/database/provider.rs#L123

https://github.com/paradigmxyz/reth/blob/600f3eac8c494dfc10b628527ff87513e2381b7f/crates/storage/provider/src/providers/database/provider.rs#L285
