### ISSUE TITLE
Make RPC server settings configurable

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2560]
### Describe the feature

default response limit is 10MB which could be exceed (getLogs for example)

## TODO
- [x] make certain rpc settings configurable
- [ ] Add support for missing settings in: https://github.com/paradigmxyz/reth/blob/c190d0e69be52ab090e2cd8d5cb69cd72c9ac9ca/crates/rpc/rpc-builder/src/eth.rs#L26-L37

ref #2559 #2664

**Comment by i-m-aditya** [comment]
I will fix this.

**Comment by ciwines** [comment]
I'm on it
