### ISSUE TITLE
Unable to compile reth on Windows due to libmdbx compilation error

### ISSUE THREAD

**Issue by krusher55** [paradigmxyz/reth#2568]
### Describe the bug

When attempting to compile reth on Windows using the build command `cargo install --locked --path bin/reth --bin reth`, build fails with an error related to reth-mdbx-sys v0.12.1-0.

An attempt to compile libmdbx from source was made using the instructions from https://github.com/erthink/libmdbx/tree/master#windows. However, this resulted in an error indicating that GNU Make v3.81 or above is required, even though GNU Make version v4.3 was already installed. This was resolved by using CMake to build libmdbx.

### Steps to reproduce

To reproduce the error when compiling reth on Windows, follow these steps:

1. Install Rust and Cargo, if they are not already installed
2. Clone reth repository using the command `git clone https://github.com/paradigmxyz/reth`
3. Navigate to reth directory using the command `cd reth`
4. Compile reth by running `cargo install --locked --path bin/reth --bin reth`
5. Wait for the compilation process to complete
6. Observe the error message while building the reth-mdbx-sys v0.12.1-0 library in crates/storage/libmdbx-rs/mdbx-sys directory:

```
error: failed to run custom build command for reth-mdbx-sys v0.12.1-0 (C:\node\reth\reth\crates\storage\libmdbx-rs\mdbx-sys)
Caused by:
process didn't exit successfully: C:\node\reth\reth\target\release\build\reth-mdbx-sys-0b550fc8e9d06992\build-script-build (exit code: 101)
--- stderr
thread 'main' panicked at 'called Result::unwrap() on an Err value: LexError { span: bytes(126..126) }', C:\Users\Administrator.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.61.0\codegen\mod.rs:4788:66
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile reth v0.1.0 (C:\node\reth\reth\bin\reth), intermediate artifacts can be found at C:\node\reth\reth\target

```

To reproduce compiling libmdbx from https://github.com/erthink/libmdbx/tree/master#windows, follow these steps:
1. Clone repository using the command `git clone https://github.com/erthink/libmdbx`
2. Navigate to libmdbx directory using the command `cd libmdbx`
3. Compile libmdbx using make by running `make all`
4. Observe the error message

```
C:\node\libmdbx> make all
// The GNU Make 4.3
process_begin: CreateProcess(NULL, env bash -c "echo $BASH", ...) failed.
GNUmakefile:12: pipe: No error
process_begin: CreateProcess(NULL, printf %3s%3s%3s 4 3, ...) failed.
GNUmakefile:13: pipe: No such file or directory
process_begin: CreateProcess(NULL, expr "" < "  3 81", ...) failed.
GNUmakefile:14: pipe: No such file or directory
GNUmakefile:16: *** Please use GNU Make 3.81 or above.  Stop.

```
(GNU Make running on this system is v4.3, so this error is unexpected)

5. Now create a new folder called `build` in libmdbx root directory
6. Compile libmdbx using cmake by running "cmake --build . --target install".
7. Observe that libmdbx compiles successfully.

Additional notes:
- Attempted to investigate further by looking at crates/storage/libmdbx-rs and mdbx-sys to see if I could update/modify anything there, but couldn't figure out how to resolve the issue.

- It may be helpful to look into erigon - has a Makefile to build for Linux/macOS and a wmake file to build for Windows using cmake, make, and mingw to build MDBX tools (https://github.com/ledgerwatch/erigon#windows).

- rust: v1.69.0
- OS: windows 10

### Platform(s)

Windows (x86)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
We fixed Windows compilation a couple of days ago. If you still have issues, please explain what happens now as it is probably just a docs issue.
