### ISSUE TITLE
Consider removing transactionLogIndex from rpc

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2569]
### Describe the feature

it is not part of json rpc spec https://ethereum.org/en/developers/docs/apis/json-rpc/#json-rpc-methods but was present in OE:

https://github.com/openethereum/openethereum/blob/6c2d392d867b058ff867c4373e40850ca3f96969/crates/rpc/src/v1/types/log.rs#L42

ref https://github.com/paradigmxyz/reth/issues/2457

**Comment by leovct** [comment]
I'd like to work on this one 👋

**Comment by mattsse** [comment]
@gakonst should we remove this?

I'm leaning toward yes.

**Comment by gakonst** [comment]
Yeh - did it
