### ISSUE TITLE
Complete VmTrace and StateDiff tracers

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2577]
### Describe the feature

This supersedes #1862
In #2576 trace conversions for StateDiff And VmTrace were kickstarted there are still some todos

- [x] record balance and nonce in step CallTracer (record nonce, balance before, after call) for StateDiff tracer
- [ ] Implement VmTrace conversion

**Comment by nhtyy** [comment]
hi this appears to still be a valid issue after looking in main, just wanted to ping you if i can be assigned before i start working on it this weekend

**Comment by nhtyy** [comment]
but for now just to confirm i can put `balanceBefore` `balanceAfter` (or maybe just `delta`) and `nonce` on the `CallTrace` struct.. `nonce` i can find in the `EVMData` passed in during the call to `fill_trace_on_call_end`, but balance im not sure... though i can i subtract the `value` field also found in the `EVMData` to find balanceAfter...

all the other stuff i think i i got figured, and the 'hardest' part being the VMTrace conversion

**Comment by mattsse** [comment]
> and the hardest part being the VMTrace conversion

yeah this is the thing that's missing:

https://github.com/paradigmxyz/reth/blob/56674ade06fb81247b4ef51fcdae875280550207/crates/revm/revm-inspectors/src/tracing/builder/parity.rs#L223-L228

the statediffs are completed now

**Comment by nhtyy** [comment]
>the statediffs are completed now

just curious in another branch right? in `master` the nonce/balance fields seem to never be set

**Comment by mattsse** [comment]
They're set separately because not recorded in the traces see ParityBuilder impl and docs

**Comment by nhtyy** [comment]
hi @mattsse this PR is about 80-90% of the way done, only lacking filling the code field in `VmTrace` but i have an outline of the approach in the code, will finish up this weekend, in the meantime if you could review this whenever you get a chance that would be awesome, i had to add a field to `CallTraceStep`

**Comment by nhtyy** [comment]
also i need the gas cost of each opcode for one of the fields, wdyt is the best way to get this in the codebase

**Comment by gakonst** [comment]
Let's use these? https://github.com/bluealloy/revm/blob/10f81ba1b3cd6171c25d3346f1800bbb04f5ead1/crates/interpreter/src/gas/constants.rs
