### ISSUE TITLE
Prevent pipeline sync while communicating with outdated CL

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#2581]
The EL node might have a more recent state than CL. If CL issues an FCU with head that was already inserted into the database, the `make_canonical` call to `BlockchainTree` will fail, engine will proceed to trigger pipeline resync and `Headers` stage would fail while attempting to insert a known block.

 
<img width="868" alt="Screenshot_2023-05-05_at_21 04 57" src="https://user-images.githubusercontent.com/25429261/236537555-79da56b2-fb9a-45bb-aa81-f22d64118511.png">

**Comment by gakonst** [comment]
Closing optimistically - I think we fixed in an old PR (@mattsse may remember)
