### ISSUE TITLE
Execution of the mainnet block 99836 fails in `reth stage`

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#2594]
### Describe the bug

```bash
RUST_LOG=info cargo run --quiet --bin reth -- stage execution --from 99835 --to 99836
2023-05-06T12:42:49.224237Z  INFO reth 0.1.0 starting stage Execution
2023-05-06T12:42:49.224322Z  INFO Opening database path="/Users/shekhirin/Library/Application Support/reth/mainnet/db"
2023-05-06T12:42:49.229912Z  INFO Unwind iteration finished to_block=99835 unwind_progress=99835 is_final_range=true
Error: Stage encountered a execution error in block 99836: Block gas used 21506 is different from expected gas used 10792..

Caused by:
    Block gas used 21506 is different from expected gas used 10792.

Location:
    bin/reth/src/stage/mod.rs:202:64
```

### Steps to reproduce

1. Sync the node up to the problematic block for the ease of debug
```bash
reth node --debug.tip 0x241668a95fc3bfc2d104a92851f2d2005b0ffcd66f0638ddda51854464685174 --debug.max-block 99836 --debug.terminate
```
2. Run a CLI for execution stage re-executing the problematic block: 
```bash
reth stage execution --from 99835 --to 99836
```

### Node logs

I added some execution logs for this block:
```
diff --git a/crates/revm/src/executor.rs b/crates/revm/src/executor.rs
index cfc58bae..bfde2884 100644
--- a/crates/revm/src/executor.rs
+++ b/crates/revm/src/executor.rs
@@ -237,6 +237,10 @@ where
             // Execute transaction.
             let ResultAndState { result, state } = self.transact(transaction, sender)?;

+            if block.number == 99836 {
+                println!("DEBUG {:#?} {result:#?} {state:#?}", self.evm.env);
+            }
+
             // commit changes
             self.commit_changes(
                 block.number,
```

Then, I repeated the steps from `Steps to reproduce`. Here are the debug print from both commands: https://gist.github.com/shekhirin/2c16d7e7a94f73461209849975315e68

And diff:
<details>
  <summary>It's large</summary>
<pre>
DEBUG Env {							DEBUG Env {
    cfg: CfgEnv {						    cfg: CfgEnv {
        chain_id: 0x00000000000000000000000000000000000000000	        chain_id: 0x00000000000000000000000000000000000000000
        spec_id: FRONTIER,					        spec_id: FRONTIER,
        perf_all_precompiles_have_balance: false,		        perf_all_precompiles_have_balance: false,
        perf_analyse_created_bytecodes: Analyse,		        perf_analyse_created_bytecodes: Analyse,
        limit_contract_code_size: None,				        limit_contract_code_size: None,
        disable_block_gas_limit: false,				        disable_block_gas_limit: false,
        disable_eip3607: false,					        disable_eip3607: false,
        disable_base_fee: false,				        disable_base_fee: false,
    },								    },
    block: BlockEnv {						    block: BlockEnv {
        number: 0x0000000000000000000000000000000000000000000	        number: 0x0000000000000000000000000000000000000000000
        coinbase: 0x2f6bce4fc330b69c9b4c2694d57c63ec7b18fec7,	        coinbase: 0x2f6bce4fc330b69c9b4c2694d57c63ec7b18fec7,
        timestamp: 0x0000000000000000000000000000000000000000	        timestamp: 0x0000000000000000000000000000000000000000
        difficulty: 0x000000000000000000000000000000000000000	        difficulty: 0x000000000000000000000000000000000000000
        prevrandao: None,					        prevrandao: None,
        basefee: 0x000000000000000000000000000000000000000000	        basefee: 0x000000000000000000000000000000000000000000
        gas_limit: 0x0000000000000000000000000000000000000000	        gas_limit: 0x0000000000000000000000000000000000000000
    },								    },
    tx: TxEnv {							    tx: TxEnv {
        caller: 0x7cfa3d23636173a3befaabc8ca86846a07c4b3dd,	        caller: 0x7cfa3d23636173a3befaabc8ca86846a07c4b3dd,
        gas_limit: 50000,					        gas_limit: 50000,
        gas_price: 0x0000000000000000000000000000000000000000	        gas_price: 0x0000000000000000000000000000000000000000
        gas_priority_fee: None,					        gas_priority_fee: None,
        transact_to: Call(					        transact_to: Call(
            0xbcd159845b81e35a0b5aff57feccd0b3114791ab,		            0xbcd159845b81e35a0b5aff57feccd0b3114791ab,
        ),							        ),
        value: 0x00000000000000000000000000000000000000000000	        value: 0x00000000000000000000000000000000000000000000
        data: b"A\xc0\xe1\xb5",					        data: b"A\xc0\xe1\xb5",
        chain_id: None,						        chain_id: None,
        nonce: Some(						        nonce: Some(
            12,							            12,
        ),							        ),
        access_list: [],					        access_list: [],
    },								    },
} Success {							} Success {
    reason: SelfDestruct,				      |	    reason: Stop,
    gas_used: 10792,					      |	    gas_used: 21506,
    gas_refunded: 10792,				      |	    gas_refunded: 0,
    logs: [],							    logs: [],
    output: Call(						    output: Call(
        b"",							        b"",
    ),								    ),
} {								} {
    0x2f6bce4fc330b69c9b4c2694d57c63ec7b18fec7: Account {	    0x2f6bce4fc330b69c9b4c2694d57c63ec7b18fec7: Account {
        info: AccountInfo {					        info: AccountInfo {
            balance: 0x00000000000000000000000000000000000000 |	            balance: 0x00000000000000000000000000000000000000
            nonce: 7,						            nonce: 7,
            code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500	            code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500
            code: Some(					      |	            code: None,
                Bytecode {				      <
                    bytecode: b"\0",			      <
                    hash: 0xc5d2460186f7233c927e7db2dcc703c0e <
                    state: Analysed {			      <
                        len: 0,				      <
                        jump_map: JumpMap(		      <
                            BitVec<u8, bitvec::order::Lsb0> { <
                                addr: 0x0000000117f5c818,     <
                                head: 000,		      <
                                bits: 1,		      <
                                capacity: 8,		      <
                            } [				      <
                                0,			      <
                            ],				      <
                        ),				      <
                    },					      <
                },					      <
            ),						      <
        },							        },
        storage: {},						        storage: {},
        storage_cleared: false,					        storage_cleared: false,
        is_destroyed: false,					        is_destroyed: false,
        is_touched: true,					        is_touched: true,
        is_not_existing: false,					        is_not_existing: false,
    },								    },
    0x7cfa3d23636173a3befaabc8ca86846a07c4b3dd: Account {	    0x7cfa3d23636173a3befaabc8ca86846a07c4b3dd: Account {
        info: AccountInfo {					        info: AccountInfo {
            balance: 0x00000000000000000000000000000000000000 |	            balance: 0x00000000000000000000000000000000000000
            nonce: 13,						            nonce: 13,
            code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500	            code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500
            code: Some(					      |	            code: None,
                Bytecode {				      <
                    bytecode: b"\0",			      <
                    hash: 0xc5d2460186f7233c927e7db2dcc703c0e <
                    state: Analysed {			      <
                        len: 0,				      <
                        jump_map: JumpMap(		      <
                            BitVec<u8, bitvec::order::Lsb0> { <
                                addr: 0x0000000118273678,     <
                                head: 000,		      <
                                bits: 1,		      <
                                capacity: 8,		      <
                            } [				      <
                                0,			      <
                            ],				      <
                        ),				      <
                    },					      <
                },					      <
            ),						      <
        },							        },
        storage: {},						        storage: {},
        storage_cleared: false,					        storage_cleared: false,
        is_destroyed: false,					        is_destroyed: false,
        is_touched: true,					        is_touched: true,
        is_not_existing: false,					        is_not_existing: false,
    },								    },
    0xbcd159845b81e35a0b5aff57feccd0b3114791ab: Account {	    0xbcd159845b81e35a0b5aff57feccd0b3114791ab: Account {
        info: AccountInfo {					        info: AccountInfo {
            balance: 0x00000000000000000000000000000000000000 |	            balance: 0x00000000000000000000000000000000000000
            nonce: 0,						            nonce: 0,
            code_hash: 0x7806ae61c39a23d3b9cf45e46c210492e814	            code_hash: 0x7806ae61c39a23d3b9cf45e46c210492e814
            code: Some(						            code: Some(
                Bytecode {					                Bytecode {
                    bytecode: b"```@R`\xe0`\x02\n`\05\x04c.\x	                    bytecode: b"```@R`\xe0`\x02\n`\05\x04c.\x
                    hash: 0x7806ae61c39a23d3b9cf45e46c210492e	                    hash: 0x7806ae61c39a23d3b9cf45e46c210492e
                    state: Analysed {				                    state: Analysed {
                        len: 316,				                        len: 316,
                        jump_map: JumpMap(			                        jump_map: JumpMap(
                            BitVec<u8, bitvec::order::Lsb0> {	                            BitVec<u8, bitvec::order::Lsb0> {
                                addr: 0x000000011abb28e0,     |	                                addr: 0x000000010cec4090,
                                head: 000,			                                head: 000,
                                bits: 349,		      |	                                bits: 352,
                                capacity: 352,			                                capacity: 352,
                            } [					                            } [
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                1,				                                1,
                                0,				                                0,
                                1,				                                1,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                1,				                                1,
                                0,				                                0,
                                0,				                                0,
                                1,				                                1,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                1,				                                1,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                1,				                                1,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                1,				                                1,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
                                0,				                                0,
							      >	                                0,
							      >	                                0,
							      >	                                0,
                            ],					                            ],
                        ),					                        ),
                    },						                    },
                },						                },
            ),							            ),
        },							        },
        storage: {						        storage: {
            0x00000000000000000000000000000000000000000000000	            0x00000000000000000000000000000000000000000000000
                original_value: 0x0000000000000000000000007cf |	                original_value: 0x000000000000000000000000000
                present_value: 0x0000000000000000000000007cfa |	                present_value: 0x0000000000000000000000000000
            },							            },
        },							        },
        storage_cleared: false,					        storage_cleared: false,
        is_destroyed: true,				      |	        is_destroyed: false,
        is_touched: true,					        is_touched: true,
        is_not_existing: false,					        is_not_existing: false,
    },								    },
}							      \	}
</pre>
  
</details>

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

bc5e15090378c482e378d91cfbb466ad83f67505

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
Might be fixed with https://github.com/paradigmxyz/reth/pull/2602

**Comment by rkrasiuk** [comment]
This happens due to unwind of selfdestruct, we'll take care of it in a bit.

**Comment by sigridjineth** [comment]
I am sorry, but what does `0x241668a95fc3bfc2d104a92851f2d2005b0ffcd66f0638ddda51854464685174` mean in a `--debug.tip` ?

**Comment by shekhirin** [comment]
@sigridjineth block 99836 hash from the canonical chain: https://etherscan.io/block/99836

**Comment by gakonst** [comment]
@rkrasiuk @shekhirin can we close this now?

**Comment by shekhirin** [comment]
@gakonst just tested on latest main, works now.
