### ISSUE TITLE
Improve log range filter

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2621]
### Describe the feature

the current range filter loops over all blocks:

https://github.com/paradigmxyz/reth/blob/abcadd987c8049e48591a26e7ac04907b6d334d8/crates/rpc/rpc/src/eth/filter.rs#L276-L295

this will cause issues with large queries like #2585 which will take forever

instead of fetching all receipts, this should check the header's bloom first:

ref https://github.com/ethereum/go-ethereum/blob/8f373227ac481685148019b21ef9e1478d3ba609/eth/filters/filter.go#L264-L265

and only if it there could be matches read the receipts

## TODO
* rewrite loop so it reads the headers first then checks bloom

the impl should keep in mind that we need to find a tradeoff between reading batches and memory size: reading ranges of data is cheaper but should be bounded

**Comment by i-m-aditya** [comment]
I will pick this.

**Comment by mattsse** [comment]
@i-m-aditya actually I was in the wrong here so this is already the case
