### ISSUE TITLE
Implement prestateTracer

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2624]
### Describe the feature

See https://geth.ethereum.org/docs/developers/evm-tracing/built-in-tracers

This is similar to https://github.com/paradigmxyz/reth/issues/2110 but for the missing 

https://github.com/paradigmxyz/reth/blob/abcadd987c8049e48591a26e7ac04907b6d334d8/crates/rpc/rpc/src/debug.rs#L378-L380

variant

## TODO
* add conversions for the inspector for pre state frame, See #2349 for CallTrace ref

**Comment by jerusan** [comment]
I am working on this.

**Comment by mattsse** [comment]
lmk if you have any questions, 
I think we need to look closely at the geth reference impl.

**Comment by jerusan** [comment]
@mattsse I'm not sure if my method of obtaining the prestate is correct. I am thinking of making a copy of state_db before passing it to [inspect().](https://github.com/paradigmxyz/reth/compare/main...jerusan:reth:jj/implement-prestate-tracer?expand=1#:~:text=//%20let%20state_db_copy%3A%20Box%3Cdyn%20StateProvider%3E%20%3D%20db.db.into_inner()%3B) In that way, db values can be accessed after passing it to inspect(). When inspect() returns post_state, I can iterate the post_state to get the addresses affected by the transaction then I will be able to use the db_copy to get the old account state.

**Comment by mattsse** [comment]
I can bump prio for this,

**Comment by PlamenHristov** [comment]
@mattsse , mind I give it a try?

**Comment by PlamenHristov** [comment]
@0x366, there is a small bug, in how the config is parsed. Will push a fix EOD.

**Comment by PlamenHristov** [comment]
@0x366 here is the [PR](https://github.com/paradigmxyz/reth/pull/4014). Apologies for the bug.
