### ISSUE TITLE
Improve range filter performance

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2633]
### Describe the feature

Currently, the range filter fetches the entire block one by one:

https://github.com/paradigmxyz/reth/blob/041b8d320762fa04e3aba25e5fd51f93562bc9e4/crates/rpc/rpc/src/eth/filter.rs#L316-L316

this is suboptimal because we only need the body if the bloom matches

we do however need to read all the headers, this should be done first via the `headers_range` API which should be fast and then only fetch the full body via cache

## TODO
* read header range (use some reasonable chunks so that we're not reading the entire range)
* only read full body if bloom is a match (reading the full block could likely be further optimized in the caching service if we already have already have the header so we only need to read the body)

**Comment by jerusan** [comment]
I can work on this
