### ISSUE TITLE
Add gas price oracle values to CLI arguments

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2642]
### Describe the feature

gas price orcale introduced here https://github.com/paradigmxyz/reth/pull/2600

we need to make this configurable via CLI

TODO:

* check geth cli for compatibility, see (`gpo.*`) values
* add new Args struct for GPO
* integrate with rpc-builder in rpc:

need new gpo config values here:

https://github.com/paradigmxyz/reth/blob/92b557d84e6b39a695ca7e205e51dfa61ffd429d/crates/rpc/rpc-builder/src/eth.rs#L23-L25

and integrate in CLI here:
https://github.com/paradigmxyz/reth/blob/92b557d84e6b39a695ca7e205e51dfa61ffd429d/bin/reth/src/args/rpc_server_args.rs#L296-L297

**Comment by i-m-aditya** [comment]
I will fix this
