### ISSUE TITLE
Spawn blocking RPC handlers

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2643]
### Describe the feature

jsonrpsee expects all handlers to be fully async, and no blocking CPU/IO

some rpc calls currently are technically blocking like `eth_GetTransactionByHash` and all tracing calls

All of them should be spawned via taskspawner

**Comment by i-m-aditya** [comment]
I will fix this.

**Comment by chirag-bgh** [comment]
I will take this

**Comment by gakonst** [comment]
@chirag-bgh got some time to work on this asap? else would like @mattsse to prioritize as we're doing benchmarking vs other clients and this is a bottleneck rn!
