### ISSUE TITLE
Add tests for the `GasPriceOracle`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#2655]
### Describe the feature

#2600 introduced the gas price oracle, which is used to estimate gas price for recent blocks. There are currently no tests for its behavior or edge cases, so tests should be added.

The following cases would be useful to test:
 * Proper filtering of `block.beneficiary` senders
 * Ensuring we error on transactions where the `base_fee > max_priority_fee_per_gas`
 * Correct estimation when some blocks are empty or small
 * Proper filtering of transactions with fees below the `ignore_price` threshold
 * Correctly bounding very high estimations with the configured `max_price`
 * Ensure the oracle returns correct results when the history is less than the configured `max_block_history`
 * Make sure the configured percentile works properly
 * A handful of sanity check tests for regular gas estimation
 * Sanity check for fetching populated blocks depending on the configured `blocks`
 * Sanity check for `last_price` working as intended when new blocks are added

**Comment by mattsse** [comment]
marking this as complete because we now have e2e tests for this
