### ISSUE TITLE
Dynamically adjust body range per request

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2658]
### Describe the feature

currently we're using a constant block range for body requests, but the total size of the range is dynamic.

ideally all blocks should be fetched with a single request to prevent followup request for a smaller range.

Suggestion:
track it the https://github.com/paradigmxyz/reth/blob/7665e597fb0c47cabb5e61c568be5369f507b5b6/crates/net/downloaders/src/bodies/request.rs#L38-L38 how often we sent followup requests and return this as part of the future response. Then in the downloader adjust the range for new requests.
The last part is a bit hard to do because there still active request with the old (too large) block range active when we receive the response from the `BodiesRequestFuture`

we'd need some sample range sizes of mainnet between 8M-17M first

**Comment by onbjerg** [comment]
Do we do this now? @mattsse
