### ISSUE TITLE
BlockchainTree unexpectedly reverts blocks 

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#2681]
### Describe the bug

It is reported a few times, but Tree receives two FCU and unexpectedly reverts 36 blocks on the second one. 

Panic on unwinding is separate issue. 
<img width="866" alt="blocktree_36_block_unwind" src="https://github.com/paradigmxyz/reth/assets/13179220/4d3a83aa-f346-489d-ae55-884a06cd32b5">

The flow goes something like:
1. Pipeline finished
2. FCU with 0xe9 head
3. New Payload 0x2a
4. FCU with 0x2a head

### Steps to reproduce

Happens on the tip.

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by gakonst** [comment]
This was a @rkrasiuk reported issue originally, we have not observed it since then so closing optimistically.
