### ISSUE TITLE
Downloading bodies may cause a core dump

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#2683]
### Describe the bug

Sometimes when syncing from genesis to tip this core dump will be observed:

```
23-05-12T19:37:24.991244Z  INFO Stage committed progress stage=Bodies checkpoint=3000000
reth: mdbx:9847: map_resize: Assertion `size_bytes == env->me_dxb_mmap.current' failed.
Aborted (core dumped)
```

It is an assertion internally in MDBX that fails. It seems to be related to mmap resizing, which only happens during write.

This core dump has only been observed during bodies download.

The current hypothesis is:

- If the network (and disk?) is sufficiently fast, the bodies stage will be busy writing bodies to the database. When syncing from genesis, this *will* trigger a mmap resize at some point.
- While the resize is on-going, the bodies downloader (run on a separate thread) will try to query headers to send the next requests for bodies
- The opening of a read transaction (used for reading headers) on the same environment as the write transaction (used for writing bodies) causes the core dump, probably because the address space is busy with the resize from the bodies stage, and the invariant fails

Unfortunately, there is no good way to catch this error since it is an *assertion* that fails in MDBX.

This raises a couple of questions:

- Are we not allowed to have a read transaction open on the same environment that has a write transaction open? (we assumed so)
- Are there any downsides to opening the environment twice, i.e. once for the downloader (to read headers) and once for the stage (to write bodies)?
- Can we observe this in other parts of the node, e.g. if I send a lot of RPC requests while we are syncing, will we encounter the opening of a read transaction leading to a core dump?

Current solutions could be:

- Introducing a lock that is acquired when writing bodies or reading headers so they do not occur at the same time
- Catching the panic and restarting the pipeline and/or downloader

But both of these feel leaky/wrong

#### More context

We write the bodies here (using a write transaction):

https://github.com/paradigmxyz/reth/blob/85e6d9ac5b8455774eddd8c595d21110052630f5/crates/stages/src/stages/bodies.rs#L116-L146

We read the headers here when we want to send a new request for bodies (by opening a read transaction):

https://github.com/paradigmxyz/reth/blob/85e6d9ac5b8455774eddd8c595d21110052630f5/crates/net/downloaders/src/bodies/bodies.rs#L111-L128

The panic originates here:

https://github.com/paradigmxyz/reth/blob/85e6d9ac5b8455774eddd8c595d21110052630f5/crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c#L9659

https://github.com/paradigmxyz/reth/blob/85e6d9ac5b8455774eddd8c595d21110052630f5/crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c#L9847

#### Workaround

Simply restart the node.

### Steps to reproduce

1. Acquire fast internet connection
2. (Possibly acquire fast disk)
3. Sync mainnet from genesis to tip
4. Observe the core dump

### Platform(s)

Linux (x86), Mac (Intel), Mac (Apple Silicon)

### What version/commit are you on?

85e6d9ac5b8455774eddd8c595d21110052630f5

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by gakonst** [comment]
The maintainer of MDBX shared in the Reth chat that updating to latest MDBX solves this issue 👍

**Comment by onbjerg** [comment]
Ah great, hopefully that's it 🙏

**Comment by gakonst** [comment]
Yikes! Can you please share logs and extra context? We haven't seen this bug since we bumped MDBX.
