### ISSUE TITLE
perf/refactor: use PollSender for ActiveSession messages

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2695]
### Describe the feature

to apply backpressure, we store the latest message if the channel is currently at capacity

https://github.com/paradigmxyz/reth/blob/2436e019c68e10ce384989a6d19e74dc840ba3c3/crates/net/network/src/session/active.rs#L80-L81

and only continue if we can make progress:

https://github.com/paradigmxyz/reth/blob/2436e019c68e10ce384989a6d19e74dc840ba3c3/crates/net/network/src/session/active.rs#L543-L546

waking the tasking is essentially a busy loop until there's capacity again, which is suboptimal.

there's a util type for this:

https://docs.rs/tokio-util/0.7.8/tokio_util/sync/struct.PollSender.html

using PollSender would require some refactoring effort because currently, we rely on `.clone().try_send` to always deliver a critical message, which I guess is susceptible to a race condition where the new slot that clone creates is immediately occupied by another message from another task.

## TODO
* integrate `PollSender` in `ActiveSession`

**Comment by i-m-aditya** [comment]
I will fix this.

**Comment by cbrit** [comment]
Do we want `PollSender` implemented in other sender than the `MetricSender` which is used by the `ActiveSession`?

Further, `PollSender` doesn't error except on a closed connection. Do we increment `send_errors` if the channel is full (but no error is returned)?

**Comment by cbrit** [comment]
I've been looking at this; since a failed send due to backpressure does not result in an error when using `tokio_utils::sync::PollSender`, should the `MetricSender` still count an error?
