### ISSUE TITLE
replace `ValidationError` string with `PayloadValidationError` enum

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2720]
### Describe the feature

use predefined errors for 

https://github.com/paradigmxyz/reth/blob/fd5a1ef4a8618315ab58f03b57c5e2b7fbad7af1/crates/rpc/rpc-types/src/eth/engine/payload.rs#L336-L339

with

https://github.com/paradigmxyz/reth/blob/fd5a1ef4a8618315ab58f03b57c5e2b7fbad7af1/crates/rpc/rpc-types/src/eth/engine/payload.rs#L400-L416

blocked by https://github.com/paradigmxyz/reth/pull/2712

requires error conversion after 2712

**Comment by chirag-bgh** [comment]
@mattsse is this still blocked? If not I'm willing to take this up.

**Comment by mattsse** [comment]
cool!

this is no longer blocked, no.

we need a proper conversion here.

I'd appreciate if we could bring #2750 over the line first, looks like this is almost ready?
