### ISSUE TITLE
perf/test: run malformed header test separately

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2723]
### Describe the feature

currently we're running

https://github.com/paradigmxyz/reth/blob/352b55dc0593a2a88e14e7e894079160aeb74010/crates/storage/codecs/derive/src/arbitrary.rs#L46-L54

per proptest, which is a bit expensive,

instead we should generate a new test case that only runs this on a single random instance.

## TODO
* generate a separate test case for rlp malformed header check to speed up CI

**Comment by chirag-bgh** [comment]
I will take this.
