### ISSUE TITLE
Hive engine: incorrect error code on `getBlockByNumber`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#2733]
### Describe the bug

The `safe Block after New SafeBlockHash` and `finalized Block after New FinalizedBlockHash` fail because there is an incorrect error code after `eth_getBlockByNumber`:
```
>> (8fba0727) {"jsonrpc":"2.0","id":1,"method":"eth_getBlockByNumber","params":["safe",false]}
<< (8fba0727) {"jsonrpc":"2.0","result":null,"id":1}
DEBUG (safe Block after New SafeBlockHash): Failed `Expect*` routine called from: file=/source/suites/engine/tests.go, line=2573
FAIL (safe Block after New SafeBlockHash): Expected error code on HeaderByNumber: want=-39001, got=0
```

### Steps to reproduce

Run hive:
```
./hive --client reth --sim "ethereum/engine" --sim.limit "engine-api/finalized Block after New FinalizedBlockHash"
./hive --client reth --sim "ethereum/engine" --sim.limit "engine-api/safe Block after New SafeBlockHash"
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
Assuming still relevant

**Comment by mattsse** [comment]
@Rjected 

it's this

https://github.com/mattsse/hive/blob/master/simulators/ethereum/engine/suites/engine/tests.go#L2571-L2573

but I have no idea where the 39001 is coming from...

**Comment by Rjected** [comment]
This test does not seem to exist any more, closing
