### ISSUE TITLE
Return `ACCEPTED` on otherwise valid non-canon `newPayload`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#2734]
### Describe the feature

When we receive a `newPayload` whose parent is not an ancestor of the canonical head, we should behave according to the [engine API spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md#engine_newpayloadv1) with respect to payload validation:
> * Client software MAY NOT validate the payload if the payload doesn't belong to the canonical chain.

And return a response according to the spec:
> Client software MUST respond to this method call in the following way:
> * `{status: ACCEPTED, latestValidHash: null, validationError: null}` if the following conditions are met:
>   * the blockHash of the payload is valid
>   * the payload doesn't extend the canonical chain
>   * the payload hasn't been fully validated
>   * ancestors of a payload are known and comprise a well-formed chain.

**Comment by Rjected** [comment]
Worth noting that we might need a way to extend the canonical tip in general, and calculate the root on this extended chain, rather than e.g. just one block descending from the tip. But for now we can just implement this behavior for extending the canonical chain by a single block.

**Comment by Rjected** [comment]
Sort of confused myself with the "payload doesn't extend the canonical chain" statement - does a payload that extends the `safe` block extend the canonical chain? or just a payload that extends the current head?

**Comment by onbjerg** [comment]
Assuming still relevant
