### ISSUE TITLE
Integrate Sealedblock to BeaconConsensusEngineEvent

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2759]
### Describe the feature

consumes of this event type 

https://github.com/paradigmxyz/reth/blob/238eea37cf23bd212823d76d2d07065a59ce7e2a/crates/consensus/beacon/src/engine/event.rs#L5-L6

may be interested in the block itself, for example, we should insert all transactions of a valid/accepted block into the pool.

## TODO
* add block to event (Arc)
* integrate here https://github.com/paradigmxyz/reth/blob/238eea37cf23bd212823d76d2d07065a59ce7e2a/crates/consensus/beacon/src/engine/mod.rs#L713-L715

**Comment by chirag-bgh** [comment]
I will take this.
