### ISSUE TITLE
Use consistent pending block in RPC/Blockchaintree

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2762]
### Describe the feature

In RPC, when we receive a `Pending` block request we reach out to the blockchaintree to send us a block that extends the canonical (latest) block.

The pending block is determined here:

https://github.com/paradigmxyz/reth/blob/238eea37cf23bd212823d76d2d07065a59ce7e2a/crates/blockchain-tree/src/block_indices.rs#L72-L78

all children of the canonical block are tracked here:

https://github.com/paradigmxyz/reth/blob/238eea37cf23bd212823d76d2d07065a59ce7e2a/crates/blockchain-tree/src/block_indices.rs#L23-L25

this means that, if there is more than 1 pending block (blocks that have the canonical block as parent) then the order is random.
So two RPC calls with `Pending` can use different blocks if a new pending block was received in the meantime.

I think we can simply always use the first block here? so we'd need to replace the hashset with something that tracks insert order.

we don't expect this list to be large, so perhaps a wrapper type around Vec is sufficient here.

**Comment by chirag-bgh** [comment]
I can take this.

**Comment by mattsse** [comment]
cool,

btw, any update on this https://github.com/paradigmxyz/reth/pull/2750 ? this looks almost ready

**Comment by chirag-bgh** [comment]
> btw, any update on this #2750 ? this looks almost ready

will complete this asap
