### ISSUE TITLE
Docker monitoring not available on Ubuntu 20.04

### ISSUE THREAD

**Issue by Sabnock01** [paradigmxyz/reth#2774]
### Describe the bug

When running a combined reth and lighthouse instance on Ubuntu 20.04 and running the provided `etc/dockermonitoring.yml` the endpoints show as `Down` in the Prometheus dashboard (`localhost:9090/targets`) and the provided Grafana dashboard is empty. The metrics can still be fetched from `127.0.0.1:9000` successfully. Prometheus still seems to be scraping however as the interval is never > ~5 seconds but the endpoints nonetheless are listed as `Down`
![image](https://github.com/paradigmxyz/reth/assets/24715302/151fde25-f981-4168-8a2b-7efcc8655f70)

At @shekhirin 's suggestion, I tried changing the `host.docker.internal:9000` endpoint to `172.17.0.1:9000` but the issue persists.
![image](https://github.com/paradigmxyz/reth/assets/24715302/7010646a-86aa-45f0-a1cc-224fcec80128)

My Docker version is `23.0.5`

### Steps to reproduce

Steps to reproduce:

1. Start reth: `RUST_LOG=info cargo run node --authrpc.jwtsecret ~/.local/share/reth/mainnet/jwt.hex --authrpc.addr 127.0.0.1 --authrpc.port 8551 --http --metrics 127.0.0.1:9000`
2. Start lighthouse: `RUST_LOG=info lighthouse bn --port 9001 --network mainnet --checkpoint-sync-url https://mainnet.checkpoint.sigp.io --execution-endpoint http://localhost:8551 --execution-jwt ~/.local/share/reth/mainnet/jwt.hex --http`
a. In this case, lighthouse uses port `9000` for ENR so we use the `--port` flag to specify use of `9001` instead
3. Run Docker monitoring: `docker compose -p reth -f ./etc/docker-monitoring.yml up`
4. Check that database is growing `cargo run db stats`
5. Check that metrics are available: `curl 127.0.0.1:9000`
6. Check Prometheus dashboard by navigating to `localhost:9090/targets`
7. Check Grafana dashboard by navigating to `localhost:3000` and navigating to Dashboards -> reth

### Platform(s)

Linux (x86)

### What version/commit are you on?

041b8d320762fa04e3aba25e5fd51f93562bc9e4

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by samtvlabs** [comment]
I would love to pick this up

**Comment by Sabnock01** [comment]
While the docs used `--metrics 127.0.0.1:9000` I was able to get this to work with `--metrics 0.0.0.0:9000`..

Will close this issue.

**Comment by shekhirin** [comment]
@Sabnock01 nice! Did it work through `localhost:9000` or `host.docker.internal:9000` Prometheus target?
