### ISSUE TITLE
IPC cannot compile on Windows

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#2777]
### Describe the bug

The IPC crate depends on `UnixStream` which is not available on Windows

https://github.com/paradigmxyz/reth/blob/352b55dc0593a2a88e14e7e894079160aeb74010/crates/rpc/ipc/src/client.rs#L13

On Windows we should use named pipes instead (https://docs.rs/tokio/latest/tokio/net/windows/named_pipe/index.html)

### Steps to reproduce

Try cross compiling using `cargo install cross`:

`cross build --target x86_64-pc-windows-gnu`

Notice that the IPC and mdbx crates will not compile (separate issue)

### Platform(s)

Windows (x86)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by gakonst** [comment]
@mattsse didn't we solve this on ethers-rs?

**Comment by mattsse** [comment]
I checked and this only affects the client implementation which we only use for testing, ignored this in #2785 until have a windows specific impl for this #2786
