### ISSUE TITLE
Add windows Ipc Client implementation 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2786]
### Describe the feature

See https://github.com/paradigmxyz/reth/pull/2785

the `IpcClientBuilder::build` returns A sender and receiver that are used to send and receive ipc messages https://github.com/paradigmxyz/reth/blob/c421aeca7f717f915019288fb0352ffcd0872c91/crates/rpc/ipc/src/client.rs#L102-L102
For windows we need types that use named pipes

## TODO

* add Sender + Receiver types that use named pipes instead https://docs.rs/tokio/latest/tokio/net/windows/named_pipe/index.html
* add windows `IpcClientBuilder::build` variant

See https://github.com/paradigmxyz/reth/blob/c421aeca7f717f915019288fb0352ffcd0872c91/crates/rpc/ipc/src/client.rs#L38-L42

**Comment by PatStiles** [comment]
Want to give this a shot!
