### ISSUE TITLE
Add reth-config crate with all config (reth.toml) types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2809]
### Describe the feature

Config currently resides in 

https://github.com/paradigmxyz/reth/blob/5039122c356f20d36e3d5979f0da97a2fc40ac75/crates/staged-sync/src/config.rs#L12-L23

we want a standalone crate that provides all config types.

## TODO
- [ ] add reth-config crate
- [ ] move Config struct to reth-config

ref #2514

**Comment by chirag-bgh** [comment]
I will take this.

**Comment by bowenyou** [comment]
I can try taking this issue. Just to confirm, only the `Config` struct should be moved? Or all the structs in the file should be moved?

**Comment by mattsse** [comment]
> Or all the structs in the file should be moved?

not exactly set on this yet, wdyt @onbjerg ?

I guess we have two options:
1. config create defines all config types used by reth crates
2. config create imports all config types from other reth crates

I feel like 2 is cleaner

**Comment by bowenyou** [comment]
I can proceed with 2 for now. Should be straightforward to change to 1 if need be.
