### ISSUE TITLE
Add helper enum for table name

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2835]
### Describe the feature

ref #2772

https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/db/get.rs#L13-L15

## TODO
* add a helper enum type with tables as variants with `FromStr` impl (perhaps good idea to put this here:  https://github.com/paradigmxyz/reth/blob/main/crates/storage/db/src/tables/mod.rs#L54-L54

**Comment by Majchrzak** [comment]
Can I take this one?
