### ISSUE TITLE
Add duptable support for `reth db get`

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#2836]
### Describe the feature

`reth db get` does not currently support duptables but it would be nice if it did

### Additional context

https://github.com/paradigmxyz/reth/pull/2772#pullrequestreview-1436354459

**Comment by dragan2234** [comment]
Hey I would be interested in trying to solve this issue :)

**Comment by onbjerg** [comment]
Thanks! I've assigned you to the issue. If you feel stuck, open up a draft PR with your questions and someone will help you. If you are prevented from solving the issue, let me know and I will unassign you :smile:

**Comment by pyropy** [comment]
This seems stale, can I take over this one?
