### ISSUE TITLE
Don't send `BeaconConsensusEngineEvent` for payloads the tree has already seen

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2843]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/main/crates/consensus/beacon/src/engine/mod.rs#L720-L720

can be called by CL (or multiple CLs) and the full block downloader for the same block

we check if the payload is already included (a duplicate) which should be represented in the `BlockStatus` variant.

so something like

```rust
enum InsertPayloadOk {
   AlreadySeen(BlockStatus),
   Inserted(BlockStatus)
}
```

**Comment by mattsse** [comment]
cool, this check is essentially here

https://github.com/paradigmxyz/reth/blob/0e9c05781e8801b4e10d2aeb21f24d1c5e045af4/crates/blockchain-tree/src/blockchain_tree.rs#L673-L674

**Comment by gakonst** [comment]
![image](https://github.com/paradigmxyz/reth/assets/17802178/cc5be7f1-df05-4b33-9721-549fac4053c6)
just repro'ed this, @chirag-bgh are you still planning on taking this

**Comment by chirag-bgh** [comment]
> just repro'ed this, @chirag-bgh are you still planning on taking this? no worries if not, would just like to get over the line

Hey, no I'm not.
