### ISSUE TITLE
Only open a single db transaction in provider impls

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2871]
### Describe the feature

See also #2870

For example the block provider function

https://github.com/paradigmxyz/reth/blob/689d869b8b43c429d2e91165cebe4382b29f9741/crates/storage/provider/src/providers/database.rs#L210-L218

opens 3 transactions, by reusing the existing functions for convenience.

This should be rewritten with standalone functions that accept a transaction, or even an extension trait for `DbTx` trait

**Comment by gakonst** [comment]
IMO we Def want the extension traits for DbTx
