### ISSUE TITLE
Execution does not respect max block parameter

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#2912]
## Description

Currently, it is impossible to position the node and its plain state at a specific block, because the `Execution` stage does not respect the max block parameter. 

## Solution

Pass the max block parameter to the execution stage and, if present, use it to decide the max block where the stage should terminate.

**Comment by onbjerg** [comment]
Set here https://github.com/paradigmxyz/reth/blob/2bc5e19edb49bd9a4a8c441f65958ae99cc01d02/crates/consensus/beacon/src/engine/mod.rs#L1652 which is then used as the target block for the stage instead of the highest block of the stage prior
