### ISSUE TITLE
Complete StateDiff tracing impl

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2919]
### Describe the feature

StateDiff tracing is not really documented

> stateDiff State difference. Provides information detailing all altered portions of the Ethereum state made due to the execution of the transaction.

But it looks like this represents the diff before the tx vs after tx which is the entire changed `State`: `HashMap<B160, Account>`

so the current conversion impl needs some work:

https://github.com/paradigmxyz/reth/blob/3347da091fa6c8e5f14a34cdc71dda09b721a445/crates/revm/revm-inspectors/src/tracing/builder/parity.rs#L104-L108

## TODO
* this function needs the `res.state` as input from here: https://github.com/paradigmxyz/reth/blob/3347da091fa6c8e5f14a34cdc71dda09b721a445/crates/rpc/rpc/src/trace.rs#L120-L123
* then we need a mapping from `HashMap<B160, Account>` to `AccountDiff`, a lot of the logic from  https://github.com/paradigmxyz/reth/blob/3347da091fa6c8e5f14a34cdc71dda09b721a445/crates/revm/revm-inspectors/src/tracing/types.rs#L223-L227 can be reused
* we also need to record the initial balances of all touched accounts this can be done separately because it is not supported in revm

**Comment by gakonst** [comment]
cc @rakita who may have insight on this from his previous work on OE
