### ISSUE TITLE
Add `rpc_` namespace

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2923]
### Describe the feature

This namespace provides a single function `rpc_modules` which returns the list of all available modules on that transport and their version, simply 1.0:

```
  "result": {
        "txpool": "1.0",
        "trace": "1.0",
        "eth": "1.0",
        "web3": "1.0",
        "net": "1.0"
    }
```

## TODO
* add new `RPC` variant
* add handler for that namespace
* integrate in rpc-builder

**Comment by TechieBoy** [comment]
I can take this one

**Comment by mattsse** [comment]
cool lmk if you need some pointers but here are the steps necessary:

* add new RethRpcModule variant
* add rpc trait
* add an impl, a struct that simply wraps a `HashMap<String,String>`
