### ISSUE TITLE
Make chain canonical if new payload is the missing block for current sync target

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2944]
### Describe the feature

scenario:

1. FCU -> Disconnected(missing_parent) -> start downloading missing parent
2. new payload == missing_parent -> make canonical

blocked by #2941 which adds the functionality required by this

FYI @Rjected

**Comment by int88** [comment]
I'd like to try if this is not fixed :) @mattsse

**Comment by mattsse** [comment]
cool!

this should be attempted here:

https://github.com/paradigmxyz/reth/blob/46dd5b8482d6257e7d306b8284668ae34e0bb375/crates/consensus/beacon/src/engine/mod.rs#L836-L840

basically: if the inserted payload is the head hash, we can make it canonical, this scenario can happen if the CL sends us a FCU first and the new payload afterward

**Comment by int88** [comment]
The most naive way to fix is add:

```rust
self.try_make_sync_target_canonical(block.num_hash());
```

before `self.sync.cancel_full_block_request(block_hash);`

Maybe some judgment conditions can be added to further optimize.

WDYT :) @mattsse

**Comment by mattsse** [comment]
> basically: if the inserted payload is the head hash, we can make it canonical,

this should be a simple check
