### ISSUE TITLE
Node Dies OOM while syncing

### ISSUE THREAD

**Issue by argakiig** [paradigmxyz/reth#2965]
### Describe the bug

Left node running after a full five day sync. Was able to reach the head from when it was started and was about 40k blocks behind due to the 5 day lag, during the catch up of those 40k blocks the node went OOM

### Steps to reproduce

1. Sync node from scratch
2. Wait for node to reach head
3. wait for node to start to catch back up
4. node died oom

### Node logs

```text
-06-02T08:10:15.361362Z  INFO Block added to canonical chain number=17391751 hash=0x608d59cce073dd58258d7097146e509748652caefab7e3771b75116f777bab94
2023-06-02T08:10:23.624262Z  INFO Status connected_peers=84 stage=None checkpoint=17391223
Killed
```

dmesg -T
```
[Fri Jun  2 08:09:50 2023] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=containerd.service,mems_allowed=0-1,global_oom,task_memcg=/user.slice/user-1000.slice/session-226.scope,task=reth,pid=177340,uid=1000
[Fri Jun  2 08:09:50 2023] Out of memory: Killed process 177340 (reth) total-vm:4535117128kB, anon-rss:117120184kB, file-rss:3072kB, shmem-rss:0kB, UID:1000 pgtables:4502428kB oom_score_adj:0
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

a441c136e3c2de83a4ee5deb6f6ef544669e88b9

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
Hi @argakiig, can you please share the specs of your node?

It is also worth noting that we have made some improvements to the memory profile of the downloading stages lately, but there might also be breaking changes so if you are willing to resync it should be better now.

**Comment by argakiig** [comment]
> Hi @argakiig, can you please share the specs of your node?
> 
> It is also worth noting that we have made some improvements to the memory profile of the downloading stages lately, but there might also be breaking changes so if you are willing to resync it should be better now.
> 

Dual e5-2670s, 128gb ddr3 ecc ram and dual sata in raid 0, can definitely try another sync

**Comment by argakiig** [comment]
have not been able to reproduce on an recent builds closing, Thanks
