### ISSUE TITLE
Give more info in `web3_clientVersion`, particularly the commit hash

### ISSUE THREAD

**Issue by sslivkoff** [paradigmxyz/reth#2976]
### Describe the feature

For the `web3_clientVersion` rpc method:
- erigon outputs `erigon/2.43.0/linux-amd64/go1.20.3`
- reth outputs `reth/v0.1.0/x86_64-unknown-linux-gnu`

For reth it would be nice to include more info. Including a commit hash prefix would be extremely helpful, particularly since reth is under active development.

Getting fancy could maybe also include abbreviations of major compile flags or runtime cli args

**Comment by 0xJepsen** [comment]
Down to tackle this if i can have some more information.

**Comment by mattsse** [comment]
I'm actually not sure about the commit hash,
not sure we want to leak that.
This usually mirrors the client version used in p2p

wdyt @gakonst

**Comment by gakonst** [comment]
Yes on same as p2p

**Comment by sslivkoff** [comment]
how about leaking the commit when it's not a tagged commit? that would be useful for dev situations but would it would just leak tagged version # for most users
