### ISSUE TITLE
Sender Recovery Stage - Possible Degradation

### ISSUE THREAD

**Issue by 0xlagrange** [paradigmxyz/reth#3028]
### Describe the bug

While syncing on commit #2967 (June 2), the sender recovery stage ran in ~5hrs on a is4gen.2xlarge EC2 instance with 8vCPUs, 48GB mem, and 1 7.5TB NVMe SSD. However, when I was recently syncing on commit #2844 (June 5) with a fresh instance (same type and specs), the sender recovery stage took ~13hrs and maxed all 8 CPUs.

![IMAGE 2023-06-06 16:05:40](https://github.com/paradigmxyz/reth/assets/107195066/56f04d1b-f69a-4a8b-b2ca-1b5403c971c2)

<img width="593" alt="Screenshot 2023-06-06 at 4 06 17 PM" src="https://github.com/paradigmxyz/reth/assets/107195066/6976c409-bfcc-406b-b75b-4e3064bb03cf">

### Steps to reproduce

On both instances:

RUSTFLAGS="-C target-cpu=native" cargo build --profile maxperf

RUST_LOG=info nohup reth node --authrpc.jwtsecret /NVMe/.secrets/jwt.hex --datadir /NVMe/data/reth/ --metrics 127.0.0.1:9111 -vvvvv > /NVMe/logs/reth.log 2>&1 &

### Platform(s)

Linux (ARM)

### What version/commit are you on?

#2844

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by valo** [comment]
I backed up my DB running on `main` and started a new sync from commit https://github.com/paradigmxyz/reth/tree/8c5379984b5068897cc462847d0730dc9032ef76. I'll report back in 12h

**Comment by valo** [comment]
Syncing on https://github.com/paradigmxyz/reth/tree/8c5379984b5068897cc462847d0730dc9032ef76 yields this rate for the SenderRecovery stage. The speed looks quite similar, may be at most 10% faster. So I can't reproduce a major performance degradation. 

![image](https://github.com/paradigmxyz/reth/assets/47639/fe3026fe-897c-4d2a-8739-1d3e6e466a1c)
