### ISSUE TITLE
`debug_traceTransaction` `enableReturnData` should be ignored for RPC responses

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3032]
### Describe the feature

the response type `StructLogRes` doesn't even include a `returnData` field, and this is only used for local debugging.

It should simply be ignored so we don't capture return data that we don't need

it's only used for `debug_standardTraceBlockToFile` and `debug_standardTraceBadBlockToFile` rpc calls

## TODO
* document extra fields in `StructLog` type (`StructLogRes`)
* ignore `enableReturnData` setting for regular `debug_trace` calls that return RPC 

is this correct @shekhirin ?

**Comment by shekhirin** [comment]
Yes, that sounds right!

**Comment by shekhirin** [comment]
@mattsse is this still relevant?

**Comment by mattsse** [comment]
yeah, the pr is still blocked because revm pr is not included in the patch.
I could finish it though with some extra code though, I think I'll just do that

**Comment by supernovahs** [comment]
Can I take this

**Comment by mattsse** [comment]
actually, since enableReturnData is opt-in, it would be more effort to remove support for it in the regular rpc calls
