### ISSUE TITLE
`cargo test --workspace` fails one test

### ISSUE THREAD

**Issue by twtaylor** [paradigmxyz/reth#3035]
### Describe the bug

For some reason, on `main@e1392a67d0666b83e00716877bace45b912e427f` fails 1 test when running `cargo test --workspace` on a fresh install on an M2 Max MacBook Pro. When running with:

`cargo test --workspace -p reth-ecies --lib`

The output is: 

```
test stream::tests::can_write_and_read ... FAILED
test algorithm::tests::communicate ... ok
test algorithm::tests::eip8_test ... ok

failures:

---- stream::tests::can_write_and_read stdout ----
thread 'stream::tests::can_write_and_read' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 48, kind: AddrInUse, message: "Address already in use" }', crates/net/ecies/src/stream.rs:156:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    stream::tests::can_write_and_read

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `-p reth-ecies --lib`
```

### Steps to reproduce

`cargo test --workspace -p reth-ecies --lib`

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

e1392a67d0666b83e00716877bace45b912e427f

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks!

fixed here https://github.com/paradigmxyz/reth/pull/3036
