### ISSUE TITLE
Known ChainSpecs should be Arc

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3064]
### Describe the feature

we already have them as lazy:
https://github.com/paradigmxyz/reth/blob/7cc69d52c6017eeb4348c824a9f5369400e331d1/crates/primitives/src/chain/spec.rs#L16-L16

they should be `Lazy<Arc<ChainSpec>> for convenience and so we don't need an additional instance when we configure `Arc<ChainSpec>`

FYI @joshieDo

**Comment by 0xJepsen** [comment]
can i do this?

**Comment by mattsse** [comment]
I think this will be integrated in #3034 since this touches a lot of the code

**Comment by 0xJepsen** [comment]
oh damn, I was able to make all the changes here. It did touch a lot of code but i enjoyed learning the code base a bit. You can close if will be done in #3034, or if you see any problems with how i did this. 
https://github.com/paradigmxyz/reth/pull/3075
