### ISSUE TITLE
Support queuing multi-block downloads and executing ranges of blocks after a forkchoice update

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#3117]
### Describe the feature

Currently we only support queuing single block downloads via the `FullBlockDownloader`. With #3059 we will have a heuristic for the number of blocks that need to be downloaded and executed to validate a forkchoice update. This is done by first fetching the head or safe block hash, and comparing the block number with the latest valid finalized block.

Instead of downloading the missing blocks one-by-one, we should support requesting ranges of blocks, since #3059 will already use the block number range to determine whether or not we should run the pipeline. This is more efficient than traversing the missing parents one-by-one.

**Comment by onbjerg** [comment]
Closed in #3416
