### ISSUE TITLE
Store headers or block numbers for valid forkchoice states 

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#3118]
### Describe the feature

The `ForkchoiceStateTracker` tracks the latest `VALID` forkchoice state, latest `SYNCING` forkchoice state, and the latest overall forkchoice state received:
https://github.com/paradigmxyz/reth/blob/f55d88b8c4c78c6a42c2d31dc08659e7a608e31e/crates/consensus/beacon/src/engine/forkchoice.rs#L4-L16

Validating a forkchoice state requires having the entire header, so we should be able to include either full sealed headers for the latest valid forkchoice state, or a `BlockNumHash`.

**Comment by onbjerg** [comment]
Ping @Rjected on this one, close or keep? If keep, add the `M-prevent-stale` label

**Comment by Rjected** [comment]
closing this one, not sure it's really needed for anything atm
