### ISSUE TITLE
increase max response size for engine rpc handler

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3131]
### Describe the feature

>  Failed to update deposit cache: GetDepositLogsFailed("eth_getLogs call failed ServerMessage { code: -32008, message: \"Response is too big\" }"), retry_millis: 60000, service: deposit_contract_rpc

we should increase memory settings for engine rpc server

**Comment by 0xJepsen** [comment]
Where are the memory settings configured? I'm poking around the `./crates/rpc/rpc-engine-api/src/engine_api.rs` and the error files.

**Comment by mattsse** [comment]
See 

https://github.com/paradigmxyz/reth/blob/39c6b22829a3c7f420fba4c72f48ec340c73c1cf/bin/reth/src/args/rpc_server_args.rs#L455-L455

and compare this to

https://github.com/paradigmxyz/reth/blob/39c6b22829a3c7f420fba4c72f48ec340c73c1cf/bin/reth/src/args/rpc_server_args.rs#L404-L410

I realized we actually need the `AuthServerConfig` to also provide fields for configuring `ServerBuilder`
