### ISSUE TITLE
Add "includingLog": bool to `callTracer`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3158]
### Describe the feature

ref 

https://github.com/ethereum/go-ethereum/issues/25967

this will add logs to the output

```
       "logs": [
          {
            "topics": [
              "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
              "0x000000000000000000000000aaa4940aa878d932d3482bf1de332e1d50c15aaa",
              "0x000000000000000000000000f35875a064cdbc29d7174f5c699f1ebeaa407036"
            ],
            "data": "0x0000000000000000000000000000000000000000000000000000000000000001"
          }
        ]
```

we already can do this via the Tracing inspector and can include them in the response

https://github.com/paradigmxyz/reth/blob/781d786e8d2f2de9b9e97e0e3748482d1815ec1e/crates/revm/revm-inspectors/src/tracing/builder/geth.rs#L103-L106

we already have the logs field:

https://github.com/paradigmxyz/reth/blob/0d691fee1697d18155cd23ccde0f1949ee90a289/crates/revm/revm-inspectors/src/tracing/types.rs#L383-L383

and we already record the logs:

https://github.com/paradigmxyz/reth/blob/0d691fee1697d18155cd23ccde0f1949ee90a289/crates/revm/revm-inspectors/src/tracing/mod.rs#L326-L327

**Comment by Vid201** [comment]
This parameter is called `withLog`, not `includingLog` (https://geth.ethereum.org/docs/developers/evm-tracing/built-in-tracers#config)

**Comment by mattsse** [comment]
you're right,

hehe yeah we're already doing this -.-

https://github.com/paradigmxyz/reth/blob/017c9cea9c1685baaab925923d443c3e97769dde/crates/revm/revm-inspectors/src/tracing/types.rs#L390-L401
