### ISSUE TITLE
Use dedicated metrics types for both headers+bodies downloaders

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3166]
### Describe the feature

atm both downloaders use the same metrics type 

https://github.com/paradigmxyz/reth/blob/3bba41a209e308abdbe8e88f601f365566befa7d/crates/net/downloaders/src/metrics.rs#L22-L22

but their implementation and their used metric values differ which is very confusing: #3165

## TODO
* split the type in two so each stage uses a dedicated type

**Comment by Autoparallel** [comment]
I'm looking at this now, but I'm not sure where to start. Are you suggesting making a `DownloaderMetricsHeaders` and `DownloaderMetricsBodies`?
