### ISSUE TITLE
Crate `reth-staged-sync` should be deprecated

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#3212]
### Describe the feature

The only remaining consumer of `reth-staged-sync` crate is the CLI, it uses the db initialization helper functions. We can probably move these helpers into the `bin/reth` itself.

Also, we have the Geth peering test in there, which also needs to be moved somewhere else: https://github.com/paradigmxyz/reth/blob/94d0f3e9edcee6bf825d5b349d889f6ef562d1dd/crates/staged-sync/tests/sync.rs#L19

**Comment by Evalir** [comment]
hey! would love to do this this week. to summarize:
- remove `reth-staged-sync` crate, move the used funcs to `bin/reth`
- move the geth peering test somewhere appropiate (was thinking the `net` crate would be a cool place)

**Comment by rkrasiuk** [comment]
1. imo `can_peer_with_geth` should be an it test in `net` crate
2. idk where to put clique. prob alongside the test above 
3. everything else can go in `bin`
4.
