### ISSUE TITLE
`trace_call` uses incorrect gas limit when it's not provided in the input

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#3218]
### Describe the bug

When no `gas` is provided in the `trace_call` tx object (first input argument), we derive it from the block the call is executed at (third input argument): https://github.com/paradigmxyz/reth/blob/d6092cf1d3bf6dcd274815ce12c15726293a529b/crates/rpc/rpc/src/eth/api/transactions.rs#L541 while both geth and Erigon uses the pre-configured constant of 50 million:
https://github.com/ledgerwatch/erigon/blob/eae2d9a79cb70dbe30b3a6b79c436872e4605458/cmd/rpcdaemon/commands/trace_adhoc.go#L956
https://github.com/ledgerwatch/erigon/blob/eae2d9a79cb70dbe30b3a6b79c436872e4605458/eth/ethconfig/config.go#L94

Reth's behaviour seems to be logically correct, as we inherit the whole environment from the specified block we trace the call at. But it's not consistent with what geth and Erigon currently do.

### Steps to reproduce

1. Start reth and erigon
2. Call `trace_call`:
```json
{
  "jsonrpc": "2.0",
  "method": "trace_call",
  "params": [
    {
      "to": "0x6b175474e89094c44da98b954eedeac495271d0f",
      "data": "0x70a082310000000000000000000000005d3a536e4d6dbd6114cc1ead35777bab948e3643"
    },
    [
      "trace"
    ],
    "0xe67702"
  ],
  "id": 314067518751704834
}
```

3. Observe the difference in responses:
```
type                index       reth       erigon
──────────────────────────────────────────────────
value   trace.0.action.gas   0x1c8fd59   0x2fa9cc8
                              29949273   49978568
```

reth's `29949273` gas limit is the mainnet block 15103746 gas limit `29970705` minus the `21432` gas (min tx gas + initialization costs)
erigon's `49978568` gas limit is the constant gas limit `50000000` minus the same `21432` gas

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by gakonst** [comment]
The solution is to just change the max gas to 30M instead of 50M right?

**Comment by mattsse** [comment]
yes, not sure why it is 50M by default though

**Comment by shekhirin** [comment]
> The solution is to just change the max gas to 30M instead of 50M right? 

and use it in the `trace_call` instead of block's actual gas limit

**Comment by shekhirin** [comment]
Turns out, same applies to `eth_call` RPC calls: if no gas limit is specified in the transaction object, Geth fallbacks to the default gas cap which is 30M: https://github.com/ethereum/go-ethereum/blob/84b05d4f343dea9d89862d0bbaa7e9d0c3f0acd5/internal/ethapi/api.go#L1037
