### ISSUE TITLE
Database corruption error

### ISSUE THREAD

**Issue by Gaon3** [paradigmxyz/reth#3226]
### Describe the bug

After initial sync, node kept running until CL client (Lighthouse) started giving me this message every block
`un 19 10:19:19.394 WARN Failed to sync chain built on invalid parent, advice: check execution node for corruption then restart it and Lighthouse, parent_root: 0xdfad422d2e6a858bd55b45d586d913da8b6d0545bfeed7c1c8c914a066e1d6b3`
At this point the node was not running stages, only printing peer updates.

I restarted it with Lighthouse and here is the error I got 
```
2 023-06-19T10:25:50.344592Z ERROR execute{stage=Bodies}: sync::pipeline: Stage encountered a fatal error: An internal database error occurred: Database write error code: -30796. stage=Bodies
2023-06-19T10:25:50.368062Z  INFO reth::cli: Wrote network peers to file peers_file="/root/.local/share/reth/mainnet/known-peers.json"
Error: A stage encountered an irrecoverable error.

Caused by:
   0: An internal database error occurred: Database write error code: -30796
   1: Database write error code: -30796

Location:
    bin/reth/src/node/mod.rs:392:9

```

### Steps to reproduce

idk

### Platform(s)

Linux (x86)

### What version/commit are you on?

a8be68a82c20ecf6b50ea66d8a706a3493c9bce0

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
Possibly related to https://github.com/paradigmxyz/reth/issues/3087
