### ISSUE TITLE
Track full sealedheaders in Blockchaintree

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3236]
### Describe the feature

atm the tree tracks only canonical hashes:

https://github.com/paradigmxyz/reth/blob/1049202f0fbb3da4a57817c73d14a5ae56b58c75/crates/blockchain-tree/src/canonical_chain.rs#L4-L12

however in order to payloads we often need full headers which results in additional lookups. Tracking SealedHeaders here would get rid of the additional lookup

first attempt here: https://github.com/paradigmxyz/reth/blob/1049202f0fbb3da4a57817c73d14a5ae56b58c75/crates/transaction-pool/src/validate.rs#L161-L165

## TODO
* refactor `CanonicalChain` so it tracks `SealedHeaders`

will require some refactoring

**Comment by leovct** [comment]
Hey, I'd like to work on this one.

If I understood correctly, we'd like to keep track of sealed block headers (on top of the hashes we already track) to avoid additional lookups in the context of payloads. My guess was to do something like the following and a little refactoring where `CanonicalChain` is used. Does that sound correct?

```rust
/// This keeps track of all blocks of the canonical chain. 
/// 
/// This is a wrapper type around an ordered set of block numbers and hashes that belong to the 
/// canonical chain. 
#[derive(Debug, Clone, Default)] 
pub(crate) struct CanonicalChain {
    chain: BTreeMap<BlockNumber, (BlockHash, BlockHeader)>,
}
```

**Comment by alessandromazza98** [comment]
I can try this one!
