### ISSUE TITLE
`metrics` default port conflicts with `lighthouse bn` default port

### ISSUE THREAD

**Issue by brockelmore** [paradigmxyz/reth#3258]
### Describe the change

`RUST_LOG=info reth node --metrics 127.0.0.1:9000` is suggested by the reth book.

Lighthouse uses port 9000 and needs it open: https://lighthouse-book.sigmaprime.io/advanced_networking.html#nat-traversal-port-forwarding.

Adjusting the metrics seems easier than a custom lighthouse configuration which seems nontrivial relative to changing `/etc/prometheus/prometheus.yml` and the mentions in the reth book.

**Comment by leovct** [comment]
Hi, happy to work on this small issue! :)

Based on the different ports exposed by the Reth Dockerfile (`30303`, `30303/udp`, `9000`, `8545` and `8546`), I suggest using port `9091` for metrics, wdyt?
