### ISSUE TITLE
perf tracing: make log recording optional

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3268]
### Describe the feature

most tracers don't need logs that we record here (currently only `CallTracer` if includeLogs is enabled):

https://github.com/paradigmxyz/reth/blob/c75cacf85551f9d6ccbdfddf5530541b6da7658e/crates/revm/revm-inspectors/src/tracing/mod.rs#L328-L341

## TODO

* add config value for `record_logs`:
https://github.com/paradigmxyz/reth/blob/c75cacf85551f9d6ccbdfddf5530541b6da7658e/crates/revm/revm-inspectors/src/tracing/config.rs#L7-L10
* only record logs if `record_logs` is true

**Comment by tcoratger** [comment]
I think this one is closed by #3286 or does it require other elements?
