### ISSUE TITLE
rpc: list all storage slots at block height

### ISSUE THREAD

**Issue by banteg** [paradigmxyz/reth#3294]
### Describe the feature

there is a little-known method called [parity_listStorageKeys](https://openethereum.github.io/JSONRPC-parity-module#parity_liststoragekeys) that returns a paginated view of a contract storage at a certain block height.

it could be a good starting point, but the method itself is not ideal, because the user would most likely also want to retrieve the associated values and not only keys. some kind of streaming or pagination would make sense to account for contracts with massive storage.

**Comment by plotchy** [comment]
+1. This is a very helpful RPC for security work. [ETHBMC](https://github.com/RUB-SysSec/EthBMC#ethbmc-a-bounded-model-checker-for-smart-contracts) is an example where it's used for storage access. Love the idea of returning key:val pairs. 

For massive storage testing, [univ2factory](https://etherscan.io/address/0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f#readContract#F2) has 202450 pairs, which IIRC is doubled in storage for redundant pair mappings pair[token][token]. Largest storage I know of

**Comment by banteg** [comment]
there is an even bigger one with over 4 million slots used https://twitter.com/austinadams10/status/1669869209520680965

**Comment by rakita** [comment]
This is interesting one, it did require fatdb flag for OE.

On impl side, I am not sure about performance but It can be done in reth, this would mean we would iterate over `StorageHistory` table to get all storages that got changed until that block, and second step is to extract values of those slots from `StorageChangeSet` table. Just to note that extracted value can be zero as it represent not existing (storage got removed) slot.

`Offset storage key from which the batch should start in order` makes sense.

**Comment by rakita** [comment]
From #3517 there is geth opcode that does similar thing: https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugstoragerangeat

The difference (other than naming) is that geth additionally takes the tx index. This means we must execute the previous transaction from block to get the updated state and intertwine that state with state form database (both overrides and ordering new values).

**Comment by avinashbo** [comment]
Does this mean this won't be supported?
