### ISSUE TITLE
Discussion: how to refactor storage libraries

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#333]
The structure of storage related libraries are now:

* `crates`
  * `codecs`
  * `db`
  * `libmdbx-rs`
  * `interfaces` (Database stuff becomes bigger and bigger, it probably deserves a standalone lib and moving them to the interface was not the greatest idea I though only the abstraction part is going to be here but this does not make a lot of sense now)
    * abstraction traits.
    * `tables`
    * `provider`
    * `codecs` impl
    

it can be refactored to:
* `crates`:
  * `storage`:
    * `libmdbx-rs`
    * `db` (This would contains db traits from interfaces, and have a feature flag `mdbx`)
       * abstraction traits
       * `tables` 
       * `providers`
       * `codecs` impl
    * `codecs`

Additionally, I would move the `StageDb` from `reth-stages` to `providers` to have all database-related operations in the same place.

**Comment by onbjerg** [comment]
Was this closed in #371?
