### ISSUE TITLE
Track path in `std::io::Error` errors

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#3330]
### Describe the feature

`std:io::Error` doesn't track the path that lead to the error. Because of that, we have a bunch of custom IO errors across the codebase, see e.g. https://github.com/paradigmxyz/reth/pull/3324.

We need to introduce a wrapper for such fallible `std::fs` methods, and use it across the codebase, propagating the error.

Reference implementation from Foundry: https://github.com/foundry-rs/foundry/pull/2053

**Comment by mattsse** [comment]
closed via #3367
