### ISSUE TITLE
Manual peer-to-peer example

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#3393]
Create an example showing how to connect directly to a peer and communicating with it.

This should use the lower-level types of the networking component as much as possible

**Comment by 0xmiri** [comment]
For this to be possible without forking, you will have to open up a lot of modules specifically in [here](https://github.com/paradigmxyz/reth/blob/main/crates/net/network/src/lib.rs) so that you can access these lower-level types

**Comment by mouseless-eth** [comment]
Currently working on this, can I take this issue?
