### ISSUE TITLE
Example showing how to create a custom payload builder

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#3401]
Create an example showing how to create a custom payload builder

**Comment by jacobkaufmann** [comment]
I started work on something [here](https://github.com/jacobkaufmann/dark-builder) for an example that builds with transaction bundles. it's still a WIP and not in a ready state at the moment (see open issues). I'm not sure whether the maintainers would want such an example, but I'd be happy to upstream it (or a pared down version) if that would be beneficial.

the intention is not a production-ready builder, but only the minimal scaffolding (i.e. skeleton) that others can use for inspiration to do far more sophisticated things (e.g. integrate with [`artemis`](https://github.com/paradigmxyz/artemis)).

**Comment by mattsse** [comment]
>  I'm not sure whether the maintainers would want such an example, but I'd be happy to upstream it (or a pared down version) if that would be beneficial.

cool, please do :)
