### ISSUE TITLE
Add a panic hook

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#3402]
### Describe the feature

We should add a panic hook that includes information we want in the bug report, along with a link to the issue form itself, such as the version, database version, platform and backtrace.

See e.g. 

- https://github.com/rust-lang/rust/blob/master/compiler/rustc_driver_impl/src/lib.rs#L1258
- https://github.com/rust-lang/rust/blob/master/compiler/rustc_driver_impl/src/lib.rs#L1235

**Comment by risingsun007** [comment]
May I be assigned this issue?

**Comment by onbjerg** [comment]
We have a panic hook
