### ISSUE TITLE
Add support for debug_storageRangeAt

### ISSUE THREAD

**Issue by ritzdorf** [paradigmxyz/reth#3417]
### Describe the feature

Hi everyone,

congrats on what has been achieved so far. It would be great if you could add support for the debug_storageRangeAt API.

The API is described here among other places: 
https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugstoragerangeat

It is really helpful in investigating historic states.

**Comment by rakita** [comment]
Something similar was requested here: https://github.com/paradigmxyz/reth/issues/3294 parity variant with similar functionality.

So I will close this as duplicate.
