### ISSUE TITLE
eth_getBlockByNumber sporadically fails on "latest" 

### ISSUE THREAD

**Issue by awilper** [paradigmxyz/reth#3424]
### Describe the bug

Querying for block with "latest", and every couple hours sporadically see this. 

```UnknownQueryError | Result {'code': -32001, 'message': 'Unknown block number'} | Query {'id': 155, 'jsonrpc': '2.0', 'method': 'eth_getBlockByNumber', 'params': ['latest', False]}```

### Steps to reproduce

Setup a callback for block headers and immediately after call getBlockByNumber with "latest". Every few hours this error appears. 

### Platform(s)

Linux (x86)

### What version/commit are you on?

Reth v0.1.0-alpha.1 

### What database version are you on?

Current database version: 1
Local database version: 1

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
optimistically closing this, please reopen if you encounter this again
