### ISSUE TITLE
Installing reth as a dependency on a rust project fails 

### ISSUE THREAD

**Issue by joshstevens19** [paradigmxyz/reth#3454]
### Describe the bug

Installing reth as a dependency in another rust project throws an error 

### Steps to reproduce

Add: 

[dependencies]
reth = { git = "https://github.com/paradigmxyz/reth" }

Build error: 

error[E0609]: no field precompiles on type &mut EVMData<'_, DB>
   --> /home/ubuntu/.cargo/git/checkouts/reth-36d3ea1d1152b20c/6b8b478/crates/revm/revm-inspectors/src/tracing/js/mod.rs:280:33
    |
280 |             PrecompileList(data.precompiles.addresses().into_iter().map(Into::into).collect());
    |                                 ^^^^^^^^^^^ unknown field
    |
    = note: available fields are: env, journaled_state, db, error

error[E0609]: no field precompiles on type &EVMData<'_, DB>
   --> /home/ubuntu/.cargo/git/checkouts/reth-36d3ea1d1152b20c/6b8b478/crates/revm/revm-inspectors/src/tracing/mod.rs:493:13
    |
493 |     if data.precompiles.contains(to) {
    |             ^^^^^^^^^^^ unknown field
    |
    = note: available fields are: env, journaled_state, db, error

For more information about this error, try rustc --explain E0609.

Let me know if you need anything else 

### Platform(s)

Linux (x86)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Gaon3** [comment]
You need to add this in your Cargo.toml
```
[patch.crates-io]
# patched for quantity U256 responses <https://github.com/recmo/uint/issues/224>
ruint = { git = "https://github.com/paradigmxyz/uint" }

revm = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
revm-primitives = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
```

Also I suggest that you add reth crates independently, I doubt you need to import the entire project.
ex: `reth-primitives = { git = "https://github.com/paradigmxyz/reth", package = "reth-primitives" }`

**Comment by joshstevens19** [comment]
awesome yep worked

[dependencies]
reth-db = { git = "https://github.com/paradigmxyz/reth", package = "reth-db" }

[patch.crates-io]
# patched for quantity U256 responses <https://github.com/recmo/uint/issues/224>
ruint = { git = "https://github.com/paradigmxyz/uint" }

revm = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
revm-primitives = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }

thanks dude

**Comment by joshstevens19** [comment]
looks like i can just remove that if i just want the db package

```
[dependencies]
reth-db = { git = "https://github.com/paradigmxyz/reth", package = "reth-db" }
```

**Comment by gakonst** [comment]
Yes - exactly. We'll be improving the UX of consuming as crates in the future, for now appreciate the patience and hope it's not a huge deal.

**Comment by joshstevens19** [comment]
Not at all my mistake really - keep up the amazing work guys 🙏🙏
