### ISSUE TITLE
Update database diagram

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#3462]
## Description

Update [database diagram](https://github.com/paradigmxyz/reth/blob/main/docs/design/database.md#table-design) according to the latest [database layout](https://github.com/paradigmxyz/reth/blob/b7c977765c5491186e041086d8199cc25a559f0f/crates/storage/db/src/tables/mod.rs).

## Additional Context

You can use https://mermaid.live for editing mermaid tables.

**Comment by Philogy** [comment]
Could I be assigned this issue? Was planning on getting into & understanding the db layout anyway

**Comment by onbjerg** [comment]
Yep, sorry for the delayed response. I assigned you, let me know if you want to be unassigned for any reason 😄

**Comment by DaniPopes** [comment]
This looks like it was done in https://github.com/paradigmxyz/reth/pull/4194
