### ISSUE TITLE
Rename tx > Transaction in DB tables for consistency

### ISSUE THREAD

**Issue by joshstevens19** [paradigmxyz/reth#3464]
### Describe the bug

Not a bug, but just flagging we have db tables:

TransactionBlock
Transactions
TxHashNumber
TxSenders

while we still in beta this could be one of those things we end up hating the Tx or Transaction table names, to be consistent we should pick Transaction or Tx IMO!

### Steps to reproduce

Look at the database table names :)

### Platform(s)

Linux (x86)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
I'm in favor of using `Transaction` and remove `Tx`

**Comment by rkrasiuk** [comment]
hmm, is there a way to do this without breaking the database format? or, perhaps, we could provide an easy and quick migration

**Comment by mattsse** [comment]
I guess we can hold off on this until we need to break the DB,

but having `Tx` is also not a big deal imo,

**Comment by joshstevens19** [comment]
Yeah it’s not big one and not end of world if it never changes
