### ISSUE TITLE
Progress reporting in between commits

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#3477]
### Describe the feature

For more insight into how the node is progressing, we should add a way for stages and the tree to report progress in between commits. **This progress will be rolled back if the node crashes or is stopped for any reason**.

These things are important:

- It is clear that the progress is not committed, and thus not final
- That there is still a metric for committed progress (checkpoints), not only ephemeral progress

It would be nice if this worked with ETAs.

This will most likely be implemented in two steps:

- [ ] Integrate in pipeline
- [ ] Integrate in the tree

**Comment by joshieDo** [comment]
We do have this to certain degrees, and it is an ongoing effort to improve, so i think we can close this
