### ISSUE TITLE
Document pruning configuration

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#3480]
### Describe the change

As we are working towards full node, we have added some new configuration. See:

- https://github.com/paradigmxyz/reth/pull/3341
- https://github.com/paradigmxyz/reth/issues/3430

We should document these in the book.

Unsure if we should document them now (as they do not do anything currently), or later once we have full node. cc @gakonst

**Comment by gakonst** [comment]
Let's do it after we have the feature in cc @shekhirin u think we can be in time for alpha.3?

**Comment by shekhirin** [comment]
We also need to document how pruning of different parts affect the RPC.
