### ISSUE TITLE
Memory usage limiter doesn't work as expected in `EthCache`

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#3503]
## Description

`schnellru::ByMemoryUsage` limiter doesn't work as expected in `EthCache` internal caches.

The metrics below show that the `memory_usage` fn, which is used by `ByMemoryUsage` limiter, reports lower usage than expected for this amount of blocks. 

<img width="859" alt="Screenshot 2023-06-30 at 16 52 30" src="https://github.com/paradigmxyz/reth/assets/25429261/488475b9-492f-4e06-bb2c-a7cf9363f0b3">

**Comment by mattsse** [comment]
right, turns out this uses `std::mem::size_of` which of course doesn't track heap alloc mem...
