### ISSUE TITLE
Error 32003 on a trace for old transaction

### ISSUE THREAD

**Issue by garythung** [paradigmxyz/reth#3514]
### Describe the bug

Getting an error response about insufficient funds when tracing an old transaction.

```
{"jsonrpc":"2.0","error":{"code":-32003,"message":"insufficient funds for gas * price + value"},"id":1}
```

Erigon returns this

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "action": {
        "from": "0xa1e4380a3b1f749673e270229993ee55f35663b4",
        "callType": "call",
        "gas": "0x0",
        "input": "0x",
        "to": "0x5df9b87991262f6ba471f09758cde1c0fc1de734",
        "value": "0x7a69"
      },
      "blockHash": "0x4e3a3754410177e6937ef1f84bba68ea139e8d1a2258c5f85db9f1cd715a1bdd",
      "blockNumber": 46147,
      "result": {
        "gasUsed": "0x0",
        "output": "0x"
      },
      "subtraces": 0,
      "traceAddress": [],
      "transactionHash": "0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060",
      "transactionPosition": 0,
      "type": "call"
    }
  ]
}
```

Transaction in question: https://etherscan.io/tx/0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060

### Steps to reproduce

Using trace module
```
curl -X POST -H "Content-Type: application/json" -d '{
  "method": "trace_transaction",
  "params": [
    "0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060"
  ],
  "id": 1,
  "jsonrpc": "2.0"
}' <YOUR_RPC>
```

Using debug module
```
curl -X POST -H "Content-Type: application/json" -d '{
  "method": "debug_traceTransaction",
  "params": [
    "0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060",
    {"tracer": "callTracer", "tracerConfig": {"onlyTopCall": False}}
  ],
  "id": 1,
  "jsonrpc": "2.0"
}' <YOUR_RPC>
```

### Node logs

None

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0 Commit SHA: 729d4ad3 Build Timestamp: 2023-06-19T23:55:41.064107103Z Build Features: jemalloc

### What database version are you on?

Current database version: 1
Local database version: 1

### If you've built Reth from source, provide the full command you used

RUSTFLAGS="-C target-cpu=native" cargo build --profile maxperf --features=jemalloc

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks for flagging this

this account is a genesis account, we fixed a bug because we didn't insert account & storage history for these accounts properly

was fixed in https://github.com/paradigmxyz/reth/pull/3346

@rkrasiuk is it possible to add them retroactively?

**Comment by rkrasiuk** [comment]
@mattsse no, not atm. let me think what we can do to backfill

**Comment by onbjerg** [comment]
@garythung Can you try with #3346 applied? It requires a resync unfortunately.

**Comment by onbjerg** [comment]
Yes, basically just wipe the datadir and resync.

**Comment by MysticRyuujin** [comment]
Whatever this transaction is, it's preventing syncing from genesis, see #11934
