### ISSUE TITLE
Implement erigons debug_TraceCallMany

### ISSUE THREAD

**Issue by geomad** [paradigmxyz/reth#3522]
### Describe the feature

The `debug_TraceCallMany` feature (see https://github.com/ledgerwatch/erigon/issues/4471) , is a helpful tool for tracing multiple transactions in a specific order.

The main distinction from `trace_CallMany` is that transactions can be simulated with different properties such as `BlockNumber`, `timestamp`, and others for each transaction. This allows users to simulate transactions across multiple consecutive blocks.

It would be beneficial if this feature could also be supported in the future for `trace_CallMany`.

Here are some notes regarding the current implementation of `debug_TraceCallMany` in Erigon:

- The change described in [this commit](https://github.com/ledgerwatch/erigon/commit/29bbe1d9c7a90873f368f53b7e5f95711cc581ae) significantly improves tracing speed when `transactionIndex` is set to -1 (default value). Instead of fetching the previous block, executing all of its transactions, and then simulating the bundles, it now fetches the latest block and simulates the transactions within that context.

- [This commit](https://github.com/ledgerwatch/erigon/commit/a83808854255a21fa1d5dc00b987c144afea6273) introduces a slight change in the behavior of the `prestateTracer` tracer when `tracerConfig` is set to `diffMode: true`. Previously, if something in the state changed to `0`, it would be omitted in the `.post` key. However, with this change, such a change will now be included in the `.post` key. This aligns the behavior with `trace_CallMany`.

**Comment by mattsse** [comment]
supportive

making this a good first issue:

# todo

* add new function binding like: https://github.com/paradigmxyz/reth/blob/ec672238ca6addf62fac89de027bd2320b49182e/crates/rpc/rpc-api/src/debug.rs#L98-L104
* add draft impl like: https://github.com/paradigmxyz/reth/blob/ec672238ca6addf62fac89de027bd2320b49182e/crates/rpc/rpc/src/debug.rs#L246-L258

**Comment by 0x6020c0** [comment]
I can try to implement this

**Comment by mattsse** [comment]
Sweet lmk if you need pointers by opening a draft pr

**Comment by tcoratger** [comment]
@mattsse Anything to do here since #3878 was merged?

**Comment by mattsse** [comment]
can be closed, thanks!
