### ISSUE TITLE
Enhanced Error Tracing for TraceApi & DebugApi

### ISSUE THREAD

**Issue by 0xvanbeethoven** [paradigmxyz/reth#3537]
### Describe the feature

As a developer working with the TraceApi & DebugApi, I've been struggling to debug my code, due in part to my lack of skills and the current lack of detailed error information. Specifically, when the InternalTracingError is thrown, it provides limited context, making it challenging to identify the root cause of the issue in my code.

Feature Description:
I'm requesting an enhancement to the error tracing within the TraceApi & DebugApi. It would be particularly useful if the InternalTracingError could return more granular information about its source. Details such as the stack trace, exact line of code that panics, or any other pertinent context could significantly streamline the debugging process.

Thanks in advance for your help! 

### Additional context

The faulty code I wrote, attempts to initialise a DebugApi & TracingApi it can be found here: [poirot-rs](https://github.com/SorellaLabs/poirot-rs) 
This is the code used to initialise the APIs.
![carbon (11)](https://github.com/paradigmxyz/reth/assets/103021596/4ec090dc-1f64-49d4-94fd-98fc53f0c8b0)

This is the code that fails:
![carbon (9)](https://github.com/paradigmxyz/reth/assets/103021596/03c11cb8-380d-4156-bf77-c32406e240bb)

As you can see from the comments, only calls that call:
![carbon (10)](https://github.com/paradigmxyz/reth/assets/103021596/032717ab-d94c-4c88-80d2-9ceaadc6d523)
throw the error, so I suspect it is an issue relating to how I initialise the task_executors/ task_spawners or a panic because the functions can't get access to the required state.

I would greatly appreciate anyone's help on this issue. Thank you in advance!

**Comment by mattsse** [comment]
the error you're referencing only happens when the spawned task panics, which is already traced, 
the error in question is a simple `mpsc::ReceiveError`

**Comment by 0xvanbeethoven** [comment]
Thank you guys for the feedback on this issue in tg. I tried initialising the runtime like how it is done in reth (Cli Runner) & I am still getting the same issue. It seems to properly query the db, but panics & aborts the db reads for some reason. 

Full code: [poirot-rs](https://github.com/SorellaLabs/poirot-rs)

This is the code:
![carbon (12)](https://github.com/paradigmxyz/reth/assets/103021596/b88b0383-6be0-4342-bc57-aca5fa29d941)

This is the log:
[error.txt](https://github.com/paradigmxyz/reth/files/11950098/error.txt)
