### ISSUE TITLE
Add helper functions to configure noops in RpcModuleBuilder

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3542]
### Describe the feature

make it easier to configure rpc without any additional components, but a lot of namespaces depend on eth_ which requires network, txpool interfaces to function properly.

ref #3536

**Comment by gakonst** [comment]
I would consider splitting up the ETH traits on methods that do not require access to pending state which we'd be albe to run w/o having to have a maintained network component. And we'd prob want to return that "Pending"-related requests are not supported when no network component is set up?

**Comment by mattsse** [comment]
this is not really feasible because rpc still needs to handle `pending` tag, they way this should work is by having a provider that doesn't know what pending is and always returns `None` objects

**Comment by gakonst** [comment]
> this is not really feasible because rpc still needs to handle pending tag, they way this should work is by having a provider that doesn't know what pending is and always returns None objects

Yeah exactly, we should refactor RPC so that it always return None on `pending` tag queries if no tree provided, and maybe we can wrap that struct with the tree in a new struct (the existing BlockchainDatabase type) and delegate to the inner struct for all non-pending queries?
