### ISSUE TITLE
Add subscriptions for transactions events for all pool transactions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3547]
### Describe the feature

atm this represents a single transaction

https://github.com/paradigmxyz/reth/blob/0aeffe96b058ec94c13dfad725d1d0051cd119bf/crates/transaction-pool/src/pool/events.rs#L8-L11

we want a way to get notified about all discarded and replaced transactions as well

## TODO 

* add a new general purpose event that also tracks the hash of the transaction, I think this should only included, mined,discarded,replaced,pending
* add a way to subscribe to all changes

https://github.com/paradigmxyz/reth/blob/0aeffe96b058ec94c13dfad725d1d0051cd119bf/crates/transaction-pool/src/pool/listener.rs#L40-L48

**Comment by tcoratger** [comment]
@mattsse I'm not sure to understand perfectly the problem to solve here because `TransactionEvent` enum already contains `mined`, `discarded`, `replaced` and `pending` variants, so what is the change to bring there? :) 
```rust
/// Various events that describe status changes of a transaction.
#[derive(Debug, Clone, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum TransactionEvent {
    /// Transaction has been added to the pending pool.
    Pending,
    /// Transaction has been added to the queued pool.
    Queued,
    /// Transaction has been included in the block belonging to this hash.
    Mined(H256),
    /// Transaction has been replaced by the transaction belonging to the hash.
    ///
    /// E.g. same (sender + nonce) pair
    Replaced(TxHash),
    /// Transaction was dropped due to configured limits.
    Discarded,
    /// Transaction became invalid indefinitely.
    Invalid,
    /// Transaction was propagated to peers.
    Propagated(Arc<Vec<PropagateKind>>),
}
```

**Comment by mattsse** [comment]
this is for specific transactions where the sender already knows the hash, but we also want this for any transaction

@rkrasiuk already took this in #3565
