### ISSUE TITLE
Document ports

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#3550]
### Describe the change

Our book does not reference what ports are used, for what, and what should likely be publicly exposed.

These are the ports:

- 30303 (TCP and UDP): Peering with other nodes. Should be exposed
- 9001 (TCP): Metrics. Should not be exposed by default
- 8545 (TCP): HTTP RPC. Should not be exposed by default
- 8546 (TCP): WS RPC. Should not be exposed by default.
- 8551 (TCP): Engine API (for communication between reth and CL). Should not be exposed by default

**Comment by Evalir** [comment]
gm, happy to help here

**Comment by onbjerg** [comment]
go ahead sir

**Comment by Sabnock01** [comment]
@Evalir you still want this one?

**Comment by Evalir** [comment]
Hey @Sabnock01 ! Yep still planning to contribute here, I'll ping you if I don't

**Comment by tcoratger** [comment]
@onbjerg I think this can be closed with #4370.

**Comment by mattsse** [comment]
thanks @tcoratger
