### ISSUE TITLE
eta=unknown during sync makes it look like it's stuck

### ISSUE THREAD

**Issue by wakamex** [paradigmxyz/reth#3569]
### Describe the bug

sync is stuck at MerkleExecute stage with eta=unknown
cpu usage is about 10-30%
memory 80% on a 64gb box
```
Jul 03 21:36:50 reth reth[587413]: 2023-07-03T19:36:50.709266Z  INFO reth::node::events: Executing stage pipeline_stages=9/13 stage=MerkleExecute from=17566399 checkpoint=17566399 eta=unknown
Jul 03 21:36:52 reth reth[587413]: 2023-07-03T19:36:52.204375Z  INFO reth::cli: Status connected_peers=180 stage=MerkleExecute checkpoint=17566399 eta=unknown
Jul 03 23:53:52 reth reth[587413]: 2023-07-03T21:53:52.218543Z  INFO reth::cli: Status connected_peers=189 stage=MerkleExecute checkpoint=17566399 eta=unknown
```
after restart:
```
Jul 04 02:11:10 reth reth[3453142]: 2023-07-04T00:11:10.493136Z  INFO reth::cli: Status connected_peers=23 stage=MerkleExecute checkpoint=17566399 eta=unknown
```

### Steps to reproduce

1. set up a fresh box on Hetzner
	using ZFS w/ zstd compression on the root drive, which includes reth
	```
	NAME   PROPERTY       VALUE  SOURCE
	rpool  compressratio  2.05x  -
	```
3. set up node with https://github.com/0xSheller/reth_helper
4. use aws to sync a snapshot of their DB
5. try to sync the rest

### Node logs

```text
10k debug lines https://gist.githubusercontent.com/wakamex/edef71bdc8054707062aa0163c9b6766/raw/4666befff03499106375cde5d09d9f3db9b03de7/debug_merkle_n10000.txt
10k trace lines https://gist.githubusercontent.com/wakamex/1fd75e1c3307adccb70d7ea4673b47f9/raw/80ae59c8bd49adf799611c594008c156e912a21e/debug_merkle_trace.txt
```

### Platform(s)

Linux (x86)
Ubuntu 22.04.2 LTS

### What version/commit are you on?

```
reth Version: 0.1.0-alpha.1
Commit SHA: b245193
Build Timestamp: 2023-06-20T01:37:15.655402245Z
Build Features: jemalloc
```

### What database version are you on?

Current database version: 1
Local database version: 1

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by wakamex** [comment]
reth_sync_entities_processed for MerkleExecute shows a perfectly flat line for the last 12 hours
![image](https://github.com/paradigmxyz/reth/assets/16990562/a368573e-c1ab-4c89-b4db-e640933cd6c0)

**Comment by wakamex** [comment]
it woke up and it's doing something. the only issue may have been the lack of eta or status updates, perhaps owing to the old hardware this is running on:
* Intel Core i7-8700
* 1x HDD SATA 2,0 TB Enterprise
* 2x SSD M.2 NVMe 1 TB
* 2x RAM 32768 MB DDR4
* NIC 1 Gbit Intel I219-LM


![image](https://github.com/paradigmxyz/reth/assets/16990562/1db743a3-4508-4e8e-9d81-b1ff611ef98c)

**Comment by wakamex** [comment]
I'm also getting an eta unknown on my home machine in a different spot: `2023-07-04T13:11:16.287629Z  INFO reth::cli: Status connected_peers=122 stage=IndexStorageHistory checkpoint=15700000 eta=unknown`

**Comment by wakamex** [comment]
line go up (Hetzner box)
`Jul 04 15:28:44 reth reth[3453142]: 2023-07-04T13:28:44.501734Z  INFO reth::cli: Status connected_peers=202 stage=Execution checkpoint=100.0% eta=unknown`
![image](https://github.com/paradigmxyz/reth/assets/16990562/55d9e488-21ce-441c-983d-ab9ed805d6d4)

**Comment by BarnumD** [comment]
Mine is stuck at
`Status connected_peers=24 stage=TransactionLookup checkpoint=28.2% eta=unknown`

**Comment by wakamex** [comment]
confirmed it's only a visual issue with repoting `eta=unknown` since my Hetzner box did catch up to the block head
![image](https://github.com/paradigmxyz/reth/assets/16990562/c8a9c42f-ad18-44ec-803c-a0413a32b426)

**Comment by onbjerg** [comment]
The eta=unknown is because we can only deduce the eta after 2 checkpoints (since we compute eta between points A and B). Since we don't commit super often, sometimes it looks like this. We're working on making improvements for this which is tracked in https://github.com/paradigmxyz/reth/issues/3477, so I'm closing this issue as sort of a duplicate
