### ISSUE TITLE
Allow configuring network in Docker Compose

### ISSUE THREAD

**Issue by vacekj** [paradigmxyz/reth#3592]
### Describe the feature

**Original**

Wondering if it would make sense to have a docker compose for Sepolia? To accompany a short addition to the docker-compose section in the docs on running on testnet.

**Edited (@onbjerg)**

Allow configuring the network (and other parts of the stack) using environment variables in Docker Compose. See https://github.com/paradigmxyz/reth/issues/3592#issuecomment-1621573445

**Comment by onbjerg** [comment]
I think the fix is to use some sort of environment variables to configure the compose file. The main issue here is that switching networks not only changes the path of the database in reth, it also requires using a different checkpoint URL for Lighthouse etc.

Renaming the issue to make this more general

**Comment by paolofacchinetti** [comment]
imo adding some abstraction to the standard `docker-compose.yml` to allow different networks is not the solution. It will probably just end up adding complexity and confusing newcomers that want to start from the default `docker-compose.yml` and make some changes to it or understand exactly what it is doing.

switching from mainnet to Sepolia isn't that complex once you know what you're doing, you can start from the base `docker-compose.yml` and tweak a few command-line args, ports and environment variables.

still, if there's a need for a default Sepolia `docker-compose.yml` we could simply have a separate compose file specific for that network.

**Comment by tjayrush** [comment]
> imo adding some abstraction to the standard `docker-compose.yml` to allow different networks is not the solution. It will probably just end up adding complexity and confusing newcomers that want to start from the default `docker-compose.yml` and make some changes to it or understand exactly what it is doing.
> 
> switching from mainnet to Sepolia isn't that complex once you know what you're doing, you can start from the base `docker-compose.yml` and tweak a few command-line args, ports and environment variables.
> 
> still, if there's a need for a default Sepolia `docker-compose.yml` we could simply have a separate compose file specific for that network.

I'm one of those people who are trying to "make some changes to...understand exactly what it's doing..."

Did you (or anyone else) write up what exactly "the command-line args, ports, and environment variables" one would need to tweak to get Sepolia to run?

Perhaps you could add those items here so I (and others) can benefit?

If not, I'll try to come back here and post what I figure out.

**Comment by paolofacchinetti** [comment]
@tjayrush try overwriting the default Reth `docker-compose.yml` with the one in the following gist:

https://gist.github.com/paolofacchinetti/06e9d23504bccaf6ff002ce6a814566e

(you'll still need to run the `generate-jwt.sh` script before running the containers)

Also, make sure to run `docker compose down -v` to remove old volumes. If you've previously ran mainnet Reth/Sepolia on those volumes that might be what's causing your problems
