### ISSUE TITLE
Docs confusion on running reth + LH

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#3597]
Having these 2 commands side by side results in users running them without changing the auth rpc port either as reth or lighthouse argument.

https://github.com/paradigmxyz/reth/blob/a932e2f1fe66e527dfcb8f4b4a1075445d2dd114/book/run/mainnet.md?plain=1#L32-L54

**Comment by onbjerg** [comment]
More:

1. Try different checkpoint URLs for Lighthouse and link https://eth-clients.github.io/checkpoint-sync-endpoints/
2. Unpack JWT secret generation more, as people get confused with it (both Eric and DCBuilder had some problems)
3. Something about metrics port conflicting with Lighthouse
4. Reth's authrpc.port doesn't match Lighthouse's

**Comment by onbjerg** [comment]
Partially addressed in https://github.com/paradigmxyz/reth/pull/3599

**Comment by rkrasiuk** [comment]
resolved
