### ISSUE TITLE
add error field to parity style TransactionTrace

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3600]
### Describe the feature

the original OE tracer did not have the error field _and_ result:

https://github.com/openethereum/openethereum/blob/6c2d392d867b058ff867c4373e40850ca3f96969/crates/ethcore/src/trace/types/flat.rs#L24-L41

it was either or:

https://github.com/openethereum/openethereum/blob/6c2d392d867b058ff867c4373e40850ca3f96969/crates/ethcore/src/trace/types/trace.rs#L298-L311

erigon changed this to

```


            "error": "Reverted",
            "result": {
                "gasUsed": "",
                "output": ""
            },
```

https://github.com/ledgerwatch/erigon/blob/eae2d9a79cb70dbe30b3a6b79c436872e4605458/cmd/rpcdaemon/commands/trace_types.go#L45-L46

## TODO

remove the TraceResult Wrapper

https://github.com/paradigmxyz/reth/blob/d058e510d25fe603c54ecf13fdda6e6d46a1c842/crates/rpc/rpc-types/src/eth/trace/parity.rs#L243-L244

and add another error: Option<String> field

**Comment by cjeva10** [comment]
Hi, 

Just submitted a PR on this - #3611. First time contributor here so I hope everything is ok!

**Comment by mattsse** [comment]
awesome, tysm, will review in a bit
