### ISSUE TITLE
`eth_feeHistory` not fully working in 0.1.0

### ISSUE THREAD

**Issue by ryanschneider** [paradigmxyz/reth#3615]
### Describe the bug

Note that the `latest` behavor has already been fixed in `main` via https://github.com/paradigmxyz/reth/pull/3288 but since I raised in on Slack gakonst asked that I log it here for completeness.

See the table below in repro steps for more details.

### Steps to reproduce

Here's a table of RPCs and their results, w/ notes.

| RPC | Result | notes|
|-----|-------|----|
| `{"method":"eth_feeHistory","params":["0x1","latest",[50]],"id":"latest","jsonrpc":"2.0"}` | `{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid block range"},"id":"latest"}` | this should work but didn't in 0.1.0 |
|  `{"method":"eth_feeHistory","params":["0x1","0x10d05cf",[50]],"id":"blocknumber","jsonrpc":"2.0"}` |  `{"jsonrpc":"2.0","result":{"baseFeePerGas":["0x9e1e3d77c","0xb1dfd6718"],"gasUsedRatio":[0.9997843333333334],"oldestBlock":"0x10d05cf","reward":[["0x0"]]},"id":"blocknumber"}` | works as expected in 0.1.0 |
|  `{"method":"eth_feeHistory","params":["0x0","latest",[50]],"id":"latest-w/-zero","jsonrpc":"2.0"}` | `{"jsonrpc":"2.0","result":{"baseFeePerGas":[],"gasUsedRatio":[],"oldestBlock":"0x0","reward":null},"id":"latest-w/-zero"}` | zero-length should either be an error or behave the same as `0x1`? |

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.1.0

### What database version are you on?

```
reth db version
Current database version: 1
Local database version: 1
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by gakonst** [comment]
As discussed this is already fixed, thank you for reporting for completeness.
