### ISSUE TITLE
Populate error field in parity traces

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3619]
### Describe the feature

this is a followup to

https://github.com/paradigmxyz/reth/pull/3611

if a call failed (`success` field) the error should contain the error string:

ref https://github.com/ledgerwatch/erigon/blob/eae2d9a79cb70dbe30b3a6b79c436872e4605458/cmd/rpcdaemon/commands/trace_adhoc.go#L393-L408

**Comment by mattsse** [comment]
@cjeva10 do you want to take this?

**Comment by cjeva10** [comment]
Opened #3627 to tackle this.

**Comment by onbjerg** [comment]
Closed in #3627
