### ISSUE TITLE
Database table names are inconsistently singular/plural

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#3625]
### Describe the feature

Tidy up
https://github.com/paradigmxyz/reth/blob/6810cd1295f99e2bec87c06023cb9cd45700793e/crates/storage/db/src/tables/mod.rs#L161-L187

**Comment by mattsse** [comment]
hehe a fairy tale as old as time

**Comment by onbjerg** [comment]
related https://github.com/paradigmxyz/reth/issues/3464

**Comment by ExtremelySunnyYK** [comment]
Is anyone working on this right now? And would this be a suitable first ticket for public to work on since its `S-breaking`? Looking to take on this ticket to familiarize myself to the codebase and contribute deeper in the future.

**Comment by shekhirin** [comment]
@ExtremelySunnyYK no one is working on it right now, assigned you! `S-breaking` for the first ticket is fine, as it'll pass the review as usually and will not be merged until the [whole batch of breaking PRs](https://github.com/paradigmxyz/reth/pulls?q=is:open+is:pr+label:S-breaking) is ready to be released.

**Comment by ExtremelySunnyYK** [comment]
thank you! for assigning it to me @shekhirin appreciate it, will start working on this at this week.

**Comment by shekhirin** [comment]
hey @ExtremelySunnyYK, let me know if you're no longer working on this, as someone else could take this good first issue!

**Comment by JosepBove** [comment]
I could take it if he is inactive

**Comment by shekhirin** [comment]
@JosepBove sounds good, assigned!

**Comment by JosepBove** [comment]
Thanks, will work on this tomorrow!

**Comment by JosepBove** [comment]
Also thought about the ommer word?

https://github.com/ConsenSys/EthOn/issues/1

**Comment by JosepBove** [comment]
Does everyone agree with this names?

```rust
 tables!([ 
     (CanonicalHeaders, TableType::Table), 
     (HeaderTD, TableType::Table), 
     (HeaderNumbers, TableType::Table), 
     (Headers, TableType::Table), 
     (BlockBodyIndices, TableType::Table), 
     (BlockOmmers, TableType::Table), 
     (BlockWithdrawals, TableType::Table), 
     (TransactionBlock, TableType::Table), 
     (Transactions, TableType::Table), 
     (TransactionHashNumbers, TableType::Table), 
     (Receipts, TableType::Table), 
     (PlainAccountStates, TableType::Table), 
     (PlainStorageStates, TableType::DupSort), 
     (Bytecodes, TableType::Table), 
     (AccountHistory, TableType::Table), 
     (StorageHistory, TableType::Table), 
     (AccountChangeSets, TableType::DupSort), 
     (StorageChangeSets, TableType::DupSort), 
     (HashedAccounts, TableType::Table), 
     (HashedStorages, TableType::DupSort), 
     (AccountsTries, TableType::Table), 
     (StoragesTries, TableType::DupSort), 
     (TransactionSenders, TableType::Table), 
     (SyncStages, TableType::Table), 
     (SyncStageProgresses, TableType::Table) 
 ]); 
```

**Comment by shekhirin** [comment]
@JosepBove IMO:
1. `HeaderTD` -> `HeaderTerminalDifficulties`, just to be clear what's TD
2. `TransactionBlock` -> `TransactionBlocks`
3. `Plain(Account|Storage)States` -> `Plain(Account|Storage)State`, because it contains the latest version of the state and not multiple
4. `(Accounts|Storages)Tries` -> `(Accounts|Storages)Trie`, same as state

**Comment by JosepBove** [comment]
Okay, I will keep this discussion open for today, if no one has anything to else I will implement the changes

**Comment by shekhirin** [comment]
@mattsse @onbjerg thoughts?

**Comment by JosepBove** [comment]
As no comments were made I start the implementation

**Comment by DaniPopes** [comment]
https://github.com/paradigmxyz/reth/pull/6787
