### ISSUE TITLE
Better tracing error message 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3631]
### Describe the feature

currently we simply use the debug impl of the status enum

https://github.com/paradigmxyz/reth/blob/73bfb2c9a4b46215c293a1156a9a18936ef4f3e9/crates/revm/revm-inspectors/src/tracing/types.rs#L162-L165

not sure what conventional errors other than "Reverted" are but we should at least return `::Revert` as "Reverted"

ref https://github.com/paradigmxyz/reth/pull/3627#pullrequestreview-1516687364

FYI @cjeva10

**Comment by cjeva10** [comment]
#3640.

I just set up a match so that we can put whatever message we want. For now I just did "Reverted" on `::Revert` and then left the default case as it was before.

**Comment by onbjerg** [comment]
Closing ref #3640, feel free to re-open if you have additional ideas for error messages here @mattsse
