### ISSUE TITLE
Improve serde test coverage for rpc-types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3634]
### Describe the feature

a lot of types in the `rpc-types` don't have serde test coverage

## TODO

* get some sample responses from other nodes (alchemy, infura): for example `cast rpc eth_getBlockByNumber "latest" false --rpc-url "https://eth-mainnet.alchemyapi.io/v2/f"` 
* add serde rountrip tests with reth types:
  1. deserialize sample response
  2. serialize into serde_json::Value, assert that sample response (as Value) is a match

bonus points for adjusting order of reth fields to match other clients (sample response)

**Comment by Sabnock01** [comment]
Think I'd like to take a crack at this one. May have some questions though.

**Comment by mattsse** [comment]
great!

pr doesn't need to include all types, can submit several prs
