### ISSUE TITLE
Good first issues for Contributing to the Reth Book?

### ISSUE THREAD

**Issue by namrapatel** [paradigmxyz/reth#365]
### Describe the feature

Hello, wondering if it might be a good idea to solicit help from the community to help write the reth book?

If there was a list of "good-first-issues" for sections in the reth book, and perhaps a tracking issue with some guidelines for contributing to the book, we might be able to bootstrap some help in writing the book. I'd personally be interested in writing some of the sections as notes as I go and read the repo over this winter break from school. 

If this sounds like a good idea, lmk, I'd be happy to make the issues myself, and getting started on some myself, but would request any thoughts on Book Contribution Guidelines from the main contributors.

**Comment by akirillo** [comment]
great idea - @0xKitsune is currently working on one of the first chapters of the book (describing the `stages` crate), once the first version of that is up it'll serve as a good reference for scope / tone / boundary between book & docs, and i'll make a tracking issue then

**Comment by akirillo** [comment]
@namrapatel check out the tracking issue #443 ! I'm going to close this in favor of that.
Re: Book Contribution Guidelines, they are currently not so explicit - for now err on the side of using the `stages` chapter from #360 as a reference point & start discussions in #443
