### ISSUE TITLE
Add propagate field to TransactionValidationOutcome

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3654]
### Describe the feature

the pool internal transaction has a `propagate` field that should determine whether the transaction should be propagated over p2p

this is currently not used but the validator impl should determine this

## TODO

add field `propagate: bool` to

https://github.com/paradigmxyz/reth/blob/b8a547670485f3571f49a348f221688f84495e91/crates/transaction-pool/src/validate/mod.rs#L114-L115 

should be true for for default impls

then use this when creating the `ValidPoolTransaction`

in a next step we can then actually use this when doing propagation

**Comment by lukebrichey** [comment]
Could I try to take on this issue?

**Comment by mattsse** [comment]
please do,

if you need pointers feel free to open draft pr asap and we take it from there

**Comment by mattsse** [comment]
only to the Valid variant

https://github.com/paradigmxyz/reth/blob/f3d7988f684d087a895d288a0041e95a6596b8a6/crates/transaction-pool/src/validate/mod.rs#L25-L33
