### ISSUE TITLE
Improve database does not exist error

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3658]
### Describe the feature

if --datdir folder does not exist, it should mention that in the error

```
Error: Could not open database at path: /root/.local/share/reth/mainnet/db

Caused by:
    Failed to open database: 2

Location:
    crates/storage/db/src/lib.rs:140:14
```

**Comment by blacktoast** [comment]
Can I fix this issue?

I try to  fix this issue  so I just ran the command `reth db stats --datadir test`
and the result is like a picture
<img width="492" alt="Screenshot 2023-07-08 at 1 16 58 AM" src="https://github.com/paradigmxyz/reth/assets/10705018/44d43430-c95c-41d8-87b3-6ca446be90ca">

in my  opinion, when I use `--datadir` command, the error message looks correct

so, Did I miss something?

**Comment by zees-dev** [comment]
Encountering the same issue; on a raspberry pi 4 - using the provided docker compose file (no changes).

**Comment by Sabnock01** [comment]
May I take this one?
