### ISSUE TITLE
Enforce `propagate` transaction setting

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3672]
### Describe the feature

only propagate transactions marked `propagate` ref https://github.com/paradigmxyz/reth/pull/3664

## TODO
enforce propagate by:
* not include them in:
https://github.com/paradigmxyz/reth/blob/42a824cf95e3cfdf2a76efe90bc65daf9012f267/crates/transaction-pool/src/traits.rs#L109-L119
https://github.com/paradigmxyz/reth/blob/42a824cf95e3cfdf2a76efe90bc65daf9012f267/crates/transaction-pool/src/traits.rs#L128-L134
https://github.com/paradigmxyz/reth/blob/42a824cf95e3cfdf2a76efe90bc65daf9012f267/crates/transaction-pool/src/traits.rs#L121-L126

FYI @lukebrichey

**Comment by lukebrichey** [comment]
I'll take this on, thanks for tagging me!
