### ISSUE TITLE
Fix nonce/balance check in standalone block check

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#370]
Code is here: https://github.com/paradigmxyz/reth/blob/b0149f0b9f71b4112d7b11c19ba6f02fd00e583c/crates/consensus/src/verification.rs#L151-L163

a nonce should take care of the author having multiple transactions in the same block. 

For balance, a previous unrelated transaction can change balance of next transaction author account, this would mean we could only know balance and be able to checkit in execution stage. revm is already doing that so we are covered but if I remember correctly OpenEthereum did have this check in the transaction pool, if we want to introduce this we need to how  geth and others are handling it.

**Comment by gakonst** [comment]
Can we close this?
