### ISSUE TITLE
Update txpool metrics properly

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3700]
### Describe the bug

currently txpool metrics are only updated on pool update

instead pool sizes should be updated after inserting txs

### Steps to reproduce

- 

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by gakonst** [comment]
Is it going to be expensive to increment the metrics for each tx that arrives? There's 2 Atomic counters, might be fine, but want to be wary on DOS on every txpool tx as there can be many many of them
