### ISSUE TITLE
Support new discovred noderecord event stream

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3701]
### Describe the feature

Add a way to create a new stream of discovered nodes

## TODO

the discovery service emits an internal event

https://github.com/paradigmxyz/reth/blob/ab2dc70368d953dc0df8d1b87f6af1421af53e22/crates/net/network/src/discovery.rs#L228-L229

we need a way to install listeners same as:

https://github.com/paradigmxyz/reth/blob/ab2dc70368d953dc0df8d1b87f6af1421af53e22/crates/net/network/src/network.rs#L292-L293

Handle sends event to manager, manager calls discovery to create a new listener and sends the listener (receiver) back to handle
discovery notifies listener when a new `Discovered` event is queued

**Comment by lukebrichey** [comment]
Could I take this on?

**Comment by mattsse** [comment]
of course,
lmk if you need pointers

**Comment by supernovahs** [comment]
I have also started on this lol 😅. Too ahead to stop
