### ISSUE TITLE
Fallback to txpool for pending block when no pending block is available from CL

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3702]
### Describe the feature

ref https://github.com/paradigmxyz/reth/issues/3568

when there's no pending block available yet reth should build a local block with pending txs from the pool

the result should be cached for a few seconds

**Comment by onbjerg** [comment]
cc @gakonst do we want this for alpha 5 or even 4? Seems above norm prio since it messes with the consistency of the rpc

**Comment by gakonst** [comment]
Good call - @mattsse assigning given you were on the dup issue and yeah I think we should have it for the next release if we can and is not a huge lift.
