### ISSUE TITLE
Autosealer fails to insert pre-merge blocks

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#3709]
### Describe the bug

In the `latest Block after New HeadBlockHash (Transition Block)` hive test, the test starts by waiting for reth (the autosealer) to exceed the configured TTD, which is 5. This means the starting blocks in the test are "pre-merge".

The autosealer is implemented by implementing a download client, and sending forkchoice updates to the engine API, so reth is prompted to download the newly sealed blocks.

This is problematic because now, we do not run the pipeline for short ranges, and the autosealer sends FCUs for single-block ranges. This means that the blockchain tree is used to insert blocks. The pipeline is the only sync component that does not refuse pre-merge blocks - the blockchain tree refuses the starting blocks in the test.

This results in the test stalling.

### Steps to reproduce

Run `latest Block after New HeadBlockHash (Transition Block)`:
```
./hive --client reth --sim "ethereum/engine" --sim.limit "engine-api/latest Block after New HeadBlockHash \(Transition"
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by int88** [comment]
IMO, there might be three ways to fix this:
1. make blockchain-tree accept pre-merge block but it might have a big impact?
2. make pipeline accept single-block range, I change `MIN_BLOCKS_FOR_PIPELINE_RUN` to 0 which make test passed. So maybe we could make pipeline threshold configurable through command line flag and configure it based on different test cases. (Don't know if it work on hive)
3. Or for pre-merge blocks, use pipeline anyway?

@Rjected WDYT?

**Comment by Rjected** [comment]
> make blockchain-tree accept pre-merge block but it might have a big impact?

We still need the pre-merge checks to satisfy engine API spec requirements, so I'm not sure we can do this.

> make pipeline accept single-block range, I change MIN_BLOCKS_FOR_PIPELINE_RUN to 0 which make test passed. So maybe we could make pipeline threshold configurable through command line flag and configure it based on different test cases. (Don't know if it work on hive)

There is actually already a way to do this, if we configure this to be zero:
https://github.com/paradigmxyz/reth/blob/6799fc3600601d4aadd73ea808734d8bd7f11cda/crates/consensus/beacon/src/engine/mod.rs#L183-L194

to be zero when the `--auto-mine` command is set, then this would force the pipeline to be run always. However we do want to use the blockchain tree (instead of the pipeline) for external FCUs, so I'm not too sure yet how we can make that happen without introducing unnecessary logic into the consensus engine

**Comment by Rjected** [comment]
Not planned - hive tests will not test transitions in the future
