### ISSUE TITLE
RPC stops working after a while

### ISSUE THREAD

**Issue by 3alpha** [paradigmxyz/reth#3712]
### Describe the bug

Reth RPC server stops accepting requests after a while.

### Steps to reproduce

1. Have a service which continously sends RPC requests to reth. In my case it was dshackle load balancer
2. Wait
3. Reth starts rejecting requests with message `Too many connections. Please try again later.`
4. Restart reth and issue goes away

### Platform(s)

Linux (x86)

### What version/commit are you on?

v0.1.0-alpha.3

### What database version are you on?

Current database version: 1
Local database version: 1

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this is the expected behaviour, reth's restricted to only a few concurrent connections by default, but you can set this as high as you like:

```
      --rpc-max-connections <COUNT>
          Maximum number of RPC server connections

          [default: 100]
```

**Comment by JossDuff** [comment]
Is there a way to monitor the active connections?  I hit 1000 fairly quickly running an op-stack setup with `op-reth` and I want to debug this further
