### ISSUE TITLE
Add Unknown block error variant

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3713]
### Describe the feature

> earliest`: The lowest numbered block the client has available; `finalized`: The most recent crypto-economically secure block, cannot be re-orged outside of manual intervention driven by community coordination; `safe`: The most recent block that is safe from re-orgs under honest majority and certain synchronicity assumptions; `latest`: The most recent block in the canonical chain observed by the client, this block may be re-orged out of the canonical chain even under healthy/normal conditions; `pending`: A sample next block built by the client on top of `latest` and containing the set of transactions usually taken from local mempool. Before the merge transition is finalized, any call querying for `finalized` or `safe` block MUST be responded to with `-39001: Unknown block` error

https://github.com/ethereum/execution-apis/blob/6d17705a875e52c26826124c2a8a15ed542aeca2/src/schemas/block.yaml#L109

## TODO

* add unknown block variant to EthApiError (there's already `UnknownBlockNumber` perhaps we can use this instead? needs investigation by sending some sample requests for nonexisting eth_getBlockByNumber to other clients)

* if finalized/safe is queried and we don't have the block, we should return the error:

https://github.com/ledgerwatch/erigon/blob/eae2d9a79cb70dbe30b3a6b79c436872e4605458/turbo/rpchelper/rpc_block.go#L36-L46

ref https://github.com/ledgerwatch/erigon/pull/4436/files

**Comment by Gooong** [comment]
I will take this one.
