### ISSUE TITLE
Add new txpool metrics to dashboard

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3717]
### Describe the feature

Add

https://github.com/paradigmxyz/reth/pull/3714
https://github.com/paradigmxyz/reth/pull/3715

to existing txpool section in dashboard

**Comment by sigridjineth** [comment]
Would like to take this one, please.

**Comment by mattsse** [comment]
ref https://github.com/paradigmxyz/reth/pull/3348

**Comment by onbjerg** [comment]
Closed in #3348
