### ISSUE TITLE
feat(op-reth): [Core | State Transition Modifications] L1 Cost Computation

### ISSUE THREAD

**Issue by clabby** [paradigmxyz/reth#3740]
### Describe the feature

**Diff Category**: Core | State Transition Modifications

### Overview

Transactions on Optimism must pay an additional L1 cost based on the amount of rollup-data-gas they consume, estimated based on gas-price-oracle information and encoded tx size. The L1 base fee, overhead, and scalar can be found in the first transaction of any block on Optimism, the L1 info tx, or in the `L1Block` contract’s storage.

L1 cost function implementation in `op-geth`: https://github.com/ethereum-optimism/op-geth/blob/39d121af21bc4cb45c46edf2dc1bf33daa28c54d/core/types/rollup_l1_cost.go

### Where should this feature live?

The L1 cost function should live in it’s own module in the `reth-revm` crate, as it only needs to be accessed by `reth-revm`'s `executor` module.

### Completion Criteria

- [ ]  The L1 cost function is implemented to parity with the version in `op-geth`.
- [ ]  The rust implementation of the L1 cost function is unit tested.

### Additional context

**Resources**
- [`op-geth` diff](https://op-geth.optimism.io/)
- [`op-erigon` diff](https://op-erigon.testinprod.io/)
- [Optimism Specs](https://github.com/ethereum-optimism/optimism/tree/develop/specs)

**Comment by clabby** [comment]
Requested assignee: @merklefruit

**Comment by rkrasiuk** [comment]
@merklefruit pls engage on this thread. can't seem to assign you

**Comment by merklefruit** [comment]
👋 Hey

**Comment by clabby** [comment]
Closing as completed.
