### ISSUE TITLE
feat(op-reth): [Core | State Transition Modifications] Transaction Processing

### ISSUE THREAD

**Issue by clabby** [paradigmxyz/reth#3741]
### Describe the feature

**Diff Category**: Core | State Transition Modifications

### Overview

Deposit transactions have special processing rules: gas is pre-paid on L1, and deposits with EVM-failure are included with rolled back changes (except mint). For regular transactions, at the end of the transition, the 1559 burn and L1 cost are routed to vaults.

Blocked by:
- #3738 
- #3740 

### Where should this feature live?

The transaction processing changes alter the execution, so the changes for this feature should mostly live in `reth-revm/executor.rs`.

### Completion Criteria
- [ ]  The state transition modifications have been implemented into `reth-revm`'s `executor` module and have parity with the ordering of operations defined in the `op-geth` diff.

### Additional context

**Resources**
- [`op-geth` diff](https://op-geth.optimism.io/)
- [`op-erigon` diff](https://op-erigon.testinprod.io/)
- [Optimism Specs](https://github.com/ethereum-optimism/optimism/tree/develop/specs)

**Comment by clabby** [comment]
Requested assignee: @merklefruit

**Comment by merklefruit** [comment]
👋

**Comment by clabby** [comment]
Closing as completed.
