### ISSUE TITLE
feat(op-reth): [Core | State Transition Modifications] Gas Limit

### ISSUE THREAD

**Issue by clabby** [paradigmxyz/reth#3742]
### Describe the feature

**Diff Category**: Core | State Transition Modifications

### Overview

On Optimism, the gaslimit is free to be set by the Engine API caller, instead of enforcing adjustments of the gaslimit in increments of 1⁄1024 of the previous gaslimit. The gaslimit is changed (and limited) through the `SystemConfig` contract.

### Where should this feature live?

This change alters the EIP-1559 logic, and should probably live in the `reth-beacon-consensus` crate.

### Completion Criteria

- [ ]  If the chain spec has an optimism configuration present, the enforcement of gas limit increments by a factor of 1⁄1024 on a block-to-block basis is lifted.

### Additional context

**Resources**
- [`op-geth` diff](https://op-geth.optimism.io/)
- [`op-erigon` diff](https://op-erigon.testinprod.io/)
- [Optimism Specs](https://github.com/ethereum-optimism/optimism/tree/develop/specs)

**Comment by refcell** [comment]
Requested assignee: @refcell

**Comment by refcell** [comment]
nvm - I believe @clabby implemented this in https://github.com/refcell/reth/commit/1bf2b08c6801bac74d8fc303080b17f93e2ead1e

**Comment by refcell** [comment]
@rkrasiuk would you mind checking this + assigning clabby
