### ISSUE TITLE
Add EIP-4844 blob transaction type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3746]
### Describe the feature

ref https://eips.ethereum.org/EIPS/eip-4844

go impl: https://github.com/ethereum/go-ethereum/blob/2754b197c935ee63101cbbca2752338246384fec/core/types/tx_blob.go#L27-L28

## TODO
* add new blob transaction struct in primitives, see for ref https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/transaction/mod.rs#L115-L118 
* impl encoding

__not__ yet: add to transaction enum https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/transaction/mod.rs#L171-L176

**Comment by i-m-aditya** [comment]
I will pick this
