### ISSUE TITLE
feat(op-reth): [Core] Chain Config

### ISSUE THREAD

**Issue by clabby** [paradigmxyz/reth#3750]
### Describe the feature

**Diff Category**: Core | Chain Config

### Overview

The rollup functionality is enabled with the `optimism` field in the chain config. The EIP-1559 parameters are configurable to adjust for faster more frequent and smaller blocks. The parameters can be overriden for testing.

### Where should this feature live?

This feature will involve a modification to the `ChainSpec` type behind the `optimism` feature flag in `reth-primitives`.

### Completion Criteria

- [ ] The `ChainSpec` type has been modified to include an `optimism` field that contains a struct with the eip1559 elasticity/denominator.

### Additional context

*Resources*
* [`op-geth` diff](https://op-geth.optimism.io)
* [`op-erigon` diff](https://op-erigon.testinprod.io/)
* [Optimism Specs](https://github.com/ethereum-optimism/optimism/tree/develop/specs)

**Comment by roberto-bayardo** [comment]
looking into this one. feel free to assign me?

**Comment by refcell** [comment]
Completed in the linked prs above, can be closed ✅

**Comment by clabby** [comment]
Closing as completed.
