### ISSUE TITLE
feat(op-reth): [Core] TxPool cost updates

### ISSUE THREAD

**Issue by clabby** [paradigmxyz/reth#3751]
### Describe the feature

**Diff Category**: Core | TxPool cost updates

### Overview

Transaction queueing and inclusion in the transaction needs to account for the L1 cost function, defined in #3740.

### Where should this feature live?

Crate: `reth-transaction-pool`

### Completion Criteria

- [x] Deposit transactions are prohibited from existing in the transaction pool, the engine API authenticates deposits.
- [x] The transaction pool considers the l1 info gas overhead and the l1 cost function when determining if the sender has enough ETH to not overdraft.

### Additional context

*Resources*
* [`op-geth` diff](https://op-geth.optimism.io)
* [`op-erigon` diff](https://op-erigon.testinprod.io/)
* [Optimism Specs](https://github.com/ethereum-optimism/optimism/tree/develop/specs)

**Comment by BrianBland** [comment]
> Deposit transactions are prohibited from existing in the transaction pool, the engine API authenticates deposits.
This is implicitly handled by this matcher, which we can codify via a unit test addition.

**Comment by BrianBland** [comment]
> Deposit transactions are prohibited from existing in the transaction pool, the engine API authenticates deposits.

This rule implicitly enforced by [this matcher](https://github.com/paradigmxyz/reth/blob/c1b1eac50505307cfe38fefd6bf3d40c84860d04/crates/transaction-pool/src/validate/eth.rs#L181-L210), which we can codify via a unit test addition.
