### ISSUE TITLE
Continous timeout error between CL<>EL communication

### ISSUE THREAD

**Issue by moose-code** [paradigmxyz/reth#3754]
### Describe the bug

Connection times out on CL when trying to reach EL. 

### Steps to reproduce

1. Run Reth
2. Run Lighthouse

### Node logs

```text
RETH logs:
2023-07-13T10:37:49.281359Z  WARN connection{remote_addr=127.0.0.1:52728 conn_id=199}: jsonrpsee_server::server: HTTP serve connection failed hyper::Error(IncompleteMessage)

Lighthouse:
Jul 13 10:42:12.776 WARN Execution engine call failed            error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 13 10:42:12.776 WARN Error whilst processing payload status  error: Api { error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out) }, service: exec
```

### What version/commit are you on?

commit 99240906a844ae7a8b6b6032fc3b0f64dce22f25 (HEAD -> main, origin/main, origin/HEAD)

### What database version are you on?

Current database version: 1
Local database version: 1

### If you've built Reth from source, provide the full command you used

cargo install --locked --path bin/reth --bin reth

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
can you please also attach the reth logs that happen at the same time?

**Comment by mattsse** [comment]
@Rjected @shekhirin 

this looks weird why is this now happening while the pipeline is active

**Comment by shekhirin** [comment]
I wonder if this change somehow caused it https://github.com/paradigmxyz/reth/blob/dbafe23cce45917a43f6640d71a0216fe3268428/crates/consensus/beacon/src/engine/mod.rs#L1573-L1574

**Comment by mattsse** [comment]
yes found it

the poll loop is now flawed

working on it
