### ISSUE TITLE
CL health events shouldn't be reported during the pipeline sync

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#3756]
### Describe the bug

While pipeline is running, it's expected that we don't process or receive any CL updates, so we shouldn't report warnings about CL health.

### Steps to reproduce

1. Drop database, start node
2. Wait for the pipeline to start
3. Observe CL warning
```console
2023-07-13T12:36:01.414909Z  WARN reth::node::events: Beacon client online, but no consensus updates received for a while. Please fix your beacon client to follow the chain! period=3295.665450884s
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> While pipeline is running, it's expected that we don't process or receive any CL updates, so we shouldn't report warnings about CL health.

I'm actually not sure how CLs behave if we signal "SYNCING", I'd expect that we still receive new FCUs?

**Comment by mattsse** [comment]
could also be related to the poll bug

**Comment by mattsse** [comment]
confirmed poll bug
