### ISSUE TITLE
cmd option parse error when start node with multi rpc namespace

### ISSUE THREAD

**Issue by huahuayu** [paradigmxyz/reth#3769]
### Describe the bug

start node with option 
```
--ws.api debug, eth, net, trace, txpool, web3, rpc
--ws.api "debug, eth, net, trace, txpool, web3, rpc"
--ws.api=debug, eth, net, trace, txpool, web3, rpc
--ws.api=[debug, eth, net, trace, txpool, web3, rpc]
--ws.api="debug, eth, net, trace, txpool, web3, rpc"
```

all failed, get errors

```
error: unexpected argument 'eth,' found

Usage: reth node [OPTIONS]

For more information, try '--help'.
```

or 

```
error: Invalid value 'debug, eth, net, trace, txpool, web3, rpc' for --ws.api <WS_API>: Matching variant not found.
```

### Steps to reproduce

start node with multi api namespace, either rpc or ws.

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
related #3703

we should update the parser to handle this as well

**Comment by PanGan21** [comment]
Hi I was checking this issue. After a bit of debugging I saw that the extra space in front of every arg triggers the error. The proposed solution would be to trim the args in your opinion?

**Comment by huahuayu** [comment]
> Hi I was checking this issue. After a bit of debugging I saw that the extra space in front of every arg triggers the error. The proposed solution would be to trim the args in your opinion?

Good to know the reason, but isn't it too easy to trigger? 

Another reason it's better to fix it is that geth handles it well, actually, I copy the args from my geth startup cmd.

**Comment by mattsse** [comment]
hey,

yeah, the solution is actually just

add `.map(str::trim)` right here:

https://github.com/paradigmxyz/reth/blob/c0cafc7a4f54f66ec450551f7da0d0561b7ad43a/crates/rpc/rpc-builder/src/lib.rs#L607-L607

**Comment by huahuayu** [comment]
Hi @mattsse you can go with the pr, I am not familiar with rust :)

**Comment by PanGan21** [comment]
I can pick it up :)
