### ISSUE TITLE
high reqs/sec puts rpc into a broken state only fixed by restart

### ISSUE THREAD

**Issue by sslivkoff** [paradigmxyz/reth#3774]
### Describe the bug

blasting reth with high reqs/sec load test will put rpc into nonfunctional state. the node does not appear to have crashed but stops serving rpc requests until being restarted

### Steps to reproduce

running a heavy load test like this

`flood eth_call erigon=<IP1>:localhost:8545 reth=<IP2>:localhost:8545 -r 1000 4000 16000 64000 -d 1`

shows an output like this
```
    ┌─────────────────┐
    │ success vs load │
    └─────────────────┘
      rate (rps)  │    erigon  │      reth
    ──────────────┼────────────┼────────────
           1,000  │  1.000000  │  1.000000
           4,000  │  1.000000  │  1.000000
          16,000  │  0.542875  │  1.000000
          64,000  │  0.143219  │  0.012266

    ┌────────────────────┐
    │ throughput vs load │
    └────────────────────┘
      rate (rps)  │  erigon (s)  │  reth (s)
    ──────────────┼──────────────┼────────────
           1,000  │       998.7  │   1,000.5
           4,000  │     3,994.3  │   4,003.0
          16,000  │     7,938.7  │  16,012.7
          64,000  │     8,350.7  │      26.1

    ┌─────────────┐
    │ p90 vs load │
    └─────────────┘
      rate (rps)  │  erigon (s)  │  reth (s)
    ──────────────┼──────────────┼────────────
           1,000  │    0.003536  │  0.000520
           4,000  │    0.002857  │  0.000454
          16,000  │    0.200907  │  0.000426
          64,000  │    0.095769  │  0.000146
```

then running a light load test like this

`flood eth_call erigon=<IP1>:localhost:8545 reth=ubuntu@<IP2>:localhost:8545 -r 8 16 24 -d 1   --debug --deep-check`

shows that rpc has stopped serving requests
```
    ┌─────────────────┐
    │ success vs load │
    └─────────────────┘
      rate (rps)  │    erigon  │      reth
    ──────────────┼────────────┼────────────
               8  │  1.000000  │  0.000000
              16  │  1.000000  │  0.000000
              24  │  1.000000  │  0.000000

    ┌────────────────────┐
    │ throughput vs load │
    └────────────────────┘
      rate (rps)  │  erigon (s)  │  reth (s)
    ──────────────┼──────────────┼────────────
               8  │    9.125029  │  0.000000
              16  │   17.034931  │  0.000000
              24  │   24.958043  │  0.000000

    ┌─────────────┐
    │ p90 vs load │
    └─────────────┘
      rate (rps)  │  erigon (s)  │   reth (s)
    ──────────────┼──────────────┼─────────────
               8  │    0.003883  │  30.000435
              16  │    0.004824  │  30.000371
              24  │    0.004074  │  30.000307
```

restarting reth restores things back to working state

### Node logs

```text
a lot of messages like this:

2023-07-14T08:06:27.686594Z  WARN connection{remote_addr=127.0.0.1:55950 conn_id=19}: jsonrpsee_server::server: HTTP serve connection failed hyper::Error(IncompleteMessage)
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

v0.1.0-alpha.3-dbafe23c

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
can you please share the reth command you used to launch the node

> high reqs/sec puts rpc into a broken state only fixed by restart

> then running a light load test like this

do you mean immediately running this after the heavy load test?

**Comment by sslivkoff** [comment]
command = `cargo r --profile maxperf -- node --http --http.api all --ws --metrics 9001 --rpc-max-connections 10000000 --rpc-max-tracing-requests 1000000 --http.addr "0.0.0.0"`

the machine was reth3

yes, I mean immediately after running the heavy load test. as soon as the heavy load test ends, rpc stops working

**Comment by mattsse** [comment]
yeah this kinda makes sense, because the connections are still present on the server side and waiting to be dropped which likely has lots of latency due to pooled connections.

I need to check if there's a setting for this

**Comment by swbartosz** [comment]
I think this may be related to #3896 
I encountered the same issue. I've tested with `eth_getTransactionReceipt` and `eth_call` (>4k rps), both managed to put the node into a broken state. In my case, the **node stopped processing new blocks** while in the broken state.

Some RPC calls seem to still work, e.g `eth_blockNumber`, while others completely hang (`eth_getTransactionReceipt`, `eth_call`).

Interestingly, the "active requests" will become inflated, as `reth_rpc_server_requests_started` metric increases but `reth_rpc_server_requests_finished` does not when the request is closed.

[on_disconnect](https://github.com/paradigmxyz/reth/blob/8fff8fa8e977386d7c599ca212b75d605b5c88e5/crates/rpc/rpc-builder/src/metrics.rs) is not called either.

jsonrpsee logs for a request that hangs (at this point, all other requests were cancelled).
`Accepting new connection 1/200000` [*](https://github.com/paritytech/jsonrpsee/blob/62bd0cac5b77ce99c67a491b32ba0b1e5c0b96ca/server/src/server.rs#L814C19-L814C19) seems to suggest it's not max rpc bottlenecking the requests.

```
2023-08-31T02:38:27.364939Z DEBUG connection{remote_addr=127.0.0.1:38188 conn_id=28187}: jsonrpsee_server::server: Accepting new connection 1/200000
2023-08-31T02:38:27.364993Z TRACE jsonrpsee_server::server: Request { method: POST, uri: /, version: HTTP/1.1, headers: {"host": "localhost:9563", "user-agent": "curl/7.88.1", "accept": "*/*", "content-type": "application/json", "content-length": "141"}, bo
dy: Body(Streaming) }
2023-08-31T02:38:27.365009Z TRACE jsonrpsee_core::http_helpers: HTTP response body: {"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x5e66f32624751bc11ecddfe1a06f2094a22dd833e5b225c23726a900cbc7595c"],"id":1}
2023-08-31T02:38:27.365023Z TRACE method_call{method="eth_getTransactionReceipt"}: jsonrpsee_core::tracing: recv="{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0x5e66f32624751bc11ecddfe1a06f2094a22dd833e5b225c23726a900
cbc7595c\"]}"
2023-08-31T02:38:27.365029Z TRACE method_call{method="eth_getTransactionReceipt"}: jsonrpsee_types::params: [next_inner] Params JSON: "[\"0x5e66f32624751bc11ecddfe1a06f2094a22dd833e5b225c23726a900cbc7595c\"]"
```

**Comment by DaniPopes** [comment]
Given #4461 and also many other improvements over time, I assume this has been fixed.
