### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by koinov** [paradigmxyz/reth#3775]
### Describe the bug

Today tried syncing alpha-3 two times, locally built and binary from releases. When bodies are 99.9% synced, something totally wrong happens. Grafana shows that all stages are synced, peers are dropping immedaitely. From recovery phase doesn't start.

### Steps to reproduce

I use lighthouse and reth-alpha3

### Node logs

```text
2023-07-14T08:07:02.249052Z TRACE net: Outgoing pending session failed remote_addr=95.216.192.41:30303 peer_id=0xeeccb4ad52a097a2fcdefbf80052b72710e2057d300e216ebb05ada436b1cad9fbe197e22d67d7ff31a197469d84354b054dc697c08aee1b17b1f74a523fb8cb error=Some(Eth(EthHandshakeError(MismatchedGenesis { expected: 0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3, got: 0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b })))
2023-07-14T08:07:02.249060Z TRACE net::peers: handling failed connection remote_addr=95.216.192.41:30303 peer_id=0xeeccb4ad52a097a2fcdefbf80052b72710e2057d300e216ebb05ada436b1cad9fbe197e22d67d7ff31a197469d84354b054dc697c08aee1b17b1f74a523fb8cb err=Eth(EthHandshakeError(MismatchedGenesis { expected: 0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3, got: 0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b }))
```

### Platform(s)

Linux (x86)

### What database version are you on?

Current database version: 1
Local database is uninitialized

### If you've built Reth from source, provide the full command you used

Tried both, build from sourse and released

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks for raising this,

the node logs are unrelated and this is an expected error since the remote node is a polygon node, see genesis hash: https://polygonscan.com/block/0

**Comment by moose-code** [comment]
I am running into the same problem built from source on main at `ad4c590b655bb3cceec334e8713ca3415b7cd207`

You can see if you just leave it running it eventually recovers itself it seems? Just needs some time to relax and chill, maybe grab a coffee before continuing on the good work. 
![Screenshot 2023-07-14 at 13 34 30](https://github.com/paradigmxyz/reth/assets/20556729/43d0a02e-2ee2-4143-9876-145c9a278d09)

**Comment by moose-code** [comment]
Note it isn't specfic to the bodies sync finishing as far as I can tell, I am getting the same issue now that senderRecovery has finished syncing 

repeatedly getting this log:
`2023-07-14T13:21:58.634456Z  INFO reth::cli: Status connected_peers=82 stage=Execution checkpoint=0 eta=unknown`

![Screenshot 2023-07-14 at 14 23 02](https://github.com/paradigmxyz/reth/assets/20556729/e1a71b30-b47d-45f3-86a4-b5608b17bf47)

**Comment by moose-code** [comment]
![Screenshot 2023-07-14 at 14 25 06](https://github.com/paradigmxyz/reth/assets/20556729/abdf233a-edc3-4d4f-b675-6e1d15d07f18)

This time it seems it only hung for about 4min before successfuly resuming

**Comment by koinov** [comment]
I'm on commit e3ac77a now. After 4 hours sync has been resumed.
<img width="511" alt="Снимок экрана 2023-07-14 в 23 30 04" src="https://github.com/paradigmxyz/reth/assets/31383904/660c8231-183b-47ef-b8c4-42ff468ec6d1">
<img width="772" alt="Снимок экрана 2023-07-14 в 23 29 10" src="https://github.com/paradigmxyz/reth/assets/31383904/655027fb-fbdd-4d44-b670-c1041c13d012">

**Comment by Rjected** [comment]
Should have been fixed by https://github.com/paradigmxyz/reth/pull/3783

**Comment by mattsse** [comment]
@koinov to add a bit more context, reth was treating single block responses as malicious behaviour, but in the recent days there was a block that exceeded the commonly used soft limit of 2MB which resulted in a single block response that reth then treated as bad behaviour and penalized the peer.

this check has now been removed to adhere to the softlimit correctly which should fix the stalled bodies stage.

closing optimistically
