### ISSUE TITLE
feat(op-reth): [Node | CLI] New flags

### ISSUE THREAD

**Issue by merklefruit** [paradigmxyz/reth#3794]
### Describe the feature

**Diff Category**: Node | CLI

### Overview

Some new CLI flags need to be added in order to make some Optimism-related functionality directly available to all node users.

CLI flags modifications:

- Transactions can be forwarded to an RPC for sequencing.
- The tx pool propagation can be enabled/disabled. 
- ~Historical calls can be forwarded to a legacy node.~ (out of scope for now) 
- ~The Optimism bedrock fork activation can be changed for testing.~ (out of scope for now)

### Where should this feature live?

The CLI flag changes will go in the main `reth` binary, under `bin/reth`. 

### Completion Criteria

- [x] added flag to forward txs to a sequencer endpoint
- [x] added flag to enable/disable transaction pool gossip
- [x] added flag to compute pending block

### Related issues

The actual implementation of these CLI flags will be addressed in other issues:

- #3795 
- #3797
- #4004

### Additional context

_Resources_

- [`op-geth` diff](https://op-geth.optimism.io/)
- [`op-erigon` diff](https://op-erigon.testinprod.io/)
- [Optimism Specs](https://github.com/ethereum-optimism/optimism/tree/develop/specs)

**Comment by roberto-bayardo** [comment]
done here: https://github.com/anton-rs/op-reth/pull/33
