### ISSUE TITLE
feat(op-reth): [Node] Option to disable transaction pool gossip

### ISSUE THREAD

**Issue by merklefruit** [paradigmxyz/reth#3795]
### Describe the feature

**Diff Category**: Node | Tx gossip disable option

### Overview

Add the ability for the transaction pool to disable gossiping of transactions. 

Blocked by: 

- #3794

### Where should this feature live?

This change should probably be implemented in the `transaction-pool` crate.

### Completion Criteria

- [ ] implemented the ability to control tx gossip to parity with the version in `op-geth`.
- [ ] added relevant unit tests for this functionality

### Additional context

_Resources_

- [`op-geth` diff](https://op-geth.optimism.io/)
- [`op-erigon` diff](https://op-erigon.testinprod.io/)
- [Optimism Specs](https://github.com/ethereum-optimism/optimism/tree/develop/specs)

**Comment by cjeva10** [comment]
@merklefruit Can we use the noop pool that's already implemented?

**Comment by rkrasiuk** [comment]
@cjeva10 noop pool is just that. it does nothing for any of the methods called. whereas the requirement here is to be able to maintain the transaction pool without propagating the transactions to the network

**Comment by refcell** [comment]
Completed in https://github.com/anton-rs/op-reth/pull/71 ✅
