### ISSUE TITLE
Include `yParity` field in Transaction objects (type 1 and 2)

### ISSUE THREAD

**Issue by ryanschneider** [paradigmxyz/reth#3798]
### Describe the bug

Seems like a lot (all?) of the clients, reth included, are returning `v` instead of `yParity` in their JSON representation of EIP-2718 type `0x1` (EIP-2930) and `0x2` (EIP-1559) transactions.

Recent discussion on Eth R&D discord here: https://discord.com/channels/595666850260713488/745077610685661265/1129684798340878457

The execution-api schemas actually do point this out: https://github.com/ethereum/execution-apis/blob/main/src/schemas/transaction.yaml#L157 but this wasn't noticed until recently, seems like most EL clients followed geth's impl and it wasn't until recently that when an EL correctly followed the spec it was noticed by Micah that this breaks Prysm (and presumably other CLs as it expects the `v` field).

Micah also opened a tracking issue in geth here: https://github.com/ethereum/go-ethereum/issues/27727

As mentioned there, I think the safest short-term behavior is to return both `v` and `yParity` on these tx types, then eventually drop `v` for these tx types (keeping it of course for Legacy and EIP-155 txs).

I suspect this will require customizing the serde (de)serialization of `Transaction` type here: https://github.com/paradigmxyz/reth/blob/085a703d7c8f7d7bbb310f8cbcda3632b7f85ad9/testing/ef-tests/src/models.rs#L392

### Steps to reproduce

curl any RPC that returns a type 1 or 2 transaction object, for example this random Sepolia tx https://sepolia.etherscan.io/tx/0xbad8ca05c9f95ea37cdb9f6353579fcf9a8c6b9604fe8188585ef0252eba1c90:

```
curl -X "POST" http://localhost:8545 \
     -H 'Content-Type: application/json' \
     -d $'{
  "id": 1,
  "method": "eth_getTransactionByHash",
  "jsonrpc": "2.0",
  "params": [
    "0xbad8ca05c9f95ea37cdb9f6353579fcf9a8c6b9604fe8188585ef0252eba1c90"
  ]
}'
{"jsonrpc":"2.0","result":{"hash":"0xbad8ca05c9f95ea37cdb9f6353579fcf9a8c6b9604fe8188585ef0252eba1c90","nonce":"0x156","blockHash":"0xa7d4c8ca72c74e54e0f3629949320b52bd679e699f90b264b545f8897b48d1a9","blockNumber":"0x1621a1","transactionIndex":"0x4","from":"0x6cc9397c3b38739dacbfaa68ead5f5d77ba5f455","to":"0x855847fc07879844c64ee1af1c65d80b0d6893b6","value":"0x1bc16d674ec80000","gasPrice":"0x59682f07","gas":"0x5208","maxFeePerGas":"0xee6b2800","maxPriorityFeePerGas":"0x59682f00","input":"0x","r":"0xc569c92f176a3be1a6352dd5005bfc751dcb32f57623dd2a23693e64bf4447b0","s":"0x1a891b566d369e79b7a66eecab1e008831e22daa15f91a0a0cf4f9f28f47ee05","v":"0x1","chainId":"0xaa36a7","accessList":[],"type":"0x2"},"id":1}
```

The signature portion should be: `{ ... "r":"0xc569c92f176a3be1a6352dd5005bfc751dcb32f57623dd2a23693e64bf4447b0","s":"0x1a891b566d369e79b7a66eecab1e008831e22daa15f91a0a0cf4f9f28f47ee05","yParity":"0x1" ... }` rather than `"v":"0x1"`.

### What version/commit are you on?

90b6d006d1fc660c4883a4335e42f8e760c4adbe (latest main)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
Looks like we would need to change the `Signature` type and add a `yParity` flag for non-legacy transactions. We mirrored geth's behavior for this and just put the y parity bit in the `v` field:
https://github.com/paradigmxyz/reth/blob/99a8e0f98211be6afb49e8e04ca61ddd7e352583/crates/rpc/rpc-types/src/eth/transaction/signature.rs#L22-L39
