### ISSUE TITLE
Add primer on all transaction types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3803]
### Describe the feature

reth has a lot of different transaction types that can be confusing for new contributors

## todo

Add short primer about txs and why they exists

**Comment by Rjected** [comment]
Pasting a response I made to a "why are there so many transaction types" question from telegram that might be useful for someone adding these docs:


> Dan Cline, [Jul 7, 2023 at 9:15:17 PM]:
> just a start but:
> 
> we have a separate type specifically for rpc, because the rpc transaction contains extra fields related to block context that does not make sense in other contexts, for example a pending transaction in the transaction pool. a pending tx does not have a block, so the type that is used in the txpool needs to be separate from the rpc type.
> 
> another reason is the difference between transactions _with_ a recovered senders, and transactions _without_ a recovered sender. When a transaction is fetched over p2p, it includes the transaction signature, but does not include the sender, because that is expected to be recovered from the signature + tx. So there needs to be separate types for recovered and non-recovered transactions.
> 
> example conversion that someone might need to do:
> non-recovered tx --- signature recovery ---> recovered tx --- fetch block context ---> rpc tx
> 
> There are _also_ multiple transaction types in ethereum in general:
>  * Legacy 
>  * Eip1559
>  * Eip2930
> 
> A transaction can also be either signed or unsigned

**Comment by mattsse** [comment]
can be closed, thanks!
