### ISSUE TITLE
Put rpc gas cap in EthApi in a new type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3813]
### Describe the feature

the configurable rpc gas cap accepts an u64

https://github.com/paradigmxyz/reth/blob/eb32fd3c6d2feec5e845981ecbe91139656e6bff/crates/rpc/rpc/src/eth/api/mod.rs#L79-L86

which should default to 50M: see https://github.com/paradigmxyz/reth/pull/3812

to make this easier we should put this in a new type so you can invoke it via `Default::default()`

## TODO

add new type wrapper for gas cap in rpc module
change `new` to accept `impl Into<GasCap>`

**Comment by altugbakan** [comment]
Hey, can I work on this?

**Comment by mattsse** [comment]
yes!
