### ISSUE TITLE
Invalid block metrics graph

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#3814]
The invalid headers cache already has some metrics tracking invalid blocks and cache inserts:
https://github.com/paradigmxyz/reth/blob/01e1344cc1175b7c7110498db6e5319329b62472/crates/consensus/beacon/src/engine/invalid_headers.rs#L89-L101

These should be neatly summarized with new graphs in the reth grafana dashboard

**Comment by darknight** [comment]
@Rjected Hi, I'm reading reth codebase and found this `good first issue`, just wondering is it still undone? If so, I'd like to give it a try.

**Comment by Rjected** [comment]
> Hi, I'm reading reth codebase and found this good first issue, just wondering is it still pending to do? If so, I'd like to give it a try.

@darknight yep! if you want to work on it I can assign you to the issue - let me know if you have any questions!

**Comment by darknight** [comment]
> > Hi, I'm reading reth codebase and found this good first issue, just wondering is it still pending to do? If so, I'd like to give it a try.
> 
> @darknight yep! if you want to work on it I can assign you to the issue - let me know if you have any questions!

@Rjected Thanks. As for this issue, if I understand correctly, all I need to do is create a new panel on `reth grafana dashboard`, right? If so, where can I find this dashboard and how to request for edit permission?

**Comment by Rjected** [comment]
> > > Hi, I'm reading reth codebase and found this good first issue, just wondering is it still pending to do? If so, I'd like to give it a try.
> > 
> > 
> > @darknight yep! if you want to work on it I can assign you to the issue - let me know if you have any questions!
> 
> @Rjected Thanks. As for this issue, if I understand correctly, all I need to do is create a new panel on `reth grafana dashboard`, right? If so, where can I find this dashboard and how to request for edit permission?

There shouldn't be any permissions necessary - it's easiest to set up and view the grafana dashboard locally with our docker-compose setup. See https://github.com/paradigmxyz/reth/pull/4391 for how to set up a sepolia node with grafana, sepolia takes up much less space and should take significantly less time to sync than a mainnet node, making it useful for development. on a laptop.

Here's an example of an existing panel: https://github.com/paradigmxyz/reth/blob/2fc574f32999fbfd966ad137c9b3cfc190e48e48/etc/grafana/dashboards/overview.json#L3430-L3460

`etc/grafana/dashboards/overview.json` is where the panel would be added

**Comment by JosepBove** [comment]
Hey, are you stucked? Do you need help?

**Comment by darknight** [comment]
> Hey, are you stucked? Do you need help?

Hey @JosepBove, thanks for asking. I was distracted by other tickets so didn't start this one instantly.

If you have interest, feel free to take it from my side. I can come back later to pick up other tickets whenever I'm available.

**Comment by JosepBove** [comment]
I will take it in around 3h if it's not done as it's a fast thing

**Comment by JosepBove** [comment]
Under which category would you add this visualizations?

**Comment by 0x-dx** [comment]
If it's still open, I can start looking into this.

**Comment by mattsse** [comment]
closing as outdated
