### ISSUE TITLE
Metrics for `make_canonical` latency when processing forkchoice updates

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#3815]
The Engine API `forkchoiceUpdated` call has one main expensive operation, which is the `make_canonical` blockchain tree method call:
https://github.com/paradigmxyz/reth/blob/01e1344cc1175b7c7110498db6e5319329b62472/crates/consensus/beacon/src/engine/mod.rs#L628-L671

We should measure the latency for this method call expose it as a metric. Maybe we should include the following cases as separate metrics to distinguish between different cases:
* `make_canonical` returns `CanonicalOutcome::AlreadyCanonical`
* `make_canonical` returns `CanonicalOutcome::Committed`
* `make_canonical` returns an error
* latency metric for _any_ outcome (any `CanonicalOutcome` or error)

**Comment by cjeva10** [comment]
Hi, I just opened a PR for this: #3862

**Comment by cjeva10** [comment]
Sorry, I had a mix-up with different Github accounts.

I opened a new PR #3865, PTAL.
