### ISSUE TITLE
Longest sidechain metric

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#3816]
We already have metrics for the number of sidechains in the blockchain tree, but we have little insight into how large these sidechains are in metrics. It would be interesting to track at least the length of the longest sidechain.

The current blockchain tree metrics are defined here:
https://github.com/paradigmxyz/reth/blob/01e1344cc1175b7c7110498db6e5319329b62472/crates/blockchain-tree/src/metrics.rs#L6-L14

And mainly updated here:
https://github.com/paradigmxyz/reth/blob/01e1344cc1175b7c7110498db6e5319329b62472/crates/blockchain-tree/src/blockchain_tree.rs#L1096-L1109

**Comment by cjeva10** [comment]
Hi, I opened a quick PR @ #3864
