### ISSUE TITLE
Output block number and hash in pipeline stage logs

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#3818]
### Describe the feature

During the pipeline sync, it's not clear towards which block number or hash the node is syncing. The user can also get confused by a bunch of `Forkchoice updated` messages thinking that might be the hash the pipeline is currently working towards:
```console
2023-07-17T03:30:27.216765Z  INFO reth::node::events: Stage finished executing pipeline_stages=9/13 stage=MerkleExecute block=17624279 checkpoint=100.0% eta=unknown
2023-07-17T03:30:32.291278Z  INFO reth::node::events: Executing stage pipeline_stages=10/13 stage=TransactionLookup from=0 checkpoint=0 eta=unknown
2023-07-17T03:30:36.157074Z  INFO reth::node::events: Forkchoice updated head_block_hash=0xd87622dfddb65ec1526dc40a0d229c91f234c36339f1ac9884e6d61303f054d3 safe_block_hash=0x53038188d4ec6f12d38730ee2ba7727a3150143499bdd04153135aaa05fccb3b 
```

We should output the final block number and hash in the `Executing stage` and `Stage finished` messages.

**Comment by Va-a-real-noob-coder** [comment]
Hey i'm sorry i don't have a node to test my code, i've wrote something if anyone can test it, i don't have the hardware requieremnt to run a node for reth sadly 


struct NodeState {
    // existing fields...
    latest_canonical_block_hash: Option<String>,
}


fn handle_consensus_engine_event(&mut self, event: BeaconConsensusEngineEvent) {
    match event {
        BeaconConsensusEngineEvent::CanonicalBlockAdded(block) => {
            self.latest_canonical_engine_block = Some(block.number);
            self.latest_canonical_block_hash = Some(block.hash.to_string());  // Assuming `hash` is an array or vector of bytes

            info!(number=block.number, hash=?block.hash, "Block added to canonical chain");
        }
        // existing match arms...
    }
}

fn handle_pipeline_event(&mut self, event: PipelineEvent) {
    match event {
        PipelineEvent::Running { pipeline_position, pipeline_total, stage_id, checkpoint } => {
            let notable = self.current_stage.is_none();
            self.current_stage = Some(stage_id);
            self.current_checkpoint = checkpoint.unwrap_or_default();

            if notable {
                info!(
                    pipeline_stages = %format!("{}/{}", pipeline_position, pipeline_total),
                    stage = %stage_id,
                    from = self.current_checkpoint.block_number,
                    checkpoint = %self.current_checkpoint,
                    eta = %self.eta,
                    latest_canonical_block = %self.latest_canonical_engine_block.unwrap_or(self.current_checkpoint.block_number),
                    latest_canonical_hash = %self.latest_canonical_block_hash.as_deref().unwrap_or("unknown"),
                    "Executing stage",
                );
            }
        }
        // existing match arms...
    }
}

**Comment by shekhirin** [comment]
@Va-a-real-noob-coder we want to log the block hash and number of pipeline sync, so it doesn't really relate to the event of adding a new canonical block to the chain. I think we should rather pass it from the place where we know up to which tip we're syncing, and add a block number of the tip when it becomes available after the Headers stage finishes.

Also, there's no need to fully sync the node to test this changes, it should be enough to just start the sync and obverse the logs.

**Comment by FredCoen** [comment]
I'm happy to give this one a go

**Comment by shekhirin** [comment]
@FredCoen great, assigned you!

**Comment by AbnerZheng** [comment]
Is this issue addressed by https://github.com/paradigmxyz/reth/pull/5518?
