### ISSUE TITLE
Add timestamp field to CanonicalStateUpdate pool update type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3829]
### Describe the feature

forks are now activated by timestamp, in order to update the pool's validator (supported tx type, additional checks) for specific forks we need a way to access the timestamp

## TODO

add timestamp: u64 to:

https://github.com/paradigmxyz/reth/blob/ec672238ca6addf62fac89de027bd2320b49182e/crates/transaction-pool/src/traits.rs#L392-L396

next when can add a new validator update function that's called on pool update, but can be done as followup

**Comment by PanGan21** [comment]
How is this timestamp used in here? Or it is supposed to be done in another issue?

https://github.com/paradigmxyz/reth/blob/ec672238ca6addf62fac89de027bd2320b49182e/crates/transaction-pool/src/pool/mod.rs#L250C1-L273C6

**Comment by mattsse** [comment]
we will need to add another function to 

https://github.com/paradigmxyz/reth/blob/26b1ffa92aa2aca6712284b03c3323458cfbe9df/crates/transaction-pool/src/validate/mod.rs#L56-L56

so it can update enforced hardforks
