### ISSUE TITLE
Log filter is broken when a topic is empty 

### ISSUE THREAD

**Issue by ngotchac** [paradigmxyz/reth#3851]
### Describe the bug

When calling `eth_getLogs` with such a filter:
```json
{
  "topics": [
    ["0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"],
    [],
    ["0x0000000000000000000000000c17e776cd218252adfca8d4e761d3fe757e9778"],
  ]
}
```
The topics filter is completely ignored, all logs from the block range are returned.

However, it works when instead of `[]` we pass `[null]`, although it should be equivalent.

NB: I don't have a Reth instance running to test, I tested against the shared RPC URL during the Reth presentation at EthCC ;)

### Steps to reproduce

This can be tested w/
```bash
curl <RETH_RPC> -H "Content-Type: application/json" --data '{"method":"eth_getLogs","params":[{"fromBlock": "0xfc359e", "toBlock": "0xfc359e", "topics": [["0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"], [], ["0x0000000000000000000000000c17e776cd218252adfca8d4e761d3fe757e9778"]]}],"id":1,"jsonrpc":"2.0"}' | jq '.result'
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
right empty list is supposed to match anything

> * [] “anything”

nice find, I'll get that fixed
