### ISSUE TITLE
report transaction response error accurately

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3855]
### Describe the feature

all variants are currently reported the same:

https://github.com/paradigmxyz/reth/blob/7476120d8170d7269ec8525f173edac995e12385/crates/interfaces/src/p2p/error.rs#L76-L85

https://github.com/paradigmxyz/reth/blob/7476120d8170d7269ec8525f173edac995e12385/crates/net/network/src/transactions.rs#L540-L542

even though we have different weights for timeout and bad message

## TODO

report peer based on error variant

**Comment by altugbakan** [comment]
Can I work on this?
