### ISSUE TITLE
Help in retroactively patching DB synced before commit d60aef5a

### ISSUE THREAD

**Issue by datskos** [paradigmxyz/reth#3859]
### Describe the feature

Nodes such as mine that were synced before commit d60aef5a are missing a `0` in the AccountHistory table for each account that was funded at mainnet genesis.

Example: the following account was funded at genesis and has never (as of now) transacted

```
$ cast balance 0x2de31Afd189a13A76ff6fE73eAD9F74Bb5c4a629
6000000000000000000000

$ cast balance 0x2de31Afd189a13A76ff6fE73eAD9F74Bb5c4a629 -B $[ $(cast bn) - 2]
0
```

This appears to have no negative impact on syncing since only the current balance is queried during sync.

However, I'm unable to trace blocks that contain transactions where these genesis accounts first transacted (ex: tracing `0x626589af1ae9f7fd261178b5c9775ceca0a3a3013859fa260824a77ba427b8e0` fails) since the tracer sees the balance as `0` for for the first transaction for each of the genesis accounts.

If you already have a script to help in patching the DB by prepending `0` for each of the genesis accounts could you share it? It'd be much appreciated! CC'ing @rkrasiuk based on TG discussion

**Comment by datskos** [comment]
Thinking something like this:

(first time writing Rust and first time dealing with reth-db so probably not the best way to do this). Please let me know if you have an official script or if I'm making some big mistakes/wrong assumptions here

```rust
/// prepend 0 to AccountHistory for all genesis accounts
fn main() -> eyre::Result<()> {
    let db = open_db(Path::new(&std::env::var("RETH_DB_PATH_CAREFUL_DESTRUCTIVE")?), None)?;

    let spec = ChainSpecBuilder::mainnet().build();
    let factory = ProviderFactory::new(&db, spec.clone().into());
    let mut provider = factory.provider_rw()?;

    let mut map: BTreeMap<Address, Vec<u64>> = BTreeMap::new();

    let _ = &db.view(|tx| {
        for addr in spec.genesis.alloc.keys() {
            let mut r = read_all_history(tx, *addr).unwrap();
            if r.get(0) != Some(&0) {
                r.insert(0, 0);
            }
            map.insert(*addr, r);
        }
    })?;

    let mut cursor = provider.deref_mut().tx_mut().cursor_write::<AccountHistory>()?;
    for addr in spec.genesis.alloc.keys() {
        unwind_all_shards(&mut cursor, *addr)?;
    }

    provider.insert_account_history_index(map)?;
    provider.commit()?;

    Ok(())
}

fn read_all_history(tx: &Tx<RO, WriteMap>, addr: H160) -> eyre::Result<Vec<u64>> {
    let mut bn: BlockNumber = 0;
    let mut blocks: Vec<u64> = Vec::new();
    while bn < u64::MAX {
        let mut cursor = tx.cursor_read::<AccountHistory>()?;
        let kv = cursor.seek(ShardedKey::new(addr, bn))?.filter(|(key, _)| key.key == addr);
        if let Some(kv) = kv {
            let mut bns: Vec<u64> = kv.1.iter(0).map(|v| v as u64).collect();
            blocks.append(&mut bns);
            bn = kv.0.highest_block_number;
        } else {
            break;
        }
    }

    Ok(blocks)
}

fn unwind_all_shards(cursor: &mut Cursor<RW, AccountHistory>, addr: Address) -> eyre::Result<()> {
    let start_key = ShardedKey::last(addr);
    let mut item = cursor.seek_exact(start_key)?;
    while let Some((ref sharded_key, _)) = item {
        if sharded_key.key != addr {
            break;
        }
        cursor.delete_current()?;
        item = cursor.prev()?;
    }

    Ok(())
}
```

**Comment by onbjerg** [comment]
I think @rkrasiuk had one IIRC?

**Comment by rkrasiuk** [comment]
I'm currently swamped w/ other high prio issues, so if anyone wants to take this - feel free. The idea is to find genesis accounts in the history tables, check whether they have genesis allocation recorded and, if not, shift all of the indices for the given accounts by prepending index `0` to the `IntegerList`. This should be done in [`init_genesis`](https://github.com/paradigmxyz/reth/blob/72ab361d67b2cddf767956f9a9d93805c3c3fb64/bin/reth/src/init.rs#L37)

**Comment by supernovahs** [comment]
I can try this one ?

**Comment by joshieDo** [comment]
think we can close this one ? @rkrasiuk

**Comment by rkrasiuk** [comment]
def
