### ISSUE TITLE
LogBloom check failed in auto-mine standalone mode

### ISSUE THREAD

**Issue by manylov** [paradigmxyz/reth#3868]
### Describe the bug

I use node with custom genesis file and auto-mine flags. 
I tried to deploy contract that has event emitted in the constructor.
I got error:

![telegram-cloud-photo-size-2-5321501245120302098-y](https://github.com/paradigmxyz/reth/assets/738898/74a22c1c-f260-4bfc-9909-cb6809af2dc1)

When I deploy same contract without event emitted, all is ok.

Commenting logbloom check here https://github.com/paradigmxyz/reth/blob/main/crates/revm/src/executor.rs#L552 helps, contract with event deployed ok.

### Steps to reproduce

1. Run node with this command:
```
reth node --chain ./mainnet.json --datadir ./db --auto-mine --http  --http.api "admin,debug,eth,net,trace,txpool,web3,rpc" --disable-discovery
```

I use this mainnet.json:
```
{
  "config": {
    "chainId": 1,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirGlacierBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "arrowGlacierBlock": 0,
    "grayGlacierBlock": 0,
    "shanghaiTime": 0,
    "terminalTotalDifficulty": 0,
    "terminalTotalDifficultyPassed": true,
    "ethash": {}
  },
  "nonce": "0x0",
  "timestamp": "0x0",
  "extraData": "0x",
  "gasLimit": "0x4c4b40",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "0x890E1C14433196dF62fceA48Cea1E79CBa77DE4F": {
      "balance": "0x56bc75e2d63100000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "baseFeePerGas": "0x0"
}
```

2. Try to deploy contract like this:
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.10;

contract NFT {
    uint256 public currentTokenId;

    event AnotherLog();

    constructor() {
        emit AnotherLog();
        currentTokenId = 1;
    }

    function getTokenId() public view returns (uint256) {
        return currentTokenId;
    }
}

```

You'll see error in node logs.

3.  Remove event emittance from constructor, try to deploy this version - everything will be ok then.

### Platform(s)

Mac (Intel)

### What version/commit are you on?

Commit SHA: 39cd0e07

### What database version are you on?

Current database version: 1
Local database version: 1

### If you've built Reth from source, provide the full command you used

cargo install --locked --path bin/reth --bin reth

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by pistomat** [comment]
Working on this.
