### ISSUE TITLE
WsProvider got doubled newBlock event

### ISSUE THREAD

**Issue by manylov** [paradigmxyz/reth#3870]
### Describe the bug

When ran node at least in auto-mine dev mode with --ws and --ws.api flags, I created ws provider in js/rs project and subscribed on new block notifications.
I got doubled notification on every new block.

### Steps to reproduce

1. command to start node 

```
reth node --chain ./mainnet.json --datadir ./db --auto-mine --ws --ws.api "admin, debug, eth, net, trace, txpool, web3, rpc" --http  --http.api "admin,debug,eth,net,trace,txpool,web3,rpc" --disable-discovery
```

2. script to subscribe to new blocks
```
const wsProvider = new ethers.WebSocketProvider("ws://localhost:8546");
wsProvider.on('block', (blockNumber) => {
    console.log('New block:', blockNumber);
  });
```

### Platform(s)

Mac (Intel)

### What version/commit are you on?

39cd0e07

### What database version are you on?

Current database version: 1

### If you've built Reth from source, provide the full command you used

cargo install --locked --path bin/reth --bin reth

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this should no longer be an issue
