### ISSUE TITLE
trace_call VmTrace specification

### ISSUE THREAD

**Issue by pistomat** [paradigmxyz/reth#3883]
### Describe the bug

I do not know where reth gets the specification for parity style tracing, so this may be a design choice rather than a bug, but I would like some clarification for this issue.

This regards the parity style `trace_call`, specifically `vmTrace`. Reth's `VmExecutedOperation` has the member [push](https://github.com/paradigmxyz/reth/blob/08403c80e210187f1f8e9c9c3d686a789dc73c4a/crates/rpc/rpc-types/src/eth/trace/parity.rs#L311) as an Option
```
pub struct VmExecutedOperation {
    ...
    /// The stack item placed, if any.
    pub push: Option<H256>,
    ...
}
```

whilst both [Parity](https://github.com/openethereum/parity-ethereum/blob/55c90d4016505317034e3e98f699af07f5404b63/ethcore/trace/src/types/trace.rs#L557) and [ethers-rs](https://github.com/gakonst/ethers-rs/blob/030bf439a100dcacd2e968e3114de0612229056b/ethers-core/src/types/trace/mod.rs#L148) implement it as a Vec
```
pub struct VMExecutedOperation {
    ...
    /// The stack item placed, if any.
    pub push: Vec<U256>,
    ...

```
[Erigon](https://github.com/ledgerwatch/erigon/blob/9d3551f8cf3f2835ba8212473024a609a53e24f7/turbo/jsonrpc/trace_adhoc.go#L118) also implements it as a vector:
```
Push  []string      `json:"push"`
```

This breaks compatibility, for example using Reth node as a ethers-rs http provider causes it to fail on deserialization. 

Example of a serialized trace can be seen [here](https://github.com/gakonst/ethers-rs/blob/030bf439a100dcacd2e968e3114de0612229056b/ethers-core/src/types/trace/example-trace-str.rs#L88), vmTrace push should be serialized as:
```
"push": [
    "0x60"
],
```
but is
```
"push": "0x0000000000000000000000000000000000000000000000000000000000000060",
```

Also the [VmInstruction](https://github.com/paradigmxyz/reth/blob/08403c80e210187f1f8e9c9c3d686a789dc73c4a/crates/rpc/rpc-types/src/eth/trace/parity.rs#L293) is missing the `op` and `idx` variables, but ethers-rs has the `op` as non-optional which also breaks deserialization.

### Steps to reproduce

1. Call `trace_call` on a reth node.

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
right, since push can be more, this should be a vec

**Comment by pistomat** [comment]
Sure I can do that 💪
