### ISSUE TITLE
Error intrinsic gas too high for eth call 

### ISSUE THREAD

**Issue by 0xZangetsudev** [paradigmxyz/reth#3887]
### Describe the bug

Hello, 

I have an issue with my reth node, I have opened http port, when I execute my swapeth from uniswap (code below) its working with alchemy http rpc but not my node (its running and working with lighthouse as consensus).

So if I only change the provider the code will works as intended but not with reth

```
use ethers::prelude::*;
use ethers::types::U256;
use eyre::Result;
use std::sync::Arc;


abigen!(
    UniswapV2Router02,
    r#"[
        function swapExactETHForTokens(uint amountOutMin, address[] calldata path, address to, uint deadline)
    ]"#,
);


#[tokio::main]
async fn main() -> Result<()> {
    let provider = Provider::<Http>::try_from("http://localhost:8545")?;
    let wallet = "xxxx"
        .parse::<LocalWallet>()?
        .with_chain_id(1 as u64);

    let signer = SignerMiddleware::new(provider, wallet);
    let signer = Arc::new(signer);

    let router_address = "xxxx".parse::<Address>()?;
    let token = "xxx".parse::<Address>()?;
    let weth = "xxx".parse::<Address>()?;

    let uv2_router = UniswapV2Router02::new(router_address, signer.clone());
    let _ierc = IERC20::new(weth, signer.clone());

    let amount_in: i128 = 221865;

    let _tx = uv2_router
        .swap_exact_eth_for_tokens(
            U256::try_from(amount_in).unwrap(),
            vec![weth, token],
            signer.address(),
            U256::from(1690197673 + 600),
        )
        .value(600200000 as i128)
        .send()
        .await?
        .await?;

    Ok(())
}
```
This create the message : intrinsic gas too high and it's the same if I setup the tx as a legacy one with gas.

### Steps to reproduce

cargo run

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
Can you please post the request json?

**Comment by 0xZangetsudev** [comment]
I'm not sure about what are you asking as its just an eth send but the json response that I got in the console is this one 

''' 
Error: (code: -32000, message: intrinsic gas too high, data: None)
'''

Hope thats what you're asking

**Comment by mattsse** [comment]
yes please post the json of the eth send

**Comment by 0xZangetsudev** [comment]
how do I access this? My code just broadcast the tx, do you want that I remove the send method and try to implement a json?

**Comment by onbjerg** [comment]
@0xZangetsudev You can do 

```rs
 let _tx = uv2_router
        .swap_exact_eth_for_tokens(
            U256::try_from(amount_in).unwrap(),
            vec![weth, token],
            signer.address(),
            U256::from(1690197673 + 600),
        )
        .value(600200000 as i128);
println!("{}", serde_json::to_string(&_tx.tx));
```

Note that you need to depend on `serde_json` if you don't already

**Comment by mattsse** [comment]
you can also enable tracing and all requests objects are logged via `RUST_LOG=ethers`

having the actual request object would make it a lot easier to debug things like this

**Comment by 0xZangetsudev** [comment]
Here is the result : (now its saying insufficient funds for gas * price + value, data: None) -> I think sometimes I get the first error sometimes this one and I have the funds.

Here is the json with serde_json:

`Ok("{\"to\":\"0x7a250d5630b4cf539739df2c5dacb4c659f2488d\",\"value\":\"0x23c65340\",\"data\":\"0x7ff36ab500000000000000000000000000000000000000000000000000000000000362a900000000000000000000000000000000000000000000000000000000000000800000000000000000000000008e07bc45d3f2fbf7f35cafb0be74f257d87d39570000000000000000000000000000000000000000000000000000000064c4c60f0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000004e58ea38f4915850fbe1577cd818a09ba673c8ee\"}")
`

For enabling tracing you mean by adding env logger and log in my cargo toml and doing debug! or error! for example? Or using tracing and tracing subscriber?

**Comment by 0xZangetsudev** [comment]
@onbjerg will do it in 1 day max because my node is syncing

@mattsse do you mean by adding env_logger and log to my cargo toml and using debug! or error! OR by adding tracing_subscriber to my cargo toml and using Fmt ?

**Comment by 0xZangetsudev** [comment]
@onbjerg here is the response when using serde_json :
`
Ok("{\"to\":\"0x7a250d5630b4cf539739df2c5dacb4c659f2488d\",\"value\":\"0xea60\",\"data\":\"0x7ff36ab500000000000000000000000000000000000000000000000000000000000362a900000000000000000000000000000000000000000000000000000000000000800000000000000000000000006c826d75b95806a121a6b1e39831b15a4c1199910000000000000000000000000000000000000000000000000000000064c4edbb0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000004e58ea38f4915850fbe1577cd818a09ba673c8ee\"}")
`

**Comment by mattsse** [comment]
what's the node's version you used because this error should be unreachable in eth_call
 
https://github.com/paradigmxyz/reth/blob/a371cb8bc133bbc014cad4e43f9a26b8ba4f5522/crates/rpc/rpc/src/eth/revm_utils.rs#L213-L215

**Comment by 0xZangetsudev** [comment]
Its on 0.1.4

**Comment by 0xZangetsudev** [comment]
Tried with the new 0.1.0 alpha 5, Its for a swap on uniswap router for weth to usdc and the account has 50 dollars in it + and I ask for like cents of usdc, I always get 

`Error: (code: -32003, message: insufficient funds for gas * price + value, data: None)`

And when I print the response using serde_json I got this :

`Ok("{\"to\":\"0x7a250d5630b4cf539739df2c5dacb4c659f2488d\",\"value\":\"0x2c68af0bb140000\",\"data\":\"0x7ff36ab500000000000000000000000000000000000000000000000002c68af0bb1400000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000c8f9d330e8d55fdbf34a9abab9d4cd8dd26a45b20000000000000000000000000000000000000000000000000000000064d50df60000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48\"}")
`

**Comment by mattsse** [comment]
at what block did you send these?

hard to replicate the exact request because of the expiration

**Comment by mattsse** [comment]
I think this has something to do with how init costs are recorded, so with low balance there might be an issue where gas price 0 still results in errors.

could you please try with balance override for your sender?

**Comment by 0xZangetsudev** [comment]
Hey what do you mean by balance override?

For blocks you can try with whatever time you want you will still have the issue

**Comment by mattsse** [comment]
> For blocks you can try with whatever time you want you will still have the issue

the provided call reverts due to expiration though

> Hey what do you mean by balance override?

override argument in the request

**Comment by 0xZangetsudev** [comment]
I passed through transaction request to pass gas and gas price + I have gave more ETH to my wallet and now its working so I guess we can close it but two questions if you may :

1) only if you have time (I understand if not) : how to do your balance override just by curiosity?

2) how much is required in eth or how much is required to have left? Like I mean for example I don't know it was like 0.02 eth funded in wallet for a 0.008eth trade that works in geth but not reth (its an example) so how much should it be the minimum or the difference to be left with ?

Thanks again :)

**Comment by mattsse** [comment]
sorry I forgot to answer here...

> how to do your balance override just by curiosity?

you can do this via the overrides argument

we fixed a bunch of gas issues since so these differences should be fixed
