### ISSUE TITLE
Add metrics for rpc servers

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3907]
### Describe the feature

we want metrics for rpc server such as:

* requests
* ws sessions
* call times

this can best be achieved via the jsonrpsee logger API: https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/logger.rs

## TODO
* add `metrics` type `RpcServerMetrics` (see other Metrics derive macro structs for references)that implements the logger trait
* integrate in rpc server instance

all in rpc-builder crate

**Comment by mattsse** [comment]
sweet, lmk if you need pointers by opening a draft pr

**Comment by 0xprames** [comment]
opened a draft pr with a skeleton of adding the `RpcServerMetrics` struct, implementing `jsonrpsee::Logger` and wiring it through to the `ServerBuilder` call we make


I do have some open questions regarding WS specific metrics( you mentioned WS sessions above), specifically on how to differentiate between WS/Http metrics in the case where its the same port thus the same server that's returned

I think the general metrics (request count, call duration etc) makes sense

**Comment by 0xprames** [comment]
came back to this after doing some other stuff.

 think `I do have some open questions regarding WS specific metrics( you mentioned WS sessions above), specifically on how to differentiate between WS/Http metrics` that was a dumb question oops:
```
/// The transport protocol used to send or receive a call or request.
#[derive(Debug, Copy, Clone)]
pub enum TransportProtocol {
	/// HTTP transport.
	Http,
	/// WebSocket transport.
	WebSocket,
}
```

the `jsonrpsee` logging middleware gives us a `TransportProtocol` to differentiate between WS requests and http requests, working on fleshing out the `Logger` implementation no. Given this, I think scoping the metrics dynamically as `rpc_server_http_ws` or `rpc_server_http`/`rpc_server_ws` doesn't make sense. let me change that as well

**Comment by mattsse** [comment]
nice you found the right type already
we can do

```rust
fn on_connect(
		&self,
		_remote_addr: SocketAddr,
		_request: &HttpRequest,
		transport: TransportProtocol,
	) {
		if matches!(transport, TransportProtocol::WebSocket) {
		   // this is a new websocket connection
		}
	}
```

**Comment by 0xprames** [comment]
not sure why the PR didn't close this (I didn'ts specify the issue tag properly in the PR description?)

but we should be good to close this out
