### ISSUE TITLE
code: -32603, internal error while tracing

### ISSUE THREAD

**Issue by ritzdorf** [paradigmxyz/reth#3915]
### Describe the bug

Tracing using `debug_traceTransaction` works for many transactions, but not all. It seems to fail for `0x6279ddfc4eb98b38ebf2119b6381c0265d4b8137af407e57b6c4f52996225eae`.  

### Steps to reproduce

1. reth node --chain mainnet --http --http.api admin, debug, eth, net, trace, txpool, web3, rpc
2. curl http://127.0.0.1:8545 -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceTransaction","params":["0x6279ddfc4eb98b38ebf2119b6381c0265d4b8137af407e57b6c4f52996225eae"], "id":1,"jsonrpc":"2.0"}'

### Node logs

```text
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 2 but the index is 2', crates/revm/revm-inspectors/src/tracing/types.rs:248:35
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.4 Commit SHA: b2b2cbe 

### What database version are you on?

Current database version: 1
Local database version: 1

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by ritzdorf** [comment]
For your convenience, the node log points here: https://github.com/paradigmxyz/reth/blob/b2b2cbedb527c429128ef9302e006bc9af958fb5/crates/revm/revm-inspectors/src/tracing/types.rs#L248

**Comment by mattsse** [comment]
thanks for this,

I suspect that this is somehow related to the failed transaction 

https://etherscan.io/tx/0x6279ddfc4eb98b38ebf2119b6381c0265d4b8137af407e57b6c4f52996225eae

checking

**Comment by ritzdorf** [comment]
Thanks @mattsse 

> I suspect that this is somehow related to the failed transaction

Yes, that is my suspicion also. The transaction a lot of failed internal transactions https://etherscan.io/tx/0x6279ddfc4eb98b38ebf2119b6381c0265d4b8137af407e57b6c4f52996225eae/advanced#internal

Thanks for the great work. Let me know if I can help.

**Comment by mattsse** [comment]
any other TXs where tracing is wrong?

**Comment by ritzdorf** [comment]
> any other TXs where tracing is wrong?

Another one is: 0x5745d002debfd23b9db3975d4498d41353a678f04e4acd106c61fc78c4184a7a

It is very similar and also fails: https://etherscan.io/tx/0x5745d002debfd23b9db3975d4498d41353a678f04e4acd106c61fc78c4184a7a/advanced#internal
