### ISSUE TITLE
Tracing Error: code: -32008, Response is too big

### ISSUE THREAD

**Issue by ritzdorf** [paradigmxyz/reth#3916]
### Describe the bug

Tracing using debug_traceTransaction works for many transactions, but not all. It seems to fail for `0xb553013bd562c57bfc88d1a7608c2af64cdce183e8c7f1a272a0d4fb7a96acea`. The received error is:

```
{"code":-32008,"message":"Response is too big","data":"Exceeded max limit of 104857600"}
```

### Steps to reproduce

1. ```reth node --chain mainnet --http --http.api admin, debug, eth, net, trace, txpool, web3, rpc```
2. ```curl http://127.0.0.1:8545 -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceTransaction","params":["0xb553013bd562c57bfc88d1a7608c2af64cdce183e8c7f1a272a0d4fb7a96acea"], "id":1,"jsonrpc":"2.0"}'```

### Node logs

```text
ERROR connection{remote_addr=127.0.0.1:51500 conn_id=12}: jsonrpsee_core::server::helpers: Error serializing response: Error("Memory capacity exceeded", line: 0, column: 0)
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.4 Commit SHA: b2b2cbe

### What database version are you on?

Current database version: 1
Local database version: 1

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
we recently bumped the size defaults, but only after the last release 

https://github.com/paradigmxyz/reth/pull/3850

can be modified via --rpc-max-response-size flag
