### ISSUE TITLE
Latitude server disk mount instructions

### ISSUE THREAD

**Issue by ipatka** [paradigmxyz/reth#3918]
### Describe the change

When setting up RETH on latitude with the `c3.large.x86` server I encountered a few undocumented steps. Documenting here in case it helps others. The main issue I encountered was that the default docker data directory is a 447GB disc which quickly ran out of space when syncing. Follow these steps to use one of the >3TB drives

1. Install docker per this guide https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04
2. Create a new docker directory, ex. `/mnt/docker`
3. Mount one of the larger drives to the new directory `mount /dev/nvme1n1 /mnt/docker`. Follow steps in this guide to permanently mount the drive https://linuxhint.com/how-to-mount-drive-in-ubuntu/
4. Change the default docker data root per this guide https://philpug.com/2021/11/14/how-to-move-docker-data-directory-to-a-different-mount-ubuntu/

`/etc/docker/daemon.json`
```
{
   "data-root": "/mnt/docker"
}
```

5. Run reth per the docker guide, notice that the big drive is now the one storing the data
![Screen Shot 2023-07-25 at 6 23 15 PM](https://github.com/paradigmxyz/reth/assets/4401444/fde72f02-799d-4c88-9c4b-29ed0bdd73cf)

### Additional context

This is probably because I chose 'no RAID' so possibly irrelevant. Instead it is recommended to choose RAID0 on the latitude page to share space across all available discs to avoid this issue

**Comment by AndreMiras** [comment]
Thanks for documenting these steps.
I think usually recommended to simply leverage docker volume binding/mounting at run time.
This is done using the -v/--volume flag as documented here:
- https://docs.docker.com/engine/reference/commandline/run/#volume
- https://paradigmxyz.github.io/reth/installation/docker.html#using-plain-docker

**Comment by ipatka** [comment]
ah thanks, that's surely a better way
