### ISSUE TITLE
Incorrect result of trace_transaction

### ISSUE THREAD

**Issue by ritzdorf** [paradigmxyz/reth#3919]
### Describe the bug

The trace of transaction `0x4c5e1a6763ea859bcdcffa541f1f7fd7e6f9c2a632a67e8c879ef333703ba5dc` is incorrect. 

It should be:

- CALL: 0x3d0768da09ce77d25e2d998e6a7b6ed4b9116c2d -> 0x412fda7643b37d436cb40628f6dbbb80a07267ed
- SUICIDE: 0x412fda7643b37d436cb40628f6dbbb80a07267ed -> 0x3d0768da09ce77d25e2d998e6a7b6ed4b9116c2d

Source: https://etherscan.io/vmtrace?txhash=0x4c5e1a6763ea859bcdcffa541f1f7fd7e6f9c2a632a67e8c879ef333703ba5dc&type=parity

Instead it is:

```
  [
    {
      "type": "suicide",
      "action": {
        "address": "0x412fda7643b37d436cb40628f6dbbb80a07267ed",
        "refundAddress": "0x3d0768da09ce77d25e2d998e6a7b6ed4b9116c2d",
        "balance": "0x0"
      },
      "result": {
        "gasUsed": "0x94",
        "output": "0x"
      },
      "subtraces": 0,
      "traceAddress": [],
      "transactionPosition": 1,
      "transactionHash": "0x4c5e1a6763ea859bcdcffa541f1f7fd7e6f9c2a632a67e8c879ef333703ba5dc",
      "blockNumber": 51921,
      "blockHash": "0x6add712197981e241e52e5dc9abbe704d24f0312f1f10c02f43f8bc81742cffd"
    }
  ]
```

As expected, the same error appears in `trace_block` for the corresponding block.

### Steps to reproduce

1. ```reth node --chain mainnet --http --http.api admin, debug, eth, net, trace, txpool, web3, rpc```
2. ```curl http://127.0.0.1:8545 -X POST -H "Content-Type: application/json" --data '{"method":"trace_transaction","params":["0x4c5e1a6763ea859bcdcffa541f1f7fd7e6f9c2a632a67e8c879ef333703ba5dc"], "id":1,"jsonrpc":"2.0"}' ```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.4 Commit SHA: b2b2cbe

### What database version are you on?

Current database version: 1
Local database version: 1

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by ritzdorf** [comment]
The result of tx `0xad41f53723d29e06ba82a3e510510c6f68ba2b7d5a6b823019cb71c1b33a1ddf` also looks weird. It is a suicide with two subtraces. Unless, I am missing something suicides do not and did not have subtraces. 


```
  [
    {
      "type": "suicide",
      "action": {
        "address": "0x01957911244e546ce519fbac6f798958fafadb41",
        "refundAddress": "0xa1eec0a9b7c50b8e79a0d9b8760bc5681fb199ec",
        "balance": "0x0"
      },
      "result": {
        "gasUsed": "0x291d",
        "output": "0x"
      },
      "subtraces": 2,
      "traceAddress": [],
      "transactionPosition": 0,
      "transactionHash": "0xad41f53723d29e06ba82a3e510510c6f68ba2b7d5a6b823019cb71c1b33a1ddf",
      "blockNumber": 56319,
      "blockHash": "0xff7fb3acb6edb8fbabbe3c7362a1f56f3ec03e565ca2eea5c790eadb6887762f"
    },
    {
      "type": "call",
      "action": {
        "from": "0x01957911244e546ce519fbac6f798958fafadb41",
        "callType": "call",
        "gas": "0x8fc",
        "input": "0x",
        "to": "0xa1eec0a9b7c50b8e79a0d9b8760bc5681fb199ec",
        "value": "0xde0b6b3a7640000"
      },
      "result": {
        "gasUsed": "0x0",
        "output": "0x"
      },
      "subtraces": 0,
      "traceAddress": [
        0
      ],
      "transactionPosition": 0,
      "transactionHash": "0xad41f53723d29e06ba82a3e510510c6f68ba2b7d5a6b823019cb71c1b33a1ddf",
      "blockNumber": 56319,
      "blockHash": "0xff7fb3acb6edb8fbabbe3c7362a1f56f3ec03e565ca2eea5c790eadb6887762f"
    },
    {
      "type": "call",
      "action": {
        "from": "0x01957911244e546ce519fbac6f798958fafadb41",
        "callType": "call",
        "gas": "0x8fc",
        "input": "0x",
        "to": "0xa1eec0a9b7c50b8e79a0d9b8760bc5681fb199ec",
        "value": "0xde0b6b3a7640000"
      },
      "result": {
        "gasUsed": "0x0",
        "output": "0x"
      },
      "subtraces": 0,
      "traceAddress": [
        1
      ],
      "transactionPosition": 0,
      "transactionHash": "0xad41f53723d29e06ba82a3e510510c6f68ba2b7d5a6b823019cb71c1b33a1ddf",
      "blockNumber": 56319,
      "blockHash": "0xff7fb3acb6edb8fbabbe3c7362a1f56f3ec03e565ca2eea5c790eadb6887762f"
    }
  ]
```

Parity Trace is also quite different:
https://etherscan.io/vmtrace?txhash=0xad41f53723d29e06ba82a3e510510c6f68ba2b7d5a6b823019cb71c1b33a1ddf&type=parity

**Comment by mattsse** [comment]
nice, thank you for all of these.

will take a closer look at how suicides/selfdestructs are recorded
