### ISSUE TITLE
CLI flag for secondary nodes

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#3924]
### Describe the feature

Add a `--secondary` CLI flag which configures the ports of the node to avoid conflicts with the defaults. This is useful for running multiple nodes on the same machine.

**Comment by alessandromazza98** [comment]
I can work on this issue.

Just a question. Do you want this field to set a different but fixed port number (example 8552) or do you want to set it in a dynamic way?

The fixed way is no doubts easier. Let me know.

In the meanwhile I can start working on the fixed way.
