### ISSUE TITLE
Integrate rpc server metrics into dashboard

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3925]
### Describe the feature

new set of metrics for rpc server added in #3913

## TODO
* integrate in dashboard
  * active requests
  * histogram
  * active websocket connections

**Comment by alessandromazza98** [comment]
Hi Matt, I can take this one. Actually I never implemented these kind of things, but I want to try.

Is something related to this file?: https://github.com/paradigmxyz/reth/blob/main/etc/grafana/dashboards/overview.json

**Comment by Rjected** [comment]
> Is something related to this file?: https://github.com/paradigmxyz/reth/blob/main/etc/grafana/dashboards/overview.json

Yep, that's where the graphs would need to be added. I recommend running a sepolia node with metrics enabled, and setting up prometheus + grafana so you can actually see the graphs as you're adding them.
