### ISSUE TITLE
Make fee bump rules configurable in txpool

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3945]
### Describe the feature

currently, PRICE_BUMP is a constant:

https://github.com/paradigmxyz/reth/blob/f98b1524bba6ef3e48fbd421eb540ef363db8b27/crates/transaction-pool/src/pool/txpool.rs#L1105-L1109

we want a setting that allows us to configure this check:

https://github.com/paradigmxyz/reth/blob/f98b1524bba6ef3e48fbd421eb540ef363db8b27/crates/transaction-pool/src/pool/txpool.rs#L1018-L1021

two approaches
a) a config struct that has required fee bumps depending on the _existing_ txtype
b) a trait that provides this function which we can then box

however if we want b)'s implementation to also be configurable then we end up at a)

so I think we should go with a), a struct that has

* default price_bump (PRICE_BUMP == 10%)
* replace blob tx price bump (100%)

should be added as new struct to

https://github.com/paradigmxyz/reth/blob/f98b1524bba6ef3e48fbd421eb540ef363db8b27/crates/transaction-pool/src/config.rs#L10-L12

**Comment by altugbakan** [comment]
Can I take this on?

**Comment by mattsse** [comment]
cool, thanks!

**Comment by tcoratger** [comment]
@altugbakan Sorry, I forgot to report myself, I quickly started working on it for a few minutes, if you need help don't hesitate :)

**Comment by altugbakan** [comment]
Thanks! Will do.
