### ISSUE TITLE
Add getreceipts eth handler implementation

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3956]
### Describe the feature

GetReceipts is still part of the active eth cap so we should implement a handler implementation here

https://github.com/paradigmxyz/reth/blob/4ab924c5d361bbfdcdad9f997d16d67b4a1730b7/crates/net/network/src/eth_requests.rs#L214-L214

ref https://github.com/ethereum/devp2p/blob/master/caps/eth.md

this will require adding a trait bound here

https://github.com/paradigmxyz/reth/blob/4ab924c5d361bbfdcdad9f997d16d67b4a1730b7/crates/net/network/src/eth_requests.rs#L72-L73

for ReceiptsProvider

**Comment by v4lproik** [comment]
Hello, I would love to give this a try if it's available :)

**Comment by mattsse** [comment]
@v4lproik ty, but looks like this was already sniped by @tcoratger 

if you would'd like to work on another good-first-issue and don't find anything that's interesting please let me know and we'll find something
