### ISSUE TITLE
make rpc-types completely standalone

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3964]
### Describe the feature

remove any reth/jsonrpsee dependencies from reth-rpc-types

**Comment by supernovahs** [comment]
Is there additional work pending for this?

**Comment by mattsse** [comment]
ideally we want to get rid of all the conversion/build functions in the rpc-types crate so that it only uses types like H256,U256 etc.

I think we move things like: https://github.com/paradigmxyz/reth/blob/c423514321c2d2e67a156681d5602cb1707852e3/crates/rpc/rpc-types/src/eth/transaction/mod.rs#L79-L87

to a new crate like rpc-types-compat or something

**Comment by supernovahs** [comment]
https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-types/src/eth/transaction/signature.rs should also be moved right?

**Comment by mattsse** [comment]
right!
we also want to move this

**Comment by supernovahs** [comment]
Should TransactionSigned, Withdrawal be removed?
https://github.com/paradigmxyz/reth/blob/b8b7ad60ada5e808c11beba2810c108d46d849bb/crates/rpc/rpc-types/src/eth/engine/payload.rs#L4.

Also , do we want to also remove constants imported through reth_primitives?
`constants::{MAXIMUM_EXTRA_DATA_SIZE, MIN_PROTOCOL_BASE_FEE_U256}`

**Comment by mattsse** [comment]
hmm,

yeah we now need to duplicate the Withdrawal type and move the `TryFrom` impls to compact I believe

**Comment by supernovahs** [comment]
What next?

**Comment by mattsse** [comment]
done,
tysm for this
