### ISSUE TITLE
Can't build the project locally

### ISSUE THREAD

**Issue by rafaelescrich** [paradigmxyz/reth#3970]
### Describe the bug

fatal: Authentication failed for 'https://github.com/paradigmxyz/uint/'
error: failed to load source for dependency `ruint`

Caused by:
  Unable to update https://github.com/paradigmxyz/uint#38f565ff

Caused by:
  failed to fetch into: /Users/rafael/.cargo/git/db/uint-10eb28276571b47e

Caused by:
  process didn't exit successfully: `git fetch --tags --force --update-head-ok 'https://github.com/paradigmxyz/uint' '+refs/heads/*:refs/remotes/origin/*' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)

### Steps to reproduce

Just cloned the project
Compile using cargo build --release
I suppose that reth uses a module that is closed source and as cargo needs to git clone all dependencies and I don't have access to this repository, I can't build.

### Platform(s)

Mac (Apple Silicon)

### If you've built Reth from source, provide the full command you used

cargo build --release

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by jnmclarty** [comment]
I was able to compile from the tip of main tonight from source.  I was on Ubuntu 22.

**Comment by wakamex** [comment]
I had the same issue, `git pull upstream main` was my solution, since I forgot I had cloned my fork

**Comment by mattsse** [comment]
closing since this should not be on issue on main
