### ISSUE TITLE
Sync stalls during Bodies stage

### ISSUE THREAD

**Issue by abdullathedruid** [paradigmxyz/reth#3974]
### Describe the bug

I have been syncing the node over the last 2 weeks. The initial pass completed all stages up to block 1781009. 
On the second pass, the syncing process has been stuck on the Bodies stage, and is halted at block 1761009 (according to grafana sync progress). I don't know if there is any significant with the numbers being exactly 80,000 blocks apart.

The logs of the node appears that connections with peers are opening and disconnecting. I first noticed the issue yesterday and the only thing that I noticed was that the syncing process had stalled.
After reviewing the logs today, I can see that there are errors regarding the database (write error code 27). I am not sure whether this is the cause of the issue, or the symptom (given that I noticed the stalling issue first)

I had started the sync progress whilst on version 0.1.0-alpha.2 and have since updated to version 0.1.0-alpha.4.

### Steps to reproduce

I am unsure on steps to reproduce. I have run the node with the following command:

`command=bash -c 'home/abdulla/.cargo/bin/reth node --datadir="/var/data/ethereum/datadir" --authrpc.jwtsecret="var/data/ethereum/datadir/jwt.hex" --authrpc.addr "127.0.0.1" --authrpc.port "8551" --http --http.addr="0.0.0.0" --http.port="8545" --http.api="eth,admin,debug,net,trace,txpool,web3,rpc" --http.corsdomain="*" --ws -vvvvv --metrics "127.0.0.1:9001"'
`

I would be happy to provide additional information

### Node logs

```text
2023-07-27T17:33:00.712716Z  WARN trust_dns_proto::xfer::dns_exchange: failed to associate send_message response to the sender
2023-07-27T17:33:00.712728Z  WARN trust_dns_proto::xfer::dns_exchange: failed to associate send_message response to the sender
2023-07-27T17:33:00.712735Z  WARN trust_dns_proto::xfer::dns_exchange: failed to associate send_message response to the sender
2023-07-27T17:33:01.366910Z ERROR execute{stage=Bodies}: sync::pipeline: Stage encountered a fatal error: An internal database error occurred: Database write error code: 27. stage=Bodies
2023-07-27T17:33:01.376780Z  INFO reth::cli: Wrote network peers to file peers_file="/var/data/ethereum/datadir/knownpeers.json"
2023-07-27T17:33:05.023082Z  INFO reth::cli: reth 0.1.0-alpha.4 (b2b2cbed) starting
2023-07-27T17:33:05.023286Z  INFO reth::cli: Configuration loaded path="/var/data/ethereum/datadir/reth.toml" 2023-07-27T17:33:05.023297Z  INFO reth::cli: Opening database path="/var/data/ethereum/datadir/db"
2023-07-27T17:33:05.108275Z  INFO reth::cli: Database opened                                                                                                                     
2023-07-27T17:33:05.108298Z  INFO reth::cli: Starting metrics endpoint addr=127.0.0.1:9001
2023-07-27T17:33:05.109076Z  INFO reth::cli: Pre-merge hard forks (block based):
2023-07-27T17:36:50.459953Z  INFO reth::cli: Transaction pool initialized
2023-07-27T17:36:50.460100Z  INFO reth::cli: Connecting to P2P network
2023-07-27T17:36:50.461108Z  INFO net::peers: Loading saved peers file=/var/data/ethereum/datadir/known-peers.json
2023-07-27T17:36:50.506317Z  WARN consensus::engine: Pipeline sync progress is inconsistent first_stage_checkpoint=17779598 inconsistent_stage_id=Bodies inconsistent_stage_check point=17761009
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth 0.1.0-alpha.4 (b2b2cbed)

### What database version are you on?

Current database version: 1
Local database version: 1

### If you've built Reth from source, provide the full command you used

cargo install --locked --path bin/reth --bin reth

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by bemevolent** [comment]
Can you share more specs: os/cpu/ram/disk and pagesize for the os `getconf PAGESIZE`. Also results from `mdbx_chk`

```
make db-tools
db-tools/mdbx_chk $(reth db path)/mdbx.dat
```

**Comment by abdullathedruid** [comment]
Sure!

- Operating System: Ubuntu 20.04.6 LTS
- Kernel: Linux 5.15.0-78-generic
- Architecture: x86-64
- CPU: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 core)
- RAM: 16 GB DIMM DDR4 Synchronous 2400MHz (2x8GB)
- Disks: 500GB Samsung SSD 850
- 4TB LVM2 (2 x 2TB Samsung SSD 870) 

`getconf PAGESIZE` -> `4096`

I've ran `mdbx_chk -vv` and it appears to be stuck, here are the logs so far (within 10 minutes): 
```
mdbx_chk v0.12.6-0-gc019631a (2023-04-29T21:30:35+03:00, T-44de01dd81ac366a7d37111eaf72726edebe5528)
Running for /var/data/ethereum/datadir/db/mdbx.dat in 'read-only' mode...
   open-MADV_DONTNEED 534633805..534773760
   readahead OFF 0..534633805
 - monopolistic mode
 - current boot-id 9cd0d952e1b548ac-b2ed12c45cd24924
 - pagesize 4096 (4096 system), max keysize 1980..2022, max readers 114
 - mapsize 4398046511104 (4.00 Tb)
 - dynamic datafile: 12288 (12.00 Kb) .. 4398046511104 (4.00 Tb), +4294967296 (4.00 Gb), -8589934592 (8.00 Gb)
 - current datafile: 2190433320960 (1.99 Tb), 534773760 pages
 - meta-0: steady txn#4602071, tail
 - meta-1: steady txn#4602075, stay
 - meta-2: steady txn#4602078, head
 - performs check for meta-pages clashes
 - performs full check recent-txn-id with meta-pages
 - transactions: recent 4602078, latter reader 4602078, lag 0
Traversal b-tree by txn#4602078...
 - found AccountChangeSet area
```

I'll keep it running a bit longer to see if anything else happens, but it looks like it's stuck here after finding the AccountChangeSet area

**Comment by bemevolent** [comment]
Based on the libmdbx `TOO_LARGE` error and the fact the current datafile is right at 2TB leads me to believe maybe LVM isn't spanning both physical volumes correctly? I'd double check that configuration.

Otherwise will need someone more familiar with reth than myself to help troubleshoot

**Comment by abdullathedruid** [comment]
This was the rest of the logs (I ended up running ctrl-C) 
```
Traversal b-tree by txn#4602078...                
 - found AccountChangeSet area
 - found AccountHistory area
 - found AccountsTrie area
 - found BlockBodyIndices area
 - found BlockOmmers area
 - found BlockWithdrawals area
 - found Bytecodes area
 - found CanonicalHeaders area
 - found HashedAccount area
 - found HashedStorage area
 - found HeaderNumbers area
 - found HeaderTD area
 - found Headers area
 - found PlainAccountState area
 - found PlainStorageState area
 - found Receipts area
 - found StorageChangeSet area
 - found StorageHistory area
 - ^C - interrupted by signal
 - pages: walked 342706866, left/unused 191926939
     @GC: subtotal 2903, branch 1, large 2886, leaf 16
 - usage: total 1403727323136 bytes, payload 1039041626199 (74.0%), unused 364685696937 (26.0%)
 - summary: average fill 74.0%, 0 problems
Processing @GC...
 - key-value kind: ordinal-key => single-value, flags: integerkey
 - last modification txn#4602076
 - page size 4096, entries 2886
 - b-tree depth 2, pages: branch 1, leaf 16, overflow 2886
 - summary: 0 records, 0 dups, 0 key's bytes, 0 data's bytes, 0 problems
 - space: 1073741824 total pages, backed 534773760 (49.8%), allocated 534633805 (49.8%), remained 539
108019 (50.2%), used 342706866 (31.9%), gc 0 (0.0%), detained 0 (0.0%), reclaimable 0 (0.0%), available 539108019 (50.2%)
Skip processing @MAIN since b-tree is corrupted (0 problems)
No error is detected, elapsed 31159.030 seconds
```

You may be right about LVM as this is the first time I've tried to use it.
```
abdulla@abdulla-MS-7A67:~/reth$ sudo vgs
  VG   #PV #LV #SN Attr   VSize  VFree
  data   2   1   0 wz--n- <3.64t 142.03g
abdulla@abdulla-MS-7A67:~/reth$ sudo pvs
  PV         VG   Fmt  Attr PSize  PFree  
  /dev/sda   data lvm2 a--  <1.82t      0 
  /dev/sdc   data lvm2 a--  <1.82t 142.03g
abdulla@abdulla-MS-7A67:~/reth$ sudo lvs
  LV       VG   Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  ethereum data -wi-ao---- 3.50t
```
This is particularly interesting as when I run `df` I get the following
```
abdulla@abdulla-MS-7A67:~/reth$ df -h /var/data/ethereum
Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/data-ethereum  3.5T  2.1T  1.3T  63% /var/data/ethereum
```

**Comment by bemevolent** [comment]
Not using `ext3` filesystem, right? That would have a max file limit of 2TB. Can you share `lsblk -f`?

**Comment by abdullathedruid** [comment]
Yeah that's it, I'm using ext3 😶‍🌫️
I didn't even think about the file size limit so thanks for all your help in debugging this issue!

I'm going to close this issue as it isn't related to reth!
