### ISSUE TITLE
Add cancun header fields to rpc types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3981]
### Describe the feature

ref #3972

add optional fields:
 blob_gas_used,
 excess_blob_gas

to anywhere where header info is used, can look for `withdrawals_root` for reference

for example 

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-types/src/eth/block.rs#L238-L240

**Comment by erik-rt** [comment]
Hey I can take this one, is it simply a matter of adding those two fields to wherever `Header` is defined and implemented? And I take it the type should be a `U256`?

**Comment by mattsse** [comment]
sure, actually setting the fields is currently blocked until we have #3972

but we can add all the fields already

**Comment by mattsse** [comment]
oh, yeah I think waiting until we land #3972 would make it easier

**Comment by mattsse** [comment]
unblocked now

**Comment by erik-rt** [comment]
Awesome, I've almost got it. I need some guidance on the following and then we'll be good to go. In the following code, if the field values remain as `None` then all tests are passing.

https://github.com/paradigmxyz/reth/blob/dee14c7b4cc27fdc78819820b831d981f77c222a/crates/rpc/rpc-types/src/eth/engine/payload.rs#L175C7-L177

I've tried adding the following values:

```rust
blob_gas_used: Some(
    payload
        .blob_gas_used
        .uint_try_to()
        .map_err(|_| PayloadError::BlobGasUsed(payload.blob_gas_used))?,
),
excess_blob_gas: Some(
    payload
        .excess_blob_gas
        .uint_try_to()
        .map_err(|_| PayloadError::ExcessBlobGas(payload.excess_blob_gas))?,
),
```

but this causes the following tests to fail:

```
failures:
    engine::tests::new_payload::new_payload_before_forkchoice
    engine::tests::new_payload::payload_known
    engine::tests::new_payload::payload_parent_unknown
    engine::tests::new_payload::payload_pre_merge
```

Also I realize this isn't explicitly a `Header` so please let me know if the above would be outside the scope of this issue. If so, I'll remove the changes within this file.

**Comment by mattsse** [comment]
@Rjected ptal

**Comment by Rjected** [comment]
@erik-rt do you mind submitting a PR for this so we can see the reason why the tests fail and help debug?

**Comment by erik-rt** [comment]
Hey Dan, the PR can be found at #4010

**Comment by Rjected** [comment]
Completed in #4010
