### ISSUE TITLE
Use named tokio tasks for spawned critical tasks

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3985]
### Describe the feature

tokio supports naming tasks which is currently unstable and requires tokio_unstable feature

ref https://github.com/paradigmxyz/reth/blob/b05b84823a9d0f8f3348da346bd95f5456ac6fc3/crates/tasks/src/lib.rs#L321-L324

wdyt @onbjerg ?

**Comment by 0xprames** [comment]
opened a PR for this if we decide to move forward with the unstable tokio api dep

imho named tasks at the tokio layer would be useful if/when #3984 is implemented

**Comment by mattsse** [comment]
not viable because tokio-console buggy
