### ISSUE TITLE
Missing Makefile Dependency: cargo-nextest

### ISSUE THREAD

**Issue by refcell** [paradigmxyz/reth#4008]
### Describe the bug

The `Makefile` `test-unit` target uses [cargo-nextest](https://nexte.st/index.html) to execute tests. This binary may not be installed and hurts devx when onboarding to reth.

This issue is to add a graceful install of `cargo-nextest` to the `Makefile`.

### Steps to reproduce

On a machine with `cargo-nextest` not installed, just execute `make test-unit` for an error.

### Platform(s)

Mac (Apple Silicon)

### If you've built Reth from source, provide the full command you used

make test-unit

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
closed via #4009
