### ISSUE TITLE
Poor performance for trace calls

### ISSUE THREAD

**Issue by 0x366** [paradigmxyz/reth#4028]
### Describe the feature

Im using debug_traceCall through IPC very extensively (executing a lot of simulations in parallel with arbitrary bytecode). I think it's around 100-1000 sims per block and up to 20-60 simultaneous requests. Previously I was running this same code on geth IPC and was getting decent times - like 200-400ms for 80 requests (it's 4 times * 20 simultaneous requests). 

With reth my average time for these same requests are 400-800ms. Sometimes it becomes 2s+, while in geth I was getting everything under 1 second. I'm using `--rpc-max-tracing-requests 1000`.

Is there anything I can tweak?

**Comment by mattsse** [comment]
what kind of tracing requests?
