### ISSUE TITLE
Disable console color coding

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#4030]
### Describe the feature

Add cli flag that is going to disable the colour coding of console output, it is particularly annoying with docker logs that would contain ansci encoding.

**Comment by rakita** [comment]
There is an option to disable it with RUST_LOG but cli flag should give better visibility to that feature:
https://github.com/paradigmxyz/reth/blob/b46101afb5e549d40b7b2537fff9b67e05ad4448/crates/tracing/src/lib.rs#L44-L52

**Comment by alessandromazza98** [comment]
I can take this one
