### ISSUE TITLE
debug.hook-transaction is not working

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#4042]
### Describe the bug

This option is not working as we removed expensive transaction hash calculation from `Providers` `block_with_senders` that is used to fetch blocks for execution.

Maybe we can add block number, transaction index that info is easy to find from etherscan and it does not require us to calculate hash

### Steps to reproduce

run with `--debug.hook-transaction` option.

**Comment by mattsse** [comment]
this has been removed
