### ISSUE TITLE
Feed new pending transactions into the BestTransactions iterator

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4045]
### Describe the feature

the Bestransactions impl is a snapshot of the pending subpool

https://github.com/paradigmxyz/reth/blob/ce6e24770e7f3ce6d3fa8356f95d5a4a6cb9a5b0/crates/transaction-pool/src/pool/best.rs#L53-L53

however since block production can take a bit, it would be beneficial to also receive new transactions from the pending pool

this would break the Iterator guarantees that it only ever yields the next best transaction, but the upside of having potentially overall better transactions in the iterator is greater.

This could be achieved by adding a broadcast channel (or a list of subscriptions) into the pending subpool.

The Bestransactions requires a sync channel API (try_recv)

**Comment by supernovahs** [comment]
Can I take this on?

**Comment by mattsse** [comment]
sure! ty

lmk when something's unclear/need directions by opening a draft pr

**Comment by 0xprames** [comment]
i opened a draft for this mainly for my own understanding (this seemed like an interesting issue - but i saw it almost a day late 😢 )

Please feel free to close my draft pr out in favor of @supernovahs' - im mainly looking for feedback to see if I understood this issue/this part of the codebase correctly or not
