### ISSUE TITLE
Move status update from `HeadersClient`

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#407]
The headers client contains the `update_status` function used to push the new status to the node (used during handshakes). This function has to be moved out of the client (prob to `NetworkHandle`)

**Comment by jonasbostoen** [comment]
I can work on this. Q: It is also used in the headers stage: `HeaderStage` contains a `HeadersClient` and calls `update_status` when updating the head. How should this be handled?

**Comment by jonasbostoen** [comment]
Another option: It looks like the calling context has access to a `NetworkHandle`, and since `NetworkHandle` can update the status, we could include it in the `HeaderStage`.

**Comment by mattsse** [comment]
this has been completed in #436
