### ISSUE TITLE
multiple vmtrace compatibility issues

### ISSUE THREAD

**Issue by banteg** [paradigmxyz/reth#4071]
### Describe the bug

these are findings from a brief comparison with erigon. note that erigon's tracing routines are [not free from bugs either](https://github.com/ledgerwatch/erigon/pull/7970).

- [x] `op` is missing
- [x] `idx` is missing
- [ ] `mem` values are missing
- [x] `used` should track the remaining gas, currently it's equal to `cost` in reth
- [x] `push` on stack currently uses full words, while in other clients you'd see `0xc0ffeebabe` rather than `0x000000000000000000000000000000000000000000000000000000c0ffeebabe`
- [x] `code` has an extra zero word at the end for some reason

### Steps to reproduce

`trace_replayTransaction` with reth and erigon and diff the output

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.1.0-alpha.4

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
there are like 0 docs for all these things so not surprising that things are missing.

The missing fields weren't part of the original OE impl.

what does `idx` represent here? `"idx": "168-2"` the last value appears to be the instruction idx, not sure what the leading value is

**Comment by onbjerg** [comment]
@mattsse Is this resolved via the linked PRs? Going through it seems like it?

**Comment by mattsse** [comment]
closing this, if there are still issues we track them separately once they get reported
