### ISSUE TITLE
feat(eip4844): include `TxEip4844` in the primitive `Transaction` enum

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#4073]
### Describe the feature

`TxEip4844` has to be included in the primitive `Transaction` enum.

https://github.com/paradigmxyz/reth/blob/544c51cc9ff15d0626cdb63666ad3d195c806be0/crates/primitives/src/transaction/mod.rs#L40-L68

**Comment by Rjected** [comment]
Fixed with #4074
