### ISSUE TITLE
Logic bug in Tracer (finalized mainnet tx fails to trace with "insufficient funds" err)

### ISSUE THREAD

**Issue by datskos** [paradigmxyz/reth#4083]
### Describe the bug

Tracing a historical transaction `0x146f113538965f67e40d70efe3eca6e24725f521862db1ec89c7f68ba8b4569c` in block `11117104` fails with an erroneous `insufficient funds` error.

Root cause is ~possibly balance from the previous transaction not being refunded while tracing~ state bug after selfdestruct

TxIdx=161 Sender=0x9a..e74 reverts
TxIdx=162 Sender=0x9a..e74 should succeed but tracer sees sender balance as `2.5534` instead of `7.199`

#### Reproduction Method 1 (trace in reth)

```
cast rpc trace_transaction 0x146f113538965f67e40d70efe3eca6e24725f521862db1ec89c7f68ba8b4569c
```

Fails with:
```(code: -32003, message: insufficient funds for gas * price + value, data: None)```

#### Reproduction Method 2 (trace in foundry; use upstream reth state)

```
cast run 0x146f113538965f67e40d70efe3eca6e24725f521862db1ec89c7f68ba8b4569c
```

Foundry also fails to trace so ~presumably the same logic error exists in both foundry & reth tracing routines~  bad historical states

```
Error:
Failed to execute transaction: 0x146f113538965f67e40d70efe3eca6e24725f521862db1ec89c7f68ba8b4569c

Context:
- backend: failed while inspecting: Transaction(LackOfFundForGasLimit { gas_limit: 0x0000000000000000000000000000000000000000000000005d327df6b79dc160_U256, balance: 0x000000000000000000000000000000000000000000000000236f832a74bb46d6_U256 })```

```
### What version/commit are you on?

v0.1.0-alpha.4

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this looks like a changeset bug after selfdestruct 

replaying this tx via cast run succeeds with reth https://etherscan.io/tx/0xec60c94efd17f14a6923c0106b4ffba201a26e9f7d209fa7edddee1d966839f4

when it shouldn't 

this mev bot contract has incorrect historical storage https://etherscan.io/address/0x0000000000007f150bd6f54c40a34d7c3d5e9f56#code

`cast rpc eth_getStorageAt 0x0000000000007f150bd6f54c40a34d7c3d5e9f56 0x7ca5987043ac53676c6e30f77ff1a34e98a5fae86b27e5d0cf74ac1711b8a8db 0xA9A22F`

which returns 0x0000000000000000000000000000000000000000000000000000000000000000 (matches latest) but should be 0x00000000000000000000000060d826838d7acb5d922947b2c2c25e34514004b8 at state of the transaction

**Comment by onbjerg** [comment]
@mattsse i think you did some work on selfdestruct recently, is this fixed?

**Comment by mattsse** [comment]
this was due to changesets, which has been fixed, right @rkrasiuk ?

**Comment by datskos** [comment]
Now that #3512 has been merged, this issue can be closed
