### ISSUE TITLE
Idle thread leak in session manager

### ISSUE THREAD

**Issue by bemevolent** [paradigmxyz/reth#4089]
### Describe the bug

I wanted to try out `tokio-console` from the existing PR. After having that running for a bit, I noticed idle threads continuously growing which might be related to other RPC timeouts others have been running into.

After adding some logging, it looks like in session manager in `start_pending_outbound_session` every once in a while the the future never returns and a thread is left idle.

https://github.com/paradigmxyz/reth/blob/aaf2d2cf194cc5b2c6e8ec106001ee44db9512c9/crates/net/network/src/session/mod.rs#L797-L810

### Steps to reproduce

- Add naming to all task spawning
- Run `tokio-console` and watch idle threads grow

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

5885ba6a55c42491475ee583cccff0f136c12841

### What database version are you on?

1

### If you've built Reth from source, provide the full command you used

RUSTFLAGS="--cfg tokio_unstable" cargo install --locked --path bin/reth --bin reth --features tokio-console

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> related to other RPC timeouts others have been running into.

related how?

**Comment by bemevolent** [comment]
Lots of idle threads could lead to thread starvation / context switching issues since `jsonrpsee` also spawns threads outside of the Task Executor. I could be way off here though, still getting familiar with tokio and the task management system being used.

**Comment by mattsse** [comment]
> This task has lost its waker, and will never be woken again.

interesting, need to investigate where this can happen

**Comment by mattsse** [comment]
this appears to be a bug in tokio-console with nested spawns (which is the case here)

https://github.com/ZcashFoundation/zebra/issues/4581

https://github.com/tokio-rs/console/issues/345

the list of idle tasks is definitely reported wrong, because we restrict how many outbound connections can be active at once, 

I wonder if we should wrap this in a timeout task

**Comment by bemevolent** [comment]
Ah thanks, I'll close this. Since we were already discussing in this thread I wanted to check my understanding - for the rpc servers they are using their own threads with `jsonrpsee_server::ServerBuilder` and normal `tokio::spawns`. Is that expected or should they be using the main tokio multi_thread runtime and a task executor? @mattsse
