### ISSUE TITLE
Persist and rotate logs by default

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#4095]
### Describe the feature

We don't persist any logs by default, but rather have a flag which users need to specify manually: https://github.com/paradigmxyz/reth/blob/aaf2d2cf194cc5b2c6e8ec106001ee44db9512c9/bin/reth/src/cli/mod.rs#L140-L143

The problem is that most of the time users don't specify any flags besides ones required for the normal operation, so when something bad happens (as we still in alpha) we may not have enough logs to debug the problem.

Lighthouse has pretty decent log persisting and rotating settings by default: https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/lighthouse/src/main.rs#L132-L153. Keeping last 5 files each max 200MB sounds pretty reasonable for me.

**Comment by bemevolent** [comment]
This would be very helpful. Although probably a good idea to clean up log levels across the board first. Ex: a `DEBUG` log level can fill 200MB in under a minute with useless dns queries and `try_insert_validated_block` nibbles that should be a trace, if logged at all

**Comment by v4lproik** [comment]
Can I try to give this one a go?
