### ISSUE TITLE
Make TransactionPool trait object safe

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4097]
### Describe the feature

some trait functions make use of trait arguments:

https://github.com/paradigmxyz/reth/blob/269b878f5cdfd8e6444675fd1b25a8ceae02ecbb/crates/transaction-pool/src/traits.rs#L252-L255

which makes the trait not object safe

## TODO
* convert arguments into Vec (these are called with most of the time anyways, if not perf impact is negligible)
* ensure trait can be boxed `pool: Box<dyn TransactionPool>`

**Comment by PatStiles** [comment]
This sounds wicked, may I humbly requests being assigned this?

**Comment by mattsse** [comment]
assigned
