### ISSUE TITLE
Ask for confirmation during `reth db drop`

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#4117]
### Describe the feature

It's a shame when a fully synced mainnet database is accidentally deleted.

Let's ask for the interactive confirmation by default and add a `-f` / `--force` flag to explicitly bypass this confirmation.

**Comment by mattsse** [comment]
makes sense, let's also add a --force to bypass user input in case this is run in ci or similar

**Comment by alessandromazza98** [comment]
I can take this
