### ISSUE TITLE
Is it meaningful to add a global LRUCache to the execution stage?

### ISSUE THREAD

**Issue by anonymousGiga** [paradigmxyz/reth#4125]
### Describe the feature

Based on the information available in the PR #2487, it seems that the addition of the LRUCache [did not show any performance improvement](https://github.com/paradigmxyz/reth/pull/2487#pullrequestreview-1415550441). This is likely because the CacheDB is also used for caching within the executor, and the LRUCache was not effective in optimizing performance while the execute_inner function was executing until synchronization ends.

However, when there is a commit_threshold, the execute_inner function may be executed multiple times during synchronization. In such cases, adding the LRUCache can potentially provide performance improvements.

Is my understanding correct? If correct, can we consider adding LRUCache to the current code.

**Comment by onbjerg** [comment]
No, there was no performance gain on syncing at all with the LRU being re-used across multiple calls to `execute_inner`. The test was not using an LRU for a single execute_inner call, it was re-using an LRU across multiple calls (as you suggest).
