### ISSUE TITLE
failed to sync after upgrade to 0.1.0-alpha.5

### ISSUE THREAD

**Issue by 0xSt1ng3R** [paradigmxyz/reth#4128]
### Describe the bug

1. Yesterday our reth node got stuck on 17867059, the same issue as in #4107.
2. Today, we upgraded to 0.1.0-alpha.5 with the #4108 fix.
3. The reth node failed to sync fully.
4. Tried to unwind a couple of blocks (reth stage unwind to-block 17860000) - but failed like in #4114.
5. Logs attached - they are after the unwind.

### Steps to reproduce

```text
reth node --authrpc.jwtsecret /root/jwt.hex --authrpc.addr 127.0.0.1 --authrpc.port 8551 --http --http.addr 127.0.0.1 --http.port 8545 --http.api all --ws --ws.addr 127.0.0.1 --ws.port 8546 --ws.api all --ipcpath /tmp/reth.ipc --rpc-max-connections 1024 --rpc-max-subscriptions-per-connection 1024 --rpc-max-tracing-requests 1024 --log.persistent --log.filter info -vvv

lighthouse --network mainnet beacon --execution-endpoint http://localhost:8551 --execution-jwt /root/jwt.hex --http --logfile /tmp/lighthouse.log
```

### Node logs

[reth logs](https://gist.github.com/0xSt1ng3R/7245dcb0950fe2743277d0f09c9e01f6), [lighthouse logs](https://gist.github.com/0xSt1ng3R/23f761c2cd76d4dda12c7a40e1c84ea4)

### Platform(s)

Linux (x86)

### What version/commit are you on?

```text
reth Version: 0.1.0-alpha.5
Commit SHA: b823cc01
Build Timestamp: 2023-08-09T07:52:03.903854775Z
Build Features: default,jemalloc
Build Profile: maxperf
```

### What database version are you on?

Current database version: 1
Local database version: 1

### If you've built Reth from source, provide the full command you used

```text
LD_PRELOAD=/usr/local/lib/libjemalloc.so RUSTFLAGS="-C target-cpu=native" cargo build --profile maxperf --features jemalloc
```

### Code of Conduct

- [x] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
we still had a bug in this commit,

the fix was added https://github.com/paradigmxyz/reth/pull/4126

**Comment by 0xSt1ng3R** [comment]
upgraded to #4116, but still have the same problem.
[reth logs](https://gist.github.com/0xSt1ng3R/c05daf164aa281891f47f43ec110445d), [lighthouse logs](https://gist.github.com/0xSt1ng3R/ba5aec5bda080d074dd7aa241891d6c0).

**Comment by 0xSt1ng3R** [comment]
looks like 6622f53 solved it!
