### ISSUE TITLE
Installation from AUR fails

### ISSUE THREAD

**Issue by danielrachi** [paradigmxyz/reth#4131]
### Describe the bug

When installing reth from the AUR, as described in [the book](https://paradigmxyz.github.io/reth/installation/binaries.html), the installation fails with the following error message:

```bash
$ yay -S reth
...
error: failed to load source for dependency `ruint`

Caused by:
  Unable to update https://github.com/paradigmxyz/uint#38f565ff

Caused by:
  failed to fetch into: /home/daniel/.cargo/git/db/uint-10eb28276571b47e

Caused by:
  failed to authenticate when downloading repository

  * attempted to find username/password via git's `credential.helper` support, but failed

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to acquire username/password from local configuration
==> ERROR: A failure occurred in prepare().
```

### Steps to reproduce

1. run `$ sudo pacman -Syu` and `$ yay -Syu`, just in case.
2. run `$ yay -S reth`

### Platform(s)

Linux (x86)

### What version/commit are you on?

yay tries to install `AUR Explicit (1): reth-v0.1.0_alpha.4-1`

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
@onbjerg I think these packages are a bit outdated now

**Comment by onbjerg** [comment]
This should be reported in my repository, the AUR package is not officially maintained. Will update the package though
