### ISSUE TITLE
Split RethNodeCommandExt into two traits

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4142]
### Describe the feature

split RethNodeCommandExt
https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/cli/ext.rs#L35

into two:

`RethNodeCommandConfig` with the existing functions
and `RethNodeCommandExt: RethNodeCommandConfig +  clap::Args` so it can be plugged into cli

this gives us more flexibility when integrating custom config

**Comment by i-m-aditya** [comment]
I will fix this.
