### ISSUE TITLE
Make the actual payload build function generic

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4145]
### Describe the feature

the BasicPayloadBuilder uses a fixed impl: 

https://github.com/paradigmxyz/reth/blob/9817a9e72420f0e7119e3a972fb2ee52da8baf3c/crates/payload/basic/src/lib.rs#L538-L550

it would be useful to make this function configurable

## TODO

* add trait for this function, default impl for `Fn(Args)`
* simplify args in a helper type

**Comment by i-m-aditya** [comment]
I will fix this

**Comment by leontiadZen** [comment]
that seems a nice good first issue for me! I may need some guidance once i get more familiar. The trait will default implement that function?

**Comment by tcoratger** [comment]
I think this can be closed with https://github.com/paradigmxyz/reth/pull/4153 no?
