### ISSUE TITLE
DNS Request Spamming

### ISSUE THREAD

**Issue by bemevolent** [paradigmxyz/reth#4155]
### Describe the bug

I run reth on a home network and for the past couple days was having all sorts of internet issues and slowness with DNS. Finally put two and two together and ran with `--disable-dns-discovery` and everything went back to normal.

Both Google and Cloudflare DNS started rate limiting and dropping packets from my IP. I'm not familiar with the node discovery protocol but it seems like it's resolving more requests than it should ever need to for 100 peers. If that's not the case and it's working as intended, I'd suggest updating the `max_requests_per_sec` and `recheck_interval` values to more reasonable defaults

### Steps to reproduce

Run with trust_dns_proto debug logs to see the number of DNS requests

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

b8b7ad60ada5e808c11beba2810c108d46d849bb

### What database version are you on?

1

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
nice find

looking at this again

https://github.com/paradigmxyz/reth/blob/e43187bf7ffdb669c45ff8383fa156e44b070eb2/crates/net/dns/src/query.rs#L81-L102

we should probably ensure that we don't have too many active requests at a time

and increase the ratelimit 

https://github.com/paradigmxyz/reth/blob/e43187bf7ffdb669c45ff8383fa156e44b070eb2/crates/net/dns/src/query.rs#L50-L53

**Comment by bemevolent** [comment]
Closing this as #4178 should solve - I think my node was able to get into a state where it was trying dozens of requests at once maybe due to some failing.

One other diff I noticed between the general dns discovery between reth and erigon is erigon includes cache hits as part of the rate limit to prevent constant cycling. If further issues pop up outside of this, that could probably be considered to limit
