### ISSUE TITLE
handle Lagged error variant in pool update channel

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4159]
### Describe the feature

this can be a Lagged error:

https://github.com/paradigmxyz/reth/blob/500b0fac135fe07635d871d64467326599e2b27e/crates/transaction-pool/src/pool/best.rs#L99-L99

which can be continued

todo

convert this function into a loop that continues on Lagged error, otherwise returns

**Comment by mr-abims** [comment]
I would love to work on this ser, I'm an EPF participant and i want to contribute to reth.
Please what pointers should i look out for...

**Comment by mattsse** [comment]
cool, ptal at the error type of the referenced line

the `Lagged` is just an indicator that the stream was lagging and we can simply try again

**Comment by mr-abims** [comment]
Alright, got it

**Comment by protocolwhisper** [comment]
Hi. @mattsse Do you mean to use something like `TryRecvError::Lagged` ?? I would love to work on this :)
