### ISSUE TITLE
map BlockIndicesNotfound error to an option

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4166]
### Describe the bug

https://github.com/paradigmxyz/reth/blob/main/crates/interfaces/src/provider.rs#L14-L14

https://github.com/paradigmxyz/reth/blob/1c23075edbdb2d49b3759935aa7bece792c2e3e4/crates/rpc/rpc-engine-api/src/engine_api.rs#L226-L233

this can happen if we have the header but not the body so during bodies stage reth responds with errors and not null values

### Steps to reproduce

-

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Va-a-real-noob-coder** [comment]
> ### Describe the bug
> https://github.com/paradigmxyz/reth/blob/main/crates/interfaces/src/provider.rs#L14-L14
> 
> https://github.com/paradigmxyz/reth/blob/1c23075edbdb2d49b3759935aa7bece792c2e3e4/crates/rpc/rpc-engine-api/src/engine_api.rs#L226-L233
> 
> this can happen if we have the header but not the body so during bodies stage reth responds with errors and not null values
> 
> ### Steps to reproduce
> 
> ### Node logs
> _No response_
> 
> ### Platform(s)
> _No response_
> 
> ### What version/commit are you on?
> _No response_
> 
> ### What database version are you on?
> _No response_
> 
> ### If you've built Reth from source, provide the full command you used
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow the Code of Conduct

i don't have a node to test but i made this 


`use crate::provider::ProviderError; // Make sure to import the ProviderError enum

pub async fn get_payload_bodies_by_range(
    &self,
    start: BlockNumber,
    count: u64,
) -> EngineApiResult<ExecutionPayloadBodiesV1> {
    let (tx, rx) = oneshot::channel();
    let inner = self.inner.clone();

    self.inner.task_spawner.spawn_blocking(Box::pin(async move {
        if count > MAX_PAYLOAD_BODIES_LIMIT {
            tx.send(Err(EngineApiError::PayloadRequestTooLarge { len: count })).ok();
            return;
        }

        if start == 0 || count == 0 {
            tx.send(Err(EngineApiError::InvalidBodiesRange { start, count })).ok();
            return;
        }

        let mut result = Vec::with_capacity(count as usize);

        let end = start.saturating_add(count);
        for num in start..end {
            let block_result = inner.provider.block(BlockHashOrNumber::Number(num));
            match block_result {
                Ok(block) => {
                    result.push(block.map(Into::into));
                }
                Err(ProviderError::BlockBodyIndicesNotFound(_)) => {
                    // Map the error to None
                    result.push(None);
                }
                Err(err) => {
                    tx.send(Err(EngineApiError::Internal(Box::new(err)))).ok();
                    return;
                }
            };
        }
        tx.send(Ok(result)).ok();
    }));

    rx.await.map_err(|err| EngineApiError::Internal(Box::new(err)))?
}
`
