### ISSUE TITLE
Complete vmTrace memory delta recording

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4168]
### Describe the feature

ref #4071

the vmtrace implementation still lacks proper memory delta calculation:

https://github.com/paradigmxyz/reth/blob/1c23075edbdb2d49b3759935aa7bece792c2e3e4/crates/revm/revm-inspectors/src/tracing/builder/parity.rs#L357-L363

this requires comparing recorded memory and delta based on opcodes
go reference impl:

https://github.com/ledgerwatch/erigon/blob/60a200fd46dcb0fa246bd4e0971690cfa111b129/turbo/jsonrpc/trace_adhoc.go#L445-L475

**Comment by alessandromazza98** [comment]
I could try this one

**Comment by mattsse** [comment]
cool, 
if you need access to a reth node to compare outputs, please dm on tg @mattsse
