### ISSUE TITLE
Add test that ensures the committing happens correctly inside Headers Stage

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#418]
We should have a test that blocks the stream per-batch, letting us check that the commit actually happened while the stage is running. Currently we're only testing that the entire stream has been committed.

_Originally posted by @gakonst in https://github.com/paradigmxyz/reth/pull/406#discussion_r1047456123_

**Comment by MegaRedHand** [comment]
I think this issue can be closed. After https://github.com/paradigmxyz/reth/pull/609, the headers stage doesn't commit directly, and returns control to the pipeline after a number of headers. Although we are missing some test that tries to execute the stage in multiple steps ([see `BodyStage`'s `sync_from_previous_progress`](https://github.com/paradigmxyz/reth/blob/db24d3ae9ec5983ad009afaabc7d4159c52a09bf/crates/stages/src/stages/bodies.rs#L341)).
