### ISSUE TITLE
Allow configuring the trusted setup file by command line flag

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#4200]
### Describe the feature

Currently we load the KZG trusted setup from a file:
https://github.com/paradigmxyz/reth/blob/0f600d39f624df27ad2f8ad0b9208a5aa869afb0/crates/primitives/src/constants/eip4844.rs#L31-L39

We should introduce a flag `--trusted-setup-file` which loads and overrides the trusted setup file if specified.

### Additional context

This is a requirement for devnets, from [dencun-devnet-8](https://notes.ethereum.org/@ethpandaops/dencun-devnet-8):
> 4844 requires a trusted setup file, Please ensure that there is a way for us to specify the file through a runtime flag such as --trusted-setup-file (or similar). If the file is baked in during compile, please ensure that the flag would indeed override the file. This is a MUST requirement for devnet 6. If your client does not support the override, we can’t include it in the devnet.

**Comment by BrazilRaw** [comment]
so if i understand it should have a command line to configure th path for --trusted-setup-fil right ? 

can you tell me how it should run ? cargo run --trusted-setup-fil=text.txt ? right ?

**Comment by mteam88** [comment]
Would be happy to take this!
