### ISSUE TITLE
Extend ExecutionPayload type with cancun fields

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4206]
### Describe the feature

ref 
https://github.com/ethereum/execution-apis/blob/main/src/engine/cancun.md#executionpayloadv3

two additional fields:

> dataGasUsed: QUANTITY, 64 Bits
> excessDataGas: QUANTITY, 64 Bits

ensure fields are present/missing for v1,v2,v3

ref #2894

blocked by #4186

**Comment by Rjected** [comment]
Fixed by #4010
