### ISSUE TITLE
Add rlp_size hint to PooledTransaction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4212]
### Describe the feature

ref #4172

add a rlp_size_hint function to pooledtransaction that returns the expected number of bytes the transaction will take up in rlp format

this will be used to enforce the soft response limit in the transaction manager.

the softresponselimit is an arbitrary limit which we can enforce at will, we don't need the exact value because encoding should happen on the peer task, instead we can assume how much it will take up and use that to limit how many txs we will include in the response

https://github.com/ethereum/devp2p/blob/master/caps/eth.md#newpooledtransactionhashes-0x08

**Comment by Rjected** [comment]
I think we can now use the `Encodable::length` for this from `PooledTransaction`:
https://github.com/paradigmxyz/reth/blob/60ad6b2f5413ff000bd43b3dad3839164decad89/crates/primitives/src/transaction/pooled.rs#L165-L184

@mattsse WDYT

**Comment by mattsse** [comment]
I think that's reasonable

**Comment by Rjected** [comment]
alright, closing this then

**Comment by mattsse** [comment]
oh, but this still encodes, right?

**Comment by Rjected** [comment]
> oh, but this still encodes, right?

It shouldn't, since we manually define the `length` method, which calculates individual field length and uses `length_of_length` to determine intermediate header length

**Comment by mattsse** [comment]
gotcha
