### ISSUE TITLE
feat(op-reth): Add Cancun Hardfork to the Optimism Chainspec [PLANNED]

### ISSUE THREAD

**Issue by refcell** [paradigmxyz/reth#4213]
### Describe the feature

This is a _planned_ change to track addition of the cancun hardfork to `optimism` feature flag chain specs.

### Overview

Cancun Hardfork will need to be added to the Optimism Chainspec.

### Where should this feature live?

In the `OP_GOERLI` and `BASE_GOERLI` ChainSpecs inside the primitives crate. See the [op-reth](https://github.com/anton-rs/op-reth/blob/clabby/op-reth/crates/primitives/src/chain/spec.rs#L237-L302) repository for reference.

### Completion Criteria

- [ ] Cancun Hardfork is added to all `ChainSpec` objects behind the `optimism` feature flag.

### Resources

- [op-geth diff](https://op-geth.optimism.io/)
- [op-erigon diff](https://op-erigon.testinprod.io/)
- [Optimism Specs](https://github.com/ethereum-optimism/optimism/tree/develop/specs)

**Comment by refcell** [comment]
@gakonst Request to add `A-op-reth` label 🙏

**Comment by clabby** [comment]
Closing, added in Ecotone.
