### ISSUE TITLE
feat(op-reth): Match the RPC changes in the LES RPC

### ISSUE THREAD

**Issue by refcell** [paradigmxyz/reth#4218]
### Describe the feature

**Diff Category**: `User API Enhancements` > `Light Ethereum Subprotocol (LES) RPC`
**`op-geth` sources**
- [les/state_accessor.go](https://op-geth.optimism.io/#id-1e7fd91b98e3d3a4b068f6cf)
- [les/api_backend.go](https://op-geth.optimism.io/#id-60bf40a23c26c1d73d3bf2a6)
- [les/odr_test.go](https://op-geth.optimism.io/#id-7d5d7e8b2f7f35cf9be90199)
- [les/client.go](https://op-geth.optimism.io/#id-520194d166f4662f8816f134)

### Additional context

This ticket is to modify the support the rpc changes in the LES rpc.

All code added in work related to this ticket should live underneath the `optimism` feature flag.

Diff sources can be seen in the snippets below.
- [les/state_accessor.go](https://op-geth.optimism.io/#id-1e7fd91b98e3d3a4b068f6cf)
- [les/api_backend.go](https://op-geth.optimism.io/#id-60bf40a23c26c1d73d3bf2a6)
- [les/odr_test.go](https://op-geth.optimism.io/#id-7d5d7e8b2f7f35cf9be90199)
- [les/client.go](https://op-geth.optimism.io/#id-520194d166f4662f8816f134)

### Where should this feature live?

Likely within the [rpc crate](https://github.com/paradigmxyz/reth/blob/main/crates/rpc/).

### Completion Criteria

- [ ] `func (b *LesApiBackend) HistoricalRPCService() *rpc.Client` is implemented
- [ ] `func (b *LesApiBackend) Genesis() *types.Block` is implemented

### Resources

- [op-geth diff](https://op-geth.optimism.io/)
- [op-erigon diff](https://op-erigon.testinprod.io/)
- [Optimism Specs](https://github.com/ethereum-optimism/optimism/tree/develop/specs)

**Comment by refcell** [comment]
Request for @gakonst to add the `A-op-reth` label.

**Comment by gakonst** [comment]
We don't have Les, so you can probably skip this?

**Comment by gakonst** [comment]
@clabby @refcell should this be closed?

**Comment by clabby** [comment]
> @clabby @refcell should this be closed?

Yep, thanks!
