### ISSUE TITLE
Database Read Error During Sync

### ISSUE THREAD

**Issue by boyle-michael** [paradigmxyz/reth#4240]
### Describe the bug

During the IndexAccountHistory stage around checkpoint 10500000, I ran into a database read error. This error stopped the syncing process and killed reth.

I was using the prebuilt binary for alpha 6 on a Linux machine. I am using LVM to combine a 1TB SSD and 2TB SSD to store the database. Restarting the node and restarting the sync did not work. Upgrading from alpha 4 to alpha 6 did not work. 

### Steps to reproduce

I ran reth with the following config: 

`RUST_LOG=info Downloads/reth node --authrpc.jwtsecret /secrets/jwt.hex --authrpc.addr 127.0.0.1 --authrpc.port 8551 --metrics 127.0.0.1:9001 --http.api all --datadir /media/michael/03d1cfa8-c0f3-49a9-91e1-ceae2ebd1540/mainnet/

### Node logs

```text
2023-08-16T14:37:57.671144Z  INFO reth::node::events: Forkchoice updated head_block_hash=0x40255b4732d2c3c7a84a83d2668edd785bf4a466a063c3650443597f5a86e0c2 safe_block_hash=0x1ee4e521c81481cc0ce2ea72d818525c0bb73ac8bd3771c31a656dab7637fa52 finalized_block_hash=0x39a9a4a83d012e8ec0599138b419996e6c7f277db3b2f3789401dc207e740f02 status=Syncing
2023-08-16T14:38:02.611929Z  WARN execute{stage=IndexAccountHistory}: sync::pipeline: Stage encountered a non-fatal error: Database write error code: 27. Retrying... stage=IndexAccountHistory
Error: An interface error occurred.

Caused by:
    Database read error code: -30782

Location:
    /project/bin/reth/src/node/mod.rs:502:9
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

88aea63

### What database version are you on?

Current database version: 1
Local database is uninitialized

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by bemevolent** [comment]
Check #3974 for a similar issue and if that doesn't resolve share some of the requested `mdbx_chk`, `vgs`, etc outputs from that thread

**Comment by boyle-michael** [comment]
I changed the file system type to Ext4 and it still did not work. 

System:
-  Operating System: Linux Mint 21.1 Cinnamon
- Cinnamon Version: 5.6.8
- Linux Kernel: 5.15.0-60-generic
- Processor: AMD Ryzen 9 3900X 12-Core Processor × 12
- Memory: 15.5 GiB
- Hard Drives: 4000.8 GB


```
$ getconf PAGESIZE
4096

$ sudo vgs
  VG #PV #LV #SN Attr   VSize  VFree
  vg   2   1   0 wz--n- <2.73t    0 

$ sudo pvs
  PV             VG Fmt  Attr PSize    PFree
  /dev/nvme1n1p1 vg lvm2 a--    <1.82t    0 
  /dev/nvme2n1p1 vg lvm2 a--  <931.51g    0 

$ sudo lvs
  LV    VG Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lvol0 vg -wi-ao---- <2.73t         
                                           
$ df -h .
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg-lvol0  2.7T  2.2T  398G  85% /media/michael/03d1cfa8-c0f3-49a9-91e1-ceae2ebd1540
```

**Comment by bemevolent** [comment]
What fs were you using before ext4? If it was ext3 then your best bet may be to resync. Even after converting the filesystem, there are some nuances around existing files still being ext3-like without recopying.

If that's not the case, other things to check include db:
```
make db-tools
db-tools/mdbx_chk $(reth db path)/mdbx.dat
```

and ram using something like `memtester`

**Comment by boyle-michael** [comment]
Thank you! Using `chattr +e mdbx.dat` seems to have worked. It has not crashed yet and has reached a new highest checkpoint.

I will close this issue as it is not an issue with reth.

**Comment by boyle-michael** [comment]
Update: it got further than last time but crashed with the same error. I will try some of the other things. 
What directory do I need to be in to run `make db-tools` or how do I install this?

`memtest` ran with no errors.

**Comment by bemevolent** [comment]
It's related to the filesystem issues from earlier to no need to run mdbx checks. Can you check `fstab` and all of original setup to make sure it's being mounted as ext4 after reboots, etc?

If none of that works I think it's still going to be best to resync unfortunately
