### ISSUE TITLE
make EthTransactionValidator generic over Validator instead to allow any validator

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4255]
### Describe the feature

ref https://github.com/paradigmxyz/reth/blob/0bcd388a2058f86ca8f560ce79b3a83ddb84fb68/crates/transaction-pool/src/validate/eth.rs#L21-L25

## TODO

* rename and make generic over V

```rust
#[derive(Debug, Clone)]
pub struct TransactionValidationTaskExecutor<V> {
    /// The validator that will validate transactions on a separate task.
    validator: V,
    /// The sender half to validation tasks that perform the actual validation.
    to_validation_task: Arc<Mutex<ValidationJobSender>>,
}
```

so any validator is supported

* move to task.rs
* update all helpers
* add new `struct EthTransactionValidator {inner: Arc<EthTransactionValidatorInner>}` type

**Comment by BrazilRaw** [comment]
Hey i would like to know if it's possible to fix this issue without having to run a node ? I don't have the specs for it

**Comment by mattsse** [comment]
@BrazilRaw @tcoratger was faster :)

lmk if you want to take on something but none of the open issues is interesting

**Comment by BrazilRaw** [comment]
> lmk

i'm definetly interested yes
