### ISSUE TITLE
Use the `DEFAULT_DISCOVERY_PORT` constant when possible

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#4274]
### Describe the feature

At the moment, in various places of the codebase, `port 30303` is hardcoded:

https://github.com/paradigmxyz/reth/blob/cbf3eb4333120cd48acf4be9533b1fb375daa842/crates/net/eth-wire/src/builder.rs#L103

There is a purpose built constant for that:

https://github.com/paradigmxyz/reth/blob/cbf3eb4333120cd48acf4be9533b1fb375daa842/crates/net/discv4/src/lib.rs#L97

Why not use it instead, except for unit tests where we want to be able to access some handmade harcoded values?

**Comment by KaushikKC** [comment]
Can you assign me to do this ?
Would like to do..
