### ISSUE TITLE
Update Return Type for eth_getFilterLogs function as per standard schema

### ISSUE THREAD

**Issue by aniketpr01** [paradigmxyz/reth#4312]
### Describe the bug

As per the standard schema, the default return value for the eth_getFilterLogs function is enum [FilterResults](https://github.com/ethereum/execution-apis/blob/fe8e13c288c592ec154ce25c534e26cb7ce0530d/src/schemas/filter.yaml#L1)/[FilterChanges](https://github.com/paradigmxyz/reth/blob/b78e10fb2fff898d94484c1e2d1356525efe59ef/crates/rpc/rpc-types/src/eth/filter.rs#L821), but in the current implementation it is array of Log objects - Vec<Log>
https://github.com/ethereum/execution-apis/blob/fe8e13c288c592ec154ce25c534e26cb7ce0530d/src/eth/filter.yaml#L45

Current implementation:
https://github.com/paradigmxyz/reth/blob/b78e10fb2fff898d94484c1e2d1356525efe59ef/crates/rpc/rpc-api/src/eth_filter.rs#L25

### Steps to reproduce

NA

### Code of Conduct

- [X] I agree to follow the Code of Conduct
```[tasklist]
### Tasks
```

**Comment by aniketpr01** [comment]
If accepted, willing to work on it!

**Comment by mattsse** [comment]
interesting, 

assigned, appreciate it.
