### ISSUE TITLE
RPC endpoint `eth_accounts` returns empty array in dev mode

### ISSUE THREAD

**Issue by Vid201** [paradigmxyz/reth#4337]
### Describe the bug

In dev mode, first 20 accounts derived from the standard seed phrase are funded with some ETH.

The endpoint `eth_accounts` should return the array of 20 addresses.

### Steps to reproduce

The signer is default: https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/api/mod.rs#L132C13-L132C20

DevSigner init with empty vector: https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/signer.rs#L47

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Vid201** [comment]
I can take this one.

Would this be a way to go?

```
pub struct EthApi<Provider, Pool, Network, Signer> {
    /// All nested fields bundled together.
    inner: Arc<EthApiInner<Provider, Pool, Network, Signer>>,
}
```

Signers should probably be passed when using `RpcModuleBuilder`.

**Comment by allnil** [comment]
I want to take it
