### ISSUE TITLE
When is the planned support for redb scheduled?

### ISSUE THREAD

**Issue by yingjun-wu** [paradigmxyz/reth#4341]
### Describe the feature

I noticed that reth has plans to support the redb. Could you please provide information on when this implementation is expected to be completed? Thank you!

```[tasklist]
### Tasks
```

**Comment by onbjerg** [comment]
Hi @yingjun-wu, this is currently only in an experimental phase while we explore options, so we won't really know if it will replace our current database or not. We'll give a heads up if it happens since it's a breaking change :)
