### ISSUE TITLE
Remove `History` variant in `StageEnum`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#4364]
### Describe the feature

At the moment, the `History` variant in `StageEnum` enum seems to duplicate other variants like `AccountHistory` or `StorageHistory`. The `History` variant can therefore be dropped in favor of a combination of other variants.

https://github.com/paradigmxyz/reth/blob/d8b1609299a4ada2bf57fd4feb62e7042d0ccbf6/bin/reth/src/args/stage_args.rs#L6-L21

**Comment by PatStiles** [comment]
@tcoratger are you on this?
