### ISSUE TITLE
Extract more functions from `RpcServerArgs` in `RethRpcConfig`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#4367]
### Describe the feature

At the moment, only `is_ipc_enabled` and `eth_config` functions are included in the `RethRpcConfig` traits:

https://github.com/paradigmxyz/reth/blob/d8b1609299a4ada2bf57fd4feb62e7042d0ccbf6/bin/reth/src/cli/config.rs#L12-L20

More functions can be included here from `RpcServerArgs`.

**Comment by alessandromazza98** [comment]
I can take this

**Comment by 1010adigupta** [comment]
I can take this one
