### ISSUE TITLE
Split `test_fee_history` in multiple tests

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#4368]
### Describe the feature

At the moment, `test_fee_history` function is huge with multiple individual tests inside. 

https://github.com/paradigmxyz/reth/blob/d8b1609299a4ada2bf57fd4feb62e7042d0ccbf6/crates/rpc/rpc/src/eth/api/server.rs#L467

For clarity, ease of debugging, and bug isolation, it would be best to split this into multiple separate tests.

**Comment by his-dudenesss** [comment]
can I take this one ?

**Comment by 1010adigupta** [comment]
I also want to take this one

**Comment by hack3r-0m** [comment]
@onbjerg @tcoratger would it be good to move fee history test case into `crates/rpc/rpc/src/eth/api/fees.rs` file along with with splitting?

**Comment by tcoratger** [comment]
@hack3r-0m I don't think so because one of the main objectives of these tests will be to test the `fee_history` function which is precisely implemented in this `server.rs` file, what do you think @onbjerg ?
