### ISSUE TITLE
Remove discarded blob transaction from blobstore

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4392]
### Describe the feature

when we discard eip4844 transactions, we should also remove them from the blobstore

**Comment by chirag-bgh** [comment]
I would take this on!

**Comment by chirag-bgh** [comment]
> cool, lmk when you need pointers by opening a draft.

Yes few pointers would be useful :)

**Comment by mattsse** [comment]
so basically, every time we get a list of discarded txs:

https://github.com/paradigmxyz/reth/blob/82fb0eedb392f6324c316210b524f2bf7fb4c864/crates/transaction-pool/src/pool/mod.rs#L771-L772

and https://github.com/paradigmxyz/reth/blob/82fb0eedb392f6324c316210b524f2bf7fb4c864/crates/transaction-pool/src/pool/mod.rs#L887-L888

we should call:

https://github.com/paradigmxyz/reth/blob/82fb0eedb392f6324c316210b524f2bf7fb4c864/crates/transaction-pool/src/pool/mod.rs#L723-L723

with all eip4844 txs
