### ISSUE TITLE
Add blobstore metrics to dashboard

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4393]
### Describe the feature

new blobstore txpool metrics:

https://github.com/paradigmxyz/reth/blob/2fc574f32999fbfd966ad137c9b3cfc190e48e48/crates/transaction-pool/src/metrics.rs#L42-L53

## TODO 
add to grafana dashboard, see existing txpool graphs:

https://github.com/paradigmxyz/reth/blob/main/etc/grafana/dashboards/overview.json

**Comment by JosepBove** [comment]
I can take this

**Comment by JosepBove** [comment]
Can be closed, feature done and merged
