### ISSUE TITLE
Improve `PayloadBuilderService` polling service

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#4403]
### Describe the feature

At the moment, a `new_job` boolean flag is used and modified inside a while condition that drains all requests:

https://github.com/paradigmxyz/reth/blob/82fb0eedb392f6324c316210b524f2bf7fb4c864/crates/payload/builder/src/service.rs#L232-L274

At the end, if `new_job` is `false`, `Poll::Pending` is returned. We could improve the efficiency here by polling only new jobs.

**Comment by mattsse** [comment]
could be converted to futures unordered probably

**Comment by chirag-bgh** [comment]
I would like to take this.

**Comment by mattsse** [comment]
any update?
should I unassign you?

**Comment by chirag-bgh** [comment]
> any update? should I unassign you?

Hey, yes I still want to work on this.
Just to confirm, we need to convert `payload_jobs` to `FuturesUnordered` right?
