### ISSUE TITLE
Mermaid diagrams are not rendered in `reth` crate docs

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#4430]
### Describe the bug

Rendered:
- https://paradigmxyz.github.io/reth/docs/reth_network/struct.NetworkManager.html
- https://paradigmxyz.github.io/reth/docs/reth_transaction_pool/pool/txpool/struct.TxPool.html

Not rendered:
- https://paradigmxyz.github.io/reth/docs/reth/network/struct.NetworkManager.html
- https://paradigmxyz.github.io/reth/docs/reth/transaction_pool/pool/txpool/struct.TxPool.html

**Comment by mattsse** [comment]
checking

**Comment by mattsse** [comment]
okay, looks like this is an issue with rustdocs of reexports which simply don't include the mermaid stuff for some reason.

we could hide the reexports, but that's probably not what we want

**Comment by vcastellm** [comment]
Hey @mattsse thinking on this, wdyt about removing `include_mmd!` and move the mermaid code to the file?

If that's not an option you like I can try to fix this in aquamarine but prob it'll take longer.

**Comment by mattsse** [comment]
this would require generating the image I think?

mermaid works fine for non-reexports, imo no action item here

**Comment by vcastellm** [comment]
No, I mean, aquamarine have issues with `include_mmd!` in reexports, so I'm proposing to get rid of `include_mmd!` and embedding the mermaid code in the doc, for example, here https://github.com/vcastellm/reth/blob/main/crates/net/network/src/manager.rs#L77 

wdyt?

**Comment by vcastellm** [comment]
Ping @mattsse

**Comment by mattsse** [comment]
I'd be okay with this yes, sg!
