### ISSUE TITLE
Add tokio Semaphore to EthStateCacheService 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4442]
### Describe the feature

there's currently no ratelimiting in place when data is fetched via the EthStateCacheService
which can result in issues under heavy load.

## TODO
integrate a semaphore in the EthStateCacheService which is then used to acquire permits before hitting the database.

**Comment by alessandromazza98** [comment]
Hi @mattsse I could take this one

**Comment by mattsse** [comment]
cool,

todos basically

* add config value for sempaphore, maybe 512 by default
* integrate EthStateCache, await in spawned futures
