### ISSUE TITLE
Consolidate eip4844 pool errors

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4449]
### Describe the feature

Combine all eip4844 errors into one error type

https://github.com/paradigmxyz/reth/blob/2a771386b9bf9a2e8a5e9727488a5eaee53fa178/crates/transaction-pool/src/error.rs#L141-L154

ref https://github.com/paradigmxyz/reth/pull/4447

would also make it easier to handle in rpc error variant

https://github.com/paradigmxyz/reth/blob/2a771386b9bf9a2e8a5e9727488a5eaee53fa178/crates/rpc/rpc/src/eth/error.rs#L475-L480

**Comment by alessandromazza98** [comment]
I could take this
