### ISSUE TITLE
Can't use reth-revm as a dependency

### ISSUE THREAD

**Issue by asdfcrypto** [paradigmxyz/reth#4452]
### Describe the bug

Title. Similar to #3454 but the workaround doesn't work.

### Steps to reproduce

1. Add `reth-revm` to `Cargo.toml`
2. Run `cargo check`

```toml
name = "reth-revm-test"
version = "0.1.0"
edition = "2021"

[dependencies]
reth-revm = { git = "https://github.com/paradigmxyz/reth.git", package = "reth-revm" }
```

### Node logs

```text
Checking reth-db v0.1.0-alpha.8 (https://github.com/paradigmxyz/reth.git#39a6fa1b)
    Checking reth-revm-inspectors v0.1.0-alpha.8 (https://github.com/paradigmxyz/reth.git#39a6fa1b)
error[E0609]: no field `precompiles` on type `&mut EVMData<'_, DB>`
   --> /home/asdf/.cargo/git/checkouts/reth-36d3ea1d1152b20c/39a6fa1/crates/revm/revm-inspectors/src/tracing/js/mod.rs:371:41
    |
371 |         self.register_precompiles(&data.precompiles);
    |                                         ^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `env`, `journaled_state`, `db`, `error`

error[E0609]: no field `precompiles` on type `&mut EVMData<'_, DB>`
   --> /home/asdf/.cargo/git/checkouts/reth-36d3ea1d1152b20c/39a6fa1/crates/revm/revm-inspectors/src/tracing/js/mod.rs:433:41
    |
433 |         self.register_precompiles(&data.precompiles);
    |                                         ^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `env`, `journaled_state`, `db`, `error`

error[E0609]: no field `precompiles` on type `&EVMData<'_, DB>`
   --> /home/asdf/.cargo/git/checkouts/reth-36d3ea1d1152b20c/39a6fa1/crates/revm/revm-inspectors/src/tracing/mod.rs:111:17
    |
111 |         if data.precompiles.contains(to) {
    |                 ^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `env`, `journaled_state`, `db`, `error`

For more information about this error, try `rustc --explain E0609`.
error: could not compile `reth-revm-inspectors` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

39a6fa1b5723466d98de3df66a5eae76e3846a28

### What database version are you on?

N/A

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by dvush** [comment]
I got the same error today and patching revm dependency worked.

`Cargo.toml`
```
[patch.crates-io]
revm = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
revm-primitives = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
```


In `Cargo.lock`
there should be one instance of revm listed and it should look something like this:
```
[[package]]
name = "revm"
version = "3.3.0"
source = "git+https://github.com/bluealloy/revm/?branch=release/v25#6084e0fa2d457931cd8c9d29934bca0812b5b8d6"
dependencies = [
 "auto_impl",
 "revm-interpreter",
 "revm-precompile",
]
```

without patch it fails with the same error mentioned above and in `Cargo.lock` there is
```
[[package]]
name = "revm"
version = "3.3.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "f293f351c4c203d321744e54ed7eed3d2b6eef4c140228910dde3ac9a5ea8031"
dependencies = [
 "auto_impl",
 "revm-interpreter 1.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "revm-precompile 2.0.3 (registry+https://github.com/rust-lang/crates.io-index)",
]

```

**Comment by rakita** [comment]
> I got the same error today and patching revm dependency worked.
> 
> `Cargo.toml`
> ```
> [patch.crates-io]
> revm = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
> revm-primitives = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
> ```
> 
> 
> In `Cargo.lock`
> there should be one instance of revm listed and it should look something like this:
> ```
> [[package]]
> name = "revm"
> version = "3.3.0"
> source = "git+https://github.com/bluealloy/revm/?branch=release/v25#6084e0fa2d457931cd8c9d29934bca0812b5b8d6"
> dependencies = [
>  "auto_impl",
>  "revm-interpreter",
>  "revm-precompile",
> ]
> ```
> 
> without patch it fails with the same error mentioned above and in `Cargo.lock` there is
> ```
> [[package]]
> name = "revm"
> version = "3.3.0"
> source = "registry+https://github.com/rust-lang/crates.io-index"
> checksum = "f293f351c4c203d321744e54ed7eed3d2b6eef4c140228910dde3ac9a5ea8031"
> dependencies = [
>  "auto_impl",
>  "revm-interpreter 1.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
>  "revm-precompile 2.0.3 (registry+https://github.com/rust-lang/crates.io-index)",
> ]
> 
> ```

We are working on updating to newest revm, patch is needed until than.

**Comment by mattsse** [comment]
we're currently using these patches 

https://github.com/paradigmxyz/reth/blob/19e03ee9cdb7c08124734a8cfbe98a32fd38460f/Cargo.toml#L80-L82
