### ISSUE TITLE
`network` crate docs

### ISSUE THREAD

**Issue by akirillo** [paradigmxyz/reth#446]

**Comment by akirillo** [comment]
Working on this in #445

**Comment by akirillo** [comment]
will be brain-dumping my thoughts on how the chapter should be structured in the comments here

**Comment by akirillo** [comment]
My current approach is going to be to walk through the flows of interaction with the crate, going from high -> low levels of abstraction.
So the first flow I'll focus on, is how is this crate used to interact with the network? Beginning from where this is invoked in the pipeline (IIUC the `StateFetcher` struct, but still reading), and walking all the way down the various struct definitions.

Another flow is viewing this from the perspective of a standalone crate, not as a part of a full node - i.e. if one simply wants to connect to the p2p network. Here, I think the entrypoint into the crate is in instantiating a network connection using either `NetworkManager` or `NetworkBuilder`

**Comment by erayack** [comment]
Can you provide more details about the role of the 'StateFetcher' struct in the overall pipeline after reading? @akirillo

> Beginning from where this is invoked in the pipeline (IIUC the `StateFetcher` struct, but still reading), and walking all the way down the various struct definitions.

**Comment by mattsse** [comment]
the mermaid diagrams are currently broken for some reason in the rendered docs.rs, but work in mermaid.live:

https://mermaid.live/edit#pako:eNplUk1PwzAM_SuRT0UqiC3t1FWIAyAEEkgIdmLlEDVmi1iTkqTA2PbfyUc3Nuilsf3e87PlFdSKI5RAyEyzdk4mF5Uk_quVlFhboaRJJpcP5E4YixL1UV-_EqZWH6iX02T3PHrpi69o6_kjvndobHK5ECgtuZUW9Sur0WwlntAYrz9N-tc9k2zmWrwcAibMvE2TB0S9zfwiLLPo-P53mLz2FvoKCcFOeG80cnx8TtZC1qoRcrbeWQq4yO0Rwgofqc7O1H_obgUR3rXcg1tn2ayjTlTsORFlWvYpzXp_zH2Uj8lZQM6Z5AskJhjSca8HwvsLj-I9itwg485FSi4UF7glhYX8HbJVi4XzLLmb72-XQIAUGtQNE9xdzMrTK7BzbLCC0j05028VVHLjcKyz6mkpayit7jCFuJErwdyZNdtkyySUK_iCMh-d5DQf53SYFXSQDUYpLKEsqMvSgtJsmNHxaZFvUvhWyvFPT4rhKMtGNM9oMR64WgrIhVX6Pt5zOOvQ4TkQfMPNDycC-WQ

will add more docs on information flow

**Comment by akirillo** [comment]
@erayack it's a dense read, but I think I'm just about to start diving into how the `StateFetcher` gets used in the pipeline as I read more about how the `FetchClient` gets instantiated - I'm still thinking about how low-level this book chapter should go, though

@mattsse the mermaid diagrams were super useful! I know we use them a couple of times throughout the rustdocs and I'm wondering if they should also get pulled into the book, which is meant to be more high-level...

Regardless, I just pushed my current progress on the draft of the doc if you want to check it out (#445)! Still a lot to write and it's got `TODO`s scattered throughout, but directionally I'm starting with how the `network` crate's items are consumed in the pipeline and going down the levels of abstraction & the various structs / traits underneath.

If you take a look, lmk what you think!

**Comment by akirillo** [comment]
(would recommend viewing the draft by pulling the branch and running `mdbook serve` from the root)

**Comment by akirillo** [comment]
#445 merged, closing
