### ISSUE TITLE
Add function for intrinsic gas checks

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4504]
### Describe the feature

the txpool validation currently does not validate intrinsic gas cost based on the tx's data and accesslist

The impl is already available:

https://github.com/mattsse/revm/blob/main/crates/interpreter/src/gas/calc.rs#L342-L348

but should be exposed in primitives or reth-revm-primitives

ref:

https://github.com/ethereum/go-ethereum/blob/28857080d732857030eda80c69b9ba2c8926f221/core/txpool/validation.go#L97-L105

https://github.com/ethereum/go-ethereum/blob/28857080d732857030eda80c69b9ba2c8926f221/core/state_transition.go#L68-L69

## TODO

* add function to compute intrinsic gas 
* add check in txpool validation
* add new error variants

**Comment by chirag-bgh** [comment]
I can take this.

**Comment by mattsse** [comment]
sweet,
what we want here is a new function `intrinsic_gas` in here

https://github.com/paradigmxyz/reth/blob/685148117aab83d4b38f2e05adb8c6c96943f7db/crates/revm/revm-primitives/src/compat.rs#L35-L35

that accepts bools for the hardforks used in `initial_tx_gas` and converts those bools into SpecId and just calls the revm function

**Comment by mattsse** [comment]
oh I see, then this is blocked by #3512

but if you like you can start adding the function using revm main deps, however you'll run into a few compile issues

https://github.com/paradigmxyz/reth/pull/3512/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R78-R80

**Comment by chirag-bgh** [comment]
> oh I see, then this is blocked by #3512
> 
> but if you like you can start adding the function using revm main deps, however you'll run into a few compile issues
> 
> https://github.com/paradigmxyz/reth/pull/3512/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R78-R80

Okay, I will wait till #3512 is merged.

**Comment by supernovahs** [comment]
#3235

**Comment by chirag-bgh** [comment]
Oh this is duplicate then

> #3235

**Comment by mattsse** [comment]
@chirag-bgh this is now unblocked

do you have bandwith for this?

**Comment by chirag-bgh** [comment]
I can make a pass on this if @supernovahs wants to take it

> @chirag-bgh this is now unblocked
> 
> do you have bandwith for this?

**Comment by mattsse** [comment]
@supernovahs already has some other issues :)

so if you have the bandwidth, please go for it

**Comment by hack3r-0m** [comment]
I would like to give it a try

**Comment by chirag-bgh** [comment]
> I would like to give it a try

Pls go for it

**Comment by supernovahs** [comment]
Is assignee still working on this?

**Comment by mattsse** [comment]
this should be an easy pr now that it's unblocked, assigned

**Comment by supernovahs** [comment]
Anything left for this?
