### ISSUE TITLE
Fix broken mermaid diagrams

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#452]
### Describe the bug

currently docs.rs fails to render the inline mermaid due to a syntax error, however mermaid.live renders it just fine.

maybe some weird formatting or syntax

### Steps to reproduce

inset net/network

cargo doc --open --no-deps

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by gakonst** [comment]
Tracking here https://github.com/mersinvald/aquamarine/issues/28

**Comment by gakonst** [comment]
fyi https://github.com/mersinvald/aquamarine/issues/28 has a fix for it now, so we can close soon
