### ISSUE TITLE
Add test for running stages partially

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#454]
### Describe the feature

Add tests that check that a stage can be run successfully on e.g. a range of blocks 0-500 and then a range of blocks 500-1000.

**Comment by MegaRedHand** [comment]
Hello! I'd like to take this on. I've noticed the [headers](https://github.com/paradigmxyz/reth/pull/843), [bodies](https://github.com/paradigmxyz/reth/blob/a5bdfe54dd96c5ad2a0251ab253905a8712ff70d/crates/stages/src/stages/bodies.rs#L341) and [sender](https://github.com/paradigmxyz/reth/blob/a5bdfe54dd96c5ad2a0251ab253905a8712ff70d/crates/stages/src/stages/sender_recovery.rs#L183) stages already have tests with partial runs. So we are only missing one for the total difficulty stage, right?
