### ISSUE TITLE
NewPooledTransactionHashes uses incorrect size for blob transactions

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#4571]
The `NewPooledTransactionHashes` message we broadcast uses the following method to populate the size associated with a transaction:
https://github.com/paradigmxyz/reth/blob/261a9f949996eb2f6129cf7f17469d5134c09761/crates/net/network/src/transactions.rs#L265-L271

with implementation:
https://github.com/paradigmxyz/reth/blob/261a9f949996eb2f6129cf7f17469d5134c09761/crates/net/network/src/transactions.rs#L733-L744

This uses `PropagateTransaction` which only computes the size based on the `TransactionSigned::length`. This is not accurate for blob transactions, which must account for the length of the `BlobSidecar` as well, i.e. the `PooledTransactionsElement` length is more appropriate.

**Comment by mattsse** [comment]
nice find, this requires two fixes,

set accordingly when the tx is created with blob, and update length by fetching from blobstore during validation (re-injected transactions)
