### ISSUE TITLE
feat(rpc): improve `Filter` topic functions

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#4575]
### Describe the feature

At the moment, in the `Filter` implementation, there are four topics functions (`topic0`, `topic1`, `topic2`, `topic3`). The `topic0` function indicates the name of the event in the case of non-anonymous events. 
 
https://github.com/paradigmxyz/reth/blob/b8e15fa10b6da6fa8650047a13b9887ceb3d683f/crates/rpc/rpc-types/src/eth/filter.rs#L407-L412

This could be indicated more clearly, either with a filter on anonymous events or with better naming so that the user can more easily understand the use cases for these topic functions plus the difference between `topic0` and the other ones.

**Comment by mattsse** [comment]
agree, this is mostly debt from ethers

**Comment by mattsse** [comment]
closed via #4950
