### ISSUE TITLE
Extremely Slow State Sync

### ISSUE THREAD

**Issue by jrocco2** [paradigmxyz/reth#4604]
### Describe the bug

I am 5 days into syncing a full archive node for RETH and according to the ETA I have at least another 7 days of syncing ahead (And that's only for the execution stage!). It feels like this node is going to be syncing for a month but I was under the impression that syncing could be done in less than a week.

I am running the node on a Google Cloud VM using an`e2-standard-4` machine type with 2 TB of SSD persistent disk (currently only 800 GB used). It appears CPU utilization never goes over 20% and Memory usage doesn't go over 30% which makes me feel this is not a resource issue.

### Steps to reproduce

Im running the following command on the VM:

`RUST_LOG=info reth node --http --ws --datadir reth-db/ --metrics 127.0.0.1:9001 --debug.tip 0x55a254b83993c57c45341500707040b90059d737e10acddbb8dc07d055d7c119`

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.8

### What database version are you on?

Current database version: 1
Local database is uninitialized

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by jrocco2** [comment]
It also says specifically in the [RETH Book ](https://paradigmxyz.github.io/reth/installation/installation.html?highlight=performance#disk)that syncing "on a GCP Persistent SSD takes around 5 days".

**Comment by azertyuiopvnx** [comment]
Execution stage is single thread & very CPU intensive
E2 gcp instance is shared CPU ? If yes, don't expect much performance on syncing reth (execution stage)

**Comment by jrocco2** [comment]
I found another video where @gakonst recommended using latitude.sh. I got myself an `m3.large.x86` and it was synced in ~50 hours as indicated.

**Comment by azertyuiopvnx** [comment]
If you use latitude.sh, don't forget the 250$ coupon discount ^^
You can find the coupon here : https://paradigmxyz.github.io/reth/installation/installation.html (at the end of page)

**Comment by jrocco2** [comment]
Dude thats awesome! Thank you! You can basically sync a full node for free. Much appreciated
