### ISSUE TITLE
Support blob transaction sidecar listeners

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4607]
### Describe the feature

There's a usecase for listening to 4844 blob sidecars, for example archiving.

currently the existing listeners only emit the tx without the sidecar, since it's extracted and put into the blobstore.

we can add another listener channel specifically for new blobs.

## TODO
* add trait function to TransactionPool trait
* add listeners mutex
* emit new blobs

Refs:

https://github.com/paradigmxyz/reth/blob/a8e0880a98142cc339c7d6c6e9d060082094e764/crates/transaction-pool/src/pool/mod.rs#L407-L411

https://github.com/paradigmxyz/reth/blob/a8e0880a98142cc339c7d6c6e9d060082094e764/crates/transaction-pool/src/pool/mod.rs#L137-L138

**Comment by chirag-bgh** [comment]
I will take ths.

**Comment by 0xprames** [comment]
hey there @chirag-bgh! - I saw this was going a bit stale so I opened a smol PR for it myself

If you're actively looking at this (and I was mistaken that it was going stale!), lmk and I'd love to close out my PR in favor of yours.

Please let me know :D

**Comment by chirag-bgh** [comment]
> hey there @chirag-bgh! - I saw this was going a bit stale so I opened a smol PR for it myself
> 
> If you're actively looking at this (and I was mistaken that it was going stale!), lmk and I'd love to close out my PR in favor of yours.
> 
> Please let me know :D

No worries, I hadn't found any time to look at this.
