### ISSUE TITLE
`PeersHandle` method for getting peer information

### ISSUE THREAD

**Issue by jonasbostoen** [paradigmxyz/reth#461]
### Describe the feature

Currently, there's no way to request additional information about a peer through `NetworkHandle.PeersHandle`. We can add a method like `peer_by_id` to get the extra info stored in the `Peer` struct.

### Additional context

I can work on this. It would involve adding a new `PeerCommand` for getting a peer, where the manager can send `Option<Peer>` on a oneshot channel sender. The `Peer` struct would also need to be public.

**Comment by mattsse** [comment]
what info should be included there?

**Comment by jonasbostoen** [comment]
Nothing extra, just what's already in the `Peer` struct:
```rs
pub struct Peer {
    /// Where to reach the peer
    addr: SocketAddr,
    /// Reputation of the peer.
    reputation: i32,
    /// The state of the connection, if any.
    state: PeerConnectionState,
}
```

`addr` could be used for constructing the enode for example. If we decide to add more info in this struct in the future, the way for getting it would already be there.

**Comment by mattsse** [comment]
gotcha, supportive of that.

you wanna take this on?

**Comment by jonasbostoen** [comment]
Yes sir!
