### ISSUE TITLE
Integrate BundleBuilder

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#4614]
Integrate bundle builder inside reth: https://github.com/bluealloy/revm/pull/649

comment: https://github.com/paradigmxyz/reth/pull/3512#discussion_r1326447552

**Comment by alessandromazza98** [comment]
I can take it

**Comment by rakita** [comment]
> I can take it

go for it!

**Comment by quentinv72** [comment]
Is this still relevant? If so, I can work on it.
