### ISSUE TITLE
Integrate `write_to_db` from State to provider

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#4620]
Comment from here: https://github.com/paradigmxyz/reth/pull/3512#discussion_r1311308380

> the naming is very confusing to me, because writing reverts results in wiped storage, because this does not actually write anything and instead deletes?

> I inherited this, can bikeshed a little on this, should be fruitful.
> 
> little history, this pattern was used when we still were not sure how to handle Provider and needed to decide on the pattern for how to write things to the database. At that point in time this was one of the promising paths that we had.
> 
> What we have decided and have now is @joshieDo had split the Provider with the traits so I think this should be moved there and have BundeStateProvider trait that will have commit_state(bundle: State) and commit_reverts(reverts:Reverts). This feels nicer imo and it shouldn't be a big change.

**Comment by alessandromazza98** [comment]
Hi,
I would like to work on it but it's not clear for me what is the required work to be done.

I mean, what I understand from the comments is:
- create a new `BundleStateProvider` trait (maybe inside `state.rs` file)
- that trait should have `commit_state(bundle: State` and `commit_reverts(reverts: Reverts)` functions.

But then I don't understand how to split the `write_to_db` function into this trait.
