### ISSUE TITLE
Wrap revm `Return` status to proper error.

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#463]
### Describe the feature

Revm will refactor return type to be more friendly and when this happens errors should be properly wrapped inside reth

**Comment by rakita** [comment]
dependent on: https://github.com/bluealloy/revm/issues/309

**Comment by rakita** [comment]
revm v3.0.0 got released so this can be started

**Comment by fkrause98** [comment]
Can I work on this?

**Comment by rakita** [comment]
> Can I work on this?

Go for it!

**Comment by fkrause98** [comment]
I've been thinking about this and dealing with some errors after bumping the revm version but 
I don't think I quite get a general idea on how to wrap the revm errors.
Any ideas or tips on how to handle this?

**Comment by rakita** [comment]
@fkrause98 most of the changes are dealing with breaking changes of the new revm version, kudos if you did it!

error wrapping is mostly cleaning up this chunk of code: https://github.com/paradigmxyz/reth/blob/df6e3143c3bf3b7d46a185ff6fa950b69f429c08/crates/executor/src/executor.rs#L367-L391

`is_success` can be set with a use of this: https://github.com/bluealloy/revm/blob/v20/crates/primitives/src/result.rs#L40

execution::Error can probably be expanded with `EVMError`

**Comment by fkrause98** [comment]
Oh, ok!
Seems like what I've been doing does not strand too far from what you just said.
Thanks, I'll have a PR ready soon 😄.

**Comment by gakonst** [comment]
@fkrause98 thanks for taking this on - can you pls push your branch and share your current progress? upgrading to revm 3.0 is P0 right now (both in Reth & Foundry) and would like to drive this to completion ASAP! thank you^^

**Comment by fkrause98** [comment]
Sure, [here it is](https://github.com/paradigmxyz/reth/pull/1235)!
Please, let me know what is to be improved.
