### ISSUE TITLE
Add More helper functions to TransactionsHandle type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4651]
### Describe the feature

It can be useful to get an overview of what transactions certain peers know about and to what peers we're connected

https://github.com/paradigmxyz/reth/blob/11ee5d75308d4a7519fdecba4a0fa5f51c61cf0e/crates/net/network/src/transactions.rs#L820-L821

## TODO
* add new command for retrieving the active peer ids
* add new command for propagating a hash to a specific peer PropagateHashTo(H256, PeerId),
* add new command for propagating full transactions to a specific peer 
* add new command for retrieving the tx hashes of peers: https://github.com/paradigmxyz/reth/blob/11ee5d75308d4a7519fdecba4a0fa5f51c61cf0e/crates/net/network/src/transactions.rs#L831-L834
  * For all Peers, for a specific peer

ref

https://github.com/paradigmxyz/reth/blob/11ee5d75308d4a7519fdecba4a0fa5f51c61cf0e/crates/net/network/src/transactions.rs#L61-L63

**Comment by luffyforever** [comment]
hello can i take this ? but please if i have problem or not understand something, may i ask about it ?

**Comment by mattsse** [comment]
sure, we can do these commands one by one

start with `PropagateHashTo(H256, PeerId)`

which is similar to 

https://github.com/paradigmxyz/reth/blob/11ee5d75308d4a7519fdecba4a0fa5f51c61cf0e/crates/net/network/src/transactions.rs#L75-L78

if you need some pointers please open a draft and we take it from there

**Comment by luffyforever** [comment]
> sure, we can do these commands one by one
> 
> start with `PropagateHashTo(H256, PeerId)`
> 
> which is similar to
> 
> https://github.com/paradigmxyz/reth/blob/11ee5d75308d4a7519fdecba4a0fa5f51c61cf0e/crates/net/network/src/transactions.rs#L75-L78
> 
> if you need some pointers please open a draft and we take it from there

Thank you so much !

**Comment by luffyforever** [comment]
Hello, I sincerely apologize, but I have decided to discontinue this because i'm not comfortable with this. I want to extend my apologies once more

**Comment by mattsse** [comment]
no worries!
maybe a different issue ;)

**Comment by duguorong009** [comment]
Hey, I am interested to take this issue.
(BTW, it seems that #4691 also mentions the same problem.)

I will start from `PropagateHashTo(hash, peer_id)` as recommended.

**Comment by tcoratger** [comment]
> Hey, I am interested to take this issue. (BTW, it seems that #4691 also mentions the same problem.)
> 
> I will start from `PropagateHashTo(hash, peer_id)` as recommended.

This issue can be closed by #4668 if I'm not mistaken @mattsse ? But issue #4691 is based precisely on the implementation of helper functions made in #4668: for each new variant, we have to implement the missing logic in `TransactionsManager` to replace the `todo!()` in the `on_command` function.

**Comment by duguorong009** [comment]
@mattsse 
Can you check the draft PR #4713 ? 
Thx in advance!

**Comment by duguorong009** [comment]
BTW, what is going on with issue #4691?
I am sure these two issues aim for same goal.

**Comment by duguorong009** [comment]
@mattsse 
I have a question about this logic. https://github.com/paradigmxyz/reth/blob/main/crates/net/network/src/transactions.rs#L302-L329
As far as I understand, the `new_pooled_hashes` includes hashes of both blob tx and full tx.
But, when sending transctions, the `max_num_full` peers receive only full txs, and other peers receive only blob tx hashes.
So, it means that `max_num_full` peers do NOT receive blob tx hashes, and other peers do NOT receive full txs.
I think this is wrong, since I believe that `max_num_full` peers not only receive full txs, but also blob tx hashes.
Can you give explanation?

**Comment by duguorong009** [comment]
@mattsse 
Here is another PR for helper impls - PR #4806 .
