### ISSUE TITLE
Add implementations for `DbTxMut` functions for `TxMock`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#4663]
### Describe the feature

At the moment, all the functions of the `DbTxMut` trait are to be implemented for the `TxMock` structure to then be able to be used in unit tests:

https://github.com/paradigmxyz/reth/blob/1406142af879567c214605b5a8189acf909b62b1/crates/storage/db/src/abstraction/mock.rs#L85-L113

**Comment by peyha** [comment]
Hello, can I take this ?
