### ISSUE TITLE
Add implementations for `DbTx` functions for `TxMock`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#4664]
### Describe the feature

At the moment, all the functions of the `DbTx` trait are to be implemented for the `TxMock` structure to then be able to be used in unit tests:

https://github.com/paradigmxyz/reth/blob/1406142af879567c214605b5a8189acf909b62b1/crates/storage/db/src/abstraction/mock.rs#L57-L83

**Comment by Arindam2407** [comment]
can I take up this issue?

**Comment by supernovahs** [comment]
I can  try this

**Comment by fgimenez** [comment]
Given that #5015 is merged this issue should be closed right?
