### ISSUE TITLE
Show enode address on startup

### ISSUE THREAD

**Issue by mohasdev** [paradigmxyz/reth#4698]
### Describe the feature

In others clients when we launch them, they print the enode address in the terminal by default.
This can be very useful, cause in reth to get the enode adress we need to launch other command and specify options like : 

``reth node --http --http.api all``
and 
``cast rpc admin_nodeInfo``

**Comment by 0xprames** [comment]
can I take a look at this issue?

**Comment by mattsse** [comment]
assigned,

geth logs on launch:

> INFO [09-21|15:52:20.523] Started P2P networking                   self=enode://418809a18bb100d658081d85db086ba79058c628e8ad20053cb9229689e260e0b72c317e944d2c8fc555e01e90a9c2be59f2db10d189c40035764fd702e0e619@127.0.0.1:30303

we can do it similarily
