### ISSUE TITLE
Bug in TypedTransactionRequest .into_transaction()

### ISSUE THREAD

**Issue by orkunkilic** [paradigmxyz/reth#4704]
### Describe the bug

We are using reth rpc-types crate in our project and discovered this bug.

Basically while converting TypedTransactionRequest into Transaction, conversion of `U256` nonce to `u64` nonce is failing. You can see the panicing section and test to reproduce it [here](https://github.com/bkolad/reth/pull/1).

Line failing: https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-types/src/eth/transaction/typed.rs#L50
Exact assertion failing: https://github.com/recmo/uint/blob/main/src/bytes.rs#L93

### Steps to reproduce

Pull https://github.com/bkolad/reth/pull/1
Run added test
It will panic in conversion

### Platform(s)

Mac (Apple Silicon)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
oh yeah to_be_bytes panics if bytes are not the same.

hmm the const generic of `to_be_bytes` is kinda pointless

need to make this conversion fallible

**Comment by mattsse** [comment]
blocked by #4674

**Comment by DaniPopes** [comment]
Read the function docs @mattsse, it should be a compile error but it's blocked by Rust const generics / inline const.
