### ISSUE TITLE
Rename `db` to `tx` where `StageDB` used to be

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#471]
### Describe the feature

In this PR https://github.com/paradigmxyz/reth/pull/470 I changed `StageDB` to `Transaction` but the actual variable names are still `db: Transaction`. Would be easy to convert all of these to `tx` so that the var communicates the type.

**Comment by 0xYami** [comment]
Hello @gakonst can I take this one?

**Comment by gakonst** [comment]
Go for it!
