### ISSUE TITLE
Consolidate primitives imports to reth-primitives

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#4714]
### :warning: Base on #4737 (`alloy`) :warning:

Currently we use `reth-primitives`, `revm-primitives`/`revm::primitives`, `reth-revm-primitives`, and `ethers-core` interchangeably for primitives types / utils. This might change in the future and they should all be replaced with `reth-primitives`.

**Comment by tcoratger** [comment]
@DaniPopes @mattsse Maybe to start with that we can first migrate the `revm-primitives` folder of the `revm` crate directly inside the `primitives` crates so that everything related to `reth-revm-primitives` will now be part of `reth-primitives`, what do you think?

**Comment by DaniPopes** [comment]
Yeah I think that's doable.

We can also remove all compat hacks between reth and revm since they use the same types:

![image](https://github.com/paradigmxyz/reth/assets/57450786/d701be2f-e6e2-42e5-945e-a7d531416f08)

(needs #4674)

**Comment by mattsse** [comment]
sgtm

**Comment by duguorong009** [comment]
@tcoratger @DaniPopes 
Is there anyone working on this issue?
If not, I would like to pick up.

BTW, what should be the base branch of this issue? `Alloy` or `main`?

**Comment by supernovahs** [comment]
What's next for this? I can do it.
