### ISSUE TITLE
Replace ethers usage in `reth_primitives::abi::decode_revert_reason`

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#4730]
### :warning: Base on #4737 (`alloy`) :warning:

This function:
https://github.com/paradigmxyz/reth/blob/a7928419668d9f05bf36a406ce7662dd42576cd3/crates/primitives/src/abi.rs#L9-L16

Should try decoding first with `alloy_sol_types::GenericContractError`, then `String::from_utf8`

Also it should take in `&[u8]` instead of `Bytes`

**Comment by alessandromazza98** [comment]
I could take it
