### ISSUE TITLE
`debug_traceCallMany` and `trace_callMany` inconsistencies with erigon / bugs

### ISSUE THREAD

**Issue by geomad** [paradigmxyz/reth#4731]
### Describe the bug

I found some inconsistencies with erigon on the said methods, along with a bug. I will desribe them as best as possible as I don't have access to erigon and my environment at the moment.

on `debug_traceCallMany` :
with args 
` [ { "transactions": [tx1]  },  { "transactions": [tx2,tx3]  } ]`

erigon would respond:
```
[
 [ //block 
  {}, // | tx in bundle 
 ],
 [ //block
  {}, // | txs in bundle
  {}  // |
 ]
]
```

while reth ommits the inner `[]` (so something like `[{},{},{}]`)

Also on `blockOverride` of the method above, erigon uses `blockNumber` and `timestamp`  as arguments (https://github.com/ledgerwatch/erigon/issues/4471) , while reth `number` and  `time` (just tested those 2)

On `trace_callMany` :
When something is altered from 0 ->value erigon uses `['+']` only for code , while in the rest cases (storage,balance etc) `['*'] {from: <zero hash>, to: <new value>}`

Also the bug: when slot 1 (or any other slot) of a contract holding a `uint` is altered instead of 0x0...1 (` storage: { '0x0000000000000000000000000000000000000000000000000000000000000001': {...} }` )  some random value appears

### Steps to reproduce

run the methods above (sorry cannot provide a script right now)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks for flagging, do you have two json outputs I can compare?

**Comment by geomad** [comment]
> thanks for flagging, do you have two json outputs I can compare?

Unfortunately I don't have access to erigon anymore, and no access to my dev environment (this one for a few more weeks). I just noticed those with a quick look since some of my scripts are broken.
I could put together a script for testing the above in the next few days, but can't provide the erigon json.

**Comment by 0xSt1ng3R** [comment]
I have a similar (slots) bug. I will try adding some examples from reth-geth-erigon in the following days.

**Comment by mattsse** [comment]
I believe those are fixed now
