### ISSUE TITLE
Merkle trie root mismatch at #18193649

### ISSUE THREAD

**Issue by KKRAKOVIA** [paradigmxyz/reth#4734]
### Describe the bug

as requested, here's the logs for the unexpected lose of sync during normal execution
[reth_log.txt](https://github.com/paradigmxyz/reth/files/12704459/reth_log.txt)
[ligthouse_logs.txt](https://github.com/paradigmxyz/reth/files/12704460/ligthouse_logs.txt)

### Steps to reproduce

normal execution

### Platform(s)

Linux (x86)

### What version/commit are you on?

alpha.8

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by KKRAKOVIA** [comment]
another log from @og484
"Merkle trie root mismatch at #18193649 "

https://pastebin.com/jFZWQVMv

**Comment by asdfcrypto** [comment]
Happened for me too.

reth logs
https://pastebin.com/kECH4cxW

**Comment by KKRAKOVIA** [comment]
i've used
reth stage unwind
to get back -100 blocks, seems something is still blocking the sync
https://pastebin.com/KUt6XAz5

**Comment by KKRAKOVIA** [comment]
upgrading the docker image to the latest git version fixed the problem.
Synced now o/

**Comment by gakonst** [comment]
Amazing. Yep as discussed, the fix is:
1. Stop node
2. Pull latest main (#3512 fixed the issue, big rework of how we handle selfdestructs)
3. `reth stage unwind num-blocks 1000`
4. Restart & should be fixed.
