### ISSUE TITLE
Remove ethers conversions (`mod ethers_compat` etc) in `reth-primitives`

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#4738]
### :warning: Base on #4737 (`alloy`) :warning:

Goal: get rid of `ethers-core` in `reth-primitives` as much as possible

**Comment by tcoratger** [comment]
@DaniPopes What do you have in mind here except `ethers_compat`? I would say that `ethers_compat` can be removed now and then we wait for https://github.com/paradigmxyz/reth/pull/4737 and we open a separate issue for:
- `FromHex`
- `Chain` types

that are also related to conversion but can be converted into separate issues to avoid too big changes and confusion, what do you think?

**Comment by tcoratger** [comment]
> I guess just `ethers_compat` looking at it, I named this issue before splitting it in the task list in the tracking issue. I don't know what you mean by `FromHex`, and `Chain` is tracked in #4741. What related conversion do you mean?

@DaniPopes Here:

https://github.com/paradigmxyz/reth/blob/371388da5d2d6b21c7cd0392d340df66cea9d099/crates/primitives/src/header.rs#L721

I imagine that if we want to completely eliminate `ethers-core` from the `primitives` crate we will also have to remove this dependency to switch to alloy, right? Or did I miss something?
