### ISSUE TITLE
Remove `reth_primitives::utils::serde_helpers` re-export

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#4739]
### :warning: Base on #4737 (`alloy`) :warning:

Goal: get rid of `ethers-core` in `reth-primitives` as much as possible

**Comment by supernovahs** [comment]
I can take this?

**Comment by DaniPopes** [comment]
Fixed in #4808, sorry @supernovahs but this was pretty simple and necessary for that PR
