### ISSUE TITLE
Deprecate `H*` type re-exports, and rename to `B*` in the codebase

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#4740]
### :warning: Base on #4737 (`alloy`) :warning:

(Referring to H64, H256...)

- Remove `H*` types re-export; this means also renaming the types in the entire codebase:
```diff
- pub use alloy_primitives::{... BXXX as HXXX ...};
+ pub use alloy_primitives::{... BXXX ...};
```
- Re-add `H*` types with a hidden, deprecated type alias for backwards compatibility:
```rust
#[doc(hidden)]
#[deprecated = "use BXXX instead"]
pub type HXXX = BXXX;
```

Note: you might want to wait until the rest of #4715 is done to avoid conflicts

**Comment by supernovahs** [comment]
Can I take this

**Comment by supernovahs** [comment]
Should I push in accordance with alloy branch?

**Comment by DaniPopes** [comment]
Yes please!
