### ISSUE TITLE
Migrate EIP-712 and signing code in `reth-rpc` to Alloy

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#4742]
### :warning: Base on #4737 (`alloy`) :warning:

Use `alloy-sol-types` for EIP-712 in `EthSigner`, re-implement `ethers_core::utils::hash_message` in `reth-primitives`:

1. https://github.com/paradigmxyz/reth/blob/675c6bfc390b17d274541ef251375741f48dd3c3/crates/rpc/rpc/src/eth/signer.rs#L89-L93
2. https://github.com/paradigmxyz/reth/blob/675c6bfc390b17d274541ef251375741f48dd3c3/crates/rpc/rpc/src/eth/api/sign.rs#L22-L29

**Comment by supernovahs** [comment]
Can I take this

**Comment by 0xprames** [comment]
ah I was just starting this! haha

no worries though, you can go for it @supernovahs. I'll find another one
