### ISSUE TITLE
Add Chainspec::hardfork_fork_id helper function

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4745]
### Describe the feature

Same as 

https://github.com/paradigmxyz/reth/blob/344ffbd38f253356e9fdb8dffda2587279507bfc/crates/primitives/src/hardfork.rs#L46-L53

but for chainspec

with additional helpers:
* shanghai_fork_id

**Comment by 0xprames** [comment]
could I take this on?

I can start looking at this in ~40ish mins
