### ISSUE TITLE
Common crashing / killed state

### ISSUE THREAD

**Issue by drewstone** [paradigmxyz/reth#4762]
### Describe the bug

Quite often (every few days I check back on the node) it seems that the node has crashed inside our cloud machine. We are running this in `tmux` and I am curious if we should build out some meta-infra to restart the process when it crashes if this is expected behaviour. Is this expected? We are also running this w/ a lighthouse node on the same machine.

### Steps to reproduce

Followed the documentation and running with
```
RUST_LOG=info reth node  \
	--authrpc.jwtsecret /secrets/jwt.hex \
	--authrpc.addr 127.0.0.1 \
	--authrpc.port 8551
```

### Node logs

```
2023-09-21T17:53:13.892157Z  INFO reth::cli: Status connected_peers=98 stage=MerkleExecute checkpoint=100.0% eta=unknown
2023-09-21T17:53:42.796513Z  INFO reth::node::events: Forkchoice updated head_block_hash=0xd70047711ed300f9ce20f13c57d4146caa5b1331ecf6487b35bc5ad1129907c3 safe_block_hash=0xb72755a7077847699169d99f2ad6a8047cfb
930599b9a60943a2c28b8e054936 finalized_block_hash=0xf13bdf4f3da841c4d33eefcee6d6bf803f75eaa7a5533018b935df529c3126f5 status=Syncing
2023-09-21T17:53:43.893016Z  INFO reth::cli: Status connected_peers=98 stage=MerkleExecute checkpoint=100.0% eta=unknown
Killed
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.1.0-alpha.4

### What database version are you on?

Current database version: 1
Local database version: 1

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> 0.1.0-alpha.4

is this correct?

latest is 0.1.0-alpha.8

**Comment by mattsse** [comment]
too many that I could keep track of them

but a lot of merkle/hashing/memory fixes since then

**Comment by gakonst** [comment]
Latest now is alpha ten so I am closing this and pls reopen if still a problem!
