### ISSUE TITLE
Upstream `reth_primitives::abi::decode_revert_reason` to Alloy

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#4789]
### :warning: Base on #4737 (`alloy`) :warning:

Move this function: https://github.com/paradigmxyz/reth/blob/7095a6078606fa5065814d6d2c3f34c8980814c5/crates/primitives/src/abi.rs#L11

To `alloy_sol_types::types::error`: https://github.com/alloy-rs/core/blob/7cb5bb220dfeacb780c55f4ca9f49650ae0bcce6/crates/sol-types/src/types/error.rs#L1

And add tests from random on-chain reverts.

cc #4759 @alessandromazza98

**Comment by alessandromazza98** [comment]
Hi Dani, as I said in the previous PR, I can work on this and write some tests.
