### ISSUE TITLE
Remove `reth-primitives` dependencies `tokio` and `tokio-stream`

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#4795]
### Describe the feature

These are used only in one place and they slow compilation significantly since it's at the root of almost every other crate in the workspace.

https://github.com/paradigmxyz/reth/blob/7024e9a8e91e9546ffd20b5aae65e85888f591a6/crates/primitives/src/listener/event_listeners.rs#L1-L2

## TODO
* move event listeners type to new crate `reth-mpsc` or `reth-tokio-utils`

**Comment by gr4yha7** [comment]
@mattsse can i start with this?

**Comment by mattsse** [comment]
@DaniPopes I think we still want this, to keep primitives lean
