### ISSUE TITLE
Add native reth_rlp decoding for ENR

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#482]
### Describe the feature

currently the `reth_rlp::Decode` impl for ENR does not advance the buffer correctly.

Ideally we have native `reth_rlp::Decode` instead of delegating to `rlp` crate

**Comment by TechieBoy** [comment]
I looked into this. Decoding the payload into all of the ENR fields is pretty straightforward. 

However the external ENR crate has all its fields set to private and we cannot create a new instance with an already existing signature (without a private key). We will have to add a pr to the `enr` crate to allow creating instances with the rlp decoded signature.

**Comment by mattsse** [comment]
yeh, that's what I expected.

however, what we should do regardless is:

1. decode rlp header via reth_rlp, this way we get the length
2. decode as we currently do
3. advance the buffer via the header payload length

this will at least get rid of the unsoundness we currently have.
Do you want to try this?

**Comment by TechieBoy** [comment]
> Do you want to try this?
Yes. Will do it.
