### ISSUE TITLE
Add new TransactionPool trait for getting the best transactions with blob fee

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4822]
### Describe the feature

we currently have to check against the internally enforced basefee

https://github.com/paradigmxyz/reth/blob/66fc1964d7aed37df56f397a7a234e55da27d4ef/crates/transaction-pool/src/traits.rs#L229-L236

which checks fetches the best transactions accordingly:

https://github.com/paradigmxyz/reth/blob/66fc1964d7aed37df56f397a7a234e55da27d4ef/crates/transaction-pool/src/pool/txpool.rs#L227-L245

with upcoming blob fee, we need the same for blob fee, since the pool's tracked blob fee could be different then the targeted (for example block building)

## TODO
* Add new function `best_transactions_with_attributes` which takes a new struct that has: `basefee: u64, blob_fee: Option<u64>`

**Comment by PanGan21** [comment]
Hi! Could I give it a try? :)

**Comment by mattsse** [comment]
more context about blobs,
all blobs are stored in the blob subpool, so we need something like this but for blob fee

`let unlocked = self.basefee_pool.satisfy_base_fee_transactions(basefee);`

but in the blob subpool

**Comment by mattsse** [comment]
@PanGan21 I noticed some parts of the blob pool are still wip,

so I'm okay with a skeleton impl for `BlobTransacions::satisfy_attributes`

**Comment by DoTheBestToGetTheBest** [comment]
Hello Mattsee, please add new good first issue, i'm still looking for good new issue. Thank you so much
