### ISSUE TITLE
Reth on Goerli periodically loses sync

### ISSUE THREAD

**Issue by yorickdowne** [paradigmxyz/reth#4829]
### Describe the bug

Every so often, `--full` Reth on Goerli will lose sync

### Steps to reproduce

Sync Reth on Goerli, with `--full` flag
Observe

When the issue occurs, a curl to the syncing endpoint will return something like

```
curl -s -m2 -N -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' "https://goerli-a.cryptomanufaktur.net"
{"jsonrpc":"2.0","result":{"startingBlock":"0x94fec2","currentBlock":"0x9515b5","highestBlock":"0x9515b5","warpChunksAmount":null,"warpChunksProcessed":null},"id":1}
```

This does not last long, just long enough to be declared "down" by our custom haproxy check

I didn't see a smoking gun in logs, but I did see a prune log right around when this happened. I am wondering whether the prune run causes it to lose sync.

The node is also serving RPC
[reth.log](https://github.com/paradigmxyz/reth/files/12743504/reth.log)

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.9 Commit SHA: b701cbc

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
looking at the logs,

```
eth-goerli-execution-1  | 2023-09-27T21:36:26.387735Z  INFO reth::node::events: Forkchoice updated head_block_hash=0x661c654a105f0d4d6fa8091f388296cad9e7aded10a2806406239392e8664db4 safe_block_hash=0x1c85a0d2a3599181274bbe52750f5b3851d94190afde45e33c080e7c7c016f73 finalized_block_hash=0xdc24c315714ded39afb28893fc62a2165237ade500f1e5e060315ffbecbccc06 status=Valid
eth-goerli-execution-1  | 2023-09-27T21:36:29.183070Z  INFO reth::cli: Status connected_peers=110 latest_block=9770430
eth-goerli-execution-1  | 2023-09-27T21:36:37.293529Z  INFO try_insert_validated_block{block=(9770431, 0x6f4d3577ee094cf6659d9c33d3722467fb5ae74f34d5af01ca378ffd5ca67ef1)}: blockchain_tree: return=Ok(Valid)
eth-goerli-execution-1  | 2023-09-27T21:36:37.293553Z  INFO reth::node::events: Block added to canonical chain number=9770431 hash=0x6f4d3577ee094cf6659d9c33d3722467fb5ae74f34d5af01ca378ffd5ca67ef1
eth-goerli-execution-1  | 2023-09-27T21:36:37.331840Z  INFO make_canonical{block_hash=0x6f4d3577ee094cf6659d9c33d3722467fb5ae74f34d5af01ca378ffd5ca67ef1}: blockchain_tree: Committing new canonical chain: [(9770431, 0x6f4d3577ee094cf6659d9c33d3722467fb5ae74f34d5af01ca378ffd5ca67ef1)]
```

looks like it's still synced?

are you specifically referring to the rpc endpoint?

**Comment by yorickdowne** [comment]
It's reporting it is no longer synced via RPC, which causes our haproxy to mark it down

**Comment by mattsse** [comment]
fyi @shekhirin

**Comment by shekhirin** [comment]
> This occurs repeatedly, but not "all the time" ... a few times a day maybe.

Probably when HAProxy healthcheck coincides with pruner run which sets the `eth_syncing` to non-`false` value.

We'll think what to do with it, because CL also uses the `eth_syncing` endpoint to determine whether to send us new updates or not, and when the pruner is running, we can't process any.

**Comment by kaliubuntu0206** [comment]
Due to how `eth_syncing` works, I think the best would be calling `eth_getBlock` for two different nodes to check sync

**Comment by yorickdowne** [comment]
Hmm interesting. How long should a pruning run take? I think my haproxy needs to see 3 failures and checks every 10s, so returning “busy” for 30s seems a bit worrisome even for staking / validation purposes

**Comment by shekhirin** [comment]
@yorickdowne we found a bug that made the `eth_syncing` return `true` not just for the time pruning is running (which is <1s), but for ~12s until the next FCU/payload arrives. https://github.com/paradigmxyz/reth/pull/4847 should fix that, we're testing it right now.

**Comment by shekhirin** [comment]
@yorickdowne can you update your node to latest main and check again?

**Comment by yorickdowne** [comment]
Yep definitely can

**Comment by yorickdowne** [comment]
@shekhirin #4854 may have gotten in the way. My Reth did not catch back up. So I'll focus on that for a bit, then back to this :sweat_smile:

**Comment by yorickdowne** [comment]
This appears to be resolved. We haven't seen the issue in the last 2 weeks. Thanks!
