### ISSUE TITLE
Increase default RPC limit

### ISSUE THREAD

**Issue by yorickdowne** [paradigmxyz/reth#4830]
### Describe the feature

With the default RPC limit of 100 connections, connections are denied on a moderately-busy private Goerli RPC server. Raising it to 1000 resolves this.

I am not sure what the right default is. 100 seems too low.

It could of course also be that connections "hang around" for too long.

**Comment by DoTheBestToGetTheBest** [comment]
> ### Describe the feature
> With the default RPC limit of 100 connections, connections are denied on a moderately-busy private Goerli RPC server. Raising it to 1000 resolves this.
> 
> I am not sure what the right default is. 100 seems too low.
> 
> It could of course also be that connections "hang around" for too long.
> 
> ### Additional context
> _No response_

Hello, seem like you can do that with command line 


Ref : https://github.com/paradigmxyz/reth/blob/8e9937bb08d4379aa837aad648723b581ece6421/book/cli/node.md?plain=1#L196

**Comment by mattsse** [comment]
I think we can reasonable bump the defaults to 250 concurrent requests by default?

@DoTheBestToGetTheBest do you want to take this?

**Comment by kaliubuntu0206** [comment]
Seems like 500 or 1000 is reasonable, agree to the issue

**Comment by DoTheBestToGetTheBest** [comment]
> n reasonable bump the defaults to 500 concurrent requests by d

i take this
