### ISSUE TITLE
Make hard fork  config chain agnostic

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#485]
### Describe the feature

currently, all settings are using mainnet defaults.

All usage of

* `Hardfork`
* `Forkid`

should take the configured chain into account.

This should be exposed on config so any values can be configured manually.

**Comment by leruaa** [comment]
I can take this on

**Comment by mattsse** [comment]
great, 

This first requires a general assessment of chain-specific settings (`NetworkConfig`), which include:
* genesis hash
* Statusmessage
* ...?

Then we need to figure out ergonomics for setting them without messing things up

**Comment by leruaa** [comment]
I'll start by having a look at:
https://github.com/paradigmxyz/reth/blob/f5ae970e63f718b5c57b213e1b74aae7fb26b477/crates/net/network/src/config.rs#L327-L332

In addition to the genesis hash, we are going to need the hardforks list with the corresponding block numbers.

I'm thinking to add a `ChainSpec` trait like this:

```rust
pub trait ChainSpec {
    fn chain_id() -> Chain;
    fn genesis_hash() -> H256;
    fn all_forks() -> Vec<Hardfork>;
    ...
}
```
with `MainnetChainSpec`, `GoerliChainSpec`, `SepoliaChainSpec`... impls. The `Hardfork` enum should be changed to a struct with the corresponding block number. [`ChainSpecification`](https://github.com/paradigmxyz/reth/blob/6407b5087eff0afae792fc6761c989417b77dbfe/bin/reth/src/util/chainspec.rs#L9) could also be refactored into the new trait.

What do you think?

**Comment by onbjerg** [comment]
@leruaa  Note here that there are multiple hardfork configs we should consolidate (ref https://github.com/paradigmxyz/reth/issues/579#issuecomment-1363622980)

- One in network (you got it)
- One in the executor https://github.com/paradigmxyz/reth/blob/8c413ad0a9338f6e8288124ff9538fc07d0fdb54/crates/executor/src/config.rs#L31
- One in the consensus crate https://github.com/paradigmxyz/reth/blob/8c413ad0a9338f6e8288124ff9538fc07d0fdb54/crates/consensus/src/config.rs#L19

Also, it is important that there is some source of truth that we can deserialize from disk (to allow for custom networks) :smile:
