### ISSUE TITLE
eth_createAccessList Improvements 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4860]
### Describe the feature

eth_createAccessList is currently susceptible to a race condition if no specific blocknumber is provided: 

https://github.com/paradigmxyz/reth/blob/a046288af93ab88d607e963670ac20c4f86c3bde/crates/rpc/rpc/src/eth/api/server.rs#L261-L264

after the `create_access_list_at` we're still estimating the gas used, at which point the targeted block might be different (for example block mined in between).

Additionally, the subsequent `estimate_gas_at` can reuse the cached reads of the `create_access_list_at`.

This will require some API changes, I think this can best be solved by adding a new function for `create_access_list_at` that takes a `callback(Env, DB)`, similar to the tracing functions:

https://github.com/paradigmxyz/reth/blob/a046288af93ab88d607e963670ac20c4f86c3bde/crates/rpc/rpc/src/eth/api/transactions.rs

**Comment by yash-atreya** [comment]
I can take this

**Comment by yash-atreya** [comment]
From what I have understood I just need to call `estimate_gas_at` inside the callback?

**Comment by mattsse** [comment]
exactly, we can also reuse the db's cache

**Comment by supernovahs** [comment]
Is the assignee still working on this? Thx

**Comment by mattsse** [comment]
I think this is up for grabs

**Comment by yash-atreya** [comment]
Hey extremely sorry for the delay.
The PR will be up by tonight.

**Comment by mattsse** [comment]
oh cool, then this still being worked on @supernovahs 

no rush though @yash-atreya

**Comment by supernovahs** [comment]
Cool . Thanks

**Comment by yash-atreya** [comment]
PR is up #4954

**Comment by yash-atreya** [comment]
@mattsse Thank you for merging. Would like to contribute more. I'll be on the lookout for more issues to solve.
