### ISSUE TITLE
Unify --port and --discovery.port

### ISSUE THREAD

**Issue by kaliubuntu0206** [paradigmxyz/reth#4864]
### Describe the feature

I wonder if they worth to be a separate option?

**Comment by mattsse** [comment]
there are already two different settings, no?

**Comment by kaliubuntu0206** [comment]
@mattsse Yes, but I wonder if they should be a different settings

**Comment by mattsse** [comment]
can you please elaborate on what you mean by "a different settings" exactly?

**Comment by kaliubuntu0206** [comment]
@mattsse I mean, we have two different options for one functionality ( listening port ). Wouldn't it be great to unify those?

**Comment by mattsse** [comment]
so you're wondering if they could only be 1 setting and always use the same port?

**Comment by kaliubuntu0206** [comment]
@mattsse Exactly.

**Comment by mattsse** [comment]
this would remove functionality and would break cross client compatibility.

closing because we want to keep this functionality
