### ISSUE TITLE
Extend custom rpc namespace example with tests 

### ISSUE THREAD

**Issue by ckoopmann** [paradigmxyz/reth#4868]
### Describe the change

The [additional-namespace-in-cli example](https://github.com/paradigmxyz/reth/tree/main/examples/additional-rpc-namespace-in-cli) is informative and concise. However after following this example to build my own rpc extension I am at a bit of a loss about how to implement rust based integration tests for the rpc endpoint. 
The closest analog I could find are the [integration tests of the rpc-builder](https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-builder/tests/it/http.rs) , however they are quite complex and would require reimplementing a lot of helper functions. So I keep thinking there should be an easier way to shoot some test requests against my rpc endpoint from a rust test. 

Having an example test for the example rpc extension would help a lot.

### Additional context

(I do understand how to manually test my rpc endpoint by just running the executable and sending requests using `cast` or `curl`, this issue relates to how to do this from rust tests).

**Comment by mattsse** [comment]
good point, will add
