### ISSUE TITLE
Add Discv4Command variant to terminate the service

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4874]
### Describe the feature

currently, once discv4 service is spawned, it runs forever

it could be useful to have a command to terminate the service

https://github.com/paradigmxyz/reth/blob/858ea41da1f8852e93e0604dbb2f7a89a5398b28/crates/net/discv4/src/lib.rs#L1698-L1698

## TODO
* Add command variant for `Terminate`
* Add event variant for `Terminated`

**Comment by DoTheBestToGetTheBest** [comment]
Can i try for this ?

**Comment by mattsse** [comment]
assigned,
if you need pointers please open a draft and we go from there
