### ISSUE TITLE
Transition to U256 transaction value type 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4891]
### Describe the feature

ref https://github.com/paradigmxyz/reth/pull/4439

while ethereum is fine with u128 transaction values, other networks like optimism are not.

In order not to break the DB format, the temp `value-256` features was introduced.

This should be removed when we're breaking the DB format.

**Comment by supernovahs** [comment]
Can I  try this?

**Comment by mattsse** [comment]
this is currently blocked, until we make a decision to break the format until then there's nothing to do really
