### ISSUE TITLE
Full pending transaction listeners are not updated with all transactions moved to pending pool

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4902]
### Describe the feature

the full tx object subscription only subscribes to new transactions added to pending pool on insert

https://github.com/paradigmxyz/reth/blob/afebb2b20b584a8664feb4042309679d47b1131e/crates/rpc/rpc/src/eth/pubsub.rs#L279-L279

https://github.com/paradigmxyz/reth/blob/afebb2b20b584a8664feb4042309679d47b1131e/crates/transaction-pool/src/pool/mod.rs#L240-L249

https://github.com/paradigmxyz/reth/blob/afebb2b20b584a8664feb4042309679d47b1131e/crates/transaction-pool/src/pool/mod.rs#L446-L447

TODO
* also notify on promoted txs on state updates here:
* 
https://github.com/paradigmxyz/reth/blob/afebb2b20b584a8664feb4042309679d47b1131e/crates/transaction-pool/src/pool/mod.rs#L595-L595

**Comment by SleepingShell** [comment]
Please assign this to me.

**Comment by SleepingShell** [comment]
@mattsse Isn't this already implemented here?
https://github.com/paradigmxyz/reth/blob/f18845d2518df8666c2f044547f50c1895b7d5c0/crates/transaction-pool/src/pool/mod.rs#L566-L572

**Comment by AtomicAzzaz** [comment]
> @mattsse Isn't this already implemented here?
> 
> https://github.com/paradigmxyz/reth/blob/f18845d2518df8666c2f044547f50c1895b7d5c0/crates/transaction-pool/src/pool/mod.rs#L566-L572

https://github.com/paradigmxyz/reth/blob/f18845d2518df8666c2f044547f50c1895b7d5c0/crates/transaction-pool/src/traits.rs#L148-L155

The pending pool streams uses transactions_listener not pending_transaction_listener (because it outputs H256 only I believe). That's the bug. 
Remark: If you notify transactions_listener on promotion, someone subscribed to all_transaction would get many doubles so idk if that's what you'd want

**Comment by SleepingShell** [comment]
I created a commitment, but I am honestly not super confident on it achieving what you are looking for, I would like some clarification if it does not.

There seems to be multiple points in the transaction-pool where listeners can be notified of transactions, so I am not entirely sure that this is optimal achievement.

Should there be some field in `TransactionListener` to indicate if it wants all new transactions, or only those that are pending? Or does it make more sense that `pending_transaction_listener` is refactored to include both full pending tx listeners, along with hash-only pending tx listeners? The latter seems to make more sense to me.

**Comment by mattsse** [comment]
>  Or does it make more sense that pending_transaction_listener is refactored into a PendingTransactionListener with a field that indicates hash-only or not? The latter seems to make more sense to me.

actually I think this is a good point, this would simplify a few things

**Comment by supernovahs** [comment]
Anything left on this?

**Comment by mattsse** [comment]
I think this can be closed
