### ISSUE TITLE
The implementation of  Transaction::Eip2930

### ISSUE THREAD

**Issue by DoTheBestToGetTheBest** [paradigmxyz/reth#4908]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/066998dc801fbe0828bf145ef0f02479f4889884/crates/transaction-pool/src/test_utils/mock.rs#L568C13-L568C33

I would take this if you don't have mind.

**Comment by mattsse** [comment]
cool, ty!

**Comment by DoTheBestToGetTheBest** [comment]
> cool, ty!

Thank you so much Matt !
