### ISSUE TITLE
Add new event hook for when the rpc servers are started on 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4917]
### Describe the feature

Add new function `on_rpc_server_started` similar to:

https://github.com/paradigmxyz/reth/blob/4dceabf06b9ef26422264ad2026f6e23fda38fbb/bin/reth/src/cli/ext.rs#L50-L71

that also takes the handles as input:

https://github.com/paradigmxyz/reth/blob/4dceabf06b9ef26422264ad2026f6e23fda38fbb/bin/reth/src/args/rpc_server_args.rs#L185-L185

called after:

https://github.com/paradigmxyz/reth/blob/4dceabf06b9ef26422264ad2026f6e23fda38fbb/bin/reth/src/args/rpc_server_args.rs#L228-L228

default impl is a noop

### Additional context

Blocked by #4918 but can be done in tandem

_No response_

**Comment by allnil** [comment]
Hi!
Maybe I can take it?
Thank you

**Comment by mattsse** [comment]
awesome, I recommend tackling #4918 first or together
