### ISSUE TITLE
Simplify extend_rpc_modules arguments

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4918]
### Describe the feature

this is currently very verbose:

https://github.com/paradigmxyz/reth/blob/4dceabf06b9ef26422264ad2026f6e23fda38fbb/bin/reth/src/cli/ext.rs#L59-L66

these two arguments should be combined into a new helper container type generic over `Reth: RethNodeComponents`

like `RethRpcComponents<'a Reth> {
  pub registry: &mut ...
}`

**Comment by supernovahs** [comment]
I can take this
