### ISSUE TITLE
Track highest pruned block per segment in metrics

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#4921]
### Describe the feature

Currently, we only report duration of pruning per segment, but it'd also be useful to have a chart of the highest pruned block per segment, same as we same in prune checkpoints.

**Comment by Paulius0112** [comment]
@shekhirin I would like to take this issue

**Comment by shekhirin** [comment]
@Paulius0112 sounds good, assigned! Let me know if you have any questions.

**Comment by Paulius0112** [comment]
Hi @shekhirin. Just double checking, after each latest segment, we just want to report the highest block in it? Or the requirements are a bit different?

**Comment by shekhirin** [comment]
@Paulius0112 yes, after the pruner run we want to not just record the duration https://github.com/paradigmxyz/reth/blob/1f12203723c98f4f31f679dcc7cfefa3a6f9779d/crates/prune/src/pruner.rs#L138-L141 but also update the highest pruned block for this segment according to the returned `PruneOutputCheckpoint`

**Comment by shekhirin** [comment]
hey @Paulius0112, are you still working on this?

**Comment by Paulius0112** [comment]
@shekhirin yes sorry for the delay. Spinning up a node for testing changes

**Comment by Paulius0112** [comment]
@shekhirin PR opened https://github.com/paradigmxyz/reth/pull/6658

**Comment by Paulius0112** [comment]
I believe this issue can now be closed. PR is merged into master
