### ISSUE TITLE
New issue defined

### ISSUE THREAD

**Issue by shivamoop** [paradigmxyz/reth#4941]
### Describe the bug

issue coming in the code while executing  do can you check again in code 

### Steps to reproduce

start 
then
check error 
exit

### Node logs

```text
1
2
3
4
```

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

version

### What database version are you on?

mysql 8.0.1.0

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
sorry, I don't know what any of this means, or why you referenced a MySQL database

could you please elaborate?
