### ISSUE TITLE
Network agnostic docker volume mount path

### ISSUE THREAD

**Issue by jgresham** [paradigmxyz/reth#4945]
### Describe the feature

When running reth with docker, the volume mount path includes the network name. Instead, I propose that reth should support a network agnostic path to reduce configuration changes for node runners.

example change: 
before (current): `-v rethdata:/root/.local/share/reth/mainnet/db`
after: `-v rethdata:/root/.local/share/reth` or `-v rethdata:/root/.local/share/reth/db`
 
Then if a user wants to run a sepolia node, they just can introduce the `--sepolia` flag without having to change the volume mount path.

Reth docker docs: https://paradigmxyz.github.io/reth/installation/docker.html#using-the-docker-image

### Additional context

Most other nodes work like. For example, geth's volume mount path is `/root/.ethereum`

Additionally, I am working on NiceNode and this simplifies things on my end.

**Comment by mattsse** [comment]
> Then if a user wants to run a sepolia node, they just can introduce the --sepolia flag without having to change the volume mount path.

this makes sense to me
defer to @rkrasiuk @shekhirin

**Comment by jgresham** [comment]
Is this a relatively easy change? If so, I could look into doing it
