### ISSUE TITLE
Add builder functions for GethDefaultTracingOptions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4953]
### Describe the feature

Add more ergonomic builder style functions for GethDefaultTracingOptions to configure all fields

https://github.com/paradigmxyz/reth/blob/98bc2b5c841bb835523f32c0c3425bbbd3859093/crates/rpc/rpc-types/src/eth/trace/geth/mod.rs#L274-L274

similar to https://github.com/paradigmxyz/reth/pull/4952

@DoTheBestToGetTheBest do you want this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by DoTheBestToGetTheBest** [comment]
i take this, please assign me directly next time. I take all issue that you judge are good for me :) 

Thank you so much !
