### ISSUE TITLE
Move Log::from_primitive to rpc-compat crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4967]
### Describe the feature

this should be moved to a standalone conversion function in the rpc-compat crate instead

https://github.com/paradigmxyz/reth/blob/1cccd097ebe460ec989719a9fde0834a15313cdd/crates/rpc/rpc-types/src/eth/log.rs#L30-L43

similar to this that converts a Signature:

https://github.com/paradigmxyz/reth/blob/1cccd097ebe460ec989719a9fde0834a15313cdd/crates/rpc/rpc-types-compat/src/transaction/signature.rs#L21-L31

## TODO:
* remove from impl from rpc-types
* add a `from_primitive_log` function in `rpc-types-compat/src/log.rs` (new file)
* update usage of `From` with the function

@DoTheBestToGetTheBest do you want to take this?

**Comment by yash-atreya** [comment]
I'd like to take this

**Comment by DoTheBestToGetTheBest** [comment]
> ### Describe the feature
> this should be moved to a standalone conversion function in the rpc-compat crate instead
> 
> https://github.com/paradigmxyz/reth/blob/1cccd097ebe460ec989719a9fde0834a15313cdd/crates/rpc/rpc-types/src/eth/log.rs#L30-L43
> 
> similar to this that converts a Signature:
> 
> https://github.com/paradigmxyz/reth/blob/1cccd097ebe460ec989719a9fde0834a15313cdd/crates/rpc/rpc-types-compat/src/transaction/signature.rs#L21-L31
> 
> ## TODO:
> * remove from impl from rpc-types
> * add a `from_primitive_log` function in `rpc-types-compat/src/log.rs` (new file)
> * update usage of `From` with the function
> 
> @DoTheBestToGetTheBest do you want to take this?
> 
> ### Additional context
> _No response_

Please @mattsse next time directly assign me without asking me please. Thank you !
