### ISSUE TITLE
Add support for pending transactions on eth_getFilterChanges endpoint

### ISSUE THREAD

**Issue by d347h-eth** [paradigmxyz/reth#4973]
### Describe the feature

Currently the API throws an error when `FilterKind::PendingTransaction` is utilized:
https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/filter.rs#L98

Example requests to trigger the error:
```bash
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_newPendingTransactionFilter","params":[],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","result":"0xd9e8d5df0c8f900c3a6cfb4312e8f511","id":1}
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xd9e8d5df0c8f900c3a6cfb4312e8f511"],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","error":{"code":-32603,"message":"pending transaction filter not supported"},"id":1}
```

This is currently utilized in some nice app that monitors pending txs and enables arbitrary tx execution when particular tx are detected in the pending pool :smile::+1: But currently it's not possible to use this feature against `reth` node.

**Comment by mattsse** [comment]
the `eth_getFilterChanges` returns a list of new transaction hashes.

what we need to do is:

* add a value to the filterkind variant for PendingTransaction https://github.com/paradigmxyz/reth/blob/00a92f526aa6bb7695c249fc634dabf9f3d4928e/crates/rpc/rpc/src/eth/filter.rs#L426-L426
this value should be the return value (Receiver) of https://github.com/paradigmxyz/reth/blob/00a92f526aa6bb7695c249fc634dabf9f3d4928e/crates/transaction-pool/src/traits.rs#L120-L120

so when a new pending tx filter is installed, we create a new receiver via the pool:
https://github.com/paradigmxyz/reth/blob/00a92f526aa6bb7695c249fc634dabf9f3d4928e/crates/rpc/rpc/src/eth/filter.rs#L242-L242

and here we drain the receiver on eth_getFilter changes via `while Ok try_recv`

https://github.com/paradigmxyz/reth/blob/00a92f526aa6bb7695c249fc634dabf9f3d4928e/crates/rpc/rpc/src/eth/filter.rs#L97-L99

**Comment by allnil** [comment]
Can I take it?

**Comment by mattsse** [comment]
assigned

**Comment by mattsse** [comment]
we have this now
