### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by 0xlagrange** [paradigmxyz/reth#4975]
### Describe the bug

htop/top reporting 50% memory usage
<img width="1051" alt="Screenshot 2023-10-10 at 1 52 33 PM" src="https://github.com/paradigmxyz/reth/assets/107195066/145175d8-c83c-4577-a748-9b1a2261dbb7">

We frequently while testing, send a very large number of requests via rpc/ipc/direct db reads. However this issue persists after the fact.

We are running the node on a c6id.12xlarge with 48 cores on a Ice Lake 8375C processor, 96GB RAM, 2x1425GB SSD configured with RAID0.

### Steps to reproduce

1. Build with: RUSTFLAGS="-C target-cpu=native" cargo build --manifest-path /home/reth/Cargo.toml --profile maxperf --features jemalloc &&  chmod +x /home/reth/target/maxperf/reth && mv /home/reth/target/maxperf/reth ~/.cargo/bin

2. Run with: RUST_LOG=info nohup reth node --authrpc.jwtsecret /home/.secrets/jwt.hex --http --http.addr 0.0.0.0 --http.port 8489 --http.api "eth,debug,txpool,web3,trace" --datadir /home/data/reth/ --metrics 127.0.0.1:9111 -vvvvv > /home/logs/reth.log 2>&1 &

3. After 3 days, memory was at 40% utilization, after about 4 it is at 50%.

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.10 Commit SHA: 6f4febc8 Build Timestamp: 2023-10-03T12:31:36.615594171Z Build Features: default,jemalloc Build Profile: maxperf

### What database version are you on?

Current database version: 1
Local database is uninitialized

### If you've built Reth from source, provide the full command you used

RUSTFLAGS="-C target-cpu=native" cargo build --manifest-path /home/reth/Cargo.toml --profile maxperf --features jemalloc &&  chmod +x /home/reth/target/maxperf/reth && mv /home/reth/target/maxperf/reth ~/.cargo/bin

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by chen4903** [comment]
The same problem: it costs 51.8%
```
 PID                USER      PR    NI       VIRT        RES           SHR S      %CPU   %MEM     TIME+         COMMAND  
1944934     ????          20      0.     5222.0g    130.3g      9.5g S.      230.0     51.8       14596:21        reth
```

**Comment by jnoorchashm37** [comment]
> The same problem: it costs 51.8%
> 
> ```
>  PID                USER      PR    NI       VIRT        RES           SHR S      %CPU   %MEM     TIME+         COMMAND  
> 1944934     ????          20      0.     5222.0g    130.3g      9.5g S.      230.0     51.8       14596:21        reth
> ```
> 
> My total memory: 257563 @jnoorchashm37 Have you solve this issue?

If I remember correctly, htop/top was just showing the allocated memory.
