### ISSUE TITLE
Add an example for transportless transaction simulation via cli extension

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4980]
### Describe the feature

similar to https://github.com/paradigmxyz/reth/blob/e04292247fff14ea93b4b0f6cf427bc9e4365c75/examples/cli-extension-event-hooks/src/main.rs#L1-L1
and 
https://github.com/paradigmxyz/reth/blob/e04292247fff14ea93b4b0f6cf427bc9e4365c75/examples/additional-rpc-namespace-in-cli/src/main.rs#L1-L1

this example should spawn a service that traces new pending transactions, it should take some arguments (for example a list of sender and target accounts used to filter transactions)

## TODO
* add a new example, use the new hook on_rpc_server_started to get access to the `EthApi` struct via the `rpc_components.registry`
https://github.com/paradigmxyz/reth/blob/e04292247fff14ea93b4b0f6cf427bc9e4365c75/bin/reth/src/cli/ext.rs#L51-L62
* spawn a service task that creates a pool subscription and calls `trace_call` for example if the new tx matches the input values

**Comment by supernovahs** [comment]
I can take this

**Comment by supernovahs** [comment]
Can be closed
