### ISSUE TITLE
move reth-tracing to workspace dependency

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4983]
## TODO
* add reth-tracing to workspace dep: https://github.com/paradigmxyz/reth/blob/00a92f526aa6bb7695c249fc634dabf9f3d4928e/Cargo.toml#L87-L87
* replace all `reth-tracing = { path = "../../tracing" }` with `reth-tracing.workspace = true`

**Comment by supernovahs** [comment]
I can take this
