### ISSUE TITLE
Tack active inflight tx requests by hash and peer in TransactionManager

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#4998]
### Describe the feature

this is part of #4550

we need to minimize scheduling new requests by tracking active requests by hash and peers that announced a missing hash.

I think the best abstraction for this is a new `TransactionFetcher` type that encapsulates:

https://github.com/paradigmxyz/reth/blob/main/crates/net/network/src/transactions.rs#L152-L153

this type needs to track:
* active requests, especially inflight hashes, so that whenever we receive new missing hashes we can check first if they're already being requested.
* keep track of missing hashes and peers that send us these, so we can possibly re-request them

**Comment by DoTheBestToGetTheBest** [comment]
i take this

**Comment by DoTheBestToGetTheBest** [comment]
> this is slightly more advanced and a bit time sensitive, I'd like to put you on something more manageable if that's ok?

of course :) thank you a lot !

**Comment by smatthewenglish** [comment]
@mattsse i'd be happy to take a crack at it

**Comment by mattsse** [comment]
closing as dup of #4550
