### ISSUE TITLE
Add `EthTransactionValidator::validate_all` function

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5001]
### Describe the feature

Add a new function that works just as:

https://github.com/paradigmxyz/reth/blob/27a0a06ca44e9ee25f05abfbad8276c518a33eff/crates/transaction-pool/src/validate/eth.rs#L41-L50

but takes a vec of (origin, tx) pairs. For now this can just call validate_one individually, which could afterward be optimized so that state access is minimized (self.client.lastest)

**Comment by DoTheBestToGetTheBest** [comment]
i can take this
