### ISSUE TITLE
Add EIP4844 variant to TypedTransactionRequest

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5004]
### Describe the feature

blob tx type missing here

https://github.com/paradigmxyz/reth/blob/27a0a06ca44e9ee25f05abfbad8276c518a33eff/crates/rpc/rpc-types/src/eth/transaction/typed.rs#L22-L22

## TODO
* add new type for EIP4844, similar to must include the additional fields versioned hashes, blobs etc, https://github.com/paradigmxyz/reth/blob/27a0a06ca44e9ee25f05abfbad8276c518a33eff/crates/rpc/rpc-types/src/eth/transaction/typed.rs#L95-L95
see also https://github.com/paradigmxyz/reth/blob/27a0a06ca44e9ee25f05abfbad8276c518a33eff/crates/primitives/src/transaction/eip4844.rs#L585-L592

**Comment by DoTheBestToGetTheBest** [comment]
i take this
