### ISSUE TITLE
debug_trace_call 

### ISSUE THREAD

**Issue by koinov** [paradigmxyz/reth#5011]
### Describe the feature

There's a significant difference between RETH and GETH in debug_trace_call

state_diff : Some(false)
RETH returns changed state, code is not included
GETH returns state and code of all accounts touched before call is made. 

state_diff : Some(true)
RETH returns code and state in POST state even if code wasn't changed
GETH returns only changed code and state 

I'm attaching some results of debug_trace_call calls for GETH and RETH

### Additional context

[reth.issue.txt](https://github.com/paradigmxyz/reth/files/12892544/reth.issue.txt)

**Comment by koinov** [comment]
Here are capture of requests and RETH replies

[reth2.issue.txt](https://github.com/paradigmxyz/reth/files/12905377/reth2.issue.txt)

**Comment by mattsse** [comment]
awesome, ty!
will get these fixed

**Comment by koinov** [comment]
Just checked last updates, it seems to be working fine, I also compared fetched data with alchemy and geth and fetched cells set for 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 equal.. So far looking good, thank you!

**Comment by mattsse** [comment]
great thanks for reporting!

I'm closing this one, if you encounter any additional issue, please open another issue 🙏
