### ISSUE TITLE
Extend CanonStateSubscriptions trait with a function that streams all blocks

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5013]
### Describe the feature

Currently the `canonical_state_stream` function returns a stream of

https://github.com/paradigmxyz/reth/blob/6c8c084e361c46816835cb3bf5483a2b63072346/crates/storage/provider/src/chain.rs#L18-L18

however, this is only fired during live sync. Ideally we want a stream that streams all blocks, so we never miss a block in case syncing falls back to pipeline sync.

This can be fixed by a new stream type that wraps the `canonical_state_stream` and keeps track of blocks that are missing. (fetch from disk). I think this can use a `Box< dyn BlockReaderIdExt>`.

since there can be a few subscribers active at the same time, we need something that synchronizes disk access so the missing blocks are only fetched once and streamed to all subscribers. something like:

```rust
struct BlockBroadcast {
  cache: Arc<tokio::RwLock<LruMap>>
  provider: Arc<dyn BlockReaderIdExt>
}
```

this is similar to the EthStateCache which could potentially be reused here but this currently resides in rpc.
I think we really want this new function for the CanonStateSubscriptions trait, hence I think duplicating this should be fine as it's not really complex

ref
https://github.com/paradigmxyz/reth/blob/6c8c084e361c46816835cb3bf5483a2b63072346/crates/storage/provider/src/traits/chain.rs#L22-L22

### Additional context

#4999

blocked by #5019

_No response_

**Comment by DoTheBestToGetTheBest** [comment]
are you okay if i take this ?

**Comment by mattsse** [comment]
this is slightly more advanced, we'll find something else once you've completed the other open prs

**Comment by PatStiles** [comment]
@mattsse down to take a crack at this

**Comment by mattsse** [comment]
cool,

we had to revert #5019 but I think we can maybe still do that rn if the necessary provider trait is object safe, or with a workaround via an additional extension trait

**Comment by leontiadZen** [comment]
Can I try that with a small guidance?

**Comment by mattsse** [comment]
@PatStiles are you still working on this?

**Comment by PatStiles** [comment]
I am! One question though, what size should we set the cache size to? Should I write a supporting bench for this?

**Comment by mattsse** [comment]
sorry forgot to respond here,

I think we can start with 50 blocks at once

**Comment by supernovahs** [comment]
Is the assignee working on this?Thanks

**Comment by PatStiles** [comment]
Yes!

**Comment by mattsse** [comment]
@PatStiles are you still working on this?

**Comment by PatStiles** [comment]
Yes will open draft!
