### ISSUE TITLE
Make BlockReaderIdExt trait object safe

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5019]
### Describe the feature

take over #5018 and make it compile by removing all generic parameters:

```
 fn transactions_by_block_range(
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...because method `transactions_by_block_range` has generic type parameters
```

replace `impl RangeBounds<BlockNumber>` with either `Range` or `RangeInclusive`

**Comment by leontiadZen** [comment]
Can I take that? Probably it needs to be done using dynamic dispatching through trait objects

**Comment by leontiadZen** [comment]
Can I take that seems okish?

**Comment by mattsse** [comment]
yeah, most of this was done in #5022 already but we had to revert this because this introduced a bug.

The issue is with these two calls:

https://github.com/paradigmxyz/reth/blob/2b71f0f6b02865a0f720254f4483db9d5b7abd9c/crates/storage/provider/src/traits/transactions.rs#L52-L59

which prevents us from using `Box< dyn BlockReader>` and caused the bug that lead to the revert

https://github.com/paradigmxyz/reth/blob/2b71f0f6b02865a0f720254f4483db9d5b7abd9c/crates/storage/provider/src/traits/block.rs#L61-L61

but we want to keep these functions so we need to find another solution...

any ideas @rkrasiuk ?
