### ISSUE TITLE
Reth post-sync memory usage is getting it killed by OS.

### ISSUE THREAD

**Issue by HrikB** [paradigmxyz/reth#5026]
### Describe the feature

Every 10 min, the reth node is getting killed due to too much memory usage after sync to tip was completed.
![image](https://github.com/paradigmxyz/reth/assets/23041116/8561c2d6-a30f-452c-b565-68d3fb6018a5)

![image](https://github.com/paradigmxyz/reth/assets/23041116/75f01b5e-ffde-40f1-8ef8-2c6b02a4a3d7)
This image shows htop when reth is on the verge of being killed.

![image](https://github.com/paradigmxyz/reth/assets/23041116/4d9adadb-49da-4595-b019-49397e289c6f)
This image shows htop right after reth has been killed.

![image](https://github.com/paradigmxyz/reth/assets/23041116/b2f28a59-f8a5-4b03-a28b-f1a9bfcfbc0c)
This image is from the grafana for the reth node. There is a very clear pattern here of it getting killed over and over again. We have the reth node running in a retry skip because this issue was happening before the sync was complete as well, but it was happening much less often. This is the script:

```
until RUST_LOG=INFO ./reth node --http --authrpc.addr 127.0.0.1 --authrpc.port 8551 --metrics 127.0.0.1:9001; do
       sleep 1
done
```

The node is now falling behind the tip since it is not making progress past MerkleExecute stage at checkpoint=100%.

Hardware wise, we are using [this](https://www.amazon.com/Beelink-SER6-Computer-Desktop-Display/dp/B0C98K3KLT?ref_=ast_sto_dp&th=1&psc=1) computer. 4.5GHz CPU w/ 16GB DDR5 RAM. We also swapped out the ssd for [this](https://www.amazon.com/gp/product/B0B7CQ2CHH/ref=ewc_pr_img_1?smid=ATVPDKIKX0DER&th=1) ssd. A 4TB nvme tlc ssd (no heatsink).

The OS being used is Xubuntu.

**Comment by cgfandia** [comment]
Apparently, this happens during the unwinding stages to previous blocks due to bad blocks of sync.
I had OOM while trying `reth stage unwind to-block`
64GB isn't enough

**Comment by HrikB** [comment]
> Apparently, this happens during the unwinding stages to previous blocks due to bad blocks of sync.
> 
> I had OOM while trying `reth stage unwind to-block`
> 
> 64GB isn't enough 

64gb of what? RAM?

**Comment by cgfandia** [comment]
Yep
