### ISSUE TITLE
Add functions to instantiate various Api types in RethModuleRegistry

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5029]
### Describe the feature

similar to:

https://github.com/paradigmxyz/reth/blob/ffcda0ddbc4a539f26fa6ce394af7a55139f7f1f/crates/rpc/rpc-builder/src/lib.rs#L1077-L1081

## TODO
* add functions that return new, TraceApi, DebugApi etc...
* update `register_*` functions so that they'll use these new functions
https://github.com/paradigmxyz/reth/blob/ffcda0ddbc4a539f26fa6ce394af7a55139f7f1f/crates/rpc/rpc-builder/src/lib.rs#L794-L806

@supernovahs

**Comment by supernovahs** [comment]
👍
