### ISSUE TITLE
feat(net): rethink spam logging

### ISSUE THREAD

**Issue by Will-Smith11** [paradigmxyz/reth#503]
### Describe the feature

currently after awhile of runnning I get spammed with this
![image](https://user-images.githubusercontent.com/44074786/208261279-733e6b74-d1a3-4d4b-b910-5d121dc38e24.png)
im running from reconnaissance, the different is thought is because reconnaissance acts as a fully synced node, we aren’t sending out block and header requests to the peers, so the timeout penalty takes a lot longer to drop out on bad nodes, which could be why we are seeing the spamming causing the packet drop on reconnaissance but not on sync? just an idea I would like to through around

**Comment by onbjerg** [comment]
The battle plan is to keep a lot of these logs but gradually adjust the log levels (e.g. that one could be `trace`), but pipe the verbose version to a log file (or systemd) and keep a more "clean" version for the CLI output that is more tailored for the use case of "how is my node doing"

**Comment by jonasbostoen** [comment]
Since the buffer sizes were increased (https://github.com/paradigmxyz/reth/pull/508), these logs don't show up anymore for me

**Comment by gakonst** [comment]
Optimistically closing this given the reactions above, and we indeed want to rethink logging holistically, part of what @onbjerg and I will be owning in the coming weeks.
