### ISSUE TITLE
Clear stale filter subscriptions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5038]
### Describe the feature

Currently the `EthFilterInner` does not handle timeouts

https://github.com/paradigmxyz/reth/blob/9ffc1433d998ba63d055c632a97bc1960c84ad78/crates/rpc/rpc/src/eth/filter.rs#L237-L239

which means filters are not cleared.

we need to fix this by spawning a new task on `new` with the task manager that clears filters that haven't been polled for a specific timeout: Duration value (default 5min).

this can be done by checking the diff of the last poll timestamp against `Instant::now`
https://github.com/paradigmxyz/reth/blob/9ffc1433d998ba63d055c632a97bc1960c84ad78/crates/rpc/rpc/src/eth/filter.rs#L416-L417

## TODO
* spawn a new task that is a loop over a tokio::Interval that clears stale filters
* Add config value and default to:
https://github.com/paradigmxyz/reth/blob/9ffc1433d998ba63d055c632a97bc1960c84ad78/crates/rpc/rpc-builder/src/eth.rs#L27-L29

**Comment by allnil** [comment]
Hi!
Maybe I can take this?

**Comment by allnil** [comment]
@mattsse thank you!
