### ISSUE TITLE
Add TraceRequest helper type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5051]
### Describe the feature

this function is intended to be used programmatically: 

https://github.com/paradigmxyz/reth/blob/d3ea66bb7923951686833177deb2a14323bf6e8a/crates/rpc/rpc/src/trace.rs#L67-L75

but it's a bit ugly, due to all the optional fields.

This can be improved via a new TraceRequest type in rpc-types that wraps a CallRequest and has builder style functions to set the optional fields.

**Comment by supernovahs** [comment]
I can take this.
