### ISSUE TITLE
Cache block values of recent blocks

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5052]
### Describe the feature

when we compute the suggested tip cap, we're searching for the lowest effective tip values of recent blocks. This set is fixed and can be cached

## TODO
* add LRU cache of `Hash -> (Hash, Vec<U256>)` that caches the outcome of: https://github.com/paradigmxyz/reth/blob/b399e5d55232b5bd3a88fc8da9f3681d62519919/crates/rpc/rpc/src/eth/gas_oracle.rs#L201-L202

The cache only needs `max_block` entries if there's activity but there can be more if there aren't any transactions, perhaps a reasonable amount would be 100 entries, 

https://github.com/paradigmxyz/reth/blob/b399e5d55232b5bd3a88fc8da9f3681d62519919/crates/rpc/rpc/src/eth/gas_oracle.rs#L26-L27

the cache needs to be moved into the mutex:

https://github.com/paradigmxyz/reth/blob/b399e5d55232b5bd3a88fc8da9f3681d62519919/crates/rpc/rpc/src/eth/gas_oracle.rs#L93-L94

**Comment by PatStiles** [comment]
Down to take this on

**Comment by mattsse** [comment]
sweet, assigned
