### ISSUE TITLE
Count the appearances of opcode and opcode sets

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#5067]
## Why

To get a good amount of insight into what is most found inside bytecode, we should count it.

## What

We should measure a few things, the count of opcode appearances and the count of opcode pair/triples/quadruples appearances.

# How

There is a single table that contains all contracts. https://github.com/paradigmxyz/reth/blob/a25161fb9f466fd0055fbc196ddef1b148559458/crates/storage/db/src/tables/mod.rs#L300-L306
We should iterate over it and save any appearance of opcode (or set) to hashmap, and for the single opcode print all of them for opcode sets print the first 200 that have at least N amount of appearance.

Note: be mindful of push opcodes, which can contain arbitrary values after opcode. Check how the code is analysed here: https://github.com/bluealloy/revm/blob/main/crates/interpreter/src/interpreter/analysis.rs#L33

**Comment by lorenzofero** [comment]
Hey @rakita, if you want I can take a look at this. It'd be my first issue on Reth therefore I could be a bit slow and need some help, I hope it's not a problem

**Comment by 0xprames** [comment]
i'd like to take a look at this, but I also want to wrap up whatever I've been helping w/ over at #4778

If this is still open later this week (probably not though due to github MEV heh) - I will start to take a look

**Comment by rakita** [comment]
> Hey @rakita, if you want I can take a look at this. It'd be my first issue on Reth therefore I could be a bit slow and need some help, I hope it's not a problem

Make it as some CLI, Here is a good example of how to open db: https://github.com/paradigmxyz/reth/blob/main/examples/rpc-db/src/main.rs should be easier after that.

For testing, sync sepolia on your local machine ( with `--debug.tip #block_hash` flag to lower block if you don't have 200gb), and we can run it on our mainnet nodes.

**Comment by lorenzofero** [comment]
Thanks for the tips! I'll start looking into it soon :hammer_and_wrench:

**Comment by ameya-deshmukh** [comment]
Hey @lorenzofero would you like to collab on this? I'm @ameyad22h on the Reth TG, shoot me a DM!

**Comment by supernovahs** [comment]
I can take this?

**Comment by ameya-deshmukh** [comment]
Too much Github MEV on this lol

**Comment by supernovahs** [comment]
@ameya-deshmukh You can take this. I'll find another issue.

**Comment by lorenzofero** [comment]
> Hey @lorenzofero would you like to collab on this? I'm @ameyad22h on the Reth TG, shoot me a DM!

Hi there! I'm sorry but I'm already collaborating with another user!

**Comment by ameya-deshmukh** [comment]
Haha no worries! As I said, the MEV on good first issues on Reth is crazy. All the best for this issue!

**Comment by malik672** [comment]
@lorenzofero still doing this
