### ISSUE TITLE
thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by lucyzhang314** [paradigmxyz/reth#5085]
### Describe the bug

error: process didn't exit successfully: `target\debug\reth.exe node --datadir d:/reth/ --authrpc.port 8552 --debug.tip 0xc2bbf684fdbd004a07253637cbdd15544d9d86f1dadf645eeddcc24655a9a479` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)

Process finished with exit code -1073741571 (0xC00000FD)

### Steps to reproduce

![1697687444778](https://github.com/paradigmxyz/reth/assets/40690755/fd917042-f0ce-4af0-91a0-259ff74fbebd)

### Node logs

```text
N/A
```

### Platform(s)

Windows (x86)

### What version/commit are you on?

reth 0.1.0-alpha.10 (7ca3db8a)

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

N/A

### If you've built Reth from source, provide the full command you used

cargo build --profile maxperf

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
does this happen repeatedly? 

could you run with full logs `RUST_LOG=trace` 

I wonder if this is an issue with kzgsettings

**Comment by lucyzhang314** [comment]
![image](https://github.com/paradigmxyz/reth/assets/40690755/7c099f08-1b1b-4080-ae3d-4b7c45363143)

**Comment by lucyzhang314** [comment]
![image](https://github.com/paradigmxyz/reth/assets/40690755/35e09747-ff3c-4b61-840c-55fada6489d2)

**Comment by mattsse** [comment]
@Rjected @DaniPopes does this ring any bell?
