### ISSUE TITLE
reth node --dev not including transactions

### ISSUE THREAD

**Issue by rodrigoherrerai** [paradigmxyz/reth#5086]
### Describe the bug

When running a private network (--dev) and sending a transaction, the chain fails to include the transactions due to the following error: 

```ERROR consensus::auto: Forkchoice update returned invalid response fcu_response=OnForkChoiceUpdated```

The chain does start and it seems to work properly until you try to execute whatever transaction.

### Steps to reproduce

1. git clone https://github.com/paradigmxyz/reth.git
2. cargo build 
3. cargo run -p reth node --dev --http

NOTE: The same error happens if you install reth in your machine as in building and running in dev mode. 

### What version/commit are you on?

reth Version: 0.1.0-alpha.10

### What database version are you on?

1

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

default

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by rodrigoherrerai** [comment]
After some debugging, the issue seems to be here: 

https://github.com/paradigmxyz/reth/blob/5d217a2867e2c7a8cd96b3b5eada371101c6e1de/crates/revm/src/processor.rs#L529

```
let receipts_root = reth_primitives::proofs::calculate_receipt_root(&receipts_with_bloom);
    if receipts_root != expected_receipts_root {
        return Err(BlockValidationError::ReceiptRootDiff {
            got: receipts_root,
            expected: expected_receipts_root,
        }
        .into())
    }
```

The expected_receipts_root differs from receipts_root. 

Although I logged the 1 transaction I made and it seems to be correct, so not sure what the problem is.

**Comment by rodrigoherrerai** [comment]
After further debugging the problem is these functions:
https://github.com/paradigmxyz/reth/blob/93e837e28a77a890f145f95be6a75ec5a66dfb19/crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs#L244
https://github.com/paradigmxyz/reth/blob/93e837e28a77a890f145f95be6a75ec5a66dfb19/crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs#L209

The events are there but it returns an empty hash, that is the root of the problem.

**Comment by Rjected** [comment]
see this PR:
https://github.com/paradigmxyz/reth/pull/5042/files/

Aiming to get this reviewed and merged soon, so progress will be tracked there

**Comment by rodrigoherrerai** [comment]
Great, closing it and tracking it in the pr
