### ISSUE TITLE
Add an option to return hashed transactions in `block_with_senders`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5092]
### Describe the feature

currently the `block_with_senders` contains a footgun:

https://github.com/paradigmxyz/reth/blob/7796e574769a16154e7d3fcf2d113ab8b051a8c8/crates/storage/provider/src/providers/database/provider.rs#L1031-L1042

this is still useful, if the caller is not interested in the transaction hash, but we should make this more obvious by adding an enum Argument to the function, like 

`enum TranasctionKind {NoHash, WithHash}`

## TODO
* introduce enum
* add enum to function, update usage and trait function

### Additional context

this is prep for #5090

**Comment by supernovahs** [comment]
Can I take this
