### ISSUE TITLE
feat(stage): consolidate `Validation` and `ExecutionError` variants in `StageError` enum

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#5099]
### Describe the feature

The `StageError` enum contains two variants, `Validation` and `ExecutionError`, which share almost identical structures and are used to represent two distinct types of errors:

https://github.com/paradigmxyz/reth/blob/78f666e62e370aef4a6f558c760cf724908c1e39/crates/stages/src/error.rs#L10-L82

These variants can be consolidated into a single variant, which will not only reduce code duplication but also make the codebase more maintainable.

## Proposed Solution

I propose consolidating the `Validation` and `ExecutionError` variants into a single variant, perhaps named `BlockError` or another appropriate name. This change will streamline the code and reduce redundancy with something like:

```rust
/// A stage execution error.
#[derive(Error, Debug)]
pub enum StageError {
    /// The stage encountered an error related to a block.
    #[error("Stage encountered a block error in block {number}: {error}.", number = block.number)]
    BlockError {
        /// The block that caused the error.
        block: SealedHeader,
        /// The specific error type, either consensus or execution error.
        #[source]
        error: BlockErrorType,
    },
...
}
```

This consolidated variant can include fields to distinguish between validation and execution errors and encapsulate the specific error types for each case using an enum like:
```rust
/// Represents the specific error type within a block error.
#[derive(Error, Debug)]
pub enum BlockErrorType {
    /// The block encountered a validation error.
    #[error("Validation error: {0}")]
    Validation(#[source] consensus::ConsensusError),
    /// The block encountered an execution error.
    #[error("Execution error: {0}")]
    Execution(#[source] executor::BlockExecutionError),
}
```

**Comment by mattsse** [comment]
sgtm, let's rename this `BlockErrorKind`
