### ISSUE TITLE
Reth not syncing to head, lagging 32 blocks

### ISSUE THREAD

**Issue by halljson** [paradigmxyz/reth#5114]
### Describe the bug

Reth is failing to sync to head and is lagging by 32-64 blocks at a time.

Requested screencaps:

![Screenshot 2023-10-20 at 2 18 11 PM](https://github.com/paradigmxyz/reth/assets/5545450/18e87b36-a07d-4c4a-b642-f3c9db504958)

![Screenshot 2023-10-20 at 2 29 12 PM](https://github.com/paradigmxyz/reth/assets/5545450/fba838c7-bd0b-4329-bb89-6f33b8c9f121)

![Screenshot 2023-10-20 at 2 27 00 PM](https://github.com/paradigmxyz/reth/assets/5545450/5b68ebd1-ccc9-4886-933a-64225e56d965)

### Steps to reproduce

Running alpha10 for weeks with no hiccups, suddenly the node got out of sync and cannot resync.
Hitting reth heavily with RPC requests.

### Node logs

```text
https://pastebin.com/H2Lj7HzP
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth 0.1.0-alpha.10 fafcabf6

### What database version are you on?

Current database version: 1

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
Hi, can you also include the "Average commit time" graph from the "Database" section?
