### ISSUE TITLE
refactor(primitives): group `effective_gas_tip` and `effective_tip_per_gas` functions together

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#5141]
#### Observation

In the current codebase, we have two separate functions, `effective_gas_tip` and `effective_tip_per_gas`, in the implementation of the `Transaction` enum, that perform similar computations to determine the effective gas tip or gasTipCap for a given transaction and base fee: 
https://github.com/paradigmxyz/reth/blob/d05b32449b43f51977abd7aa22c55d894cf07776/crates/primitives/src/transaction/mod.rs#L308-L352

These two functions car be grouped together using a common logic.

#### Proposed Solution

I propose merging the logic of these two functions into a single function, which we can name `effective_tip_per_gas`. This consolidated function can accept an `Option<u64>` for the base fee, making it versatile enough to handle cases where the base fee is either present or absent.

The consolidated function will centralize the logic for calculating the effective gas tip or gasTipCap, which includes handling scenarios where the base fee is not specified. This refactoring will lead to more maintainable and cleaner code.

**Comment by DoTheBestToGetTheBest** [comment]
@mattsse oh i'm sorry i made  a PR before you assign tcoratger

**Comment by tcoratger** [comment]
> @mattsse oh i'm sorry i made a PR before you assign tcoratger

@DoTheBestToGetTheBest No worries, I hadn't started it and I have others to do so really no problem.

**Comment by DoTheBestToGetTheBest** [comment]
> > @mattsse oh i'm sorry i made a PR before you assign tcoratger
> 
> @DoTheBestToGetTheBest No worries, I hadn't started it and I have others to do so really 

Thank you lot !

**Comment by onbjerg** [comment]
Solved in https://github.com/paradigmxyz/reth/issues/5141
