### ISSUE TITLE
Add TransactionsHandle function to retrieve transactions from certain peers

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5143]
### Describe the feature

Currently we only have commands for propagating transactions

https://github.com/paradigmxyz/reth/blob/2b71f0f6b02865a0f720254f4483db9d5b7abd9c/crates/net/network/src/transactions.rs#L1019-L1021

we could use some functions that request transactions from peers.

this should simply use the sender to the peer

https://github.com/paradigmxyz/reth/blob/2b71f0f6b02865a0f720254f4483db9d5b7abd9c/crates/net/network/src/transactions.rs#L1010-L1011

and send a request which is then awaited by the Handle:
1. manager receives command (peer, hashes)
2. sends the request through the peer's channel
3. sends the response channel back to the handle
4. handle awaits transactions response

@smatthewenglish

**Comment by smatthewenglish** [comment]
this sounds like a fun feature to work on. I'd be happy to pick it up if you think it's a good fit! 🤖
