### ISSUE TITLE
rpc tracing compare testing support

### ISSUE THREAD

**Issue by DoTheBestToGetTheBest** [paradigmxyz/reth#5146]
taking this

**Comment by DoTheBestToGetTheBest** [comment]
@mattsse i need to write test block in trace.rs right ?

**Comment by mattsse** [comment]
> But also which are the two rpc that i need to compare ?

ideally anything.

I think we want a helper type that takes two clients and then some testing support that allows us to compare responses, for example given an input for

https://github.com/paradigmxyz/reth/blob/916b6b3b286e06534fbe1de30ba699b2b40264c5/crates/rpc/rpc-testing-util/src/trace.rs#L107-L114

this will tests that both streams yield the same results etc.

**Comment by DaniPopes** [comment]
Closing #5148
