### ISSUE TITLE
Use built-in `ruint` `is_zero()` function to replace `== U256::ZERO`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#5147]
### Describe the feature

When the next version of `ruint` is released, there are different places in the code where the expression `== U256::ZERO` like in:

https://github.com/paradigmxyz/reth/blob/b71a8ac85dd86d45d7ddaff32df4d0ac23ca8582/crates/primitives/src/account.rs#L35

can be replaced by the dedicated built-in `is_zero()` function, recently developed here:

https://github.com/recmo/uint/blob/666cd312be3810a1301257b1aaa40f03193788c7/src/cmp.rs

**Comment by mattsse** [comment]
oh yes!!!

**Comment by supernovahs** [comment]
I can take this?

**Comment by supernovahs** [comment]
I can take this?

**Comment by mattsse** [comment]
yeah this should be easily fixable via regex replacements
