### ISSUE TITLE
Add missing beacon API eventstream types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5152]
### Describe the feature

Add missing rpc-types for beacon event types

API definitions:

https://github.com/ethereum/beacon-APIs/blob/master/apis/eventstream/index.yaml

helpful tool: https://transform.tools/json-to-rust-serde

## TODO
* add type definitions
* add serde tests using sample data: `curl -X 'GET' 'http://localhost:5052/eth/v1/events?topics=payload_attributes' -H 'accept: text/event-stream'`, lighthouse docs: https://lighthouse-book.sigmaprime.io/api-bn.html#beacon-node-api
* add enum type `BeaconApiEvent{...}` and `BeaconApiEventTopic{...}`

### Additional context

payload attributes beacon api event type added here https://github.com/paradigmxyz/reth/pull/5130

**Comment by i-m-aditya** [comment]
I will pick this.
