### ISSUE TITLE
Add support for eth_newPendingTransactionFilter full rpc function

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5165]
### Describe the feature

the `eth_newPendingTransactionFilter` takes an optional bool parameter that determines whether the filter is for hashes or full transactions:

https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc/src/eth/filter.rs#L238-L238

this is similar to the pubsub function parameters:

https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc-types/src/eth/pubsub.rs#L99-L109

## TODO

* add new parameter type in rpc-types/filter.rs that is an enum `PendingTransactionFilterKind {Hashes, Full}`
* add Serialize and Deserialize impls that correspond to `Option<bool>`, similar to: https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc-types/src/eth/pubsub.rs#L125-L138
* add this as an parameter to the EthFilter function
* depending on the input parameter either install a listener for pending hashes like it is now:
https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc/src/eth/filter.rs#L240-L242
or install a listener for full transactions: 
https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/transaction-pool/src/traits.rs#L147-L147
see pubsub for reference: https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc/src/eth/pubsub.rs#L270-L280

add an enum for both variants where one variant for hashes is: https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc/src/eth/filter.rs#L481-L485

add a new variant for Transaction to the filterchanges type:

https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc-types/src/eth/filter.rs#L827-L833

### Additional context
@DoTheBestToGetTheBest 
_No response_

**Comment by DoTheBestToGetTheBest** [comment]
Thank you so much. I take this

**Comment by DoTheBestToGetTheBest** [comment]
> * add this as an parameter to the EthFilter function

Hey Mat, sorry to ping you for this but please can you tell me what is the EthFilter function ?

**Comment by mattsse** [comment]
ah sorry, I see how this was worded badly

it's this one

> async fn new_pending_transaction_filter(&self) -> RpcResult<FilterId> {

**Comment by DoTheBestToGetTheBest** [comment]
> ah sorry, I see how this was worded badly

No don't be sorry, it's normal. Thank you so much for the fast answer 


> 
> it's this one
> 
> > async fn new_pending_transaction_filter(&self) -> RpcResult {

Ty lot !

**Comment by DoTheBestToGetTheBest** [comment]
> ### Describe the feature
> the `eth_newPendingTransactionFilter` takes an optional bool parameter that determines whether the filter is for hashes or full transactions:
> 
> https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc/src/eth/filter.rs#L238-L238
> 
> this is similar to the pubsub function parameters:
> 
> https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc-types/src/eth/pubsub.rs#L99-L109
> 
> ## TODO
> * add new parameter type in rpc-types/filter.rs that is an enum `PendingTransactionFilterKind {Hashes, Full}`
> * add Serialize and Deserialize impls that correspond to `Option<bool>`, similar to: https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc-types/src/eth/pubsub.rs#L125-L138
> * add this as an parameter to the EthFilter function
> * depending on the input parameter either install a listener for pending hashes like it is now:
>   https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc/src/eth/filter.rs#L240-L242
>   
>   or install a listener for full transactions:
>   https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/transaction-pool/src/traits.rs#L147-L147
>   
>   see pubsub for reference: https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc/src/eth/pubsub.rs#L270-L280
> 
> add an enum for both variants where one variant for hashes is:
> 
> https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc/src/eth/filter.rs#L481-L485
> 
> add a new variant for Transaction to the filterchanges type:
> 
> https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/rpc/rpc-types/src/eth/filter.rs#L827-L833
> 
> ### Additional context
> @DoTheBestToGetTheBest _No response_

hey mat, i have a problem here if you can help please

when i add the type in parameter of the function, i need to also add it to into the trait where the function is defined. But i can't import PendingTransactionFilterKind where the trait function is defined. Any idea how can i solve this please?

**Comment by DoTheBestToGetTheBest** [comment]
here : https://github.com/paradigmxyz/reth/blob/fc4fc936807870b07acb91e1d50c3920b55ff055/crates/rpc/rpc-api/src/eth_filter.rs#L18

**Comment by mattsse** [comment]
hmm, I don't think this is an issue if you 

* define `PendingTransactionKind` in reth-rpc-types
* use it in reth-rpc-api

because reth-rpc-api already depends on it

feel free to open a draft anytime

**Comment by DoTheBestToGetTheBest** [comment]
> hmm, I don't think this is an issue if you
> 
> * define `PendingTransactionKind` in reth-rpc-types
> * use it in reth-rpc-api
> 
> because reth-rpc-api already depends on it
> 
> feel free to open a draft anytime

oh very good like that. I thought you wanted this type  in rpc-rpc

Thank you so much for your help Mat, realy appreciate this

**Comment by DoTheBestToGetTheBest** [comment]
> add an enum for both variants where one variant for hashes is:

hey , sorry for this but just wanna to be sure if you are okay with this name : 
are you okay with this type name ? 

```rust
enum PendingTransactionsReceiverKind {
    Hashes(PendingTransactionsReceiver),
    Full(NewSubpoolTransactionStream<Transaction>),
}```

if you don't like this name for this type i can take anything you suggest

**Comment by mattsse** [comment]
sounds good
