### ISSUE TITLE
refactor: rename primitives constant hashes

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#5168]
### Describe the feature

To clarify the naming of constants in the `primitives` crate, all the following constants

https://github.com/paradigmxyz/reth/blob/0f254e16a50a6d39543fe59590227a09fd0e21bb/crates/primitives/src/constants/mod.rs#L75-L105

concern hashes. For clearer naming and uniformity, wouldn't it be better to add the suffix `_HASH` at the end of each hash (for example `MAINNET_GENESIS` would become `MAINNET_GENESIS_HASH`). What do you think?

**Comment by mattsse** [comment]
sgtm
