### ISSUE TITLE
Keep rpc pending state separate from tree

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5183]
### Describe the feature

currently inserting into the tree on CL messages and RPC requests for pending state are synchronized

ideally, rpc requests don't interfere with the tree so the pending block+state should be kept separately.

this is currently hard to do and requires a few changes to the tree first or another approach, since we don't want any overhead with shared locks, we could emit this as a message and keep it entirely separate

**Comment by Arindam2407** [comment]
@mattsse Could you please add a bit more context? I would like to take up this issue
