### ISSUE TITLE
TransactionFetcher improvements

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5192]
### Describe the feature

with new transaction fetcher #5058 we optimized how we handle incoming announcements, there are a few things we need to improve:

1. Keep a map of active peer requests: `PeerId -> PeerRequestInfo`
  * introduce a PeerRequestInfo type that tracks the number of inflight hashes and requests

2. Incorporate Transaction metadata: type,size into requested hashes: https://github.com/paradigmxyz/reth/blob/d06931a38cb403073cd7e8496dd33f761da9fc60/crates/net/network/src/transactions.rs#L968-L969

this needs some changes here, because currently we're only using the hashes of the message

https://github.com/paradigmxyz/reth/blob/d06931a38cb403073cd7e8496dd33f761da9fc60/crates/net/network/src/transactions.rs#L491-L512

but we should use the type,size as well which are part of the message if eth68
https://github.com/paradigmxyz/reth/blob/d06931a38cb403073cd7e8496dd33f761da9fc60/crates/net/eth-wire/src/types/broadcast.rs#L260-L264

3. check missing requested hashes from response:
* this one needs a bit more thinking, because ideally we want to minimize the number of requests  and also don't overload individual peers
So I think we need another set of `Peer -> Set<Hash>` that keeps track of announced hashes so we can loop over idle peers and find all hashes that are not being requested atm

I think we should start with 2. @smatthewenglish

**Comment by smatthewenglish** [comment]
That sounds straight forward enough. I'll give it a shot!

Is it higher priority to start work on point 2 and table https://github.com/paradigmxyz/reth/issues/5143 for now, or would you rather have me land 5143 first?

**Comment by mattsse** [comment]
if you already started on #5143 let's wrap this up first, this shouldn't take too long

**Comment by mattsse** [comment]
incorporated into #4550
