### ISSUE TITLE
Measure how long do different steps of canonical commit take

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#5203]
### Describe the feature

Currently, we just measure the total canonical commit time and don't really know what the average 250ms consists of. In addition to that, we could also track the time per logical step (EVM execution / state root calc / database commit). It should be achievable by using tracing spans and logging these timings on DEBUG log level.

**Comment by i-m-aditya** [comment]
I will pick this.

**Comment by solidoracle** [comment]
@shekhirin I'd like to tackle this
