### ISSUE TITLE
Add maxuploadtarget flag to regulate outbound upload traffic

### ISSUE THREAD

**Issue by kaliubuntu0206** [paradigmxyz/reth#5235]
### Describe the feature

Just like how the flag on bitcoin works https://github.com/bitcoin/bitcoin/blob/master/doc/reduce-traffic.md#1-use--maxuploadtargetmib-per-day

The feature was once rejected by Geth team https://github.com/ethereum/go-ethereum/issues/22101 however it is an important feature for server ops since not all ISP allows excessive usage of ethereum nodes ( This is why running an ethereum node could lead to suspension of the internet service )

Related

https://www.reddit.com/r/ethstaker/comments/k3n4pr/controlling_geth_upload_bandwidth/
https://www.reddit.com/r/ethstaker/comments/jzux4x/be_aware_of_bandwidth_utilization_if_you_are_home/

For sharing ethereum data it should be contributed with some other methods that could regulate the P2P bandwidth, like webseeding or seeding through torrent for example

https://github.com/ledgerwatch/erigon-snapshot/tree/main/webseed

**Comment by kaliubuntu0206** [comment]
cc @karalabe @lightclient @holiman

**Comment by kaliubuntu0206** [comment]
Also possibly related with https://ethereum-magicians.org/t/eip-4444-bound-historical-data-in-execution-clients/7450

**Comment by lightclient** [comment]
Hi @kaliubuntu0206, this is an interesting feature to pursue. As Marius mentioned in the PR, there is a concern that this limit could get triggered and create a difficult situation for new nodes syncing. This could exacerbate an unrelated problem which causes many nodes to need resyncing (e.g. a problem in a particular client leaves them far behind). So I think following exactly in the path of `maxuploadtarget` is unwise here.

Additionally, history isn't really the bottleneck. If we look at the ingress ETH traffic over the last day, tx propagation is consumes roughly an order of magnitude more bandwidth than history queries:

![2023-10-30-150942_screenshot](https://github.com/paradigmxyz/reth/assets/14004106/98daa097-ec7d-4ddd-812f-ded3e3c5e623)

So the real win would be optimizing tx broadcast.

If it were me, there are couple things I would consider:
1. If there are improvements to the devp2p protocol which can reduce bandwidth usage across the board.
2. How can the tx broadcast algorithm be improved on the client side? 
3. What if we relaxed the assumption that clients attempt to retrieve and share *every* possible available tx and only retrieve / propagate a smaller, random subset?

On EIP-4444, it will certainly play a role in reducing the amount of bandwidth clients use to bootstrap new nodes, but as I said, that is a very small portion of the total bandwidth used by clients.

**Comment by kaliubuntu0206** [comment]
@lightclient Thank you for your reply. I think we could solve the problem by splitting flags to regulate bandwidth allowed for uploading history and transaction broadcast ( Bitcoin node also supports disabling transaction relay for this case, also I think in some case transaction with low gas fees could be ignored from the relay as well )

https://github.com/bitcoin/bitcoin/blob/master/doc/reduce-traffic.md#4-turn-off-transaction-relay--blocksonly

It is great to have the actual discussion to give users a choice to regulate traffic and I think it is important since limiting traffic would allow more validators to be hosted without an additional expense for networking fees.

**Comment by lightclient** [comment]
The main issue I would generally be cautious of giving people command line flags that i) rationale users will enable and ii) degrade the network experience. There is an argument that tx broadcasting is on the downhill with the rise of private txpools, but in all likelihood the public txpool will be the last resort for those who are being censored. So we want to get it right.

Before going down the path of allowing users to turn off their txpol, I simply request that you carefully consider what happens if you succeed.
