### ISSUE TITLE
Add blocksonly flag for disabling transaction relay

### ISSUE THREAD

**Issue by kaliubuntu0206** [paradigmxyz/reth#5244]
### Describe the feature

Could be useful for some environments and could decrease overall traffic

Example from bitcoin node

https://github.com/bitcoin/bitcoin/blob/master/doc/reduce-traffic.md#4-turn-off-transaction-relay--blocksonly

Related

https://github.com/paradigmxyz/reth/issues/5235#issuecomment-1786062429

**Comment by mattsse** [comment]
ref #4377

**Comment by DoTheBestToGetTheBest** [comment]
> ref #4377

Any idea where part of code we need to see for this issue ? I want to give try on it
