### ISSUE TITLE
feat(payload): Split Optimism Builder Crate

### ISSUE THREAD

**Issue by refcell** [paradigmxyz/reth#5247]
### Describe the feature

Following #4377, @mattsse [requested](https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376095889) that the optimism payload builder logic be placed in its own crate.

> I'd actually prefer the optimism builder in a separate crate as another type.
>
> everything that can be shared, like build_empty_payload can be moved to builder crate

**Comment by supernovahs** [comment]
I can take this

**Comment by Rjected** [comment]
I think this was solved by https://github.com/paradigmxyz/reth/pull/5876, so closing
