### ISSUE TITLE
Test `can_peer_with_geth` is flaky

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#5306]
### Describe the bug

`reth-network::it geth::can_peer_with_geth`

<https://github.com/paradigmxyz/reth/actions/runs/6760933670/job/18375255287>

### Steps to reproduce

N/A

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by DaniPopes** [comment]
cc @mattsse maybe we should run these with `--retries`?

**Comment by mattsse** [comment]
I think that's reasonable + tokiotimeout
I suspect we're not waiting long enough before we try connecting
