### ISSUE TITLE
Potential DoS attack

### ISSUE THREAD

**Issue by SE2023Test** [paradigmxyz/reth#5326]
### Describe the bug

Since the blob transactions has a very low gas cost,
blob transactions that execute numerous operations, such as opstore, can lead to excessive memory usage. Consequently, an OOM error can occur, potentially raising a DoS attack.

### Steps to reproduce

1. deploy a memory-heavy contract
2. call this contract with blob transactions

**Comment by mattsse** [comment]
> such as opstore, can lead to excessive memory usage

can you elaborate on this

**Comment by Rjected** [comment]
Going to close this for now due to lack of supporting details
