### ISSUE TITLE
[macOS, container] Failed to open database: 22

### ISSUE THREAD

**Issue by jgresham** [paradigmxyz/reth#5333]
### Describe the bug

Reth fails to start when running as a container on macOS (in a linux VM) with Podman which is similar to Docker Desktop. I have `chmod -R 777` the datadir as well.

### Steps to reproduce

1. Install podman (docker desktop replacement) and start a machine
2. Start the container
`
podman run -q --name reth -v "/Users/johns/Library/Application Support/NiceNode/nodes/reth-1699295497":/root/.local/share/reth/mainnet/db -p 30303:30303/tcp -p 30303:30303/udp -p 8545:8545 -p 8546:8546 -p 8551:8551 ghcr.io/paradigmxyz/reth node --color never --authrpc.addr 0.0.0.0 --authrpc.jwtsecret /root/.local/share/reth/mainnet/db/jwtsecret --ipcdisable --http --http.corsdomain http://localhost --full --http.addr 0.0.0.0 --chain mainnet
`

### Node logs

```text
Error logs:

2023-11-06T18:35:34.058758Z  INFO reth::cli: reth 0.1.0-alpha.10 (1b16d80) starting
2023-11-06T18:35:34.059683Z  INFO reth::cli: Configuration loaded path="/root/.local/share/reth/mainnet/reth.toml"
2023-11-06T18:35:34.059753Z  INFO reth::cli: Opening database path="/root/.local/share/reth/mainnet/db"
Error: Failed to open database: 22

Location:
    /project/crates/storage/db/src/lib.rs:121:18
```
```


### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

reth 0.1.0-alpha.10 (1b16d80)

### What database version are you on?

version in `latest` reth container

### What type of node are you running?

Full via --full flag

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by jgresham** [comment]
fyi, I have the same error using version `0.1.0alpha.15`

**Comment by onbjerg** [comment]
Hi @jgresham, sorry about the non-response. Is this still an issue on the latest beta?

**Comment by jgresham** [comment]
> Hi @jgresham, sorry about the non-response. Is this still an issue on the latest beta?

Either the new beta version fixed this, or Podman v5's change to macOS vfkit for the Linux VM fixed this. Not sure. I have not tested with Docker Desktop on macOS. 

Log `"Database opened"` in ss:
<img width="1109" alt="Screenshot 2024-04-02 at 11 41 32 AM" src="https://github.com/paradigmxyz/reth/assets/3721291/4b26d418-6dc3-4703-b9df-da846347c985">
