### ISSUE TITLE
Engine RPC API metrics graph

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#5336]
### Describe the feature

We now have metrics for the various engine API endpoints:
https://github.com/paradigmxyz/reth/pull/4912

Dashboards for these metrics should be added to the grafana dashboard

**Comment by 1010adigupta** [comment]
I will take up this issue

**Comment by Rjected** [comment]
> I will take up this issue

sweet, assigned!

**Comment by Rjected** [comment]
We'd want something like this for example, since p90/p95/p99/p999 metrics are important:
<img width="922" alt="Screenshot 2023-11-07 at 11 08 27 AM" src="https://github.com/paradigmxyz/reth/assets/6798349/c623d133-28ad-4cd6-80fb-6f74f9f06ad5">
<img width="922" alt="Screenshot 2023-11-07 at 11 08 47 AM" src="https://github.com/paradigmxyz/reth/assets/6798349/b9c881e1-4375-4174-b4d6-1c7238e80be7">

**Comment by 1010adigupta** [comment]
okay understood

**Comment by 1010adigupta** [comment]
so basically these metrics: [ENGINE METRICS](https://github.com/paradigmxyz/reth/pull/4912/files#diff-f8f9f7d45b9b38017684ad3f5c65c4a415614911c7be26f0d637636ed7ece665 )
are needed to be added in overview.json, right??

**Comment by Rjected** [comment]
> so basically these metrics: [ENGINE METRICS](https://github.com/paradigmxyz/reth/pull/4912/files#diff-f8f9f7d45b9b38017684ad3f5c65c4a415614911c7be26f0d637636ed7ece665) are needed to be added in overview.json, right??

yep exactly

**Comment by Rjected** [comment]
> so basically these metrics: [ENGINE METRICS](https://github.com/paradigmxyz/reth/pull/4912/files#diff-f8f9f7d45b9b38017684ad3f5c65c4a415614911c7be26f0d637636ed7ece665) are needed to be added in overview.json, right??

@1010adigupta hi, have you had time for this? do you need any help?
