### ISSUE TITLE
Massive unwind + Issue #5024 + Weirdness

### ISSUE THREAD

**Issue by brockelmore** [paradigmxyz/reth#5343]
### Describe the bug

![image](https://github.com/paradigmxyz/reth/assets/31553173/c4052c28-5445-4196-8e0d-7dac73df048a)

Some context: I don't imagine this is reproducible, but I wanted to document it here. I use Arch Linux. Prior to starting up my node I had to run `fsck`, because my drive was corrupted. So on a fresh install of reth + lighthouse, I started to sync a node

Everything was going fine, I finished the headers + totalDifficulty stages. During `Sender Recovery` stage, I hit #5024. I commented that I hit it on that issue, restarted my node, and it seemed to have fixed itself. Sender Recovery finishes and execution starts. I go to bed and overnight my internet shuts off. Check on sync progress and see execution had stopped, the db had been unwound to the blockheight of the latest executed block (4604449). Sender Recovery drops from 18m to 4604449. A number of hours later `Bodies`, followed by `TotalDifficulty`, followed `Headers`, all drop to 4.6m.

I reset my internet in the AM and it starts redownloading headers, and is currently redownloading bodies.

So a few things:
1. #5024 
2. Massive unwind?
3. All could be related to a dying nvme drive

### Steps to reproduce

1. Maybe have a broken drive, run `fsck`
2. Start Node
3. Hit #5024
4. Restart Node
5. Finish Sender Recovery, start execution
6. Lose internet connection
7. Undergo the massive unwind

### Node logs

```text
Unfortunately logs were overwritten when I restarted the node.
```

### Platform(s)

Linux main 0.5.9-arch2-1 (Arch Linux)

### What version/commit are you on?

2d315c2f

### What database version are you on?

1

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

None

### If you've built Reth from source, provide the full command you used

RUSTFLAGS="-C target-cpu=native" cargo build --profile maxperf --features jemalloc

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
@brockelmore was this due to bit flip? or is this something we should look into
