### ISSUE TITLE
Add NetworkEvents trait

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5352]
### Describe the feature

we can use a trait that exposes event subscriptions of the NetworkHandle

## TODO

add `trait NetworkEvents` here https://github.com/paradigmxyz/reth/blob/fd7896fd7c67a70364fe5546967ac88a0535000a/crates/net/network/src/network.rs#L341-L341
(we could do this in network-api but this would require moving a lot of stuff...)

then add trait functions for:

https://github.com/paradigmxyz/reth/blob/fd7896fd7c67a70364fe5546967ac88a0535000a/crates/net/network/src/network.rs#L86-L100

then add new trait here as additional bound

https://github.com/paradigmxyz/reth/blob/fd7896fd7c67a70364fe5546967ac88a0535000a/bin/reth/src/cli/components.rs#L50-L50

**Comment by PanGan21** [comment]
Hi! I did some work for this! Let me know if it is okay :)
