### ISSUE TITLE
(fix available) Loading genesis.json from Geth fails due to very large U256: terminalTotalDifficulty

### ISSUE THREAD

**Issue by CRossel87a** [paradigmxyz/reth#5359]
### Describe the bug

Hi,

When attempting to load eth mainnet (or forks) genesis.json from geth you will get the error Error("invalid type: floating point `58750003716598360000000 on the field terminalTotalDifficulty

A quick hack is to edit the file and wrap the number in quotes "x" so that serde does not force reading it as a floating point.

After init, you have to run the client with reth --chain genesis.json or it will get the difficulty numbers wrong

I tried to make a deserializer to avoid this, but it seems the serde package is forcing non-quoted numbers into floating points

### Steps to reproduce

reth init --chain genesis.json

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
which commit are you on?
can you please share the json file?

**Comment by CRossel87a** [comment]
> which commit are you on? can you please share the json file?

Tested on master. The attached file was generated by 'geth --mainnet dumpgenesis'

[eth.json](https://github.com/paradigmxyz/reth/files/13299256/eth.json)

**Comment by mattsse** [comment]
sorry can't reproduce on main, please provide sha

```
cargo run --bin reth -- init --chain ../genesis.json --datadir dummy                                                                                                                                                                       $ main
    Finished dev [unoptimized + debuginfo] target(s) in 0.64s
     Running `target/debug/reth init --chain ../genesis.json --datadir dummy`
2023-11-08T17:03:59.226724Z  INFO reth::cli: reth init starting
2023-11-08T17:03:59.226868Z  INFO reth::cli: Opening database path="dummy/db"
2023-11-08T17:03:59.230323Z  INFO reth::cli: Database opened
2023-11-08T17:03:59.230337Z  INFO reth::cli: Writing genesis block
2023-11-08T17:04:00.982056Z  INFO reth::cli: Genesis block written hash=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3

```

**Comment by CRossel87a** [comment]
You're right. I blundered with a fork unknowingly and I had an older version. Sorry
