### ISSUE TITLE
Test support for e2e rpc tests

### ISSUE THREAD

**Issue by DoTheBestToGetTheBest** [paradigmxyz/reth#5374]
### Describe the feature

currently geth have testBackend type where it hold some data for backend testing, Ref  : https://github.com/ethereum/go-ethereum/blob/0004c6b229b787281760b14fb9460ffd9c2496f1/eth/tracers/api_test.go#L54-L54

thinking of adding a new type called TestBackend with only provider data on it

and a trait of EthereumRPC  which would have transaction_by_hash, block_by_hash ... etc

then implement this trait for our type 

Is it good approach ?

**Comment by mattsse** [comment]
> thinking of adding a new type called TestBackend with only provider data on it

yeah, this type should wrap:
* Arc<TempDatabase<DatabaseEnv>>
* Chainspec

similar to:
https://github.com/paradigmxyz/reth/blob/d9920ce6c4ac43bc1be41b944d4015c5329f3031/crates/stages/src/test_utils/test_db.rs#L34-L36

this will be a good starting point, then we need a bunch of helper functions to insert and get stuff

**Comment by DoTheBestToGetTheBest** [comment]
> > thinking of adding a new type called TestBackend with only provider data on it
> 
> yeah, this type should wrap:
> 
> * Arc<TempDatabase>
> * Chainspec
> 
> similar to:
> 
> https://github.com/paradigmxyz/reth/blob/d9920ce6c4ac43bc1be41b944d4015c5329f3031/crates/stages/src/test_utils/test_db.rs#L34-L36
> 
> this will be a good starting point, then we need a bunch of helper functions to insert and get stuff

thnak you for your answer. This should be in which file please?

**Comment by DoTheBestToGetTheBest** [comment]
hey @mattsse any hint where this should be written please? :)

**Comment by mattsse** [comment]
let's keep it in rpc-builder for now, we can eventually move it later

**Comment by mattsse** [comment]
closing this because I'll convert this into a new larger tracking issue
