### ISSUE TITLE
Possible data loss during the trace_replayBlockTransactions request

### ISSUE THREAD

**Issue by derevyan** [paradigmxyz/reth#5386]
### Describe the bug

We looking at storage slots state changes for WETH on a Reth archive node (block: 18518212) and get this output:

```
0xb87eaeeeb196a873a0a4c6b95f4bc1447f3b2072039aa5ea8e277a1f18d71d81: Born(
    0x00000000000000000000000000000000000000000000000000b1a2bc2ec50000,
)
```

But when I request the same on QuickNode (erigon i guess), the output is different:

```
0xb87eaeeeb196a873a0a4c6b95f4bc1447f3b2072039aa5ea8e277a1f18d71d81: Changed(
    ChangedType {
        from: 0x00000000000000000000000000000000000000000000000000b1a2bc2ec50000,
        to:   0x00000000000000000000000000000000000000000000000000d529ae9e860000,
    }
)
```

For some reason, this change is not reflected in Reth: 
`0x00000000000000000000000000000000000000000000000000d529ae9e860000` 

This example in: 
`"transactionHash": "0xa9f39ee5a6ecbfb39a52617097c2de48576a2f78b8b28954b73178e75171129d"`

However, the same type of missing data is also present in other blocks.

We discovered that this occurs only with **Diff::Born** type.

Uncertain if it's present in version 0.1.0-alpha.10; a node resynchronization may be necessary to confirm, which I cannot perform at the moment.

Thanks a lot for a great product, by the way and good luck!

### Steps to reproduce

`curl http://localhost:8545/ \
        -X POST \
        -H "Content-Type: application/json" \
        --data '{"method":"trace_replayBlockTransactions","params":["0x11A90C4",["stateDiff"]],"id":1,"jsonrpc":"2.0"}'`

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.1.0-alpha.8

### What database version are you on?

1

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this has been fixed since alpha8

you can check public node http://69.67.151.138:8545
