### ISSUE TITLE
SSZ implementation for (relay) types

### ISSUE THREAD

**Issue by blombern** [paradigmxyz/reth#5388]
### Describe the feature

As a relay developer, I'm excited to start depending on Reth relay types: https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-types/src/relay.rs

One thing that's been a bit annoying is the SSZ encode/decode situation (most payloads our relay receives are SSZ encoded).   Because there's no SSZ implementation for the primitive types, I've had to use wrapper types to implement it.

I've found two SSZ libraries (we're using the sigp one):
https://github.com/sigp/ethereum_ssz
https://github.com/ralexstokes/ssz-rs

It'd be great there existed canonical relay types with SSZ implemented.

**Comment by mattsse** [comment]
this should be pretty simple since all the primitive types already support ssz

do you have some test vectors for the types that should support ssz?

**Comment by blombern** [comment]
We have terabytes of submissions, which look like:

```rust
pub struct SubmitBlockRequest {
    pub message: BidTrace,
    pub execution_payload: ExecutionPayload,
    pub signature: BlsSignature,
}
```

This type is what the relay needs SSZ for. I can provide some test data if it's helpful.

**Comment by mattsse** [comment]
yes please, testdata would be very helpful
adding ssz would be straightforward to add I suppose

**Comment by blombern** [comment]
Ok, I'll try to get a PR up when I have a minute

**Comment by blombern** [comment]
It seems that there's an ssz issue with `alloy-primitives`, which leads to e.g. `BidTrace` returning the wrong fixed size, and breaking encoding when part of an ssz container https://github.com/alloy-rs/core/issues/448

**Comment by DaniPopes** [comment]
Can this be closed? @blombern @mattsse

**Comment by mattsse** [comment]
yep, I'll also move all of these types to alloy directly under a new crate
