### ISSUE TITLE
Suicide trace missing

### ISSUE THREAD

**Issue by mavileo** [paradigmxyz/reth#5409]
### Describe the bug

trace_transaction for tx 0xe37f5d4b7b2dd19f7d152acdc8fcef2791e66df3b819327a46db4274d646b4e7 returns 14 traces instead of 15, missing the suicide trace.

Other txs: 
0x72d25e40c40a26a6539fb3ca36a8d7e078f32bd31cba05b898ad88fd6894352a
0xd8a0f39ec4314cdc9aa019028d86ff1daccecf386f9c7f21c4bf4b198f690695

Same behaviour for trace_block.

reth Version: 0.1.0-alpha.10
Commit SHA: https://github.com/paradigmxyz/reth/commit/98bc2b5c841bb835523f32c0c3425bbbd3859093
Build Timestamp: 2023-10-08T13:02:17.115606141Z
Build Features: default,jemalloc
Build Profile: release

### Steps to reproduce

curl http://localhost:8545   \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"trace_transaction","params":["0x54160ddcdbfaf98a43a43c328ebd44aa99faa765e0daa93e61145b06815a4071"],"id":1,"jsonrpc":"2.0"}' 

### Platform(s)

Linux (x86)

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

cargo build --release

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks,
this has since been fixed on main

**Comment by mavileo** [comment]
Thank you!
