### ISSUE TITLE
Use `alloy_chains::Chain` instead of vendoring own implementation

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#5429]
### Describe the feature

Use [`alloy_chains::Chain`](https://github.com/alloy-rs/chains) instead of vendoring our own implementation in `reth_primitives::Chain`. Both `Chain` and `NamedChain` should be able to be replaced easily.

### Additional context

`alloy_chains`
- [on crates.io](https://crates.io/crates/alloy-chains)
- [on docs.rs](https://docs.rs/alloy-chains)

**Comment by 1010adigupta** [comment]
I would like to take up this issue

**Comment by mattsse** [comment]
assigned

**Comment by supernovahs** [comment]
I can take this if available

**Comment by supernovahs** [comment]
I can take this

**Comment by 1010adigupta** [comment]
Hey @supernovahs, I have recently started working on it. :)

**Comment by 1010adigupta** [comment]
@mattsse basically instead of reth-primitives::<items> I need to use alloy-chains::<item> where they appear and change the associated logic accordingly right?

**Comment by mattsse** [comment]
yeah remove reth_primitives::Chain and reexport alloy_chains::Chain instead
