### ISSUE TITLE
Add an example on how to enable eth_callBundle please

### ISSUE THREAD

**Issue by pxr64** [paradigmxyz/reth#5444]
### Describe the change

Hey, I'm having trouble figuring out how to enable the eth_*Bundle features, can you please point out how to modify the code to enable them?

**Comment by DoTheBestToGetTheBest** [comment]
I think what you are looking for is : https://github.com/paradigmxyz/reth/blob/main/examples/additional-rpc-namespace-in-cli/src/main.rs#L77

**Comment by pxr64** [comment]
Getting the following error when setting the flag:
```
error: Invalid value 'admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots,eth-call-bundle' for --http.api <HTTP_API>: Matching variant not found.
```
