### ISSUE TITLE
Enable ResolvePayloadFuture to be generic to the PayloadJob trait

### ISSUE THREAD

**Issue by loocapro** [paradigmxyz/reth#5452]
### Describe the feature

I am using the reth Payload crate to modify the default behaviour of engine Api payload jobs. I am implementing the PayloadJobGenerator passing my own PayloadJob. 

Currently the `PayloadJob::resolve()`returns a `ResolvePayloadFuture` which is tied to the BuiltPayload reth type currently consumed by the engine API.

I 'd love that the ResolvePayloadFuture could be generic so that I could return a `BuiltPayload` and some other parameter that I am calculating from my PayloadJobs.

@mattsse do you have any better way to achieve this?

I'd love to pick this up myself.

**Comment by mattsse** [comment]
how are you using your type?

because, by default, the generator is controlled by the service:

https://github.com/paradigmxyz/reth/blob/460b5f6fda19ee39c35c867bf84a71bd8cd3ef09/crates/payload/builder/src/service.rs#L159-L162

which is wired to the engine API

**Comment by loocapro** [comment]
> how are you using your type?
> 
> because, by default, the generator is controlled by the service:
> 
> https://github.com/paradigmxyz/reth/blob/460b5f6fda19ee39c35c867bf84a71bd8cd3ef09/crates/payload/builder/src/service.rs#L159-L162
> 
> which is wired to the engine API

I am just implementing a custom generator, with a custom job, and spawning a custom payload service.

Then I interact to the custom payload service via the payload handle resolve function, which unfortunately can only return a BuiltPayload future.

**Comment by mattsse** [comment]
gotcha, 
so currently this format is fixed, but I think we actually want this to be generic, because optimism would also benefit from this.

I need to think about this a bit more because it would introduce a few more changes wrt generics

**Comment by loocapro** [comment]
Okk, please let me know. If it's not a huge change i d like to take it.

**Comment by loocapro** [comment]
Hi @mattsse sorry to hassle you, have you got any news on this?

Currently I have solved by duplicating the PayloadService code but I am a bit worried about future conflicts.

**Comment by mattsse** [comment]
this would require significant changes across the codebase and is more or less blocked by this https://github.com/paradigmxyz/reth/issues/5501

perhaps we can at least introduce a new associated type to the trait for now and require that it is `Into<BuiltPayload>`

But I also think you should be able to work around this for your use case with some extra code bypassing the payload handle, which doesn't have generics

**Comment by loocapro** [comment]
> bypassing the payload handle, which doesn't have generics

Thanks a lot Matt. Could you please show me how would you by pass the payload handle?

**Comment by idatsy** [comment]
Would this be resolved by just making the `PayloadBuilderHandle::new` pub so that extending `spawn_payload_builder_service` lets you roll your own builder logic consuming the `to_service` channel directly?

That or make `PayloadBuilderHandle` a pub trait where users can impl their own `resolve`, `best_payload`, `payload_attributes`, `send_new_payload` and `new_payload`?

**Comment by mattsse** [comment]
> Would this be resolved by just making the PayloadBuilderHandle::new pub so that extending

that would def make this possible, yeah

let's do that first.

then I think we want the return type of the Future Also `Into<Payload>`, though we'd need to break that again eventually

**Comment by idatsy** [comment]
> > Would this be resolved by just making the PayloadBuilderHandle::new pub so that extending
> 
> that would def make this possible, yeah
> 
> let's do that first.
> 
> then I think we want the return type of the Future Also `Into<Payload>`, though we'd need to break that again eventually

Awesome, I'll PR that for your right away, will drastically simplify my (and I assume others) payload building logic :)

**Comment by idatsy** [comment]
> > Would this be resolved by just making the PayloadBuilderHandle::new pub so that extending
> 
> that would def make this possible, yeah
> 
> let's do that first.
> 
> then I think we want the return type of the Future Also `Into<Payload>`, though we'd need to break that again eventually

I left out the `Into<Payload>` change as I'm not sure exactly what you have in mind there: #5578

**Comment by loocapro** [comment]
Thanks @idatsy. 

This is not going to solve my issue as I am using the payload crate (generator + service + handle) and I like how it is structured. I don't even think that `new` function should be exposed to the outside as it could expose the internal implementation to the outside world and it would totally miss the purpose of encapsulation.

@mattsse I love the idea of restricting the ResolvePayloadFuture to `Into<Payload>`, will try to get a pr up soon.

**Comment by mattsse** [comment]
marking this as completed because this is now possible:

https://github.com/paradigmxyz/reth/blob/f23250d88c1eb809ca9aed91079cb913d79fb7be/crates/payload/builder/src/service.rs#L201-L201

https://github.com/paradigmxyz/reth/blob/f23250d88c1eb809ca9aed91079cb913d79fb7be/crates/payload/builder/src/traits.rs#L27-L28
