### ISSUE TITLE
Report MDBX commit latency metrics

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#5458]
### Describe the feature

On `mdbx_txn_commit_ex`, we discard the [latencies](https://erthink.github.io/libmdbx/struct_m_d_b_x__commit__latency.html) that MDBX reported to us. It has some interesting metrics that can be useful for debugging of database-related issues.

---

The commit call is made in two places: https://github.com/paradigmxyz/reth/blob/e5362882e0da7e39912210152eebc4b08b0e6c7c/crates/storage/libmdbx-rs/src/transaction.rs#L188 https://github.com/paradigmxyz/reth/blob/e5362882e0da7e39912210152eebc4b08b0e6c7c/crates/storage/libmdbx-rs/src/environment.rs#L590

Both require passing a pointer to latencies variable (which shouldn't be of `ffi:MDBX_commit_latency` type, let's create a wrapper type with nice doc comments according to MDBX docs), and then returning it from the method as a second tuple value https://github.com/paradigmxyz/reth/blob/e5362882e0da7e39912210152eebc4b08b0e6c7c/crates/storage/libmdbx-rs/src/transaction.rs#L184

Then, the metric should be reported using existing helper https://github.com/paradigmxyz/reth/blob/e5362882e0da7e39912210152eebc4b08b0e6c7c/crates/storage/db/src/implementation/mdbx/tx.rs#L198-L202

**Comment by pakrentos** [comment]
I would like to take this issue

**Comment by shekhirin** [comment]
@pakrentos hi, are you still working on it?

**Comment by pakrentos** [comment]
@shekhirin hi, yep. sorry, hit some personal snags and work delays, but still pushing forward on this. thanks for your patience!

**Comment by onbjerg** [comment]
Closed in #5668
