### ISSUE TITLE
Restore txpool after reboot

### ISSUE THREAD

**Issue by jsvisa** [paradigmxyz/reth#5509]
### Describe the feature

Reth will not dump the txpool's content into disk and restore them after reboot, this will cause the local txs to be missing if they were not announced before reboot.

**Comment by mattsse** [comment]
right, we definitely want this

I guess we can get away with only dumping local txs?
or at least start with that

**Comment by jsvisa** [comment]
> I guess we can get away with only dumping local txs?
> or at least start with that

I totally agree with the only dump/restore the local txs

**Comment by allnil** [comment]
Take it
