### ISSUE TITLE
Weird params inside send_transaction function

### ISSUE THREAD

**Issue by huongcodelight** [paradigmxyz/reth#5510]
I try to run this function (my comment referenced below) and when it comes into method `self.estimate_gas_at`,  the underlying `CallFees::ensure_fees` function return the error `Err(EthApiError::ConflictingFeeFieldsInRequest)`. I debugged and found that in the `match` case at the bottom, there is no case that all of three `gas_price`, `max_fee_per_gas` and `max_priority_fee_per_gas` is `Some(...)`, but those parameters pass from `self.estimate_gas_at` are always `Some`. Could anyone please help me with this point?

And if I were wrong at some point, could anyone send me the correct parameters to pass into the `send_transaction` function to execute successfully? Thank you so much for the help.

_Originally posted by @huongcodelight in https://github.com/paradigmxyz/reth/pull/1976#discussion_r1399010050_

**Comment by mattsse** [comment]
what price should be picked when conflicting fields are set?

send_transaction isn't really implemented because only useful for dev purposes.

there are no signers included so this is essentially a noop by default

**Comment by huongcodelight** [comment]
> what price should be picked when conflicting fields are set?
> 
> send_transaction isn't really implemented because only useful for dev purposes.
> 
> there are no signers included so this is essentially a noop by default

Thank you for your quick response 🙏  I use Postman to call rpc eth_sendTransaction and find this issue. Are there some relevant ways to send transactions if the way above isn't really implemented?

**Comment by mattsse** [comment]
if you want to send real transaction to the network you should always use the `send_rawTransaction` endpoint that only accepts signed transactions.

if you need a node for local testing purposes, you can use anvil for example

**Comment by mattsse** [comment]
this has been fixed via #6671
