### ISSUE TITLE
The --http.api eth-call-bundle is not working

### ISSUE THREAD

**Issue by hedgepaybsc** [paradigmxyz/reth#5515]
### Describe the bug

Trying to start the reth instace with `eth-call-bundle`  fails
error: Invalid value 'admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots,eth-call-bundle' for --http.api <HTTP_API>: Matching variant not found.

### Steps to reproduce

Start a reth instance with the ` eth-call-bundle` flag

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
unable to reproduce on main
