### ISSUE TITLE
Slim down reth-primitives crate by extracting fork types to standalone crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5524]
### Describe the feature

the crate is currently a bit bloated and it includes things that are useful on its own.

This includes:

* Hardfork + ForkId etc..

## TODO
* Extract Hardfork + Forkid to new crate `reth-ethereum-forks`

**Comment by Arindam2407** [comment]
I can take this

**Comment by mattsse** [comment]
I think the only real road bump are these functions:

https://github.com/paradigmxyz/reth/blob/226eb86c73a1e2d443d0115ddaed1c31f3f46da6/crates/primitives/src/hardfork.rs#L54-L54

which I guess we should flip so that they are functions of `ChainSpec` instead of functions of Hardfork
