### ISSUE TITLE
Add StateOverrides to estimateGas call

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5558]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/37d74029669a2ceb10b223b7a251e9bce22b2391/crates/rpc/rpc-api/src/eth.rs#L186-L193

like call:

https://github.com/paradigmxyz/reth/blob/37d74029669a2ceb10b223b7a251e9bce22b2391/crates/rpc/rpc-api/src/eth.rs#L151-L151

## TODO
* add type
* apply overrides https://github.com/paradigmxyz/reth/blob/37d74029669a2ceb10b223b7a251e9bce22b2391/crates/rpc/rpc/src/eth/revm_utils.rs#L523-L523

**Comment by allnil** [comment]
Hi!
Maybe I can take this?

**Comment by mattsse** [comment]
assigned
