### ISSUE TITLE
parity `vmTrace` stack pushes are incorrect

### ISSUE THREAD

**Issue by gbrew** [paradigmxyz/reth#5561]
### Describe the bug

The code which reports the newly pushed stack elements for each executed opcode is broken, and gives some obviously wrong answers, like this, which shows two elements pushed by a PUSH1:

```
      {
        "cost": 3,
        "ex": {
          "used": 180751,
          "push": [
            "0x20",
            "0x40"
          ],
          "mem": {
            "off": 2688,
            "data": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000>
          },
          "store": null
        },
        "pc": 371,
        "sub": null,
        "op": "PUSH1"
      },
```

Looking at the code, I can see that the issue is in trying to use both `stack` and `push_stack` to produce this value. I'll put up a PR soon to fix it.

### Steps to reproduce

cast rpc trace_replayTransaction --raw '[ "txhash", ["vmTrace"]]'

You'll get wrong answers for basically any transaction.

### Platform(s)

Linux (x86)

### What version/commit are you on?

af8885172313aca66816dfc72537728d0c3c4e36

### What database version are you on?

1

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks for flagging, 
I figured that these are still not quite right.
will tackle them next

**Comment by gbrew** [comment]
No problem, just posted a PR with a fix
