### ISSUE TITLE
error: command `/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics --all-features` exited with code 101

### ISSUE THREAD

**Issue by yy138484** [paradigmxyz/reth#5581]
### Describe the bug

I clone the source code of Reth v0.1.0-alpha.11 to my environment, when I run the command: cargo llvm-cov nextest --html  --locked --manifest-path bin/reth/Cargo.toml --all-features, it get to an error: could not compile `reth` (lib test); and
error: command `/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics --all-features` exited with code 101
my environment is Ubuntu 22.04.3 LTS

### Steps to reproduce

cargo llvm-cov nextest --html  --locked --manifest-path bin/reth/Cargo.toml --all-features

### Platform(s)

Linux (x86)

### What type of node are you running?

None

### If you've built Reth from source, provide the full command you used

cargo llvm-cov nextest --html  --locked --manifest-path bin/reth/Cargo.toml --all-features

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
Are you running in QEMU or another VM? Do you have `build-essential` installed?

**Comment by onbjerg** [comment]
Closing this, let me know if you still have this issue
