### ISSUE TITLE
Prototype `eth_multicallV1` RPC API endpoint

### ISSUE THREAD

**Issue by pistomat** [paradigmxyz/reth#5586]
### Describe the feature

There is an ongoing effort to standardise an endpoint for a multicall across execution clients and introduce a new RPC method `eth_multicallV1`, which allows users to make complex RPC calls to Ethereum nodes. Compared to `eth_call`, it has many new additional features such as multiple dependent calls, various new overrides or simulating multiple blocks.

This endpoint is not finalised yet, but implementing it will help it's development.

### Additional context

The specification for this RPC method can be found here: https://github.com/ethereum/execution-apis/pull/484

#### Other client's implementation
Geth: https://github.com/s1na/go-ethereum/tree/multicall
Nethermind: https://github.com/NethermindEth/nethermind/tree/feature/eth_multicall

**Comment by mattsse** [comment]
I think this is similar to 

https://github.com/paradigmxyz/reth/blob/ca9f236947cc5e07db9f0ae0bf5f4a02e727f2c5/crates/rpc/rpc/src/eth/api/call.rs#L72-L79

**Comment by solidoracle** [comment]
I'll take this

**Comment by leontiadZen** [comment]
Hey can I check that with some guidance?
