### ISSUE TITLE
panic when reading tx receipts using DatabaseProvider

### ISSUE THREAD

**Issue by naps62** [paradigmxyz/reth#5592]
I'm having panics when trying to read tx receipts directly from DB (using code similar to the one in `reth-indexer`). the TLDR:

```rust
    let provider: reth_provider::DatabaseProvider<Tx<RO>> = factory.provider().unwrap();

    // tx works
    let tx = provider.transaction_by_hash(hash).unwrap().unwrap();

    // panics
    let receipt = provider.receipt_by_hash(hash).unwrap().unwrap();
```

this is happening on a local Sepolia full node.
doing the equivalent JSON-RPC request (`eth_getTransactionReceipt`) against the same node works with no issues.
`reth.toml` was fully generated on the first run, and this is the node command:

```
  reth node \
    --chain sepolia \
    --datadir $DIR/reth \
    --metrics 0.0.0.0:$ETH1_METRICS_PORT \
    --authrpc.addr 127.0.0.1 \
    --authrpc.port $AUTHRPC_PORT \
    --http \
    --http.port 8555 \
    --http.api all \
    --ws \
    --ws.port 8556 \
    --ws.api all
```

#### Using alpha.10 (yesterday)
I would get two different errors. `assertion failed self.remaining() >= 1` seemed to happen when querying recent blocks, and a different error when querying older ones. Unfortunately I didn't keep full details of this since my plan was to re-sync my local node with alpha.11 to see if it was fixed

#### Using alpha.11 (today)
this was after a full sync from scratch since yesterday. Getting:

```
thread 'main' panicked at /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/8667c33/crates/primitives/src/receipt.rs:19:1:
Failed to decompress: Src size is incorrect
```

<details>
  <summary>with `RUST_BACKTRACE=1` (click to expand)</summary>
<pre>
<code>
   Compiling reth-bug v0.1.0 (/home/naps62/projects/reth-bug)
    Finished dev [unoptimized + debuginfo] target(s) in 0.42s
     Running `target/debug/reth-bug`
[src/main.rs:24] &tx.hash() = 0x4ebd87bd156d95ccfd256b9e63badb6b6c368685f9ef9dac4595fc7b4059150b
thread 'main' panicked at /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/8667c33/crates/primitives/src/receipt.rs:19:1:
Failed to decompress: Src size is incorrect
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9a66e4471f71283fd54d80ef8147630d34756332/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9a66e4471f71283fd54d80ef8147630d34756332/library/core/src/panicking.rs:72:14
   2: <reth_primitives::receipt::Receipt as reth_codecs::Compact>::from_compact::{{closure}}
             at /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/8667c33/crates/primitives/src/receipt.rs:19:1
   3: std::thread::local::LocalKey<T>::try_with
             at /rustc/9a66e4471f71283fd54d80ef8147630d34756332/library/std/src/thread/local.rs:270:16
   4: std::thread::local::LocalKey<T>::with
             at /rustc/9a66e4471f71283fd54d80ef8147630d34756332/library/std/src/thread/local.rs:246:9
   5: <reth_primitives::receipt::Receipt as reth_codecs::Compact>::from_compact
             at /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/8667c33/crates/primitives/src/receipt.rs:19:1
   6: reth_db::tables::codecs::compact::<impl reth_db::abstraction::table::Decompress for reth_primitives::receipt::Receipt>::decompress
             at /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/8667c33/crates/storage/db/src/tables/codecs/compact.rs:25:36
   7: reth_db::tables::utils::decode_one
             at /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/8667c33/crates/storage/db/src/tables/utils.rs:81:29
   8: core::ops::function::FnOnce::call_once
             at /rustc/9a66e4471f71283fd54d80ef8147630d34756332/library/core/src/ops/function.rs:250:5
   9: core::option::Option<T>::map
             at /rustc/9a66e4471f71283fd54d80ef8147630d34756332/library/core/src/option.rs:1072:29
  10: <reth_db::implementation::mdbx::tx::Tx<K> as reth_db::abstraction::transaction::DbTx>::get::{{closure}}
             at /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/8667c33/crates/storage/db/src/implementation/mdbx/tx.rs:228:13
  11: reth_db::implementation::mdbx::tx::Tx<K>::execute_with_operation_metric
             at /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/8667c33/crates/storage/db/src/implementation/mdbx/tx.rs:140:13
  12: <reth_db::implementation::mdbx::tx::Tx<K> as reth_db::abstraction::transaction::DbTx>::get
             at /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/8667c33/crates/storage/db/src/implementation/mdbx/tx.rs:227:9
  13: <reth_provider::providers::database::provider::DatabaseProvider<TX> as reth_provider::traits::receipts::ReceiptProvider>::receipt
             at /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/8667c33/crates/storage/provider/src/providers/database/provider.rs:1430:12
  14: <reth_provider::providers::database::provider::DatabaseProvider<TX> as reth_provider::traits::receipts::ReceiptProvider>::receipt_by_hash
             at /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/8667c33/crates/storage/provider/src/providers/database/provider.rs:1435:13
  15: reth_bug::main
             at ./src/main.rs:27:19
  16: core::ops::function::FnOnce::call_once
             at /rustc/9a66e4471f71283fd54d80ef8147630d34756332/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

  </code></pre>
</details>

### Steps to reproduce

Reproducible setup: https://github.com/naps62/reth-bug
(it's hardcoded to sepolia network, and queries a hardcoded txhash)

the code is hardcoded to use Sepolia network, and a hardcode txhash from a recent block. these settings can be changed directly in `main.rs`

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.11 Commit SHA: e5b33dbe Build Timestamp: 2023-11-26T21:46:56.501304989Z Build Features: default,jemalloc Build Profile: release

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

None

### What prune config do you use, if any?

empty (full archival node)

### If you've built Reth from source, provide the full command you used

cargo install --locked --path bin/reth --bin reth

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
ptal @joshieDo this looks like a decrompress error in receipts

https://github.com/paradigmxyz/reth/blob/02e4135bb41c5fc58a600714ecb04934ec88e707/crates/primitives/src/receipt.rs#L19-L19

**Comment by naps62** [comment]
@mattsse update: seems the cause was the fact that I was using `features = ["optimism"]` while targeting a sepolia node.

I'm not sure if this is intended though. feature flags should be additive in principle right? not sure if that principle is supposed to apply here


**Now, why did I originally added this flag?**

It's no longer a problem after I extracted to a separate repo, but right now, trying to add reth dependencies **without optimism** to a codebase that also didn't use optimism in any way, but depends on `revm`, `forge` among others, causes this:
```
error[E0063]: missing field `optimism` in initializer of `TxEnv`
   --> /home/naps62/.cargo/git/checkouts/reth-36d3ea1d1152b20c/07265d9/crates/primitives/src/revm/env.rs:168:14
    |
168 |     env.tx = TxEnv {
    |              ^^^^^ missing `optimism`
```

this can be reproduced by just `cargo build` on [this branch](https://github.com/iron-wallet/iron/tree/reth-op)
