### ISSUE TITLE
Add new helper trait for Network to get access to TransactionsHandle

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5598]
### Describe the feature

The `TransactionsHandle` provides useful functions to interact with the network:

https://github.com/paradigmxyz/reth/blob/503c4010d3c8b5df36a24e75cd4087eb4cf16640/crates/net/network/src/transactions.rs#L72-L72

It would be useful to get a `TransactionsHandle` directly from the 

https://github.com/paradigmxyz/reth/blob/503c4010d3c8b5df36a24e75cd4087eb4cf16640/crates/net/network/src/network.rs#L37-L37

## TODO

* add new helper trait: `EthNetwork` that provides a function to access the `TransactionsHandle`. This should be solved by adding a `Mutex<Option<TransactionHandle>>` to the NetworkInner https://github.com/paradigmxyz/reth/blob/503c4010d3c8b5df36a24e75cd4087eb4cf16640/crates/net/network/src/network.rs#L324-L324
so it can be set once the transactionmanager is installed:

https://github.com/paradigmxyz/reth/blob/503c4010d3c8b5df36a24e75cd4087eb4cf16640/crates/net/network/src/manager.rs#L135-L135

see for example:

https://github.com/paradigmxyz/reth/blob/503c4010d3c8b5df36a24e75cd4087eb4cf16640/crates/net/network/src/builder.rs#L59-L62

then we can also move these functions to the trait:

https://github.com/paradigmxyz/reth/blob/503c4010d3c8b5df36a24e75cd4087eb4cf16640/crates/net/network/src/network.rs#L119-L135

**Comment by DoTheBestToGetTheBest** [comment]
happy to take this :) ty for all this details !

**Comment by i-m-aditya** [comment]
@DoTheBestToGetTheBest I have already created a PR, so if you haven't started, let me know :)

**Comment by DoTheBestToGetTheBest** [comment]
> @DoTheBestToGetTheBest I have already created a PR, so if you haven't started, let me know :)

i still didn't started working on this but this is my issue so i will work on it, thanks

**Comment by i-m-aditya** [comment]
@mattsse Absolutely, let's keep the good vibes going! 😄

**Comment by daniel-huertas** [comment]
I'm eager to try this challenge !

**Comment by DoTheBestToGetTheBest** [comment]
> I'm eager to try this challenge !

please choose another thing, this is my issue, i will work on it when i'am free :)

i don't not abandon this :)

ty for your understand

**Comment by mattsse** [comment]
@DoTheBestToGetTheBest are you still on this?

**Comment by DoTheBestToGetTheBest** [comment]
> @DoTheBestToGetTheBest are you still on this?

i was going to work on it last week but since i can't use reth for not ( related with this https://github.com/paradigmxyz/reth/issues/6258 ) i'm unable to work on this until fix 

probably someone should work on it i don't know how much time it would except for fixing CD

**Comment by DoTheBestToGetTheBest** [comment]
@i-m-aditya @daniel-huertas hey feel free to take this if you want, i'm unable to work with reth for the moment until fix

**Comment by qiweiii** [comment]
I can try to work on this, but please don't assign me, if I can do it, there will be a PR in 24 hrs
