### ISSUE TITLE
I will use cargo test --workspace build error

### ISSUE THREAD

**Issue by shangsony** [paradigmxyz/reth#5607]
### Describe the bug

eth/target/debug/deps/reth_rpc-f8a899eb9de84f51" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: collect2: fatal error: ld terminated with signal 9 [Killed]
          compilation terminated.

error: could not compile `reth-rpc` (lib test) due to previous error
warning: build failed, waiting for other jobs to finish...

### Steps to reproduce

eth/target/debug/deps/reth_rpc-f8a899eb9de84f51" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: collect2: fatal error: ld terminated with signal 9 [Killed]
          compilation terminated.

error: could not compile `reth-rpc` (lib test) due to previous error
warning: build failed, waiting for other jobs to finish...

### Platform(s)

Linux (x86)

### What database version are you on?

![FNEpEgZCZM](https://github.com/paradigmxyz/reth/assets/19890858/38c27987-99c4-4c57-9e2e-5250748c5c5c)

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
Cannot reproduce, so it is likely an issue with your linker or host system. Please try to reinstall your build tools

Tested on Arch
