### ISSUE TITLE
Add command for querying info of connected peers

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#564]
### Describe the feature

Add a new command+function for querying Peer info, mainly to provide

https://geth.ethereum.org/docs/rpc/ns-admin#admin_peers

**Comment by ayushm2003** [comment]
Hey, I would like to take this up. Where should this new function be placed?

**Comment by mattsse** [comment]
awesome, we need a couple of things.

- [ ] a new public `PeerInfo` type that includes the relevant info, the type doesn't need to follow this model 1:1 but should use the things we already have here: 


https://github.com/paradigmxyz/reth/blob/c9958a4d13be69977032e306021de71584d08757/crates/net/network/src/session/handle.rs#L37-L50


```text
{
    caps: ["eth/61", "eth/62", "eth/63"],
    id: "08a6b39263470c78d3e4f58e3c997cd2e7af623afce64656cfc56480babcea7a9138f3d09d7b9879344c2d2e457679e3655d4b56eaff5fd4fd7f147bdb045124",
    name: "Geth/v1.5.0-unstable/linux/go1.5.1",
    network: {
      localAddress: "192.168.0.104:51068",
      remoteAddress: "71.62.31.72:30303"
    },
    protocols: {
      eth: {
        difficulty: 17334052235346465000,
        head: "5794b768dae6c6ee5366e6ca7662bdff2882576e09609bf778633e470e0e7852",
        version: 63
      }
    }
}
```

- [ ] then we need another command variant here

https://github.com/paradigmxyz/reth/blob/c9958a4d13be69977032e306021de71584d08757/crates/net/network/src/network.rs#L188

which will be handled by the `NetworkManager` which then asks the `SessionManager` to return all `PeerStatus` from here:

https://github.com/paradigmxyz/reth/blob/c9958a4d13be69977032e306021de71584d08757/crates/net/network/src/session/mod.rs#L79

**Comment by ayushm2003** [comment]
Hey, I opened the draft pr. Wanted to know if I'm moving in the right direction.

`ActiveSessionHandle` is not backward compatible in the pr atm due to the new fields.
