### ISSUE TITLE
Support for OP/Base Sepolia

### ISSUE THREAD

**Issue by quickchase** [paradigmxyz/reth#5653]
### Describe the feature

Can you add `op_sepolia` and `base_sepolia` to the list of built in supported chains?

### Additional context

Both Optimism and Base have Sepolia testnets and Goerli is "EoL"

**Comment by mattsse** [comment]
@clabby I believe this is already the case?

**Comment by clabby** [comment]
Support is there, but built-in chainspecs are not.

**Comment by clabby** [comment]
For anyone that may take up this issue, genesis files can be found within the [`superchain-registry`](https://github.com/ethereum-optimism/superchain-registry/tree/main/superchain/extra/genesis/sepolia)

**Comment by yash-atreya** [comment]
@clabby @mattsse Willing to take this up. Just need some guidance on where I should add the ChainSpecs. If you could guide me on where the current op/base mainnet specs are implemented, I'll just follow that implementation.

**Comment by Chomtana** [comment]
Hi @mattsse , I have added base sepolia support on pull request #5697 

It would be very pleasure if you can review that

Sorry for frontrunning @yash-atreya as I need to sync base sepolia node to be sync asap
