### ISSUE TITLE
Support reorged logs in eth_Logs subscriptions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5677]
### Describe the feature

eth_filter is poll based (`http` request to get new entries)

The way this works is, on `filter_changes` we take the filter and calculate the new matching block range

https://github.com/paradigmxyz/reth/blob/6f7d6d50160e0dbb84de5b74f9794e14cc04406b/crates/rpc/rpc/src/eth/filter.rs#L132-L132

then query the new block range:

https://github.com/paradigmxyz/reth/blob/6f7d6d50160e0dbb84de5b74f9794e14cc04406b/crates/rpc/rpc/src/eth/filter.rs#L193-L193

This currently doesn't include reorged blocks, which should be sent again with `removed` field

https://github.com/paradigmxyz/reth/blob/6f7d6d50160e0dbb84de5b74f9794e14cc04406b/crates/rpc/rpc/src/eth/filter.rs#L471-L471

what we need is a way to store reorged blocks and check if the filter previously sent any logs belonging to a reorged block.

hence we need to store not only the block number but also the block hash in the filter:

https://github.com/paradigmxyz/reth/blob/6f7d6d50160e0dbb84de5b74f9794e14cc04406b/crates/rpc/rpc/src/eth/filter.rs#L550-L551

then we need a cache that stores a few recently reorged blocks so we can check if the filter previously served any reorged logs.
This can be solved in multiple ways.
perhaps the easiest and most performant solution is to monitor reorged blocks and then update the impacted filters:

1. new task that reacts to reorged blocks:
2. check impacted log filters
3. store necessary data in the flog filter

for reference how to get a stream of block events:

https://github.com/paradigmxyz/reth/blob/6f7d6d50160e0dbb84de5b74f9794e14cc04406b/crates/rpc/rpc/src/eth/pubsub.rs#L156-L158

the new task should take a clone of `EthFilter` and then acquire active filters and check if they need to be updated:
https://github.com/paradigmxyz/reth/blob/6f7d6d50160e0dbb84de5b74f9794e14cc04406b/crates/rpc/rpc/src/eth/filter.rs#L325-L326
an active log filter: 
https://github.com/paradigmxyz/reth/blob/6f7d6d50160e0dbb84de5b74f9794e14cc04406b/crates/rpc/rpc/src/eth/filter.rs#L650-L650
then can have something like `Arc<Mutex<Option<Vec<Logs>>>` where matching reorged logs are stored which are checked when the filter is polled.

**Comment by mattsse** [comment]
I believe @leontiadZen is already on this one, just forgot to assign -.-

do you want to take #5680 instead?

**Comment by Arindam2407** [comment]
> I believe @leontiadZen is already on this one, just forgot to assign -.-
> 
> do you want to take #5680 instead?

Yes, sure

**Comment by mattsse** [comment]
ref #2380
