### ISSUE TITLE
Use lazy JsObjects for JS tracing

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5679]
### Describe the feature

Currently we create new JsObjects on demand during JS tracing:

for example for step:

https://github.com/paradigmxyz/reth/blob/main/crates/revm/revm-inspectors/src/tracing/js/mod.rs#L216-L223

profiling showed, creating new JsObjects is very expensive.

Instead, we want a solution that utilizes  existing JsObjects so we only have to create them once and clone them instead with updated state 

This needs a bit more investigation how geth js tracing behaves if the input objects are stored in js trace object's context

**Comment by Arindam2407** [comment]
Can I take this?

**Comment by mattsse** [comment]
yes!
this is a bit tricky though, we likely need to use same `Rc` and shared mutability hacks here.
if you need some pointers/questions lmk by opening a draft PR

**Comment by Arindam2407** [comment]
revm-inspector seems to have been removed from the repo
