### ISSUE TITLE
Improve eth_getLogs performance for latest block 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5680]
### Describe the feature

Currently we're computing the range of matching blocks of a log filter:

https://github.com/paradigmxyz/reth/blob/f15e87825061a7bf11c1eb685a5cf7815652a3ec/crates/rpc/rpc/src/eth/filter.rs#L173-L181

and then request that range:

https://github.com/paradigmxyz/reth/blob/f15e87825061a7bf11c1eb685a5cf7815652a3ec/crates/rpc/rpc/src/eth/filter.rs#L442-L447

this is very inefficient for filters such as `[latest,latest]` which are only interested in the  latest blocks, because this range query always hits the disk when the data is always cached (EthStateCache).

so we should improve this
check the range arguments https://github.com/paradigmxyz/reth/blob/f15e87825061a7bf11c1eb685a5cf7815652a3ec/crates/rpc/rpc/src/eth/filter.rs#L423-L428
if this is a single block and Filter's upperbound is `Latest` use the  state cache to fetch the block's data

like we do for the block hash variant:

https://github.com/paradigmxyz/reth/blob/f15e87825061a7bf11c1eb685a5cf7815652a3ec/crates/rpc/rpc/src/eth/filter.rs#L351-L356

The `get_logs_in_block_range` function argument likely needs additional info now (for the currently latest block):

https://github.com/paradigmxyz/reth/blob/f15e87825061a7bf11c1eb685a5cf7815652a3ec/crates/rpc/rpc/src/eth/filter.rs#L133-L134

cc @Arindam2407

**Comment by mattsse** [comment]
@Arindam2407 what we should do here is implement multiple functions that fetch the range:

1. via the existing loop over `BlockRangeInclusiveIter`
2. single call to cache if range is one block
3. multiple calls to cache if `from..=to` is smaller than x blocks (perhaps 10) and their distance from `latest` is lower than the ethcache's targeted cache range

**Comment by leontiad** [comment]
So the cache calls should be there only in those cases:

1. from==to==latest
2. from-to<= threshold and  |latest-(from-to)|<=ethcache-range,

Where is that ethcache-range  defined?

**Comment by mattsse** [comment]
yes, because we assume here that the targeted block is still cached if it's near the tip.

I think we can use max_blocks or `max_blocks / 2` as a cutoff

**Comment by mattsse** [comment]
@Arindam2407 turns out @leontiad started working on this already
so feel free to continue with #5677, sorry about the confusion

**Comment by yash-atreya** [comment]
@mattsse I can take this and #5677 if @leontiad and @Arindam2407 decide to discontinue working.

**Comment by leontiad** [comment]
I am on that - opening a WIP PR

**Comment by allnil** [comment]
take a look

**Comment by leontiad** [comment]
Can't push my branch, am I authed to do that? @mattsse

**Comment by allnil** [comment]
@leontiad 
Hi Iraklis! I think you cloned reth repo but...you need make a fork, make branch in your forked reth and than you will be able to open merge request which appeared in this repo :)
hope it helps!

**Comment by leontiad** [comment]
> @leontiad Hi Iraklis! I think you cloned reth repo but...you need make a fork, make branch in your forked reth and than you will be able to open merge request which appeared in this repo :) hope it helps!

Thanks!That make it work!

**Comment by sambacha** [comment]
just wanting some clarification, this `latest` is really an alias for `unsafe` correct?   
  
`unsafe` being "The most recent block in the canonical chain observed by the client this block can be re-orged out of the canonical chain"  
  
  
Also @mattsse would you be open to adding `blockTimestamp` as part of the logs object returned by `eth_getLogs[^1]`

\[^1\]: \[See this proposal on ethereum magicians forums regarding adding blockTimestamp to eth\_getLogs\](https://ethereum-magicians.org/t/proposal-for-adding-blocktimestamp-to-logs-object-returned-by-eth-getlogs-and-related-requests/11183/2)

**Comment by mattsse** [comment]
> unsafe being "The most recent block in the canonical chain observed by the client this block can be re-orged out of the canonical chain"

yeah latest is the highest canonical block processed by the chain
