### ISSUE TITLE
javascript debug_traceTransaction not fully compatible with geth

### ISSUE THREAD

**Issue by drortirosh** [paradigmxyz/reth#5684]
### Describe the bug

when using javascript "tracer", the output is not fully compatible with geth.
Running the following script against a local GETH generates:
`["setup","PUSH1","PUSH1","MSTORE","PUSH1","DUP1","DUP2","DUP3","DUP4","DUP5","GAS","DUP7","CALL","enter","exit","POP","POP","PUSH1","DUP1","PUSH1","PUSH1","CODECOPY","PUSH1","RETURN"]`
but against RETH:
`["setup","enter","PUSH1","PUSH1","MSTORE","PUSH1","DUP1","DUP2","DUP3","DUP4","DUP5","GAS","DUP7","CALL","enter","exit","POP","POP","PUSH1","DUP1","PUSH1","PUSH1","CODECOPY","PUSH1","RETURN","exit"]`

The opcodes (calls to "step") are the same, but the "enter/leave" method calls differ

(and tiny ux bug: it reports: "trace object must expose a function result()" even when the result method  exist, and the "fault" method is missing.... it is better than geth's reporting (which is just "tracer not found"), but still confusing

### Steps to reproduce

1. start local RETH (or GETH)
2. run the following script:
```
#!/bin/bash 
#data is minimal calldata that calls a function (from constructor calls address(0))
cat > asd1.sol <<EOF
pragma solidity ^0.8.10;
//SPDX-License-Identifier: MIT

contract Asd {

  constructor() payable {
    assembly {
      pop(call(0,gas(),0,0,0,0,0))
    }
  }

  fallback() external payable {
    // address(0).call("");
  }
}
EOF

data=`solc asd1.sol --optimize --metadata-hash none --bin|grep 6080`

tracer=`cat <<EOF
{ 
  ret: [],
  setup: function() {this.ret.push('setup')},
  enter: function() {this.ret.push('enter')},
  exit: function() {this.ret.push('exit')},
  fault: function() {this.ret.push('fault')},
  step: function (log) {this.ret.push(log.op.toString())},
  result: function() { return this.ret; } }
EOF
`
options=`cat <<EOF
{ "tracer": "$tracer" }
EOF
`

params=`cat <<EOF
[
  { "data":"0x$data"},
  "latest",
  $options
]
EOF
`
echo $params | cast rpc debug_traceCall --raw 
```

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
ty for this!

looks like we're including additional `"enter"` and `exit` for the root call.

checking

> (and tiny ux bug: it reports: "trace object must expose a function result()" even when the result method exist, and the "fault" method is missing.... it is better than geth's reporting (which is just "tracer not found"), but still confusing

right, improving this

**Comment by drortirosh** [comment]
> 
> looks like we're including additional `"enter"` and `exit` for the root call.
>

Thanks.
But please add more tests. I only brought this sample because it is simple.
The real flow that gets broken is in erc4337 bundler validation

**Comment by mattsse** [comment]
working on better rpc/e2e testing tooling for rpc as we speak
