### ISSUE TITLE
Implement Activation Block Data for Ethereum Hardforks

### ISSUE THREAD

**Issue by DoTheBestToGetTheBest** [paradigmxyz/reth#5707]
### Describe the feature

Create a function in the Hardfork enum to return activation block numbers for Ethereum hardforks, 

```rust
pub fn activation_block(&self) -> Option<u64> {}
```
Documentation about block number activation : https://ethereum.github.io/execution-specs/autoapi/index.html

Part code : https://github.com/paradigmxyz/reth/blob/main/crates/ethereum-forks/src/hardfork.rs

**Comment by DoTheBestToGetTheBest** [comment]
Hey it's possible to add Good First Issue for this one ? :)

**Comment by mattsse** [comment]
related:

https://github.com/foundry-rs/foundry/issues/6440

this function should take `Chain` as an argument and return the known activation block

**Comment by DoTheBestToGetTheBest** [comment]
> related:
> 
> [foundry-rs/foundry#6440](https://github.com/foundry-rs/foundry/issues/6440)
> 
> this function should take `Chain` as an argument and return the known activation block

i would like to give this for another person if you are okay :)

**Comment by supernovahs** [comment]
I can take this

**Comment by supernovahs** [comment]
I can take this

**Comment by 1010adigupta** [comment]
Hey @mattsse you can assign me this, ig #5723 aimed to solve this but was unable due to circular dependencies which can be tackled if we switched to alloy-chains instead reth-primitive implementation, I am currently working on #5429, hence will see this issue as well simultaneously.
