### ISSUE TITLE
EVM error StackUnderflow

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [paradigmxyz/reth#5711]
### Describe the bug

I'm running Reth in auto sealer mode on a custom chain within a container. Docker compose setup below
Using remix to compile and deploy contracts.
All my attempts to deploy a contract hit EVM error StackUnderflow. 

When I run Reth without a container I have no issues. So it must be a volume getting corrupted somewhere. I have this problem on both my local dev PC and a beefy cloud machine ( I don't think resources or machine architecture is the issue)

Other notes:
*  EOAs work fine.
* I ran the mbdx checker inside the container and it reported no issues. 
* I have the same issue running in dev mode

```yml
version: '3.7'

volumes:
  reth:
    driver: local

  node:
    image: {image}
    pull_policy: always
    container_name: node
    command:
      [
        '/usr/local/bin/reth',
        'node',
        '--chain',
        'botanix_testnet',
        '--datadir',
        '/reth/botanix_testnet',
        '--http',
        '--http.corsdomain',
        '*',
        '--http.port',
        '8545',
        '--http.addr',
        '0.0.0.0',
        '--http.api',
        'admin,debug,eth,net,trace,txpool,web3,rpc',
        '-vvv',
        '--auto-mine',
        '--disable-discovery',
      ]
    ports:
      - '30303:30303'
      - '9001:9001'
      - '8545:8545'
      - '8546:8546'
    volumes:
      - reth:/reth/botanix_testnet/db

```

### Steps to reproduce

1. Run reth in docker compose with --dev
2. Try and deploy and contract using remix ide

### Node logs

```text
Nothing applicable. Contract deployments go on chain but with status 0x0.
Getting the fee estimation of a contract deployment results in an `EVM error StackUnderflow`.
```

### Platform(s)

Linux (x86)

### What database version are you on?

Current database version: 1                                                                                                                                                                     
Local database version: 1

### What type of node are you running?

None

### What prune config do you use, if any?

N/A

### If you've built Reth from source, provide the full command you used

Build using Docker 

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by rakita** [comment]
StackUnderflow is logical bytecode error not a client/reth error, so it is unlikely this is reth related expecially when it is working without container

**Comment by 0xBEEFCAF3** [comment]
I was on a really old version from Sept. 2023. I rebased some of my changes no longer get the error.
