### ISSUE TITLE
eth_syncing RPC call returns nullish

### ISSUE THREAD

**Issue by rarecrumb** [paradigmxyz/reth#5713]
### Describe the bug

When reth is syncing, making a call to the RPC endpoint for `eth_syncing` returns a nullish response:

```json
{"jsonrpc":"2.0","result":{"startingBlock":"0x0","currentBlock":"0x0","highestBlock":"0x0","warpChunksAmount":null,"warpChunksProcessed":null},"id":1}
```

### Steps to reproduce

- Start reth
- Execute an HTTP request: `curl -s -X POST --header 'Content-Type: application/json' http://localhost:8545 --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'`
- Get a "bad" response

### Platform(s)

Linux (ARM)

### What version/commit are you on?

v0.1.0-alpha.13

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

I would expect the call to return `syncing: true, highest_block: ...` or something similar.

**Comment by onbjerg** [comment]
This is the correct behaviour
