### ISSUE TITLE
eth_getTransactionReceipt returns empty result for some transactions

### ISSUE THREAD

**Issue by JakkuSakura** [paradigmxyz/reth#5717]
### Describe the bug

I'm developing a product that scans all blocks and transactions. However, for some blocks, I observed a lot of empty transaction receipts in old blocks.
For example, I got an empty result from reth
```bash
curl http://localhost:8545/ \
  -X POST  \
  -H "Content-Type: application/json"  \
  --data '{"method":"eth_getTransactionReceipt","params":["0xb5bf9e2e13aadb921b06202d4c9dab146fb015b77ff7e292c8d80a378802c56f"],"id":1,"jsonrpc":"2.0"}'
```
```json
{"jsonrpc":"2.0","result":null,"id":1}
```
But with a public node
```bash
curl https://docs-demo.quiknode.pro/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getTransactionReceipt","params":["0xb5bf9e2e13aadb921b06202d4c9dab146fb015b77ff7e292c8d80a378802c56f"],"id":1,"jsonrpc":"2.0"}'
```
I got the following
```json
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x60da43f0613bb7a12c4a2d56454f2f2bc156d1cf69b045c4d24e1783a3e3a0cb","blockNumber":"0x11af333","contractAddress":"0x0a3340129816a86b62b7eafd61427f743c315ef8","cumulativeGasUsed":"0x80af6a","effectiveGasPrice":"0x10696bb4f3","from":"0xc1f2b71a502b551a65eee9c96318afdd5fd439fa","gasUsed":"0x80af6a","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","status":"0x1","to":null,"transactionHash":"0xb5bf9e2e13aadb921b06202d4c9dab146fb015b77ff7e292c8d80a378802c56f","transactionIndex":"0x0","type":"0x2"}}
```

### Steps to reproduce

```bash
curl http://localhost:8545/ \
  -X POST  \
  -H "Content-Type: application/json"  \
  --data '{"method":"eth_getTransactionReceipt","params":["0xb5bf9e2e13aadb921b06202d4c9dab146fb015b77ff7e292c8d80a378802c56f"],"id":1,"jsonrpc":"2.0"}'
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.10 Commit SHA: 460b5f6f Build Timestamp: 2023-11-16T16:31:23.836829400Z Build Features: default,jemalloc Build Profile: release

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Full via --full flag

### What prune config do you use, if any?

No

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by yash-atreya** [comment]
If you want to scan all blocks and transactions, you should run an archive node for that

You're running a full node currently which doesn't store all history

**Comment by JakkuSakura** [comment]
To me the full mode is kind misleading, like everything in the history but it's not

**Comment by JakkuSakura** [comment]
Is there a way to convert a full node to an archive node? Just chancing CLI parameter doesn't sync previous transaction receipts

**Comment by rkrasiuk** [comment]
@JakkuSakura not at the moment, you would have to resync the node. re full vs archival node, geth has a great page explaining both https://geth.ethereum.org/docs/fundamentals/sync-modes. i can see tho how "full node" term might get confusing

**Comment by shekhirin** [comment]
@JakkuSakura also check out our book page about pruning: https://paradigmxyz.github.io/reth/run/pruning.html
