### ISSUE TITLE
Arcify EthStateCache

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5720]
### Describe the feature

Currently retrieving blocks/receipts from the cache involves cloning.

Mostly we only need to convert the data to json or fill the evm env for tracing.

Hence, we should store Blocks receipts in Arcs and send Arc clones

**Comment by i-m-aditya** [comment]
Will pick this.

**Comment by mattsse** [comment]
@i-m-aditya let's do this is multiple steps, starting with receipts, this should be less invasive

**Comment by supernovahs** [comment]
Can be closed

**Comment by Rjected** [comment]
Yep, closing
