### ISSUE TITLE
Invalid: Unchecked Transaction Exceeds MAX_CODE_SIZE Limit

### ISSUE THREAD

**Issue by hsyodyssey** [paradigmxyz/reth#5722]
### Describe the bug

We know that for a number of historical reasons, rule checking at the Ethereum execution layer is complex and cumbersome. For example, `MAX_CODE_SIZE `is replaced by `MAX_INIT_CODE_SIZE ` only after enabling [EIP-3860](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md). 

Therefore, without enabling eip-3860, the bytecode should not exceed the size of MAX_CODE_SIZE. In fact, Geth does the MAX_CODE_SIZE check in an obscure place, [here](https://github.com/ethereum/go-ethereum/blob/e206d3f8975bd98cc86d14055dca40f996bacc60/core/vm/evm.go#L469-L472).

But Reth doesn't seem to be checking the size of the bytecode for such transactions. I only found the checking logic [here ](https://github.com/paradigmxyz/reth/blob/main/crates/transaction-pool/src/validate/eth.rs#L214-L219) after Shanghai.

Actually adding this section wasn't that difficult, but it required some higher level design, such if managing so many Ethereum rules. I'm trying to build nodes for some other ethereum compatible chains by using Reth. Not all EVMs will be compatible with Shanghai upgrades, so found this out.

### Steps to reproduce

Run reth on a private env

### Platform(s)

Linux (x86), Windows (x86)

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> Geth does the MAX_CODE_SIZE check in an obscure place, [here](https://github.com/ethereum/go-ethereum/blob/e206d3f8975bd98cc86d14055dca40f996bacc60/core/vm/evm.go#L469-L472).

this is in the evm, the right location where this check should be.

> But Reth doesn't seem to be checking the size of the bytecode for such transactions.
this is also checked in the evm

> Therefore, without enabling eip-3860, the bytecode should not exceed the size of MAX_CODE_SIZE.

this is correct, though prior eip-3860 there's no protocol enforced upper bound for the size. 

Not exactly sure what you're asking for here

**Comment by hsyodyssey** [comment]
sry, I'll rephrase it. In Geth, the check on bytecode is in fact performed twice, once [here](https://github.com/ethereum/go-ethereum/blob/e206d3f8975bd98cc86d14055dca40f996bacc60/core/txpool/validation.go#L69-L71)(eip-3860 checking in txpool part) and once [here](https://github.com/ethereum/go-ethereum/blob/e206d3f8975bd98cc86d14055dca40f996bacc60/core/vm/evm.go#L469-L472)(the old rules in evm part). In reth, I only found [one](https://github.com/paradigmxyz/reth/blob/main/crates/transaction-pool/src/validate/eth.rs#L214-L219) checking logic(about after the Shanghai upgrade one), and it seems to be missing the old rule checking(before enabling eip-3860). 

Some EVM-compatible chains, including some L2 Sequencers don't have enable Shanghai upgrades, so there seems to be some rules management mismatch here.

Imagine if a network exists with both reth and geth nodes, some legitimate transactions here on reth may be invalid on the geth nodes because they exceed the bytecode limit. Of course, this is no problem on the main ethereum network, which reth does extremely well.

**Comment by mattsse** [comment]
> it seems to be missing the old rule checking

which one do you mean?

> some legitimate transactions here on reth may be invalid on the geth nodes because they exceed the bytecode limit

can you elaborate here?

or rather specifically, which geth check are we currently missing?

**Comment by hsyodyssey** [comment]
> or rather specifically, which geth check are we currently missing?

whether CodeSize > MAX_CODE_SIZE when not enabling eip-3860.

**Comment by mattsse** [comment]
analyzing bytecode is not really feasible here, hence there's no constant check for code size I assume

> and it seems to be missing the old rule checking

**Comment by hsyodyssey** [comment]
Yes, but I did not find this part of the rule check in the revm part either?

**Comment by mattsse** [comment]
it's here:

https://github.com/bluealloy/revm/blob/5a47ae0d2bb0909cc70d1b8ae2b6fc721ab1ca7d/crates/revm/src/evm_context.rs#L384-L396

**Comment by hsyodyssey** [comment]
> it's here:
> 
> https://github.com/bluealloy/revm/blob/5a47ae0d2bb0909cc70d1b8ae2b6fc721ab1ca7d/crates/revm/src/evm_context.rs#L384-L396

Oh thank you sir! I thought the logic for that part would be in the reth codebase somewhere! That should be fine then, thanks for your work. I'll look into revm repo.
