### ISSUE TITLE
Structured (JSON) logging for reth

### ISSUE THREAD

**Issue by 0x416e746f6e** [paradigmxyz/reth#5726]
### Describe the feature

It would be great if reth could be configured to emit logs in structured (json) format.

**Comment by mattsse** [comment]
this can be done here:

https://github.com/paradigmxyz/reth/blob/829d3ede65a792fb26f2b5d513265bb4fd59425a/crates/tracing/src/lib.rs#L39-L49

I think we want something like `geth's`

 --log.format value            
          Log format to use (json|logfmt|terminal)

option here:

https://github.com/paradigmxyz/reth/blob/829d3ede65a792fb26f2b5d513265bb4fd59425a/bin/reth/src/cli/mod.rs#L178-L181

wdyt @shekhirin

**Comment by shekhirin** [comment]
@mattsse that sounds good, I also think we need to separate the log format and filters for stdout, journald and file log.

Currently, filters are already separated, but there's no way to define the filters specifically for stdout (after https://github.com/paradigmxyz/reth/pull/5735, `RUST_LOG` is applied to all log outputs). So it would makes sense for me to add a common struct with `filter` and `format` fields that can be re-used for stdout, journald and file log arguments.

**Comment by mattsse** [comment]
assigned:

relevant: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Format.html#method.json

**Comment by loocapro** [comment]
> I think we want something like `geth's`
> 
> --log.format value Log format to use (json|logfmt|terminal)

@mattsse,

`log.format logfmt`: can I use: https://docs.rs/tracing-logfmt/latest/tracing_logfmt/?

**Comment by mattsse** [comment]
I think so
