### ISSUE TITLE
Can I convert a full node to archive node, or vise versa?

### ISSUE THREAD

**Issue by JakkuSakura** [paradigmxyz/reth#5727]
### Describe the feature

In the previous issue, I was told that archive won't save the whole history of the blockchain. However, I already have a full node. Changing CLI parameter to archive does not sync the history. Deleting them requires duplicate downloads and down time, which I don't want.
Is there a way to sync historical transactions or prune them?

**Comment by gakonst** [comment]
This is a good Q which we should add to the book. You can technically do Archive -> Full but not vice versa, so you'll need to resync there from scratch (you can also just `drop-stage execution` and re-execute). Do you want to open a PR to the book for this?
