### ISSUE TITLE
Include raw revert reason in debug_ traces

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5737]
### Describe the feature

currently we're returning a `revert:` prefixed error

<img width="981" alt="image" src="https://github.com/paradigmxyz/reth/assets/19890894/a4c2bba9-2503-40a8-8ae9-384042027a7a">

needs https://github.com/alloy-rs/core/issues/449 first
then we need the use the `reason` without the prefix here:

https://github.com/paradigmxyz/reth/blob/829d3ede65a792fb26f2b5d513265bb4fd59425a/crates/revm/revm-inspectors/src/tracing/types.rs#L350-L350

**Comment by peyha** [comment]
I'd be happy to handle this one

**Comment by peyha** [comment]
Should this issue be dropped after [this](https://github.com/alloy-rs/core/pull/457) ?

**Comment by mattsse** [comment]
no this is still they case but we can now make this work by using the new `RevertReason` struct

**Comment by supernovahs** [comment]
Can be closed i think
