### ISSUE TITLE
Split `reth-primitives` and support `no_std` compilation.

### ISSUE THREAD

**Issue by yjhmelody** [paradigmxyz/reth#5746]
### Describe the feature

I noticed that reth-primitives can be used by the rust eth ecosystem and even supports no_std compilation. Is there any plan to support splitting this crate into several crates? I could help to improve this.

**Comment by mattsse** [comment]
yes we want to slim that down ref #5524 

I think next thing would be removing chainspec + genesis stuff

**Comment by eyusufatik** [comment]
Hey, is this still in the roadmap?

We at Citrea would really love this feature :)

**Comment by mattsse** [comment]
definitely,
I assume you're mostly interested in the tx types?
or something else?

**Comment by eyusufatik** [comment]
> definitely, I assume you're mostly interested in the tx types? or something else?

tx types, receipt. some primitive types such as B256, some constants and some errors.

we want to use reth-primitives inside risc0 zkvm and until know it looks like only reason we can't compile it to risc0 zkvm is `sucds` and `zstd` packages.

I'm up to implement this btw. Ofc we should discuss how beforehand :)

**Comment by mattsse** [comment]
makes sense, definitely something we want to support, will gather some input for #7050 which would allow us to move off from zstd and non_std stuff,

will discuss internally how to cleanup reth-primitives because it's gotten a bit bloated
