### ISSUE TITLE
eth_estimateGasBundle - AccessListInspector on bundles

### ISSUE THREAD

**Issue by 0xSt1ng3R** [paradigmxyz/reth#5748]
### Describe the feature

For MEV related simulations, access list creation in bundles is needed.
Can be implemented as a part of eth_callBundle or in a new RPC call like eth_estimateGasBundle ([example from geth](https://github.com/chainstack/mev-geth/commit/147e5e2248291593bc93a620b99f0097fc8053c6)).

**Comment by 0xSt1ng3R** [comment]
I know very little about rust, but here is something I hacked together that looks like a good starting point (?):
```rust
pub async fn create_access_list_from_bundle(
    &self,
    calls: Vec<CallRequest>,
    block_id: Option<BlockId>,
) -> EthResult<Vec<AccessListWithGasUsed>> {
    let at = block_id.unwrap_or(BlockId::Number(BlockNumberOrTag::Latest));
    let (cfg, block_env, at) = self.inner.eth_api.evm_env_at(at).await?;

    self.inner
        .eth_api
        .spawn_with_state_at_block(at, move |state| {
            let mut access_lists = Vec::with_capacity(calls.len());
            let mut db = CacheDB::new(StateProviderDatabase::new(state));

            for mut call in calls {
                let mut env = build_call_evm_env(cfg.clone(), block_env.clone(), call.clone())?;
                env.cfg.disable_block_gas_limit = true;
                env.cfg.disable_base_fee = true;

                if call.gas.is_none() && env.tx.gas_price > U256::ZERO {
                    cap_tx_gas_limit_with_caller_allowance(&mut db, &mut env.tx)?;
                }

                let from = call.from.unwrap_or_default();
                let to = call.to.unwrap_or(from.create(db.basic_ref(from)?.unwrap_or_default().nonce));
                let initial = call.access_list.take().unwrap_or_default();

                let precompiles = get_precompiles(env.cfg.spec_id);
                let mut inspector = AccessListInspector::new(initial, from, to, precompiles);
                let (result, env) = inspect(&mut db, env, &mut inspector)?;

                result.result.ensure_success()?;

                let access_list = inspector.into_access_list();
                call.access_list = Some(access_list.clone());
                let gas_used = self.estimate_gas_with(env.cfg, env.block, call, db.db.state(), None)?;

                access_lists.push(AccessListWithGasUsed { access_list, gas_used });
            }

            Ok(access_lists)
        })
        .await
}
```

Can someone with more rust knowledge take it from here?

**Comment by mattsse** [comment]
in order to support the `eth_estimateGasBundle` we need to do:

1. add the function definition here: 
https://github.com/paradigmxyz/reth/blob/013b4c93db27e6c1926d3295319f9a4319d4f691/crates/rpc/rpc-api/src/bundle.rs#L16-L22
2. Implement the function here: https://github.com/paradigmxyz/reth/blob/013b4c93db27e6c1926d3295319f9a4319d4f691/crates/rpc/rpc/src/eth/bundle.rs#L181-L187

your sample looks appropriate, will take a closer look when you open a PR

**Comment by 0xSt1ng3R** [comment]
Can I instead add the code here, as a new RPC method named eth_createBundleAccessList?
https://github.com/paradigmxyz/reth/blob/5062b7ea866960a99fb3b459550034fb6c37e766/crates/rpc/rpc/src/eth/api/call.rs#L353
and:
https://github.com/paradigmxyz/reth/blob/5062b7ea866960a99fb3b459550034fb6c37e766/crates/rpc/rpc/src/eth/api/server.rs#L253
and here:
https://github.com/paradigmxyz/reth/blob/013b4c93db27e6c1926d3295319f9a4319d4f691/crates/rpc/rpc-api/src/eth.rs#L180
