### ISSUE TITLE
Support other networks

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#579]
### Describe the feature

Currently, we only support mainnet. 

We should support other networks via:
1. Configurable genesis.json: https://github.com/paradigmxyz/reth/blob/a85793cd9b973519498f6b37eef0afc19a181629/bin/reth/src/util/chainspec.rs#L75
2. Configurable bootnodes (currently we only do mainnet): https://github.com/paradigmxyz/reth/blob/a85793cd9b973519498f6b37eef0afc19a181629/bin/reth/src/node/mod.rs#L220
3. Configurable database path in the CLI (currently ~/.reth/db, should be ~/.reth/{chain}/db)
4. What else?

Also it happens to be that while our mainnet.json is kosher, the goerli.json is missing params like `"daoForkBlock": 0` and `"parisBlock": ??`. Makes me think that some of these should be Options? Not sure.

**Comment by mattsse** [comment]
ref #485

**Comment by onbjerg** [comment]
>Configurable genesis.json: 

This is done

What we need is basically `NetworkConfig` to be `Serialize`/`Deserialize` and for `ForkId`s in the network component to be dynamic (#485)

**Comment by onbjerg** [comment]
Blocked on #747

**Comment by Rjected** [comment]
Now that #747 is in, is there anything left here? We should be able to support goerli / sepolia, but have not personally tested

**Comment by gakonst** [comment]
We still need these to be separate per chain
* bootnodes for other networks to be
* db path / reth.toml

**Comment by mattsse** [comment]
can close @onbjerg ?
