### ISSUE TITLE
guides to integrating op-reth into magi

### ISSUE THREAD

**Issue by sartimo** [paradigmxyz/reth#5794]
### Describe the change

are there any guides to integrating op-reth into magi

**Comment by onbjerg** [comment]
Magi is an op-node implementation which represents the CL in the L2 world and op-reth is the EL in the L2 world. You don't integrate them together, you run them side by side. Here is a guide to running an OP stack, just replace op-geth with op-reth https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup
