### ISSUE TITLE
Improve Optimism RPC errors

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5807]
### Describe the feature

currently we're mapping OP errors

https://github.com/paradigmxyz/reth/blob/048c593c7eacb139d84008b61e6fc7531d2d578b/crates/rpc/rpc/src/eth/api/transactions.rs#L969-L972

## TODO
* Extend OP specific rpc errors https://github.com/paradigmxyz/reth/blob/048c593c7eacb139d84008b61e6fc7531d2d578b/crates/rpc/rpc/src/eth/error.rs#L112-L112
* Map errors accordingly and convert into `EthApiError::Optimism`

**Comment by psychiller** [comment]
I have started working on this issue.
Should I use a general ```EthApiError::Optimism(OptimismEthApiError::InternalEthError)``` for all such instances in transaction.rs or should I add specific error for each instance based on if it occured during serializing/ l1 data gas/ l1 gas fee.
If it needs to be specific, would appreciate some guidance on naming of such errors.
Thank you.

**Comment by mattsse** [comment]
> n transaction.rs or should I add specific error for each instance based on if it occured during serializing/ l1 data gas/ l1 gas fee.
If it needs to be specific, would appreciate some guidance on naming of such errors.

specific, meaningful types for these error cases, yes

ty!
