### ISSUE TITLE
Error -32602, unknown field `blockhash`, returned by eth_getLogs

### ISSUE THREAD

**Issue by qnduncan** [paradigmxyz/reth#5830]
### Describe the bug

Got the response 
```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params","data":"unknown field `blockhash`, expected one of `fromBlock`, `toBlock`, `address`, `topics`, `blockHash` at line 1 column 12"},"id":1}
``` 
by request payload `{"jsonrpc":"2.0","method":"eth_getLogs","id":1,"params":[{"blockhash":"0x58dc57ab582b282c143424bd01e8d923cddfdcda9455bad02a29522f6274a948"}]}`

While the request payload is valid for erigon=2.55.1-12889fd0

### Steps to reproduce

```
curl <reth-client> \
    -X POST \
    -H "Content-Type: application/json" \
    --data '{"jsonrpc":"2.0","method":"eth_getLogs","id":1,"params":[{"blockhash":"0x58dc57ab582b282c143424bd01e8d923cddfdcda9455bad02a29522f6274a948"}]}'
```

### Node logs

```text
NA
```

### Platform(s)

Ubuntu 22.04, x86_64

### What version/commit are you on?

c4c07b86

### What database version are you on?

Current database version: 1
Local database is uninitialized

### What type of node are you running?

archive

### What prune config do you use, if any?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
you have a typo here "blockhash", this should be `blockHash`.

this only works on go clients because they json library supports case insensitive entries by default, though the spec is `blockHash`
