### ISSUE TITLE
Add dumpgenesis subcommand

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5833]
### Describe the feature

geth ref:

```
NAME:
   geth dumpgenesis - Dumps genesis block JSON configuration to stdout

USAGE:
   geth dumpgenesis [command options] [arguments...]

DESCRIPTION:
   
   The dumpgenesis command prints the genesis configuration of the network preset
   if one is set.  Otherwise it prints the genesis from the datadir.

OPTIONS:
   ETHEREUM

   
    --datadir value                (default: /Users/Matthias/Library/Ethereum)
          Data directory for the databases and keystore
   
    --goerli                       (default: false)
          Görli network: pre-configured proof-of-authority test network
   
    --mainnet                      (default: false)
          Ethereum mainnet
   
    --sepolia                      (default: false)
          Sepolia network: pre-configured proof-of-work test network

```

## TODO
add new subcommand that dumps the genesis file

https://github.com/paradigmxyz/reth/blob/33c8f405fcccc16e52916d96d404d64a2605e0a1/bin/reth/src/cli/mod.rs#L134-L134

see also:

https://github.com/paradigmxyz/reth/blob/33c8f405fcccc16e52916d96d404d64a2605e0a1/crates/primitives/src/chain/spec.rs#L567-L572

**Comment by estensen** [comment]
I'd like to work on this ✋🏻

**Comment by mattsse** [comment]
hey @estensen do you have the bandwidth to work on this, or should I open this up again?

**Comment by gnapoli23** [comment]
Hi @mattsse I would pick it up if @estensen has to work on other stuff.

**Comment by estensen** [comment]
Sorry haven't had time, should have unassigned myself

**Comment by mattsse** [comment]
all good, feel free to pick another one if you want and have the bandwidth :)

**Comment by Rjected** [comment]
> Hi @mattsse I would pick it up if @estensen has to work on other stuff.

@gnapoli23 how's it going? do you need any help?

**Comment by gnapoli23** [comment]
Hey @Rjected started to work on it but have been busy last days; gonna be back on it next few ones 👍🏻 I'll ping you if needed, thanks!
