### ISSUE TITLE
Improve HistoricalStateProvider.

### ISSUE THREAD

**Issue by RIg410** [paradigmxyz/reth#5844]
### Describe the feature

I am interested in knowing if there are plans to support StateRootProvider and StateProvider::proof for HistoricalStateProvider. 

We need to be able to use the get_proof API on historical data.
Also, we need the capability to perform forks, roll back to an earlier block, and insert a new block on top of a non-latest block using engine_forkchoiceUpdatedV1.
Currently, we are encountering an error "unable to compute state root on top of historical block."  geth allows this operation, and we would like to implement it in reth.

We are very interested in this functionality and could take on its implementation ourselves.
We are interested in hearing your vision of the problem and its possible solutions.

**Comment by borispovod** [comment]
Yeah, same here. 

Would be great if someone can assist with it a little
Thank you
