### ISSUE TITLE
Add  easter egg CLI option

### ISSUE THREAD

**Issue by shemnon** [paradigmxyz/reth#5857]
### Describe the feature

For a late March/early April release add a hidden flag `--h4ck3r-m0d3` that will cause reth to output a log message at info about once every 4-5 minutes (about once per page at full screen logging) that includes hacker jokes like "Neo, the matrix has you", "0.0234526 Ether rescued from central bankers", "Toggling id10t flag", etc.

https://twitter.com/_prestwich/status/1738436227584684169

Obviously a low severity / weekend hack priority issue.

**Comment by peyha** [comment]
Seems fun, I will do it

**Comment by emnul** [comment]
@mattsse this seems like a fun project. Could it be assigned to me?
