### ISSUE TITLE
Add new methods for Hardfork 

### ISSUE THREAD

**Issue by DoTheBestToGetTheBest** [paradigmxyz/reth#5873]
### Describe the feature

the method should returns true/false if the hardfork includes a specific eip.

```rust
pub fn has_eip1559(&self) -> bool
EIP-2718
EIP-2930
EIP-4844 


``` 

Please add first good issue for this

**Comment by mattsse** [comment]
hmm, how would these be useful?

all these eips belong to certain hardforks

**Comment by DoTheBestToGetTheBest** [comment]
> hmm, how would these be useful?
> 
> all these eips belong to certain hardforks

well i was thinking we could provide a  way to check whether specific eip  are included in each hardfork but i can close this if it's not interesting to add it

**Comment by mattsse** [comment]
these are not particularly useful because hardforks are additive.
all of these checks or done in revm internally

and usually you check against hardfork directly like `hardfork >= Hardfork::London`
