### ISSUE TITLE
Add optional feature to enable faster keccak implementation

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#5874]
### Describe the feature

See https://github.com/alloy-rs/core/pull/466 (released in v0.5.4).

It should also enable this feature by default when creating distribution binaries in CI, since that's where the biggest speed up is.

**Comment by lordshashank** [comment]
Hey, I think I can work on this one.

**Comment by lordshashank** [comment]
Hey, I am thinking of updating the alloy-primitives version to 0.5.4 and then use the keccak-asm, would this be correct or should it be implemented here only?

**Comment by DaniPopes** [comment]
alloy-primitives is on 0.5.4 already. All you have to do is add a `asm-keccak = ["alloy-primitives/asm-keccak"]` in `reth-primitives`, and the same in the `reth` crate (`bin/reth`). Then enable this in the release CI.

**Comment by Rjected** [comment]
This was fixed by #5997, closing
