### ISSUE TITLE
Move top-level lints to [workspace.lints] manifest table

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#5877]
### Describe the feature

- In the root /Cargo.toml: add [`[workspace.lints]`](https://doc.rust-lang.org/nightly/cargo/reference/workspaces.html#the-lints-table) with the lints that are in (almost) every crate, and remove said lints from the crates:
  ```rust
  #![warn(missing_debug_implementations, missing_docs, unreachable_pub, rustdoc::all)]
  #![deny(unused_must_use, rust_2018_idioms)]
  ```
- In all package Cargo.toml: add [`[lints] workspace = true`](https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-lints-section) after `[package]`
- Run `cargo clippy --workspace` to verify
- It's fine if you have to manually allow some of these in individual crates

**Comment by hoffeig** [comment]
Happy to work on this.

**Comment by mx644** [comment]
When the warn flag is applied to `rustdoc.all` as suggested, the compiler emits an `unknown_lints` warning, as seen below on the `blockchain-tree` crate:

```
warning[E0602]: unknown lint: `rustdoc.all`
  |
  = note: requested on the command line with `-W rustdoc.all`
  = note: `#[warn(unknown_lints)]` on by default

For more information about this error, try `rustc --explain E0602`.
```

I want to solicit feedback on supressing `unknown_lints` warnings or leaving it as-is before moving foreward.

**Comment by mx644** [comment]
When the warn flag is applied to `rustdoc.all` as suggested, the compiler emits an `unknown_lints` warning (not limited to but shown by) the `blockchain-tree` crate compilation step:

```
warning[E0602]: unknown lint: `rustdoc.all`
  |
  = note: requested on the command line with `-W rustdoc.all`
  = note: `#[warn(unknown_lints)]` on by default

For more information about this error, try `rustc --explain E0602`.
```

I just want to solicit feedback on supressing `unknown_lints` warnings in the parent `Cargo.toml` or to leave it as-is.

**Comment by mx644** [comment]
When the warn flag is applied to `rustdoc.all` as suggested, the compiler emits an `unknown_lints` warning (not limited to but shown by) the `blockchain-tree` crate compilation step:

```
warning[E0602]: unknown lint: `rustdoc.all`
  |
  = note: requested on the command line with `-W rustdoc.all`
  = note: `#[warn(unknown_lints)]` on by default

For more information about this error, try `rustc --explain E0602`.
```

Submitted a PR, but soliciting feedback on removing the `unknown_lints = "allow"` line.

**Comment by DaniPopes** [comment]
Replied in the PR

**Comment by DaniPopes** [comment]
Well I don't know what happened here, @tcoratger do still you want take this?

**Comment by tcoratger** [comment]
> * It's fine if you have to manually allow some of these in individual crates

@DaniPopes Let me reopen one. I saw that there were a lot of exceptions and as I had a lot of work I didn't want to stuck the issue and I told myself that someone would go faster but I'm going to reopen.
