### ISSUE TITLE
Support full payload validations for sidechains

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5889]
### Describe the feature

Due to past limitations, the state root check was skipped for blocks in sidechains:

https://github.com/paradigmxyz/reth/blob/cd08ba825f63dd60ecb64aa72ae47074e87d24e6/crates/blockchain-tree/src/blockchain_tree.rs#L130-L141

This can cause attestation issues on 1-block reorgs/late blocks specifically with CL clients (lighthouse for example), because ACCEPTED is treated the same as SYNCING
because then the CL needs to wait for processed FCU and can't reuse the previous status response of the payload.

## TODO
* support full state root validation for sidechains in the tree, I believe @Rjected had a PR for this at some point

**Comment by michaelsproul** [comment]
Yesss hyped for this
