### ISSUE TITLE
replace &Bytes with &[u8] in optimism functions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5891]
### Describe the feature

blocked by https://github.com/bluealloy/revm/pull/937 (and upstream here)

## TODO:

replace &Bytes with &[u8] here:

https://github.com/paradigmxyz/reth/blob/cd08ba825f63dd60ecb64aa72ae47074e87d24e6/crates/revm/src/optimism/mod.rs#L94-L94

**Comment by supernovahs** [comment]
Let me take this
