### ISSUE TITLE
Add standalone optimism transaction validator

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5892]
### Describe the feature

currently the OP transaction validator is the regular ethereum validator:

https://github.com/paradigmxyz/reth/blob/cd08ba825f63dd60ecb64aa72ae47074e87d24e6/crates/transaction-pool/src/validate/eth.rs#L99-L104

with additional cfg checks:

https://github.com/paradigmxyz/reth/blob/cd08ba825f63dd60ecb64aa72ae47074e87d24e6/crates/transaction-pool/src/validate/eth.rs#L379-L383

this makes it impossible to use both variants in the same binary

## TODO
* add Standalone Op validator

most of the checks can be reused, so perhaps the OP validator can just wrap the eth version and apply the additional checks (l1 gas cost) this would be feasible since this is the most expensive check anyway so the op could only check this if the eth validate succeeded.

we could also restructure the existing checks into reusable functions.

FYI @clabby @refcell

**Comment by clabby** [comment]
I can grab this one. Is the goal here to get rid of the `optimism` feature flag in the transaction pool crate? Rather than making a fully separate inner validator, it'd be way less code to break out the cost computation into a new function in the `EthTransactionValidatorInner` & switch on `self.chain_spec().is_optimism()`.

**Comment by mattsse** [comment]
> so that it can be toggled @ runtime? 

yes exactly

> it'd be way less code to break out the cost computation into a new function in the EthTransactionValidatorInner & switch on self.chain_spec().is_optimism()

that could work

**Comment by Rjected** [comment]
@clabby any progress here? would be great to be able to toggle at runtime
