### ISSUE TITLE
Invalid transaction signature for ancient transactions

### ISSUE THREAD

**Issue by Troublor** [paradigmxyz/reth#5903]
### Describe the bug

When getting transaction which are very old, e.g., [`0xcbaa1b514a4565003fa0708a21cf0ddb115ab20d2c9373ffda0c129d1deaeebc`](https://etherscan.io/tx/0xcbaa1b514a4565003fa0708a21cf0ddb115ab20d2c9373ffda0c129d1deaeebc), the `eth_getTransactionByHash` json rpc returns 
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "invalid transaction signature"
    },
    "id": 1
}
```

### Steps to reproduce

Send the following JSON RPC request:
```
{
	"jsonrpc":"2.0",
	"method":"eth_getTransactionByHash",
	"params":[
		"0xcbaa1b514a4565003fa0708a21cf0ddb115ab20d2c9373ffda0c129d1deaeebc"
	],
	"id":1
}
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

v0.1.0-alpha.13

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

cargo build --release

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this is fixed on main #5721
