### ISSUE TITLE
Add TransactionPool::get_transaction_by_sender_and_nonce

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5910]
### Describe the feature

similar to 

https://github.com/paradigmxyz/reth/blob/b318c57236311c761d537b00d092103c5c354b47/crates/transaction-pool/src/traits.rs#L303-L307

but should fetch the matching nonce if it exists.

this could be useful for upcoming eth_ rpc calls

ref #5904

cc @tcoratger

**Comment by tcoratger** [comment]
Can I work on this?
