### ISSUE TITLE
Node stalled and Lighthouse reported "Chain failed!" after Reth running for a while

### ISSUE THREAD

**Issue by tobernguyen** [paradigmxyz/reth#5916]
### Describe the bug

Reth node (full node) stopped advancing after a while running. Reth is still running but printing out this WARN.

```
...
2024-01-01T22:59:51.933918Z  WARN reth::node::events: Beacon client online, but no consensus updates received for a while. Please fix your beacon client to follow the chain! period=345228.777070008s
2024-01-01T22:59:55.322041Z  INFO reth::cli: Status connected_peers=95 freelist=1537858 latest_block=18887170
2024-01-01T23:00:20.321990Z  INFO reth::cli: Status connected_peers=95 freelist=1537858 latest_block=18887170
...
```

When checking Lighthouse, it complained that the execution node was corrupted and advised to restart both Reth then Lighthouse.
```
Jan 01 23:04:41.001 INFO Syncing                                 est_time: --, distance: 28793 slots (3 days 23 hrs), peers: 23, service: slot_notifier
Jan 01 23:04:42.739 WARN Failed to sync chain built on invalid parent, advice: check execution node for corruption then restart it and Lighthouse, parent_root: 0xae74edc5228e53dfaf7269b816dcbdaa5ce9748e9a604c96605771ad70d81db3
Jan 01 23:04:42.739 WARN Batch failed to download. Dropping chain scoring peers, batch_epoch: 252554, score_adjustment: Low Tolerance Error, chain: 5508887011758294417, service: sync
Jan 01 23:04:42.739 WARN Chain failed! Syncing to its head won't be retried for at least the next 30 seconds, id: 5508887011758294417, from: 252552, to: 253451, end_root: 0xa639…5b24, current_target: 252554, batches: 8, peers:
 0, validated_batches: 0, state: Syncing, service: sync
Jan 01 23:04:42.743 INFO Sync state updated                      new_state: Evaluating known peers, old_state: Syncing Finalized Chain, service: sync
Jan 01 23:04:53.001 INFO Syncing                                 est_time: --, distance: 28794 slots (3 days 23 hrs), peers: 19, service: slot_notifier
Jan 01 23:05:05.001 INFO Syncing                                 est_time: --, distance: 28795 slots (3 days 23 hrs), peers: 18, service: slot_notifier
Jan 01 23:05:16.838 INFO Sync state updated                      new_state: Syncing Finalized Chain, old_state: Evaluating known peers, service: sync
Jan 01 23:05:17.001 INFO Syncing                                 est_time: --, distance: 28796 slots (3 days 23 hrs), peers: 20, service: slot_notifier
Jan 01 23:05:19.412 WARN Failed to sync chain built on invalid parent, advice: check execution node for corruption then restart it and Lighthouse, parent_root: 0xae74edc5228e53dfaf7269b816dcbdaa5ce9748e9a604c96605771ad70d81db3
```

I have tried to restart the Lighthouse first (not reth) to check if Lighthouse was the issue but it will print the same logs as above after a while. So I restarted Reth and Lighthouse and it started to sync again.
Note: Lighthouse also needed to be restarted after reth is restarted for the node to sync.

### Steps to reproduce

I don't know

### Node logs

[reth-stall-2023-01-01.log.zip](https://github.com/paradigmxyz/reth/files/13806254/reth-stall-2023-01-01.log.zip)

### Platform(s)

Linux (x86)

### What version/commit are you on?

v0.1.0-alpha.13

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
Looks like this is a receipts root failure for block `0xa436f28d8ba44912b516064db82ee5b6d69751bc9e048c5b43c1fef27280a927`:
```
2023-12-28T23:06:00.759410Z  WARN consensus::engine: Marking block as invalid invalid_number=18887254 invalid_hash=0xa436f28d8ba44912b516064db82ee5b6d69751bc9e048c5b43c1fef27280a927 err=Execution(Validation(ReceiptRootDiff(GotExpected { got: 0x6d4545e0cf1dc8c010b3add91dd06a587198cc53cc098f2a6068192c285b8e73, expected: 0x0fbcfe47c573b53bae4928dc4cb9ce0352b428ada1063cd6b7bed165f6536c46 })))
```

This block is canonical and other nodes are keeping up, so I wonder what could have caused this

**Comment by Rjected** [comment]
[reth-stall-receipts-root.log](https://github.com/paradigmxyz/reth/files/13895468/reth-stall-receipts-root.log)

Adding the relevant part of the log here

**Comment by tobernguyen** [comment]
I'm still experiencing this issue

**Comment by tobernguyen** [comment]
> > I'm still experiencing this issue
> 
> on alpha.17? do you mind sending some updated logs?

Oh not alpha17. I'm upgrading to alpha18 today and will let you know. I just want to add a comment so the bot won't close the issue.

**Comment by tobernguyen** [comment]
Still see this on alpha.21 with lighthouse 5.0.0

[reth-stall-03-06-2024.log.zip](https://github.com/paradigmxyz/reth/files/14513035/reth-stall-03-06-2024.log.zip)
