### ISSUE TITLE
`reth-revm-inspectors`: Move inspectors out of reth and into their own repo

### ISSUE THREAD

**Issue by Evalir** [paradigmxyz/reth#5956]
### Describe the feature

Foundry now depends on `reth-revm-inspectors` for tracing with https://github.com/foundry-rs/foundry/pull/6219. To remove some burden on foundry having to depend on reth, it would be ideal to extract the inspectors to their own repo, namely https://github.com/paradigmxyz/evm-inspectors. Doing this completes a milestone in https://github.com/foundry-rs/foundry/issues/5216.

**Comment by supernovahs** [comment]
I can take this

**Comment by DaniPopes** [comment]
Hi @supernovahs we're taking this over since it's blocking for further work: <https://github.com/paradigmxyz/evm-inspectors>

**Comment by mattsse** [comment]
completed
