### ISSUE TITLE
Update rust version

### ISSUE THREAD

**Issue by supernovahs** [paradigmxyz/reth#5965]
### Describe the feature

Current rust version in reth is `1.70`

Maybe we should update it incrementally by looking at changes for each release in rust [lang](https://github.com/rust-lang/rust/blob/master/RELEASES.md)

Wdyt?

**Comment by Rjected** [comment]
The `rust-version` field in `Cargo.toml` represents the minimum supported rust version, so this should only be updated when we adopt features in newer rust versions. We did adopt features newer than `1.70` though, so updated it here: #5974
