### ISSUE TITLE
Help. Secp256k1 error

### ISSUE THREAD

**Issue by hzw19** [paradigmxyz/reth#5968]
### Describe the bug

![asecp](https://github.com/paradigmxyz/reth/assets/145047790/0b28c4be-5dfb-4381-937e-296572ce674c)
![acargo](https://github.com/paradigmxyz/reth/assets/145047790/c29b5e00-4d64-4d38-a68a-3a40a0831c38)

### Steps to reproduce

Run code error

### Platform(s)

Mac (Intel)

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this just looks like a version mismatch.

try:

https://github.com/paradigmxyz/reth/blob/3038c3c7ba35b1262b3ee55be136514e2e4c44c4/Cargo.toml#L221-L225
