### ISSUE TITLE
Exclude private transactions for pending block in RPC

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5970]
### Describe the feature

Currently, requesting the pending block in rpc might leak state changes of private transactions.

we should not include private transactions here:

https://github.com/paradigmxyz/reth/blob/d51375c4f3b1221b4a9429aea239d792d67ecbcc/crates/rpc/rpc/src/eth/api/pending_block.rs#L65-L65

we can either solve this by marking private txs as invalid here or add a filter to the BesTransactions trait and add a helper iterator type that wraps `BestTransactions` and applies this internally

**Comment by supernovahs** [comment]
I can take this
