### ISSUE TITLE
Database version file

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#598]
### Describe the feature

After we stabilize database and ship the first version of it, we need to take care of upgrades and have a mechanism that would allow the transition from old to new versions that can break compatibility. 

First step is to have `database.version` file saved in same place as database is saved, read it on boot and compare it with hardcoded value

**Comment by onbjerg** [comment]
Alternatively a single table that lists the migrations performed - this schema is unlikely to ever change and it makes migrations durable as well (no chance we apply migration but don't bump the db version)

**Comment by rakita** [comment]
Db metadata as in version is mostly put outside of database so you can read it without opening the database. For example, if we move to redb, metadata would contains db type and its version.

Upgrading (moving tables etc.) something as big as eth client db is one way, not safe operation as the amount of data is massive, version file bump at the end is not that big of the problem and we could have intermediate state. something like `version:5`, `version: upgrading5-6`, `version:6`.

**Comment by Genysys** [comment]
I would love take this on

**Comment by gakonst** [comment]
Agreed with this on principle. This will save users from having to resync their databases whenever there's a breaking db change.


I think there's 2 paths here:
1. We formally define all our DB semantics and we write a proper migration tool, similar to what ORMs have. [I love how Prisma does this](https://www.prisma.io/docs/concepts/components/prisma-migrate/mental-model). 
    * Honestly, this might be something that the Database itself should provided and we can talk with Chris at Redb about supporting it potentially. This is probably a lot of work, but I have not thought about it a lot
2. As the Database stabilizes, it may be good enough that we manually publish a tool which does surgery based on our changes. This will require some discipline from our side in tracking the breaking changes, and ensuring that our tool properly migrates from a version to another. It will be less work to do it manually per-migration. I know Optimism has written things like that before, when they were doing breaking changes in their (now-deprecated) OVM. @Tynes and/or @kelvinfichter iirc owned that back then and may have input for us here with common mistakes.

> something like version:5, version: upgrading5-6, version:6.

Yep, we have some logic around that in [ethers-solc](https://github.com/gakonst/ethers-rs/blob/799f752e55e80aa8d6357321d4f5f7ebf66daa8a/ethers-solc/src/cache.rs#L28) for detecting when the cache format has changed.

**Comment by tynes** [comment]
The database migration work that we did at Optimism was more at the application layer, ie migrating the ERC20 representation of ether to a native representation of ether. I think you could prob get away with requiring users to resync early on (reth still in alpha/beta) if you communicate that clearly. I believe erigon still requires users to resync every now and again

**Comment by gakonst** [comment]
> The database migration work that we did at Optimism was more at the application layer, ie migrating the ERC20 representation of ether to a native representation of ether. I think you could prob get away with requiring users to resync early on (reth still in alpha/beta) if you communicate that clearly. I believe erigon still requires users to resync every now and again

Agreed - we're exploring if we can do better than that!

**Comment by seroze** [comment]
Hi @rakita is this issue still relevant?

**Comment by rakita** [comment]
> Hi @rakita is this issue still relevant?

Yes it is, first step would be to add the simple json file with version field and comprate it with hardcoded version from code

**Comment by rakita** [comment]
> > Yes it is, first step would be to add the simple json file with version field and comprate it with hardcoded version from code
> 
> Should we take some action here, like in case the version doesn't match then process should exit etc.. ?

yep, and write to the console that there is a breaking db change, it is a good UX
