### ISSUE TITLE
Move engine related rpc types to alloy

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#5989]
### Describe the feature

move engine related rpc types (reth-rpc-types/engine) to a new crate in alloy, similar to existing rpc types crates there

blocked by #5948

**Comment by 1010adigupta** [comment]
can take this

**Comment by mattsse** [comment]
triggered merge on #5948 that unblocks this

**Comment by 1010adigupta** [comment]
@mattsse I have linked a pr here, kindly give review on it
