### ISSUE TITLE
Emit new Peer Networkevents

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#599]
### Describe the feature

followup for #574 to emit events

ref: https://github.com/paradigmxyz/reth/pull/574#pullrequestreview-1229571517

cc @TechieBoy

**Comment by TechieBoy** [comment]
I am still getting familiar with the code

If I understand correctly:
PeerManager emits a new  `PeerAction` (notifyAdded, notifyRemoved) when a new peer is added/removed from its `peers` HashMap

Then this `PeerAction` is bubbled to swarm by `PeerAction` -> `StateAction` -> `SwarmEvent`
