### ISSUE TITLE
Latest docker version (v0.1.0-alpha.14) immediately exits

### ISSUE THREAD

**Issue by timjrobinson** [paradigmxyz/reth#6007]
### Describe the bug

I was having issues with my reth node, so I pulled the latest docker file and ran it. It immediately exits after the startup output. 

### Steps to reproduce

Put the following into docker-run.sh:

```
#!/bin/bash

docker run \
    -d \
    -p 9000:9000 \
    -p 8545:8545 \
    -p 8546:8546 \
    -p 8551:8551 \
    -p 20303:20303 \
    -p 30303:30303 \
    --name reth \
    ghcr.io/paradigmxyz/reth:latest \
    node
```

Run the script and notice it exits immediately

### Node logs

```text
2024-01-10T14:19:37.559985Z  INFO reth::cli: reth 0.1.0-alpha.14 (573c73f) starting
2024-01-10T14:19:37.560073Z  INFO reth::cli: Opening database path="/root/.local/share/reth/mainnet/db"
2024-01-10T14:19:37.570867Z  INFO reth::cli: Configuration loaded path="/root/.local/share/reth/mainnet/reth.toml"
2024-01-10T14:19:37.571549Z  INFO reth::cli: Database opened
2024-01-10T14:19:37.572301Z  INFO reth::cli: Starting metrics endpoint addr=0.0.0.0:9000
2024-01-10T14:19:37.572687Z  INFO reth::cli: Pre-merge hard forks (block based):
- Frontier                         @0
- Homestead                        @1150000
- Dao                              @1920000
- Tangerine                        @2463000
- SpuriousDragon                   @2675000
- Byzantium                        @4370000
- Constantinople                   @7280000
- Petersburg                       @7280000
- Istanbul                         @9069000
- MuirGlacier                      @9200000
- Berlin                           @12244000
- London                           @12965000
- ArrowGlacier                     @13773000
- GrayGlacier                      @15050000
Merge hard forks:
- Paris                            @58750000000000000000000 (network is not known to be merged)

Post-merge hard forks (timestamp based):
- Shanghai                         @1681338455
```
```


### Platform(s)

_No response_

### What version/commit are you on?

v0.1.0-alpha.14

### What database version are you on?

_No response_

### What type of node are you running?

None

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by timjrobinson** [comment]
Actually this is happening when reverting back to 0.13 too, so not sure what's going on, investigating further.

**Comment by mattsse** [comment]
I think what's happening here is that the script terminates after docker run succeeds

not a docker expert but I ran your script and the container is up and running once the script terminates

**Comment by mattsse** [comment]
I tried
```
#!/bin/bash

docker run \
    -d \
    -p 9000:9000 \
    -p 8545:8545 \
    -p 8546:8546 \
    -p 8551:8551 \
    -p 20303:20303 \
    -p 30303:30303 \
    --name reth \
    ghcr.io/paradigmxyz/reth:latest \
    node
docker attach reth
```
which now works as expected.

closing since this appears to be a docker issue

**Comment by timjrobinson** [comment]
Yea it's very strange it's working fine on other systems, and other docker containers are working fine on this server. Just the reth container is immediately aborting after those debug logs even with a very simple startup script. I can't figure it out.

**Comment by timjrobinson** [comment]
I spent a while debugging this and still cannot figure out what's going on. `strace` shows the container exiting with status code 132, adding `-vvvvv` shows no additional logs. The container just exits after that initial output and I've run out of tools to be able to debug it further. 

I even upgraded the server from Debian 10 to 11 and that didn't help either.

Is there some piece of code that runs after that output that could be triggering something? Do any devs have any idea what could be making it exit?
