### ISSUE TITLE
Try to resolve public ip before announcing local NodeRecord

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#601]
### Describe the feature

Before discovery service is started, the ip field of the local NodeRecord, that's announced via discv4 should be set to the external public IP, if possible

ref https://github.com/sbstp/rust-igd/blob/master/examples/external_ip.rs UPNP external IP discovery

ref https://github.com/avitex/rust-public-ip to resolve public IP via dns/https resolver

**Comment by gakonst** [comment]
What is the implication here going to be? Are we going to be more likely to find "good" peers that way?

**Comment by mattsse** [comment]
this probably has no impact on the peer we're discovering but will affect what we're announcing, the external IP where we can be reached
