### ISSUE TITLE
Refactor WsHttpServerKind to Simplify Service Combinations and Enable Custom Services

### ISSUE THREAD

**Issue by supernovahs** [paradigmxyz/reth#6017]
### Describe the feature

- In our current implementation of the `WsHttpServerKind` enum, we handle various combinations of HTTP servers, including options with CORS, authentication, or both. This approach leads to a complex and somewhat rigid structure, which could be streamlined for better maintainability and flexibility.

- Refactoring the `WsHttpServerKind` enum to simplify the service combinations and, ideally, to allow the installation of custom services. This change would likely involve some API alterations and significant refactoring.

- We could explore the use of tower::Service and OptionLayer to create a more flexible and cleaner structure. This might allow for a more elegant way of stacking or combining services based on runtime configuration rather than hardcoding all possible combinations.

As Discussed with @mattsse

**Comment by mattsse** [comment]
somewhat related #5894

**Comment by onbjerg** [comment]
Closed https://github.com/paradigmxyz/reth/pull/7531
