### ISSUE TITLE
how can i send transaction with reth api ? 

### ISSUE THREAD

**Issue by Degen-Player** [paradigmxyz/reth#6022]
### Describe the change

I'm looking to use reth for my mev bot and looking to send transaction with reth, could someone moi give me hints how i'am supposed to send transaction with reth ?

### Additional context

thanks

**Comment by mattsse** [comment]
are you using a vanilla instance?

then you can simply submit it via `eth_sendRawTransaction`.

if you run a modified instance ptal at same examples how to use API programmatically

https://github.com/paradigmxyz/reth/blob/main/examples/trace-transaction-cli/src/main.rs

**Comment by Degen-Player** [comment]
> are you using a vanilla instance?
> 
> then you can simply submit it via `eth_sendRawTransaction`.
> 
> if you run a modified instance ptal at same examples how to use API programmatically
> 
> https://github.com/paradigmxyz/reth/blob/main/examples/trace-transaction-cli/src/main.rs

i can't use primitive reth ?

**Comment by Degen-Player** [comment]
> are you using a vanilla instance?
> 
> then you can simply submit it via `eth_sendRawTransaction`.
> 
> if you run a modified instance ptal at same examples how to use API programmatically
> 
> https://github.com/paradigmxyz/reth/blob/main/examples/trace-transaction-cli/src/main.rs

https://github.com/paradigmxyz/reth/tree/main/crates/primitives/src/transaction

**Comment by mattsse** [comment]
you can, but you need to convert them first before adding them to the pool via the transactionpool trait

ptal at the these traits: https://github.com/paradigmxyz/reth/blob/6430731fff06bfde15318667240d5738505fd6f8/crates/primitives/src/transaction/mod.rs#L1533-L1533
