### ISSUE TITLE
Add Filtered BestTransactions helper implementation

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6023]
### Describe the feature

Add a general purpose `BestTransactions` implementation:

https://github.com/paradigmxyz/reth/blob/df4774c709c906976842425f294f5e3f8fe876df/crates/transaction-pool/src/traits.rs#L619-L619

That wraps an existing `BestTransaction` and a pattern that decides if a transaction should be marked invalid: https://github.com/paradigmxyz/reth/blob/df4774c709c906976842425f294f5e3f8fe876df/crates/transaction-pool/src/traits.rs#L625-L625

This is similar to the std's `Filter` https://doc.rust-lang.org/stable/src/core/iter/adapters/filter.rs.html#18

ref https://github.com/paradigmxyz/reth/issues/5970

**Comment by yash-atreya** [comment]
Can take this!

**Comment by mattsse** [comment]
hey @yash-atreya 

just checking in, do you have the bandwidth to work on this?
if not, I'd like to open this up again

**Comment by yash-atreya** [comment]
Hey @mattsse 

Sorry for blocking this. You can open it.

**Comment by mattsse** [comment]
no worries!

**Comment by i-m-aditya** [comment]
I will pick this up.
