### ISSUE TITLE
Add Rpc config and builder types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#604]
### Describe the feature

rpc modules in the rpc crate can be merged to a [RpcModule](https://docs.rs/jsonrpsee/0.16.2/jsonrpsee/struct.RpcModule.html) via: https://docs.rs/jsonrpsee/0.16.2/jsonrpsee/struct.RpcModule.html#method.merge

to makes this convenient to use we need

* config type: what transports (HTTP, ws, ipc) to enable and what namespaces
* builder type: that allows to easily merge reth rpc modules

**Comment by onbjerg** [comment]
One thing to keep in mind is that we need 2 entirely different RPC endpoints, since a requirement of the engine spec is that the `engine` namespace is exposed on a different endpoint (along with some of the `eth` namespace)

**Comment by mattsse** [comment]
all types/api has been added.

will followup with targeted issues for remaining tasks
