### ISSUE TITLE
support extending the jwt authenticated rpc server with custom methods

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6049]
### Describe the feature

optimism has additional option engine method:

https://github.com/ethereum-optimism/optimism/blob/develop/specs/exec-engine.md#engine_signalsuperchainv1

currently we can only extend the regular rpc server's methods but we want support for this as well.

https://github.com/paradigmxyz/reth/blob/bc229c67c9961e7d19cc8bf0b6160df9eb62aeaf/bin/reth/src/args/rpc_server_args.rs#L254-L255

the AuthModule holds the configured authenticated methods:

https://github.com/paradigmxyz/reth/blob/bc229c67c9961e7d19cc8bf0b6160df9eb62aeaf/bin/reth/src/args/rpc_server_args.rs#L245-L245

https://github.com/paradigmxyz/reth/blob/bc229c67c9961e7d19cc8bf0b6160df9eb62aeaf/crates/rpc/rpc-builder/src/auth.rs#L251-L251

we want something like:

https://github.com/paradigmxyz/reth/blob/bc229c67c9961e7d19cc8bf0b6160df9eb62aeaf/crates/rpc/rpc-builder/src/lib.rs#L1787-L1800

**Comment by Arindam2407** [comment]
I can take this
