### ISSUE TITLE
remove reth-codec dependency from ethereum-forks crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6054]
### Describe the feature

the 

https://github.com/paradigmxyz/reth/blob/bc229c67c9961e7d19cc8bf0b6160df9eb62aeaf/crates/ethereum-forks/Cargo.toml#L16-L16

dependency is currently used to easily derive rlp and arbitrary.

to make this crate reth independent we should remove the codes dependency and instead derive/impl rlp+arbitrary directly.

**Comment by supernovahs** [comment]
Let me take this
