### ISSUE TITLE
Transaction Pool function `is_underpriced` does not work correctly

### ISSUE THREAD

**Issue by ercecan** [paradigmxyz/reth#6058]
### Describe the bug

I have detected a bug in the transaction pool's **transaction replacement calculations** when testing sending transactions to the pool with same nonces and different max_fee_per_gas.

I was able to replace my txs with **very minor bumps** to the **fee per gas** and **max priority fee per gas**. Currently the tx insertion does not check correctly if the replacement tx fees are bumped enough to replace and we can replace txs in the pool with even a **1%** increase in **fee per gas** and **max priority fee per gas**.

In `crates/transaction-pool/src/pool/txpool.rs`
```rust
#[inline]
    fn is_underpriced(
        existing_transaction: &ValidPoolTransaction<T>,
        maybe_replacement: &ValidPoolTransaction<T>,
        price_bumps: &PriceBumpConfig,
    ) -> bool {
        let price_bump = price_bumps.price_bump(existing_transaction.tx_type());
        //! price_bump is u128, so for default value of 10 for price_bump
        //! price_bump_multiplier is 110 / 100 = 1 due to integer division.
        let price_bump_multiplier = (100 + price_bump) / 100;

        if maybe_replacement.max_fee_per_gas() <=
            existing_transaction.max_fee_per_gas() * price_bump_multiplier // this just multiplies with 1?
        {
            return true
        }
        ...
        //! same problem here and on
        if replacement_max_priority_fee_per_gas <=
            existing_max_priority_fee_per_gas * price_bump_multiplier &&
            existing_max_priority_fee_per_gas != 0 &&
            replacement_max_priority_fee_per_gas != 0
        {
            return true
        }
        ...
    }
```
Basically the problem is that `price_bump_multiplier` variable type is `u128` so the result of  `(100 + price_bump) / 100` is always **1** (for `price_bump < 100` ).
This causes many errors throughout the function and transaction replacement.
For example for transactions with same nonce and same  or lower `max_fee_per_gas` and same or lower `max_priority_fee_per_gas` the code still works as intended and returns true as it is ùnder_priced`, but even if we increase the max_fee_per_gas and amx_priority_fee by %0.0001 percent the tx will be replaced in this scenario. 

### Steps to reproduce

I have written a test exactly like `insert_replace` test but I changed the initial tx's and replacement tx's priority fee and max fee.
- I set initial tx's priority fee and max fee to a **100** 
- I then set replacement tx's priority fee and max fee to a **101**
- The current price bump is **1%**
- The default price bump percentage value is **10%** as stated in  `crates/transaction-pool/src/config.rs`

According to this information the test below should **fail** and the replacement tx should **not** be inserted into the pool, however it **does**.

Try and run this test in `crates/transaction-pool/src/pool/txpool.rs`.
```rust
 #[test]
    fn insert_replace_one_percent_bump() {
        let on_chain_balance = U256::ZERO;
        let on_chain_nonce = 0;
        let mut f = MockTransactionFactory::default();
        let mut pool = AllTransactions::default();
        let mut tx = MockTransaction::eip1559().inc_price().inc_limit();
        tx.set_priority_fee(100);
        tx.set_max_fee(100);
        let first = f.validated(tx.clone());
        let _ = pool.insert_tx(first.clone(), on_chain_balance, on_chain_nonce).unwrap();
        let mut replacement = f.validated(tx.rng_hash().inc_price());
        replacement.transaction.set_priority_fee(101);
        replacement.transaction.set_max_fee(101);
        let InsertOk { updates, replaced_tx, .. } =
            pool.insert_tx(replacement.clone(), on_chain_balance, on_chain_nonce).unwrap();
        assert!(updates.is_empty());
        let replaced = replaced_tx.unwrap();
        assert_eq!(replaced.0.hash(), first.hash());

        // ensure replaced tx is fully removed
        assert!(!pool.contains(first.hash()));
        assert!(pool.contains(replacement.hash()));
        assert_eq!(pool.len(), 1);
    }
```

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

a075c315422fd9d04fc87ea6a7534306d9d56d79

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
tysm for this thorough report.


@tcoratger as pointed out above, storing this in a temp var introduces a loss:
```
let price_bump_multiplier = (100 + price_bump) / 100;
```

I believe the right fix here is to always do it together with the multiplication:

```
existing_transaction.max_fee_per_gas() * price_bump_multiplier
```

see also:

https://github.com/ethereum/go-ethereum/blob/e206d3f8975bd98cc86d14055dca40f996bacc60/core/txpool/legacypool/list.go#L308-L311

**Comment by tcoratger** [comment]
@mattsse Yes I think that, for example, instead of:

```rust
existing_transaction.max_fee_per_gas() * price_bump_multiplier
```

we should have 

```rust
existing_transaction.max_fee_per_gas() * (100 + price_bump) / 100
```

This will require calculating the `price_bump_multiplier` potentially several times, but it will avoid problems like the one mentioned in this issue.

@mattsse Let me know if you need a PR on this, but I have the impression that @ercecan had already proposed to work on it and already had a very good idea of what to do with his unit testing proposal to prevent this bug happens again.

**Comment by mattsse** [comment]
@ercecan do you want to submit a fix for this?

**Comment by ercecan** [comment]
Yes I would be happy to.
