### ISSUE TITLE
Move more types from CLI crate to node-builder crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6063]
### Describe the feature

we need to move a few things from the cli crate to the API crate so we can put them into traits and make them part of the node builder setup.

This requires some additional work, because ideally we want to have the `NodeConfig` type in the node-builder crate, though this type currently depends on all the CLI args types:

https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/builder/mod.rs#L220-L227

To unblock this, we should put either all args types into a new crate or move them into the builder crate, together with:

* config traits: https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/cli/config.rs
* dirs: https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/dirs.rs

**Comment by i-m-aditya** [comment]
I will fix this

**Comment by mattsse** [comment]
@i-m-aditya thanks for taking this on.

Since this will become a blocker very soon, I'm wondering if you could give an ETA here?

**Comment by i-m-aditya** [comment]
@mattsse I will get this done by tomorrow.
