### ISSUE TITLE
Headers stage commits when the full range is synced

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#607]
### Describe the bug

We used to (as a workaround) commit directly in the header stage, but since it was no longer needed, it was removed again.

However, the header stage still uses `commit_threshold` to chunk the header stream:

And not as an exit condition, which effectively means that the header stage will run, and not hand control over to the pipeline for checkpointing until the full range is synced.

Instead, the stream should not be chunked as we can validate the headers one-by-one as they come in and write them to the transaction. This simplifies the stage a bit.

Once we have either (1) gotten all of the headers we want (i.e. synced the full range) or (2) received `commit_threshold` headers, we should return control to the pipeline. In the first case we should return with `done: true` (signifying the pipeline can progress), in the second case we should return with `done: false` (signifying we have more headers to sync)

### Steps to reproduce

Run the node, setting `--debug.tip` to some arbitrarily large number (e.g. block 2m)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by rkrasiuk** [comment]
The solution here is to extract total difficulty into a separate stage and use logic from `get_head_and_tip` method to figure out whether the stage is done 
https://github.com/paradigmxyz/reth/blob/ba585cf7d997b6021878ac4a59a8c8a0b7cd6c09/crates/stages/src/stages/headers.rs#L171
