### ISSUE TITLE
Cap max graceful incoming disconnects if node is at capacity

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6079]
### Describe the feature

If the node's capacity exceeds the available slots for incoming connections

https://github.com/paradigmxyz/reth/blob/9d65a4cfbb39d0fc9a90ef9aee451595bcd05ba5/crates/net/network/src/swarm.rs#L205-L211

this handles disconnects gracefully:

https://github.com/paradigmxyz/reth/blob/9d65a4cfbb39d0fc9a90ef9aee451595bcd05ba5/crates/net/network/src/session/mod.rs#L307-L319

this should be capped at a certain number of active graceful disconnects, once it exceeds that number it should simply drop the connection.

A simple solution would be an atomic counter that's increased and decreased after disconnect.

perhaps a reasonable threshold would be 15

**Comment by 1010adigupta** [comment]
intresting!, will handle this.

**Comment by mattsse** [comment]
commonly this can be implemented with an Arc wrapper

```rust
Counter(Arc<()>);
```

that exposes `Arc::strong_count`

then you can check how many instances of this type exists before cloning and moving it into the spawned task
