### ISSUE TITLE
Shorten alloy types display output

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6080]
### Describe the feature

make logs more friendly to read for the human eye.

it would be best to output the alternate display form of the alloy `FixedBytes` types. rn, tracing crate doesn't support this https://github.com/tokio-rs/tracing/issues/1311, so we can't get away with simply `trace!(peer_id=#peer_id)`. for now we need to allocate a string for this like `trace!(peer_id=format!("{peer_id:#}")`.

to take into consideration here, is if any interop tests are using the current log output format, and if this then is a breaking change. (update: this is verified, it won't be a breaking change, no interop tests use hard coded log output as checkpoints)

here is how I have been setting alternate display flag in `tracing` for lists
`tracing!(hashes=format!("[{}]", hashes.iter().fold(String::new(), |acc, &hash| acc + &format!("{hash:#},"))))`

**Comment by emhane** [comment]
peer id is probably ok to shorten for all cases, but not tx hash. since block explorers require the whole hash in a search query, it's good to keep the whole hash even if the list is long.

**Comment by mattsse** [comment]
closing because unclear what the todos here are

if there's anything actionable here, please open a new good first issue for this
