### ISSUE TITLE
Extract Genesis types to standalone crate in alloy

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6085]
### Describe the feature

move all genesis types to new crate in alloy https://github.com/alloy-rs/alloy

https://github.com/paradigmxyz/reth/blob/93c0eeac171f20234ca8cae59f8ebdd9a21dd994/crates/primitives/src/genesis.rs

**Comment by supernovahs** [comment]
I can take this

**Comment by mattsse** [comment]
let's do this in two steps

first copy to alloy-genesis then replace in reth

**Comment by DaniPopes** [comment]
Note that I already ported it from ethers here: <https://github.com/alloy-rs/alloy/blob/ccc6c9340be86cf6c054776747daf70ce18cc4aa/crates/node-bindings/src/genesis.rs#L1>

Will need to be updated there too

**Comment by mattsse** [comment]
should be same format, yes
