### ISSUE TITLE
Create NodeHandle future for waiting for node exit

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6098]
### Describe the feature

The `NodeHandle` has a method which waits for the consensus engine to exit - this should be turned into its own struct that implements `Future`:

https://github.com/paradigmxyz/reth/blob/afa860757ded8209677ff85589aefa3ce05f437a/bin/reth/src/builder/mod.rs#L1374-L1385

**Comment by allnil** [comment]
Seems to be straightforward, maybe I can implement it?

**Comment by Rjected** [comment]
Sure! assigned

**Comment by allnil** [comment]
could be closed, I think
