### ISSUE TITLE
Add Pending block watcher in tree

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6104]
### Describe the feature

Currently, to fetch the pending block we need to go through the Blockchain tree:

https://github.com/paradigmxyz/reth/blob/fd12aba49c86d1d0da142f1efb2a8fd8b3e20c59/crates/blockchain-tree/src/blockchain_tree.rs#L230-L234

this tracks the pending block received from the CL:

https://github.com/paradigmxyz/reth/blob/fd12aba49c86d1d0da142f1efb2a8fd8b3e20c59/crates/blockchain-tree/src/block_indices.rs#L78-L86

we should make this available via shared state, ideally `tokio::sync::Watch<Option<SealedBlock>`

In order to do this we need to track two things:
* when we insert a new block into the tree, check if it's the pending block (parent_hash == canonical tip), and update the block in the watcher
* when we make a chain canonical: check if we can update the tracked pending block as well: https://github.com/paradigmxyz/reth/blob/fd12aba49c86d1d0da142f1efb2a8fd8b3e20c59/crates/blockchain-tree/src/blockchain_tree.rs#L1133-L1134

**Comment by Quertyy** [comment]
Can I take this one?

**Comment by mattsse** [comment]
that'd be great!
assigned, lmk if you need some pointers/questions

can also dm on tg @mattsse

**Comment by mattsse** [comment]
ref #6108

@Quertyy do you have the bandwidth to work on this? do you need any pointers?

**Comment by Quertyy** [comment]
> ref #6108
> 
> @Quertyy do you have the bandwidth to work on this? do you need any pointers?

Yes, no worries about bandwidth
I don't mind some pointers, I've already been able to understand the code base a little better

**Comment by loocapro** [comment]
Hi @Quertyy are you still working on this? If you don't have bandwidth I am happy to take it! 🙏

**Comment by Quertyy** [comment]
> Hi @Quertyy are you still working on this? If you don't have bandwidth I am happy to take it! 🙏

Hey, I should open a first draft before end of week :)

**Comment by mattsse** [comment]
@Quertyy any progress here?

if you don't have the bandwidth that's okay. This is now a blocker and I'd like to move forward with this

**Comment by Quertyy** [comment]
> @Quertyy any progress here?
> 
> 
> 
> if you don't have the bandwidth that's okay. This is now a blocker and I'd like to move forward with this

Hey, sorry but I can't get anything working and I have a lack of free time. Sorry for the lost time, it would be my pleasure to help on a feature more affordable for me 🫡

**Comment by mattsse** [comment]
hey @Quertyy, no worries! ty for trying.

we have a few more good first issues, if none of those are interesting to you, please let me know and we'll figure something out

**Comment by cfc-ctf** [comment]
#6286  is also related to this issue here

**Comment by AbnerZheng** [comment]
I will give it a try this weekend.
