### ISSUE TITLE
Write example on how to join other network p2p

### ISSUE THREAD

**Issue by Degen-Player** [paradigmxyz/reth#6127]
### Describe the change

Add example on how to join other network network (bsc or polygon)

**Comment by mattsse** [comment]
here's an example for polygon that could be converted into a new example

https://blog.merkle.io/blog/fastest-transaction-network-eth-polygon-bsc

cc @supernovahs perhaps interesting

**Comment by supernovahs** [comment]
I'll take this

**Comment by Degen-Player** [comment]
> here's an example for polygon that could be converted into a new example
> 
> https://blog.merkle.io/blog/fastest-transaction-network-eth-polygon-bsc
> 
> cc @supernovahs perhaps interesting

We should not use that since it is already as example, we don't want to do copy pasta, we should use that for BSC or for both bsc and polygon

**Comment by 0xMelkor** [comment]
Hi guys, if you run on polygon consider to set the network mode to `PoW`. This prevents the `NetworkManager` to disconnect peers that send blocks over the wire.

**Comment by mattsse** [comment]
I keep this open for BSC example
