### ISSUE TITLE
wsl2 can't build reth

### ISSUE THREAD

**Issue by Degen-Player** [paradigmxyz/reth#6128]
### Describe the bug

cyclic dependencies and a build error with libffi-sys

For instance, reth_auto_seal_consensus and reth depend on each other
for instance related to libffi sys
The build process is unable to find or create config.log, which suggests a possible issue with file paths, permissions, or missing dependencies
Environment variables like CC  are not set, which could mean the build process is unable to find a required compiler

The build script panicked while configuring libffi

### Steps to reproduce

clone main brench on wsl2

### Platform(s)

Windows (x86)

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by DaniPopes** [comment]
Can you post the full error message logs and compiler version (`rustc -Vv`)?
