### ISSUE TITLE
add example using reth revm sims 

### ISSUE THREAD

**Issue by Degen-Player** [paradigmxyz/reth#6145]
### Describe the feature

use reth revm crate for this, very easy to write a example, ask question if you need help on this task

**Comment by Degen-Player** [comment]
@mattsse add good first issue ticket here

**Comment by rakita** [comment]
`revm` already has a binary for these kinds of thing. and PR is already started by Charles: https://github.com/bluealloy/revm/pull/1039

**Comment by justcode740** [comment]
anyone take a look on this? if not, i can give it a try

**Comment by Degen-Player** [comment]
> anyone take a look on this? if not, i can give it a try

go for it

**Comment by AbnerZheng** [comment]
@justcode740 Are you still working on this issue? If not, maybe I can give it a try.
