### ISSUE TITLE
Finish Engine API implementation

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#616]
### Describe the feature

#551 introduced basic Engine API implementation. 

Items to be completed:

- [x] Review existing payload validation.
- [x] Execute payload on top of the current state.
- [ ] Review the existing `engine_forkchoiceUpdatedV1` handler and add a way to deal with reorgs detected within this handler.

Stretch:

- [ ] Add support for block building.

### Additional context

- [Engine spec](https://github.com/ethereum/execution-apis/tree/main/src/engine)
- [geth ConsensusAPI](https://github.com/ethereum/go-ethereum/blob/01808421e20ba9d19c029b64fcda841df77c9aff/eth/catalyst/api.go#L82)

**Comment by metafraction** [comment]
I can take this

**Comment by rkrasiuk** [comment]
@metafraction appreciate the initiative, but I'm currently working on this one. There are plenty of [good first issues](https://github.com/paradigmxyz/reth/issues?q=is%3Aopen+is%3Aissue+label%3AD-good-first-issue) to take on, encourage you to take a look

**Comment by mattsse** [comment]
`engine_` API is now fully implemented
