### ISSUE TITLE
impossible to compile reth in WSL2

### ISSUE THREAD

**Issue by Blaeaea** [paradigmxyz/reth#6170]
### Describe the bug

Latest rust version compiler (stable & nightly both doesn't compile) 

### Steps to reproduce

git clone https://github.com/paradigmxyz/reth/
cd reth
cargo build

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
Could you please paste the compilation error?
