### ISSUE TITLE
Implement arbitrary manually for NewPooledTransactions68

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6173]
### Describe the feature

with #6090 rlp decoding of the type enforces same length of the internal Vecs

The proptest strategy generates a fixed size of all vecs. It would be nice if the arbitrary implementation of this types generates a random fixed size instead

https://github.com/paradigmxyz/reth/blob/2b97e0cb9fa2b09ced58488c3dc2c9a79ad32bf9/crates/net/eth-wire/src/types/broadcast.rs#L262

## TODO

implement arbitrary manually for the type.
Perhaps the easiest approach would be to expand the macro, copy and modify the generated code

**Comment by supernovahs** [comment]
I can take this
