### ISSUE TITLE
arbitrary impl `NewPooledTransactionHashes`: choose sizes from limited range

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6202]
### Describe the feature

building onto https://github.com/paradigmxyz/reth/issues/6173, it would be helpful if the values generated for `sizes`, are limited to the range `0..0x20000`.

**Comment by emhane** [comment]
@supernovahs perhaps something you want to look into?

**Comment by supernovahs** [comment]
I'll take this
