### ISSUE TITLE
Stader Guardian is unable to send tx

### ISSUE THREAD

**Issue by yorickdowne** [paradigmxyz/reth#6205]
### Describe the bug

Sending tx via Stader Guardian fails. Pointing the app at a partial Geth archive instead works.

Tested with a Reth archive on Ethereum mainnet. Output from Stader Guardian:
```
New Exchange Rate data: {19072800 75029479908760713110197 73570042123220188356194}
Old Exchange Rate data: {19065600 75677193647928469732705 74211565812785576762603}
Submitting Exchange Rate price: {19072800 75029479908760713110197 73570042123220188356194}
Submitted transaction hash: 0x34fc20e1793965c22c83f9dd3e3a71f8c6954485e54f4e0b2001dd7733d0c73c
2024/01/24 11:24:44 failed to submit Exchange Rate: failed to check transaction status: transaction receipt not found after 10 minutes
```

### Steps to reproduce

Run any Stader Guardian duty against an archive Reth

### Node logs

```text
Debug logs are long. Please download from https://www.dropbox.com/scl/fi/811e6vfylw9jxsln2r5x5/reth-debug.txt?rlkey=63qvr4awlysuzwk9lboq7eemd&dl=0

Search for 0x34fc20e1793965c22c83f9dd3e3a71f8c6954485e54f4e0b2001dd7733d0c73c then go up a little to see the estimateGas, and the sendRawTransaction is right after that.
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.16 Commit SHA: d8a9b58 Build Timestamp: 2024-01-23T16:43:42.089594260Z Build Features:  Build Profile: maxperf

### What database version are you on?

1

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
I see, so it successfully submitted the tx but it appears the tx is stuck in the mempool.
The node has peers, so this either a broadcast issue or the tx isn't moved into the pending state.

could you please check if the tx is still in the pool and if its pending or queued via

https://github.com/paradigmxyz/reth/blob/dd2c6ead390eba9d624df81ae3b4259ad9cab5d1/book/jsonrpc/txpool.md#L5-L5

**Comment by yorickdowne** [comment]
Redid the test, here's the tx
```
Submitting Exchange Rate price: {19072800 75029479908760713110197 73570042123220188356194}
Submitted transaction hash: 0x1342147fec3e5c4c01ec2ec81f10cd0c1743942d71a63d969b43a52e9ce9d305
2024/01/24 18:01:43 failed to submit Exchange Rate: failed to check transaction status: transaction receipt not found after 10 minutes
```

When submitted, it's in `queued`. After timeout, it remains in `queued`.

[txpool-after-timeout.txt](https://github.com/paradigmxyz/reth/files/14042095/txpool-after-timeout.txt)
[txpool-when-submitted.txt](https://github.com/paradigmxyz/reth/files/14042097/txpool-when-submitted.txt)

**Comment by yorickdowne** [comment]
Reth is being run as `reth node --datadir /var/lib/reth --metrics 0.0.0.0:6060 --port 30303 --discovery.port 30303 --nat publicip --http --http.addr 0.0.0.0 --http.port 8545 --http.api web3,eth,net,txpool --http.corsdomain=* --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api web3,eth,net --ws.origins=* --authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.jwtsecret /var/lib/reth/ee-secret/jwtsecret --chain mainnet -vvv`

**Comment by yorickdowne** [comment]
That is a very good question. What do the logs from the first attempt show you? Is the app getting the right nonce from Reth for the sender address?

**Comment by mattsse** [comment]
so since the tx is submitted via sendRaw it is already signed with the nonce, so the nonce is chosen by the user, unclear how though.

I'm actually not sure about this here for eth_getTransactionCount with pending tag

https://github.com/paradigmxyz/reth/blob/575b5d3f53cb4ad820b30d88d578187ea62fa44c/crates/rpc/rpc/src/eth/api/state.rs#L62-L66

an interesting data point is, etherscan reports that the tx has 742 transactions (out+in), but could be unrelated

**Comment by yorickdowne** [comment]
It's got to be this part I am thinking:
```
eth-main-execution-1  | 2024-01-24T11:14:44.892411Z TRACE jsonrpsee_server::server: Request { method: POST, uri: /, version: HTTP/1.1, headers: {"host": "execution:8545",
 "user-agent": "Go-http-client/1.1", "content-length": "128", "accept": "application/json", "content-type": "application/json", "accept-encoding": "gzip"}, body: Body(Str
eaming) }
eth-main-execution-1  | 2024-01-24T11:14:44.892422Z TRACE jsonrpsee_core::http_helpers: HTTP response body: {"jsonrpc":"2.0","id":7643,"method":"eth_getTransactionCount",
"params":["0x561b5893f3de795dfd270d20b24d11ba5e05e696","pending"]}
eth-main-execution-1  | 2024-01-24T11:14:44.892429Z TRACE method_call{method="eth_getTransactionCount"}: jsonrpsee_core::tracing: recv="{\"jsonrpc\":\"2.0\",\"id\":7643,\
"method\":\"eth_getTransactionCount\",\"params\":[\"0x561b5893f3de795dfd270d20b24d11ba5e05e696\",\"pending\"]}"
eth-main-execution-1  | 2024-01-24T11:14:44.892436Z TRACE method_call{method="eth_getTransactionCount"}: jsonrpsee_types::params: [next_inner] Params JSON: "[\"0x561b5893
f3de795dfd270d20b24d11ba5e05e696\",\"pending\"]"
eth-main-execution-1  | 2024-01-24T11:14:44.892444Z TRACE method_call{method="eth_getTransactionCount"}: jsonrpsee_types::params: [next_inner] Params JSON: ",\"pending\"]
"
eth-main-execution-1  | 2024-01-24T11:14:44.892465Z TRACE method_call{method="eth_getTransactionCount"}: jsonrpsee_core::tracing: send="{\"jsonrpc\":\"2.0\",\"result\":\"
0x2f4\",\"id\":7643}"
```

**Comment by mattsse** [comment]
Oh interesting

```
eth-main-execution-1  | 2024-01-24T11:14:44.892422Z TRACE jsonrpsee_core::http_helpers: HTTP response body: {"jsonrpc":"2.0","id":7643,"method":"eth_getTransactionCount","params":["0x561b5893f3de795dfd270d20b24d11ba5e05e696","pending"]}
eth-main-execution-1  | 2024-01-24T11:14:44.892429Z TRACE method_call{method="eth_getTransactionCount"}: jsonrpsee_core::tracing: recv="{\"jsonrpc\":\"2.0\",\"id\":7643,\"method\":\"eth_getTransactionCount\",\"params\":[\"0x561b5893f3de795dfd270d20b24d11ba5e05e696\",\"pending\"]}"
eth-main-execution-1  | 2024-01-24T11:14:44.892436Z TRACE method_call{method="eth_getTransactionCount"}: jsonrpsee_types::params: [next_inner] Params JSON: "[\"0x561b5893f3de795dfd270d20b24d11ba5e05e696\",\"pending\"]"
eth-main-execution-1  | 2024-01-24T11:14:44.892444Z TRACE method_call{method="eth_getTransactionCount"}: jsonrpsee_types::params: [next_inner] Params JSON: ",\"pending\"]"
eth-main-execution-1  | 2024-01-24T11:14:44.892465Z TRACE method_call{method="eth_getTransactionCount"}: jsonrpsee_core::tracing: send="{\"jsonrpc\":\"2.0\",\"result\":\"0x2f4\",\"id\":7643}"
```
then the raw is submitted with same nonce 0x2f4 756

**Comment by yorickdowne** [comment]
Right. So ... how should `eth_getTranscountCount` for pending behave? Is this a matter of unclear specs, assumptions by the app, or a bug in Reth? I keep coming back to "it works with Geth", but am also very aware that we shouldn't say "supermajority client is always right" but should say "follow the spec, and the behavior of the supermajority client can be wrong"

**Comment by mattsse** [comment]
I see, this is slightly different than what reth does

https://github.com/ethereum/go-ethereum/blob/f55a10b64d511b27beb02ff4978a6ed66d604cd8/core/txpool/txpool.go#L334-L342

will get this fixed by mirroring geth, but I'm trying to find more info in the spec

**Comment by Rjected** [comment]
@yorickdowne do you mind retrying using this program, with reth logs enabled + whatever logs this program has? To solve this, I think we need to understand better what's going on exactly, and be able to trace where a specific transaction is going in the logs of both programs.

**Comment by yorickdowne** [comment]
You have those logs. What the program outputs is in https://github.com/paradigmxyz/reth/issues/6205#issuecomment-1908661986. You have the Reth logs that show the RPC calls and the response. I think the analysis at https://github.com/paradigmxyz/reth/issues/6205#issuecomment-1908733879 is spot-on

**Comment by mattsse** [comment]
upon closer inspection the geth implementation also does:
find the highest nonce in the pool + 1 for `eth_getTransactionCount(Pending)`

so still unclear what caused the high nonce here...

**Comment by yorickdowne** [comment]
Are you able to reproduce this?

**Comment by yorickdowne** [comment]
At this point I am unable to reproduce this. I'll close the issue and ask you to re-open should I see it again.

**Comment by mattsse** [comment]
cool!

I was also unable to reproduce this, I tested various things in --dev mode:

```
cast send -r http://localhost:8545 0x8a91dc2d28b689474298d91899f0c1baf62cb85b --value 1ether --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --nonce 11 --async
```

```
cast rpc eth_getTransactionCount "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266" "pending"
```

and couldn't find anything odd
