### ISSUE TITLE
Allow reth version to be set manually, based on binary

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6218]
I think we want a solution where the used version can be set manually,

for example if this is used by multiple binaries with different version (op-reth, reth), so let's open an issue for this feature?

_Originally posted by @mattsse in https://github.com/paradigmxyz/reth/pull/6195#pullrequestreview-1840163317_

**Comment by mattsse** [comment]
I think this can be done with a global once

**Comment by abhijeetbhagat** [comment]
@mattsse i can take this. what exactly needs to be done?

**Comment by Rjected** [comment]
> @Rjected @mattsse i can take this. what exactly needs to be done? what does setting reth version manually mean?

We essentially want a global value that users can change if they are importing reth and creating a different binary than the regular reth binary. This way, their metrics will reflect that value
