### ISSUE TITLE
cli-ext: payload builder constraints 

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#6219]
## Description

With the recent changes in the abstractions of the payload builder, it has become more difficult to override default builder behavior. It requires either using the provided `payload_builder` or implement a builder that's generic over payload arguments and what kind of payload it produces. It doesn't always make sense if you are implementing a payload builder only for ethereum or only for optimism.

https://github.com/paradigmxyz/reth/blob/ce010264b9210bb23d046e1e5f5954096c2887b3/bin/reth/src/cli/ext.rs#L131-L136

## Example Request

Create an example in `examples/` directory that implements an empty payload builder and spawns it instead in CLI extension `RethNodeCommandConfig::spawn_payload_builder_service`. 

Some existing doc code can be reused:
https://github.com/paradigmxyz/reth/blob/ce010264b9210bb23d046e1e5f5954096c2887b3/crates/payload/builder/src/lib.rs#L27-L89

**Comment by loocapro** [comment]
Hi @Rjected if you don't have bandwidth I am happy to take it. Thanks!
