### ISSUE TITLE
trap invalid opcode / illegal instruction (core dumped)

### ISSUE THREAD

**Issue by thorstenhirsch** [paradigmxyz/reth#6220]
### Describe the bug

When starting reth on an Intel i5-4278U it crashes du to an invalid opcode. Is the CPU too old?
Here's how the start looks like:
```
2024-01-24T20:35:33.589013Z  INFO reth::cli: reth 0.1.0-alpha.16 (d8a9b58) starting
2024-01-24T20:35:33.589052Z  INFO reth::cli: Opening database path="/some/reth-eth-mainnet-data/db"
2024-01-24T20:35:33.592394Z  INFO reth::cli: Configuration loaded path="/some/reth-eth-mainnet-data/reth.toml"
2024-01-24T20:35:33.593035Z  INFO reth::cli: Database opened
2024-01-24T20:35:33.593296Z  INFO reth::cli: Pre-merge hard forks (block based):
- Frontier                         @0
- Homestead                        @1150000
- Dao                              @1920000
- Tangerine                        @2463000
- SpuriousDragon                   @2675000
- Byzantium                        @4370000
- Constantinople                   @7280000
- Petersburg                       @7280000
- Istanbul                         @9069000
- MuirGlacier                      @9200000
- Berlin                           @12244000
- London                           @12965000
- ArrowGlacier                     @13773000
- GrayGlacier                      @15050000
Merge hard forks:
- Paris                            @58750000000000000000000 (network is not known to be merged)

Post-merge hard forks (timestamp based):
- Shanghai                         @1681338455

bash: line 1:  8314 Illegal instruction     (core dumped) reth node --datadir=/some/reth-eth-mainnet-data --nat=extip:(my-ip-removed) --full
```

dmesg:
```
[ 3670.918117] traps: reth[8077] trap invalid opcode ip:55e4ca2a212e sp:7ffe9930fca8 error:0 in reth[55e4c8000000+2d1a000]
```

### Steps to reproduce

1. Download reth alpha16 for Linux/x86
2. Run "reth node ..."

### Platform(s)

Linux (x86)

### What version/commit are you on?

alpha16

### What database version are you on?

(default)

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
Could you try running `make maxperf-no-asm` and let us know if it still errors?

**Comment by DaniPopes** [comment]
Before that can you open it in a debugger and print the stacktrace?

**Comment by mattsse** [comment]
> I believe we build dist binaries with RUSTFLAGS=native

oh? I don't think we should do that

**Comment by Rjected** [comment]
awesome, this helped narrow it down to blst, which conditions on the platform
https://github.com/supranational/blst/commit/83d78c2a122e8e1f643b6efb991247ff6689bb85

Let's introduce a `portable` feature to c-kzg-4844 which enables the blst `portable` feature.

**Comment by Rjected** [comment]
PR here: https://github.com/ethereum/c-kzg-4844/pull/389
