### ISSUE TITLE
trace block 11117104 insufficient gas

### ISSUE THREAD

**Issue by zzir** [paradigmxyz/reth#6238]
### Describe the bug

request:
```bash
curl -X "POST" "http://127.0.0.1:8545/" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "debug_traceBlockByNumber",
  "params": [
    "0xA9A230",
    {
      "tracerConfig": {
        "diffMode": true
      },
      "tracer": "prestateTracer"
    }
  ]
}'

```

response:
```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32003,
    "message": "insufficient funds for gas * price + value"
  },
  "id": 0
}
```

### Steps to reproduce

do call `debug_traceBlockByNumber` api

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.16

### What database version are you on?

Current database version: 1

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

RUSTFLAGS="-C target-cpu=native" cargo build --profile maxperf

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by joshieDo** [comment]
Not able to reproduce on beta.2 and alpha.21. Is it still an issue? @zzir

**Comment by zzir** [comment]
> Not able to reproduce on beta.2 and alpha.21. Is it still an issue? @zzir 

node beta.2 is in a fresh sync, I will test again after the sync is complete.

**Comment by zzir** [comment]
this issue has been fixed. Great!
