### ISSUE TITLE
BlockOverride:baseFee is not working for CallMany and TraceCall

### ISSUE THREAD

**Issue by corentindenoeud** [paradigmxyz/reth#6240]
### Describe the bug

When overriding the baseFee for TraceCall and CallMany, it's value is not considered.

If we do a traceCall or CallMany on a transaction with a MaxFeePerGas of 1 Wei and we override the block base fee at 100 GWei we should have an error saying that the maxFeePerGas is not sufficient.

### Steps to reproduce

Do a trace call (or CallMany) on any transaction  that has a maxFeePerGas of 1 Wei and override the block base fee with 100 GWei : 

For traceCall : 

```
curl -X "POST" "http://127.0.0.1:8543/" \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d $'{ 
                "jsonrpc": "2.0",
                "id": 0,
                "method": "trace_call",
                "params": [
                {
                    "from": "0x000000000000000000000000000000000000dEaD",
                    "to": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
                    "gas": "0x61a80",
                    "maxFeePerGas":"0x1",                     
                    "maxPriorityFeePerGas":"0x1",
                    "nonce": "0x0",
                    "value": "0x0",
                    "data": "0x70a0823100000000000000000000000088e6a0c2ddd26feeb64f039a2c41296fcb3f5640",
                    "type": "0x2"
                },
                ["trace"],                              
                "0x12349d0",                              
                {},                                     
                {"baseFee":"0x174876E800"}               
                ]
                }'
```

For call Many :

```
curl -X "POST" "http://127.0.0.1:8543/" \
        -H 'Content-Type: application/json; charset=utf-8' \
        -d $'{ 
              "jsonrpc": "2.0",
              "id": 0,
              "method": "eth_callMany",
              "params": [
              {
                  "transactions":[
                          {
                              "from": "0x000000000000000000000000000000000000dEaD",
                              "to": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
                              "gas": "0x61a80",
                              "maxFeePerGas":"0x1",                     
                              "maxPriorityFeePerGas":"0x1",
                              "nonce": "0x0",
                              "value": "0x0",
                              "data": "0x70a0823100000000000000000000000088e6a0c2ddd26feeb64f039a2c41296fcb3f5640",
                              "type": "0x2"
                          }],
                  "blockOverride":{"baseFee":"0x174876E800"} 
              },                            
              {"blockNumber":"0x12349d0"}           
              ]
              }'
```

Response Call Many 

`{"jsonrpc":"2.0","result":[{"value":"0x0000000000000000000000000000000000000000000004ed16fd3e38c58560d1"}],"id":0}`

Response Trace Call 

`{"jsonrpc":"2.0","result":{"output":"0x0000000000000000000000000000000000000000000004ed16fd3e38c58560d1","stateDiff":null,"trace":[{"type":"call","action":{"from":"0x000000000000000000000000000000000000dead","callType":"call","gas":"0x61a80","input":"0x70a0823100000000000000000000000088e6a0c2ddd26feeb64f039a2c41296fcb3f5640","to":"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","value":"0x0"},"result":{"gasUsed":"0x5d9e","output":"0x0000000000000000000000000000000000000000000004ed16fd3e38c58560d1"},"subtraces":0,"traceAddress":[]}],"vmTrace":null},"id":0}`

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.15

### What database version are you on?

N/A

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

None

### Code of Conduct

- [x] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
okay, so basefee is disabled in eth_call but enabled in traceCall

eth_call

https://github.com/ledgerwatch/erigon/blob/513fd50fa501ab6385dc3f58b18079d806d6ff5a/turbo/transactions/call.go#L86-L86

traceCall

https://github.com/ledgerwatch/erigon/blob/513fd50fa501ab6385dc3f58b18079d806d6ff5a/turbo/transactions/tracing.go#L184-L184

**Comment by mattsse** [comment]
I did some digging in #6246 and it looks like the behaviour re basefee is not consistent across clients.
personally disabling basefee doesn't really make sense to me but perhaps there's a reason for disabling it in trace call related endpoints.

**Comment by corentindenoeud** [comment]
Would be great if it could works in both eth_call and trace_call (and eth_call_many &  trace_call_many). If i remember well from erigon contributor, this was not an intented behavior in Erigon and they had to fix it

**Comment by corentindenoeud** [comment]
Hi @mattsse,

I have updated with the latest alpha and I see some behavior change. What was the last change on this matter ? thank you.

When doing a CallMany or TraceCall, I have lot of "max fee per gas less than block base fee" that I didn't have before.

**Comment by mattsse** [comment]
@corentindenoeud could you try against http://69.67.151.138:8545 and see if this is still the case there?

**Comment by mattsse** [comment]
@corentindenoeud ah the issue here is that you override the basefee but your tx's fee is lower

https://github.com/paradigmxyz/reth/blob/28f3a2e2d9525bf2f6373e755e2d6dc0c2f97821/crates/rpc/rpc/src/eth/revm_utils.rs#L469-L472

I believe this is also how other clients behave here, although with a better error message

```
{
    "id": 0,
    "jsonrpc": "2.0",
    "error": {
        "message": "fee cap less than block base fee: address 0x000000000000000000000000000000000000dEaD, gasFeeCap: 1 baseFee: 85222968270",
        "code": -32000
    }
}```

**Comment by mattsse** [comment]
But I think there's something else wrong here, checking

**Comment by corentindenoeud** [comment]
@mattsse  I have tested locally your changes and it works ! Thank you ! That was fast !
