### ISSUE TITLE
An unexpected `OutOfFund` call trace is produced

### ISSUE THREAD

**Issue by lukekim** [paradigmxyz/reth#6254]
### Describe the bug

A unexpected `OutOfFund` call trace is produced for transaction `0x105707c8e3b3675a8424a7b0820b271cbe394eaf4d5065b03c273298e3a81314`.

```json
{
                        "from": "0x8ba8ceecdcb00bee67a0e9acc0c23f4ef433857e",
                        "gas": "0x1e8e5",
                        "gasUsed": "0x0",
                        "to": "0xdafea492d9c6733ae3d56b7ed1adb60692c98bc5",
                        "input": "0x",
                        "error": "OutOfFund",
                        "value": "0xa39521c9636027bac0f37a7b47a16052ac007f7a",
                        "type": "CALL"
}
```

This trace is only returned by Reth and *not* by Geth. See attached JSON outputs.

- [geth.json](https://github.com/paradigmxyz/reth/files/14070616/geth.json)
- [reth.json](https://github.com/paradigmxyz/reth/files/14070617/reth.json)

Etherscan parity traces: https://etherscan.io/vmtrace?txhash=0x105707c8e3b3675a8424a7b0820b271cbe394eaf4d5065b03c273298e3a81314&type=parity#raw

### Steps to reproduce

Make the JSON RPC call:

```bash
curl --request POST \
  --url 'http://localhost:8545/' \
  --header 'Content-Type: application/json' \
  --data '{
    "jsonrpc": "2.0",
    "method": "debug_traceBlockByNumber",
    "id": 0,
    "params": [
        "0x1232B58",
        {
            "tracer": "callTracer"
        }
    ]
}
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.14 Commit SHA: 573c73f Build Timestamp: 2024-01-10T11:06:23.575561916Z Build Features: default,jemalloc Build Profile: maxperf

### What database version are you on?

Current database version: 1
Local database is uninitialized

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
I'm closing this because this is a real call, it's just not recorded by geth's tracer because the value transfer check in geth happens before capturing the call, see also:

https://github.com/paradigmxyz/reth/issues/3523#issuecomment-1641571054
