### ISSUE TITLE
missing "memory" field from debug_traceTransaction

### ISSUE THREAD

**Issue by 0xSt1ng3R** [paradigmxyz/reth#6255]
### Describe the bug

in erigon, a step in debug_traceTransaction default view looks like:
```json
{
  "depth": 1,
  "gas": 306596,
  "gasCost": 3,
  "op": "MSTORE",
  "pc": 7579,
  "stack": [
    "0xdd",
    "0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffed25c",
    "0x24"
  ],
  "memory": [
    "0x0000000000000000000000000000000000000000000000000000000000000000",
    "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
  ]
}
```

in reth, it is missing the "memory" field, making reth unusable for certain debugging applications:
```json
{
  "depth": 1,
  "gas": 306596,
  "gasCost": 3,
  "op": "MSTORE",
  "pc": 7579,
  "stack": [
    "0xdd",
    "0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffed25c",
    "0x24"
  ]
}
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

```
reth Version: 0.1.0-alpha.16
Commit SHA: 33b14a1
Build Timestamp: 2024-01-26T04:40:09.728037151Z
Build Features: jemalloc
Build Profile: maxperf
```

### What database version are you on?

```
Current database version: 1
Local database version: 1
```

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by 0xSt1ng3R** [comment]
I just found out that there is an enableMemory flag in tracerConfig...
But I don't see how to use it with the [default tracer](https://github.com/alloy-rs/alloy/blob/main/crates/rpc-trace-types/src/geth/mod.rs#L110)? the closest way seems like that, but it doesn't work:
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "debug_traceTransaction",
    "params": [<tx_hash>, {"tracer": "default", "tracerConfig": {"enableMemory": True}}]
}
```

**Comment by mattsse** [comment]
try

```json
{  "enableMemory": true}
```

**Comment by 0xSt1ng3R** [comment]
> try
> 
> ```json
> {  "enableMemory": true}
> ```

nice thank you!

haha it's a little confusing... as all the others have params, but the default is not...
```
["tx_hash", {"tracer": "callTracer", "tracerConfig": {"onlyTopCall": True, "withLog": False}}]
```
vs.
```
["tx_hash", {"enableMemory": true}]
```

any plans to change that?
