### ISSUE TITLE
Add RLP encoding support for IpAddr

### ISSUE THREAD

**Issue by MegaRedHand** [paradigmxyz/reth#628]
### Describe the feature

Currently, `net::Octets` from _primitives_ crate is a copy of `std::net::IpAddr` with `Encodable` `Decodable` support. I propose:

- [x] add `Encodable` `Decodable` support for `std::net::IpAddr` in _rlp_ crate
- [x] use `std::net::IpAddr` instead of `Octets`
- [x] remove `Octets`

**Comment by mattsse** [comment]
sg, we need to put this behind a cfg with feature = `std`
