### ISSUE TITLE
Pending transaction pool empties with huge number of pending pool imports

### ISSUE THREAD

**Issue by ArtificialPB** [paradigmxyz/reth#6282]
### Describe the bug

Latest version randomly sends a large number of transaction requests to other peers, causing a huge number of pending pool imports. When it happens, it seems to almost fully clear the pending transaction pool, along with frequent fill and clear of queued pool. See attached screenshot for reference.

Most likely causing this issue as well: https://github.com/paradigmxyz/reth/issues/6280

I assume this is due to latest txfetcher changes, but haven't dug too deep yet: https://github.com/paradigmxyz/reth/pull/6012

<img width="1984" alt="Screenshot 2024-01-30 at 11 41 46" src="https://github.com/paradigmxyz/reth/assets/4672155/5570f4b3-0d02-4d9d-a7bc-92f9918797f2">

Graph showing before/after. The node was updated at the time when huge number of pending pool imports start appearing. 
<img width="997" alt="Screenshot 2024-01-30 at 11 47 31" src="https://github.com/paradigmxyz/reth/assets/4672155/873e7f43-48ca-470f-a1d5-98353a22eeb1">

### Steps to reproduce

1. Run the latest version
2. Keep running for a few hours

### Platform(s)

Linux (x86)

### What version/commit are you on?

v0.1.0-alpha.16 

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
@Rjected those large dips in the last graph right when the pool hits the 10k limit look very odd

@ArtificialPB was the node restarted several times?

@emhane I assume what's happening here is that tx fetching is too aggressive? with ~400 active requests at a time that eventually saturates the pool insert queue.

**Comment by ArtificialPB** [comment]
@mattsse It was restarted 4 times after new version was deployed. 

I had a quick look and noticed that each tx is imported individually, maybe importing them in batches would help with lock contention in the pool?

**Comment by mattsse** [comment]
@ArtificialPB thanks for this report

there was an eviction bug #6284 that is definitely related, but perhaps there's more
also improving the insert process

**Comment by emhane** [comment]
that means blob txns, guessed by @Rjected at 131 072 bytes, are requested singly, since they surpass the soft limit already.

link to specs btw https://github.com/ethereum/devp2p/blob/master/caps/eth.md#newpooledtransactionhashes-0x08

**Comment by ArtificialPB** [comment]
Amount of pending pool imports has skyrocketed in the last 12 hours, and it's been pretty much up-only since then. Pending/queued/base fee pools have stayed flat for the last 4 hours. 

Stopped all of our external dependents on the transaction pool (the crosshair on the graph), and the queue started clearing after ~8min, but stopped after about 30% cleared. Could be coincidence but makes me think it could be related?

Looking at the flamegraph right after I stopped our external dependents, it's dominated by tx fetcher.

<img width="1981" alt="Screenshot 2024-01-31 at 18 34 16" src="https://github.com/paradigmxyz/reth/assets/4672155/777dbbc5-930f-4800-993f-bd7360354e01">

<img width="2049" alt="Screenshot 2024-01-31 at 18 37 06" src="https://github.com/paradigmxyz/reth/assets/4672155/6238437f-a137-44c9-b08d-e278ea19fb28">

**Comment by emhane** [comment]
> Amount of pending pool imports has skyrocketed in the last 12 hours, and it's been pretty much up-only since then. Pending/queued/base fee pools have stayed flat for the last 4 hours.
> 
> Stopped all of our external dependents on the transaction pool (the crosshair on the graph), and the queue started clearing after ~8min, but stopped after about 30% cleared. Could be coincidence but makes me think it could be related?
> 
> Looking at the flamegraph right after I stopped our external dependents, it's dominated by tx fetcher.
> 
> <img alt="Screenshot 2024-01-31 at 18 34 16" width="1981" src="https://private-user-images.githubusercontent.com/4672155/301253970-777dbbc5-930f-4800-993f-bd7360354e01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjQ1NTEsIm5iZiI6MTcwNjcyNDI1MSwicGF0aCI6Ii80NjcyMTU1LzMwMTI1Mzk3MC03NzdkYmJjNS05MzBmLTQ4MDAtOTkzZi1iZDczNjAzNTRlMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTgwNDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjkxMGM0YzAwMTU0ODgxNTNjNzFjNjQzNTRiZmQ5N2M1YjY3ZDY2MGFhNWQ4ZDE3MGU3MWIxYmE3NGYxZDY4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CkPUV0jilE-jmh2uHMAwqqI7COwCfxdFuYgEoux-GhA"> <img alt="Screenshot 2024-01-31 at 18 37 06" width="2000" src="https://private-user-images.githubusercontent.com/4672155/301254653-6238437f-a137-44c9-b08d-e278ea19fb28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjQ1NTEsIm5iZiI6MTcwNjcyNDI1MSwicGF0aCI6Ii80NjcyMTU1LzMwMTI1NDY1My02MjM4NDM3Zi1hMTM3LTQ0YzktYjA4ZC1lMjc4ZWExOWZiMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTgwNDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQxZjYwYjgzNjY3YzEwZjNiMDA1YzdjZTBkNTM1NzczMzU2NDQ2MThlNDAxZTk5MmFjMjIxY2I5NjI4MzA5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y7hEi5kB1HPubNuFktskkk9oTp_y4sfpFHrutNabJA4">

thanks for the nice stats. this is definitely related. the limit for responses was increased from 128 KB to 2MB. so more transactions are being fetched in a shorter time. naturally, since your batch pr wasn't merged yet, that increases the pending imports at first. hopefully with the batch code merged, the increased response soft limit, will make sure batches aren't 1 tx big. feel free to set this constant yourself https://github.com/paradigmxyz/reth/blob/34cda3a99f399dd53018fa33b82a8296711df80a/crates/net/network/src/transactions/mod.rs#L83, aiming to expose it in cli. if you do, please share what value works best.

**Comment by emhane** [comment]
@ArtificialPB thanks for the nice stats. this is definitely related. the limit for responses was increased from 128 KB to 2MB. so more transactions are being fetched in a shorter time. naturally, since your batch pr wasn't merged yet, that increases the pending imports at first. hopefully with the batch code merged, the increased response soft limit, will make sure batches aren't 1 tx big. feel free to set this constant yourself https://github.com/paradigmxyz/reth/blob/34cda3a99f399dd53018fa33b82a8296711df80a/crates/net/network/src/transactions/mod.rs#L83, aiming to expose it in cli. if you do, please share what value works best.

**Comment by emhane** [comment]
https://github.com/paradigmxyz/reth/pull/6284 closes this. the issue has shined light on tx fetcher's insufficient inability to assist in recovery from suboptimal node conditions, temporarily handled here https://github.com/paradigmxyz/reth/pull/6384. the goal to enable refetch logic, originally mentioned in https://github.com/paradigmxyz/reth/issues/5192, persists. refetch logic is currently being simplified in https://github.com/paradigmxyz/reth/pull/6318.

**Comment by ArtificialPB** [comment]
Can confirm the issue has been resolved with the v0.1.0-alpha.17 release. Running it for the last 24 hours without problems. 

Appreciate the quick resolution
