### ISSUE TITLE
Faster newHead notifications

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6286]
### Describe the feature

Currently we're emitting a new chain event after we've committed new block(s) to disk on FCU

By this time we already know the chain is valid but need to flush to disk first to update the "latest". A db commit is only expected to fail in the event of a db error because the new chain has been validated.
This guarantees that once we've emitted a new chain event the corresponding state for the new head is available.
This is also slow and means that newHead updates can be trailing by a few 100ms.

When we're committing a new block we have the corresponding (valid) state in memory, which means we could map this to the "latest" tag right away and emit a chain update earlier.

Emitting chain updates before the db commit could introduce a few race conditions, for example
user receives newHead event, queries state using the newHead's hash, which is currently being inserted.

To mitigate these, we'd need to keep track of in progress inserts and account for this, we also need to make the state that's being inserted available before we emit the event:

```rust
struct LatestState {
  committing: AtomicBool,
  latestState: RwLock<Option<Block + State>>
}
```

which needs to be checked by the provider when handling BlockId conversions, this part needs to cover all edge cases.

Reorgs and multiblock commits are problematic and even more complex, so those should be processed as we do currently.

this is somewhat related to #6104

**Comment by allnil** [comment]
Maybe I can take a look?

**Comment by mattsse** [comment]
we haven't decided on a path forward for this but eventually, there'll be some tasks

**Comment by cfc-ctf** [comment]
Getting the head block with the same speed as `geth` is critical for many kinds of real-time chain analytics.

**Comment by bsh98** [comment]
this is important! happy to help

**Comment by geomad** [comment]
I run both geth and reth, and just keeping geth atm because I need fast heads.

If reth can notify and access state as fast as geth, I can finally drop geth and just relay on reth, as it will  be on par or better in all aspects.

This will be nice to have since running multiple nodes it's a bit of headache and have its problems (bandwidth, storage etc)

I think many other people are in the same situation as me.

**Comment by cfc-ctf** [comment]
Any progress om this one?

**Comment by cfc-ctf** [comment]
Will this fix arrive in the Beta version?

**Comment by cfc-ctf** [comment]
+1 on this one.

(I remember there was another issue opened about the same topic)

**Comment by mattsse** [comment]
closing in favor #8742 which solves this
