### ISSUE TITLE
Improve e2e test coverage foor pool at capacity

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6292]
### Describe the feature

see #6282 

basically, some "fuzzing" with pool at capacity:
* senders with multiple txs
* all pools at capacity
* ...

This should use the actual pool (testing_pool()| mock_pool) and be in /it/evict.rs or smth

**Comment by Rjected** [comment]
solved by https://github.com/paradigmxyz/reth/pull/6437 i think
