### ISSUE TITLE
Add a `Headers` structure

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#6293]
### Describe the feature

In the current codebase, we frequently utilize the `Vec<Header>` structure. Inspired by the approach suggested in [this pull request](https://github.com/paradigmxyz/reth/pull/6267) for `Withdrawals`, it seems beneficial to introduce a dedicated `Headers` struct type. This new struct would encapsulate the vector of `Header` instances, promoting better code organization and maintainability.

### Proposed Changes

The proposed changes involve the creation of a `Headers` struct that internally manages a `Vec<Header>`. This encapsulation not only provides a more coherent representation but also facilitates future enhancements.

### Motivation

1. **Code Clarity:** Introducing a dedicated `Headers` struct enhances code readability by clearly expressing the intent of handling a collection of headers.

2. **Abstraction:** The new struct abstracts away the internal representation of headers, allowing for easier modifications or optimizations in the future.

3. **Consistency:** Following a similar pattern as seen in [PR #6267](https://github.com/paradigmxyz/reth/pull/6267) for `Withdrawals` promotes consistency within the codebase.

**Comment by dannou812** [comment]
Hi, I would like to work on this issue, is it still available?

**Comment by Rjected** [comment]
> Hi, I would like to work on this issue, is it still available?

we generally review PRs on a first come first serve basis, so feel free to submit a PR!
