### ISSUE TITLE
Remove semantically identical data in TransactionsManager

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6304]
### Describe the feature

for the purpose of rate limiting tx requests to max inflight requests per tx hash at any given time, we can remove this
https://github.com/paradigmxyz/reth/blob/add3c6a3a2ae0cecd8627533bbc5688a456435ad/crates/net/network/src/transactions/mod.rs#L206-L210
in favour of `active_peers` and `inflight_requests` in `TransactionFecther` that already handle this.

in order to do so, we need to execute the code for creating transaction import futures from here https://github.com/paradigmxyz/reth/blob/add3c6a3a2ae0cecd8627533bbc5688a456435ad/crates/net/network/src/transactions/mod.rs#L935-L935
...to somewhere here, where we have got unknown previously unseen hashes (new hashes)
https://github.com/paradigmxyz/reth/blob/add3c6a3a2ae0cecd8627533bbc5688a456435ad/crates/net/network/src/transactions/mod.rs#L593

makes sense to complete after https://github.com/paradigmxyz/reth/issues/6289

**Comment by int88** [comment]
But `transactions_by_peers` still could be used to penalize peers on `on_bad_import()` ? 😄

**Comment by emhane** [comment]
> But `transactions_by_peers` still could be used to penalize peers on `on_bad_import()` ? 😄

very true, we have given `transactions_by_peers` a lot of new purpose since this issue was opened. well spotted.
