### ISSUE TITLE
remove proptest-specific encoding logic from Header

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6329]
### Describe the feature

This code needs to be removed, along with the similar looking code in that file:
https://github.com/paradigmxyz/reth/blob/e03544bd5cd4bbbfbf0395c38860f975038ae9ff/crates/primitives/src/header.rs#L521-L572

We need to fix the `proptest::arbitrary::Arbitrary` implementation to only include i.e. `excess_blob_gas` if all previous fork specific fields exist.
https://github.com/paradigmxyz/reth/blob/e03544bd5cd4bbbfbf0395c38860f975038ae9ff/crates/primitives/src/header.rs#L616-L633

**Comment by supernovahs** [comment]
Let me take this

**Comment by Rjected** [comment]
> Let me take this

hey! feel free to submit a PR and I'll review
