### ISSUE TITLE
Add eth_blobBaseFee

### ISSUE THREAD

**Issue by allnil** [paradigmxyz/reth#6330]
### Describe the feature

Implement upcoming changes to eth_feeHistory: [https://github.com/ethereum/execution-apis/pull/486](https://github.com/ethereum/execution-apis/pull/486)
@mattsse

**Comment by AbnerZheng** [comment]
Can I give it a try?

**Comment by mattsse** [comment]
oh yeah, we added this already but apparently the name changes:

https://github.com/paradigmxyz/reth/blob/84b13286f0046df773ace64902301ec805d55b6a/crates/rpc/rpc/src/eth/api/server.rs#L301-L305

would you like to submit a PR that rename this accordingly?

**Comment by AbnerZheng** [comment]
Sure
