### ISSUE TITLE
introduce `try_` conversion method for payload v3

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6331]
### Describe the feature

Currently we use the following conversion to convert blocks into `ExecutionPayloadV3`:
https://github.com/paradigmxyz/reth/blob/231e6437e4a052ed06c6eb29d38948b42d2f8899/crates/rpc/rpc-types-compat/src/engine/payload.rs#L212-L213

We have the `try_block_to_payload_v2` and `try_block_to_payload_v1` methods, but no `try_block_to_payload_v3` method. This method should be created.

This would allow us to create a fallible conversion between built payloads and `ExecutionPayloadV3` here, which could be done in a followup:
https://github.com/paradigmxyz/reth/blob/9f82af20f96919146d82cb2cdfc00bc952264c5e/crates/payload/builder/src/payload.rs#L124

**Comment by 1010adigupta** [comment]
would like to take this :)

**Comment by Rjected** [comment]
> would like to take this :)

awesome, feel free to submit a PR and ping me for review!

**Comment by justcode740** [comment]
in the queue if prev person time out.

**Comment by Rjected** [comment]
> in the queue if prev person time out.

sure, feel free to work on it!

**Comment by Rjected** [comment]
just assigned!

**Comment by justcode740** [comment]
> built payloads and `ExecutionP`

@Rjected but even `try_block_to_payload_v1` and `try_block_to_payload_v2` doesn't return a Result, and current `block_to_payload_v3` seem has no reason to fail? wonder what need to be done here.

**Comment by mattsse** [comment]
we have tryfrom conversions now
