### ISSUE TITLE
Move error data from `error.data` to `error.message` for failing rpc-compat calls

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6332]
### Describe the feature

ref https://github.com/ethereum/hive/pull/975#issuecomment-1921611234

We should, where possible, prevent using the `error.data` field if the error message can be contained in the `error.message` field.

This includes, but is not limited to `debug_getRawReceipts`.

Analyzing the `rpc-compat` suite failures is the best way to understand every call that needs a change in error message:
https://github.com/paradigmxyz/reth/actions/runs/7734052427/job/21088043313

**Comment by emhane** [comment]
so this originates from here you mean @Rjected ?

https://github.com/paradigmxyz/reth/blob/de6332b51e9d4bdf9d3e75a1523ff1cdfb862686/crates/rpc/rpc/src/eth/error.rs#L408-L422

and the solution is: control that the output field on `RevertError` is only used by spec error codes, not custom errors?

https://github.com/paradigmxyz/reth/blob/de6332b51e9d4bdf9d3e75a1523ff1cdfb862686/crates/rpc/rpc/src/eth/error.rs#L491-L500

links to where in specs the errors can be found?

**Comment by Rjected** [comment]
> links to where in specs the errors can be found?

there are no specs for rpc errors, the hive tests are considered the spec more or less

We basically cannot use the `data` field here:
https://github.com/paradigmxyz/reth/blob/fadc7b02a9f46192bd0eaa6c2e4c74cea0f490e5/crates/rpc/rpc/src/result.rs#L137-L140
