### ISSUE TITLE
add AccountHashingStage and StorageHashingStage

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#634]
To prepare the state for merklelization, Account addresses need to be hashed with `keccak256` and all storage keys (Even if there are H256) need to be hashed `keccak256`.

There are two tables here:
* `HashedAcccounts: H256(keccak256(Address)) -> AccountInfo (balance,nonce,code_hash) ` Basic info is needed as it is hashed inside Merkle trie and for partial update of storage we would need to have ability to hash it. 
* `HashedStorage: DubSorted  H256(keccak256(Address)) -> (SubKey(H256(keccak256(key)), Value)`

**Comment by entropidelic** [comment]
I would really like to start working on this. Let me outline the process as I understand it:
- Two modules inside the stages crate should be added: `account_hashes` and `storage_hashes` 
- Create structs `AccountHashStage` and `StorageHashStage`
- Implement the `Stage` trait on them
- Push stages into the pipeline
- Add tables `HashedAcccounts` and `HashedStorage`

I’m a little more hazy on the actual implementation of  execute  for the Stage trait, but IIUC the outline is as follows:
- If syncing from genesis, or if the difference of max gas and current gas is greater than a threshold set at configuration:
    - `HashedAccounts` should be cleared
    - Loop over the `Accounts` table, hash each accounts address and push each entry to HashedAccounts as `H256(keccak256(address)) => AcountInfo`
- else:  still working on this.

**Comment by gakonst** [comment]
Are we sure we want to hash all the leaves of the tree and store them on disk? Sounds weird to me? Don't we want to only store the intermediate hashes in the state tree, as otherwise we're gonna blow everything up in terms of space?

**Comment by rakita** [comment]
Impl is close to be finished here: https://github.com/paradigmxyz/reth/tree/rakita/hashing_stages
Tests are missing

**Comment by rakita** [comment]
> Are we sure we want to hash all the leaves of the tree and store them on disk? Sounds weird to me? Don't we want to only store the intermediate hashes in the state tree, as otherwise we're gonna blow everything up in terms of space?

Yes, either way, we are storing hashes of it somewhere as for partial update we will need node hashes, Merkle trie is done on sorted array of hashed keys, so order matter. Shouldn't be a big deal for space, but idk the obvious impact.

**Comment by entropidelic** [comment]
We have tests, I'll push them and move the PRs out of draft. Maybe we can merge your branch?

**Comment by MegaRedHand** [comment]
Just pushed last changes to https://github.com/paradigmxyz/reth/pull/704
The implementation is working, and it has a `StageTestRunner`, along with custom tests.

**Comment by rakita** [comment]
Here is the draft: https://github.com/paradigmxyz/reth/pull/756
Unwind for StorageHasher is still missing, and tests of course. But it reads changesets in a bundle for more performant reads, and it writes them in a sorted way back so that cursor will not panic.

**Comment by rakita** [comment]
@MegaRedHand @entropidelic hope it is okay if I take tests and use them, they are great?

**Comment by entropidelic** [comment]
@rakita of course, go ahead :). Would you like us to make a PR to your branch adding the tests?

**Comment by rakita** [comment]
@entropidelic I can do it. Thank a lot!

**Comment by rakita** [comment]
finished
