### ISSUE TITLE
Report human-readable errors instead of MDBX error codes

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#6342]
### Describe the feature

https://github.com/paradigmxyz/reth/pull/5955 added human-readable descriptions for MDBX errors, but they're still not passed upstream, so the user sees just the error codes in the terminal.

For example, if you manually corrupt (flip a couple of bits) the database file and try to open it, we just report an internal code and nothing else:
```consoe
Error: Could not open database at path: ../reth-datadir-corr/db

Caused by:
    failed to open the database (-30419)

Location:
    crates/storage/db/src/lib.rs:128:14
```
but in reality we can report a nice error message https://github.com/paradigmxyz/reth/blob/4e5ae6c540fb8085ee102586c5caf1cd20379e4b/crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h#L1914 https://github.com/paradigmxyz/reth/blob/4e5ae6c540fb8085ee102586c5caf1cd20379e4b/crates/storage/libmdbx-rs/src/error.rs#L91-L94

The same applies to kernel errors, e.g.:
- Permission denied
```console
Error: Could not open database at path: chain/reth/data/db

Caused by:
    failed to open the database (13)

Location:
    crates/storage/db/src/lib.rs:128:14
```
- File not found
```console
Error: Could not open database at path: /home/ubuntu/.local/share/reth/mainnet/db

Caused by:
    failed to open the database (2)

Location:
    crates/storage/db/src/lib.rs:128:14
```

**Comment by sevazhidkov** [comment]
Would love to take this on.
