### ISSUE TITLE
Add missing blob sub pool metrics

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6347]
### Describe the feature

Add metrics for blob subpool to https://github.com/paradigmxyz/reth/blob/4e5ae6c540fb8085ee102586c5caf1cd20379e4b/crates/transaction-pool/src/metrics.rs#L11-L11

just like:

https://github.com/paradigmxyz/reth/blob/4e5ae6c540fb8085ee102586c5caf1cd20379e4b/crates/transaction-pool/src/metrics.rs#L24-L27

update:

https://github.com/paradigmxyz/reth/blob/4e5ae6c540fb8085ee102586c5caf1cd20379e4b/docs/design/metrics.md#L75-L75

and include them in the dashboard:

https://github.com/paradigmxyz/reth/blob/4e5ae6c540fb8085ee102586c5caf1cd20379e4b/etc/grafana/dashboards/overview.json#L3468-L3478

https://github.com/paradigmxyz/reth/blob/4e5ae6c540fb8085ee102586c5caf1cd20379e4b/etc/grafana/dashboards/overview.json#L3585-L3595

**Comment by Rjected** [comment]
Fixed with https://github.com/paradigmxyz/reth/pull/6373
