### ISSUE TITLE
Failed to open the database(30)

### ISSUE THREAD

**Issue by argakiig** [paradigmxyz/reth#6354]
### Describe the bug

I have created a read only volume with a snapshot of the reth data directory with the intent of reading the db only.
When subsequently opening the DB from a volume mounted as read_only I get `Failed to open the database(30)`

### Steps to reproduce

1. Run Reth in kube context with PVC
2. Create snapshot of PVC
3. Spin up readonly PVC of snapshot
4. Start workload in kube with volume mounted as read only
5. check logs and see unable to openDB

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth version was 12 when snapshot was taken

### What database version are you on?

reth version was alpha.12 when snapshot was taken

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by argakiig** [comment]
further context.
When this is done using a GCE PD mounted as read only(ro,noload) this works
When moved over to GKE and using a PVC mounted as read only and running from within a container error 30 is returned

**Comment by argakiig** [comment]
It seems like even though the DB is being openned as read only the mdbx.lck is being written to. To test this out further I was able to setup some symlinks so the mdbx.dat was symlinked into a writable directory. upon opening the db as read only the directory had another file mdbx.lck

**Comment by gakonst** [comment]
What's the right fix here @argakiig? 

@shekhirin should we disable the creation of mdbx.lck on read? i think probably cannot?

**Comment by argakiig** [comment]
I may be reading the docs wrong? https://erthink.github.io/libmdbx/group__c__opening.html 
![image](https://github.com/paradigmxyz/reth/assets/6511720/8e5276ac-cd2f-46a7-bf86-1e22d59fba48)
specifically, it seems like it should be able to open without touching the lock file if readonly

**Comment by argakiig** [comment]
Bumping,  it seems to me from the documentation I linked it shouldn't matter if it can do anything with the lock file. If the filesystem is read only and you open it read only why does it touch the lck? Is this the intended mdbx behavior or is this a mdbx bug?
