### ISSUE TITLE
Archive node sync issue

### ISSUE THREAD

**Issue by mrabino1** [paradigmxyz/reth#6356]
### Describe the bug

[[](url)](https://www.dropbox.com/s/zbc0n4wk9d6xhhz/2024-02-01_17-27-34.png?dl=0)

this was seen during an initial archive node sync. 
running alpha.16 on ubuntu

### Steps to reproduce

ubuntu 
start reth initial sync for an archive node

### Node logs

```text
see picture
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

alpha.16

### What database version are you on?

alpha.16

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
@shekhirin 

![image](https://github.com/paradigmxyz/reth/assets/19890894/92796ee7-0315-4213-be51-88855410b097)

**Comment by shekhirin** [comment]
this looks either a bug with long-lived transaction detection, or a database query that took that long to execute

**Comment by shekhirin** [comment]
@mrabino1 could you please tell us what hardware you were using for syncing this node?

**Comment by mrabino1** [comment]
NUC 10.. with an i7 .. nvme 4tb.. and 32gb of ram..

**Comment by emhane** [comment]
maybe related @shekhirin ? https://github.com/paradigmxyz/reth/pull/6850

**Comment by shekhirin** [comment]
> maybe related @shekhirin ? #6850

likely not, because this warning isn't coming from the `TxnManager` and timeout-ing the transaction, it's just an informational message that we don't act upon

**Comment by emhane** [comment]
thinking if mdbx re-assigning a ptr could have lead to this... @shekhirin

**Comment by shekhirin** [comment]
> thinking if mdbx re-assigning a ptr could have lead to this... @shekhirin 

we issue these warning logs independently from the pointer tracking, and they're based purely on our Rust structs for transactions

**Comment by emhane** [comment]
yes but considering that the same txn id `41970` is shown for both crashes in the backtrace I think it's safe to say the same pointer is being used. the scenario I presented, which your pr addresses, has probably happened:
txn_1 has timed out and been aborted
pointer of txn_1 has been reassigned by mdbx to txn_2
user uses txn_1 again

so both txn_1 and txn_2 use same txn pointer.

furthermore I read the code for checking `open_duration`. on main, committing doesn't check if a transaction is timed out (indirectly that checks `open_duration`: if timed out `open_duration` has been exceeded). so the `open_duration` could be exceeded.

https://github.com/paradigmxyz/reth/blob/c5955f13059b2bb9e8f0c63b366ccd48a42387e2/crates/storage/db/src/implementation/mdbx/tx.rs#L290-L295

https://github.com/paradigmxyz/reth/blob/c5955f13059b2bb9e8f0c63b366ccd48a42387e2/crates/storage/libmdbx-rs/src/transaction.rs#L561-L570

however now this is done now in your pr

https://github.com/paradigmxyz/reth/blob/130f8b79f789383f884f25de8fdd14f0b73da67a/crates/storage/libmdbx-rs/src/transaction.rs#L542-L560

**Comment by shekhirin** [comment]
> yes but considering that the same txn id 41970 is shown for both crashes in the backtrace I think it's safe to say the same pointer is being used.

this is not true. `txn_id` in the screenshot is the ID of the transaction, and not the pointer. For read transactions, IDs are reused because they mean the snapshot ID of the database, and are **expected** to be non-unique: https://erthink.github.io/libmdbx/group__c__statinfo.html#gae13b7a7436c8073013bc5832194c6add

> txn_1 has timed out and been aborted

I don't think so:
1. We don't see a `WARN` log for transaction being timed out by the `TxnManager` https://github.com/paradigmxyz/reth/blob/d8a9b581da3bf82d03a9b7cb36f0d81765e08523/crates/storage/libmdbx-rs/src/txn_manager.rs#L276
2. Transactions on the screenshot are open for 108s and 78s, but our timeout is 5 minutes https://github.com/paradigmxyz/reth/blob/d8a9b581da3bf82d03a9b7cb36f0d81765e08523/crates/storage/libmdbx-rs/src/environment.rs#L26

---

I'm also re-opening this, because we see that these read-only transactions open for more than a minute are coming from the networking part, and the PR https://github.com/paradigmxyz/reth/pull/6850 most likely isn't going to change anything here.

**Comment by emhane** [comment]
> > yes but considering that the same txn id 41970 is shown for both crashes in the backtrace I think it's safe to say the same pointer is being used.
> 
> this is not true. `txn_id` in the screenshot is the ID of the transaction, and not the pointer. For read transactions, IDs are reused because they mean the snapshot ID of the database, and are **expected** to be non-unique: https://erthink.github.io/libmdbx/group__c__statinfo.html#gae13b7a7436c8073013bc5832194c6add
> 
alright, I followed the code down to here, looks like it's assigned by mdbx not by db

https://github.com/paradigmxyz/reth/blob/2df0d91f8d009885f4a067ca6c33bd5e2c6bfae5/crates/storage/libmdbx-rs/src/transaction.rs#L128-L131

> > txn_1 has timed out and been aborted
> 
> I don't think so:
> 
> 1. We don't see a `WARN` log for transaction being timed out by the `TxnManager` https://github.com/paradigmxyz/reth/blob/d8a9b581da3bf82d03a9b7cb36f0d81765e08523/crates/storage/libmdbx-rs/src/txn_manager.rs#L276

fair enough

> 2. Transactions on the screenshot are open for 108s and 78s, but our timeout is 5 minutes https://github.com/paradigmxyz/reth/blob/d8a9b581da3bf82d03a9b7cb36f0d81765e08523/crates/storage/libmdbx-rs/src/environment.rs#L26
> 
but this doesn't need to be a chain of just 2 transactions being reassigned the same pointer, this could be a much longer chain.

> I'm also re-opening this, because we see that these read-only transactions open for more than a minute are coming from the networking part, and the PR #6850 most likely isn't going to change anything there.
