### ISSUE TITLE
Make `to_transactions_manager` metrics more descriptive

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6363]
### Describe the feature

Currently the `to_transactions_manager` channel uses an `UnboundedMeteredSender` for its metrics. This works, but we have legends for metrics that are very generic: 
![Screenshot 2024-02-02 at 3 38 04 PM](https://github.com/paradigmxyz/reth/assets/6798349/c09de3f9-1ab1-4b37-ae63-17a39c8b11bf)

For example, it's very unclear what `c/s` means, and `messages sent` does not indicate anything about _what_ is in the channel.

The `to_transactions_manager` channel:
https://github.com/paradigmxyz/reth/blob/855d5b0a9539174a665690e46c68aff6827019bd/crates/net/network/src/manager.rs#L85-L87

The grafana should be changed to have more descriptive names:
https://github.com/paradigmxyz/reth/blob/855d5b0a9539174a665690e46c68aff6827019bd/etc/grafana/dashboards/overview.json#L4198-L4239

There are opportunities for followup PRs that do similar things with other metrics in our dashboard.

**Comment by emhane** [comment]
it would be very helpful if the actual variable name is the name of the metric. it makes it easier to find in the codebase.

**Comment by Rjected** [comment]
> @Rjected Regarding the description of this task, my understanding is to add more explanatory text in the grafana dashboard. May I confirm if my understanding is correct? If it is, please assign this task to me, and I can try it.

Yes, that's correct, feel free to submit a PR and I'll be happy to review!
