### ISSUE TITLE
Use plain code instead of a macro in the txpool `discard_worst` method

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6370]
> I think we can make the discard_worst loop nicer and get rid of the ugly macros if we basically do the same loop in the truncate functions anyway

yep definitely

_Originally posted by @Rjected in https://github.com/paradigmxyz/reth/issues/6368#issuecomment-1924919770_

**Comment by jsvisa** [comment]
I want to try this one, please assign it to me, thanks
