### ISSUE TITLE
Move node-api docs example to new example crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6372]
### Describe the feature

the node-api crate is intended for highlevel traits

currently the docs example require ethereum specific types which causes conflicts.

## TODO

* move https://github.com/paradigmxyz/reth/blob/72b7caa4c4847d63e25058794c32a587cd0d3ede/crates/node-api/src/engine/mod.rs#L17-L17 to a new example crate in the examples folder: `custom-node` or smth. we will expand this example once we have full node customization supported

**Comment by jsvisa** [comment]
@mattsse May I ask if I can pick this task?

**Comment by mattsse** [comment]
assigned 🙏
