### ISSUE TITLE
On disk Blob store metrics are not tracked accurately

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6379]
### Describe the feature

The `DiskFileBlobStore`'s size metrics only go up because removing a file skips reading the size  of the file.
The size metrics can also drift for other reasons, for example if files are deleted manually.

we want delete operations to be as fast as possible, we also don't have to delete as quickly as possible (sync) and it would actually be preferable if this is offloaded to somewhere else

https://github.com/paradigmxyz/reth/blob/57eef7ea03edf6eb00b72512ba99030528da1d3a/crates/transaction-pool/src/blobstore/disk.rs#L111-L111

This could be solved with a different delete approach for the DiskfileBlobstore:

delete operations in the `DiskFileBlobStore` only mark files for deletion, for example a simple Set
then we take care of pending blob file deletions in the maintain pool loop, either once per block or once per epoch

## TODO

Extend `BlobStore` trait with a function: `cleanup(&self)` 
The implementation for DiskfileBlobstore should then delete all previously marked files for deletion
so the current delete operations can be replaced with an insert into an `RwLock<HashSet>` instead.
cleanup is then called in maintain, but in a spawned task, because this might take a bit:
https://github.com/paradigmxyz/reth/blob/57eef7ea03edf6eb00b72512ba99030528da1d3a/crates/transaction-pool/src/maintain.rs#L193-L194

cleanup is then also responsible for updating metrics accordingly

**Comment by jsvisa** [comment]
@mattsse I want to pick up this issue, please assign it to me, thanks :)
