### ISSUE TITLE
Implement missing dynamic blob fee change check for `Transactionpool::best_transactions_with_attributes`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6383]
### Describe the feature

with EIP-4844 we now have two dynamic fees:

we're currently missing the blob fee directional fee change checks:

https://github.com/paradigmxyz/reth/blob/44a9975f76e22a26e876631aba4dcdb451302cf3/crates/transaction-pool/src/pool/txpool.rs#L330-L340

## TODO
if the provided argument includes a pending blob fee we need to handle this appropriately

there are more cases to check, the driving one is still the base fee but then we also need to check the directional move of the pending blob fee

lower blob fee: more eip4844 could be pending now
higher blob fee: pending eip4844 could no longer be pending

**Comment by allnil** [comment]
Take it
