### ISSUE TITLE
Blob tx batches bigger than 1 blob

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6411]
### Describe the feature

Recent improvements to `TransactionManager` included batching tx imports to commit to the pool. For blob txns requested over an eth68 connection, this will be trivial. This is due to the fact that the soft limit for the expected response size, with respect to which `GetPooledTransaction` are filled with hashes, is 128 KB. That means each request will only request one blob tx. Either the expected response size soft limit is increased, devp2p spec's standard size limit for responses 2 MiB would be great, or batches need to persist the scope of `import_transactions`, in order to allow filling the batch up with a non-trivial  number of elements before committing to the pool, when the limit of 128 KB is kept.

**Comment by justcode740** [comment]
will take a look tmr on this

**Comment by emhane** [comment]
nice @justcode740, please base your pr on this branch https://github.com/paradigmxyz/reth/tree/emhane/speed-up-request-buffered-hashes since it introduces some structural changes that make fixing merge conflicts nasty.
