### ISSUE TITLE
Make the PayloadBuilder configurable over the PayloadBuilder stack

### ISSUE THREAD

**Issue by loocapro** [paradigmxyz/reth#6418]
### Describe the feature

I'd like the possibility to inject some custom logic into the process of building a payload (I.E: adding a static transaction to the payload body).

Currently it seems like we pass EthPayloadBuilder or OptimismPayloadBuilder to the spawn_payload_builder_service function from outside making it impossible to overwrite its behaviour.l

For reference the custom payload builder example: https://github.com/paradigmxyz/reth/pull/6269

CC: @mattsse @rkrasiuk @Rjected

**Comment by mattsse** [comment]
this should no longer be an issue with new node builder
