### ISSUE TITLE
feature request: rpc method for per opcode gas tracing

### ISSUE THREAD

**Issue by sslivkoff** [paradigmxyz/reth#6421]
### Describe the feature

It would be very nice to have an rpc method ("`opcode_trace`") that gives a per-transaction accounting of:

- how many times each opcode was called
- how much total gas was used per opcode

This would be the final missing piece for full resolution gas analysis.

Data could have a similar schema to state_diffs tracing:
```python
data = {
    "opcode": [
        {
            "transaction_hash": "0x1234...",
            "opcode_counts": {
                "SSTORE": 17,
                ...
            },
            "opcode_gas": {
                "SSTORE": 153000,
                ...
            },
            ...
        }
        {
            "transaction_hash": "0x8764...",
            ...
        }
    ]
}
```

**Comment by gakonst** [comment]
I _think_ this should be possible via a custom tracer similar to Geth's tracers, or should this be in a separate trace method @matthuang ?

**Comment by mattsse** [comment]
I believe the only way to do this rn is via JS

but it's possible to add this

**Comment by mattsse** [comment]
cc @DoTheBestToGetTheBest 

we can add this as `trace_blockOpcodeGas` and `trace_transactionOpcodeGas`

**Comment by sslivkoff** [comment]
possible schema for output

1. trace_transactionOpcodeGas

request:
`[txHash]`

response:
```json
{
    "transactionHash": "0xb5be..."
    "opcode_counts": {
        "SSTORE": 4,
        "CREATE": 1,
        ...
    },
    "opcode_gas": {
        "SSTORE": 38000,
        "CREATE": 32000,
        ...
    },
}
```


2. trace_blockOpcodeGas

request:
`[blockNumber | blockHash]`

response:
```json
{
    "blockHash": "0x9eaf...",
    "transactions": [trace_transactionOpcodeGasResponse],
}
```
