### ISSUE TITLE
Modify `BlobTransactionSidecar` definition

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#6432]
### Describe the feature

Currently, the `BlobTransactionSidecar` struct is composed of three separate vectors:

https://github.com/paradigmxyz/reth/blob/5c69eecba758b615769fcdfc9fcd15e96f132348/crates/primitives/src/transaction/sidecar.rs#L305-L312

- A vector of blobs
- A vector of commitments
- A vector of proofs

As per the [EIP-4844 specification](https://eips.ethereum.org/EIPS/eip-4844), it is mandated that:

> There are an equal number of tx_payload_body.blob_versioned_hashes, blobs, commitments, and proofs.

While this equality must be guaranteed by the node, the approach of maintaining three separate vectors with synchronized sizes seems counterintuitive. A more streamlined solution could involve introducing a structured entity, perhaps named `BlobTransactionSidecarInner`, which encapsulates a `blob` field, a `commitment` field, and a `proof` field. By adopting this structure, the creation of a `BlobTransactionSidecar` instance would involve a single vector of `BlobTransactionSidecarInner` instances, simplifying the maintenance and ensuring the synchronization of related data.

## Proposal

- Introduce a `BlobTransactionSidecarInner` structure containing `blob`, `commitment`, and `proof` fields.
- Modify `BlobTransactionSidecar` to utilize a single vector of `BlobTransactionSidecarInner` instances instead of three separate vectors.

This approach enhances code clarity, reduces redundancy, and aligns with the specifications outlined in EIP-4844.

**Comment by Rjected** [comment]
Here's an overview of our blob types:
* `BlobTransactionSidecarRlp`, used for rlp encoding and decoding. Converts into `BlobTransactionSidecar`.
* `BlobTransactionSidecar`, used as input to validation methods, included in transaction types, and for engine API serialization / deserialization.

I'm not sure that we need a third sidecar type, what's the motivation behind this?

**Comment by tcoratger** [comment]
> Here's an overview of our blob types:
> 
> * `BlobTransactionSidecarRlp`, used for rlp encoding and decoding. Converts into `BlobTransactionSidecar`.
> * `BlobTransactionSidecar`, used as input to validation methods, included in transaction types, and for engine API serialization / deserialization.
> 
> I'm not sure that we need a third sidecar type, what's the motivation behind this?

@Rjected Maybe I wasn't clear or I'm wrong but here's what I noticed, tell me what you think. Currently there is indeed a `BlobTransactionSidecar` structure with three vectors in it (blobs, commitment and proofs). But these three vectors must of course have the same length because the commitments are associated with blobs: for example we cannot have a vector with 5 blobs and next to it a vector with 4 commitments. This must be verified by consensus according to the EIP-4844 specification.
- However, on the one hand in the current construction of the structure it is possible. I can create an instance of `BlobTransactionSidecar` with 3 vectors of different sizes, which is not very logical I would say.
- On the other hand it forces us to create three vectors each time.

What I proposed here is to create a struct of type:

```rust
pub struct BlobTransactionSidecarInner {
     /// The blob data.
     pub blob:Blob,
     /// The blob commitment.
     pub commitment:Bytes48,
     /// The blob proof.
     pub proof: Bytes48,
}
```

and create another structure next to it which is a vector of `BlobTransactionSidecarInner`:
```rust
pub struct BlobTransactionSidecar {Vec<BlobTransactionSidecarInner>}
```

In this way:
- We are obliged to have as many blobs as commitments as proofs: we enforce equality through construction.
- We only create one vector rather than three separate ones.

Does it make sense or not at all?

**Comment by Rjected** [comment]
> We only create one vector rather than three separate ones.

One versus three vectors is not an optimization.

> However, on the one hand in the current construction of the structure it is possible. I can create an instance of `BlobTransactionSidecar` with 3 vectors of different sizes, which is not very logical I would say.

We need to create a type like this when we receive a transaction from the network, which may include invalid sidecars. We also have accompanying validation methods, which are run before we use the sidecar for anything. These are accompanied by the _other_ validation tasks we need to do, for example signature verification. Is it logical that you can construct an invalid signature using the `Signature` struct? Yes. Because the data structure still needs to be validated according to the spec. Same with the sidecar.

> We are obliged to have as many blobs as commitments as proofs: we enforce equality through construction.

We already have checks for this. Ultimately the proposal is a trivial wrapper, and not worth spending time on, so I'm closing this issue. If the fact that the blob sidecar must be validated is not clear, we could add some documentation.
