### ISSUE TITLE
Support transaction filtering

### ISSUE THREAD

**Issue by tthebst** [paradigmxyz/reth#6440]
### Describe the feature

What:
Add cli flag to reth that allows for filtering transactions that are included in a block. For my usecase it would already be sufficient if there is a flag to provide a list of prohibited source and destination addresses.

Why:
no 🥪 

How:
(not familiar with reth) Either filter when building the block or don't even store transactions that match the provided list.

I would be willing to implement this.

**Comment by mattsse** [comment]
closing this because this is not a feature we want natively supported as setting, but can easily be done with a few modest modifications using an extension
