### ISSUE TITLE
Use `terminalTotalDifficultyPassed` to determine "network is known to be merged"

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6453]
### Describe the feature

Right now we determine the "network is not known to be merged" based on the `TTD { fork_block, .. }` field:
https://github.com/paradigmxyz/reth/blob/37a8780a4d71856fddc09a9146823d00a2ed0201/crates/primitives/src/chain/spec.rs#L1478-L1482

This is incorrect because this is not enabled for mainnet:
https://github.com/paradigmxyz/reth/blob/37a8780a4d71856fddc09a9146823d00a2ed0201/crates/primitives/src/chain/spec.rs#L1346-L1351

This causes reth to incorrectly show "network is not known to be merged".

Instead we should use the `terminal_total_difficulty_passed` parameter if parsing from `genesis.json`, and introduce a parameter in `ChainSpec` for this. Then we can use that field to determine this messsage.

**Comment by jsvisa** [comment]
could you please assign this issue to me, I want to have a try

**Comment by Rjected** [comment]
> could you please assign this issue to me, I want to have a try 

Just assigned!

**Comment by Rjected** [comment]
I just realized we have `paris_block_and_total_difficulty` in `ChainSpec` so that could even be re-used for this
