### ISSUE TITLE
Database operation metrics should be cached

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#6457]
### Describe the feature

Every time we record a new database operation metric, we create an instance of metrics with `new_with_labels` https://github.com/paradigmxyz/reth/blob/93e213c21fd40a43bdf71e9365228f2a4bcaf24e/crates/storage/db/src/metrics.rs#L208-L211

It has a significant perf penalty (thanks @joshieDo for the flamegraph)

![image](https://github.com/paradigmxyz/reth/assets/5773434/93910c47-70ee-415c-896a-1a87386e4304)

so we need to cache the created metrics as we usually do https://github.com/paradigmxyz/reth/blob/93e213c21fd40a43bdf71e9365228f2a4bcaf24e/crates/prune/src/metrics.rs#L21-L23

**Comment by sevazhidkov** [comment]
Can take this on.
