### ISSUE TITLE
Track latest nightly regression async_trait

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#646]
### Describe the bug

fixed by patching nightly version in CI #642

* investigate switch to stable, likely blocked by GATs?
* switch to nightly channel once resolved

### Steps to reproduce

-

### Node logs

```text
-
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by gakonst** [comment]
I think we actually don't need nightly at all? The GATs we use are the stabilized one, and I've been building reth locally on stable.

**Comment by rkrasiuk** [comment]
ref #640

**Comment by rkrasiuk** [comment]
@gakonst we need nightly for fmt & **maybe** clippy

**Comment by gakonst** [comment]
Yep but that's fine - my point being is we're not blocked on GATs or any nightly feature to build.
