### ISSUE TITLE
devp2p hive failure: TestSimultaneousRequests

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6475]
The `devp2p/eth` test `TestSimultaneousRequests` fails with the following logs:
```
not ok 3 TestSimultaneousRequests
# unexpected request id in response: got 222, want 111
```

## How to reproduce
Run hive:
```
./hive --client reth --sim devp2p --sim.limit "eth/TestSimultaneousRequests" --sim.loglevel 5
```

It would be great to write a rust test that's analogous to the hive test along with the fix! It would also help to speed up the feedback loop when fixing, or in case we have regressions

**Comment by mattsse** [comment]
I think the issue with this test is that the test expects the responses in the same order as the outgoing requests

https://github.com/ethereum/go-ethereum/blob/fc380f52ef9778e988266f776b9593ce719cf79d/cmd/devp2p/internal/ethtest/suite.go#L202-L216

but we can easily replicate this Test 

ref: crates/net/network/tests/it

**Comment by emhane** [comment]
seems to be passing since https://github.com/paradigmxyz/reth/actions/runs/7923893449
