### ISSUE TITLE
reuse alloy-eips constants

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6489]
### Describe the feature

alloy's eips crate has a bunch of duplicated constants that we can re-export 

in

https://github.com/paradigmxyz/reth/blob/672246d40062d29985b0dabc21ba523e4971ccfd/crates/primitives/src/constants/eip4844.rs

from

https://github.com/alloy-rs/alloy/blob/1737429f1f50fe7cb8aacc070831088bf3290320/crates/eips/src/eip4844.rs

**Comment by ThreeHrSleep** [comment]
Can I take this on?

**Comment by mattsse** [comment]
assigned!
