### ISSUE TITLE
raise fd limit for binaries

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#649]
### Describe the feature

the fdlimit crate https://crates.io/crates/fdlimit supports raising the open file descriptors limit on UNIX so reth can handle

* p2p 
* db
* rpc

**Comment by gakonst** [comment]
Did we encounter this as a problem anywhere?

**Comment by mattsse** [comment]
not but we'll most likely will once rpc is enabled, same as with anvil
