### ISSUE TITLE
Add retry to git clone during ethereum tests

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#651]
### Describe the feature

run https://github.com/paradigmxyz/reth/actions/runs/3800815905/jobs/6464644125 failed due to 429 (too many requests)

I suspect multiple concurrent builds triggered some github rate limit

unfortunately there's no retry integrated in https://github.com/actions/checkout

there's however https://github.com/nick-fields/retry which would require to clone via command

**Comment by onbjerg** [comment]
We have not seen this since, so I assume this was just a fluke. Going to close this w/o adding the retry for now
