### ISSUE TITLE
eth_sendRawTransaction is taking over 20 secs

### ISSUE THREAD

**Issue by roy-looter** [paradigmxyz/reth#6516]
### Describe the bug

eth_sendRawTransaction is taking very long when it should give feedback instantly whether its error or tx hash.

After some time it came back to normal.

@mattsse said it could be due to clogged import queue (on tg) - wasn't able to verify though.

### Steps to reproduce

Sometimes send transaction by eth_sendRawTransaction through reth node takes very long time to resolve.
couldn't reproduce constantly.

### Platform(s)

Linux (ARM)

### What version/commit are you on?

0.1.0-alpha.16

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
we had some perf issues on alpha 16 with too aggressive tx fetching resulting in clogged pool import queue which can cause this.

this should mostly be fixed with 17, though I think we want a tier system so that local txs are prioritized

**Comment by mattsse** [comment]
this should be resolved now
