### ISSUE TITLE
maybe dev flag inconsistency when depending on reth

### ISSUE THREAD

**Issue by 0xSha5** [paradigmxyz/reth#6518]
### Describe the bug

I have a crate depending on reth.

The Cargo.toml is as follow: 
```
[package]
name = "bot"
version = "0.0.0"
edition = "2021"

[dependencies]
reth = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
clap = "4"
```
The crate lib.rs is as follow:
```
use reth::cli::Cli;
use clap::Parser;

pub fn run() {
    if let Err(err) = Cli::<()>::parse().run() {
        eprintln!("fatal error: {err:#?}");
        std::process::exit(1);
    }
}
```
And the main simply calls crate::run().

If I launch this crate using the dev flag:
> cargo run -- node --dev

I can deploy contracts on the network, however i cannot call view functions for the contracts, it returns empty bytes.
Additionally gas estimations return 21001 whatever the call you are trying to do.

If I use the reth github repo and launch it using the exact same command, it works and the view call returns the expected value.

Also I'm running this on ubuntu 20.04 in a vm.

### Steps to reproduce

Refer to description

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.1.0-alpha.17

### What database version are you on?

Current database version: 1
Local database is uninitialized

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

default

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
hey @0xSha5, do you have a `cast` command or steps for deploying / calling a view function on a simple contract that triggers the bug?

**Comment by 0xSha5** [comment]
Yes, the contract is deployed using hardhat:

The contract is:
```
// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract Token is ERC20("Token", "TKN") {
    constructor() {
        _mint(msg.sender, 10000 ether);
    }
}
```

It's deployed  with the script:
```
const { ethers } = require("hardhat");

async function main() {
    // test..test mnemonic wallet[0]
    const owner = new ethers.Wallet("0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80", ethers.provider)

	const factory = await ethers.getContractFactory("Token");
        // gasLimit as gasEstimation returns 21001
	const token = await factory.connect(owner).deploy({gasLimit: 7000000});
	await token.deployed();
	console.log(token.address)
       // call exception
       console.log(await token.connect(ethers.provider).decimals())
}

if (require.main === module)
	main()
		.then(_ => process.exit())
		.catch(e => {
			console.error(e);
			process.exit(1);
		})
```

If I use the command cast codesize, I get 2327:
> cast codesize <TOKEN_ADDRESS>

The hardhat.config.js is as follow:
```
require("dotenv").config();
require("@nomicfoundation/hardhat-toolbox");
require("hardhat-abi-exporter");
require("hardhat-gas-reporter");
require("hardhat-contract-sizer");
const { ethers } = require("ethers");

const dev = {
    url: "http://localhost:8545/",
	chainId: 1337,
}

module.exports = {
    networks: {
        dev: dev
    },
	abiExporter: {
		path: "./abis",
		runOnCompile: true,
		clear: true,
		flat: false,
		pretty: false,
	},
	solidity: {
		compilers: [
			{
				version: "0.8.0",
				settings: {
					optimizer: {
						enabled: true,
						runs: 200,
					}
				}
			},
			{
				version: "0.6.6",
				settings: {
					optimizer: {
						enabled: true,
						runs: 200,
					}
				}
			},
			{
				version: "0.5.16",
				settings: {
					optimizer: {
						enabled: true,
						runs: 200,
					}
				}
			},
		]
	}
};
```

The package.json is as follow:
```
{
  "name": "hardhat-project",
  "dependencies": {
    "@flashbots/ethers-provider-bundle": "^0.6.1",
    "@nomicfoundation/hardhat-toolbox": "^2.0.2",
    "@nomicfoundation/hardhat-verify": "^1.1.1",
    "@openzeppelin/contracts": "^4.9.2",
    "@uniswap/v2-core": "^1.0.1",
    "@uniswap/v2-periphery": "^1.1.0-beta.0",
    "canonical-weth": "^1.4.0",
    "dotenv": "^16.3.1",
    "hardhat": "^2.17.2",
    "hardhat-abi-exporter": "^2.10.1",
    "hardhat-contract-sizer": "^2.10.0",
    "hardhat-gas-reporter": "^1.0.9",
    "keccak256": "^1.0.6",
    "merkletreejs": "^0.3.10"
  }
}
```

Deploying command is:
> npx hardhat run --network dev deploy.js

The cast command using the crate depending on reth:
> cast call <TOKEN_ADDRESS> "decimals()(uint256)"
Error: 
could not decode output; did you specify the wrong function return data type?
Context:
Error #0: buffer overrun while deserializing
Error #1: buffer overrun while deserializing

If i start reth from the reth repo and cast the exact same command:
I get 18 which is the expected amount

other calls such as totalSupply etc behaves the same way

**Comment by Rjected** [comment]
tysm for the detailed report, going to try this today!
