### ISSUE TITLE
Eth68 announcement metrics, track entries by `TxType`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6524]
### Describe the feature

Make use of eth68 announcement metadata, to aggregate transaction hashes by `TxType`. At least number of transaction hashes per type, possibly also size range per type.

```rust
struct AnnouncedTxSizeMetrics {
    legacy: Histogram,
    eip2930: Histogram,
    eip1559: Histogram,
    eip4844: Histogram,
}
```

These metrics should be updated in announcement validation, which is examining each announcement entry based on `TxType` anyway.

**Comment by Richa-iitr** [comment]
Can i take this up?
