### ISSUE TITLE
Store fallback peers in `TransactionFetcher` as a `(PeerId, usize)` tuple

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6528]
### Describe the feature

Rn, size metadata from an eth68 announcement for a tx hash, is overwritten on the insertion of each new fallback peer for that hash. We should keep doing this, since it's then easily accessible in estimating `PooledTransactions` response size in assembling a `GetPooledTransactions` request, even when assembling a request for a fallback peer on an eth66 connection.

Additionally for peers on an eth68 connection, if they get inserted as fallback peer for a hash then the size they announced for the tx should get stored along with them. This way peers can be caught that announce wrong sizes. At this level in announcement processing, hashes with an announced size equal to zero, have already been filtered out. Hence, zero can be used as `None` value. The [`PackedOption` type from `cranelift`](https://github.com/bytecodealliance/wasmtime/blob/2c6f38622d3b009293437839e5d75b4df64fa774/cranelift/entity/src/packed_option.rs#L24-L27) can also be used for this.

**Comment by AbhinavMir** [comment]
Looking into this! Have a few questions I'll post here tomorrow!

**Comment by emhane** [comment]
nice @AbhinavMir ! suggest you use https://github.com/paradigmxyz/reth/tree/emhane/speed-up-request-buffered-hashes as base branch since that branch introduces some structural changes that may otherwise make merge conflicts with main tedious later cc @mattsse

**Comment by justcode740** [comment]
> ranch intro

hey it seems u r simultaneously take multiple issues, i wonder would it be better if u could claim one by one for maximum efficiency, also to give other people who have the bandwidth a chance.

**Comment by AbhinavMir** [comment]
Hey, you're right! I didn't mean to, but I'm closing in on solving the other issue and thus moved to also pick this up since I have some context on what this issue is about. I won't be taking up new "good first issues" post these two to allow newer contributors to contribute. Cheers!

**Comment by AbhinavMir** [comment]
You're right! I was investigating the other one and came pretty close to figuring things out, but also had some context as to how to fix this issue. I won't be taking up any new issues before I complete these two, since I feel I am close to a fix in both.

**Comment by justcode740** [comment]
> You're right! I was investigating the other one and came pretty close to figuring things out, but also had some context as to how to fix this issue. I won't be taking up any new issues before I complete these two, since I feel I am close to a fix in both.

gotcha, but remember seeing u on >=3 diff issue somehow lol but yeah nvm, just my two cents.

**Comment by AbhinavMir** [comment]
>=3? I think I'm on 2, could you link me to the others?

**Comment by AbhinavMir** [comment]
No you're right, more than 3 would be a problem but I think I'm on 2, could you link me to the others? https://github.com/paradigmxyz/reth/pull/6399 has a fix candidate and seems like my fix is approved thus far. Is there some other one I've missed? Github's search/notifs has been not great because I can't find any. I definitely wouldn't want to block!
