### ISSUE TITLE
Track unique tx hashes in valid announcement data

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6530]
### Describe the feature

This is interesting to observe on a protocol level as it tells us something about the redundancy level in the mempool. ~~For each new tx hash that gets inserted into the `TransactionFetcher`, a counter can be updated.~~ The total number of announced hashes in the valid announcement data should be counted. The tx pool imports reflects unique tx hashes that are successfully fetched, that's good enough.

https://github.com/paradigmxyz/reth/blob/3c3c7b36adeb0a0491518854a2b13f9f85fc0aff/crates/net/network/src/transactions/fetcher.rs#L345

In the description for this metric, should be included that this metric is not absolute in the sense that statefulness of `TransactionFetcher` is limited. If a tx hash is evicted, because max retires for it is reached or because it's the _least_ recently used entry, and **then** appears in an announcement, it is inserted as a new tx hash.

**Comment by AbhinavMir** [comment]
Would love to take this up!

**Comment by AbhinavMir** [comment]
Just checking if this is the right direction:

  - Detect new transaction hashes announced by peers that the `TransactionFetcher` is not already tracking.
  - Consider a hash new if it is not present in the `unknown_hashes` map, indicating the `TransactionFetcher` has neither seen nor is currently fetching it.
  - For each newly detected transaction hash, increment a counter to keep track of the total number of unique hashes announced.
  - The logic for identifying new hashes and incrementing the counter is to be placed within the `filter_unseen_and_pending_hashes` method of the `TransactionFetcher`.

**Comment by AbhinavMir** [comment]
Just checking if this is the right direction:

  - Detect new transaction hashes announced by peers that the `TransactionFetcher` is not already tracking.
  - Consider a hash new if it is not present in the `unknown_hashes` map, indicating the `TransactionFetcher` has neither seen nor is currently fetching it.
  - For each newly detected transaction hash, increment a counter to keep track of the total number of unique hashes announced.
  - Modify `filter_unseen_and_pending_hashes`  to handle this

**Comment by emhane** [comment]
Closed as side effect of https://github.com/paradigmxyz/reth/pull/6681, which clarifies existing metric that was found to exactly describe this and adding a metric for observing intersection between hashes in pool and hashes in announcements.
