### ISSUE TITLE
debug_traceTransaction custom EVM tracer not compatible with geth

### ISSUE THREAD

**Issue by naddison36** [paradigmxyz/reth#6533]
### Describe the bug

Geth's custom EVM tracer for the `debug_traceTransaction` API is documented in https://geth.ethereum.org/docs/developers/evm-tracing/custom-tracer

rETH's `getPc()` method on the `log` argument of the `step` function does not match geth's `getPC()` function
https://geth.ethereum.org/docs/developers/evm-tracing/custom-tracer#step

rETH is using a lower case `c`, while geth is using an uppercase `C`.

### Steps to reproduce

The following request returns a list of program counters using `log.getPc()`
```json
{
    "jsonrpc": "2.0",
    "method": "debug_traceTransaction",
    "params": [
        "0x6892b5c44e0ec2382f0e30d86dfaba11847f2ddc038a2cce30b5c3be4d08108b",
        {
            "tracer": "{data: [], fault: function(log) {}, step: function(log) { this.data.push(log.getPc()) }, result: function() { return this.data; }}"
        }
    ],
    "id": 1
}
```

The following using geth style `log.getPC()` does not return any results
```json
{
    "jsonrpc": "2.0",
    "method": "debug_traceTransaction",
    "params": [
        "0x6892b5c44e0ec2382f0e30d86dfaba11847f2ddc038a2cce30b5c3be4d08108b",
        {
            "tracer": "{data: [], fault: function(log) {}, step: function(log) { this.data.push(log.getPC()) }, result: function() { return this.data; }}"
        }
    ],
    "id": 1
}
```

### Platform(s)

Windows (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.17 Commit SHA: aac72f4 Build Timestamp: 2024-02-06T12:40:32.633974683Z Build Features: jemalloc Build Profile: maxperf

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks!

fixed in the referenced PR
