### ISSUE TITLE
Update `current_stage` tracker for Status message when unwinding

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#6543]
### Describe the feature

Currently, we update it only on `PipelineEvent::Run` https://github.com/paradigmxyz/reth/blob/8cfa5efe62e79923b317d9685fc9f8205d5a92b5/bin/reth/src/commands/node/events.rs#L112 and `PipelineEvent::Ran` https://github.com/paradigmxyz/reth/blob/8cfa5efe62e79923b317d9685fc9f8205d5a92b5/bin/reth/src/commands/node/events.rs#L158 events. We need to do the same on unwind to keep the `Status` message up-to-date.

**Comment by loocapro** [comment]
I can take this!

**Comment by shekhirin** [comment]
@loocapro assigned!
