### ISSUE TITLE
Set excess_blob_gas  for local pending block

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6562]
### Describe the feature

when building the pending block locally we update the header's base fee:

https://github.com/paradigmxyz/reth/blob/17eca361e8951362f5c544a2dfe20c9b046bef5f/crates/rpc/rpc/src/eth/api/mod.rs#L292-L293

we need to do the same for `excess_blob_gas` via:

https://github.com/paradigmxyz/reth/blob/17eca361e8951362f5c544a2dfe20c9b046bef5f/crates/primitives/src/header.rs#L258-L258

**Comment by justcode740** [comment]
can give it a quick look

**Comment by justcode740** [comment]
unsure i get it but the change seems less than the issue descript here. https://github.com/paradigmxyz/reth/pull/6603
