### ISSUE TITLE
Database transaction metrics should be cached

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#6564]
### Describe the feature

Similar to https://github.com/paradigmxyz/reth/issues/6457, but for transaction-level metrics: https://github.com/paradigmxyz/reth/blob/2a5efb2a99ca50a45e41c50b5ef0e6d838d46b28/crates/storage/db/src/metrics.rs#L195-L196 https://github.com/paradigmxyz/reth/blob/2a5efb2a99ca50a45e41c50b5ef0e6d838d46b28/crates/storage/db/src/metrics.rs#L208-L215

**Comment by sevazhidkov** [comment]
Will do
