### ISSUE TITLE
debug_traceCallMany should increment block/timestamp on next bundle

### ISSUE THREAD

**Issue by geomad** [paradigmxyz/reth#6566]
### Describe the bug

Currently, in `debug_traceCallMany` reth does not automatically increment `blockNumber` and `timestamp` in each consecutive bundle, if those values are not overridden.

In erigons implementation they are incremented ie if tracing `'latest'` block:
```
[
            {
                "transactions": [ tx1, tx2 ], //block and timestamp in this bundle are correctly set to match 'latest' block
            },
            {
                "transactions": [ tx3 ], //block and timestamp in this bundle match 'latest' block , but should be block+1 and timestamp+12
            },
            {
                "transactions": [ tx4, tx5, tx6 ], //block and timestamp in this bundle match 'latest' block , but should be block+2 and timestamp+24
            },
]
```
Note: In erigon `timestamp` is incremented by `1` for each consecutive block, but this was from PoW times. I think in PoS it makes more sense to increment by `12`

### Steps to reproduce

debug_traceCallMany

### Platform(s)

Linux (x86)

### What version/commit are you on?

aac72f4

### What database version are you on?

1

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> but should be block+1 and timestamp+12

is this specified anywhere?

**Comment by geomad** [comment]
> > but should be block+1 and timestamp+12
> 
> is this specified anywhere?

I'm not sure if its specified (is there even a spec for this?) but that's how erigon does it, and it makes sense, since the usefulness of bundles is to trace txs in different contexts, otherwise all the txs could be traced in the same bundle

**Comment by mattsse** [comment]
hmm, I guess it makes sense to mirror this behaviour, and it's still possible to set custom parameters for this via the block overrides.

**Comment by loocapro** [comment]
May I take this?
