### ISSUE TITLE
Implement eth_getHeaderByNumber and eth_getHeaderByHash

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6571]
### Describe the feature

Basically the same as:

https://github.com/paradigmxyz/reth/blob/17eca361e8951362f5c544a2dfe20c9b046bef5f/crates/rpc/rpc-api/src/eth.rs#L41-L51

https://github.com/paradigmxyz/reth/blob/17eca361e8951362f5c544a2dfe20c9b046bef5f/crates/rpc/rpc/src/eth/api/server.rs#L87-L101

but only the header

see also:

https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-eth#ethgetheaderbynumber

**Comment by rodrigoherrerai** [comment]
Can I take it ?

**Comment by mattsse** [comment]
assigned, ty

**Comment by mattsse** [comment]
@rodrigoherrerai 

the new functions can make use of the existing block functions, and then simply return the inner header field of `RichBlock` type

**Comment by rodrigoherrerai** [comment]
Hi @mattsse finishing this pr, just one thing, geth's header has an extra value "total difficulty". Reth doesn't have it. Wouldn't this create an incompatibility ?

**Comment by mattsse** [comment]
I see,
in that case we need to move the ttd field into the header type here first

https://github.com/alloy-rs/alloy/blob/e127fed9118b53c9f6776ce7aed412788827e9a5/crates/rpc-types/src/eth/block.rs#L19-L25

mind opening a pr for this?

**Comment by rodrigoherrerai** [comment]
Sure !
