### ISSUE TITLE
Don't enforce nonce in eth_call and adjacent endpoints

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6574]
### Describe the feature

even though if the nonce is provided in the request args, it's ignored by other clients:

ref:

https://github.com/ethereum/go-ethereum/blob/fc380f52ef9778e988266f776b9593ce719cf79d/internal/ethapi/api.go#L1079-L1096

https://github.com/ethereum/go-ethereum/blob/fc380f52ef9778e988266f776b9593ce719cf79d/internal/ethapi/transaction_args.go#L256-L256

https://github.com/ethereum/go-ethereum/blob/fc380f52ef9778e988266f776b9593ce719cf79d/core/state_transition.go#L144-L147

## TODO

ignore nonce for call env by taking the optional nonce from the `tx`:

https://github.com/paradigmxyz/reth/blob/d4cf706ed29b70eb3bd76847c12c9607b9570a74/crates/rpc/rpc/src/eth/revm_utils.rs#L308-L308

Update docs accordingly:

https://github.com/paradigmxyz/reth/blob/d4cf706ed29b70eb3bd76847c12c9607b9570a74/crates/rpc/rpc/src/eth/revm_utils.rs#L231-L235

**Comment by abhijeetbhagat** [comment]
@mattsse i can take a crack at this.
