### ISSUE TITLE
Add Eth66 as supported version by default

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#658]
### Describe the feature

Currently, we only include eth77

https://github.com/paradigmxyz/reth/blob/c6d38f0f6a652c227df861a2735364b945270433/crates/net/eth-wire/src/builder.rs#L101

eth66 is a superset of eth77: https://github.com/ethereum/devp2p/blob/master/caps/eth.md#eth66-eip-2481-april-2021

> Version 67 removed the GetNodeData and NodeData messages.

which should still be fine, even though we don't have handlers implemented yet.

**Comment by rakita** [comment]
eth/66 will work if we return an empty responses for those messages.
