### ISSUE TITLE
Remove default cfg_and_block_env impl from PayloadBuilderAttributes trait

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6599]
### Describe the feature

ref https://github.com/paradigmxyz/reth/pull/6598#pullrequestreview-1879211813

Currently there's a default implementation for `PayloadBuilderAttributes::cfg_and_block_env`

https://github.com/paradigmxyz/reth/blob/b1d6790332d3acc137b67e5ebb2be7d74b2f8da4/crates/node-api/src/engine/traits.rs#L86

Because this now depends on whether or not the optimism feature is enabled, this default implementation should be removed, and the op-specific logic should be added to the `OptimismPayloadBuilderAttributes` struct.

The `optimism` feature can then be removed from `node-api`

**Comment by i-m-aditya** [comment]
I will pick this.

**Comment by Rjected** [comment]
> I will pick this.

Sounds good, just assigned!
