### ISSUE TITLE
"baseFeePerGas" missing after DEV node restart

### ISSUE THREAD

**Issue by mm-zk** [paradigmxyz/reth#6605]
### Describe the bug

When running in dev mode (localnetwork), after restarting the node, the eth_getBlockByNumber no longer returns baseFeePerGas - which results in lots of tooling seeing it like EIP-1559 was not active

### Steps to reproduce

**Start the node**
```
./reth  node --http  -vvvvv --dev --instance 1 --dev.block-time 1s --datadir /tmp/data
```
**Kill the node**
CTRL-C
**Restart the node again**
```
./reth  node --http  -vvvvv --dev --instance 1 --dev.block-time 1s --datadir /tmp/data
```
**Now a simple transfer no longer works**
```
cast send -r http://localhost:8545 0x8a91dc2d28b689474298d91899f0c1baf62cb85b --value 1ether  --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
> Error: 
> custom error: EIP-1559 not activated
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.18

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
oh, huh, this is weird, I just reproduced.

**Comment by mm-zk** [comment]
I've checked the fix and it works. Thanks so much for quick response @Rjected @mattsse !
