### ISSUE TITLE
Database Corruption

### ISSUE THREAD

**Issue by cheddiefender** [paradigmxyz/reth#6613]
### Describe the bug

I keep getting database write errors (-30796) when syncing. 

I have been using checkpoint sync and i tried checking the db i got from merkle but it was not corrupted before i tried to sync. Then when i run reth i eventually get the db write error after some hours. 

I checked my ram with memtest86+ and that doesn't seem to be the issue. All I can think of is my nvme? not sure. I have been running raid0 on dual samsung 990 pros (which i updated the firmware on before setting up the raid array) and i set up the raid array using the drivers that came with my motherboard for windows 10. I am using docker-compose to run reth. 

### Steps to reproduce

1. Checkpoint sync
2. Run Reth
3. After a few hrs, database write error

### Platform(s)

Windows (x86)

### What version/commit are you on?

0.1.0-alpha.17

### What database version are you on?

not sure how to check in my scenario. The db is not inside docker

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by cheddiefender** [comment]
Ended up migrating to ubuntu and using software raid instead of firmware raid (in the bios). No more issues. Not sure if it's an OS thing or the different RAID approach

**Comment by emhane** [comment]
> Ended up migrating to ubuntu and using software raid instead of firmware raid (in the bios). No more issues. Not sure if it's an OS thing or the different RAID approach

so this issue can be closed @cheddiefender ?
