### ISSUE TITLE
Listen to incoming rpc requests using `NodeHandle`

### ISSUE THREAD

**Issue by ayushm2003** [paradigmxyz/reth#6614]
### Describe the feature

Want to be able to listen to the incoming rpc requests after launching a node say using [`launch_from_config`](https://github.com/paradigmxyz/reth/blob/main/bin/reth/src/builder.rs#L73)

### Additional context

Matthias' comment on tg: "this will be possible once we update some rpc dependencies and expose this"

**Comment by mattsse** [comment]
ref #5894
