### ISSUE TITLE
Healthcheck call for verifying if the client is operational

### ISSUE THREAD

**Issue by rswanson** [paradigmxyz/reth#6619]
### Describe the feature

As an operator it would be great if there were a single call that could be made via rpc to validate the health of a given client from an operational perspective. Effectively the goal of the call (suggested: `eth_healthcheck`) would be to answer the question "is this running binary healthy" so that automation can make informed decisions as to the health of a given node and whether it should be made available for use or potentially marked as unhealthy. 

Design notes:
- expected that this call would be made on a consistent (every X seconds) basis so it should be lightweight
- if there was a desire to expose any other health metrics over rpc I would recommend separating the call that returns health (a boolean, maybe a status at most) vs the call to introspect into the running system (something that returns rich data)

**Comment by cfc-ctf** [comment]
+1 on this

I also suggest that the short answer contains a simple code/flag, indicating the type or error, especially for external errors easy to detect (no working CL, no network, no peers, no DNS, no disk space left, …)
