### ISSUE TITLE
Discuss: Reorgs 

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#662]
Writing this for future discussion.

for Ethereum network where reorg can happen only on one block, we are aggregating potential blocks until forkchoice API is called from CL side to finalize it. While I am now thinking about this most of the Ethereum like blockchains with finality can be done in that way. Downside is that in this case, state is updated only when finalization happens, we are introducing a small delay here (We can probably allow execution on the state of those pending blocks).

We are currently saving NumHash for block `bodies/headers/transactions` how exactly is this going to be used?

Polygon is maybe the only one that has deep reorgs: https://polygonscan.com/blocks_forked?p=3
For it we would need to execute N blocks to check if the new chain is valid, unwind N block from current chain, execute new N blocks from the new chain, the new chain becomes current.

**Comment by rkrasiuk** [comment]
One solution is to bake reorg logic into the headers stage. The reason for that is that we don't know about the reorg unless writing the header data into the database fails (most likely the line below). We don't know neither about reorg having occurred nor about its depth.
https://github.com/paradigmxyz/reth/blob/4efb7b92b84c73fe2effbc5089d63a2a643d5524/crates/stages/src/stages/headers.rs#L279
Open to other suggestions

**Comment by rakita** [comment]
> One solution is to bake reorg logic into the headers stage. The reason for that is that we don't know about the reorg until we attempt to write header data into the database (the line below would most likely fail). We don't know neither about reorg having occurred nor about its depth.
> 
> https://github.com/paradigmxyz/reth/blob/4efb7b92b84c73fe2effbc5089d63a2a643d5524/crates/stages/src/stages/headers.rs#L279
> 
> 
> Open to other suggestions

Just to say this statement differently: writing to `CanonicalHeader` table is the point of choice if block is going to reorg the main chain.

**Comment by rakita** [comment]
Soo, we discussed having pending blocks and sidechains handled in memory, and for main tables to contain only canonical blocks.
More on the efforts in that direction can be found here: https://github.com/paradigmxyz/reth/issues/1107 and here https://github.com/paradigmxyz/reth/issues/1104
