### ISSUE TITLE
Automatically set pr labels upon open

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6637]
### Describe the feature

Update actions to set labels on PRs that have "close #XXXX" in the description. Labels on the PR should match labels on the issue. This action should run when a PR is opened. If the PR doesn't have "close #XXXX" in the description, it doesn't get labeled.

**Comment by supernovahs** [comment]
`closes xxxx` and `close xxxx` both would work right?

**Comment by emhane** [comment]
> `closes xxxx` and `close xxxx` both would work right?

I'm not sure...try it out on one of your prs. should pop up under the "Development" heading in the right-hand side column on your pr if it works.

**Comment by onbjerg** [comment]
yes, "closes", "close", "fixes", "fix", and others: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
