### ISSUE TITLE
Unblock `NetworkState`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6642]
### Describe the feature

Branching from changes that were requested too late https://github.com/paradigmxyz/reth/pull/6640#pullrequestreview-1886660131.

As mentioned in the link PR, `Swarm` can still block and starve other threads. So, one iteration in `NetworkManager` might take a second, or it might take some microseconds.

Even if we made the budget in network manager a `Duration` instead of an `i32`, we would still not return from swarm if it blocks. So, let's aim at unblocking swarm, most pressingly the nested stream `NetworkState`.

https://github.com/paradigmxyz/reth/blob/29701f6486717514673e61b2b9b49418de7c4187/crates/net/network/src/state.rs#L398-L471

**Comment by mattsse** [comment]
this type doesn't do any blocking IO, network future is pre-empted on top level to which events a are bubbled up

**Comment by emhane** [comment]
propose of issue is not only for DoS protection, also for addressing starvation between reth components and cl running on same machine
