### ISSUE TITLE
Re-add network transaction channel size metric

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6663]
https://github.com/paradigmxyz/reth/pull/6650 Removed the `messages in channel` metric for the network transaction channel. This is extremely useful for understanding how the channel size effects memory usage, and the difference in sent / received is not as easy to see visually, especially when it may only be a small difference. The original issue described a problem with its name on the dashboard, not its usefulness.

**Comment by jsvisa** [comment]
Sorry for that, I'll add it back ASAP
