### ISSUE TITLE
strange failure of eth_sendTransaction

### ISSUE THREAD

**Issue by drortirosh** [paradigmxyz/reth#6670]
### Describe the bug

The following command:
```
cast rpc eth_sendTransaction '{"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266", "to":"0x70997970C51812dc3A010C7d01b50e0d17dc79C8" }'
```

Fails with a strange error:
```
Error:
(code: -32602, message: both gasPrice and (maxFeePerGas or maxPriorityFeePerGas) specified, data: None)
```

### Steps to reproduce

run the above command.

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

reth Version: 0.1.0-alpha.18

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
@Evalir this looks like a serde error on TransactionRequest

**Comment by onbjerg** [comment]
@mattsse this is an intentional check in reth: https://github.com/paradigmxyz/reth/blob/7cb9eaea9c5cad7637f6d869e3f5a45af849358c/crates/rpc/rpc/src/eth/api/transactions.rs#L741

**Comment by jsvisa** [comment]
seems it is related to the default value of `gas_price` and `max_fee_per_gas`. I want to fix this issue, could you please assign it to me, thanks :)

**Comment by jsvisa** [comment]
in reth the default value is null if not given. but in go-ethereum the default value of `gas_price` or eip1559 gas is derived from the chain states

**Comment by Evalir** [comment]
@mattsse i think this actually seems to be cast specifying both legacy/eip1559 gas fields if none are set?

**Comment by mattsse** [comment]
this is a reth bug,
fixing rn

**Comment by jsvisa** [comment]
btw, even if I specify the `gasPrice`, reth also can't handle it.

> request

```json
{
  "jsonrpc": "2.0",
  "method": "eth_sendTransaction",
  "id": 1,
  "params": [
    {
      "value": "0x0",
      "to": "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
      "gas": "0x76c0",
      "data": "0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675",
      "gasPrice": "0x9184e72a000",
      "from": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    }
  ]
}
```

> response

```json
{
  "error": {
    "code": -32602,
    "message": "both gasPrice and (maxFeePerGas or maxPriorityFeePerGas) specified"
  },
  "id": 1,
  "jsonrpc": "2.0"
}
```
