### ISSUE TITLE
call to eth_getTransactionReceipt for a transaction returns null 

### ISSUE THREAD

**Issue by abhijeetbhagat** [paradigmxyz/reth#6678]
### Describe the bug

i am trying to [setup a base node](https://docs.base.org/guides/run-a-base-node/#running-a-node) with reth + lighthouse as the L1 rpc node connected to eth mainnet & fully synced. in the base node logs, i see this error: 
```
t=2024-02-19T19:45:20+0000 lvl=warn msg="Derivation process temporary error" attempts=5 err="temp: failed to fetch receipts of L1 block 0x7946514c046f3b2598eed41b32e1bccafcd90fa3a2f721a79cf34bb77bd4a816:17481769 (parent: 0x5c13d307623a926cd31415036c8b7fa14572f9dac64528e857a470511fc30771:17481768) for L1 sysCfg update: got 1 receipts but expected 163"
```
when i call `eth_getTransactionReceipt` for `0x7946514c046f3b2598eed41b32e1bccafcd90fa3a2f721a79cf34bb77bd4a816` i get a null result:
```
⟩ curl 'http://url-of-my-reth-rpc-endpoint/'  -X POST   -H "Content-Type: application/json"  --data '{"method":"eth_getTransactionReceipt","params":["0x7946514c046f3b2598eed41b32e1bccafcd90fa3a2f721a79cf34bb77bd4a816"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","result":null,"id":1}
```

### Steps to reproduce

1. setup reth + lighthouse fully synced with the eth mainnet
2. clone https://github.com/base-org/node
3. in the docker-compose.yml file, uncomment both the `.env.mainnet` lines under `env_file`
4. in the .env.mainnet file, set the `OP_NODE_L1_ETH_RPC` & `OP_NODE_L1_BEACON` vars to the rpc & beacon urls respectively.  
5. uncomment `OP_NODE_L1_TRUST_RPC=true`
6. pass `--l1.trustrpc` to `./op-node` in the `op-node-entrypoint.sh`
7. build the images using `docker compose build` & run using `docker-compose up -d`
8. check the logs for `base-node-node-1`

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

 0.1.0-alpha.16

### What database version are you on?

```
# ./reth db version
Current database version: 1
Local database version: 1
```

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Degen-Player** [comment]
seem like you don't have all states

are you running archive node ?

**Comment by abhijeetbhagat** [comment]
i am running a full node since it is a requirement from the setup docs:
```
Ensure you have an Ethereum L1 full node RPC available (not Base), and set OP_NODE_L1_ETH_RPC (in the .env.* file if using docker-compose). If running your own L1 node, it needs to be synced before Base will be able to fully sync.
```

**Comment by Degen-Player** [comment]
> i am running a full node since it is a requirement from the setup docs:
> 
> ```
> Ensure you have an Ethereum L1 full node RPC available (not Base), and set OP_NODE_L1_ETH_RPC (in the .env.* file if using docker-compose). If running your own L1 node, it needs to be synced before Base will be able to fully sync.
> ```

Don't.

Run an archive node. 

See https://geth.ethereum.org/docs/fundamentals/sync-modes


Closing this because unrelated to reth issue

**Comment by joshieDo** [comment]
Our full node does prune receipts, that's why it returns null here. Like @Degen-Player  mentioned for this usecase you should use archive, or an archive where custom pruning options (eg. pruning changesets) : [book](https://paradigmxyz.github.io/reth/run/config.html#the-prune-section)
