### ISSUE TITLE
TransitionConfiguration can't be deserialized

### ISSUE THREAD

**Issue by leruaa** [paradigmxyz/reth#669]
### Describe the feature

I'm using some Reth crates as libs for a project, and I need to handle `engine_exchangeTransitionConfigurationV1` method from CL.

Unfortunately, when trying to deserialize `transitionConfiguration` json into [reth_rpc_types::eth::engine::TransitionConfiguration](https://github.com/paradigmxyz/reth/blob/4efb7b92b84c73fe2effbc5089d63a2a643d5524/crates/net/rpc-types/src/eth/engine.rs#L144), I get an error because  `terminal_block_number` is stored as a 0x-prefixed, big-endian hex string, and the corresponding field on `TransitionConfiguration` is `u64`.

**Comment by leruaa** [comment]
I would be happy to work on a fix. I guess there is 2 options:

- Just change `terminal_block_number` type from `BlockNumber` to `U64`
- Add a de/serialization helper like [this one](https://github.com/sigp/lighthouse/blob/21dec6f603edd53ad8d2372941c77ab8098d3b5a/consensus/serde_utils/src/u64_hex_be.rs) to handle de/serialization correctly

what would be the best thing to do?

@rkrasiuk maybe you had the same issue while working on #616?

**Comment by mattsse** [comment]
since these are RPC types, let's just replace u64 with `U64` here which deserializes/serializes as hex

**Comment by rkrasiuk** [comment]
@leruaa agree w/ everything above, do you want to take on this issue?

**Comment by leruaa** [comment]
Yes, I'm just about to push ;)
