### ISSUE TITLE
Use smallvec for txs_by_sender

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6690]
### Describe the feature

we know

https://github.com/paradigmxyz/reth/blob/a5dc8d66799412d3e19f6c80e4857ffac0269a5a/crates/transaction-pool/src/pool/parked.rs#L90-L90

will return fewer entries than:

https://github.com/paradigmxyz/reth/blob/a5dc8d66799412d3e19f6c80e4857ffac0269a5a/crates/transaction-pool/src/config.rs#L5-L5

this is frequently allocated+deallocated in this loop

https://github.com/paradigmxyz/reth/blob/a5dc8d66799412d3e19f6c80e4857ffac0269a5a/crates/transaction-pool/src/pool/parked.rs#L163-L163

TransactionId is 2 u64

we can move this inline to `SmallVec<[;16]>`

**Comment by loocapro** [comment]
Can i take this?
