### ISSUE TITLE
Remove Optimism specific network config from reth-network

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6695]
### Describe the feature

This is unused internally

https://github.com/paradigmxyz/reth/blob/3a4ca175c7f31df968098c9bd4bf5b5eb3c9792a/crates/net/network/src/config.rs#L80-L82

This is only exposed via:

https://github.com/paradigmxyz/reth/blob/3a4ca175c7f31df968098c9bd4bf5b5eb3c9792a/crates/net/network/src/network.rs#L318-L318

and used by rpc

https://github.com/paradigmxyz/reth/blob/ca2c883cd64dbeb94650a8fb34c9b5b339ecf9a0/crates/rpc/rpc/src/eth/api/transactions.rs#L1192-L1192

## TODO

* remove this from reth-network
* move to RPC instead, together with:
https://github.com/paradigmxyz/reth/blob/ca2c883cd64dbeb94650a8fb34c9b5b339ecf9a0/crates/rpc/rpc/src/eth/api/mod.rs#L494-L496

**Comment by rodrigoherrerai** [comment]
Can I take it ?

**Comment by mattsse** [comment]
assgined!

lmk if you need more context

**Comment by rodrigoherrerai** [comment]
@mattsse If I understand it correctly we need to remove the sequencer_endpoint from the network crate, move it to RPC and update the transaction.rs file where it is used. 

Is this correct ? 

If so, should it be a new separate field in https://github.com/paradigmxyz/reth/blob/ca2c883cd64dbeb94650a8fb34c9b5b339ecf9a0/crates/rpc/rpc/src/eth/api/mod.rs#L467 or should it be together with the http_client: https://github.com/paradigmxyz/reth/blob/ca2c883cd64dbeb94650a8fb34c9b5b339ecf9a0/crates/rpc/rpc/src/eth/api/mod.rs#L496

**Comment by mattsse** [comment]
exactly,

I think we want this in a separate type, like `SequencerClient {url, client}` 
then we can make the field: Option<SequencerClient>

**Comment by rodrigoherrerai** [comment]
@mattsse  one q, to get the sequencer_endpoint from the config, should it be done here directly https://github.com/paradigmxyz/reth/blob/ca2c883cd64dbeb94650a8fb34c9b5b339ecf9a0/crates/rpc/rpc/src/eth/api/mod.rs#L126 and removed from here https://github.com/paradigmxyz/reth/blob/2f3c3089bc1c6d8a7b588a8e51a859eadb4c7742/crates/node-core/src/node_config.rs#L773

?
