### ISSUE TITLE
Make ETL file size configurable

### ISSUE THREAD

**Issue by joshieDo** [paradigmxyz/reth#6696]
this should be configurable to allow lower-end and higher-end hardware to operate at their capacity

_Originally posted by @shekhirin in https://github.com/paradigmxyz/reth/pull/6655#discussion_r1495727679_

**pending `feat/static` merge into `main`**

**Comment by justcode740** [comment]
can take this

**Comment by SozinM** [comment]
Hi @justcode740 @joshieDo do you mind me taking this issue?
Already started to work on it.
