### ISSUE TITLE
Add grafana panel for maintenance txpool metrics

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6709]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/86788c618c636fa70f4efdc88b9cb1680e69e4c7/crates/transaction-pool/src/metrics.rs#L64-L72

## TODO
* add metrics to grafana dashboard

**Comment by AbnerZheng** [comment]
Can I give it a try?

**Comment by mattsse** [comment]
thanks,

we have a few txpool related metrics in the dashboard already, best to add them there

**Comment by AbnerZheng** [comment]
Just created the [PR](https://github.com/paradigmxyz/reth/pull/6719), PTAL when you are available.
