### ISSUE TITLE
Remove "SAFETY:" tag on comments that are not related to `unsafe` blocks

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#6724]
### Describe the feature

The `// SAFETY: ` comment tag is used above `unsafe` blocks and `impl`s to explain the need of its usage or why it's safe.

This is not always the case in this code base, where it's also used above calls to `unwrap()`/`expect("...")` explaining why it won't panic, and other places which are completely unrelated to `unsafe`.

These should be replaced with `NOTE: ` or removed to make it just a normal comment.

### Additional context

- [Rust standard library guideline](https://std-dev-guide.rust-lang.org/policy/safety-comments.html)
- [`clippy::undocumented_unsafe_blocks`](https://rust-lang.github.io/rust-clippy/master/#/undocumented_unsafe_blocks)
- [`clippy::missing_safety_doc`](https://rust-lang.github.io/rust-clippy/master/#/missing_safety_doc)
- [`zerocopy::safety_comment!`](https://github.com/google/zerocopy/blob/2b1a900de300f079717c78a01dbd2bfaa9a5a080/src/macros.rs#L9-L33)

**Comment by TomAFrench** [comment]
This can be closed now.
