### ISSUE TITLE
Improve Engine API abstraction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6734]
### Describe the feature

Currently we provide a way to abstract parts of the engine API (PayloadAttributes) because these are different eth vs OP

https://github.com/paradigmxyz/reth/blob/a4c034903b7d136b237a4f8e284d9eace43ae724/crates/node-api/src/engine/mod.rs#L19-L24

with https://github.com/alloy-rs/alloy/pull/227 we now have the case where the return type: `ExecutionPayload` is also no longer consistent which means those trait conversion functions are no longer entirely consistent:

https://github.com/paradigmxyz/reth/blob/a4c034903b7d136b237a4f8e284d9eace43ae724/crates/node-api/src/engine/traits.rs#L15-L32

The way it currently works is, the `EngineTypes` configure
* The PayloadAttributes type: type we get from the CL
* BuiltPayload: the type that payload builder service builds, which currently must be convertible into the versioned execution payload envelope

I think we now also the `ExecutionPayloadV*` types to be configurable, so that we can have clean types for all networks and don't need additional Options for OP for example, see alloy PR

## TODO
we can solve this in a number of ways, but I think we want an additional associated type for the  `ExecutionPayload` on the `EngineTypes` trait and then a requirement that the configured `BuiltPayload` can be converted into this type.

perhaps we want an associated type for each version or an enum, I assume 3 types might be easier to handle from engine impl POV: https://github.com/paradigmxyz/reth/blob/a4c034903b7d136b237a4f8e284d9eace43ae724/crates/rpc/rpc-engine-api/src/engine_api.rs#L253-L256

This would also require to introduce OP specific V3 type on alloy-rpc

@fgimenez would you be interested in this?

**Comment by fgimenez** [comment]
> @fgimenez would you be interested in this?

absolutely! thx a lot @mattsse will start with it asap

**Comment by mattsse** [comment]
fyi @fgimenez this is also relevant here

https://github.com/paradigmxyz/reth/issues/6331

We should do `TryFrom` or similar
