### ISSUE TITLE
Log Execution stage speed in mgas/s

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#6741]
### Describe the feature

Currently, we only report processed gas in the Execution stage to metrics https://github.com/paradigmxyz/reth/blob/755ce9efc2b9c0bca2e715522778e83df91b2fe6/crates/stages/src/stages/execution.rs#L171-L175

We also need to log this data, so even users without metrics set up can have an idea of the performance they have. Ideally, it should be in mgas/s, and reported in the node events https://github.com/paradigmxyz/reth/blob/755ce9efc2b9c0bca2e715522778e83df91b2fe6/crates/node-core/src/events/node.rs#L126-L148

**Comment by MuhtasimTanmoy** [comment]
Working on it

**Comment by shekhirin** [comment]
hey @MuhtasimTanmoy, any progress on this?

**Comment by MuhtasimTanmoy** [comment]
Sorry for delay. Will update within tomorrow.

**Comment by MuhtasimTanmoy** [comment]
While using `docker compose` to run `reth` getting this error.

```
reth-1  | thread 'main' panicked at /project/crates/primitives/src/integer_list.rs:51:18:
reth-1  | IntegerList must be pre-sorted and non-empty: NonSortedIntegers { valid_until: 1 }
```

Any insight?

**Comment by MuhtasimTanmoy** [comment]
@shekhirin 

Which node event should be reported to? `PipelineEvent::Ran` ?

**Comment by MuhtasimTanmoy** [comment]
@shekhirin for publishing as Node Event is this the right approach as `PipelineEvent::Ran` is emitted when a stage has run a single time?

```rust
self.listeners.notify(PipelineEvent::Ran {
    pipeline_stages_progress: event::PipelineStagesProgress {
        current: stage_index + 1,
        total: total_stages,
    },
    stage_id,
    result: out.clone(),
});
```

To log `gas_used` in `mgas/s` where should the following line go as the `PipelineEvent::Ran` event doesn't seem to have any field for that?

`mgas=%format!("{:.3}", block.header.gas_used as f64 / constants::MGAS_TO_GAS as f64)`

**Comment by Rjected** [comment]
bump @shekhirin for advice here

**Comment by Rjected** [comment]
@MuhtasimTanmoy if you have any progress it would be great to open a PR! We can give more detailed feedback there

**Comment by sdfii** [comment]
I would like to continue.

**Comment by Rjected** [comment]
@sdfii assigned! I just added some utils that should make this easier here:
https://github.com/paradigmxyz/reth/pull/9247

lmk if you run into any blockers!
