### ISSUE TITLE
Problem with jemalloc on system with larger page size

### ISSUE THREAD

**Issue by jtraglia** [paradigmxyz/reth#6742]
### Describe the bug

It appears that jemalloc is built with the expectation of 4K pages. This will not work for Linux systems with larger page sizes, such as 16K and 64K on some newer ARM systems. I mentioned this in telegram and the following PR was made:

* https://github.com/paradigmxyz/reth/pull/6495

But this doesn't appear to disable jemalloc. If I test this on a different ARM system with a standard 4K page size, it shows that jemalloc is still enabled:

```
$ getconf PAGE_SIZE
4096
$ docker run --rm ghcr.io/paradigmxyz/reth:v0.1.0-alpha.19 --version
reth Version: 0.1.0-alpha.19
Commit SHA: 0192934
Build Timestamp: 2024-02-19T21:13:25.581883626Z
Build Features: jemalloc
Build Profile: maxperf
```

Worth mentioning that this isn't an issue on macOS for some reason. It must use a jemalloc built to support 16K pages.

### Steps to reproduce

On an arm64 machine running Linux with a larger page size, run the following command:

```
$ docker run --rm ghcr.io/paradigmxyz/reth:v0.1.0-alpha.19 --version
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
```

You can check the page size like so:

```
$ getconf PAGE_SIZE
16384
```

### Platform(s)

Linux (ARM)

### What version/commit are you on?

v0.1.0-alpha.19

### What database version are you on?

N/A

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by jtraglia** [comment]
@DaniPopes the PR I made last week did not fix this problem. It appears that jemalloc is still enabled on aarch64 docker images. How are the Reth docker images created? And can you re-open this issue?

```
$ docker run --rm ghcr.io/paradigmxyz/reth:v0.1.0-alpha.20 --version
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed

$ docker run --rm ghcr.io/paradigmxyz/reth:v0.1.0-alpha.21 --version
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
```

**Comment by DaniPopes** [comment]
Docker releases are created with https://github.com/paradigmxyz/reth/blob/6e0cf0f33a03ef8066abb6f2a8effc549b05ecf1/.github/workflows/docker.yml#L40

We want to remove jemalloc from `FEATURES` when building for docker in the makefile.

**Comment by jtraglia** [comment]
Hmm. But I thought that's what my PR did.

`docker-build-latest` calls `build_docker_image`

https://github.com/paradigmxyz/reth/blob/02111c4213ba8ede8694e0c55b7b170a20a98f19/Makefile#L187-L188

`build_docker_image` will build the aarch64 binary.

https://github.com/paradigmxyz/reth/blob/02111c4213ba8ede8694e0c55b7b170a20a98f19/Makefile#L199-L208

And `build-aarch64-unknown-linux-gnu` filters out jemalloc.

https://github.com/paradigmxyz/reth/blob/02111c4213ba8ede8694e0c55b7b170a20a98f19/Makefile#L88-L91

**Comment by DaniPopes** [comment]
Ah yeah, it's just enabled by default on every command unless `--no-default-features` is specified.
