### ISSUE TITLE
Feat: extend eth_getLogs RPC to return blockTimestamp in the log object response 

### ISSUE THREAD

**Issue by sambacha** [paradigmxyz/reth#6752]
### Describe the feature

> Per discussion in https://github.com/paradigmxyz/reth/issues/5680 I am opening up a new issue for this requested feature.

## New Feature: Addition of a `blockTimestamp` field in the log object returned by eth_getLogs.

The proposed enhancement to include a `blockTimestamp` field in the eth_getLogs response is a pragmatic approach to solving a significant efficiency problem faced by Ethereum applications. It streamlines the process of fetching event data with timestamps, which is critical for many blockchain-based applications. 

### Purpose

This field will contain the Unix timestamp of the block where the event occurred, eliminating the need for additional requests to fetch this information.

### Impact

The inclusion of the `blockTimestamp` will significantly reduce the number of requests needed to process events with timestamp data, enhancing the efficiency of indexers and dApps.

### Specification

A specification was originally drafted here: https://github.com/ethereum/execution-apis/issues/295 , an updated copy can be found here as well: https://github.com/manifoldfinance/rpc-eip-drafts/blob/master/eth_getLogs+timestamp/README.md

#### Object 

The filter options:

**fromBlock**: QUANTITY|TAG - (optional, default: "latest") Integer block number, or "latest" for the last mined block or "pending", "earliest" for not yet mined transactions.
**toBlock**: QUANTITY|TAG - (optional, default: "latest") Integer block number, or "latest" for the last mined block or "pending", "earliest" for not yet mined transactions.
**address**: DATA|Array, 20 Bytes - (optional) Contract address or a list of addresses from which logs should originate.
**topics**: Array of DATA, - (optional) Array of 32 Bytes DATA topics. Topics are order-dependent. Each topic can also be an array of DATA with "or" options.
**blockhash**: DATA, 32 Bytes - (optional, future) With the addition of EIP-234, blockHash will be a new filter option which restricts the logs returned to the single block with the 32-byte hash blockHash. Using blockHash is equivalent to fromBlock = toBlock = the block number with hash blockHash. If blockHash is present in in the filter criteria, then neither fromBlock nor toBlock are allowed.

```jsonc
params: [
  {
    topics: [
      "0x000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b",
    ],
  },
]
```

#### Returns 

Array - Array of log objects, with following params:

**removed**: TAG - true when the log was removed, due to a chain reorganization. false if its a valid log.
**logIndex**: QUANTITY - integer of the log index position in the block. null when its pending log.
**transactionIndex**: QUANTITY - integer of the transactions index position log was created from. null when its pending log.
**transactionHash**: DATA, 32 Bytes - hash of the transactions this log was created from. null when its pending log.
**blockHash**: DATA, 32 Bytes - hash of the block where this log was in. null when its pending. null when its pending log.
**blockNumber**: QUANTITY - the block number where this log was in. null when its pending. null when its pending log.
**blockTimestamp**: QUANTITY - the unix timestamp for when the block where this log was in, was collated. null when its pending. null when its pending log.
**address**: DATA, 20 Bytes - address from which this log originated.
**data**: DATA - contains one or more 32 Bytes non-indexed arguments of the log.
**topics**: Array of DATA - Array of 0 to 4 32 Bytes DATA of indexed log arguments. (In solidity: The first topic is the hash of the signature of the event (e.g. Deposit(address,bytes32,uint256)), except you declared the event with the anonymous specifier.)

**Comment by cairoeth** [comment]
can take this one
