### ISSUE TITLE
Reduce debug log target spam

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6754]
### Describe the feature

ref #6644

we're currently logging a lot of network related stuff on debug target.
most of it is very spammy and not meaningful.

should re-evaluate certain debug! logs and downgrade to trace!

**Comment by abhijeetbhagat** [comment]
i can pick this @mattsse

**Comment by shekhirin** [comment]
Fixed by https://github.com/paradigmxyz/reth/pull/6815
