### ISSUE TITLE
Add more eth_ getraw transactions functions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6760]
## TODO

Add missing eth functions: 

* `eth_getRawTransactionByBlockNumberAndIndex`: https://github.com/ethereum/go-ethereum/blob/b590cae89232299d54aac8aada88c66d00c5b34c/internal/ethapi/api.go#L1592-L1592
* `eth_getRawTransactionByBlockHashAndIndex`: https://github.com/ethereum/go-ethereum/blob/b590cae89232299d54aac8aada88c66d00c5b34c/internal/ethapi/api.go#L1600-L1600
* `eth_getRawTransactionByHash`: https://github.com/ethereum/go-ethereum/blob/b590cae89232299d54aac8aada88c66d00c5b34c/internal/ethapi/api.go#L1648-L1648

Note for `eth_getRawTransactionByHash` and blob tx this needs to include the blobs:

https://github.com/paradigmxyz/reth/blob/761c707e418bbe90bd2e47357ecf1673185f6c2a/crates/transaction-pool/src/traits.rs#L218-L222

Similar to 

https://github.com/paradigmxyz/reth/blob/761c707e418bbe90bd2e47357ecf1673185f6c2a/crates/rpc/rpc/src/debug.rs#L637-L639

but here:

https://github.com/paradigmxyz/reth/blob/761c707e418bbe90bd2e47357ecf1673185f6c2a/crates/rpc/rpc-api/src/eth.rs#L96-L98

fyi @loocapro

**Comment by loocapro** [comment]
May I?

**Comment by mattsse** [comment]
assigned
