### ISSUE TITLE
Add new txpool trait function for retrieving 1 pooled tx by hash 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6761]
### Describe the feature

Basically same as:

https://github.com/paradigmxyz/reth/blob/761c707e418bbe90bd2e47357ecf1673185f6c2a/crates/transaction-pool/src/traits.rs#L218-L222

but with a single hash as arg

ref #6760

**Comment by gr4yha7** [comment]
@mattsse can I take this?
