### ISSUE TITLE
max_concurrent_outbound_dials does not restrict max concurrent outbound dials

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6778]
### Describe the feature

The `max_concurrent_outbound_dials` 
https://github.com/paradigmxyz/reth/blob/a7e183d1a58f3d7eada9a087eca56af5e794e916/crates/net/network/src/peers/manager.rs#L832-L834

only restricts how many __new__ outbound dials we create __at once__ but this does not respect how many are already in progress atm.

https://github.com/paradigmxyz/reth/blob/a7e183d1a58f3d7eada9a087eca56af5e794e916/crates/net/network/src/peers/manager.rs#L702-L702

This should instead restrict how many outbound dials we allow at once and should slow down new connections if exceeded.

## TODO

This can be solved by a new connection state and counter that is `PendingOut`

https://github.com/paradigmxyz/reth/blob/a7e183d1a58f3d7eada9a087eca56af5e794e916/crates/net/network/src/peers/manager.rs#L822-L824

https://github.com/paradigmxyz/reth/blob/a7e183d1a58f3d7eada9a087eca56af5e794e916/crates/net/network/src/peers/manager.rs#L1021-L1022

when we initiate an outgoing connection the peer's state is set to `PendingOut` and counter increased.

once the session is established or failed we need to update the state and counter for all possible cases:

https://github.com/paradigmxyz/reth/blob/a7e183d1a58f3d7eada9a087eca56af5e794e916/crates/net/network/src/peers/manager.rs#L850-L850

https://github.com/paradigmxyz/reth/blob/a7e183d1a58f3d7eada9a087eca56af5e794e916/crates/net/network/src/peers/manager.rs#L386-L386

and need a new function `on_active_session_established` that then shifts the peer's state from `PendingOut` to `Out`

**Comment by abhijeetbhagat** [comment]
@mattsse i can take this

**Comment by mattsse** [comment]
nice, lmk if anything's unclear

**Comment by abhijeetbhagat** [comment]
@mattsse where should `on_active_session_established` be called from?

**Comment by mattsse** [comment]
from top level, we already have it for incoming, we also need it for outgoing:

https://github.com/paradigmxyz/reth/blob/be6d5057451501285f9cfa95682bfdcbd055be3d/crates/net/network/src/manager.rs#L733-L738
