### ISSUE TITLE
Communicate to read-write engine hook that it needs to stop

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#6796]
### Describe the feature

We need to be able to tell a running hook with a database read-write access that it needs to stop ASAP, so we can process a new incoming Engine message.

Currently, we just skip an incoming FCU if such a hook is running https://github.com/paradigmxyz/reth/blob/ac36fa96ecca5d7aa1a223b7755c996b84c00449/crates/consensus/beacon/src/engine/mod.rs#L358-L368

Ideally, we want to let the hook know that it needs to be stopped ASAP, so the Engine loop can proceed with the FCU.

See https://github.com/paradigmxyz/reth/pull/6792#issuecomment-1964289389

**Comment by krakovia-evm** [comment]
not sure but probably what you're talking about gave me bad performances reported in that issue
https://github.com/paradigmxyz/reth/issues/6644#issuecomment-1962394045

**Comment by emhane** [comment]
this could be solved by running operations of all types that impl `EngineHook` in one dedicated thread, in order to prioritise them. see how it's done for reconstruction, finalization migration and blob pruning in lh https://github.com/sigp/lighthouse/blob/b5bae6e7a2f52310617a3b93ab7579f3dc9d7880/beacon_node/beacon_chain/src/migrate.rs#L421-L432. wdyt @shekhirin ?

**Comment by shekhirin** [comment]
@emhane unsure if that will solve this issue that easily, because we mostly care about stopping the database write transaction taken by a hook, and not acquiring the blocking thread.

**Comment by emhane** [comment]
that would be if we are sending the db rw op that the current thread want to execute to that same thread i.e. that all db rw op go through one thread (same model as `TxnManager` but on this higher level). so fork choice update, pruning, static files producer (did I miss anything?).

any pointers on how clean interrupt should be done for the respective types that impl `EngineHook`?

**Comment by emhane** [comment]
related https://github.com/paradigmxyz/reth/issues/6770
