### ISSUE TITLE
Bound hashes inflight and pending fetch cache

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6801]
Right now we have a cache that is unbounded:
https://github.com/paradigmxyz/reth/blob/facad24ad64b322b309c2a6547d931cdf0f7bca8/crates/net/network/src/transactions/fetcher.rs#L54

This should be bounded, so it does not grow indefinitely

**Comment by int88** [comment]
@Rjected I could take this :)

**Comment by Rjected** [comment]
> @Rjected I could take this :)

sure! assigned, also let me know if you see that bounding this data structure would break some invariant in fetching
