### ISSUE TITLE
Prune known senders on new block

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6802]
Right now we have a few maps that grow unbounded with the number of known senders:
https://github.com/paradigmxyz/reth/blob/facad24ad64b322b309c2a6547d931cdf0f7bca8/crates/transaction-pool/src/pool/txpool.rs#L47

https://github.com/paradigmxyz/reth/blob/facad24ad64b322b309c2a6547d931cdf0f7bca8/crates/transaction-pool/src/identifier.rs#L13-L16

When we have a new block, we should remove senders in this map which do not exist in any subpool

**Comment by gr4yha7** [comment]
@Rjected  can I take this?

**Comment by Rjected** [comment]
My current thinking: it will probably be expensive to do this on every eviction, the pool and sender id lock have to be taken, and we'd be iterating over multiple lists of ~25k senders. If we do this in the maintain loop, it won't be run if the node is syncing. But maybe that's fine

**Comment by mattsse** [comment]
we can do this here

https://github.com/paradigmxyz/reth/blob/27f1496daaddccfceec51592003c7eddc0acb42c/crates/transaction-pool/src/pool/mod.rs#L360-L360

perhaps every x updates then fetch all unique senders in the pool and cleanup:

https://github.com/paradigmxyz/reth/blob/27f1496daaddccfceec51592003c7eddc0acb42c/crates/transaction-pool/src/pool/mod.rs#L134-L134

**Comment by Rjected** [comment]
going to close this, complexity for doing this is not worth it
