### ISSUE TITLE
Add metrics for AllTransactions

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6808]
We have a struct in the transaction pool called `AllTransactions`:
https://github.com/paradigmxyz/reth/blob/ce28fe32d94a67e8db8295c63ec95724d31ddbc2/crates/transaction-pool/src/pool/txpool.rs#L921

It would be good to get some basic metrics for some of the contained data structures, notably these
https://github.com/paradigmxyz/reth/blob/ce28fe32d94a67e8db8295c63ec95724d31ddbc2/crates/transaction-pool/src/pool/txpool.rs#L930-L935

**Comment by codenikel** [comment]
@Rjected Can I take this one?

Will this primarily involve adding a `metrics` field similar to https://github.com/paradigmxyz/reth/blob/ce28fe32d94a67e8db8295c63ec95724d31ddbc2/crates/transaction-pool/src/pool/txpool.rs#L76

**Comment by Rjected** [comment]
> @Rjected Can I take this one?
> 
> Will this primarily involve adding a `metrics` field similar to
> 
> https://github.com/paradigmxyz/reth/blob/ce28fe32d94a67e8db8295c63ec95724d31ddbc2/crates/transaction-pool/src/pool/txpool.rs#L76

yep, exactly, just assigned!
