### ISSUE TITLE
Decouple commonly used Network features

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#683]
### Describe the feature

the `network` crate includes types commonly used by other crates, most importantly the `NetworkHandle` type.

NetworkHandle is pretty powerful, and usually, only a tiny part is used, for example in RPC implementations to interact with the network.

This could be improved by introducing a new crate `network-common` where we can introduce additional traits that encapsulate network behavior, which is then implemented by `NetworkHandle`.

having specific behavior encapsulated, makes it easier to come up with tests, because it we don't need to create a `NetworkHandle` first.

Alternatively, this could be done in the `interfaces` crate but I'd like to have a network related separate crate for this.

**Comment by gakonst** [comment]
@mattsse can this be closed, or do we need to refactor more parts from the NetworkHandle? if yes, which?
