### ISSUE TITLE
Prevent indefinite transactions_by_peers growth

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6834]
The `transactions_by_peers` data structure in the `TransactionsManager` appears to grow unbounded:
![Screenshot 2024-02-27 at 7 56 19 PM](https://github.com/paradigmxyz/reth/assets/6798349/5ee17ff9-a1fc-422f-a935-6ed52cbab618)
In this graph, `transactions by peers total count` is the sum of the `vec` lengths, and `transactions by peers` is the number of keys in the map.

See the following from a memory profile, the push operation accounts for almost a third of inuse space:
![image](https://github.com/paradigmxyz/reth/assets/6798349/371dcb26-1c44-4998-9d09-0f12332b5f83)

The line referred to in the memory profile is here:
https://github.com/paradigmxyz/reth/blob/445e1ad6c8c25df5b2ee59ae38156d62a9443fd4/crates/net/network/src/transactions/mod.rs#L998

We need to come up with a way to prune or bound this data structure, after investigating why this does not shrink.

**Comment by mattsse** [comment]
can close @Rjected ?

**Comment by Rjected** [comment]
yep, memory with this fix:
<img width="753" alt="Screenshot 2024-03-04 at 10 26 32 AM" src="https://github.com/paradigmxyz/reth/assets/6798349/78e5a017-2933-4252-871f-b4364b28d612">
