### ISSUE TITLE
Switch `net::LruCache` to not use `LinkedHashSet`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6836]
Right now the `LruCache` data structure uses a `LinkedHashSet`. This data structure is responsible for a large number of allocations. We don't strictly need to use this dependency, and there may be related memory leaks, re:
https://github.com/paradigmxyz/reth/issues/6765#issuecomment-1966558358

**Comment by PanGan21** [comment]
Hi @Rjected , what would you suggest to use instead of `LinkedHashSet ` ?

**Comment by mattsse** [comment]
essentially `schnellru::LruMap::new(ByLength::new(max_length))`

but there's one problem:

https://github.com/paradigmxyz/reth/blob/6725d43f053d3eba66c0a516af041c5018452bd9/crates/net/network/src/cache.rs#L39-L39

I don't think the api supports this, but we currently rely on this for some cleanup:

https://github.com/paradigmxyz/reth/blob/6725d43f053d3eba66c0a516af041c5018452bd9/crates/net/network/src/transactions/fetcher.rs#L407-L410

so unclear if we can easily do this

**Comment by AbnerZheng** [comment]
Will give it a try, since LruMap support `pop_oldest`,  which is the same as `LinkedHashSet::pop_front`
https://docs.rs/schnellru/latest/schnellru/struct.LruMap.html#method.pop_oldest

**Comment by mattsse** [comment]
this is unfortunately not equivalent because this forcefully pops

**Comment by AbnerZheng** [comment]
```rust
    /// Same as [`Self::insert`] but returns a tuple, where the second index is the evicted value,
    /// if one was evicted.
    pub fn insert_and_get_evicted(&mut self, entry: T) -> (bool, Option<T>) {
        if self.inner.insert(entry) {
            if self.limit.get() < self.inner.len() {
                // remove the oldest element in the set
                return (true, self.remove_lru())
            }
            return (true, None)
        }
        (false, None)
    }
   ```

**Comment by AbnerZheng** [comment]
We can create a LRUMap with len = limit + 1, then the code of `insert_and_get_evicted` would keep the same except replacing `LinkedHashSet::pop_front` with `LruMap::pop_oldest`.

**Comment by Rjected** [comment]
> We can create a LRUMap with len = limit + 1, then the code of `insert_and_get_evicted` would keep the same except replacing `LinkedHashSet::pop_front` with `LruMap::pop_oldest`.

this would impact the ordering though, right?

**Comment by AbnerZheng** [comment]
In my opinion, they are both following the same logic, remove the least recently used entry and return it.

**Comment by mattsse** [comment]
> remove the least recently used entry and return it.

but that's all it does, no _insert_, so this needs to be done manually, so I guess we need the wrapper type and implement insert_and_get_evicted manually

**Comment by AbnerZheng** [comment]
Ah, I got it. You want to find a LRU library that is able to support `insert_and_get_evicted` natively, even though the current implementation of `LRUCache` implemented the logic manually.

**Comment by 0xqd** [comment]
@Rjected I just go through the implementation of the LinkedHashSet and it's not optimal, and at the same time the way we use the unlimited memory for LRU can cause crash.

**Comment by onbjerg** [comment]
@0xJepsen can you type a short msg here so I can assign you?
