### ISSUE TITLE
Add Holesky, Sepolia,Base etc activation timestamps + block

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6848]
### Describe the feature

same as 

https://github.com/paradigmxyz/reth/blob/0f26cd6df32c5ed56ebacede56e2b05ccb63c32b/crates/ethereum-forks/src/hardfork.rs#L138-L138

but for other chains

**Comment by justcode740** [comment]
will take a look

**Comment by justcode740** [comment]
do i need to run each of the chain's node to get such info?

**Comment by mattsse** [comment]
you can get free rpc endpoints from https://chainlist.org/chain/8453 

I suggest you try cast find-block and then double check explorer, 
for those activated by block
