### ISSUE TITLE
Add add_trusted_peer command

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#686]
### Describe the feature

ref #672

Same as existing `add_peer` command

https://github.com/paradigmxyz/reth/blob/13441ff299b4766959b5439235dfed2071059c54/crates/net/network/src/network.rs#L138-L142

but for trusted nodes.

Internally the command that's sent to the manager should be extended with `PeerKind` so we can use the same command for adding peers and then handling it depending on the `kind`

cc @leruaa

**Comment by leruaa** [comment]
I can take this on, following the work I started on #685

**Comment by mattsse** [comment]
closed via #685
