### ISSUE TITLE
remove deposit variant from mocktransaction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6861]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/2aa5f5ddcd137b70bbfaa1f486f2d315c1e603f4/crates/transaction-pool/src/test_utils/mock.rs#L244-L246

Deposit txs aren't pooled:

https://github.com/paradigmxyz/reth/blob/2aa5f5ddcd137b70bbfaa1f486f2d315c1e603f4/crates/transaction-pool/src/validate/eth.rs#L148-L154

so we can remove this variant entirely because not needed

**Comment by peyha** [comment]
I can take this one

**Comment by mattsse** [comment]
nice, assigned

**Comment by justcode740** [comment]
will take a look

**Comment by peyha** [comment]
this issue can be closed thanks to #6931
