### ISSUE TITLE
SenderRecovery Stage can starve other jobs

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6888]
### Describe the feature

spawning recovery jobs onto the global pool can starve other tasks, like the engine server

> Feb 29 14:33:11.432 WARN Error whilst processing payload status  error: Api { error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out) }, service: exec

https://github.com/paradigmxyz/reth/blob/19ff1fb35c3d6031e368f5588269af6d66223d3a/crates/stages/src/stages/sender_recovery.rs#L90-L93

this can easily queue up more jobs than available cores, rayon pool is then fighting over resources with the tokio pools

we should pick a chunk size that leads to `spawned jobs < available cores` 

this should also reduce spawn related overhead

**Comment by Rjected** [comment]
Considering this done with https://github.com/paradigmxyz/reth/pull/7267 and https://github.com/paradigmxyz/reth/pull/7333
