### ISSUE TITLE
Enable `unused_crate_dependencies` rustc lint

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#6890]
### Describe the feature

Add `#![cfg_attr(not(test)), warn(unused_crate_dependencies)]` in all crates' lib.rs and remove unused dependencies.

Don't add if false positives are encountered.

cc @jsvisa

### Additional context

- https://github.com/paradigmxyz/reth/pull/6886#issuecomment-1971314947
- [`unused_crate_dependencies`](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unused-crate-dependencies)

**Comment by justcode740** [comment]
will take a look
