### ISSUE TITLE
Use safe math when calculating pool tx values

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6897]
### Describe the feature

This is applied on unvalidated txs:

https://github.com/paradigmxyz/reth/blob/74dc0e36d39ed46caca48666254e97c543e318a4/crates/transaction-pool/src/traits.rs#L920-L937

even though invalid transactions will get rejected

these ops can overflow

## TODO

use saturating math when calculating cost

saturating is fine because U256::MAX as cost will result in a rejected tx

**Comment by justcode740** [comment]
will take a look
