### ISSUE TITLE
`cargo test -p reth-revm --features optimism` could not compile normally

### ISSUE THREAD

**Issue by yjhmelody** [paradigmxyz/reth#6901]
### Describe the bug

`cargo test -p reth-revm --features optimism` could not compile normally

### Steps to reproduce

`cargo test -p reth-revm --features optimism`

### Node logs

```text
` crates/rpc/rpc-types-compat/src/transaction/mod.rs:78:29
    |
78  |     let access_list = match &mut signed_tx.transaction {
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^ pattern `&mut reth_primitives::Transaction::Deposit(_)` not covered
`
```

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

master

### What database version are you on?

none

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

none

### If you've built Reth from source, provide the full command you used

cargo test -p reth-revm --features optimism

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by DaniPopes** [comment]
We don't fully support --optimism on individual crates, especially tests due to circular dependencies. There aren't optimism specific tests in most crates anyway I believe.
