### ISSUE TITLE
Remove `feature = "optimism"` from `reth-optimism-payload-builder`

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#6906]
### Describe the feature

The feature doesn't make sense as the entire crate is only imported when building op-reth.

Remove `[features] optimism = []` and all `cfg` inside of the crate.

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/pull/5940
```

**Comment by mattsse** [comment]
I think this should be possible now

**Comment by AbnerZheng** [comment]
Could I give it a try?

**Comment by AbnerZheng** [comment]
I attempted to remove the `features=optimism` and create a PR, but it appears to be unsuccessful. In my PR, the `reth-optimism-payload-builder` is a workspace member and it require the activation of the `optimism` feature in `reth-primitives`. However, other crates require the `optimism` feature of `reth-primitives` to be deactivated when running `make lint`(no optimism enabled). This is incompatible with Cargo's feature resolution, which builds a dependency with the union of all features enabled by any package that depends on it.
https://doc.rust-lang.org/cargo/reference/features.html#feature-unification
