### ISSUE TITLE
Remove OP deposit tx variant from PooledTransactionElement

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6915]
### Describe the feature

The `PooledTransactionElement` type represents txs that can be sent over p2p

https://github.com/paradigmxyz/reth/blob/8ea032adad8600b28dbc6041f39c3dc97952db2a/crates/primitives/src/transaction/pooled.rs#L18-L22

This is not the case for the OP deposit variant:

https://github.com/paradigmxyz/reth/blob/8ea032adad8600b28dbc6041f39c3dc97952db2a/crates/primitives/src/transaction/pooled.rs#L52-L61

hence it can be safely removed

## TODO

remove deposit variant

This from conversion is no longer possible and must be replaced with a TryFrom

https://github.com/paradigmxyz/reth/blob/8ea032adad8600b28dbc6041f39c3dc97952db2a/crates/primitives/src/transaction/pooled.rs#L541-L541

This has implications on:

https://github.com/paradigmxyz/reth/blob/8ea032adad8600b28dbc6041f39c3dc97952db2a/crates/transaction-pool/src/traits.rs#L918-L918

and this trait:

https://github.com/paradigmxyz/reth/blob/8ea032adad8600b28dbc6041f39c3dc97952db2a/crates/primitives/src/transaction/mod.rs#L1552-L1555

which should be a TryFrom instead

**Comment by justcode740** [comment]
will take a look

**Comment by mattsse** [comment]
nice, this may require a few other changes if we change the trait to tryfrom, so if you're stuck please open a pr and we can figure out a solution

**Comment by justcode740** [comment]
will take a look

**Comment by justcode740** [comment]
> nice, this may require a few other changes if we change the trait to tryfrom, so if you're stuck please open a pr and we can figure out a solution

emm, i don't really find this issue any tricky or could get me stuck it feels quite mechanical, i prob haven't thought enough on all touched runtime logic but checked on two thing u mentioned above and didn't really think there's anything need to be changed on those..except https://github.com/paradigmxyz/reth/commit/b6dca63010b72799482ce006369a2d9e9a76e127 seem left some todos relevant with deposit tx.
