### ISSUE TITLE
Don't fetch txns that are pending pool import

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6930]
### Describe the feature

Announcements should be filtered w.r.t to `transactions_by_peers` which maps all transactions that are currently pending import to pool in context of `TransactionsManager`.

https://github.com/paradigmxyz/reth/blob/a79db0f83989865eb51be4444bafdef9684d7b6c/crates/net/network/src/transactions/mod.rs#L224-L228

This should be done as second step here.

https://github.com/paradigmxyz/reth/blob/a79db0f83989865eb51be4444bafdef9684d7b6c/crates/net/network/src/transactions/mod.rs#L693

**Comment by justcode740** [comment]
will take a look

**Comment by emhane** [comment]
> will take a look

already have a fix for this @justcode740, wanted to observe it on mainnet asap
