### ISSUE TITLE
Make it possible to store static files outside of the datadir

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#6945]
### Describe the feature

Currently, we derive the path for static files purely from the node-wide datadir https://github.com/paradigmxyz/reth/blob/b75862010aca90faee8687d969aa10b4076cb947/crates/node-core/src/dirs.rs#L285-L288

Instead, we should be able to pass a separate argument `--datadir.static-files` that overrides the static files path and defaults to the previous behavior inside the `datadir`.

**Comment by justcode740** [comment]
will take a look

**Comment by justcode740** [comment]
will take a look

**Comment by joshieDo** [comment]
I'd keep the main directory as is, but add a secondary directory which `fn iter_static_files` would look into. This would allow the secondary directory be the mount, while the main directory can have the files under construction

**Comment by justcode740** [comment]
if we keep as it is, would all the writes still write to main directory, so just change iter_static_files would allow all reading to read from iter_static_files while writes etc still happen under main directory? would that lead to any conflicts? 

what're some example static files and how they used throughout the program?

**Comment by shekhirin** [comment]
> I'd keep the main directory as is, but add a secondary directory which `fn iter_static_files` would look into. This would allow the secondary directory be the mount, while the main directory can have the files under construction

unsure, what's the motivation for this? I imagine there are people who want to have all (including unfinished) static files to be on a separate drive. Given that our block interval is 500k, it's quite a lot of disk space to occupy until the file is finished and moved to the permanent location. Also, unwinds can still change the finished files, it seems to complicate the logic quite a bit.

**Comment by joshieDo** [comment]
> what's the motivation for this?

I personally, see at least two situations.

* Main directory can be my fast disk where I build the next static file range. Eventually I'll move finished files to my slow disk (on my own). I may not want my slow disk slowing the `StaticFileProducer` hook.
* My secondary directory can be a `read-only` mount which i mount in different machines for whatever purpose. 

> I imagine there are people who want to have all (including unfinished) static files to be on a separate drive.
Sure, but even now, someone more savvy could accomplish this and mount a drive directly on `datadir/static_file`

> Also, unwinds can still change the finished files, it seems to complicate the logic quite a bit.
I wouldn't add moving logic (from main to secondary directory) to this PR tbh.

> Also, unwinds can still change the finished files, 
 Yes, but it's not that straightforward. As far as I can see it can only happen in two specific scenarios:
 * in the initial sync if something goes wrong during the pipeline (bug)
 * on a pipeline trigger after a restart, and only if the blocks that were copied from mdbx (pre pipeline) were re-orged and it actually had copied it into a finished file.

If at any time during a live sync I stop the node, I think we can assume that any finished file is truly finished.

**Comment by joshieDo** [comment]
> if we keep as it is, would all the writes still write to main directory, so just change iter_static_files would allow all reading to read from iter_static_files while writes etc still happen under main directory? would that lead to any conflicts?

It shouldn't

> what're some example static files and how they used throughout the program?

`StaticFileProducer` <- writes
`StaticFileProvider` <- manages all static files (for reading and writing)
`iter_static_files`

**Comment by joshieDo** [comment]
i expressed myself badly, i'd still let the main directory to be overriden (as long as its `read-write`), but i'd like a secondary location that can support read-only drives

**Comment by justcode740** [comment]
so wonder 

> > if we keep as it is, would all the writes still write to main directory, so just change iter_static_files would allow all reading to read from iter_static_files while writes etc still happen under main directory? would that lead to any conflicts?
> 
> It shouldn't
> 
> > what're some example static files and how they used throughout the program?
> 
> `StaticFileProducer` <- writes `StaticFileProvider` <- manages all static files (for reading and writing) `iter_static_files` <- detects static file ranges

i would prob need to read more on how static files are used, guess my question is how frequent (if any) that a written static files gonna be read later? do we need to check state diff every read to ensure strong consistency between main and secondary directory? (assume there's separate process to sync from main directory all static files to read-only directory every X seconds).

**Comment by yorickdowne** [comment]
This feature would it trivial to support this in Eth Docker. OS level mounts can be made to / hacked to work with Docker containers, but doing it in an automated fashion for the user that works both for users who want an `ANCIENT_DIR` and those who don't, that requires a `--` parameter to point to a location in the filesystem.

**Comment by gakonst** [comment]
What's an example of how this is done in other tools? i.e. what'd your ideal UX be in Eth Docker?

**Comment by yorickdowne** [comment]
My ideal UX is the one I have now for Geth:

- User sets `ANCIENT_DIR` in `.env` to a file system path or leaves it blank
- If it's set, my `compose.yml` maps it into a location in the container, say `/var/lib/ancient`
- If it's set, my `docker-entrypoint.sh` calls the client with `--datadir.ancient /var/lib/ancient`, or whatever the parameter is

From a user perspective, they create a directory, chown it to 10001, and reference it in `.env` and that's it

**Comment by cfc-ctf** [comment]
From the perspective of running reth as a service (rather than manually
starting reth), flags are always safer (and more explicit) than env
variables, so I applaud the introduction of --datadir.ancient as a reth
starting/config.toml flag.

Thanks!

**Comment by gakonst** [comment]
It should be `--datadir.static-files` but yes. Both!
