### ISSUE TITLE
Move eth-wire types to a standalone crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6959]
### Describe the feature

currently reth-interfaces is pretty big and depends on things like:

https://github.com/paradigmxyz/reth/blob/53e67c2b99c0dba0b9636c1e94d3184661257b50/crates/interfaces/Cargo.toml#L18-L19

I think we can solve this by separating the wire types from the implementation by moving them to their own crate: eth-wire-types

### Additional context

This is currently blocked until audit concluded

_No response_

**Comment by 0xJepsen** [comment]
I can do this when the audit finishes. What is it's timeline?

**Comment by mattsse** [comment]
will ping, perhaps 2weeks

**Comment by JackG-eth** [comment]
Will take if available.

**Comment by emhane** [comment]
isn't this debt rather than enhancement?
