### ISSUE TITLE
--nat=extIp is not respected when querying the enode via admin_nodeInfo

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6961]
### Describe the feature

this is most likely a bug where the local node record is not updated correctly

https://github.com/paradigmxyz/reth/blob/ebe72f7ae85f690ed3b64abd1986752b45e8cdd3/crates/net/network/src/network.rs#L223-L223

because there are different mutexes:

https://github.com/paradigmxyz/reth/blob/ebe72f7ae85f690ed3b64abd1986752b45e8cdd3/crates/net/discv4/src/lib.rs#L606-L617

one in discv4 and one in network

Since discovery is optional, we can fix this in a few ways, the simplest solution would be to give the NetworkInner type an Option of `Discv4` so we can use

https://github.com/paradigmxyz/reth/blob/ebe72f7ae85f690ed3b64abd1986752b45e8cdd3/crates/net/discv4/src/lib.rs#L255-L265

in:

https://github.com/paradigmxyz/reth/blob/ebe72f7ae85f690ed3b64abd1986752b45e8cdd3/crates/net/network/src/network.rs#L221-L221

**Comment by mattsse** [comment]
fyi @abhijeetbhagat 

perhaps you're interested in this one

**Comment by justcode740** [comment]
will take a look

**Comment by estensen** [comment]
I'd like to work on this
