### ISSUE TITLE
Use pipeline for `reth stage unwind`

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#6965]
## Problem

Currently, `reth stage unwind` relies on the `DatabaseProvider` for deleting the data data from the database https://github.com/paradigmxyz/reth/blob/1214f2df012b82d7296755d3baa675085450c5c8/bin/reth/src/commands/stage/unwind.rs#L71-L78

It's not ideal for two reasons:
1. It doesn't work with static files anymore. Static files can only be unwound using the pipeline stages, but `take_block_and_execution_range` works purely on the database.
2. `take_block_and_execution_range` is needed only for the blockchain tree (and this CLI), and adding the static files unwind logic there doesn't make a lot of sense.

## Solution

Invoke pipeline unwind in `reth stage unwind`.

**Comment by PanGan21** [comment]
Hi @shekhirin could I give it a try?
