### ISSUE TITLE
Simplify fill_tx_env trait function

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6979]
### Describe the feature

currently we require a meta input type:

https://github.com/paradigmxyz/reth/blob/176ce4f9630c316138c711b9e0c39af968e38f6e/crates/node-api/src/evm/traits.rs#L29-L39

This should be unnecessary if we instead either require:

`T: AsRef<TransactionSignedEcRecovred>`

or another solution that allows us to use encode_envelope for OP transactions

https://github.com/paradigmxyz/reth/blob/176ce4f9630c316138c711b9e0c39af968e38f6e/crates/revm/src/processor.rs#L247-L261

we could think of a different approach where we change the input and do something like:

```rust
type TxInput<'a> where Self: 'a; // requires gat

fn fill_tx_env<'a, T>(tx_env: &mut TxEnv, input: T)
    where
        T: Into<TxInput<'a>;

enum EthTxInput<'a> {
  EcRecovered(Cow<'a, TransactionSignedEcRecovered>),
  WithAddress(Cow<'a,Transaction>, Address)
}

```

This needs some tinkering

cc @Rjected @fgimenez

**Comment by JackG-eth** [comment]
Hi, I'd like to pick this up, although I might need some more info as its my first issue :)

**Comment by mattsse** [comment]
this might actually need more research first before I know exactly what to do here...

if you don't find any other good first issue, please reach out on tg @mattsse and we'll figure something out
