### ISSUE TITLE
Convert `FromRecoveredTransaction` into `TryFromRecoveredTransaction`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6983]
### Describe the feature

This fallible trait is unsound with eip4844 and deposit transactions

https://github.com/paradigmxyz/reth/blob/6725d43f053d3eba66c0a516af041c5018452bd9/crates/primitives/src/transaction/mod.rs#L1552-L1552

This matters here:

https://github.com/paradigmxyz/reth/blob/6725d43f053d3eba66c0a516af041c5018452bd9/crates/transaction-pool/src/traits.rs#L1127-L1130

with one caveat that eip4844 transaction are support here by marking the blob as missing:

https://github.com/paradigmxyz/reth/blob/6725d43f053d3eba66c0a516af041c5018452bd9/crates/transaction-pool/src/traits.rs#L934-L934

## TODO
change the trait to `TryFromRecoveredTransaction` basically the same as `TryFrom` crate with an error type that is an associated type. for the impls we can use

https://github.com/paradigmxyz/reth/blob/6725d43f053d3eba66c0a516af041c5018452bd9/crates/primitives/src/transaction/error.rs#L56-L59

**Comment by gr4yha7** [comment]
@mattsse may I?

**Comment by mattsse** [comment]
assgined

**Comment by mattsse** [comment]
@gr4yha7 just checking in, do you have the bandwidth to work on this?

**Comment by gr4yha7** [comment]
> @gr4yha7 just checking in, do you have the bandwidth to work on this?

@mattsse I've been unfortunately tied up these past couple of days. Probably best I'm unassigned? ☹️

**Comment by estensen** [comment]
I would be happy to take over
