### ISSUE TITLE
Always accept incoming connections from trusted peers

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7001]
### Describe the feature

currently we're always rejecting incoming connections if we're at capacity

https://github.com/paradigmxyz/reth/blob/e42fb32c7fb6fc570b043686622e82dfaedd7005/crates/net/network/src/peers/manager.rs#L226-L228

this makes it impossible to accept connections from trusted peers

the problem is that we only get the peer id after negotiating the rlpx session

so we can't directly disconnect these connections as long as the ip is not banned:

https://github.com/paradigmxyz/reth/blob/e42fb32c7fb6fc570b043686622e82dfaedd7005/crates/net/network/src/swarm.rs#L198-L201

https://github.com/paradigmxyz/reth/blob/e42fb32c7fb6fc570b043686622e82dfaedd7005/crates/net/network/src/session/mod.rs#L313-L318

instead we need to establish them and then apply the capacity check here, if the peer is not trusted:

https://github.com/paradigmxyz/reth/blob/e42fb32c7fb6fc570b043686622e82dfaedd7005/crates/net/network/src/peers/manager.rs#L269-L269

the expected behaviour should mimic:

https://github.com/ethereum/go-ethereum/blob/b590cae89232299d54aac8aada88c66d00c5b34c/p2p/server.go#L817-L829

## TODO
* only immediately disconnect on incoming if IP is banned
* apply capacity/trusted check on_incoming_session_established

**Comment by freezlite** [comment]
I think in this change port should not be checked because incoming port can be different every time.

For example geth allows to add trusted enodes without IP and Port. But reth requires both.

**Comment by mattsse** [comment]
> For example geth allows to add trusted enodes without IP and Port. But reth requires both.

do you mean via rpc or config?

only checked briefly but unsure where we check the port

**Comment by freezlite** [comment]
> do you mean via rpc or config?

Yes, I tried rpc. At least there empty or 0 port is rejected. I'm fine to put not real one, important just not check the port(and maybe ip) on incoming connection. Probably just public key.

**Comment by mattsse** [comment]
gotcha, this is a separate issue then, will track this separately:

https://github.com/paradigmxyz/reth/issues/7003

**Comment by AbnerZheng** [comment]
Will try it since it is related to https://github.com/paradigmxyz/reth/issues/7003
