### ISSUE TITLE
e2e testsuite and testing support for convenient test setups

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7002]
### Describe the feature

with https://github.com/paradigmxyz/reth/pull/6972 we have now a crate for e2e testing support

we can iterate on this and extend the functionality

ideally we have a bunch of test helper types that:
* inject some state into the chain, this can be done via engine api or perhaps directly into the DB before launching
* run some tests against it

ref for inspiration:

https://github.com/ethereum/hive/blob/master/simulators/ethereum/rpc-compat/main.go#L29-L29

see also .rlp files

fyi @loocapro

**Comment by loocapro** [comment]
May I take this?
