### ISSUE TITLE
Rename `TxType` variants to UpperCamelCase (PascalCase)

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#7006]
### Describe the feature

Enum variants are UpperCamelCase in Rust. Acronyms count as one word.

### Additional context

- [Naming - Rust API Guidelines](https://rust-lang.github.io/api-guidelines/naming.html)
> In UpperCamelCase, acronyms and contractions of compound words count as one word: use Uuid rather than UUID, Usize rather than USize or Stdin rather than StdIn

**Comment by AbnerZheng** [comment]
Will give it a try.
