### ISSUE TITLE
Flaky tests in stages

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#7007]
### Describe the feature

<img width="741" alt="Screenshot 2024-03-06 at 16 43 53" src="https://github.com/paradigmxyz/reth/assets/58548332/abbbbf96-eb17-4904-b419-e9ee3630774c">

https://github.com/paradigmxyz/reth/actions/runs/8173266629/job/22345368736

last commit to files of with these tests in was 20 hours ago @shekhirin https://github.com/paradigmxyz/reth/pull/6973

**Comment by DaniPopes** [comment]
cc https://github.com/paradigmxyz/reth/pull/6987
