### ISSUE TITLE
Clean up DB methods in stages

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#702]
Go through the DB interactions in stages and clean up repeating/redundant methods where possible by adding methods to `Transaction`.

Some examples of code to clean up:
https://github.com/paradigmxyz/reth/blob/93b6ce597ad192e6ee6b7ef60fdaa030d0a16a51/crates/stages/src/stages/total_difficulty.rs#L67-L69
https://github.com/paradigmxyz/reth/blob/eb600d1f029da7381bd7f5f69a75aeafb9a54247/crates/stages/src/stages/execution.rs#L107-L111

**Comment by MegaRedHand** [comment]
I'd like to take this on. Was thinking of turning:
```rust
let mut header_hashes_cursor = tx.cursor::<tables::CanonicalHeaders>()?;
let walker = canonicals 
    .walk(start_block)? 
    .take_while(|entry| entry.as_ref().map(|e| e.0 <= end_block).unwrap_or_default())?;
```
into:
```rust
let walker = tx.walk_range::<tables::CanonicalHeaders>(start_block, end_block)?;
```
wdyt?
