### ISSUE TITLE
For `ForkCondition::Timestamp(0)/ForkCondition::Block(0)`, should they be semantically strictly equivalent in implementation?

### ISSUE THREAD

**Issue by yjhmelody** [paradigmxyz/reth#7027]
### Describe the feature

I found some new harkforks activated by timestamp, but others activated by block number.
Many new hardfork checks are only for timestamp, but if it's activated in genesis block, the checking seems return false.
Should we transfer `ForkCondition::Block(0)` to `ForkCondition::Timestamp(0)` when init chain spec?
 
### Additional context

Like shanghai/cancun harkfork.

**Comment by yjhmelody** [comment]
For shanghai hardfork, now all use function `is_shanghai_active_at_timestamp` to check.
But for a new chain of chain spec, it should be supported to set `(Hardfork::Shanghai, ForkCondition::Block(0))`, but `is_shanghai_active_at_timestamp` always return false.

**Comment by mattsse** [comment]
shanghai is activated by timestamp, all post merge hardforks are

**Comment by yjhmelody** [comment]
Ok, maybe should align RFC.
