### ISSUE TITLE
Op-reth sync failure Base mainnet with Magi and checkpoints

### ISSUE THREAD

**Issue by CRossel87a** [paradigmxyz/reth#7028]
### Describe the bug

Bad block during start of stage 4 / 13:

2024-03-07T09:12:44.034299Z  INFO Status connected_peers=2 freelist=15 stage=SenderRecovery checkpoint=0 target=11501544 stage_progress=None
2024-03-07T09:12:51.177201Z ERROR Stage encountered a validation error: transaction signer recovery error stage=SenderRecovery bad_block=1

Then unwinding starts:
2024-03-07T09:18:34.033730Z  INFO Status connected_peers=2 freelist=15 stage=SenderRecovery checkpoint=0 target=11501544 stage_progress=None
2024-03-07T09:18:48.637900Z  INFO Unwinding{stage=Bodies}: Stage unwound stage=Bodies unwind_to=0 progress=0 done=true
2024-03-07T09:18:48.921865Z  INFO Unwinding{stage=TotalDifficulty}: Stage unwound stage=TotalDifficulty unwind_to=0 progress=11401543 done=false
2024-03-07T09:18:49.045141Z  INFO Unwinding{stage=TotalDifficulty}: Stage unwound stage=TotalDifficulty unwind_to=0 progress=11301542 done=false

Completes:

2024-03-07T09:19:01.981552Z  INFO Unwinding{stage=TotalDifficulty}: Stage unwound stage=TotalDifficulty unwind_to=0 progress=1429 done=false
2024-03-07T09:19:01.984493Z  INFO Unwinding{stage=TotalDifficulty}: Stage unwound stage=TotalDifficulty unwind_to=0 progress=0 done=true

Then bad block and full stop:

2024-03-07T09:23:44.826990Z  INFO Unwinding{stage=Headers}: Stage unwound stage=Headers unwind_to=0 progress=0 done=true
2024-03-07T09:23:44.929791Z  WARN Bad block detected in unwind invalid_hash=0x07eee59d552f482e0f350933b8e96f824aa0bfa28267de53dcb0ddbe868a4bf9 invalid_number=1
2024-03-07T09:23:44.929840Z  WARN Bad block with hash hash=0x07eee59d552f482e0f350933b8e96f824aa0bfa28267de53dcb0ddbe868a4bf9 header=Header { parent_hash: 0xf712aa9241cc24369b143cf6dce85f0902a9731e70
d66818a3a5845b296c73dd, ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, beneficiary: 0x4200000000000000000000000000000000000011, state_root: 0xe3e10cb3963f6b88b7ba14c
c76c34de65308fc0524dca48410ee53df2a43700b, transactions_root: 0xee45a6283d626ebed087ac705c71740d7ecb276d81b745284a68b88925dc91ae, receipts_root: 0x637d9e6847368bb52b56e90dd608facc34122c153872e8733cb0
b01caa581f85, withdrawals_root: None, logs_bloom: 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, difficulty: 0x0_U256, number: 1
, gas_limit: 30000000, gas_used: 64013, timestamp: 1686789349, mix_hash: 0xae36673a68b9370a513a06698115fd86cc7faf4d6c248a982fbc3ae29c442da2, nonce: 0, base_fee_per_gas: Some(980000000), blob_gas_used
: None, excess_blob_gas: None, parent_beacon_block_root: None, extra_data: 0x }

### Steps to reproduce

Run commands:

op-reth -vvv node --chain base --rollup.sequencer-http https://sequencer.base.org --http --http.port 43433 --ws --ws.port 43434 --port 50303 --full --authrpc.port 8551 --authrpc.jwtsecret /root/base/jwt.hex --datadir /root/.basedata2/ --builder.deadline 999999 

Protip: Merkle has a free eth RPC
magi --network base --jwt-file /root/base/jwt.hex --l1-rpc-url https://eth.merkle.io --l2-engine-url http://0.0.0.0:8551 --l2-rpc-url https://mainnet.base.org --rpc-port 19545 --rpc-addr 127.0.0.1 --sync-mode checkpoint --checkpoint-sync-url https://mainnet.base.org

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.20

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by CRossel87a** [comment]
Same error with latest commit

**Comment by CRossel87a** [comment]
The hashes seem to match up perfectly with mainnet, so the block is correct

conn.eth.get_block(1)
Out[211]: 
AttributeDict({'baseFeePerGas': 980000000,
 'difficulty': 0,
 'extraData': HexBytes('0x'),
 'gasLimit': 30000000,
 'gasUsed': 64013,
 'hash': HexBytes('0x07eee59d552f482e0f350933b8e96f824aa0bfa28267de53dcb0ddbe868a4bf9'),
 'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'),
 'miner': '0x4200000000000000000000000000000000000011',
 'mixHash': HexBytes('0xae36673a68b9370a513a06698115fd86cc7faf4d6c248a982fbc3ae29c442da2'),
 'nonce': HexBytes('0x0000000000000000'),
 'number': 1,
 'parentHash': HexBytes('0xf712aa9241cc24369b143cf6dce85f0902a9731e70d66818a3a5845b296c73dd'),
 'receiptsRoot': HexBytes('0x637d9e6847368bb52b56e90dd608facc34122c153872e8733cb0b01caa581f85'),
 'sha3Uncles': HexBytes('0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'),
 'size': 870,
 'stateRoot': HexBytes('0xe3e10cb3963f6b88b7ba14cc76c34de65308fc0524dca48410ee53df2a43700b'),
 'timestamp': 1686789349,
 'totalDifficulty': 0,
 'transactions': [HexBytes('0x68736fb400dc3b69ab1c4c2cbe75a600aa7ba7cd8d025797ebd8a0108955c91f')],
 'transactionsRoot': HexBytes('0xee45a6283d626ebed087ac705c71740d7ecb276d81b745284a68b88925dc91ae'),
 'uncles': []})

**Comment by emhane** [comment]
did you try out temp solutions proposed by users in https://github.com/paradigmxyz/reth/issues/7500 and did this solve your issue @CRossel87a?

**Comment by gakonst** [comment]
Hi what's the state of this @CRossel87a? Are you on latest commit / beta?

**Comment by CRossel87a** [comment]
> Hi what's the state of this @CRossel87a? Are you on latest commit / beta?

Hi,

I am not tracking this issue anymore - could not get it working back then. Will close the issue
