### ISSUE TITLE
reth doesn't respect `--trusted-only` flag

### ISSUE THREAD

**Issue by geomad** [paradigmxyz/reth#7036]
### Describe the bug

I'm running eth with the below args:
```
--trusted-only \
--datadir /chain/reth2 \
--port 30305 \
--http.corsdomain * \
--http \
--http.addr 192.168.1.2 \
--http.port 8751 \
--http.api debug,eth,net,trace,txpool,web3,rpc,reth,ots,admin \
--ws \
--ws.addr 192.168.1.2 \
--ws.port 8750 \
--ws.api debug,eth,net,trace,txpool,web3,rpc,reth,ots \
--ws.origins * \
--authrpc.port 8554 \
--authrpc.jwtsecret /etc/ethereum/jwt.hex \
--discovery.port 30305 \
--rpc-gas-cap 30500000 \
--trusted-peers enode://<redacted>@127.0.0.1:30304
```

however the logs report 24 peers
```
2024-03-07T20:35:18.343688Z  INFO Status connected_peers=24 freelist=13 stage=Bodies checkpoint=6261000 target=19385478 stage_progress=32.29%
```

### Steps to reproduce

Run with `--trusted-only` argument, and a trusted node in `--trusted-peers`

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.2.0-beta.1 Commit SHA: 91c7dd04b

### What database version are you on?

2

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by jsvisa** [comment]
IHMO, should also respect the incoming peers, such as one runs his node with an expansive outbound network price, he doesn't want to serve anyone unknown to connect to his node, so with this arg enabled can fix his issue.

**Comment by mattsse** [comment]
That makes perfect sense
