### ISSUE TITLE
Pending tx stopping randomly

### ISSUE THREAD

**Issue by 0xSha5** [paradigmxyz/reth#7042]
### Describe the bug

It looks like the full node compiled with maxperf/release profile stops receiving pending transactions from time to time for at least a few seconds, sometimes minutes and then starts receiving them again. 
It seems the number of txs in the queue is always very close to 20000 when this occurs with default pool config, and most of the time it is exactly 20000, which appears to be an unexpected number as the max should be 10000. I'm unsure if it is related though as if you launch the node with `--txpool.queued_max_count 0` it doesnt appear instantly. 
The node remains sync all along.

The following 2 pics to illustrate:
![c](https://github.com/paradigmxyz/reth/assets/126895034/e91b4e80-e476-40a2-ab32-0c7db267600c)
![b](https://github.com/paradigmxyz/reth/assets/126895034/5ec7648f-4552-4e15-b299-c48431c7b84f)

### 1. Start by running a full node:

> RUST_LOG=info ./reth node --full --ws --ws.api=all

### 2. Listens on pending txs and display them, for instance if using ethers.rs:
```
use ethers::prelude::*;

const URL: &str = "ws://127.0.0.1:8546";

#[tokio::main]
async fn main() -> eyre::Result<()> {
    let subscriber = tracing_subscriber::fmt().compact().finish();
    tracing::subscriber::set_global_default(subscriber).unwrap();

    let provider = Provider::<Ws>::connect(URL).await?;
    let mut stream = provider.subscribe_pending_txs().await?;
    while let Some(tx) = stream.next().await {
        let tx_hash = format!("{:?}", tx);
        tracing::info!(%tx_hash);
    }
    Ok(())
}
```

### 3. Wait
This will take some time

### Platform(s)

Linux (ARM)

### What version/commit are you on?

latest alpha version - 0.1.0-alpha.21

### What database version are you on?

1

### What type of node are you running?

Full via --full flag

### If you've built Reth from source, provide the full command you used

cargo build --profile maxperf OR cargo build --release

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by ry-zan** [comment]
I'm also experiencing this issue right now on multiple reth nodes w/ version alpha.22. Pending tx streaming over Ipc using ethers-rs will eventually stop (and not start up again until reth node is restarted). Streaming new blocks continues without a problem. Tried both subscribe_pending_txs() and subscribe_full_pending_txs(). Noticed the issue also on previous versions > alpha.15 or so (but not on any versions before that).

**Comment by fullportshove** [comment]
issue is fixed for me upon upgrading to beta versions .3 and .4
