### ISSUE TITLE
Deduplicate primitive types and use alloy's existing types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7050]
### Describe the feature

ref https://github.com/alloy-rs/alloy/issues/255

ref #5746 

currently all codec traits are implemented in reth-primitives via derive macros, therefor we're duplicating types that already exists in alloy:

https://github.com/paradigmxyz/reth/blob/9569692d474f7e6c7d4a843e8fe897848a9ba4fa/crates/primitives/src/transaction/access_list.rs#L43-L46

https://github.com/paradigmxyz/reth/blob/9569692d474f7e6c7d4a843e8fe897848a9ba4fa/crates/primitives/src/withdrawal.rs#L9-L12

https://github.com/paradigmxyz/reth/blob/9569692d474f7e6c7d4a843e8fe897848a9ba4fa/crates/primitives/src/log.rs#L6-L9

In order to replace them, we need to impl all the codecs for alloy types.
This can be done in two ways:
1. impl codecs in alloy directly
2. impl codecs in reth's codec crate https://github.com/paradigmxyz/reth/blob/9569692d474f7e6c7d4a843e8fe897848a9ba4fa/crates/storage/codecs/Cargo.toml#L2-L2

since codecs are a reth thing, we could pursue option 2. 
This however, would require implementing codecs manually, because derive is not possible
we could also spin out codecs which is just the Compact trait to it's standalone repo and make it a feature in alloy (option 1.)

https://github.com/paradigmxyz/reth/blob/9569692d474f7e6c7d4a843e8fe897848a9ba4fa/crates/storage/codecs/src/lib.rs#L36-L36

wdyt @DaniPopes

**Comment by gakonst** [comment]
I'm open to either. I do think the Compact eth specific encoding is valuable (optimal / zero cost?) so if it's worth pulling out of reth we should do that.

**Comment by mattsse** [comment]
this should be integrated in the codecs crate for alloy-eips types
then replacing the duplicated reth-primitive types with alloy-eips

**Comment by 0xqd** [comment]
regarding the `reth_codecs` where should we spin it to a standalone one, maybe we create something like `alloy/codecs`, we need it to avoid circular deps while moving code around. Can you create the repo? @mattsse

**Comment by mattsse** [comment]
these should be implemented where the Compact trait is defined, we discarded the other option.

**Comment by 0xqd** [comment]
oh I see, this is definitely easier to implement. I thought we wanted to move the whole `Compact` to alloy, it's clear now.

**Comment by mattsse** [comment]
great!

I think we can move the impls in a new alloy.rs file here

https://github.com/paradigmxyz/reth/blob/57e25be058d041907840f81feb2e82a1aade6714/crates/storage/codecs/src/lib.rs#L18-L18

**Comment by 0xqd** [comment]
I will continue with Withdrawal, and AccessList then we can replace them in next PRs.

**Comment by mattsse** [comment]
cool! ty

separately, we can now replace the reth_primitive::Log type in a separate pr

**Comment by 0xqd** [comment]
Thanks @mattsse for replacing duplicate Withdrawl part, I was a bit busy.
