### ISSUE TITLE
Prevent banning trusted peers for a long time

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7056]
### Describe the feature

ref #7052

with #7052 we provided a bit more leeway when penalizing misbehaving trusted peers, but we would still endup banning them, which basically puts them into a timeout for:

https://github.com/paradigmxyz/reth/blob/54449917b1dc31e996bbcf5dfbb0dc169eed18b8/crates/net/network/src/peers/manager.rs#L1217-L1218

## TODO
* ban misbehaving trusted peers for shorter durations:

https://github.com/paradigmxyz/reth/blob/54449917b1dc31e996bbcf5dfbb0dc169eed18b8/crates/net/network/src/peers/manager.rs#L299-L301

we should use the default uban interval here so trusted peers get unbanned with the next interval

**Comment by int88** [comment]
I'd like to fix it
