### ISSUE TITLE
Add TransactionManager Metrics type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#706]
### Describe the feature

Same as https://github.com/paradigmxyz/reth/issues/684

but a metrics type for the `Transactionmanager`, which should include

* propagated transactions
* ...?

**Comment by Kuly14** [comment]
Would love to help out with this.

**Comment by mattsse** [comment]
awesome!

**Comment by Kuly14** [comment]
Hi, @mattsse I finished the changes, but I cannot push them to a new branch. I'm getting a permission denied error:

```
ERROR: Permission to paradigmxyz/reth.git denied to Kuly14.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Is there some problem on my end, or do you need to grant me some permissions? Thanks a lot!

**Comment by mattsse** [comment]
did you fork it?

https://github.com/Kuly14/reth does not exist yet

try:
1. fork
2. push to fork
3. open PR

**Comment by Kuly14** [comment]
Oh, of course. Damn, I'm used to just being able to create branches willy-nilly. Thanks for the advice!
