### ISSUE TITLE
Add more helper functions to PooledTransactionElement

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7097]
### Describe the feature

see also:

https://github.com/paradigmxyz/reth/blob/8c4d74fdae5a3585398dc211b3e707daef287b72/crates/primitives/src/transaction/mod.rs#L548-L584

https://github.com/paradigmxyz/reth/blob/8c4d74fdae5a3585398dc211b3e707daef287b72/crates/primitives/src/transaction/mod.rs#L331-L331

https://github.com/paradigmxyz/reth/blob/8c4d74fdae5a3585398dc211b3e707daef287b72/crates/primitives/src/transaction/mod.rs#L317-L317

https://github.com/paradigmxyz/reth/blob/8c4d74fdae5a3585398dc211b3e707daef287b72/crates/primitives/src/transaction/mod.rs#L285-L285

https://github.com/paradigmxyz/reth/blob/8c4d74fdae5a3585398dc211b3e707daef287b72/crates/primitives/src/transaction/mod.rs#L268-L268

and more...

**Comment by int88** [comment]
I'd like to take it :)
