### ISSUE TITLE
Extend fork activation blocks data

### ISSUE THREAD

**Issue by klkvr** [paradigmxyz/reth#7098]
### Describe the feature

Extend https://github.com/paradigmxyz/reth/blob/main/crates/ethereum-forks/src/hardfork.rs with fork activation block numbers data for more chains.

This data is non-trivial to obtain, so comments/links to lists of hardfork->block mappings are appreciated as well even if you have no plans for creating a PR with those.

Especially useful would be data for Arbitrum and any other chains enabling Shanghai/Cancun support in the near future.

**Comment by mattsse** [comment]
arbitrum would be great

**Comment by altugbakan** [comment]
So, I’ve started doing some research. Are Arbitrum One and its testnet sufficient, or should we consider Arbitrum Nova and others?

**Comment by mattsse** [comment]
happy to accept all :)

up to you how much you'd like to do, but one+testnet would be sufficient

**Comment by altugbakan** [comment]
Quick update: I've found the corresponding upgrades (ArbOS 11 for Shangai, ArbOS 20 Atlas for Cancun), but I could not find the actual blocks where the upgrade has happened. They have the update information [here](https://docs.arbitrum.foundation/network-upgrades#network-activation-statuses), but there is no information on the block number, just the date. I'm continuing my research, but if there are any tips you would like to give, I'm open to them.

**Comment by mattsse** [comment]
you can try `cast find-block <timestamp>` to find the block that corresponds to a timestamp

**Comment by gakonst** [comment]
We don't support Arbitrum yet so not sure we should include this?

**Comment by klkvr** [comment]
We've discussed this in context of this being useful as a separate crate which we could also pull in as a foundry dep to address https://github.com/foundry-rs/foundry/issues/6228#issuecomment-1812843644 by determining spec for forked env.

Agreed that it'd be confusing to have arbitrum feature flag in any of Reth packages at this point

@mattsse wdyt?

**Comment by mvares** [comment]
@mattsse think you should close this issue... (it's still in reth tracker)
