### ISSUE TITLE
Add AllTransactionsMetrics graph in txpool dashboard

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#7121]
### Describe the feature

We now have metrics for `AllTransactions`, added here:
https://github.com/paradigmxyz/reth/pull/7067

We should add the new metrics here:
https://github.com/paradigmxyz/reth/blob/027d50fc105fd527dca0bf56fe51b7240f119e66/etc/grafana/dashboards/reth-mempool.json#L1-L200

**Comment by AbnerZheng** [comment]
Will give it a try.
