### ISSUE TITLE
Support more granular backoff timeouts

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#714]
### Describe the feature

Currently, we only have 1 backoff timeout for all `SessionError::should_backoff`.

This should be more granular and allow multiple durations.

**Comment by gakonst** [comment]
Specifically:
* 30s for `TooManyPeers` so we try again in case somebody gets disconnected
* 30s for Ecies Unreadable Stream

I think we penalize too aggressively for both right now. Pls P0 it as it is one of the main reasons why P2P has been unreliable
