### ISSUE TITLE
Return invalid header on error in consensus validation methods

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#7169]
ref https://github.com/paradigmxyz/reth/issues/3007#issuecomment-2000570498

We need to modify some of the consensus validation methods which are used in the full block downloader, so the full block downloader can properly notify the engine of invalid headers.

We should create a new error type that includes both the `ConsensusError` and the invalid header. The `validate_headers_range` method should then return that error type.

**Comment by AbnerZheng** [comment]
Will give it a try.
