### ISSUE TITLE
Parallel State Hashing

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#7183]
### Describe the feature

Make state hashing parallelized using rayon's `par_iter`.

https://github.com/paradigmxyz/reth/blob/e88b16e6e784da7db5fb9cdae3ee7868c3b0790b/crates/trie/src/state.rs#L37-L54

Akin to 

https://github.com/paradigmxyz/reth/blob/ffde69e69b2a145c94ce6422c03b1085b4cd3a80/crates/primitives/src/transaction/mod.rs#L1026-L1039

**Comment by jsvisa** [comment]
I'm interested in this feature, could you please assign this to me, I'll have a try, thanks.
