### ISSUE TITLE
Integrate new pending session metrics into grafana

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7228]
### Describe the feature

new metrics introduced in #7225

they should be integrated into the existing Connections panel:

https://github.com/paradigmxyz/reth/blob/1ad50d148a271d131bcc742a35fcc09f7b2060b7/etc/grafana/dashboards/overview.json#L3082-L3082

**Comment by AbnerZheng** [comment]
Will fire a PR soon.
