### ISSUE TITLE
Websocket 403 error

### ISSUE THREAD

**Issue by van-eth** [paradigmxyz/reth#7248]
### Describe the bug

I'm using v0.1.0-alpha.22 reth and trying to connect to websocket. Using --ws.origins="*" argument but still getting 403 error. Did I miss something? HTTP RPC is working great, problem only persists with websocket connection.

Part of the docker-compose:
 ```
      node
      --chain=mainnet

      --datadir=/data

      --port=30001

      --authrpc.addr=0.0.0.0
      --authrpc.port=7001
      --authrpc.jwtsecret=/config/secrets/jwt.hex

      --rpc-gas-cap=1000000
      --http
      --http.addr=0.0.0.0
      --http.port=8001
      --http.api=eth,net,trace,web3,debug

      --ws
      --ws.addr=0.0.0.0
      --ws.port=8003
      --ws.origins '*' # tried to set --ws.origins="*" as well.
      --ws.api=debug,eth,net,trace,txpool,web3,rpc
```

### Steps to reproduce

1. build v0.1.0-alpha.22 docker image on linux x86 (Ubuntu 22)
2. configure websocket CLI options as described [here](https://paradigmxyz.github.io/reth/cli/reth/node.html)
3. run node
4. make any (e.g chain_id) websocket request using web3 client (web3.py in my case)

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth:v0.1.0-alpha.22 docker image
ghcr.io/paradigmxyz/reth:v0.1.0-alpha.22

### What database version are you on?

Current database version: 1

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this might be a docker thing,
what url are you using?

**Comment by van-eth** [comment]
I basically forgot to add following lines to my nginx configuration as we're loadbalancing websockets. The issue is unrelated to reth, closing.
Fix:
```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";`
```
