### ISSUE TITLE
Remove trusted setup file argument and support

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7266]
### Describe the feature

managing custom trusted setups is no longer desirable, because revm also uses the regular mainnet setup, so we should remove support for this:

https://github.com/paradigmxyz/reth/blob/c868c52063a7f507f2a455a752e159c9b5f08402/crates/node-core/src/node_config.rs#L172-L173

https://github.com/paradigmxyz/reth/blob/c868c52063a7f507f2a455a752e159c9b5f08402/crates/node-builder/src/builder.rs#L1100-L1100

**Comment by JackG-eth** [comment]
Will pick this up
