### ISSUE TITLE
Add timeouts for handshake functions:

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7270]
### Describe the feature

These functions wait (indefinitely) for incoming data from the remote.
This can cause issues if the remote peer never sends data and should be mitigated with a tokio::time::timeout wrapper like

```rust
tokio::time::timeout(HANDSHAKE_TIMEOUT, self.inner.next()).await
```

we need a new error variant for this and new tests

ref:

https://github.com/paradigmxyz/reth/blob/66c9403ea1d3d03938eafc099e64e789aadc3616/crates/net/eth-wire/src/ethstream.rs#L71

https://github.com/paradigmxyz/reth/blob/66c9403ea1d3d03938eafc099e64e789aadc3616/crates/net/ecies/src/stream.rs#L54

https://github.com/paradigmxyz/reth/blob/66c9403ea1d3d03938eafc099e64e789aadc3616/crates/net/ecies/src/stream.rs#L80

**Comment by JackG-eth** [comment]
will take
