### ISSUE TITLE
Safe rlpx capability id masking

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7271]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/0da7b7c314f3c536a50e32b08bf2a0a9759bbf9a/crates/net/eth-wire/src/multiplex.rs#L311-L311

https://github.com/paradigmxyz/reth/blob/0da7b7c314f3c536a50e32b08bf2a0a9759bbf9a/crates/net/eth-wire/src/multiplex.rs#L323-L323

https://github.com/paradigmxyz/reth/blob/0da7b7c314f3c536a50e32b08bf2a0a9759bbf9a/crates/net/eth-wire/src/multiplex.rs#L600-L600

https://github.com/paradigmxyz/reth/blob/0da7b7c314f3c536a50e32b08bf2a0a9759bbf9a/crates/net/eth-wire/src/multiplex.rs#L611-L611

can potentially overflow because the message id space has no restrictions other than:
https://github.com/paradigmxyz/reth/blob/0da7b7c314f3c536a50e32b08bf2a0a9759bbf9a/crates/net/eth-wire/src/capability.rs#L527-L527
 
masking/unmasking should use checked_(add/sub) and return an error on overflow

These should also check for empty input, although this case has already been checked before but just to be safe it should return an error if the msg is empty.
(`io::ErrorKind::InvalidInput`)

**Comment by AbnerZheng** [comment]
Will give it a try.
