### ISSUE TITLE
Check RequestPair payload length during decoding

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#7278]
Currently we discard the rlp header during `RequestPair` decoding:
https://github.com/paradigmxyz/reth/blob/672bdcc57fe3924610e706ea682527ce4dd41121/crates/net/eth-wire/src/types/message.rs#L471

We should:
* Check that the buffer is large enough for the payload length, and
* Check that the buffer consumed exactly `payload_length` bytes after decoding the `RequestPair`

**Comment by AbnerZheng** [comment]
Will give it a try.
