### ISSUE TITLE
Ensure `DisconnectReason` RLP header payload length is correct

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#7279]
The `DisconnectReason` RLP header is decoded here:
https://github.com/paradigmxyz/reth/blob/672bdcc57fe3924610e706ea682527ce4dd41121/crates/net/eth-wire/src/disconnect.rs#L131

But we do not check that the payload length is one. We should add a check that the payload length is one.

Tests should be added which ensure that the decoding fails if the payload length is zero

**Comment by 0xqd** [comment]
hi @Rjected can I take this one? 
However, there is one thing regarding checking payload is one, should we check it? Since the check of `buf.len() > 1` is needed because we want to advance the buf 1 since it's a list. And this piece of code applies for `buf.len() == 1` case as well

```
if buf[0] == 0x00 {
            buf.advance(1);
            Ok(DisconnectReason::DisconnectRequested)
        } else {
            DisconnectReason::try_from(u8::decode(buf)?)
                .map_err(|_| RlpError::Custom("unknown disconnect reason"))
        }
```

**Comment by Rjected** [comment]
> hi @Rjected can I take this one? However, there is one thing regarding checking payload is one, should we check it? Since the check of `buf.len() > 1` is needed because we want to advance the buf 1 since it's a list. And this piece of code applies for `buf.len() == 1` case as well
> 
> ```rust
> if buf[0] == 0x00 {
>             buf.advance(1);
>             Ok(DisconnectReason::DisconnectRequested)
>         } else {
>             DisconnectReason::try_from(u8::decode(buf)?)
>                 .map_err(|_| RlpError::Custom("unknown disconnect reason"))
>         }
> ```

We don't want to check that `buf.len() == 1`, we want to check that `header.payload_length == 1` instead.

**Comment by Rjected** [comment]
also assigned!
