### ISSUE TITLE
Ensure messages are at least one byte before attempting snappy decompression

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#7280]
Currently we use `item.len() - 1` when initializing the snappy buf:
https://github.com/paradigmxyz/reth/blob/66c9403ea1d3d03938eafc099e64e789aadc3616/crates/net/eth-wire/src/p2pstream.rs#L599-L601

We should return an error if the length is zero before attempting this.

**Comment by allnil** [comment]
Can fix it tmrw

**Comment by Rjected** [comment]
> Can fix it tmrw

cool! assigned
