### ISSUE TITLE
Return an error if multiplex message is empty

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#7281]
Right now if the message is empty, this
https://github.com/paradigmxyz/reth/blob/66c9403ea1d3d03938eafc099e64e789aadc3616/crates/net/eth-wire/src/multiplex.rs#L169
and this
https://github.com/paradigmxyz/reth/blob/66c9403ea1d3d03938eafc099e64e789aadc3616/crates/net/eth-wire/src/multiplex.rs#L512

will panic. We should use `.get(0)` here and return an error if the call returns `None`.

**Comment by int88** [comment]
Let me do this :)

**Comment by EthCel** [comment]
Hey, I'd like this one
