### ISSUE TITLE
Custom EVM tracer - log.contract.getAddress()

### ISSUE THREAD

**Issue by naddison36** [paradigmxyz/reth#7293]
### Describe the bug

log.contract.getAddress() is returning the implementation contract address instead of the proxy address

### Steps to reproduce

The following RPC call against reth
```json
{
    "jsonrpc": "2.0",
    "method": "debug_traceTransaction",
    "params": [
        "0xaa0667392bdf6c9823c3dc48a1b7074ef772f567c6b985e4ccd3f1c1c3bbb202",
        {
            "tracer": "{data: [], fault: function(log) {}, step: function(log) { if (log.op.toString().match(/LOG/)) { const topic1 = log.stack.peek(2).toString(16); const tokenAddress = toHex(log.contract.getAddress()); if (topic1 === \"ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef\") { this.data.push({ event: \"Transfer\", pc: log.getPC(), tokenAddress}) } } }, result: function() { return this.data; }}"
        }
    ],
    "id": 1
}
```

Returns 
```json
{
    "jsonrpc": "2.0",
    "result": [
        {
            "event": "Transfer",
            "pc": 12300,
            "tokenAddress": "e42c659dc09109566720ea8b2de186c2be7d94d9"
        },
        {
            "event": "Transfer",
            "pc": 12300,
            "tokenAddress": "e42c659dc09109566720ea8b2de186c2be7d94d9"
        }
    ],
    "id": 1
}
```

When running against a Geth node, it returns
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
        {
            "event": "Transfer",
            "pc": 12300,
            "tokenAddress": "0x889edc2edab5f40e902b864ad4d7ade8e412f9b1"
        },
        {
            "event": "Transfer",
            "pc": 12300,
            "tokenAddress": "0x889edc2edab5f40e902b864ad4d7ade8e412f9b1"
        }
    ]
}
```

Note the token address from reth is `e42c659dc09109566720ea8b2de186c2be7d94d9` while Geth is `0x889edc2edab5f40e902b864ad4d7ade8e412f9b1`

0x889edc2edab5f40e902b864ad4d7ade8e412f9b1 is the proxy address
0xe42c659dc09109566720ea8b2de186c2be7d94d9 is the implementation contract

### Platform(s)

Windows (x86)

### What version/commit are you on?

```
reth Version: 0.2.0-beta.3
Commit SHA: 56d688b
Build Timestamp: 2024-03-18T13:08:51.400134562Z
Build Features: jemalloc
Build Profile: maxperf
```

### What database version are you on?

```
Current database version: 2
Local database version: 2
```

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
I believe it's this

https://github.com/paradigmxyz/evm-inspectors/blob/b3082f3deca76e721ac72cee4a6857b4ff88e684/src/tracing/js/mod.rs#L448-L454

I can't really remember why we did this for the regular tracer, but it looks like we need to remove this for JS
