### ISSUE TITLE
Implement ots_getTransactionError endpoints

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7309]
### Describe the feature

Execute the transaction and get the return type

https://github.com/paradigmxyz/reth/blob/1dc0aab51c50cfe6836e54283928b6eca590aa4c/crates/rpc/rpc/src/otterscan.rs#L46-L49

This can be done with a NoopInspector here:

https://github.com/paradigmxyz/reth/blob/1dc0aab51c50cfe6836e54283928b6eca590aa4c/crates/rpc/rpc/src/eth/api/transactions.rs#L993-L993

## TODO:

also restrict this to `EthTransactions`

https://github.com/paradigmxyz/reth/blob/1dc0aab51c50cfe6836e54283928b6eca590aa4c/crates/rpc/rpc/src/otterscan.rs#L29-L29

### Additional context

https://github.com/otterscan/otterscan/blob/develop/docs/custom-jsonrpc.md

**Comment by AbnerZheng** [comment]
Will give it a try.
