### ISSUE TITLE
Implement `ots_getInternalOperations`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7310]
### Describe the feature

Needs inspector in evm-inspectors

https://github.com/paradigmxyz/evm-inspectors/pull/76

## TODO:

implement

https://github.com/paradigmxyz/reth/blob/1dc0aab51c50cfe6836e54283928b6eca590aa4c/crates/rpc/rpc/src/otterscan.rs#L41-L44

extend trait bounds to `EthTransactions`, ref #7309

see also for reference:

https://github.com/paradigmxyz/reth/blob/1dc0aab51c50cfe6836e54283928b6eca590aa4c/crates/rpc/rpc/src/trace.rs#L183-L203

**Comment by AbnerZheng** [comment]
Will give it a try once the `inspector` be merged.
