### ISSUE TITLE
Implement `ots_getBlockTransactions`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7311]
### Describe the feature

See also:

https://github.com/otterscan/otterscan/blob/develop/docs/custom-jsonrpc.md

This is similar to:

https://github.com/paradigmxyz/reth/blob/1dc0aab51c50cfe6836e54283928b6eca590aa4c/crates/rpc/rpc/src/otterscan.rs#L65-L69

but also needs receipts, which can be obtained via:

https://github.com/paradigmxyz/reth/blob/1dc0aab51c50cfe6836e54283928b6eca590aa4c/crates/rpc/rpc-api/src/eth.rs#L74-L77

https://github.com/paradigmxyz/reth/blob/1dc0aab51c50cfe6836e54283928b6eca590aa4c/crates/rpc/rpc/src/otterscan.rs#L71-L72

ref page cropping:

https://github.com/ledgerwatch/erigon/blob/aefb97b07d1c4fd32a66097a24eddd8f6ccacae0/turbo/jsonrpc/otterscan_api.go#L619-L627

**Comment by AbnerZheng** [comment]
Will give it a try.
