### ISSUE TITLE
Differentiate between tagged releases and source builds in `--version` output

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#7325]
### Describe the feature

We can set an environment variable in the build script to append '-dev' at the end of the version string when the binary has not been built on a git tag.

### Additional context

- for example, rustc:
```text
$ rustc +stage2 -V
rustc 1.79.0-dev

$ rustc +stage2 -Vv
rustc 1.79.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.79.0-dev
LLVM version: 18.1.2
```

**Comment by allnil** [comment]
Can do it tmrw
