### ISSUE TITLE
Insufficient backpressure during body stage

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7331]
### Describe the feature

ref https://github.com/paradigmxyz/reth/issues/7233

while we limit the size of buffered responses and slow down followup requests:

https://github.com/paradigmxyz/reth/blob/a6d4f6bd15ece660ab348f46a047ea9b47b71959/crates/net/downloaders/src/bodies/bodies.rs#L59-L60

https://github.com/paradigmxyz/reth/blob/a6d4f6bd15ece660ab348f46a047ea9b47b71959/crates/net/downloaders/src/bodies/bodies.rs#L373-L376

this does not take the already queued blocks into account:

https://github.com/paradigmxyz/reth/blob/a6d4f6bd15ece660ab348f46a047ea9b47b71959/crates/net/downloaders/src/bodies/bodies.rs#L61-L62

it's possible that this buffer runs away if there are requests that prevent us from yielding a new batch in time.

## TODO
* limit new requests if queued bodies exceed a certain threshold

**Comment by 0xqd** [comment]
if i understand it correctly, 

**Current Behavior:**
The downloader limits new requests solely based on a full buffered_responses queue, potentially overflowing queued_bodies.

**Proposed Fix:**
Free Slots: If both buffered_responses and queued_bodies have free slots, accept new requests.
Full Queued Bodies: If queued_bodies is full, limit new requests (backpressure).
Full Buffered Responses: If buffered_responses is full, limit new requests (backpressure).

I can take this one

**Comment by mattsse** [comment]
I'd like to get @rkrasiuk and @Rjected view on this but I think we can limit new requests here
```rust
 'inner: while this.in_progress_queue.len() < concurrent_requests_limit && 
     this.has_buffer_capacity() 
```
when the queued bodies exceed a certain threshold, just like we do for the buffered (`has_buffer_capacity`)

**Comment by 0xqd** [comment]
yes definitely, we need to add another len for bodies buffered and check if both are empty before accepting any new requests.

**Comment by Rjected** [comment]
> I'd like to get @rkrasiuk and @Rjected view on this but I think we can limit new requests here
> 
> ```rust
>  'inner: while this.in_progress_queue.len() < concurrent_requests_limit && 
>      this.has_buffer_capacity() 
> ```
> 
> when the queued bodies exceed a certain threshold, just like we do for the buffered (`has_buffer_capacity`)

I think this makes sense, we should stop sending requests if the queued bodies grows too large. the bodies stage will then eventually deal with the queued bodies and we'll start sending requests again. The queued buffer could still grow, since we'd insert here
https://github.com/paradigmxyz/reth/blob/a6d4f6bd15ece660ab348f46a047ea9b47b71959/crates/net/downloaders/src/bodies/bodies.rs#L396-L398

But this is based on the limits we set for buffered responses, so the growth should be bounded
