### ISSUE TITLE
Initialize `BuilderContext`

### ISSUE THREAD

**Issue by grantkee** [paradigmxyz/reth#7357]
### Describe the feature

`BuilderContext` is used to build components, but it isn't publicly available. I'd like to manage my own `BuilderContext` for launching custom node components.

### Additional context

My blockchain uses some components for producing blocks and other components for validating and executing blocks after consensus. I need the same `BuilderContext` for launching components in these separate domains, but I can't initialize the struct because it's private.

**Comment by mattsse** [comment]
are you extending the NodeComponents trait?
would like to know more about your customizations, consider reaching out on tg @mattsse :)
