### ISSUE TITLE
Remove `ProviderError` variant in `BlockExecutionError`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#7359]
Right now there is a non-descriptive `ProviderError` in `BlockExecutionError`:
https://github.com/paradigmxyz/reth/blob/1a7ba845b2ed623699a04031919c7e6479f39dc9/crates/interfaces/src/executor.rs#L91-L93

This is only used in `complete_header`:
https://github.com/paradigmxyz/reth/blob/1a7ba845b2ed623699a04031919c7e6479f39dc9/crates/consensus/auto-seal/src/lib.rs#L409-L414

We should evaluate what kind of error this should be, maybe a block validation error, but if it's used in block production, that might not be appropriate

**Comment by allnil** [comment]
Hi! May take a look here
