### ISSUE TITLE
Read Only DB accesses are not parallelized

### ISSUE THREAD

**Issue by AtomicAzzaz** [paradigmxyz/reth#7360]
### Describe the bug

I have a multi-threaded program that needs to query the state very often. I thus use a `LatestStateProvider` (or `HistoricalStateProvider`) put under an `Arc` that I share across threads. As those are read-only providers, there should not be any issue with multi-threading. However, I noticed that the db access is not parallelized at all when doing this, it takes exactly the same time as if all the queries were done in series.

I compared with re-creating a state provider in each thread, and the performances were much better (actually parallelized), but it is not very convenient. 

I don't know if this behaviour is intended. If it is, what would be the correct way to have a state provider sharable between threads that would actually parallelize db accesses?

### Steps to reproduce

- Create a `ProviderFactory` with a database opened using `open_db_read_only`.
- Compare the performances between:
  - Create a provider `let provider = Arc::new(provider_factory.latest()?);`, start some threads and in each one of them query random storages on an `Arc::clone` of the provider.
  - Start some threads, and in each one of them create a provider  `let provider = provider_factory.latest()?;` and then query random storages on that provider.

### Platform(s)

Linux (x86)

### What version/commit are you on?

alpha.21

### What database version are you on?

1

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by 0xAlcibiades** [comment]
Seems like this might be belonging on alloy.

**Comment by AtomicAzzaz** [comment]
> Seems like this might be belonging on alloy.

There are "providers" in reth; used for low-level interaction with the DB.

https://github.com/paradigmxyz/reth/blob/09de0ac13d99648f5662a6b15cebfacff010d0ae/crates/storage/provider/src/providers/state/latest.rs#L124-L130

**Comment by gakonst** [comment]
Yes you need to open a separate transaction per thread via the factory's latest() method. 

One transaction, even if shared across threads, will block / not give you perf improvements.

**Comment by gakonst** [comment]
Reopening in case MDBX NOTLS affects this.
