### ISSUE TITLE
Support features and rustflags in `Dockerfile`

### ISSUE THREAD

**Issue by 0xAlcibiades** [paradigmxyz/reth#7365]
### Describe the feature

Right now `RUSTFLAGS` support is ommited, and features flags are implemented incorrectly throughout the `Dockerfile`, i.e. that the feature flags such as jemalloc need to be present during both the cook and build phase, and `RUSTFLAGS` in prepare, cook, and build.

### Additional context

Should be an ez pz PR.

**Comment by KyrylR** [comment]
Hello, I am new here, but would like to tackle this problem this week, can I?
