### ISSUE TITLE
Add support for engine API over IPC

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7370]
### Describe the feature

currently the engine API (AuthServer) is only spawned over HTTP and ws:

https://github.com/paradigmxyz/reth/blob/33c466d88c4bee67f0b4eb15b2ca1b2fc421b10b/crates/rpc/rpc-builder/src/auth.rs#L168-L168

we can add an option to also make open a new IPC socket, no auth required here because local.

ref:

https://github.com/paradigmxyz/reth/blob/33c466d88c4bee67f0b4eb15b2ca1b2fc421b10b/crates/rpc/rpc-builder/src/lib.rs#L1454-L1457

## TODO

add ipc config to

https://github.com/paradigmxyz/reth/blob/33c466d88c4bee67f0b4eb15b2ca1b2fc421b10b/crates/rpc/rpc-builder/src/auth.rs#L190-L190

and launch if configured

**Comment by allnil** [comment]
Can take it
