### ISSUE TITLE
Untangle inconvenient node-api dependencies 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7375]
### Describe the feature

currently we have a few weird traits and dependencies across several crates

https://github.com/paradigmxyz/reth/blob/6ed91107da39ac6534408b8f5b0052568967bb60/crates/node-builder/src/provider.rs#L10-L10

This really belongs into node-api:

https://github.com/paradigmxyz/reth/blob/6ed91107da39ac6534408b8f5b0052568967bb60/crates/node-builder/src/node.rs#L38-L38

The node-api is to broad, especially this dep makes it very inconvenient:

https://github.com/paradigmxyz/reth/blob/6ed91107da39ac6534408b8f5b0052568967bb60/crates/storage/provider/Cargo.toml#L22-L22

we need to scope all of this down a bit by:
* adding a crate for foundational traits only (node-primitives)
* node-api then gathers everything needed to configure a node (node-primitives + provider)

**Comment by 0xqd** [comment]
```
adding a crate for foundational traits only (node-primitives)
node-api then gathers everything needed to configure a node (node-primitives + provider)
```

I agree, this is a good scope to organize types across projects, wrapping and unwrap across projects would not be ideal, and it looks ugly. We need a primitives types where everyone can explore before introduce new one.
