### ISSUE TITLE
Improve reth-revm crate and layout

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7391]
### Describe the feature

Atm a few things are mangled with optimism features.
The goal is to extract as much as possible to standalone op specific crates.
This has been done with payload builder and txpool crates

op features in the evm/blockexecutor code is the biggest pain point atm.
we already have an evm abstraction which should be the starting point for this.
we need to follow a similar pattern here:
1. extract the general abstraction (traits)
2. move ethereum impl to ethereum crate, move optimism impl to op crate

This is similar to #7375 but should be done before #7375

we need:
* `reth-evm`: contains all evm related abstractions: `ConfigureEvm`, for the time being the `BlockExecutor` traits as well
* `reth-ethereum-evm`
* `reth-optimism-evm`

**Comment by Rjected** [comment]
Is there anything left on this?
