### ISSUE TITLE
Simplify BlockExecutor trait

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7392]
### Describe the feature

the BlockExecutor trait provides several functions:

https://github.com/paradigmxyz/reth/blob/c13d7da68d83404ec385ed106fe309db5472e086/crates/storage/provider/src/traits/executor.rs#L20-L21

however only one is really used (besides tests):
https://github.com/paradigmxyz/reth/blob/c13d7da68d83404ec385ed106fe309db5472e086/crates/blockchain-tree/src/chain.rs#L205-L206

the others are more or less only used internally by the function above.

There are two usages of this trait:
* In the execution stage where a series of blocks is executed before the state is extracted
* In the tree where a single block is executed before a block is extracted

This interface can be simplified:
* First remove unused (public) functions
* Reorder internals so both usecases can be supported

blocked by #7391

**Comment by onbjerg** [comment]
the trait has been replaced, is this still relevant @mattsse
