### ISSUE TITLE
Add BlockReader::block_with_senders_range

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7395]
### Describe the feature

we currently only have:

https://github.com/paradigmxyz/reth/blob/c13d7da68d83404ec385ed106fe309db5472e086/crates/storage/provider/src/traits/block.rs#L132-L135

it would be useful to also have a function that returns the senders that would be beneficial for `trace_filter`

**Comment by AbnerZheng** [comment]
Can I take this?

**Comment by mattsse** [comment]
sure!

there are likely some simplficiations we can do for these functions:

https://github.com/paradigmxyz/reth/blob/87c4ae744ae8430ef64e8055d9531a7cdcc2f164/crates/storage/provider/src/providers/database/provider.rs#L1360-L1360
