### ISSUE TITLE
Download Headers concurrently

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#741]
### Describe the feature

Currently we download headers batch by batch based on the parent hash, essentially: `hash(blocknum - limit)`

In the BodiesDownloader we already have a concurrent stream of requests.

ideally the HeadersDownloader would work the same, but we'd need to switch to requesting by block number instead of by hash.

since the logic of both is somewhat similar, some parts can probably be unified

https://github.com/paradigmxyz/reth/blob/ee8b0efed69556c256d659b7a32c0558b3d8392b/crates/net/downloaders/src/bodies/concurrent.rs#L56

**Comment by onbjerg** [comment]
Superceded by #764
