### ISSUE TITLE
mainnet reth keeps going out of sync

### ISSUE THREAD

**Issue by Moataz-E** [paradigmxyz/reth#7420]
### Describe the bug

Running reth as EL and lighthouse as CL. My validators keep going offline sporadically and when I log into the machine it is usually reth that has gone out of sync. I tried leaving the machine running overnight with trace logging level but woke up to it offline with out of space errors due to a 2.7T of log file. I have ~370MB of logs from around the incident that I would be happy to share.

The out of sync behaviour can be seen around the **Apr 01 22:00:00** mark.

[reth_trace.log](https://github.com/paradigmxyz/reth/files/14829462/reth_trace.log)
[lighthousebeacon.log](https://github.com/paradigmxyz/reth/files/14829452/lighthousebeacon.log)

### Steps to reproduce

Run a node with reth as EL client and lighthouse as CL client.

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.2.0-beta.4

### What database version are you on?

2

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
What are your machine specs, especially disk specs? Can you also share how you're running the node, specifically what command?

**Comment by Moataz-E** [comment]
**Machine:**
* Linux Mint 21.1
* Intel i5-1135G7 @ 2.4GHz
* 16GB Ram
* 4TB Fanxiang S790 PCIE4.0x4 SSD M.2 TLC

**Command:**
* reth node --full --datadir /var/lib/reth --log.file.directory /var/lib/reth/logs --authrpc.jwtsecret /var/lib/jwtsecret/jwt.hex

**Comment by onbjerg** [comment]
@Moataz-E In the logs, it looks like you restart the node at 21:57, after which you have almost no peers. Did you restart the node because it was not syncing prior to this?

**Comment by Moataz-E** [comment]
> @Moataz-E In the logs, it looks like you restart the node at 21:57, after which you have almost no peers. Did you restart the node because it was not syncing prior to this?

If you are referring to line 46878 in the reth.log file, that's an hour after the incident and the reason for the restart is I was changing the log level from info to trace in the hope that I can capture something about the behavior. Note that there appears to be two timestamps, a local one and a UTC one.

The incident I am reporting happened at line 46686 and unfortunately at that time my log level was set to INFO.

**Comment by Moataz-E** [comment]
Quick update, it turns out the issue was with my network speed. I've upgraded to 5G mobile broadband and reth has been running smoothly for two days now with near perfect attestation ratio. For some reason geth worked fine on the slower network but it did have a low attestation efficiency which I brushed off.

Thanks for taking a look, I will close the issue.
