### ISSUE TITLE
Add more sophisticated e2e tests

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7437]
### Describe the feature

with https://github.com/paradigmxyz/reth/blob/05c9f61a38978eadd8ba587d3d952fd9eedcbd1f/crates/node-e2e-tests/tests/it/eth.rs#L20-L20

we now have a setup run e2e tests.
now we can add more sophisticated tests and utils to:
* record and replay blocks:
  * save all blocks to a file
  * restart a new and replay all blocks
* deploy contracts on launch (this could even be integrated with some helpers that run forge scripts)
* generate txs that interact with the deployed contracts

Emphasis is here on reusability of tooling

cc @loocapro

**Comment by loocapro** [comment]
I am up for this!
