### ISSUE TITLE
perf(downloaders): Download bodies while writing to disk to utilize bandwidth optimally

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#744]
# Context

1. Right now, the bodies downloader gets a batch of blocks given the headers

https://github.com/paradigmxyz/reth/blob/f21a4020b190f6e4f880636595342c56bc7aa7fe/crates/net/downloaders/src/bodies/concurrent.rs#L123-L126

2. Exposed over `bodies_stream` which concurrently batch polls the headers split in chunks

https://github.com/paradigmxyz/reth/blob/a94560fc5d0688911ec148ec8732a4d2ae0fa192/crates/net/downloaders/src/bodies/concurrent.rs#L56-L74

3. The bodies stage queries the DB with a range of blocks to get the headers it needs

https://github.com/paradigmxyz/reth/blob/a94560fc5d0688911ec148ec8732a4d2ae0fa192/crates/stages/src/stages/bodies.rs#L241-L263

4. Then there's the I/O heavy component which seems to block the stream

https://github.com/paradigmxyz/reth/blob/a94560fc5d0688911ec148ec8732a4d2ae0fa192/crates/stages/src/stages/bodies.rs#L100-L111

5. As a result, the stream isn't downloading stuff in the background until it's polled again, underutilizing our bandwidth. It

![image](https://user-images.githubusercontent.com/17802178/210966186-1cf616e2-1fda-4e82-a82f-c94656d1b044.png)

# Solution

* Should the downloader keep downloading while we're writing blocks in the i/o part of the loop?
* Should we be spawning the i/o loop?

idk/not sure keen to discuss.

**Comment by rkrasiuk** [comment]
You can't doing without breaking the current control flow (e.g. delegating commit responsibility to stages), since downloaders are not separate processes, but short-lived streams (they exist only for the duration of a single `Stage::execute` invocation)

**Comment by gakonst** [comment]
Maybe the downloader can download larger slices than the commit threshold in a background task? And the bodies stream simply yields these values instead of downloading + yielding them? cc @mattsse also given stream territory

**Comment by gakonst** [comment]
Maybe related to the logic to be unified with Headers here https://github.com/paradigmxyz/reth/issues/741#issue-1521544969

**Comment by onbjerg** [comment]
That block in the while loop is not I/O heavy, it is not writing to disk. Things are only written to disk when the stage is done (`tx.commit` is called). It might be blocking though, but I think that's just a product of the stream not being handrolled like for headers.

**Comment by mattsse** [comment]
downloading should be a separate task then and the stage just controls that task, submits new batch requests, pulls responses then.

**Comment by onbjerg** [comment]
Superceded by #764
