### ISSUE TITLE
Persistent P2P Peers

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#745]
### Describe the feature

Right now, we initialize with a fresh peer set each time, taking some time until we re-discover new good peers.

It would be nice if we could instead dump our peers to disk, and load them on startup time.

### How?

1. Add a ctrl+c / on-shutdown hook which dumps the current peerset to a CLI-configured path, default `persistent-peers.json` (maybe stored next to the mdbx.dat?)
2. The format of that file probably should be `[ { "enode": "enode://...", "reputation": "1234" }, ... ]`?
3. There probably should be an option to only dump the top X percentile of your peers, to avoid stagnating / getting eclipsed and never being able to peer with good peers?

**Comment by gakonst** [comment]
@ralexstokes @lightclient I know you guys had thoughts on this, so curious for any additional feedback.

**Comment by lightclient** [comment]
I don't really have much of my own thoughts on this, mostly parroting conversations I've had in the past with Felix:

Overall, this is a good idea. A main reason we haven't done this in geth AFAIK is that i) it is a little weird to layer a second connection state on top of TCP and ii) NATs tend to be smarter about TCP connection states so reviving the connection may be more difficult than via UDP. Should be super doable though.

**Comment by gakonst** [comment]
Marking as good-first-issue and unassigning Matt.

**Comment by MegaRedHand** [comment]
I would like to take this on.

**Comment by gakonst** [comment]
Assigned! Thank you.
