### ISSUE TITLE
Request for Documentation Addition: Retrieving Peer ID from Local REVM Node

### ISSUE THREAD

**Issue by bagatka** [paradigmxyz/reth#7456]
### Describe the change

I am reaching out to request the addition of documentation regarding the process of retrieving the peer ID from a local REVM node. Currently, the available documentation does not provide clear guidance on this matter, leading to confusion for users attempting to interface with the node.

Despite utilizing the `admin_nodeInfo` RPC call, users, including myself, are encountering difficulties in obtaining the correct peer ID. The peer ID returned from this call does not seem to be compatible with the formatting required for certain applications, such as creating p2p node addresses.

In the example provided (`/ip4/54.167.71.57/tcp/13000/p2p/16Uiu2HAkvxQyb62x55RrhxxYHm1ZJFMFFFhCZ67YVmTcS6kJwqQR`), the peer ID appears to be encoded differently from what I am receiving. (template requires NodeID `/ip4/<IPv4_NETWORK_ADDRESS>/tcp/<LISTENING_PORT>/p2p/<NODE_ID>`)

I believe that comprehensive documentation detailing the steps required to retrieve the peer ID from a local REVM node, as well as potential troubleshooting tips for common issues, would greatly benefit the community.

Could the documentation team please consider adding a section or updating existing documentation to address this topic? Clear instructions and examples would assist users in effectively interfacing with their local REVM nodes.

Thank you for considering this request.

### Additional context

Utilized `admin_nodeInfo` RPC call
Peer ID received (`0xa9...deb38f45`) not compatible with desired format

**Comment by mattsse** [comment]
> not compatible with desired format

what's the desired format?

**Comment by bagatka** [comment]
Sorry @mattsse, updated the issue.

Here's what I'm trying to achieve: `/ip4/<IPv4_NETWORK_ADDRESS>/tcp/<LISTENING_PORT>/p2p/<NODE_ID>`.

`16Uiu2HAkvxQyb62x55RrhxxYHm1ZJFMFFFhCZ67YVmTcS6kJwqQR` was used as an example value in docs.
