### ISSUE TITLE
Use alloy-rpc types for admin namespace

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7459]
### Describe the feature

these types are now available in alloy and we should remove them here:

https://github.com/paradigmxyz/reth/blob/8d1d13ef89cf19459adc37ba0c45e7aac6270dc1/crates/rpc/rpc-types/src/admin.rs#L9-L9

and instead use alloy's types

cc @AbnerZheng

**Comment by justcode740** [comment]
will take a look

**Comment by justcode740** [comment]
will take a look
