### ISSUE TITLE
replace lru with schnellru

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7471]
### Describe the feature

replace this lru

https://github.com/paradigmxyz/reth/blob/67558db6f39a9bc260cac6a88c614c6f61818437/crates/blockchain-tree/Cargo.toml#L25-L25

https://github.com/paradigmxyz/reth/blob/67558db6f39a9bc260cac6a88c614c6f61818437/crates/blockchain-tree/src/block_buffer.rs#L35-L35

with schnellru::LruMap with byLength limiter

ref

https://github.com/paradigmxyz/reth/blob/67558db6f39a9bc260cac6a88c614c6f61818437/crates/net/network/src/discovery.rs#L133-L133

**Comment by 0xJepsen** [comment]
I can do this, will open a PR tomorrow.
