### ISSUE TITLE
Launch disc services concurrently

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7473]
### Describe the feature

this is a bit verbose because all of these are optional:

https://github.com/paradigmxyz/reth/blob/57e25be058d041907840f81feb2e82a1aade6714/crates/net/network/src/discovery.rs#L81-L109

but this setup can be done concurrently.

I think the most straight-forward approach here would be to use async scopes that we then try_join

**Comment by justcode740** [comment]
will take a look
