### ISSUE TITLE
Extend `NodeBuilder::extend_rpc_modules` to a more general rpc config call

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7487]
### Describe the feature

there should be a call that not only extends but also gives more control over the builtin rpc namespaces, especially eth.
Most likely the rpc setup would need to be modified so that custom logic can be injected more easily. This needs to be solved for `EthApi` first, with something like `EthApiCore` that provides the foundation for all network specific (eth/op) impls.

see also https://github.com/paradigmxyz/reth/pull/7482

**Comment by ameya-deshmukh** [comment]
@mattsse is this still open? Have personally found the `extend_rpc_modules` in its current state a bit tedious to use, happy to take this up

**Comment by mattsse** [comment]
we decided on a different design

**Comment by ameya-deshmukh** [comment]
thanks! is there work on this that is still relevant to be taken up as an external contribution?
