### ISSUE TITLE
Add anvil_ hardhat rpc-api traits

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7489]
### Describe the feature

it would be nice to have rpc client traits for the anvil_/hardhat_ namespace

This issue consists of two parts:

1. Move all rpc types that are part of the anvil_ /hardhat_ endpoints and missing in alloy-rpc-types to alloy-rpc-types, for example: https://github.com/foundry-rs/foundry/blob/master/crates/anvil/core/src/eth/mod.rs#L375-L376
2. Add bindings for all anvil_ /hardhat_ endpoints from:
https://github.com/foundry-rs/foundry/blob/master/crates/anvil/core/src/eth/mod.rs#L44-L44
as traits to rpc-api crate, same as:
https://github.com/paradigmxyz/reth/blob/b89af430e2f45f8a6e53776a6e5150c1b21458c6/crates/rpc/rpc-api/src/web3.rs#L4-L7

**Comment by justcode740** [comment]
will take a look

**Comment by mattsse** [comment]
thanks @justcode740, 
you're already assigned to a few other issues. I'll leave this open in case anyone else wants to take this or until you wrapped up the others :)

**Comment by kallydev** [comment]
Could I take this issue?

**Comment by mattsse** [comment]
I believe there should be an alias attribute for jsonrpsee, so we probably don't need two traits
