### ISSUE TITLE
Replace ethsigner trait with alloy-signer

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7490]
### Describe the feature

we now have alloy-signer as dependency, and the `EthSigner` trait:

https://github.com/paradigmxyz/reth/blob/b89af430e2f45f8a6e53776a6e5150c1b21458c6/crates/rpc/rpc/src/eth/signer.rs#L19-L19

can now be replaced with alloy signer traits (NetworkSigner)

we can also replace all the typedtransaction types:
https://github.com/paradigmxyz/reth/blob/b89af430e2f45f8a6e53776a6e5150c1b21458c6/crates/rpc/rpc-types/src/eth/transaction/typed.rs#L18-L18

in favor of https://github.com/alloy-rs/alloy/blob/098907b76208f786f3070e23c76428d692e94dc3/crates/network/src/transaction/builder.rs#L48-L48 which is implemented for `TransactionRequest`

https://github.com/alloy-rs/alloy/blob/098907b76208f786f3070e23c76428d692e94dc3/crates/network/src/transaction/builder.rs#L212-L216

cc @allnil

**Comment by justcode740** [comment]
will take a look

**Comment by mattsse** [comment]
thanks @justcode740,
you're already assigned to a few other issues. I'll leave this open in case anyone else wants to take this or until you've wrapped up the others :)

**Comment by allnil** [comment]
will look at it

**Comment by onbjerg** [comment]
Hey @allnil, what's the status of this?

**Comment by allnil** [comment]
@onbjerg 
hey! going to finish it this week

**Comment by allnil** [comment]
in progress

**Comment by Rjected** [comment]
@allnil update on this?

**Comment by kamuik16** [comment]
> ### Describe the feature
> we now have alloy-signer as dependency, and the `EthSigner` trait:
> 
> https://github.com/paradigmxyz/reth/blob/b89af430e2f45f8a6e53776a6e5150c1b21458c6/crates/rpc/rpc/src/eth/signer.rs#L19-L19
> 
> can now be replaced with alloy signer traits (NetworkSigner)
> 
> we can also replace all the typedtransaction types:
> 
> https://github.com/paradigmxyz/reth/blob/b89af430e2f45f8a6e53776a6e5150c1b21458c6/crates/rpc/rpc-types/src/eth/transaction/typed.rs#L18-L18
> 
> in favor of https://github.com/alloy-rs/alloy/blob/098907b76208f786f3070e23c76428d692e94dc3/crates/network/src/transaction/builder.rs#L48-L48 which is implemented for `TransactionRequest`
> 
> https://github.com/alloy-rs/alloy/blob/098907b76208f786f3070e23c76428d692e94dc3/crates/network/src/transaction/builder.rs#L212-L216
> 
> cc @allnil
> 
> ### Additional context
> _No response_

Hey @mattsse! Is this issue open to work?

**Comment by mattsse** [comment]
hey @kamuik16 are you still interested in this?

**Comment by allnil** [comment]
yeh, guys, sorry, I don't have capacity to finish it, pretty big issue and I was quite overloaded

**Comment by mattsse** [comment]
all good, the draft should be useful for anyone that'll pick this up, ty @allnil

**Comment by mvares** [comment]
@mattsse that’s interesting. I’m finishing my last issue and go for this

**Comment by mvares** [comment]
@mattsse, will all components that implement the trait `EthSigner` possibly be changed?

**Comment by mattsse** [comment]
I think we can keep the trait but hide the signing internally like:

https://github.com/alloy-rs/alloy/blob/c3ccf7e2c5f9720fa6c193a9ea918aabf88aa6a2/crates/network/src/transaction/signer.rs#L51-L60

**Comment by mvares** [comment]
> I think we can keep the trait but hide the signing internally like:
> 
> https://github.com/alloy-rs/alloy/blob/c3ccf7e2c5f9720fa6c193a9ea918aabf88aa6a2/crates/network/src/transaction/signer.rs#L51-L60
> 
> similar to:
> 
> https://github.com/paradigmxyz/reth/pull/8614/files#diff-fc791d9a535c846c23e379d9e1656f7c2f5974e06c91da0ce8d89e0322b1696bR1063-R1072
> 
> I'm fine with the rlp roundtrip

well, what I was wondering:

continue with trait `EthSigner` and only assigns it with `Signer` from alloy-signer

cc @mattsse

**Comment by mvares** [comment]
> I think we can keep the trait but hide the signing internally like:
> 
> https://github.com/alloy-rs/alloy/blob/c3ccf7e2c5f9720fa6c193a9ea918aabf88aa6a2/crates/network/src/transaction/signer.rs#L51-L60
> 
> similar to:
> 
> https://github.com/paradigmxyz/reth/pull/8614/files#diff-fc791d9a535c846c23e379d9e1656f7c2f5974e06c91da0ce8d89e0322b1696bR1063-R1072
> 
> I'm fine with the rlp roundtrip

btw, this makes sense
if we keep the trait, maybe could be benefincial for we...

**Comment by mattsse** [comment]
marking this as completed per #11089
