### ISSUE TITLE
remove WsHttpServerKind type and simplify server launch

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7491]
### Describe the feature

the rpc-builder process has too many steps
Currently, we have a type for all server variants we're using:

https://github.com/paradigmxyz/reth/blob/b89af430e2f45f8a6e53776a6e5150c1b21458c6/crates/rpc/rpc-builder/src/lib.rs#L2018-L2020

## TODO
remove intermediary types so that the launch process becomes a single function that configures the server and starts it without doing multiple steps, which is basically this function:

https://github.com/paradigmxyz/reth/blob/b89af430e2f45f8a6e53776a6e5150c1b21458c6/crates/rpc/rpc-builder/src/lib.rs#L1752-L1752

this means this function must also go

https://github.com/paradigmxyz/reth/blob/b89af430e2f45f8a6e53776a6e5150c1b21458c6/crates/rpc/rpc-builder/src/lib.rs#L1637-L1643

and instead everything should be a single function that configures the tower services without intermediary types.
`Optionlayer` is likely useful here for cors,auth

**Comment by justcode740** [comment]
will take a look

**Comment by smatthewenglish** [comment]
@mattsse i took an initial crack at it, just getting back up to speed on things. are there some tests I can run to make sure i'm on the right track?

**Comment by mattsse** [comment]
existing tests should cover this, but could be better, something we can look into next :)

**Comment by elijahhampton** [comment]
@mattsse I will take it

**Comment by ozgunozerk** [comment]
If this is still stale, I think I can do it, let me know!
