### ISSUE TITLE
Auto impl Arc, & and Box for `StateProviderFactory`

### ISSUE THREAD

**Issue by 0xDmtri** [paradigmxyz/reth#7496]
### Describe the feature

I am doing some dev work using Reth components and I have realized that we don't have `#[auto_impl(Arc, &, Box)]` for the `StateProviderFactory`. Was there a particular reason not to auto impl them? If not, would you be Ok with me adding these auto impls to the corresponding trait?

### Additional context

https://github.com/paradigmxyz/reth/blob/main/crates/storage/provider/src/traits/state.rs#L100

**Comment by shekhirin** [comment]
yeah, I'm personally fine with that

**Comment by 0xDmtri** [comment]
> yeah, I'm personally fine with that

great, will do the PR today and ref this issue. Cheers lads!

**Comment by emhane** [comment]
@0xDmtri technically a lady, but can roll with lad
