### ISSUE TITLE
Document QueuedStage::execute vs Stage::execute

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#751]
### Describe the feature

The current docs here are not helpful when coming from `Stage::execute`

https://github.com/paradigmxyz/reth/blob/9d6be78f4b0051efc7b5901f294b20bb7a3cb7d9/crates/stages/src/pipeline.rs#L295-L300

After looking at the code it becomes obvious what it does

```rust
 loop {
     stage.execute()
     if done {
        return
     }
 } 
```

https://github.com/paradigmxyz/reth/blob/9d6be78f4b0051efc7b5901f294b20bb7a3cb7d9/crates/stages/src/pipeline.rs#L354-L360

Maybe `Stage::execute` is not 100% fitting because it only executes until it can no longer make progress, hence the `done`

perhaps we rename this to highlight this?

**Comment by onbjerg** [comment]
What is the point of confusion for `Stage::execute`?

**Comment by mattsse** [comment]
it's mainly that both, `QueuedStage` and `Stage` are called `Stage` and both have `execute` but they behave differently.

If you're not familiar with the code yet, the question "Why does QueuedStage not impl Stage?" may come up.
And how do the `execute` functions differ

**Comment by onbjerg** [comment]
No longer relevant as `QueuedStage` doesn't exist anymore
