### ISSUE TITLE
replace basefeeparams with alloy-eips-basefee-params

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7530]
## TODO

replace

https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/chain/spec.rs#L443-L450

with alloy-eips::BasefeeParams

add const functions for optimism constructors

### Additional context

-

**Comment by rodrigoherrerai** [comment]
Can I take it

**Comment by rodrigoherrerai** [comment]
@mattsse  

The max_change_demnominator and elasticity_multiplier is u128 in alloy and in reth is u64.
https://github.com/alloy-rs/alloy/blob/987b3936f78c067baedcf811620975d3a4a26443/crates/eips/src/lib.rs#L12

Where should the change be ?

**Comment by mattsse** [comment]
in reth
