### ISSUE TITLE
Add rpc trait bindings for optimism specific endpoints

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7540]
### Describe the feature

ref https://docs.optimism.io/builders/node-operators/json-rpc

similar to #7489

**Comment by AbnerZheng** [comment]
I will give it a try.

**Comment by AbnerZheng** [comment]
How about method defined in opp2p namespace?  Are they needed as well?

https://docs.optimism.io/builders/node-operators/json-rpc#opp2p

**Comment by mattsse** [comment]
would be nice to have
