### ISSUE TITLE
eth_callMany RPC not accepting hexstrings for maxFeePerGas and maxPriorityFeePerGas

### ISSUE THREAD

**Issue by dallonby** [paradigmxyz/reth#7542]
### Describe the bug

maxFeePerGas and maxPriorityFeePerGas should permit hexstrings for these values, and used to do in reth until recently.

### Steps to reproduce

`('eth_callMany', [{"transactions":[{"from":"0x0000000000000011110000000000000000000000","to":"0x1100000000000000000000000000000000000000","value":"0x1111111","maxFeePerGas":"0x3a35294400","maxPriorityFeePerGas":"0x3b9aca00"}]},{"blockNumber":"latest"}])`

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.2.0-beta.5 / 283b56c1b

### What database version are you on?

NA

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by dallonby** [comment]
error returned `  response: '{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params","data":"invalid number at line 1 column 156"},"id":5}'`

**Comment by mattsse** [comment]
fixed via #7512

**Comment by dallonby** [comment]
confirmed
