### ISSUE TITLE
Only prune blocks not needed by ExEx's in full sync mode

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#7546]
### Describe the feature

The pruner should check `finished_height` from the manager to determine what blocks are safe to prune if there are any ExEx's installed in the node using `ExExManagerHandle`: https://github.com/paradigmxyz/reth/pull/7340

**Comment by mw2000** [comment]
@onbjerg happy to take this on

**Comment by shekhirin** [comment]
hey @mw2000, we're working on ExEx feature internally now, and given it's a new area of code and still rapidly evolving, I'd prefer to keep this issue for the core team!
