### ISSUE TITLE
Rename `cursor` and `cursor_mut` functions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#755]
### Describe the change

It looks like the `Mut` cursor is for _write_ operations

https://github.com/paradigmxyz/reth/blob/e014eaad339e4b01f6c682614a15c0c0651cc218/crates/storage/db/src/abstraction/transaction.rs#L48-L49

I'd expect that a `cursor_mut` takes a `mut` reference, which is not the case:

https://github.com/paradigmxyz/reth/blob/e014eaad339e4b01f6c682614a15c0c0651cc218/crates/storage/db/src/abstraction/transaction.rs#L56-L57

Perhaps we rename this to `read_cursor`/ `write_cursor` or `cursor_read` / `cursor_write` instead?

**Comment by rakita** [comment]
For me `cursor_read/cursor_write` reads nicer than `mut`

**Comment by entropidelic** [comment]
I can take this 👍

**Comment by gakonst** [comment]
Just to ask the question: does this mean that we should also use tx_read and tx_write? I didn't mind the previous naming so would like to understand that a little better

**Comment by mattsse** [comment]
> tx_read and tx_write 

haven't looked at them but would probably be reasonable as well.

> I didn't mind the previous naming so would like to understand that a little better

the point of confusing for me was, even if there's `cursor_mut` it does not take a mutable reference.
renaming to write|read would mimic some sync primitive APIs like RwLock is more appropriate imo
