### ISSUE TITLE
Add `poll_reserve` to `ExExHandle`

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#7570]
no, we should just add the equivalent fo poll_reserve,

but can also do this separately, so no blocker here

_Originally posted by @mattsse in https://github.com/paradigmxyz/reth/pull/7340#discussion_r1561275928_

**Comment by mw2000** [comment]
I took a first pass at this. From what I understood from your (@onbjerg) and @mattsse conversation, we want to separate the `poll_reserve` logic out into a new function on the `ExExHandle` level that the manager can call. Was a relatively low effort on my end, so let me know if major chunks are missing or if I got the context wrong.

**Comment by shekhirin** [comment]
https://github.com/paradigmxyz/reth/pull/7610#pullrequestreview-2101833227
