### ISSUE TITLE
EVM execution ExEx example

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#7571]
An example of ExEx that call some Uniswap function and records the return value at every height, keeping a running average.

**Comment by AbnerZheng** [comment]
Can I give it a try?

**Comment by shekhirin** [comment]
hey @AbnerZheng, we're working on ExEx feature internally now, and given it's a new area of code and still rapidly evolving, I'd prefer to keep this issue for the core team!

**Comment by AbnerZheng** [comment]
Sure, NP.

**Comment by onbjerg** [comment]
Can we close this w #7994 @shekhirin

**Comment by shekhirin** [comment]
@onbjerg yeah, technically done in https://github.com/paradigmxyz/reth/pull/7826
