### ISSUE TITLE
ExEx metrics panels

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#7572]
### Describe the feature

We added metrics in #7340 and we should add panels for these

https://github.com/paradigmxyz/reth/blob/81090da4937b0fcbabb17ab0ea16781e2aea3315/crates/exex/src/manager.rs#L26-L34

https://github.com/paradigmxyz/reth/blob/81090da4937b0fcbabb17ab0ea16781e2aea3315/crates/exex/src/manager.rs#L118-L130

**Comment by mw2000** [comment]
Would love to take this on

**Comment by onbjerg** [comment]
Cool, thanks @mw2000! Let me know if you get stuck 😄 Do you have a rough timeline?

**Comment by mw2000** [comment]
Ideally this weekend! I'll take a first pass at it in 2-4 hours in case I have more questions

**Comment by mw2000** [comment]
@onbjerg here's a first pass at it -> https://github.com/paradigmxyz/reth/pull/7605

Pretty much used similar panels that we had for blockchain_tree_canonical_chain_height.

A bit green when it comes to grafana dashboards, but I was seeing the following on my end:

<img width="1429" alt="Screenshot 2024-04-12 at 11 27 04 AM" src="https://github.com/paradigmxyz/reth/assets/11898068/d3bfec7c-ebad-4e45-94a8-49d42b01bc82"> 

As opposed to what the blockchain_tree_canonical_chain_
<img width="711" alt="Screenshot 2024-04-12 at 11 27 53 AM" src="https://github.com/paradigmxyz/reth/assets/11898068/f8bbee35-19df-44ac-bd35-80a05ec1278b">
height panel looks like:

Is there a misconfig in the code for the exex panels somewhere? I'll also double check from my side in the meantime

**Comment by onbjerg** [comment]
No, the reason you don't have any data is because you don't have any extensions installed - this is expected. 

It looks fine to me, can you also add panels for the manager metrics?

**Comment by mw2000** [comment]
@onbjerg that sounds good, let me go ahead and do that
