### ISSUE TITLE
gracefully shutdown prometheus server

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7587]
### Describe the feature

this should use graceful shutdown:

https://github.com/paradigmxyz/reth/blob/47d533217c2d4fdeced51a384194ba1562b68c2d/crates/node-core/src/metrics/prometheus_exporter.rs#L70-L73

this function should take a graceful shutdown via the taskspawner that is then used by the hyper server

https://github.com/paradigmxyz/reth/blob/47d533217c2d4fdeced51a384194ba1562b68c2d/crates/node-core/src/metrics/prometheus_exporter.rs#L78-L88

see also: 

https://github.com/paradigmxyz/reth/blob/47d533217c2d4fdeced51a384194ba1562b68c2d/crates/tasks/src/lib.rs#L528-L528

ref:

https://hyper.rs/guides/0.14/server/graceful-shutdown/

**Comment by markovichecha** [comment]
Hey, can I take this one?

**Comment by shekhirin** [comment]
@markovichecha assigned, let me know if you have any questions!

**Comment by rupam-04** [comment]
> @markovichecha assigned, let me know if you have any questions!

Since it looks like anybody isn't working on this issue, I am opening a PR #7728 . Would love to get it reviewed if any changes are required
