### ISSUE TITLE
extract interfaces/p2p to standalone crate under net/p2p

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7598]
### Describe the feature

we want to get rid of the interfaces crate, all p2p logic should be moved to a standalone crate under net/

https://github.com/paradigmxyz/reth/tree/dd28a4ca730f5d213861ab23ca012896c1d19c34/crates/interfaces/src/p2p

should also be moved there:

https://github.com/paradigmxyz/reth/blob/dd28a4ca730f5d213861ab23ca012896c1d19c34/crates/interfaces/src/sync.rs#L8-L8

**Comment by mattsse** [comment]
@supernovahs maybe you want to take this? :)

**Comment by supernovahs** [comment]
thanks , I'll take it

**Comment by wlawt** [comment]
can i take this issue

**Comment by wlawt** [comment]
seems like this issue is resolved? i see the `net/p2p` folder in `main`. should the issue be closed?

**Comment by mattsse** [comment]
thanks!
yeah this can be closed
