### ISSUE TITLE
Add gas limit check when inserting new transactions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#76]
ensure requested gas limit < block.gaslimit:

ref https://github.com/foundry-rs/reth/pull/71#discussion_r995863539

part of #36

**Comment by mattsse** [comment]
awesome, feel free to add this.

I think this should probably take place here

https://github.com/paradigmxyz/reth/blob/e014eaad339e4b01f6c682614a15c0c0651cc218/crates/transaction-pool/src/pool/txpool.rs#L736-L743

**Comment by elprogramadorgt** [comment]
Hi @mattsse, it's ealvarez968, so I think I should add this code

if transaction.gas_limit() < self.block_gas_limit {

    return Err(Error::TransactionGasLimitMoreThenAvailableBlockGas {
            block_gas_limit: self.block_gas_limit,
            gas_limit: transaction.gas_limit,
    })

}
and I think it should be before the current_txs  declaration
