### ISSUE TITLE
ERROR Invalid JWT: provided signature is invalid

### ISSUE THREAD

**Issue by userbox020** [paradigmxyz/reth#7628]
### Describe the bug

getting ERROR Invalid JWT: provided signature is invalid on my excecution layer

### Steps to reproduce

i had running sepolia reth beta5, then i installed mainnet reth node and both of them start to get same error. Both using ./ethd documentation for multiple nodes
https://eth-docker.net/Usage/Advanced#multiple-nodes-on-one-host

### Node logs

```text
ERROR Invalid JWT: provided signature is invalid
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

beta5

### What database version are you on?

db2

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
Does your CL use the same JWT as your EL?

**Comment by userbox020** [comment]
> Does your CL use the same JWT as your EL? Please provide a set of commands/steps we can use to reproduce. I am not familiar with ethd usage at all

Sure Bro, the steps ara basically install full archive sepolia reth+lighthouse node and then 
```
cd ~ && git clone https://github.com/eth-educators/eth-docker.git && cd eth-docker

./ethd install

./ethd config
```
Th

**Comment by userbox020** [comment]
update to beta6 solve the issue
