### ISSUE TITLE
Add a metric for the number of ExEx's on a node

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#7629]
### Describe the feature

Add a metric for the number of ExEx's on a node. This should go into `ExExManagerMetrics`, be a `Gauge` and be set only on creation of the manager, as the number of ExEx's is static over the node's lifetime (if one crashes, the node crashes)

https://github.com/paradigmxyz/reth/blob/4d799673357d69927059854aa2231d34dc4dbe18/crates/exex/src/manager.rs#L121

Additionally there should be a panel (one that just displays a number) for the number of ExEx's in Granfa (see #7572)

**Comment by AbnerZheng** [comment]
I can take it.
