### ISSUE TITLE
Replace `calculate_next_block_base_fee` with alloy's builtin function

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7635]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/d4ea41528a68c851b3d67c2a224cc2b225f65fef/crates/primitives/src/basefee.rs#L26-L26

https://github.com/alloy-rs/alloy/blob/269c0606c0ca7a196f5a92b20c651a4d13ecf5d8/crates/eips/src/eip1559/helpers.rs#L26

https://github.com/alloy-rs/alloy/blob/269c0606c0ca7a196f5a92b20c651a4d13ecf5d8/crates/eips/src/eip1559/basefee.rs#L36

**Comment by rupam-04** [comment]
Can I take this up?

**Comment by AbnerZheng** [comment]
The function in the alloy is using type `u128` for `gas_used` , `gas_limit` etc,  but the comment of the function tell me it is returning `u64` and in reth project, these field are using `u64`. Is there any problem with the function in alloy?

https://github.com/alloy-rs/alloy/blob/269c0606c0ca7a196f5a92b20c651a4d13ecf5d8/crates/eips/src/eip1559/helpers.rs#L22-L31
