### ISSUE TITLE
Getting an error while running the tests

### ISSUE THREAD

**Issue by guha-rahul** [paradigmxyz/reth#7653]
### Describe the bug

I was trying to run the tests using `cargo nextest run` and `cargo test --workspace`and i got these errors.

### Steps to reproduce

1. `git clone https://github.com/paradigmxyz/reth`
2. `cd reth`
3. `cargo nextest run`

### Node logs

```text
error: failed to run custom build command for `reth-mdbx-sys v0.2.0-beta.5 (/home/rahul/reth/crates/storage/libmdbx-rs/mdbx-sys)`

Caused by:
  process didn't exit successfully: `/home/rahul/reth/target/debug/build/reth-mdbx-sys-16e6604ece511e1b/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/home/rahul/reth/crates/storage/libmdbx-rs/mdbx-sys/libmdbx

  --- stderr
  thread 'main' panicked at /home/rahul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.69.4/lib.rs:622:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish..
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

Reth v0.2.0-beta.5

### What database version are you on?

NA

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by shekhirin** [comment]
You need to install the dependencies, see https://paradigmxyz.github.io/reth/installation/source.html#dependencies

**Comment by 0xqd** [comment]
@guha-rahul you should check the .github/workflow or https://github.com/0xqd/earthly-reth. It contains everything you need to do to run reth test suite.

**Comment by guha-rahul** [comment]
thanks @shekhirin , do u think there should be a link the dependencies to install in the readme?
