### ISSUE TITLE
Add OptimismGenesis fields type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7702]
### Describe the feature

Optimism includes additional info in the genesis file.

we don't want to pollute the eth genesis bindings with these, instead we should bundle them in a separate type:

See for example:

https://raw.githubusercontent.com/paradigmxyz/alphanet/331aaea21649e1295d676b73a4ce206bbfbdfe04/crates/testing/resources/etc/genesis.json

This includes OP timestamps + optimism object

This type can be added to node-optimism crate for now

cc @fgimenez

**Comment by andrzejSulkowski** [comment]
It's the first time I will be contributing to this repo and my second time in total so I just would like to clarify quickly...
Steps to tackle this issue are:
1) Identify differences between the genesis file of optimism and eth
2) Extract the differences into a separate type (inside node-optimism crate)

Thank you in advance!

**Comment by fgimenez** [comment]
hey @andrzejSulkowski this task is blocking other areas of work and it is already in progress, sorry for not updating its state. 

pls take a look at other good first issues to work on! https://github.com/paradigmxyz/reth/labels/D-good-first-issue

**Comment by Jrachman** [comment]
temporary solution i put together that programmatically launches the dev node with custom genesis updates: https://github.com/Jrachman/alphanet/blob/main/examples/custom-genesis-dev-node.rs
