### ISSUE TITLE
cargo test: Too many open files

### ISSUE THREAD

**Issue by igor-ritual** [paradigmxyz/reth#7706]
### Describe the bug

`tests::etl_hashes` fails with too many open files.

### Steps to reproduce

```
% git log -1
commit 493f41a12607a1d3d11d11692d6e30dea0b03e5f (HEAD -> main, origin/main, origin/HEAD)
Author: Matthias Seitz <matthias.seitz@outlook.de>
Date:   Tue Apr 16 17:03:01 2024 +0200

% cargo test --workspace
...
running 1 test
test tests::etl_hashes ... FAILED

failures:

---- tests::etl_hashes stdout ----
thread 'tests::etl_hashes' panicked at crates/etl/src/lib.rs:287:36:
called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: PathError { path: "/var/folders/ss/5qyjb9fs00ggls9bc9tnfw8h0000gn/T/.tmpUDtIzU/.tmpjLFRpl", err: Os { code: 24, kind: Uncategorized, message: "Too many open files" } } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

commit 493f41a12607a1d3d11d11692d6e30dea0b03e5f (HEAD -> main, origin/main, origin/HEAD)

### What database version are you on?

commit 493f41a12607a1d3d11d11692d6e30dea0b03e5f (HEAD -> main, origin/main, origin/HEAD)

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
What is your limit on file handles? You can check with

```bash
sysctl kern.maxfiles
sysctl kern.maxfilesperproc
```

and you can also increase it via 

```bash
# max global file handles
sysctl -w kern.maxfiles=20480
# max file handles per process
sysctl -w kern.maxfilesperproc=18000
```

Note that this is not permanent

Unfortunately it's not immediately obvious if this is because you have too many file handles open in general (due to other processes also having a large number of file handles open) or not, but it is likely the case

**Comment by onbjerg** [comment]
Closing pre-emptively as this is likely not something in our test suite seeing as the tests are runnable locally on both Linux, macOS, and in GitHub actions. Let me know if there are developments, though
