### ISSUE TITLE
Can't build from source on Windows at latest

### ISSUE THREAD

**Issue by ejmahler** [paradigmxyz/reth#7711]
### Describe the bug

I'm trying to run `cargo check` on Windows. 

At commit 0ff3b0e3afcd319057cf7df80c510bcc65766234 the compile fails with the following error:

```
    Checking reth-rpc-builder v0.2.0-beta.5 (D:\Documents\GitHub\reth\crates\rpc\rpc-builder)
error[E0432]: unresolved import `reth_ipc::client`
  --> crates\rpc\rpc-builder\src\auth.rs:16:15
   |
16 | use reth_ipc::client::IpcClientBuilder;
   |               ^^^^^^ could not find `client` in `reth_ipc`
   |
note: found an item that was configured out
  --> D:\Documents\GitHub\reth\crates\rpc\ipc\src\lib.rs:16:9
   |
16 | pub mod client;
   |         ^^^^^^

````

If I revert to the [v0.2.0-beta.5 commit](https://github.com/paradigmxyz/reth/tree/54f75cdcc82125a97ffd82952c2a8bc8ed324b48), `cargo check` completes without error:.

### Steps to reproduce

cargo check at latest on windows

### Platform(s)

Windows (x86)

### What version/commit are you on?

0ff3b0e3afcd319057cf7df80c510bcc65766234

### What database version are you on?

n/a

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

cargo check

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
Sorry about that!

Fixed here: https://github.com/paradigmxyz/reth/pull/7712
