### ISSUE TITLE
Add example for BSC p2p 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7738]
### Describe the feature

It'd be nice to have a manual p2p example for bsc

## TODO
* add BSC chain chain spec: https://github.com/bnb-chain/bsc/blob/master/params/config.go

Add an example, very similar to the polygon example:

https://github.com/paradigmxyz/reth/blob/1c46e5ae7d21a0696bc299fefc172d5a6cb993f6/examples/polygon-p2p/src/main.rs#L32-L32

https://github.com/paradigmxyz/reth/blob/1c46e5ae7d21a0696bc299fefc172d5a6cb993f6/examples/polygon-p2p/src/chain_cfg.rs#L10-L10

**Comment by Quertyy** [comment]
Can I take this one?

**Comment by mattsse** [comment]
assigned

would be great if we could connect and get some txs we can print or something

**Comment by onbjerg** [comment]
Hey @Quertyy, what's the status on this? Feel free to open a draft PR if you get stuck/need feedback on the direction 😄
