### ISSUE TITLE
Block gas used mismatch on bad_block = 18832982

### ISSUE THREAD

**Issue by itsPinkDev** [paradigmxyz/reth#7782]
### Describe the bug

While setting up a mainnet node, during pipeline_stages 4/12 it reached over 99%, then it crashed.
Since I restarted the node it always resyncs stages 2/12 and 3/12 (starting from a stage_progress around 95%) and after it finishes both stages it goes to 4/12 where it encounters the block gas used mismatch error. From there it goes back to resyncing stage 2 & 3/12.

### Steps to reproduce

Simply run the command
`RUST_LOG=info reth node --full     --authrpc.jwtsecret jwt.hex     --authrpc.addr 127.0.0.1     --authrpc.port 8551`
while running a lighthouse consensus client.

### Node logs

```text
Stage encountered an execution error: block gas used mismatch: got 29989737, expected 29984937; gas spent by each transaction: [(0, 9795804), (1, 11127189), (2, 11245360), (3, 11365148), (4, 11495947), (5, 11608397), (6, 11629397), (7, 11831281), (8, 11940853), (9, 12205392), (10, 12324883), (11, 12586204), (12, 13539234), (13, 13683822), (14, 14375615), (15, 14424140), (16, 14651396), (17, 14867930), (18, 14929394), (19, 14973735), (20, 15018076), (21, 15062417), (22, 15106758), (23, 15151099), (24, 15214308), (25, 15396949), (26, 15464800), (27, 15703685), (28, 15845539), (29, 15895951), (30, 16055735), (31, 16225060), (32, 16334062), (33, 16519353), (34, 16744065), (35, 17254282), (36, 17327895), (37, 17424229), (38, 17497852), (39, 17518852), (40, 17539852), (41, 17560852), (42, 17581852), (43, 17602852), (44, 17623852), (45, 17644852), (46, 17665852), (47, 17686852), (48, 17707852), (49, 17792060), (50, 17947093), (51, 18077814), (52, 18123923), (53, 18187132), (54, 18250341), (55, 18315978), (56, 18379150), (57, 18431534), (58, 18483429), (59, 18504429), (60, 18567626), (61, 18633251), (62, 18654251), (63, 18675251), (64, 18724088), (65, 18776376), (66, 18822485), (67, 18866849), (68, 18901655), (69, 18922655), (70, 18943655), (71, 18964655), (72, 19027334), (73, 19089612), (74, 19209414), (75, 19230414), (76, 19251414), (77, 19947400), (78, 20013025), (79, 20076234), (80, 20102877), (81, 20132905), (82, 20201383), (83, 20269869), (84, 20339198), (85, 20514016), (86, 20555325), (87, 20735083), (88, 20778808), (89, 20822545), (90, 20866282), (91, 20912262), (92, 20958467), (93, 21004947), (94, 21051467), (95, 21098330), (96, 21145382), (97, 21192534), (98, 21396273), (99, 21444822), (100, 21496603), (101, 21542756), (102, 21650023), (103, 21757290), (104, 21865166), (105, 21919133), (106, 21979970), (107, 22028867), (108, 22087276), (109, 22150485), (110, 22213706), (111, 22281227), (112, 22349703), (113, 22419022), (114, 22488351), (115, 22559528), (116, 22704564), (117, 22781480), (118, 22859103), (119, 22938349), (120, 22999186), (121, 23093909), (122, 23515403), (123, 23601409), (124, 23622665), (125, 23730541), (126, 23752693), (127, 23893397), (128, 23944003), (129, 24070044), (130, 24133265), (131, 24259846), (132, 24389299), (133, 24520575), (134, 24652608), (135, 24679251), (136, 24731105), (137, 24777214), (138, 24823335), (139, 25108502), (140, 25160447), (141, 25310023), (142, 25470679), (143, 25637716), (144, 25818045), (145, 25984247), (146, 26168806), (147, 26216001), (148, 26405723), (149, 26606590), (150, 26825845), (151, 27017655), (152, 27064946), (153, 27094378), (154, 27123984), (155, 27153617), (156, 27183250), (157, 27212883), (158, 27242516), (159, 27272149), (160, 27301795), (161, 27331460), (162, 27361125), (163, 27390812), (164, 27420499), (165, 27450193), (166, 27479892), (167, 27509591), (168, 27539300), (169, 27569018), (170, 27598746), (171, 27628556), (172, 27658412), (173, 27688293), (174, 27718229), (175, 27749072), (176, 27841446), (177, 27873618), (178, 27906084), (179, 28236627), (180, 28271214), (181, 28306266), (182, 28342656), (183, 28708128), (184, 29073612), (185, 29116705), (186, 29145924), (187, 29176352), (188, 29222716), (189, 29269223), (190, 29315768), (191, 29362319), (192, 29409058), (193, 29455797), (194, 29617546), (195, 29780102), (196, 29828910), (197, 29877807), (198, 29926704), (199, 29947704), (200, 29968704), (201, 29989737)] stage=Execution bad_block=18832982
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.2.0-beta.4
87c4ae744

### What database version are you on?

2

### What type of node are you running?

Full via --full flag

### If you've built Reth from source, provide the full command you used

RUST_LOG=info reth node --full     --authrpc.jwtsecret jwt.hex     --authrpc.addr 127.0.0.1     --authrpc.port 8551

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
Was this node synced from scratch? I.e. no upgrades in between syncing?

**Comment by itsPinkDev** [comment]
> Was this node synced from scratch? I.e. no upgrades in between syncing?

I started it from scratch but it crashed like 2 times during stage 4, whereby I restarted the process with the same command.

**Comment by onbjerg** [comment]
Did it initially crash because of the above error, or for another reason?

**Comment by itsPinkDev** [comment]
It initially crashed because of another error. I don't think I saved it as I thought this expected in Beta. But it ultimately just said something simple like Killed without much more Info I think, but then it continued without any problem.

**Comment by onbjerg** [comment]
Can you post the specs of your machine? I'm trying to narrow this down to if maybe the process ran out of memory, was killed, and then we ended up in an inconsistent state

**Comment by rkrasiuk** [comment]
@itsPinkDev could you also post your debug logs pls? default location on linux is `~/.cache/reth/logs`

**Comment by itsPinkDev** [comment]
@rkrasiuk Will do that in a few hours!
Thanks

**Comment by itsPinkDev** [comment]
[reth_log_1.zip](https://github.com/paradigmxyz/reth/files/15065054/reth_log_1.zip)
[reth_log_2.zip](https://github.com/paradigmxyz/reth/files/15065055/reth_log_2.zip)
[reth_log_3.zip](https://github.com/paradigmxyz/reth/files/15065056/reth_log_3.zip)
[reth_log_4.zip](https://github.com/paradigmxyz/reth/files/15065057/reth_log_4.zip)
[reth_log_5.zip](https://github.com/paradigmxyz/reth/files/15065058/reth_log_5.zip)

**Comment by VersoriumX** [comment]
I dont recall a crash! Something to that end!

**Comment by VersoriumX** [comment]
My linode was breached and blah

**Comment by itsPinkDev** [comment]
@VersoriumX I'm sorry, I don't understand your comments ^^

**Comment by VersoriumX** [comment]
Vx

**Comment by VersoriumX** [comment]
@VersoriumX squash and merge
