### ISSUE TITLE
`trace_call`/`trace_callMany` report different values for `gas`, `gasUsed`, and `balance` compared to reference Erigon node

### ISSUE THREAD

**Issue by Robert-MacWha** [paradigmxyz/reth#7785]
### Describe the bug

I noticed that Reth sometimes reports different values for the `gas`, `gasUsed`, and `balance` fields returned by `trace_call` and `trace_callMany` compared to a reference Quicknode endpoint.

Lesser importance, but I've also noticed that Reth often returns the trace for `trace_call` / `trace_callMany` non-sequentially for transactions where a contract was created and destroyed within the same call.

Using the trace from `0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65` for example, the two actions are right beside each other despite there being several trace actions between them in the actual trace.  Since the `traceAddress` field is correct and, as far as I can tell, a parent trace is never present before its child, this isn't that large a concern.  Just curious if it's intentional.
```json
    {
        "action": {
            "from": "0x54b5ae5ebe86d2d86134f3bb7e36e7c83295cbcb",
            "gas": "0xa85b45",
            "init": "0x60806040526040516109b33803806109b38339...",
            "value": "0xd2106d815ebeac00000"
        },
        "result": {
            "address": "0x9381fb80871bce0c10e730185c608e4fe7940dc4",
            "code": "0x",
            "gasUsed": "0x1815f6"
        },
        "subtraces": 15,
        "traceAddress": [
            0,
            0,
            3,
            2
        ],
        "type": "create"
    },
    {
        "action": {
            "address": "0x9381fb80871bce0c10e730185c608e4fe7940dc4",
            "balance": "0xd2106d815ebeac00000",
            "refundAddress": "0x54b5ae5ebe86d2d86134f3bb7e36e7c83295cbcb"
        },
        "result": null,
        "subtraces": 0,
        "traceAddress": [
            0,
            0,
            3,
            2,
            14
        ],
        "type": "suicide"
    },
```

### Steps to reproduce

Running the below python script for Reth and an Erigon (in my case quicknode) node for the following transactions produces examples of the buggy behaviour. Attached are also a few example scripts I ran and the differences between the JSON files produced by Reth and Quicknode.

**Example Files**
 - `0xe7ac8d56645a72615ace7cbbd696ae46523b1e842008439636736d11b0f4e3b1` - simpler example, shows different `gas` and `gasUsed`
   - [quicknode_0xe7ac8d56645a72615ace7cbbd696ae46523b1e842008439636736d11b0f4e3b1.json](https://github.com/paradigmxyz/reth/files/15057204/quicknode_0xe7ac8d56645a72615ace7cbbd696ae46523b1e842008439636736d11b0f4e3b1.json)
   - [reth_0xe7ac8d56645a72615ace7cbbd696ae46523b1e842008439636736d11b0f4e3b1.json](https://github.com/paradigmxyz/reth/files/15057206/reth_0xe7ac8d56645a72615ace7cbbd696ae46523b1e842008439636736d11b0f4e3b1.json)

```bash
$ diff reth_0xe7ac8d56645a72615ace7cbbd696ae46523b1e842008439636736d11b0f4e3b1.json quicknode_0xe7ac8d56645a72615ace7cbbd696ae46523b1e842008439636736d11b0f4e3b1.json
6c6
<             "gas": "0x33307",
---
>             "gas": "0x2dc9b",
12c12
<             "gasUsed": "0x25178",
---
>             "gasUsed": "0x253b8",
```

 - `0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65` - full example including `gas` miss-match.
   - [quicknode_0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65.json](https://github.com/paradigmxyz/reth/files/15057176/quicknode_0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65.json)
   - [reth_0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65.json](https://github.com/paradigmxyz/reth/files/15057178/reth_0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65.json)

```bash
$ diff reth_0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65.json quicknode_0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65.json
6c6
<             "gas": "0xb71b00",
---
>             "gas": "0xb6c838",
12c12
<             "gasUsed": "0x58ce26",
---
>             "gasUsed": "0x78b55e",
3655c3655
<             "balance": "0x0",
---
>             "balance": "0xc40dd33b3a1d71f422",
3673c3673
<             "balance": "0xd2106d815ebeac00000",
---
>             "balance": "0xd25b3d000079ba216dc",
7057c7057
<             "balance": "0x0",
---
>             "balance": "0xc2aa529d97a198ed4d",
7075c7075
<             "balance": "0xd2106d815ebeac00000",
---
>             "balance": "0xd248f59a9dda300ef0d",
10459c10459
<             "balance": "0x0",
---
>             "balance": "0xc18c9d199d28e2029e",
10477c10477
<             "balance": "0xd2106d815ebeac00000",
---
>             "balance": "0xd237831a781bdf087d3",
13861c13861
<             "balance": "0x0",
---
>             "balance": "0xc08b17ceabc4cb3b52",
13879c13879
<             "balance": "0xd2106d815ebeac00000",
---
>             "balance": "0xd227c563ff117e2ba23",
17263c17263
<             "balance": "0x0",
---
>             "balance": "0xbfa684d10ecf7ee87c",
17281c17281
<             "balance": "0xd2106d815ebeac00000",
---
>             "balance": "0xd219c930d29a4f16d88",
```

**Replication Script**
```python
from web3 import Web3
import json
from functools import cmp_to_key

def compare_traces(trace1, trace2):
    addr1 = trace1['traceAddress']
    addr2 = trace2['traceAddress']

    min_len = min(len(addr1), len(addr2))
    for i in range(min_len):
        if addr1[i] != addr2[i]:
            return -1 if addr1[i] < addr2[i] else 1
        
    return -1 if len(addr1) < len(addr2) else 1

def get_call_trace(web3, tx_hash):
    transaction = web3.eth.get_transaction(tx_hash)
    if transaction is None:
        raise ValueError("Transaction not found")

    tx_body = {
        'from': transaction['from'],
        'to': transaction['to'],
        'data': transaction['input'].hex(),
        'value': hex(int(transaction['value'])),
        'gas': hex(int(transaction['gas'])),
        'gasPrice': hex(int(transaction.get('gasPrice', 0))),
    }

    blockHex = hex(int(transaction['blockNumber']) - 1)
    trace = web3.provider.make_request('trace_call', [tx_body, ['trace'], blockHex])
    return trace

node_url = 'http://192.168.2.212:8545'
web3 = Web3(Web3.HTTPProvider(node_url))
tx_hash = '0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65'

call_trace = get_call_trace(web3, tx_hash)

trace = call_trace['result']['trace']
# sorting because of the above-mentioned sequentiality issue. Lets us focus on the actual differences.
trace = sorted(trace, key=cmp_to_key(compare_traces))

s  = json.dumps(trace, indent=4, sort_keys=True)
print(s)
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

Replicated on both Reth version beta.4 and beta.5

### What database version are you on?

database version: 2

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Robert-MacWha** [comment]
This might have something to do with https://github.com/paradigmxyz/reth/issues/4262?  Noticed similar issues, but felt since the other one's been closed & is of lesser scope it was worthwhile opening something new.

**Comment by Robert-MacWha** [comment]
I didn't realize this, but it looks like all of the balance fields are wrong.

**Comment by mattsse** [comment]
could you please attach the json request object for this?

**Comment by Robert-MacWha** [comment]
Taking another look at the gas difference for https://etherscan.io/tx/0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65.

Reth reports `"gas"` correctly - it's the same value as is in the `"trace_call"` request I made.  However, I'm fairly sure the reported `"gasUsed"` is incorrect.  The `"gasUsed"` by a trace should always be larger than the `"gasUsed"` by that call's sub-traces, right?  See below, this isn't the case.

Interestingly, Reth reports the same value for `"gasUsed"` as Etherscan does (5,819,942).  This value comes from the `"trace_transaction"` endpoint instead of `"trace_call"`.  Since this transaction has already happened, is it perhaps getting the `"gasUsed"` from the database?

```js
// snippet from 0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65_request.json/
// parent's gasUsed > child's gasUsed
    {
        "result": {
            "gasUsed": "0x78b55e",
            "output": "0x"
        },
        "traceAddress": [],
    },
    {
        "result": {
            "gasUsed": "0x789365",
            "output": "0x"
        },
        "traceAddress": [
            0
        ],
    },
```

**Comment by nateless** [comment]
Hello guys,

Any updates on this task?

**Comment by mattsse** [comment]
what specifically?

gasUsed of the top call returns the gasUsed of the transaction, this can be lower due to refunds etc..

**Comment by Robert-MacWha** [comment]
As of reth `0.2.0-beta.9` the issue is still present.  I haven't gotten around to updating to the 1.0 release candidates, so can't confirm behaviour.  Running the replication script for both the above transactions produces the same file diff between Reth and Quicknode as on beta 0.5.

**Comment by mattsse** [comment]
>  the issue is still present

which one specifically?

**Comment by mattsse** [comment]
what's not working when running in a docker container?
please open another issue for this, because unrelated

**Comment by Robert-MacWha** [comment]
Oh sorry,

To clarify, "the issue" I was referencing was the differing gas and balance bug.  I was just outlining that it hadn't been fixed or changed in the new versions of Reth.  I have no reason to believe that anything within the docker container is broken or causing problems.

**Comment by Robert-MacWha** [comment]
> gasUsed of the top call returns the gasUsed of the transaction, this can be lower due to refunds etc

Regardless, shouldn't this be the same across different execution clients?  I'm not familiar with when gas refunds are applied, but I thought it was in the subcall where the refund was issued?

**Comment by mattsse** [comment]
> Regardless, shouldn't this be the same across different execution clients

there's no spec for these calls

> Interestingly, Reth reports the same value for "gasUsed" as Etherscan (5,819,942).

we chose to return the gasUsed by tx here

**Comment by Robert-MacWha** [comment]
> we chose to return the gasUsed by tx here

I take it reth does the same for the "value" field?

Are you saying that, for transactions that have already been executed on-chain, `trace_replayTransaction` and `trace_call` will return the same result?  That also doesn't seem to be the case, since if I re-run transaction `0xc71cea6fa00d11e98f6733ee8740f239cb37b11dec29e7cf85d7a4077977fa65` on Reth, comparing the diff for `trace_replayTransaction` vs `trace_call` I get yet another result:
```js
$ diff call.json replay.json
1878c1878
<             "output": "0x000000000000000000000000000000000000000000468020d9ba07c8c8ce3299"
---
>             "output": "0x00000000000000000000000000000000000000000046802091b8e663fe79e184"
3235c3235
<             "output": "0x000000000000000000000000000000000000000000468020d9ba07c8c8ce3299"
---
>             "output": "0x00000000000000000000000000000000000000000046802091b8e663fe79e184"
5280c5280
<             "output": "0x000000000000000000000000000000000000000000468020d9ba07c8c8ce3299"
---
>             "output": "0x00000000000000000000000000000000000000000046802091b8e663fe79e184"
6637c6637
<             "output": "0x000000000000000000000000000000000000000000468020d9ba07c8c8ce3299"
---
>             "output": "0x00000000000000000000000000000000000000000046802091b8e663fe79e184"
8682c8682
<             "output": "0x000000000000000000000000000000000000000000468020d9ba07c8c8ce3299"
---
>             "output": "0x00000000000000000000000000000000000000000046802091b8e663fe79e184"
10039c10039
<             "output": "0x000000000000000000000000000000000000000000468020d9ba07c8c8ce3299"
---
>             "output": "0x00000000000000000000000000000000000000000046802091b8e663fe79e184"
12084c12084
<             "output": "0x000000000000000000000000000000000000000000468020d9ba07c8c8ce3299"
---
>             "output": "0x00000000000000000000000000000000000000000046802091b8e663fe79e184"
13441c13441
<             "output": "0x000000000000000000000000000000000000000000468020d9ba07c8c8ce3299"
---
>             "output": "0x00000000000000000000000000000000000000000046802091b8e663fe79e184"
15486c15486
<             "output": "0x000000000000000000000000000000000000000000468020d9ba07c8c8ce3299"
---
>             "output": "0x00000000000000000000000000000000000000000046802091b8e663fe79e184"
16843c16843
<             "output": "0x000000000000000000000000000000000000000000468020d9ba07c8c8ce3299"
---
>             "output": "0x00000000000000000000000000000000000000000046802091b8e663fe79e184"
```

In this instance the outputs from `trace_call` are different from the apparent on-chain state according to Etherscan.

**Comment by mattsse** [comment]
> I take it reth does the same for the "value" field?

the value of the top level call should be the tx.value, right?

and trace_call and trace_replacetx are entirely different

**Comment by Robert-MacWha** [comment]
I'm not sure why, but as of reth v1.0.1 parity seems to have been mostly restored between reth and erigon's outputs.

I'll close the issue since my problem is now solved, but I don't know whether the problem is 100% completed or whether it's just fixed for my use case.
