### ISSUE TITLE
replace OP error variant with a general purpose error

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7825]
### Describe the feature

This 
https://github.com/paradigmxyz/reth/blob/ce1e401d217215dfdbe6c9de6b87efadf9f804e6/crates/rpc/rpc-engine-api/src/error.rs#L89-L93

needs to be replaced with a general purpose error variant, just like:

https://github.com/paradigmxyz/reth/blob/ce1e401d217215dfdbe6c9de6b87efadf9f804e6/crates/rpc/rpc/src/eth/error.rs#L121-L123

we already have a trait for this:

https://github.com/paradigmxyz/reth/blob/ce1e401d217215dfdbe6c9de6b87efadf9f804e6/crates/rpc/rpc/src/eth/error.rs#L20-L24

## TODO
* move trait to rpc-types
* replace op error variant with `Other`
* the OP error variant appears to be unused so this variant can be removed entirely

**Comment by lakshya-sky** [comment]
can I take this one?

**Comment by mattsse** [comment]
assigned
