### ISSUE TITLE
Expose bandwidth metering metrics

### ISSUE THREAD

**Issue by akirillo** [paradigmxyz/reth#783]
### Describe the feature

#707 introduced a `BandwidthMeter` struct that measures the total inbound / outbound bandwidth through a `AsyncRead` and/or `AsyncWrite` stream, which is getting used to wrap streams with peers.

We now have to expose the values measured by this struct as metrics via the `metrics` or `metrics-derive` crate.

**Comment by akirillo** [comment]
have begun working on this, will put up a draft PR soon.

@mattsse [here](https://github.com/paradigmxyz/reth/issues/570#issuecomment-1371449513) you mention that the metric should be a `Gauge` representing a rate of throughput that we update ourselves on a given interval.

what if instead, we just use a `Counter` that we increment/set at the same time as the underlying `BandwidthMeter`, and leave the calculation of a rate to Grafana, as we do with headers (i.e. the headers/s metric in the default grafana dash)?

we could do this by wrapping `MeteredStream` in another type that makes use of actual metrics, and implement `AsyncRead` and `AsyncWrite` for this type to increment the `Counter`s it holds and then call `MeteredStream::poll_read` / `MeteredStream::poll_write` accordingly

lmk if this makes sense

**Comment by onbjerg** [comment]
I am partial to letting Prometheus or Grafana calculate the rates. I think that is a better solution because it allows users to specify their own granularity.

**Comment by akirillo** [comment]
I know we just had some great work done in #785 to allow for dynamic scope setting - and we should keep it - but I think in this case, it's a better fit to make use of [metric labels](https://docs.rs/metrics/latest/metrics/struct.Label.html) for e.g. labeling the different session IDs of the streams we're metering.

May open a separate issue for enabling this through `metrics-derive`

**Comment by mattsse** [comment]
> I am partial to letting Prometheus or Grafana calculate the rates. I think that is a better solution because it allows users to specify their own granularity.

this makes sense, but throughput metrics are tool dependent then.
but perhaps not worth it to add our own throughput metrics?

**Comment by akirillo** [comment]
> this makes sense, but throughput metrics are tool dependent then.
> 
> but perhaps not worth it to add our own throughput metrics?

That's my thinking, unless we want to reference throughput metrics in code, e.g. for disconnecting low-throughout peers

**Comment by akirillo** [comment]
> reference throughput metrics in code
Mm yeah, especially as I think about #908, I think we want this - so I'm leaning towards exposing both a `Counter` as we do now (for throughput to be calculated by downstream tools) and also a custom `Gauge` for throughput that can be referenced in code

**Comment by akirillo** [comment]
@mattsse @onbjerg Per our sync today, it sounds like we want:
1. Total ingress / egress (# bytes) per stream, which #844 will accomplish
2. Throughput of messages per second per stream, which #726 can be used for

Regarding point 1, however: I'm not sure where we'll use total ingress / outgress in the code. My current plan for disconnecting slow peers (#908) doesn't involve this, it would only use latency (RTT) and throughput (messages/s). The code is already written, but if we aren't going to reference total ingress / egress in-process, should we just increment a metric instead of tracking the values themselves in a struct?

**Comment by onbjerg** [comment]
Still relevant @mattsse?

**Comment by mattsse** [comment]
Now that we have more feedback from running the downloader on networks with different speeds, it turns out that this is not a problem at all.
And we don't really need to disconnect slowest peers. By and large, downloaders are pretty small, so it's not really worth the effort
