### ISSUE TITLE
More granular sync info RPC method

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#7838]
### Describe the feature

We should add an endpoint to get more granular syncing info from Reth. It should return:

- The current checkpoint of each stage in an ordered array of `{ stage, checkpoint }`
- The current target, e.g. just the latest FCU

**Comment by onbjerg** [comment]
cc @mattsse unsure if we should just stuff this into the `reth_` namespace

**Comment by mattsse** [comment]
we should but this under reth_ namespace

we need a few things first
1. rpc types
2. rpc module variant
3. then a handler implementation that monitors engine events

**Comment by kunal365roy** [comment]
Hey @mattsse, I'd love to take a stab at this!

**Comment by loocapro** [comment]
Can I take this?

**Comment by mattsse** [comment]
completed via #10042
