### ISSUE TITLE
Rename some examples

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#7863]
### Describe the feature

The following examples have misleading names:

- [ ] `custom-node` only deals with custom engine types, so it should probably be named `custom-engine-types`
- [ ] `cli-extension-event-hooks` demonstrates lifecycle event hooks in node builder, so it should probably be named `node-event-hooks`
- [ ] `trace-transaction-cli` traces tx's in mempool as they come in, so it should probably be named `txpool-tracing`
- [ ] `additional-rpc-namespace-in-cli` spins up a custom RPC namespace with node builder, so it should probably be named `node-custom-rpc`

Remember to update the README in `examples/README.md` to link to the new examples

**Comment by andrzejSulkowski** [comment]
I can work on this
