### ISSUE TITLE
Replace TransactionKind with alloy_primitives::TxKind

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7871]
### Describe the feature

replace

https://github.com/paradigmxyz/reth/blob/c7008deef8d7a86706673c25255cab795e6e3108/crates/rpc/rpc-types/src/eth/transaction/typed.rs#L121-L125

with alloy_primitives::TxKind

cc @rodrigoherrerai 

### Additional context

#7859

**Comment by andrzejSulkowski** [comment]
Can I do this one?
