### ISSUE TITLE
Add bidirectional function around `v` signature calculations

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#7893]
### Describe the feature

As per https://github.com/paradigmxyz/reth/pull/7882#discussion_r1579753322, in the repo, we need to make calculations around `v` in `Signature` in both directions:

https://github.com/paradigmxyz/reth/blob/f6e1b0640cea24ed17efe2d4c09ceb591d6fa7cf/crates/primitives/src/transaction/signature.rs#L80-L95 

and in the other direction for the conversion included in https://github.com/paradigmxyz/reth/pull/7882

As a result, this would make sense to unify that into a standalone method to wrap this bidirectional conversion.

**Comment by Rjected** [comment]
> As a result, this would make sense to unify that into a standalone method to wrap this bidirectional conversion.

We probably just need to implement the method that does the inverse of `v`, there is code in `decode_eip155_chain_id` that should already work and is efficient, so we would want to extract that into a method more or less
