### ISSUE TITLE
feature gate rpc-types import for alloy conversions

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7906]
requires https://github.com/alloy-rs/alloy/issues/633

likely more

## TODO
only re-export types from alloy-eips, like BlockId etc...

feature gate alloy rpc type conversions

**Comment by andrzejSulkowski** [comment]
I can take this one but I'd need further information.

- Where should I re-export the types in our repo (as alloy-eips is a separate library)?
- Feature Gate means to include a feature like `#![cfg(feature = "optimism")]`?
- Is the feature name "alloy-rpc-conversion" suitable?

**Comment by mattsse** [comment]
> Where should I re-export the types in our repo (as alloy-eips is a separate library)?

this is already the case, for example: 

https://github.com/paradigmxyz/reth/blob/1f6753b84a3ea3f75a6bcb9134e03f7b286ea130/crates/primitives/src/withdrawal.rs#L7-L9

this issue mainly concerns these conversions:

https://github.com/paradigmxyz/reth/blob/1f6753b84a3ea3f75a6bcb9134e03f7b286ea130/crates/primitives/src/block.rs#L151-L151

it looks like this issue is blocked by https://github.com/paradigmxyz/reth/issues/7928 and #7929

but we could already introduce the alloy-compat feature for the tryfrom conversions

**Comment by andrzejSulkowski** [comment]
will be done
