### ISSUE TITLE
extract peer types to net/types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7907]
we should move the peer types defined in:

https://github.com/paradigmxyz/reth/blob/57d09e84beaa4dafa505461db733d672163e4d99/crates/primitives/src/peer.rs#L5-L5

these are network specific and we can move them to a standalone crate like `reth-network-types` or into the common crate: https://github.com/paradigmxyz/reth/blob/57d09e84beaa4dafa505461db733d672163e4d99/crates/net/common/Cargo.toml#L2-L2

but a standalone crate sounds cleaner

**Comment by andrzejSulkowski** [comment]
I can work on this one
