### ISSUE TITLE
Support for multiple devp2p capabilities

### ISSUE THREAD

**Issue by akirillo** [paradigmxyz/reth#791]
### Describe the feature

The current implementation of p2p streams only supports a single capability, because we only support `eth` and are compatible with both `eth/66` and `eth/67`.

We should implement support for multiple capabilities using [message ID multiplexing](https://github.com/ethereum/devp2p/blob/master/rlpx.md#message-id-based-multiplexing).

### Additional context

We already have some of the logic for message ID multiplexing via the calculation of message ID offsets, but we can't yet fully support multiple capabilities. Currently, the `EthStream` directly wraps the `P2PStream`, assumes `eth` is the only supported capability and just subtracts the offset for every message in the stream before decoding.

To support multiple capabilities we'd need to create a new Stream type (which might need to implement `Future` or something similar) to go on top of `P2PStream`, containing its capability.

The `P2PStream` would still send pings and handle pongs, but now contain a map of capabilities to their respective stream / channel. It would determine the intended capability (based on the shared capabilities / offsets), and send the message to that capabilities' stream. Each stream would be responsible for containing the offset for that stream and would only increment / decrement message IDs.

**Comment by mridullpandey** [comment]
Hello @akirillo Sir, Is this done!
If not I would love to take this

**Comment by akirillo** [comment]
> Hello @akirillo Sir, Is this done!
> 
> If not I would love to take this

Hi hi @mridullpandey, nope not done, I'm handling #908 right now so feel free to take this!

**Comment by gakonst** [comment]
@mridullpandey let us know if you'll have some capacity on this; else can unassign^^

**Comment by anukul** [comment]
Hi! I'd like to try this issue, if available.

**Comment by gakonst** [comment]
@mridullpandey do you intend to take this? else we can give to @anukul!

**Comment by mridullpandey** [comment]
Yes for now i'm working on other issue so we can give it to @anukul

**Comment by bharath-123** [comment]
hey @anukul are you still on this?

**Comment by bharath-123** [comment]
would love to take it up if not

**Comment by anukul** [comment]
hey @bharath-123 i haven't gotten around to finishing this one, go for it.

**Comment by bharath-123** [comment]
Thanks for assigning @gakonst ! Will take a look at this

**Comment by onbjerg** [comment]
Still relevant @mattsse @Rjected?

**Comment by gakonst** [comment]
Yes we don't have support for eg adding snap or les.
