### ISSUE TITLE
Write pruning config to `reth.toml` when `--full` is specified

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#7923]
### Describe the feature

Currently when you sync with `--full`, and then run `reth node` without `--full` (usually by mistake), everything will seem to run normally until the pipeline fails with `stage is missing static file data` during execution. Stage commands, lacking a `--full` option, often also fail.

We should instead use the pruning config, if it exists, in `reth.toml`. We should also write to this when the user specifies `--full`. This way, the stage commands do not need a `--full` argument, since they should also read from the reth config.

We could also warn the user if they attempt to run without `--full`, but have an existing pruning config, that this is a full node

**Comment by lakshya-sky** [comment]
can I take this one?

**Comment by mattsse** [comment]
yes

the ideal place to do this would be here:

https://github.com/paradigmxyz/reth/blob/ffa36b7348b2e5f4bdb09804961eda597131b91d/crates/node-builder/src/launch/common.rs#L66-L67

what we need here is also updating the toml file with the prune info
