### ISSUE TITLE
move NodeRecord type to net/types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7928]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/cc4a418ddf73ae5af240b403e4b6e1d191130cee/crates/rpc/rpc-types/src/net.rs#L44-L44

should be part of `net/types`

### Additional context

blocked by #7929 which needs to happen first

**Comment by rodrigoherrerai** [comment]
I can take it :)

**Comment by rodrigoherrerai** [comment]
I can take it

**Comment by mattsse** [comment]
cool, first we need to do #7929
