### ISSUE TITLE
Base Reth node is not syncing

### ISSUE THREAD

**Issue by tofanovskiy** [paradigmxyz/reth#7950]
### Describe the bug

I am trying to launch Base mainnet node following your guide.

After a week of node running - it synced only 12000 blocks. What am I doing wrong? 

Logs:
```
024-04-28T18:36:59.022057Z DEBUG jsonrpsee-server: Accepting new connection 1/500
2024-04-28T18:36:59.022410Z DEBUG jsonrpsee-server: Accepting new connection 1/500
2024-04-28T18:36:59.542218Z DEBUG jsonrpsee-server: Accepting new connection 1/500
2024-04-28T18:36:59.543343Z  INFO blockchain_tree: Block is already canonical, ignoring. block_hash=0x871f0d50446b04f880b
eb7b883afaabd9ed1e2b42acf3febad0fb31ecfb55669
2024-04-28T18:36:59.543530Z DEBUG consensus::engine: [Optimism] Allowing beacon reorg to old head fcu_head_num=13495 curr
ent_head_num=13495
2024-04-28T18:36:59.543797Z  INFO reth_node_events::node: Canonical chain committed number=13495 hash=0x871f0d50446b04f880beb7b883afaabd9ed1e2b42acf3febad0fb31ecfb55669 elapsed=791.717µs
2024-04-28T18:36:59.544126Z DEBUG consensus::engine::hooks: Next hook is not ready hook="Prune"
2024-04-28T18:37:12.267854Z  INFO reth::cli: Status connected_peers=0 freelist=364 latest_block=13495
```

Other question - is it possible to download somewhere snapshot for archive and use it with Reth base version?

My launch commands:

```
nohup op-reth node \
    --chain base \
    --rollup.sequencer-http https://sequencer.base.org \
    --http \
    --ws \
    --authrpc.port 9551 \
    --authrpc.jwtsecret /company/jwt.hex \
    --datadir /company/data &

nohup op-node \
    --network="base-mainnet" \
    --l1=https://eth-l1.company.io \
    --l1.beacon=https://lighthouse.company.io \
    --l2=http://localhost:9551 \
    --l2.jwt-secret=/company/jwt.hex \
    --rpc.addr=0.0.0.0 \
    --rpc.port=7000 \
    --log.level=debug > nohup2.out &
```

Using latest CLI clients. Anything I can do to make it sync faster? 
Thanks a lot

### Steps to reproduce

following main guide

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.2.0-beta.5-dev
Commit SHA: 250da4e44
Build Timestamp: 2024-04-22T13:19:08.271330192Z
Build Features: jemalloc,optimism
Build Profile: release

### What database version are you on?

Current database version: 2
Local database is uninitialized

### Which chain / network are you on?

mainnet

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

-

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by emhane** [comment]
you could try https://github.com/paradigmxyz/reth/issues/7500#issuecomment-2074698780 @tofanovskiy

**Comment by emhane** [comment]
we don't have the op-reth base datadir available for download atm @gakonst @clabby

**Comment by emhane** [comment]
second look at this, I see you are missing the `--enable-discv5-discovery` flag from the `op-reth` command. this is enabled by default for op stack in upcoming release https://github.com/paradigmxyz/reth/pull/8065.

**Comment by Rjected** [comment]
@tofanovskiy is this still a problem / have you tried the above flag?

**Comment by gakonst** [comment]
bump @tovanovskiy

**Comment by emhane** [comment]
from op-node the `--syncmode=execution-layer` flag is missing @tofanovskiy
