### ISSUE TITLE
Send incoming requests safely from active session to manager

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#800]
### Describe the feature

Currently we don't differentiate between broadcasts and incoming requests and use

https://github.com/paradigmxyz/reth/blob/3bd1458df62c66ce9f9b2b7988bd4e2f42dd5340/crates/net/network/src/session/active.rs#L247-L256

for incoming requests:

https://github.com/paradigmxyz/reth/blob/3bd1458df62c66ce9f9b2b7988bd4e2f42dd5340/crates/net/network/src/session/active.rs#L164-L166

we should safely send this by cloning the sender like:

https://github.com/paradigmxyz/reth/blob/3bd1458df62c66ce9f9b2b7988bd4e2f42dd5340/crates/net/network/src/session/active.rs#L274-L282

## TODO

and helper function similar to:

https://github.com/paradigmxyz/reth/blob/55bc2591e683df7a8ff9f4d6a622063abcfc8142/crates/net/discv4/src/lib.rs#L307-L309

modify `on_request!` macro to send message via clone

**Comment by CryptoTurboFish** [comment]
i can help with it, got a question do we want to handle both `try_emit_message` and `on_bad_message` or just `try_emit_message`? `on_bad_message` seems to have the same `Sender` not cloned issue. 

```
    /// Send a message back to the [`SessionsManager`]
    fn try_emit_message(
        &self,
        message: PeerMessage,
    ) -> Result<(), mpsc::error::TrySendError<ActiveSessionMessage>> {
        self.to_session
            .try_send(ActiveSessionMessage::ValidMessage { peer_id: self.remote_peer_id, message })
    }

    /// Notify the manager that the peer sent a bad message
    fn on_bad_message(&self) {
        let _ = self
            .to_session
            .try_send(ActiveSessionMessage::BadMessage { peer_id: self.remote_peer_id });
    }
```

which means introducing two safe functions `safe_emit_message` and `safe_bad_message` looks verbose but considering one is for request one for response, might be OK
