### ISSUE TITLE
Add an example of using `reth-discv5`

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#8007]
### Describe the feature

Write an example along of how to use `reth-discv5` in a standalone setting for e.g. a crawler. Ideally this example demonstrates nice discv5 features like subtopics

**Comment by xJeffx23** [comment]
Hello, i can do it!

**Comment by nqd** [comment]
hi @onbjerg just look at this and https://github.com/sigp/discv5, looks like the sigp/discv5 haven't supported REGTOPIC yet. Did i miss anything?

**Comment by onbjerg** [comment]
cc @emhane since she wrote the reth integration

**Comment by mattsse** [comment]
we can close this in favor of https://github.com/paradigmxyz/reth-exex-examples/issues/20
