### ISSUE TITLE
Add example for an ExEx that registers an RLPx subprotocol

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8017]
### Describe the feature

Similar to https://github.com/paradigmxyz/reth/issues/7130

but integrated in as an exex, see for example

https://github.com/paradigmxyz/reth/blob/fb960fb3e45e11c24125ccb4bd93f2e2e21ce271/examples/exex/minimal/src/main.rs#L46-L46

This should include a custom RLPx protocol, for example broadcasting decoded logs or similar over p2p

**Comment by AbnerZheng** [comment]
Can I give it a try?

**Comment by shekhirin** [comment]
Superseded by https://github.com/paradigmxyz/reth-exex-examples/issues/3
