### ISSUE TITLE
integrate FullNodeComponents in ExExContext

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8018]
### Describe the feature

the struct already depends on:

https://github.com/paradigmxyz/reth/blob/fb960fb3e45e11c24125ccb4bd93f2e2e21ce271/crates/exex/src/context.rs#L14-L14

this should be made a field instead `components: Node`

and implement the trait as well for ease of use

**Comment by lakshya-sky** [comment]
can I take this?

**Comment by mattsse** [comment]
assigned

**Comment by lakshya-sky** [comment]
I looked at the refactoring and it seems this introduces circular dependency. `NodeComponents` is in `node-reth-builder` crate and the crate also uses `exex`. @mattsse do you have ideas how should I approach this?

**Comment by mattsse** [comment]
ah sorry, the naming is still wip

for this issue we need `Node: FullNodeComponents` of course

https://github.com/paradigmxyz/reth/blob/0938504f4a265eec74e0b833ab5c41d66649bdee/crates/exex/src/context.rs#L14-L14

and replace these:

https://github.com/paradigmxyz/reth/blob/0938504f4a265eec74e0b833ab5c41d66649bdee/crates/exex/src/context.rs#L17-L18

with just `node: Node`
