### ISSUE TITLE
Deduplicate fork timestamp configuration in ChainSpec

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8035]
Currently we define fork timestamps in two places, in the hardfork list:
https://github.com/paradigmxyz/reth/blob/9d2ca45c30a1cf13c193abe1e1ae172d0381d9c6/crates/primitives/src/chain/spec.rs#L545

and in the `fork_timestamps` field:
https://github.com/paradigmxyz/reth/blob/9d2ca45c30a1cf13c193abe1e1ae172d0381d9c6/crates/primitives/src/chain/spec.rs#L542

Given that the hardfork list is used for forkids and other activation specific logic, it should be the source of truth, and ONLY place where these are configured. `fork_timestamps` should be removed, and everything that uses it should convert to using `hardforks`.

**Comment by 0xKitsune** [comment]
Hey, can I take this one?

**Comment by 0xKitsune** [comment]
Hey, can I take this one?

**Comment by onbjerg** [comment]
yep, assigned you @0xKitsune, feel free to open up a draft PR and ask any questions you might have on direction/blockers
