### ISSUE TITLE
Unify Alloy and Reth EIP-4844 types

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#8063]
### Describe the feature

When using [foundry-blob-explorers](https://github.com/foundry-rs/block-explorers/tree/main/crates/blob-explorers) with Reth types, a bunch of type conversion shenanigans are needed https://github.com/paradigmxyz/reth/blob/fd2ade5013b82f87f9d2f990eb6748743582b15f/examples/exex/rollup/src/execution.rs#L140-L147

I believe it's due to type duplication between Alloy and Reth.

**Comment by mattsse** [comment]
@prestwich in alloy we have different blob types depending on the features:

https://github.com/alloy-rs/alloy/blob/c6329d5680467f0a47fc5e99f0f278eebb09e461/crates/consensus/src/transaction/eip4844.rs#L22-L31

should we stick to alloy_primitives and instead do a transmute in c-kzg validation?

https://github.com/alloy-rs/alloy/blob/c6329d5680467f0a47fc5e99f0f278eebb09e461/crates/consensus/src/transaction/eip4844.rs#L474-L479

then we could also easily move the sidecar type to the eips crate

**Comment by prestwich** [comment]
relevant issue:

https://github.com/alloy-rs/alloy/issues/402

**Comment by mattsse** [comment]
nice, on it!

**Comment by mattsse** [comment]
I'm marking this as completed because we now use alloys 4844 tx types and blob types and settings
