### ISSUE TITLE
Gracefully shutdown when process is killed

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#807]
### Describe the feature

Currently any signal sent to the node just kills the node with no clean up.

If you CTRL-C a running instance, make a few changes, and start the node again, you will most likely end up trying to peer with nodes you've peered with before, but they have not yet evicted you from their peerset. This leads to you connecting to nodes that think you are already connected, the connection will fail.

The CLI should handle appropriate signals using the [`ctrlc`](https://docs.rs/ctrlc/latest/ctrlc/) crate. The following should happen (ideally):

- Disconnect from all peers *and stop connecting to new ones*
- Try to wait for the current executing stage to finish
  - As a note here, the header and bodies stage will be designed to hang until they get all the data they want. For this reason, we should provide a reasonable timeout before we simply discard what the stage has been doing.

**Comment by mattsse** [comment]
supersede by #1315
