### ISSUE TITLE
Increase the timeout for peers that are to be backed off repeatedly from

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#808]
### Describe the feature

when a connection failed we check what kind of error caused the failure, and put the peer in timeout:

https://github.com/paradigmxyz/reth/blob/e846fbbb80c5ae0d8343cb8dbccf94cc4455cf8d/crates/net/network/src/peers/manager.rs#L381-L385

this is always the same timeout, and will lead to a high number of attempts if there are a lot of peers in the peerset.
For example, if there are so many peers in the group that we cannot try them all during the backoff timeout, we may not be able to reliably cycle though all peers.

This could be fixed by incrementally increasing the timeout, with a simple counter in `Peer` for example so that the next timeout becomes

```rust
peer.backoff_counter +=1;
let timeout = backoff_timeout * peer.backoff_counter;
```

**Comment by Kuly14** [comment]
I can take this.
