### ISSUE TITLE
replace reth BlobTransactionSidecar with alloy's

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8081]
### Describe the feature

with this https://github.com/alloy-rs/alloy/pull/677

we can remove this entirely:

https://github.com/paradigmxyz/reth/blob/ead753db4c96f5f9f0fd2867106d88ef6d312405/crates/primitives/src/transaction/sidecar.rs#L309-L319

and this implementation as well

https://github.com/paradigmxyz/reth/blob/ead753db4c96f5f9f0fd2867106d88ef6d312405/crates/primitives/src/transaction/eip4844.rs#L118-L123

**Comment by mahesh-dalle** [comment]
hey there, is the issue open or blocked by the alloy pr?

**Comment by mattsse** [comment]
should be ready now, last blocker is possibly https://github.com/alloy-rs/alloy/pull/679 but doesn't impact changes just --all-features compilation

do you want to take this?

first we need to bump the alloy deps here and https://github.com/paradigmxyz/evm-inspectors

**Comment by mahesh-dalle** [comment]
Yes, i would like to try this.

**Comment by mattsse** [comment]
nice, if you have any questions etc, please open a draft pr and we take it from there

**Comment by mahesh-dalle** [comment]
Well, before opening a draft can u please dump as many pointers as you can. Also from what i understand , we need to delete the struct and all the impls related to it  what do we exactly import from alloy for BlobTransactionSidecar?, also we need to delete the validate_blob function and import it from alloy_consensus right?

**Comment by mattsse** [comment]
> we need to delete the struct and all the impls related to it what do we exactly import from alloy for BlobTransactionSidecar?, also we need to delete the validate_blob function and import it from alloy_consensus right?

yes to all of this

**Comment by mahesh-dalle** [comment]
> > we need to delete the struct and all the impls related to it what do we exactly import from alloy for BlobTransactionSidecar?, also we need to delete the validate_blob function and import it from alloy_consensus right?
> 
> yes to all of this
Do we need this ?
`impl proptest::arbitrary::Arbitrary for BlobTransactionSidecar ` and `BlobTransactionSidecarRlp` ?
cuz i am getting an error after removing the struct and impl for `BlobTransactionSidecar`.
```
error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate
   --> crates/primitives/src/transaction/sidecar.rs:468:1
    |
468 | impl proptest::arbitrary::Arbitrary for BlobTransactionSidecar {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^----------------------
    | |                                       |
    | |                                       `reth_rpc_types::BlobTransactionSidecar` is not defined in the current crate
    | impl doesn't use only types from inside the current crate
    |
    = note: define and implement a trait or new type instead

error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate
   --> crates/primitives/src/transaction/sidecar.rs:443:1
    |
443 | impl<'a> arbitrary::Arbitrary<'a> for BlobTransactionSidecar {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^----------------------
    | |                                     |
    | |                                     `reth_rpc_types::BlobTransactionSidecar` is not defined in the current crate
    | impl doesn't use only types from inside the current crate
    |
    = note: define and implement a trait or new type instead
    ```

**Comment by mattsse** [comment]
this is merged now:

https://github.com/alloy-rs/alloy/pull/677

**Comment by mahesh-dalle** [comment]
Hey i dont think i would be able to continue on this one. Will be out on a lookout for more easier GFIs.
