### ISSUE TITLE
ExEx notification type targets finalized/safe blocktag

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8086]
Add Stream type that only yields a canonstate notififaction on new finalized/safe block.

This should be a helper wrapper type over

https://github.com/paradigmxyz/reth/blob/ead753db4c96f5f9f0fd2867106d88ef6d312405/crates/storage/provider/src/traits/chain.rs#L30-L30

that monitors buffers a `Chain` until a new finalized/safe block is reached, this info can be obtained from a `Provider`

**Comment by guha-rahul** [comment]
Hey can i work on it.Also can you please share more pointers?

**Comment by mattsse** [comment]
not exactly what this should do is skip new items if it's not the latest, or finalized hash,

perhaps we should first introduce a tokio watch for the safe/finalized trackers

https://github.com/paradigmxyz/reth/blob/a8e5eb6186bcd5ea9e63044ebf19e87a7c531c3e/crates/storage/provider/src/providers/chain_info.rs#L131-L136

**Comment by mattsse** [comment]
closing in favor of #8794
