### ISSUE TITLE
Don't restrict database error variant on executor

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8089]
### Describe the feature

This should not require ProviderError and should just require `Error` or `Into<BlockExecutionError>`
https://github.com/paradigmxyz/reth/blob/ead753db4c96f5f9f0fd2867106d88ef6d312405/crates/evm/src/execute.rs#L123-L123

blocked by https://github.com/paradigmxyz/reth/issues/8088

**Comment by sergerad** [comment]
@mattsse I have looked into this one out of interest. Wanted to ask if you thought the diffs in the PR are on the right track or not.

I assume I can get around the current compiler error by implementing the appropriate from() or into(). But it feels like that could be going down the wrong track and likely to hit many more issues after that. 
```
required for `revm_primitives::EVMError<std::boxed::Box<dyn std::error::Error>>` to implement `std::convert::Into<std::boxed::Box<revm_primitives::EVMError<reth_evm::execute::ProviderError>>>`
```

Any insight / direction would be appreciated, thanks 🙏

**Comment by mattsse** [comment]
ah sorry I forgot to link the relevant issue #8152

this problem will go away with an upcoming stable rust feature, on nightly this already works
