### ISSUE TITLE
move beacon API types to a new crate in alloy

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8094]
### Describe the feature

 
# TODO
* move https://github.com/paradigmxyz/reth/tree/ead753db4c96f5f9f0fd2867106d88ef6d312405/crates/rpc/rpc-types/src/beacon to a new crate rpc-types-beacon in alloy: https://github.com/alloy-rs/alloy/tree/main/crates
* should also include the `relay` module

**Comment by rupam-04** [comment]
do we totally remove the beacon crate from here?
