### ISSUE TITLE
replace U64 fields with primitive u64 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8095]
### Describe the feature

we have a lot of U64 fields, in this file:

https://github.com/paradigmxyz/reth/blob/ead753db4c96f5f9f0fd2867106d88ef6d312405/crates/rpc/rpc-types/src/mev.rs#L37-L38

this should be replaced with `u64`, `Option<u64>` and and a serde attribute `[serde(with = "alloy_rpc_types::serde_helpers::num::u64(_opt)_via_ruint")]`

**Comment by guha-rahul** [comment]
Can i take it?
for this, after we replace U64 with u64 from primitives we have to replace/add the assigned serde attribute with the one you mentioned right?

**Comment by mattsse** [comment]
> we have to replace/add the assigned serde attribute with the one you mentioned right?

yeah for Option<U64> it's `u64_opt_via_ruint` and for U64 it's num::u64_via_ruint
