### ISSUE TITLE
Misbehaviour in debug_traceCall 

### ISSUE THREAD

**Issue by Arvmor** [paradigmxyz/reth#8103]
### Describe the bug

In reth, we fail to retain `contract address` when using debug_traceCall,
however the exact same function, without anychanges, returns the right values in geth

### Steps to reproduce

Reth, faulty response:
```curl
curl http://localhost:8545/ -X POST -H 'Content-Type: application/json' -d '{"id":1,"jsonrpc":"2.0","method":"debug_traceCall","params":[{"data":"0x03e11a81a460ea6fd96a73d5672f1f4aa684697d4b44cc46c8229b","from":"0xaeeb8456f598f7242ed32bc9658ba20f6b4557fd","gas":"0x927c0","gasPrice":"0x149d12861","to":"0x0015fe03456b000000009a38ba029a1d515f00e8","value":"0x49e1b0a"},"0x12e0a13",{"stateOverrides":{},"tracer":"{ retVal: [], callStack: [], byte2Hex: function(byte) { if (byte < 0x10) return \"0\" + byte.toString(16); return byte.toString(16); }, array2Hex: function(arr) { var retVal = \"\"; for (var i = 0; i < arr.length; i++) retVal += this.byte2Hex(arr[i]); return retVal; }, getAddr: function(log) { return this.array2Hex(log.contract.getAddress()); }, step: function(log, db) { var opcode = log.op.toNumber(); if (opcode == 0x54) { this.retVal.push(this.getAddr(log) + \":\" + log.stack.peek(0).toString(16)); } if (opcode == 0x55) this.retVal.push(this.getAddr(log) + \":\" + log.stack.peek(0).toString(16) + \";\" + log.stack.peek(1).toString(16)); }, fault: function(log, db) { this.retVal.push(\"FAULT: \"); }, result: function(ctx, db) { return this.retVal; } }"}]}'
```

```json
[":29014e76b0986d11d3cdf684c1f9f21c48ee047d65ac69db0da87068aa883c4f"]
```

Geth right response:
*just change localhost to this geth node: `https://eth-pokt.nodies.app` *

```json
["c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2:29014e76b0986d11d3cdf684c1f9f21c48ee047d65ac69db0da87068aa883c4f"]
```

as you can see, the contract address before the `:` is missing in reth respone

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.2.0-beta.6
Commit SHA: ac29b4b73
Build Timestamp: 2024-05-03T11:36:14.574613897Z
Build Features: jemalloc
Build Profile: maxperf

### What database version are you on?

Current database version: 2
Local database is uninitialized

### Which chain / network are you on?

mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
yeah and contract is set:

https://github.com/paradigmxyz/evm-inspectors/blob/089efacf72e7583630841b7027c46a3cb2f9c28b/src/tracing/js/bindings.rs#L202-L202

looks like log.contract.getAddress() returns an empty vec? which would explain ":..."

**Comment by Arvmor** [comment]
for a little context,
this script is mainly used to generate accessLists
since the ‘eth_generateAccesslist’ is restricted to one transaction
simulation at once

**Comment by mattsse** [comment]
@Arvmor finally found it, sorry for the delay
