### ISSUE TITLE
Add a signal to gracefully shut down the networking component

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#812]
### Describe the feature

A signal should be added that prompts the networking component to stop connecting to new peers, drops all pending connections, tells incoming connections that we are shutting down, and sends disconnect reasons to all connected peers.

It should be possible to know when the shutdown is complete. The `NetworkManager` future should resolve.

A proposed API would be to add a `shutdown` function to `NetworkHandle` that returns a future that resolves once the shutdown is complete.

### Additional context

This is currently blocking #807

**Comment by entropidelic** [comment]
I would like to take this one if possible :)

**Comment by mattsse** [comment]
great,

for now, I think we can start with:

1. a new command (`Shutdown(oneshotSender<()>)`) from `NetworkHandle` -> `NetworkManager`
2. disconnect all sessions
3. send `()`

**Comment by entropidelic** [comment]
great, I will send a PR shortly, thanks!
