### ISSUE TITLE
Wrong Use of Fallback IP(0.0.0.0) as fromIP in Ping message of Node Discovery Protocol 

### ISSUE THREAD

**Issue by learnerLj** [paradigmxyz/reth#8122]
### Describe the bug

Our tool finds that a client `reth/v0.1.0-alpha.10` sends node discovery Ping message whose fromIP is 0.0.0.0. But the second Ping of it shows the correct public IP. I guess the it is the NAT or the setupPortMapping that trigger the problem.
![image](https://github.com/paradigmxyz/reth/assets/72367122/35d76d92-0b8c-439f-b97f-f3631fc918cd)

Geth has the similar bug, see https://github.com/ethereum/go-ethereum/issues/29713 . But its source IP in the first Ping is 127.0.0.1 

### Steps to reproduce

measure the ethereum network

### Platform(s)

Linux (x86)

### What version/commit are you on?

unknown system.
![image](https://github.com/paradigmxyz/reth/assets/72367122/b2b6da47-85ea-4956-8cda-4adb1a512624)

### What database version are you on?

unknown 

### Which chain / network are you on?

'caps' = {list: 3} [{'name': 'eth', 'version': 68}, {'name': 'eth', 'version': 67}, {'name': 'eth', 'version': 66}]
'networkID' = {Int64} 1
'genesisHash' = {str} '0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3'
'forkID' = {str} 'fc64ec04/118c30'

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

unkown node

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
In general we do not consider bugs from versions as old as `alpha.10` as valid, specifically this issue we triaged and fixed:
https://github.com/paradigmxyz/reth/issues/4222
https://github.com/paradigmxyz/reth/pull/4224
https://github.com/paradigmxyz/reth/pull/4268
https://github.com/paradigmxyz/reth/pull/4849 

closing this issue, in the future reproductions should be with `alpha.23` or `beta.6`

**Comment by learnerLj** [comment]
Thank you for your insightful reply!
