### ISSUE TITLE
op-reth killed by out-of-memory killer

### ISSUE THREAD

**Issue by Nojoix** [paradigmxyz/reth#8131]
### Describe the bug

Hi,
I had the same issue as #8115 but with op-reth
I'm running on debian with 128gb of ram, L1 reth on same machine and RAID 0 disks
Compiled  `0.2.0-beta.6` from source with `make install-op` nothing fancy.
I'm running it with `discv5` enable after syncing it with debug.tip 
It run for a couple of days without issue and got killed, unfortunatly i dont have more than the reth log i'm sending.

### Steps to reproduce

start op-reth
get oom

### Node logs

[rethlogs.tar.gz](https://github.com/paradigmxyz/reth/files/15226541/rethlogs.tar.gz)

[rethlogs3_5.tar.gz](https://github.com/paradigmxyz/reth/files/15226558/rethlogs3_5.tar.gz)

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.2.0-beta.6
Commit SHA: VERGEN_IDEMPOTENT_OUTPUT
Build Timestamp: 2024-05-01T12:22:09.264105989Z
Build Features: jemalloc,optimism
Build Profile: release

### What database version are you on?

Current database version: 2
Local database version: 2

### Which chain / network are you on?

base mainnet

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

i use default, i didn't touched reth.toml

### If you've built Reth from source, provide the full command you used

make install-op

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### UPDATE :

After ~10hrs the op-reth node is growing by 7gb of ram
After ~24hrs 100 gb of ram is used 

i have this warning sometimes : 
`2024-05-08T06:58:24.248553Z  WARN IPC request failed: Custom { kind: Other, error: "bytes remaining on stream" }
2024-05-08T06:58:24.248550Z  WARN IPC request failed: Custom { kind: Other, error: "bytes remaining on stream" }
`

**Comment by mattsse** [comment]
sorry for not getting back to you earlier, this indeed looks ipc related, we fixed a few ipc issues since then so this should be resolved, I also noticed a lot of

> Invalid params", data: Some(RawValue("unknown field `Number`, expected one of `blockNumber`, `number`,

related to blockOverrides
