### ISSUE TITLE
Move and rename BeaconConsensus

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8137]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/f281bbdccda2e08b1d5db651f25c7735ea1d63ed/crates/consensus/beacon-core/src/lib.rs#L22-L22

should be renamed to `EthBeaconConsensus`
and moved to crates/ethereum/consensus

**Comment by rupam-04** [comment]
Can I take this

**Comment by willco-1** [comment]
i started on this

**Comment by rupam-04** [comment]
> i started on this

oh sorry man didn't notice this closing my pr now

**Comment by willco-1** [comment]
you're good! you beat me to it. i will make sure not to open an additional pr

**Comment by rupam-04** [comment]
> you're good! you beat me to it. i will make sure not to open an additional pr

oh so should I reopen it?

**Comment by willco-1** [comment]
oh, i misread that as the pr was closed as in merged already. i can just open mine, im finished
