### ISSUE TITLE
Historical EIP-1186 `eth_getProof` support for op-stack Withdrawal proofs

### ISSUE THREAD

**Issue by 0xOsiris** [paradigmxyz/reth#8147]
### Describe the feature

Currently Reth does not offer support for `eth_getProof` on historical blocks. This breaks compatibility with the op-stack having Reth running as the sequencing execution client as Reth will not be able to generate withdrawal proofs for the proposer to post to L1 (except at the tip). 

### Additional context

Ref: https://github.com/ethereum-optimism/optimism/blob/89a3a5f32b79b2447690cdac70b1df498ffdb25c/op-node/withdrawals/utils.go#L102

Related to: https://github.com/paradigmxyz/reth/issues/5246

**Comment by 0xKitsune** [comment]
Just a quick update, @0xOsiris and I have started working on this. I will open a draft PR with a few questions a little later today.

**Comment by nikkolasg** [comment]
Hey - any chance this issue might be worked on at some point ? I see it dropped now but it would be a fantastic and important feature to have for reth !

**Comment by 0xKitsune** [comment]
Hey, sorry for the delay, there were a few high priority items that inhibited us from finishing up this PR. 

This is still being worked on and we actually just updated the ExEx to [include support for fault proofs](https://github.com/0xKitsune/reth/pull/10). We should have an updated PR ready for review within the next few days (future PRs from us will be much faster).

**Comment by onbjerg** [comment]
Thanks for flagging, reopened it for consideration:)

**Comment by jaeaster** [comment]
+1 for this. We decided to go with Besu until this is ready

**Comment by denis-pingin** [comment]
This is a much needed feature to be able to use Reth for OP stack rollups

**Comment by benluelo** [comment]
any progress here? `eth_getProof` is a requirement for IBC trustless bridging, meaning we can't use reth for any eth execution clients 🫤
