### ISSUE TITLE
Use associated trait bound for Database Error = ProviderError

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8152]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/8954ffb42333a0966d509ae470558a5d96396dbc/crates/evm/src/execute.rs#L144-L144

ideally we can use something like `type Executor<DB: Database<Error : Into<ProviderError>>>:` instead.

This currently only works on nightly, but will be stabilized:

https://github.com/rust-lang/rust/issues/52662

**Comment by i-m-aditya** [comment]
Working on this.
