### ISSUE TITLE
Extract layers module from rpc crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8161]
### Describe the feature

These layers aren't used by the crate directly, only in rpc-builder, they don't even need any eth/reth types

https://github.com/paradigmxyz/reth/tree/bdb8238d79c383033a68cbeef8809c37a481e303/crates/rpc/rpc/src/layers

## TODO
* extract these types to a standalone crate `rpc/rpc-layer` or `rpc/rpc-util`

**Comment by rupam-04** [comment]
Can I take this?
