### ISSUE TITLE
MerkleStage

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#817]
### Describe the feature

As hashing of state is done inside `AccongHashingStage` and `StorageHashingStage` we can create MerkleStage that would create intermediate hashes stored them and calculate merkle trie state root,

After merkle root is created in we should check if it matches state root of the block, and error if it is not.

Note As Merkle stage require HashingStages it needs to come after Hashing stages on both execution path and unwind path. To facilitate that and not introduce custom order logic we can create one MerkleStage but put it in two places in pipeline, first one will trigger on unwind and second one on execution path.
ordering it as:
- MerkleStage for unwind path
- HashingStage. for both execution and unwind paths.
- MerkleStage for execution path. (edited)

Take a look at: https://github.com/paradigmxyz/reth/pull/756/files#diff-c165764b7c3e03f51dedc225878a5dffd8331960e769a776cdb001401df32d89

**Comment by entropidelic** [comment]
would love to take this one!
