### ISSUE TITLE
extract node-core/init.rs from node-core

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8171]
### Describe the feature

these operations are out of place here:

https://github.com/paradigmxyz/reth/blob/aa07257d3ba071188b7b7e372856b50be094e8ba/crates/node-core/src/init.rs

they also can't be included in any existing storage crates, like db/provider and should be moved to `reth-db-{common,core,init,ops}`. Any other naming ideas @Rjected ?
leaning towards reth-db-common

**Comment by willco-1** [comment]
can i take this?

**Comment by wlawt** [comment]
is this still available? i can try to take a stab at it @mattsse
