### ISSUE TITLE
Feat: ExEx op-proposer

### ISSUE THREAD

**Issue by 0xKitsune** [paradigmxyz/reth#8174]
### Describe the feature

The `eth_getProof` endpoint currently lacks support for [storage proofs at historical blocks](https://github.com/paradigmxyz/reth/issues/8147).  The `op-proposer` must retrieve proofs from historical blocks for the `L2ToL1MessagePasser` account in order to submit [WithdrawalProofs](https://specs.optimism.io/protocol/withdrawals.html#withdrawal-verification-and-finalization) and facilitate withdrawals from L2 -> L1 for the OP stack.

Instead of unwinding the state to the specified block and calculating the storage proof, we can implement the `op-proposer` logic as an ExEx, getting a storage proof every `n` blocks or at some specified interval. The ExEx would then create a transaction that would post the proof to the `L2OutputOracle` on L1.

We can get started working on this now.

**Comment by 0xOsiris** [comment]
The current design is to have the exex fetching the proof at the tip on the `SUBMISSION_INTERVAL` as specified on configuration. A signer will post the proof to L1 at the time of fetching the proof. An external database could be used as a backup data source, but there are still concerns on robustness e.g. Inclusion on L1 fails, backup db failure, etc. Withdrawal verification on L1 is critically dependent on both the availability of the Proofs, and the inclusion of those proofs on L1. Not being able to recompute these proofs in an edge case when the proof needs to be recomputed on a historical block is a significant weak point in a rollup with this design.  

**Brainstorming**
- You could run a trusted Geth client alongside the sequencer as a absolute worst case fallback if the historical proof can't be fetched from a database (This makes running Reth as the sequencer a bit silly at this point)
- You could linearly rollback state to the time of the historical block, and then re execute to the tip (i.e. basically the functionality of `getProof` on historical blocks

Just seems like a fragile mechanism to be completely reliant on transaction inclusion, and a db to verify withdrawals from the rollup. Just trying to think of a design here that would have the robustness of a production ready rollup with **guarantees** on withdrawals 

Open to thoughts/suggestions
