### ISSUE TITLE
Add CI check that `reth-primitives` compiles to RISC-V

### ISSUE THREAD

**Issue by puma314** [paradigmxyz/reth#8176]
### Describe the feature

RISC-V is an important target for zkVMs, such as SP1, Risc0, JOLT and others, which prove the execution of RISC-V bytecode in a zero-knowledge proof. `reth-primitives` is an important crate that is meant to be minimal in dependencies and should be compilable to the RISC-V target for use in all zkVMs. 

While PRs in the past have been merged in to ensure that `reth-primitives` can compile to RISC-V, without a CI check to ensure this compilation is possible, networking dependencies (or other incompatible dependencies) sneak into the `reth-primitives` crate.

It would be great to add a CI check to ensure this crate (and others that can be added in the future) with appropriate features enabled can be compiled to RISC-V.

h/t to @preston-evans98 for suggesting this issue.

**Comment by preston-evans98** [comment]
This would be super useful for us at Sovereign Labs! 

Note that of the platforms referenced in the original issue require a 32-bit RISC-V architecture.

Our preferred target for the check is the official [riscv32im-risc0-zkvm](https://doc.rust-lang.org/nightly/rustc/platform-support/riscv32im-risc0-zkvm-elf.html), which captures the constraints of zk execution environments (i.e. limited `std` support with no networking).
