### ISSUE TITLE
Unify `reth_primitives` and `alloy_rpc_types`

### ISSUE THREAD

**Issue by puma314** [paradigmxyz/reth#8177]
### Describe the feature

There are several places where `reth_primitives` have types that could be `alloy_rpc_types`. As an example where this causes pain is in SP1-Reth, where we have [200 LOC](https://github.com/succinctlabs/sp1-reth/blob/main/primitives/src/alloy2reth.rs) devoted to converting between these types, as we fetch data from an RPC endpoint, and then must convert it to feed it into reth processing.

**Comment by mattsse** [comment]
withdrawals are now used from alloy, and we have a few tryfrom conversions available via the alloy-compat feature:

https://github.com/paradigmxyz/reth/blob/aa07257d3ba071188b7b7e372856b50be094e8ba/crates/primitives/src/block.rs#L150-L152

**Comment by Vid201** [comment]
I can take this

**Comment by gakonst** [comment]
assigned! @puma314 got any more things to share with @Vid201 on what it'd take to consider this completed?
