### ISSUE TITLE
Support DNS resolution for bootnode URL

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8187]
Geth parses enode addrs here:
https://github.com/ethereum/go-ethereum/blob/74edc9386495f0ff44d68bf6e237a69f27021144/p2p/enode/urlv4.go#L72-L81

which does resolution here:
https://github.com/ethereum/go-ethereum/blob/74edc9386495f0ff44d68bf6e237a69f27021144/p2p/enode/urlv4.go#L129-L137

We should support DNS resolution for bootnode enode URLs, although we should:
* first parse, with a string fallback in case it is a domain and not an IP
* attempt to resolve the string fallback later, with a timeout

**Comment by sergerad** [comment]
@Rjected did you want any help with your PR for this? Happy to help, have worked on similar stack in geth.
