### ISSUE TITLE
Sender recovery (trace_filter) failed for an old block

### ISSUE THREAD

**Issue by paulmillr** [paradigmxyz/reth#8191]
### Describe the bug

`eth.merkle.io` snapshot was used, so it's unclear if it's corrupted snapshot; or reth, which generated corrupted data

### Steps to reproduce

Get internal transactions (trace_filter) for address `0x6994eCe772cC4aBb5C9993c065a34C94544A4087` from block 46100 to block 46200

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.2 b6

### What database version are you on?

-

### Which chain / network are you on?

-

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks, this is pre eip2, we just need to use a different recovery fn here #8200
