### ISSUE TITLE
`eth` message type metrics

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8245]
### Describe the feature

Even if we don't handle a certain type of request, it would be interesting to see what kinds of requests we are receiving, and in what proportion (GetReceipts, GetBlockHeaders, ...). We should add metrics for this.

This would involve introducing a new metrics type with counts for each type of `eth` message, and then increment the counts here:
https://github.com/paradigmxyz/reth/blob/081796b138fd00a6d0af2ad463123fdbe04765ab/crates/net/network/src/eth_requests.rs#L236-L258

**Comment by vcshih** [comment]
I'm interested in taking this one on but i noticed there's already a EthRequestHandlerMetrics here: https://github.com/paradigmxyz/reth/blob/081796b138fd00a6d0af2ad463123fdbe04765ab/crates/net/network/src/metrics.rs#L310-L318 which increments headers and bodies here: https://github.com/paradigmxyz/reth/blob/081796b138fd00a6d0af2ad463123fdbe04765ab/crates/net/network/src/eth_requests.rs#L141-L187. I can just extend it for the other two request types but wanted to make sure that that is the intended behavior.

**Comment by Rjected** [comment]
>  . I can just extend it for the other two request types but wanted to make sure that that is the intended behavior.

yep, exactly!
