### ISSUE TITLE
move relay rpc types to alloy

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8273]
### Describe the feature

move these 

https://github.com/paradigmxyz/reth/blob/aa5c52b944ba47f59512700571a19d8ae877abb2/crates/rpc/rpc-types/src/relay/mod.rs#L1-L1

to https://github.com/alloy-rs/alloy/tree/main/crates/rpc-types-beacon

**Comment by Vid201** [comment]
I can take this
