### ISSUE TITLE
replace JwtSecret type with alloy's

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8276]
### Describe the feature

alloy now has the same type, which means we can now phase out the reth type:

https://github.com/paradigmxyz/reth/blob/79d505adb29a84674df6f293909fab2192af2431/crates/rpc/rpc-layer/src/jwt_secret.rs#L77-L79

we like need to change the function that reads from disk to a standalone function

**Comment by quentinv72** [comment]
I can do this. @mattsse Would it make sense to define the `from_file` and `try_create` methods in alloy directly? As opposed to creating standalone functions in reth.
