### ISSUE TITLE
Run reth in a private testnet

### ISSUE THREAD

**Issue by anonymousGiga** [paradigmxyz/reth#8279]
### Describe the change

I want to run a private testnet using reth on two machines to debug the reth code I modified. But in the reth book, only one document uses kurtosis to build a private testnet. Can you provide a document for building reth from source code and building a private testnet with lighthouses? 

### Additional context

Run Reth in a private testnet using Kurtosis:    https://paradigmxyz.github.io/reth/run/private-testnet.html#run-reth-in-a-private-testnet-using-kurtosis

**Comment by mattsse** [comment]
this should be doable with kurtosis if you use a locally build reth image instead of pulling it from ghrc

**Comment by Rjected** [comment]
IMO the book does a good job at describing how to run a private testnet, just added a note in #8354
