### ISSUE TITLE
Extract payload related types from engine types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8330]
### Describe the feature

currently the payloadbuilder types are defined in the enginetypes:

https://github.com/paradigmxyz/reth/blob/5100ddd28e3ae0396aa97633d6f700d77aefb50f/crates/engine-primitives/src/lib.rs#L32-L46

and used like this:

https://github.com/paradigmxyz/reth/blob/5100ddd28e3ae0396aa97633d6f700d77aefb50f/crates/payload/builder/src/service.rs#L276-L280

afaik the payload impls only need these three types,

we should extract those to a new trait and then reuse and restrict those in EngineTypes

## TODO
* First PR: introduce new crate payload-primitives and move the traits and relevant types from: https://github.com/paradigmxyz/reth/blob/5100ddd28e3ae0396aa97633d6f700d77aefb50f/crates/payload/builder/src/traits.rs#L7-L7
* Then, Introduce a PayloadTypes trait that contains the 3 associated types from engine types
* reuse in enginetypes and add the existing TryFrom restrictions etc.

**Comment by 0xqd** [comment]
Can I take this one?
