### ISSUE TITLE
Make EthEngineTypes generic

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8331]
### Describe the feature

currently the associated types for enginetypes are fixed

https://github.com/paradigmxyz/reth/blob/5100ddd28e3ae0396aa97633d6f700d77aefb50f/crates/ethereum/engine-primitives/src/lib.rs#L32-L38

which makes it harder to configure a custom payload/builder etc

we should make the relevant payload types generic here, this should happen after:

https://github.com/paradigmxyz/reth/issues/8330

**Comment by leontiad** [comment]
can look at it

**Comment by sergerad** [comment]
@mattsse which of these `Eth*` and `Exec*` types do you want to become generic? All of them?

```rust
impl PayloadTypes for EthEngineTypes {
    type BuiltPayload = EthBuiltPayload;
    type PayloadAttributes = EthPayloadAttributes;
    type PayloadBuilderAttributes = EthPayloadBuilderAttributes;
}

impl EngineTypes for EthEngineTypes {
    type ExecutionPayloadV1 = ExecutionPayloadV1;
    type ExecutionPayloadV2 = ExecutionPayloadEnvelopeV2;
    type ExecutionPayloadV3 = ExecutionPayloadEnvelopeV3;
    type ExecutionPayloadV4 = ExecutionPayloadEnvelopeV4;
```

And I'm assuming you mean that `EthEngineTypes` becomes generic and `EngineTypes` and `PayloadTypes` do not

**Comment by FredCoen** [comment]
Hey @mattsse is this the right way to go? https://github.com/paradigmxyz/reth/pull/10779
thanks!

**Comment by mattsse** [comment]
closing because this is no longer feasible
