### ISSUE TITLE
Integrate critical task metrics in grafana dashboard

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8332]
### Describe the feature

we have these useful metrics but don't have them in the dashboard:

https://github.com/paradigmxyz/reth/blob/043b4a9cda8d738283b414897335c1863bfd34c2/crates/tasks/src/metrics.rs#L7-L19

## TODO
* integrate a graph in grafana similar to 

https://github.com/paradigmxyz/reth/blob/043b4a9cda8d738283b414897335c1863bfd34c2/etc/grafana/dashboards/reth-mempool.json#L1454-L1492

needs #8263

**Comment by d3or** [comment]
i can take this

**Comment by greged93** [comment]
Hey @d3or I'm down to take this if you didn't have time to work on it

**Comment by d3or** [comment]
Hey! Feel free to take it :)
