### ISSUE TITLE
Integrate eth request metrics into grafana dashboard

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8334]
### Describe the feature

We have the following metrics for the different `eth` request types:
https://github.com/paradigmxyz/reth/blob/6b14cbc5e75b12efcbf5e7085ad6ac25a82f4ee3/crates/net/network/src/metrics.rs#L309-L324

These should be added to the grafana dashboard, so we can observe in real time how many of each type of request we receive.

**Comment by hopinheimer** [comment]
I'd like to work on this

**Comment by Rjected** [comment]
> I'd like to work on this @Rjected

sure! assigned

**Comment by Rjected** [comment]
> I'd like to work on this @Rjected

@hopinheimer any updates / need any help?

**Comment by hopinheimer** [comment]
apologies @Rjected for a really delayed response. I'm not available for sometime and I think this issue is time sensitive so, I'm unassigning myself --  I really regret for the inconvenience caused

**Comment by d3or** [comment]
Hey! Can I take this on?

**Comment by Rjected** [comment]
@d3or sure, just assigned!
