### ISSUE TITLE
Introduce total gas and gas per second metrics on new payload

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8378]
### Describe the feature

We currently have latency metrics for newPayload here:
https://github.com/paradigmxyz/reth/blob/d7172b6605c43b5847ce0d3429a5ee85bf88b0b2/crates/rpc/rpc-engine-api/src/engine_api.rs#L49-L50

We should also record the gas / gas per second for each payload on each VALID newPayload response.

**Comment by qiweiii** [comment]
hi @Rjected , I made a draft pr, could you check if I'm on the right track?

**Comment by Josh-121** [comment]
Can work on this. Please assign
