### ISSUE TITLE
Update EIP-2935

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#8379]
https://github.com/ethereum/EIPs/pull/8577 Per this getting merged we'll need to remove the backfill logic for devnet-1.

_Originally posted by @gakonst in https://github.com/paradigmxyz/reth/issues/7818#issuecomment-2128187576_

**Comment by shekhirin** [comment]
Done in https://github.com/paradigmxyz/reth/pull/8431

**Comment by onbjerg** [comment]
This just requires an alloy update with https://github.com/alloy-rs/alloy/pull/934

**Comment by onbjerg** [comment]
New version released, just need to bump to 0.1.2. Will do that today
