### ISSUE TITLE
Move reth-network config types to new crate network-types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8418]
### Describe the feature

currently reth-config depends on a few types from network which are serializable:

https://github.com/paradigmxyz/reth/blob/e54398308b7439e2297623a9117964d97d106586/crates/config/src/config.rs#L3-L3

these can be also be moved to a new crate to keep network-api and network leaner and then re-export again from reth-network

https://github.com/paradigmxyz/reth/blob/e54398308b7439e2297623a9117964d97d106586/crates/net/network/src/peers/manager.rs#L1271-L1275

## TODO

* move relevant config types from reth-network to a new crate reth-network-types/src/config.rs

**Comment by polebug** [comment]
Could I take this issue?

**Comment by wlawt** [comment]
@polebug just wondering if you're still on this issue, or if you don't mind if i take an attempt

**Comment by polebug** [comment]
> @polebug just wondering if you're still on this issue, or if you don't mind if i take an attempt

I am still doing this.

**Comment by mattsse** [comment]
just checking in @polebug 
do you have bandwidth to work on this?
