### ISSUE TITLE
`stage --help` should list valid stages

### ISSUE THREAD

**Issue by loren** [paradigmxyz/reth#842]
### Describe the feature

Initial guess at stage name:
```
reth stage --from 4999000 --to 5000000 Senders
error: Invalid value 'Senders' for '<STAGE>': Matching variant not found

For more information try '--help'
```

help doesn't say what the valid values are:
```
Arguments:
  <STAGE>
          The name of the stage to run
```

The right answer is `senders` but this requires looking at the code to see that the case changes:
```
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "kebab-case")]
enum StageEnum {
    Headers,
    Bodies,
    Senders,
    Execution,
}
```

On a related note, metrics outputs a different name for the senders stage. It's the only one that differs from what's in the `enum`:
```
reth_stage_progress{stage="Bodies"} 5000000
reth_stage_progress{stage="Execution"} 1920000
reth_stage_progress{stage="Headers"} 5000000
reth_stage_progress{stage="SenderRecovery"} 5000000
```

**Comment by onbjerg** [comment]
The metrics names are correct, unsure why they were renamed in the CLI.
