### ISSUE TITLE
exclude examples from workspace and check them in a separate CI job

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8451]
### Describe the feature

currently all examples are compiled as part of the workspace:

https://github.com/paradigmxyz/reth/blob/76b32c8b5f3b9937ca507c75b4ba53cb0c83915e/Cargo.toml#L86-L104

we should put them in the exclude_members section and have a dedicated CI job just for examples

**Comment by andrzejSulkowski** [comment]
Will be done

**Comment by Josh-121** [comment]
Please assign. Can work on this

**Comment by mattsse** [comment]
solved via https://github.com/paradigmxyz/reth/pull/8953
