### ISSUE TITLE
Add no-std support for in reth-storage-errors

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8459]
### Describe the feature

Ideally, we want to have a subset of crates with no_std supports (evm specifically)
we need to do some prep for this first by making some crates no_std first

## TODO

* add `#![cfg_attr(not(feature = "std"), no_std)]`
* Add to cargo.toml
```
default = ["std"]
std = []
``` 
* Fix errors by manually implementing std::error::Error instead of deriving and put it behind std feature

Best way to do this is `cargo expand` and modify the generated code

**Comment by JackG-eth** [comment]
Happy to take
