### ISSUE TITLE
Extract core rpc server types to standalone crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8460]
### Describe the feature

currently node-core pulls in rpc-builder for constants and setup code

rpc-builder is pretty beefy because it pulls in the entire stack required for all endpoints.
node-core sits pretty deep in the stack so this results in bloated dependency trees

## TODO
[x] add new crate `rpc-server(-common|types)` and extract all types/constants used by node-core rn
[ ] move eth cache types https://github.com/paradigmxyz/reth/blob/13fcb885c60bab1390c4525cb5a0c35ab215e833/crates/rpc/rpc/src/eth/cache/config.rs#L2-L2

**Comment by leruaa** [comment]
I can take this on
