### ISSUE TITLE
Add append_receipts function

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8466]
### Describe the feature

The static file writer currently only has a function for single receipts:

https://github.com/paradigmxyz/reth/blob/7262d08f474d386b13830891842ec768f8bc921d/crates/storage/provider/src/providers/static_file/writer.rs#L455-L459

resulting in code like this:

https://github.com/paradigmxyz/reth/blob/7262d08f474d386b13830891842ec768f8bc921d/crates/static-file/src/segments/receipts.rs#L47-L51

and 

https://github.com/paradigmxyz/reth/blob/7262d08f474d386b13830891842ec768f8bc921d/crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs#L48-L52

the append_receipt always does two syscalls for the clock
https://github.com/paradigmxyz/reth/blob/main/crates/storage/provider/src/providers/static_file/writer.rs#L460-L460

we can optimize this by using a append_receipts function that accepts an iterator instead and only update the metrics once

**Comment by leontiad** [comment]
I can look at that
