### ISSUE TITLE
Add EIP-4844 transaction type description in book

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#8470]
### Describe the change

In the reth book, in the transaction type description:

https://github.com/paradigmxyz/reth/blob/7262d08f474d386b13830891842ec768f8bc921d/book/run/transactions.md

we currently lack a description of EIP-4844 transactions which are now part of reth implementation. A complete description of this can be found here: 

https://www.eip4844.com/

**Comment by Josh-121** [comment]
please assign. Can work on this

**Comment by MariangelaNM** [comment]
Hi, I would like to contribute.

**Comment by JosepBove** [comment]
Should be closed, it's already implemented.
