### ISSUE TITLE
reth-db does not compile without default features

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8477]
### Describe the feature

the function signature uses a type that only exists if the feature is enabled because this is a mdbx type

https://github.com/paradigmxyz/reth/blob/ab938e7923882bd2127064b08aa11a3a8b84b1fb/crates/storage/db/src/lib.rs#L153-L156

```
cargo c --no-default-features
```

```
error[E0412]: cannot find type `DatabaseEnv` in this scope
   --> crates/storage/db/src/lib.rs:155:70
    |
155 | pub fn open_db(path: &Path, args: DatabaseArguments) -> eyre::Result<DatabaseEnv> {
    |                                                                      ^^^^^^^^^^^ not found in this scope
```

todo make it compile without mdbx

imo this function should only exist if the mdbx feature is enabled, this would also prevent issues when the crate is used without mdbx feature which would result in a runtime panic

**Comment by DaniPopes** [comment]
moving cfg to function seems fine
