### ISSUE TITLE
Add a way to get the `NodeRecord` of the local node

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#849]
### Describe the feature

Currently we can get the peer ID of the local node by using `NetworkHandle::peer_id`, but it would also be beneficial to get the `NodeRecord` corresponding to the local node. The `NodeRecord` is constructed from the peer ID and the socket address the node is advertising itself on.

We can use this to display the ENR of the local node.

### Additional 

The function should be moved to the `PeersInfo` (https://github.com/paradigmxyz/reth/pull/860) trait, that's then implemented for NetworkHandle.

See also https://github.com/paradigmxyz/reth/pull/838 and https://github.com/paradigmxyz/reth/issues/857

**Comment by mattsse** [comment]
The function should be moved to a trait, that's then implemented for `NetworkHandle`.

See https://github.com/paradigmxyz/reth/pull/838 and #857

**Comment by Evalir** [comment]
would love to handle this to unblock #849!
