### ISSUE TITLE
Integrate payload metrics in grafana dashboard

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8494]
### Describe the feature

we're missing a panel for these in the grafana dashboard

https://github.com/paradigmxyz/reth/blob/42667e1cfdcc34f3a0409d239d0f6662f0455028/crates/payload/basic/src/metrics.rs#L9-L14

I think these should go into 

https://github.com/paradigmxyz/reth/blob/42667e1cfdcc34f3a0409d239d0f6662f0455028/etc/grafana/dashboards/overview.json

**Comment by Josh-121** [comment]
please assign

**Comment by Rjected** [comment]
@Josh-121 assigned!

**Comment by onbjerg** [comment]
@stevencartavia can you comment here to let me assign you please? :)

**Comment by stevencartavia** [comment]
I can work on this :D
