### ISSUE TITLE
Enable discv5 for op in `reth-node-optimism` crate

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#8499]
### Describe the feature

Move network specific logic that enables discv5 for an op network into `reth-node-optimism` crate.

https://github.com/paradigmxyz/reth/blob/072d4225dec15ad7bed3a4cebf58c3ae27e99be6/crates/node-core/src/args/network.rs#L171-L174

https://github.com/paradigmxyz/reth/blob/072d4225dec15ad7bed3a4cebf58c3ae27e99be6/crates/node-core/src/node_config.rs#L469

**Comment by qiweiii** [comment]
can i take this?

**Comment by mattsse** [comment]
sure

we can configure this in the OP network builder:

https://github.com/paradigmxyz/reth/blob/977def880a96b0913a439bab4f2efe377f33528a/crates/optimism/node/src/node.rs#L272-L272

**Comment by qiweiii** [comment]
@mattsse @emhane please check if the pr changes are the expected solution
