### ISSUE TITLE
Add an RPC method to get the local node record

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#850]
### Describe the feature

We should add an RPC method named `admin_nodeInfo` that returns the ENR of the node. This depends on #849.

Additionally, `AdminApi` in the `reth-rpc` crate should be exported and constructable: currently it is private and impossible to construct.

### Additional context

To add the new RPC method, first extend the `AdminApiServer` trait here: https://github.com/paradigmxyz/reth/blob/main/crates/net/rpc-api/src/admin.rs

Then add the implementation for the new method here: https://github.com/paradigmxyz/reth/blob/main/crates/net/rpc/src/admin/mod.rs

The ENR should be fetched using the `NetworkHandle` in the `AdminApi` implementation.

**Comment by Evalir** [comment]
Happy to take on this as well!

**Comment by onbjerg** [comment]
@Evalir Note that this issue is blocked on #849. If you still want this task, pls comment on that issue so I can assign you :smile:

**Comment by Evalir** [comment]
Should now be unblocked with #875
