### ISSUE TITLE
Extract reth-trie-types from reth-trie

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8514]
### Describe the feature

reth-trie mixes db implementations with type definitions, which is problematic if we want to use these types in evm for different targets (risc, maybe even no_std).

hence we should extract the core types to a standalone crate, primarily the TrieUpdates type

currently this type has functions that make use of db:

https://github.com/paradigmxyz/reth/blob/f43ccc760b150854654e7364892f6ec753c17eeb/crates/trie/trie/src/updates.rs#L132-L132

or 

https://github.com/paradigmxyz/reth/blob/f43ccc760b150854654e7364892f6ec753c17eeb/crates/trie/trie/src/updates.rs#L114-L119

The triewalker functions could be inverted and implemented on triewalker instead,
for the flush function we could use a tmp wrapper type instead

**Comment by RomanHodulak** [comment]
I'd love to take this

**Comment by RomanHodulak** [comment]
Solved by #10008

Can be closed
