### ISSUE TITLE
Start the RPC in `reth node`

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#852]
### Describe the feature

We should start the RPC in the `reth node` command. Adding all namespaces (**except for `engine`**) for now is fine, and it is also OK that some of the namespaces are not fully implemented.

At a minimum we should add an `--rpc <addr>` flag that binds the RPC to the given socket address. The socket address should be parsed as we currently parse the metrics endpoint (see `--metrics`).

Alternatively, we can add these flags:

- `--rpc` to enable the RPC
- `--rpc.addr <addr>` which works as the flag mentioned above, with the difference being that it defaults to `[::]:8045`.

If the `--rpc` flag is not specified, the RPC should not be launched.

### Additional context

Blocked by https://github.com/paradigmxyz/reth/issues/604

**Comment by Evalir** [comment]
happy to take this!

**Comment by mattsse** [comment]
@Evalir the RPC will be configured here: 

https://github.com/paradigmxyz/reth/blob/bcbc3dacc799fa309f63d95593909c14eaf1a780/crates/net/rpc-builder/src/lib.rs#L75-L80

by merging all the handlers into one `RpcModule`

https://github.com/paritytech/jsonrpsee/blob/2c2abcb807c3b7688daedf8aaa3308da77cb8c11/core/src/server/rpc_module.rs#L311

first we need to address: #857 I'd start from there and try get rid of the `NetworkHandle` and instead move everything into the `network-api` traits

**Comment by Evalir** [comment]
Hey! Looking to get back to closing this, sorry for the delay. Seems #857 was just closed—do we need to do anything different here then?
