### ISSUE TITLE
Support old receipt type (state root before byzantium)

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#853]
This is more a discussion and dont forget it task.

Receipt before Byzantium contained state root and didn't have `status`, how exactly do we want to support that? calculating state root is expensive and it is best done while execution is on the way, we could just ignore it and put empty/zero value or maybe somehow hardcode it?

Part of code that checks receipt root (without stateroot within receipt this is skipped before byzantium):
https://github.com/paradigmxyz/reth/blob/e6ca4c56c6a314e5553656e5b62be3bca6801b85/crates/executor/src/executor.rs#L261-L268

**Comment by gakonst** [comment]
How does Erigon do this?

**Comment by rakita** [comment]
Geth checks the root of every block, one of the reasons why geth archive is not usable, for Erigon idk.

**Comment by gakonst** [comment]
@carver just saw your note on Reddit, should we remove that reference to Trin from the blog? apologies if it felt inaccurate.

What should we do here to better support Trin / what are you missing?

**Comment by njgheorghita** [comment]
Any update on this issue / estimated timeline until Reth might be able to support pre-byzantium receipts?

**Comment by Rjected** [comment]
> Any update on this issue / estimated timeline until Reth might be able to support pre-byzantium receipts?

Do you need this for an application? Would be good to know what the requirements are exactly

**Comment by njgheorghita** [comment]
The use case would be to re-calculate valid receipt roots for pre-byzantium blocks, which requires the `state_root` field. However, in [Trin](https://github.com/ethereum/trin) / the [Portal Network](https://www.ethportal.net/), we're moving towards using `era1` files for pre-byzantium blocks, rather than requesting the data from a client, so this is no longer needed from our side

**Comment by pedrohba1** [comment]
Hi. We would like this feature too. I think I could be able to implement it after looking how Geth handles it.
Just to be sure, [this step from geth](https://github.com/ethereum/go-ethereum/blob/95741b18448aaacacd0edd8f73a9364bd3df8c92/cmd/evm/internal/t8ntool/execution.go#L258) is related, right?

**Comment by Rjected** [comment]
> Hi. We would like this feature too. I think I could be able to implement it after looking how Geth handles it. Just to be sure, [this step from geth](https://github.com/ethereum/go-ethereum/blob/95741b18448aaacacd0edd8f73a9364bd3df8c92/cmd/evm/internal/t8ntool/execution.go#L258) is related, right?

yes, although fair warning, it's definitely a nontrivial change, and I'm still not convinced we should support this. What's the use case for pre byzantium receipts?

**Comment by pedrohba1** [comment]
> yes, although fair warning, it's definitely a nontrivial change, and I'm still not convinced we should support this. What's the use case for pre byzantium receipts?

In our flat files decoder [here](https://github.com/semiotic-ai/flat-files-decoder/blob/main/src/receipts/mod.rs#L76) we need to have  encoding that supports pre-byzantinum transactions. We did some workaround in order for it to work, however, it would be nice if Reth handled it.

Thinking about it now, just handling this functionality in `enconde_inner` in Reth should be enough, right?

**Comment by Rjected** [comment]
> > yes, although fair warning, it's definitely a nontrivial change, and I'm still not convinced we should support this. What's the use case for pre byzantium receipts?
> 
> In our flat files decoder [here](https://github.com/semiotic-ai/flat-files-decoder/blob/main/src/receipts/mod.rs#L76) we need to have encoding that supports pre-byzantinum transactions. We did some workaround in order for it to work, however, it would be nice if Reth handled it.
> 
> Thinking about it now, just handling this functionality in `enconde_inner` in Reth should be enough, right?

Yeah, I would even be open to supporting a separate pre-byzantium receipt type (which would derive rlp encodable / decodable) if necessary

**Comment by pedrohba1** [comment]
> Yeah, I would even be open to supporting a separate pre-byzantium receipt type (which would derive rlp encodable / decodable) if necessary

Neat. I will work on it. Any recommendations for this task besides the contribution guidelines?
