### ISSUE TITLE
Add a `--nat` flag to `reth node`

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#854]
### Describe the feature

It should be possible to specify what kind of NAT mechanism to use when invoking `reth node`.

The supported methods can be found here: https://github.com/paradigmxyz/reth/blob/e6ca4c56c6a314e5553656e5b62be3bca6801b85/crates/net/nat/src/lib.rs#L25

The flag should be: `--nat <method>`, where `<method>` is any of:

- `any`
- `upnp`
- `auto` (maps to `PublicIp`)
- `extip:<ip>` (maps to `ExternalIp`)
- `none` (maps to `None`)

The default should be `any`.

Ideally, the `NatResolver` enum would be re-used for the CLI to not duplicate code.

The resolution method is set on `NetworkConfigBuilder` using:

```rs
builder::discovery(
  Discv4Config::builder()
    .external_ip_resolver(Some(nat_resolution_method))
)
```

**Comment by literallymarvellous** [comment]
Would like to take this

**Comment by onbjerg** [comment]
Thanks! I've assigned you to the issue. If you feel stuck, open up a draft PR with your questions and someone will help you. If you are prevented from solving the issue, let me know and I will unassign you :smile:
