### ISSUE TITLE
Implement `set_block_gas_limit` for `EthTransactionValidatorBuilder`

### ISSUE THREAD

**Issue by eyusufatik** [paradigmxyz/reth#8550]
### Describe the feature

`EthTransactionValidator`, with its current implementation, can be used by different EVM rollups.

However, if the block gas limit of said rollup is different than Ethereum's, the transaction pool fails to return an error when a transaction with more gas limit than the rollup's block gas limit is submitted. This happens because the `block_gas_limit` field of `EthTransactionValidatorBuilder` is hard coded here:

https://github.com/paradigmxyz/reth/blob/99c951a8bdde3c1f733e569832a08c75b7183f61/crates/transaction-pool/src/validate/eth.rs#L456

An additional function `pub const fn set_block_gas_limit(mut self, block_gas_limit: u64) -> Self` for `EthTransactionValidatorBuilder` can solve this.

If concept is accepted I can open a PR.

**Comment by mattsse** [comment]
reasonable
