### ISSUE TITLE
Add `redundant_pub_crate = "warn"` clippy lint

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#8564]
### Describe the feature

At the moment, `redundant_pub_crate` clippy lint is allowed

https://github.com/paradigmxyz/reth/blob/994f98f12db30c7b45c453960ada15ba119b9557/Cargo.toml#L174

It seems it has quite a lot of findings inside the codebase. It could be useful to activate a warn for this one.

**Comment by mattsse** [comment]
hmm, pub crate functions are not accessible by other crates, I don't think this lint is very useful

**Comment by mattsse** [comment]
this would be very noisy
