### ISSUE TITLE
Move Engine API V4 capabilities to Alloy

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#8565]
### Describe the feature

These capabilities https://github.com/paradigmxyz/reth/blob/994f98f12db30c7b45c453960ada15ba119b9557/crates/rpc/rpc-engine-api/src/engine_api.rs#L28-L30
should be moved to the default list of capabilities that we import from Alloy https://github.com/alloy-rs/alloy/blob/91e8a0f84323d9744a732427f038937a4b3c01e4/crates/rpc-types-engine/src/lib.rs#L32-L46

They were added separately because we wanted to implement all changes needed for the Pectra devnet-0 ASAP, and now it's a debt.

**Comment by Vid201** [comment]
I can take this
