### ISSUE TITLE
Replace `NetworkHandle` with `network-api` traits in RPC Handler impls

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#857]
### Describe the feature

atm rpc impls rely on the `NetworkHandle` type, for example:

https://github.com/paradigmxyz/reth/blob/c4bafe809b8689a2332d7d98902dd2e15c1d5adc/crates/net/rpc/src/net/mod.rs#L10-L12

As part of #683 the `network-api` crate was introduced:

https://github.com/paradigmxyz/reth/pull/838

This will allow us to replace `NetworkHandle` with the corresponding traits.

**Comment by Evalir** [comment]
Aight, will handle this as #852 will benefit from this work as well!

**Comment by Evalir** [comment]
Aight, so will get on this early on next week, as some PRs that concern this issue have been merged. Just wanted to ask for some pointers:

> This will allow us to replace NetworkHandle with the corresponding traits.
- We'll need to add more traits right? As the current traits do not cover the whole impl for `NetworkHandle`.
- With phasing out `NetworkHandle`, I suppose we'll build many smaller `Handles` that are specialized for these traits? Happy to get a bit more info on this!

**Comment by mattsse** [comment]
> We'll need to add more traits right? As the current traits do not cover the whole impl for NetworkHandle.

yes, functions and traits, there's PeersInfo for readonly peer-related stuff, we def need something that allows us to add peers, ref `admin` namespace, which should be separate.

> With phasing out NetworkHandle, I suppose we'll build many smaller Handles that are specialized for these traits?

the main motivation for this is, that making it dependent on traits rather than the `NetworkHandle`, makes improves testability so we can write custom implementations of the traits, and we don't need to launch the actual network in order to test rpc stuff.
