### ISSUE TITLE
Add a `--bootnodes` flag for `reth node`

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#858]
### Describe the feature

Currently we always use mainnet bootnodes, but they should be resolved loading the bootnodes chainspec (should be handled in #485). We should also provide the ability to override the bootnodes by specifying a `--bootnodes` flag.

The format should be `--bootnodes <enrs>` where `<enrs>` is a comma-seperated list of Ethereum node records.

The type should be `Option<Vec<NodeRecord>>`.

### Additional context

To parse comma-separated values, clap provides [`value_delimiter`](https://docs.rs/clap/latest/clap/builder/struct.Arg.html#method.value_delimiter). Example:

```rs
struct Opts {
  #[arg(long, value_delimiter = ',')]
  nodes: Option<Vec<NodeRecord>>
}
```

**Comment by literallymarvellous** [comment]
I'd like to take this.

**Comment by onbjerg** [comment]
Thanks! I've assigned you to the issue. If you feel stuck, open up a draft PR with your questions and someone will help you. If you are prevented from solving the issue, let me know and I will unassign you :smile:
