### ISSUE TITLE
logs / logs blooms are missing (zeroes/empty) when inserting block in v0.2.0-beta.8 (and on v0.2.0-beta.7 tag too). works fine on v0.2.0-beta.6

### ISSUE THREAD

**Issue by bfdays** [paradigmxyz/reth#8581]
### Describe the bug

we have solidity bridge contracts (cannot provide source code right now, but will provide some logs) and those contracts generate events/logs. they worked perfectly on v0.2.0-beta.6 but on v0.2.0-beta.7 they stopped to generate logs on the last stage. I though it is because some bugs in v0.2.0-beta.7. this version wasnt mention in reth 'releases' section that's why we decided to wait for the version mentioned in 'releases' section in hope of fix. today we've got  v0.2.0-beta.8 but the problem persists.
I have figured out that logs blooms (used for fetching events later) are zeroed in crates/blockchain-tree/src/blockchain_tree.rs (fn insert_block) - and added "debug!("block.block.logs_bloom.0: {:?}", block.block.logs_bloom.0);" into logs attached here. As you can see there non-empty logs blooms for v0.2.0-beta.6 but for v0.2.0-beta.8 they are always 0 - hope it may help.

[v0.2.0-beta.6.txt](https://github.com/user-attachments/files/15543620/v0.2.0-beta.6.txt)
[v0.2.0-beta.8.txt](https://github.com/user-attachments/files/15543621/v0.2.0-beta.8.txt)

[SendTokens.v0.2.0-beta.6.txt](https://github.com/user-attachments/files/15543634/SendTokens.v0.2.0-beta.6.txt)
[SendTokens.v0.2.0-beta.8.txt](https://github.com/user-attachments/files/15543636/SendTokens.v0.2.0-beta.8.txt)

### Steps to reproduce

all that i can share now are the logs above. discussing the idea of passing solidity contracts with running hardhat code running them

### Node logs

```text
see 'Describe the bug' section
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

v0.2.0-beta.8 / v0.2.0-beta.6

### What database version are you on?

Current database version: 2
Local database version: 1

### Which chain / network are you on?

dev

### What type of node are you running?

Full via --full flag

### If you've built Reth from source, provide the full command you used

run --package reth --bin reth -- --chain=dev node --datadir=./datadir --dev --full --http --port=30305

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
could you please clarify where the logs are missing?
form the rpc response?

**Comment by bfdays** [comment]
> could you please clarify where the logs are missing? form the rpc response?

yes.
as you can see in SendTokens.v0.2.0-beta.6.txt returns logs/events l2BridgeContractReceivedMessageEvents for block 13 in the end, but SendTokens.v0.2.0-beta.8.txt doesnt. also checked beta.7 and the latest beta.9 - the same problem persits.

**Comment by mattsse** [comment]
Sorry, I'm not sure exactly what I should be looking for in the logs.

I see `logs` in `SendTokens.v0.2.0-beta.8.txt`

**Comment by bfdays** [comment]
@mattsse here is working contracts you can run yourself https://github.com/bfdays/sol-contracts . if you have yarn installed follow:
```
make prepare
# in separate window
make run_evm_node
# here you must have reth node running with (or whatever you like)
cargo run --package reth --bin reth -- --color=never --chain=dev node --datadir=datadir --dev --full --http --port=30305
# and to run test contracts use
make test_SendTokens
# at the end you will see error reporting the problem which doesnt exists in beta6
```

**Comment by bfdays** [comment]
fix https://github.com/paradigmxyz/reth/pull/8945
