### ISSUE TITLE
Investigate moving core rpc server types to standalone crate

### ISSUE THREAD

**Issue by leruaa** [paradigmxyz/reth#8602]
> I think next step is investigating, whether we can extract the node-core/cli/config/ traits.
> 
> a few solutions are possible here
> a) move them to node-builder
> b) move all of them to a separate crate under CLI
> c) move RethRpcConfig to rpc-builder
> 
> perhaps option c) is the most viable solution

_Originally posted by @mattsse in https://github.com/paradigmxyz/reth/pull/8597#pullrequestreview-2097204532_

**Comment by leruaa** [comment]
I'm willing to work on this.

**Comment by leruaa** [comment]
@mattsse option 3) imply moving `RpcServerArgs` to `rpc-builder` (because it impl `RethRpcConfig`). Is that ok?

https://github.com/paradigmxyz/reth/blob/a8095740fcf0e5cecfcee68a972faf096bb10389/crates/node-core/src/args/rpc_server.rs#L270

**Comment by mattsse** [comment]
not the args just the config trait

so that we can implement it for rpcserverargs

**Comment by leruaa** [comment]
@mattsse but if `RpcServerArgs` stays in node-core but `RethRpcConfig` move to rpc-builder, we'll need to keep a deps between them in order to impl `RethRpcConfig` for `RpcServerArgs` and it's what we want to remove.

So I guess option c) in your original message is not possible.

**Comment by mattsse** [comment]
you can implement traits for foreign types in the crate where the crate is defined<br>and our goal is to invert the dependency so that builder depends on core, and not the other way around
