### ISSUE TITLE
Store a copy of TaskExecutor in global static

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8612]
### Describe the feature

currently the nodebuilder entry requires:

https://github.com/paradigmxyz/reth/blob/01fd9b3c76705e582cea17774f269fe4a78d8af3/crates/node/builder/src/builder/mod.rs#L166-L166

It would be nice to obtain TaskExecutor from a global

https://github.com/paradigmxyz/reth/blob/01fd9b3c76705e582cea17774f269fe4a78d8af3/crates/tasks/src/lib.rs#L195-L205

for this we'd need to change these:

https://github.com/paradigmxyz/reth/blob/01fd9b3c76705e582cea17774f269fe4a78d8af3/crates/tasks/src/lib.rs#L171-L182

and install a global clone of Taskexecutor

**Comment by sergerad** [comment]
@mattsse I can have a crack at this
