### ISSUE TITLE
Build features only includes `reth-node-core` features

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#8623]
### Describe the feature

The generated `VERGEN_CARGO_FEATURES` uses the features passed only to `reth-node-core`, so the features displayed in grafana / --version output does not contain all the features passed to `cargo build --features ...`

This can be fixed by either passing through relevant features to the crate, even if they won't do anything, or moving the build script to the `reth` crate. cc @mattsse

**Comment by mattsse** [comment]
yeah the only reason this is still in there is because the commands use the version constant for things like client identifier/extradata

we perhaps there's a way to use a global static instead that we then set from reth binary?

ref #7576

**Comment by DaniPopes** [comment]
Fixed by https://github.com/paradigmxyz/reth/pull/9866
