### ISSUE TITLE
extract trusted peer resolve into separate function

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8637]
### Describe the feature

this should be a separate function:

https://github.com/paradigmxyz/reth/blob/b11c83cee6b58e57860f18baf47513624b53dc1d/crates/node/builder/src/launch/common.rs#L85-L97

so that we can call it from the launch ctx with another call:

https://github.com/paradigmxyz/reth/blob/b11c83cee6b58e57860f18baf47513624b53dc1d/crates/node/builder/src/launch/mod.rs#L95-L97

like `.with_resolved().await?`

FYI @sergerad

**Comment by caglaryucekaya** [comment]
I'd like to work on this
