### ISSUE TITLE
Implement `ots_getContractCreator`

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#8638]
### Describe the feature

Ref https://github.com/paradigmxyz/reth/issues/3726

This RPC method does not require a separate database index, so we can implement it without any breaking changes.

The only client that implements this RPC is Erigon, and we should use its [implementation](https://github.com/ledgerwatch/erigon/blob/2a9ead64f4b7c48016b97f5c303bf824c3d22d82/turbo/jsonrpc/otterscan_contract_creator.go#L24) as a reference.

**Comment by jsvisa** [comment]
pick this one.

**Comment by kamuik16** [comment]
would like to try this, if can someone give some helper refs maybe?
