### ISSUE TITLE
Validate ForkId when present in `Discovered` event

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#864]
### Describe the feature

followup to #863

if the forkId is present in the Discovered event (#863) then we need to check if it's valid first, same as here:

https://github.com/paradigmxyz/reth/blob/7ef2931dfcacaac411e9e50bfe9f5e958433366c/crates/net/network/src/swarm.rs#L237-L242

**Comment by TechieBoy** [comment]
On it 🫡
