### ISSUE TITLE
remove Bandwidthmeter type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8643]
### Describe the feature

this type isn't really useful because for metrics grafana/prometheus has builtin metrics for bandwidth and we don't even set metrics for these
https://github.com/paradigmxyz/reth/blob/40d8ac099f1bf9eb9640ddf0665e9c7461c0f80a/crates/net/common/src/bandwidth_meter.rs#L53-L53

## TODO
* remove type
* remove usage

**Comment by Quertyy** [comment]
Can I take this one?

**Comment by mattsse** [comment]
assigned, ty 🙏

**Comment by kamuik16** [comment]
> Can I take this one?

Hey @Quertyy! I already have made much progress on this, can I take this one, please?
