### ISSUE TITLE
Remove `HeaderSyncMode::Continuous`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8651]
We probably do not need `HeaderSyncMode` as it was an artifact of when some hive tests relied on block announcements in p2p for the other client to sync.

ref https://github.com/ethereum/hive/pull/1115

Most tests use the engine API now, so we should remove the `debug.continuous` flag and remove the sync mode enum variant.

**Comment by PelleKrab** [comment]
I can take this one.
