### ISSUE TITLE
`op-reth` does not forward raw transactions to the Base mainnet sequencer

### ISSUE THREAD

**Issue by BowTiedDevil** [paradigmxyz/reth#8661]
### Describe the bug

After starting `op-reth` with the `--rollup.sequencer-http` argument specified in the [Reth Book's OP Stack page](https://reth.rs/run/optimism.html), raw transactions are not forwarded to the sequencer.

When running with debug level verbosity (`-vvvv`), the node does not display any messages about raw transaction forwarding.

The node is receiving the local transaction, and it persists in the local txpool across restarts. Re-submitting the transaction results in "already known" errors. Re-submitting with an increased priority fee succeeds, but the transaction is still not forwarded to the sequencer.

Submitting the same transaction to an external RPC succeeds, so the formatting of the transaction is not at fault.

### Steps to reproduce

Node configuration (Docker container): 

```
op-reth node \
        --full \
        --chain base \
        --datadir /data \
        --rollup.sequencer-http https://mainnet-sequencer.base.org \
        --rollup.disable-tx-pool-gossip \
        --port 30305 \
        --discovery.port 30305 \
        --enable-discv5-discovery \
        --discovery.v5.addr 0.0.0.0 \
        --discovery.v5.port 30306 \
        --discovery.v5.port.ipv6 30306 \
        --ipcpath /ipc/reth.ipc \
        --http \
        --http.port 8547 \
        --http.corsdomain "*" \
        --http.api all \
        --ws \
        --ws.port 8548 \
        --ws.origins "*" \
        --ws.api all \
        --authrpc.jwtsecret /jwt/jwt.hex \
        --authrpc.port 9551
```

I am submitting raw transactions with this simple Python script my local node and to the external Ankr endpoint as needed:

```
import dotenv
import eth_account
import eth_account.account
import web3

CONFIG: dict = dotenv.dotenv_values("base.env")
FROM_ACCT = CONFIG["OPERATOR_ADDRESS"]
PKEY = CONFIG["OPERATOR_PRIVATE_KEY"]

w3 = web3.Web3(web3.HTTPProvider("http://localhost:8547"))
# w3 = web3.Web3(web3.HTTPProvider("https://rpc.ankr.com/base"))

tx = {
    "from": FROM_ACCT,
    "to": FROM_ACCT,
    "chainId": w3.eth.chain_id,
    "value": 0,
    "nonce": w3.eth.get_transaction_count(FROM_ACCT),
    "gas": 21_000,
    "type": 2,
    "maxFeePerGas": int(0.1 * 10**9),
    "maxPriorityFeePerGas": 50,
}

signed_tx = eth_account.Account.sign_transaction(
    transaction_dict=tx, private_key=PKEY
)

tx_hash = w3.eth.send_raw_transaction(signed_tx.rawTransaction)
print(f"{tx_hash=}")
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.2.0-beta.9
Commit SHA: 7b435e0
Build Timestamp: 2024-06-06T21:54:15.346853593Z
Build Features: jemalloc,optimism
Build Profile: maxperf

### What database version are you on?

Current database version: 2
Local database is uninitialized

### Which chain / network are you on?

base

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks for filing this,

this was indeed ignored...

sorry about this
