### ISSUE TITLE
ExEx notification is sent before state is written

### ISSUE THREAD

**Issue by frisitano** [paradigmxyz/reth#8696]
### Describe the bug

In the `ExecutionStage` the `ExExNotification` is sent before the updated state is written to storage. As such we could experience a race condition in which the `ExEx` does some lookup associated with the notification but the corresponding state has not been written yet.  I have not tried to create a race condition but I think it is sensible to address this in any case. As a solution I would propose that state is written to storage before the `ExExNotification` is sent. 

Reference:
https://github.com/paradigmxyz/reth/blob/70b6bc45ad9c61ef1e64697d59fb975169df2df4/crates/stages/stages/src/stages/execution.rs#L281-L306

### Steps to reproduce

N/A

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

master

### What database version are you on?

N/A

### Which chain / network are you on?

N/A

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment]
this was a deliberate choice we forgot to document - the reason it is like this is simply that we'd have to have the entire range of blocks + state diffs + plain state in memory for the entire duration of the stage, which would massively increase the memory requirement.

**Comment by frisitano** [comment]
> this was a deliberate choice we forgot to document - the reason it is like this is simply that we'd have to have the entire range of blocks + state diffs + plain state in memory for the entire duration of the stage, which would massively increase the memory requirement.

Understood, that makes sense. From a functional perspective is it correct that this could yield race conditions if the exex tries to invoke some provider for a block associated with a notification who's state has not been committed due to the stage not being complete? This would appear to be undesirable behaviour and break the functionality of ExEx's requiring providers.

**Comment by mattsse** [comment]
this is a very good point, although this is mostly an issue for historical syncing.

we need to find a solution for this and make it possible to get notified once the state on disk is updated

**Comment by onbjerg** [comment]
we can reverse the decision but i would just like to point out that we designed with this assumption in mind (you cannot rely on plain state from db) as we agreed on:) if you need access to some state for a specific account it is possible to reconstruct the state from the notifications, as they yield both the latest plain state + the account changesets

**Comment by frisitano** [comment]
Just to add some additional context here we may want to wait until the full pipeline is complete (including merkle hashing). I have a particular use case in which I want to generate block witnesses (for which I will be introducing an API) and as such will require the latest merkle data as well as state (reverts).

**Comment by shekhirin** [comment]
@frisitano if we wait until completion before sending the notifications, it means that ExExes will start syncing only once the node finishes syncing, increasing the total time required to sync the node and all ExExes. We made a decision to send notifications ASAP from the Execution stage, but it comes at the expense of hashed state, merkle, transaction lookup and history stages data not being available.

There's another downside to waiting until the pipeline is complete: if you're running a full node, we will not be able to replay the transactions, including all reverts, because the full node doesn't persist changesets.

**Comment by frisitano** [comment]
> @frisitano if we wait until completion before sending the notifications, it means that ExExes will start syncing only once the node finishes syncing, increasing the total time required to sync the node and all ExExes. We made a decision to send notifications ASAP from the Execution stage, but it comes at the expense of hashed state, merkle, transaction lookup and history stages data not being available.

Ok that makes sense. So just to clarify for my understanding. When syncing, each stage of the pipeline is run to completion to the tip of the chain before the next stage is run? So in this case the execution stage will execute all blocks to the tip before hashed state, merkle, history, etc stages are run? 

> There's another downside to waiting until the pipeline is complete: if you're running a full node, we will not be able to replay the transactions, including all reverts, because the full node doesn't persist changesets.

Just for my own personal understanding why will immediate emission enable the full node to replay transactions?

**Comment by shekhirin** [comment]
> When syncing, each stage of the pipeline is run to completion to the tip of the chain before the next stage is run? So in this case the execution stage will execute all blocks to the tip before hashed state, merkle, history, etc stages are run?

correct

> Just for my own personal understanding why will immediate emission enable the full node to replay transactions?

It's the other way around: if you emit the notifications after all stages are completed, you will need to somehow get the state diffs (reverts) for past blocks, but we don't store them in the full node.
