### ISSUE TITLE
feature gate secp256k1 in reth-network-peers

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8700]
### Describe the feature

secp256k1 usage can be problematic for certain usecases and should be feature-gated

## TODO
* introduce `secp256k1` feature in reth-network-peers and put usage behind feature
* disable default features in workspace for reth-network-peers and enable where required

**Comment by PanGan21** [comment]
Hey @mattsse . I gave it a try in #8712  and looking for reviews 🙂
