### ISSUE TITLE
Building `reth-primitives` fails when consuming `reth` as a library target

### ISSUE THREAD

**Issue by jmcph4** [paradigmxyz/reth#8713]
### Describe the bug

In bluealloy/revm#1143, the signature for `validate_initial_tx_gas` was changed to accept an additional parameter for the EOF initcodes. As of [Reth 0.2.0-beta.9](https://github.com/paradigmxyz/reth/releases/tag/v0.2.0-beta.9), when calculating intrinsic gas usage of a transaction, the pre-EOF interface is used (i.e., only four parameters are provided to `validate_initial_tx_gas`).

https://github.com/paradigmxyz/reth/blob/7b435e0d6dede497dca211090d95a4cfa387dd1b/crates/primitives/src/revm/compat.rs#L28-L40

To achieve this, Reth patches the various `revm-*` crates:

https://github.com/paradigmxyz/reth/blob/7b435e0d6dede497dca211090d95a4cfa387dd1b/Cargo.toml#L453-L457

When building `reth-primitives` directly, via `cargo build -p reth-primitives`, this works; however, breaks when relying on Reth as an upstream dependency as [Git-based dependencies cannot be transitively patched](https://stackoverflow.com/a/72261235/8028639).

This is fixed by not hiding Reth's dependency on a specific commit by patching:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index b281d4e7d..4f159de81 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -325,8 +325,8 @@ reth-trie = { path = "crates/trie/trie" }
 reth-trie-parallel = { path = "crates/trie/parallel" }
 
 # revm
-revm = { version = "9.0.0", features = [ "std", "secp256k1", "blst", ], default-features = false }
-revm-primitives = { version = "4.0.0", features = [ "std", ], default-features = false }
+revm = { git = "https://github.com/bluealloy/revm", rev = "a28a543", features = [ "std", "secp256k1", "blst" ], default-features = false }
+revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "a28a543", features = [ "std", ], default-features = false }
 revm-inspectors = { git = "https://github.com/paradigmxyz/evm-inspectors", rev = "53aa2b2" }
 
 # eth
@@ -455,9 +455,3 @@ proptest-derive = "0.4"
 serial_test = "3"
 similar-asserts = "1.5.0"
 test-fuzz = "5"
-
-[patch.crates-io]
-revm = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }
-revm-interpreter = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }
-revm-precompile = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }
-revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }
```

### Steps to reproduce

```
$ rustup override set nightly
$ cat src/main.rs
#![feature(async_closure)]
use std::sync::Arc;

use clap::Parser;
use reth::{
    builder::{InitState, NodeHandle, WithLaunchContext},
    cli::Cli,
    commands::node::NoArgs,
};
use reth_db::DatabaseEnv;
use reth_node_ethereum::EthereumNode;

fn main() -> eyre::Result<()> {
    Cli::<NoArgs>::parse().run(
        async move |builder: WithLaunchContext<Arc<DatabaseEnv>, InitState>, _args| {
            let NodeHandle {
                node,
                node_exit_future,
            } = builder.node(EthereumNode::default()).launch().await?;
            node.task_executor.spawn(Box::pin(async move {
                println!("Hello, world!");
            }));

            node_exit_future.await
        },
    )?;

    Ok(())
}
$ cat Cargo.toml
[package]
name = "foobar"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
eyre = "0.6.12"
pretty_env_logger = "0.5.0"
reth = { git = "https://github.com/paradigmxyz/reth", rev = "7b435e0" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "7b435e0" }
reth-db = { git = "https://github.com/paradigmxyz/reth", rev = "7b435e0" }
$ cargo run
error[E0061]: this function takes 5 arguments but 4 arguments were supplied
   --> /home/jmcph4/.cargo/git/checkouts/reth-36d3ea1d1152b20c/7b435e0/crates/primitives/src/revm/compat.rs:39:5
    |
39  |     validate_initial_tx_gas(spec_id, input, kind.is_create(), access_list)
    |     ^^^^^^^^^^^^^^^^^^^^^^^----------------------------------------------- an argument of type `&[alloy_primitives::Bytes]` is missing
    |
note: function defined here
   --> /home/jmcph4/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-interpreter-5.0.0/src/gas/calc.rs:356:8
    |
356 | pub fn validate_initial_tx_gas(
    |        ^^^^^^^^^^^^^^^^^^^^^^^
help: provide the argument
    |
39  |     validate_initial_tx_gas(spec_id, input, kind.is_create(), access_list, /* &[alloy_primitives::Bytes] */)
    |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Compiling hyper-util v0.1.5
error[E0063]: missing fields `eof_initcodes` and `eof_initcodes_hashed` in initializer of `TxEnv`
   --> /home/jmcph4/.cargo/git/checkouts/reth-36d3ea1d1152b20c/7b435e0/crates/primitives/src/revm/env.rs:180:14
    |
180 |     env.tx = TxEnv {
    |              ^^^^^ missing `eof_initcodes` and `eof_initcodes_hashed`

$ echo $?
101
```

### Node logs

```text
N/A
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

[0.2.0-beta.9 (`7b435e0`)]()

### What database version are you on?

N/A

### Which chain / network are you on?

N/A

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

N/A

### If you've built Reth from source, provide the full command you used

`cargo run`

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by jmcph4** [comment]
Propagating the patch locally (by copying it into the `Cargo.toml` of the downstream project) also seems to work.

**Comment by mattsse** [comment]
yeah, we currently use a revm patch, see 

https://github.com/paradigmxyz/reth/blob/40fc19f0851b595e113485ebb6d9476732ed4f97/Cargo.toml#L459-L463

**Comment by jmcph4** [comment]
> yeah, we currently use a revm patch, see
> 
> https://github.com/paradigmxyz/reth/blob/40fc19f0851b595e113485ebb6d9476732ed4f97/Cargo.toml#L459-L463
> 
> we'll get rid of this with a new revm release

This should be fixed prior to 1.0. Given that we're already at a release candidate and that no such `revm` release has occurred yet, I don't really think this should have been closed -- especially given that use as a library is an explicit design goal of Reth.

**Comment by undenuicap** [comment]
an empty project only with this fails :-(

[dependencies]
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.0-rc.2" }

[patch.crates-io]
revm = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }
revm-interpreter = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }
revm-precompile = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }
revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }

**Comment by shekhirin** [comment]
@undenuicap we will remove the patches soon, in the meantime please use this revision (from [Cargo.toml](https://github.com/paradigmxyz/reth/blob/main/Cargo.toml))
```toml
[patch.crates-io]
revm = { git = "https://github.com/bluealloy/revm.git", rev = "41e2f7f" }
revm-interpreter = { git = "https://github.com/bluealloy/revm.git", rev = "41e2f7f" }
revm-precompile = { git = "https://github.com/bluealloy/revm.git", rev = "41e2f7f" }
revm-primitives = { git = "https://github.com/bluealloy/revm.git", rev = "41e2f7f" }
```
