### ISSUE TITLE
Check no std in CI

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#8716]
### Describe the feature

Some crates will have no std support, see #8705 

Currently we don't check that these actually compile with `--no-default-features` (i.e. no std) in CI, but we should.

For resolving this issue, add a `cargo check` pass for all crates in the workspace with `--no-default-features`

**Comment by JackG-eth** [comment]
i will take this as part of the tracker

**Comment by DaniPopes** [comment]
Note: should be careful in not running *only tests* with --no-default-features, since the crates will be built with cfg(test) and other features enabled only through dev-dependencies. These enable std regardless of user-specified features
