### ISSUE TITLE
Rename `BundleStateWithReceipts`

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#8727]
Think time to rename this to `BundleState` and have `with_receipts` and `with_requests` methods?

_Originally posted by @gakonst in https://github.com/paradigmxyz/reth/pull/8709#pullrequestreview-2108311231_

**Comment by tcoratger** [comment]
Won't this create a naming clash with `BundleState` coming from `revm::db::states::BundleState` which is also included in it?

We could do `use revm::db::states::BundleState as RevmBundleState` but if we have to do it in all files concerned that might be a lot of overhead, wdyt?

**Comment by rakita** [comment]
BundleStateExt could be nicer?

**Comment by mattsse** [comment]
what this type represents is the outcome of executed block(s), it is not limited to state, hence bundle is confusing

this should be called BlockExecutionOutcome imo
