### ISSUE TITLE
Make `NetworkConfig` serializable

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#873]
### Describe the feature

The idea of the `Config` struct used in the CLI is that it is a thin wrapper around existing config structs to the extent possible to lower maintenance, i.e. instead of having to add new config in 2 places, you just add it in one.

Currently though, it is not possible to serialize or deserialize the `NetworkConfig` struct (or `NetworkConfigBuilder`) because:

1. It takes a generic parameter `C` as a stand-in for the client.
2. It holds a `Box<dyn BlockImport>`

There are a few possible paths here:

1. We try to make `NetworkConfigBuilder` serializable by moving the non-serializable parts into the `build` function, or
2. We make `NetworkConfig` serializable, which means the networking components need to take the unserializable things separately from the config,
3. We make a new slimmer version of `NetworkConfig` that is `Serialize` and `Deserialize`, and we have `NetworkConfig` hold one of these

### Additional context

As part of this issue we would also need to deduplicate a few things. Currently we have a `PeersConfig` as part of the `Config` struct, but this is also present on `NetworkConfig`.

**Comment by leruaa** [comment]
I can take this on.
