### ISSUE TITLE
Deduplicate alloy dependencies

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#8735]
### Describe the feature

currently alloy is duplicated through foundry-blob-explorers in the exex-rollup example

cc @shekhirin 

### Additional context

see https://github.com/paradigmxyz/reth/blob/bd1f5ba8eb7a8b449f7b1b8a58c833047ad540df/Cargo.lock#L171-L201

**Comment by mattsse** [comment]
this will go away after alloy release
