### ISSUE TITLE
Simplify `reth db drop`

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#874]
### Describe the feature

Currently the `reth db drop` command requires us to update it with an up-to-date list of tables, but in reality we can just delete the file pointed to by the `--db` flag, which would lower maintenance burden.

### Additional context

The command is in `bin/reth/src/db/mod.rs`

**Comment by mpaulucci** [comment]
Hi, I'm just starting on this project and would be interested in taking this one. I that ok?

**Comment by onbjerg** [comment]
Yep! I've assigned you to the issue. If you feel stuck, open up a draft PR with your questions and someone will help you. If you are prevented from solving the issue for any reason, let me know and I will unassign you :smile:

**Comment by mpaulucci** [comment]
Thank you!

**Comment by gakonst** [comment]
I guess we'd still want the previous functionality if we wanted to just drop a single table?

**Comment by onbjerg** [comment]
Yes @gakonst
