### ISSUE TITLE
In Memory Engine Tree state

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8745]
for the engine rewrite we need to decouple disk writes from state updates

Ideal we keep a larger range of blocks in memory and flush on demand.

This means to process engine and rpc requests, we need to able to access state at any block height.

This is likely similar to the current blockchaintree internals but must be more efficient wrt state root.

**Comment by emhane** [comment]
Ref https://github.com/sigp/lighthouse/blob/f1d88ba4b1256e084d3a2a547e0ce574b896246c/beacon_node/store/src/hot_cold_store.rs#L45-L83
