### ISSUE TITLE
Replace `as_str`-based static files duration metrics with enums

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8758]
Using an enum for each type step of the static files, like in `MakeCanonicalMetrics`:
https://github.com/paradigmxyz/reth/blob/a5d825edb3069e5a80f0de6d003108f9fc32c6ef/crates/blockchain-tree/src/metrics.rs#L95-L122

Is IMO much more clear than how we do it in `StaticFileProviderOperationMetrics`:
https://github.com/paradigmxyz/reth/blob/a5d825edb3069e5a80f0de6d003108f9fc32c6ef/crates/storage/provider/src/providers/static_file/metrics.rs#L108-L127

So we should switch to doing something similar for `StaticFileProviderOperationMetrics`

**Comment by 9547** [comment]
Hi @Rjected I want to pick this one

**Comment by Rjected** [comment]
re: https://github.com/paradigmxyz/reth/pull/8782#issuecomment-2166164977

Going to close this issue, will open up another one for the actually desired approach, which will likely involve adding some additional info about structs in `metrics-derive`, to make it easier to navigate to metrics structs and use labels.
