### ISSUE TITLE
Use proper conversion errors for OP tx variant

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8777]
### Describe the feature

ref #8763

blocked by https://github.com/alloy-rs/alloy/pull/875

## TODO
* use proper error variants here: 

https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/alloy_compat.rs#L232-L233

**Comment by PelleKrab** [comment]
I can take this.  Am I good to update alloy_compat.rs make a pr and then just wait for the Alloy version to be bumped?

**Comment by PelleKrab** [comment]
nvm, it seems like this was already taken care of in #8763 37d51c4bb39cf2d01ee451a65d732b672c2d164a.
