### ISSUE TITLE
Broken panels `reth-mempool` dashboard

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#8778]
### Describe the feature

Some metrics, ending `_messages_sent_total` and `_messages_received_total`, in `reth-mempool` panel don't exist in the codebase. 

Panels are broken

<img width="853" alt="Screenshot 2024-06-12 at 19 20 05" src="https://github.com/paradigmxyz/reth/assets/58548332/8ab6f21c-b1e9-4298-8ca7-f14182d6c53d">

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/pull/8806
```

**Comment by mattsse** [comment]
is this because the grafana is outdated or the names are incorrect?

**Comment by emhane** [comment]
no, literally don't exist in the codebase except for grafana file, changed here https://github.com/paradigmxyz/reth/pull/8263/files#diff-58ab453540dbae6ba2cb046b1afadb417121d7d00c4df97ef7e05edfeb4c39c3 @mattsse

**Comment by mattsse** [comment]
are those not

https://github.com/paradigmxyz/reth/pull/8263/files#diff-9769b7102656bf897b26be32c87beda0d80109a4a3194c3c382017ad888d0dbaR257-R268 

?

**Comment by emhane** [comment]
yes, I think it's related to those too, but the target `reth_network_transaction_pool` can't be found for example

**Comment by emhane** [comment]
fixed one of the panels, can't figure out what's wrong with the `All transactions` panel

**Comment by mattsse** [comment]
this appears to be fixed
