### ISSUE TITLE
Disable reth-primitives default features in workspace

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8793]
Currently a few features are enabled by default

https://github.com/paradigmxyz/reth/blob/a80f0126dd76e0e25f500a37143b41077e1f8256/crates/primitives/Cargo.toml#L99-L99

reth-primitives is used by a few crates that don't need those

## TODO

* disable default features in workspace and enable where required, check via `cargo hack check`
https://github.com/paradigmxyz/reth/blob/a80f0126dd76e0e25f500a37143b41077e1f8256/Cargo.toml#L307-L307

FYI @JackG-eth

**Comment by JackG-eth** [comment]
Will take this

**Comment by kunal365roy** [comment]
@JackG-eth you still working on this? Happy to take if not

**Comment by JackG-eth** [comment]
@kunal365roy  Hey sorry yes, there are just some on going discussions on the best way to handle the "zstd-codec" dependency.
