### ISSUE TITLE
eth p2p types abstraction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8825]
once we support custom p2p types, we also need to make the eth-wire-types generic over txs/blocks.

ideally this solution also makes it possible to incorporate nuances e.g bnb 
https://github.com/bnb-chain/reth/tree/develop/crates/net/eth-wire-types/src 

we should start this with the `BlockBodies` type

**Comment by mattsse** [comment]
@yutianwu could you perhaps point me to the bsc differences on the eth rlpx protocol level

iirc blocks are different and some message ids?

**Comment by pythonberg1997** [comment]
There's an extra filed `pub sidecars: Option<BlobSidecars>` after `withdrawals` and no `requests` on bsc. The `BlobSidecars` is like:
```
pub struct BlobSidecars(Vec<BlobSidecar>);

pub struct BlobSidecar {
    pub blob_transaction_sidecar: alloy_eips::eip4844::BlobTransactionSidecar,
    pub block_number: U256,
    pub block_hash: B256,
    pub tx_index: u64,
    pub tx_hash: B256,
}
```

@mattsse

**Comment by unclezoro** [comment]
> There's an extra filed `pub sidecars: Option<BlobSidecars>` after `withdrawals` and no `requests` on bsc. The `BlobSidecars` is like:
> 
> ```
> pub struct BlobSidecars(Vec<BlobSidecar>);
> 
> pub struct BlobSidecar {
>     pub blob_transaction_sidecar: alloy_eips::eip4844::BlobTransactionSidecar,
>     pub block_number: U256,
>     pub block_hash: B256,
>     pub tx_index: u64,
>     pub tx_hash: B256,
> }
> ```
> 
> @mattsse

This impact the `NewBlockPacket`, `BlockBody` packet regarding p2p.

**Comment by unclezoro** [comment]
I guess the `typed_transaction` is an good abstract example? Ethereum can extend new transaction type without breaking anything.  Maybe introduce `typed block body`, `typed block` so anyone depends on Reth can custom it.

**Comment by mattsse** [comment]
marking this as completed, any further improvements will be tracked separately
