### ISSUE TITLE
Tracking: eth_simulateV1

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8844]
eth_simulateV1 does not seem too difficult to support, we basically need to do two things to support it:

```[tasklist]
### eth_simulateV1
- [ ] https://github.com/alloy-rs/alloy/issues/901 , then
- [ ] Implement eth_simulateV1 in reth
```

**Comment by JackG-eth** [comment]
Will take this :)

**Comment by dhruvmalik007** [comment]
Thanks for followup . I am available as assignee as soon as the PR for the request /response types on the alloy is finished.

**Comment by Blaeaea** [comment]
> Thanks for followup . I am available to work on this as soon as the PR for the request /response types on the alloy is finished.

PR is merged, feel free to start it

**Comment by GHowlett** [comment]
@dhruvmalik007 have you already taken / started this issue?

**Comment by dhruvmalik007** [comment]
Hi @GHowlett I have started it developing localy the function call but only have time on weekends to push the PR. If I don't have time later this weekend , I will share the progress to make you assignee

**Comment by mattsse** [comment]
#8281 contains sufficient context, closing in favor of #8281
