### ISSUE TITLE
not announcing peering/discovery on correct ports when using --discovery.port

### ISSUE THREAD

**Issue by jmo-staked** [paradigmxyz/reth#8851]
### Describe the bug

reth doesn't announce it is listening on `--port 30303` when you also have `--discovery.port 30304` set. reth will only announce you are using port `30304` even though it binds locally to both 30303 & 30304

I'd expect my enode to be announced as (as geth does): `"enode": "enode://...@1.2.3.4:30303?discport=30304"`

and for `admin.nodeInfo` to report:
```json
    "ports": {
      "discovery": 30304,
      "listener": 30303
    },
```

for ref: running inside kubernetes with an LB doesn't allow you to expose both TCP & UDP on the same port, so can't use the default, combined 30303 TCP/UDP discovery/peering setup

### Steps to reproduce

1. start reth including flags `--port 30303 --discovery.port 30304`
2. check `ss/netstat` to see reth is indeed listening TCP on 30303 and UDP on 30304
```bash
$ ss -tulpn
Netid           State             Recv-Q            Send-Q                       Local Address:Port                        Peer Address:Port           Process                                 
udp             UNCONN            0                 0                                  0.0.0.0:30304                            0.0.0.0:*               users:(("reth",pid=1,fd=15))           
tcp             LISTEN            0                 1024                               0.0.0.0:30303                            0.0.0.0:*               users:(("reth",pid=1,fd=14))
```
3. curl rpc to get node info:
```bash
curl -s --header 'Content-Type: application/json' -d '{"jsonrpc": "2.0","method": "admin_nodeInfo","params": [],"id": ""}' localhost:8545 | jq

{
  "jsonrpc": "2.0",
  "result": {
    "id": "...",
    "name": "reth/v0.2.0-beta.9-7b435e0/x86_64-unknown-linux-gnu",
    "enode": "enode://...@1.2.3.4:30304",
    "enr": "...",
    "ip": "1.2.3.4",
    "ports": {
      "discovery": 30304,
      "listener": 30304
    },
    "listenAddr": "1.2.3.4:30304",
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.2.0-beta.9
Commit SHA: 7b435e0

### What database version are you on?

Current database version: 2

### Which chain / network are you on?

private network

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks for flagging, this is indeed misconfigured in the setup resulting in incorrect reporting via rpc
