### ISSUE TITLE
remove test-vectors command

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8856]
### Describe the feature

this command pulls in proptest etc

can either be removed or should be put behind a feature flag or moved to test-utils

https://github.com/paradigmxyz/reth/blob/22e6afe3f1c758c012d54586f1efb8750ebce165/bin/reth/src/commands/test_vectors/mod.rs#L7-L12

wdyt @rkrasiuk @joshieDo

**Comment by DaniPopes** [comment]
https://github.com/paradigmxyz/reth/pull/9329
