### ISSUE TITLE
reth-revm no-std support

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8865]
support no-std in reth-revm

**Comment by JosepBove** [comment]
I can take this (btw the linear link is not accessible)

**Comment by JackG-eth** [comment]
> I can take this (btw the linear link is not accessible).
> 
> Update: I've seen @JackG-eth is taking this issues, let's wait for him to say if he wants it before assigning it to me.

Hey!

I'm happy to let you pick this up if you want to. Ping me if you have any questions as i'm well versed in it now :)

**Comment by kamuik16** [comment]
> > I can take this (btw the linear link is not accessible).
> > Update: I've seen @JackG-eth is taking this issues, let's wait for him to say if he wants it before assigning it to me.
> 
> Hey!
> 
> I'm happy to let you pick this up if you want to. Ping me if you have any questions as i'm well versed in it now :)

Hey! I am also taking an issue of this kind. would you mind sharing your previous PRs as a reference we can take a look at? Thanks!

**Comment by JackG-eth** [comment]
> > > I can take this (btw the linear link is not accessible).
> > > Update: I've seen @JackG-eth is taking this issues, let's wait for him to say if he wants it before assigning it to me.
> > 
> > 
> > Hey!
> > I'm happy to let you pick this up if you want to. Ping me if you have any questions as i'm well versed in it now :)
> 
> Hey! I am also taking an issue of this kind. would you mind sharing your previous PRs as a reference we can take a look at? Thanks!

Sure, heres a few:

https://github.com/paradigmxyz/reth/pull/8792
https://github.com/paradigmxyz/reth/pull/8729
https://github.com/paradigmxyz/reth/pull/8817

**Comment by JosepBove** [comment]
Any ideas on how to do no-std for use std::time::Duration;?

**Comment by kamuik16** [comment]
> Any ideas on how to do no-std for std::time::Duration @JackG-eth ?

you can use [this](https://doc.rust-lang.org/core/time/struct.Duration.html), if I'm not wrong.

**Comment by JosepBove** [comment]
Oh yeah, somehow I didn't find it. Thanks
