### ISSUE TITLE
clippy: add `clippy::needless_pass_by_value` warn rule

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#8886]
### Describe the feature

Currently, the Clippy lint `clippy::needless_pass_by_value` is not enabled. This lint suggests passing function arguments by reference instead of by value where possible, promoting flexibility and potentially reducing unnecessary allocations.

### Details

- **Clippy Lint Documentation**: [clippy::needless_pass_by_value](https://rust-lang.github.io/rust-clippy/master/#/needless_pass_by_value?groups=nursery,pedantic)
- **Expected Benefits**: By passing arguments by reference (`&T`) rather than by value (`T`), we can optimize code by avoiding unnecessary copying and allocations. This can lead to better performance and more efficient memory usage in certain scenarios.

It could be nice to add it as a warn and solve the positives.

**Comment by shekhirin** [comment]
https://github.com/paradigmxyz/reth/pull/9197#issuecomment-2206609441
