### ISSUE TITLE
move calculate_intrinsic_gas_after_merge to txpool eth validator

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8899]
### Describe the feature

this is only used in the eth validator:

https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/revm/compat.rs#L31-L43

and should be moved there, this means the txpool would need the revm-interpreter dep

**Comment by kamuik16** [comment]
would like to work on this!

**Comment by mattsse** [comment]
only used here

https://github.com/paradigmxyz/reth/blob/2219d7d23e3b68118652ad5764005b56bb0dd1f3/crates/transaction-pool/src/validate/eth.rs#L718-L718

we can simply remove the function and inline it in there
