### ISSUE TITLE
Implement ots_getTransactionBySenderAndNonce

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8905]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/2219d7d23e3b68118652ad5764005b56bb0dd1f3/crates/rpc/rpc-api/src/otterscan.rs#L77-L83

this should be very similar to #8638

and would likely require some additional provider trait functions that give access to the indexes + tracing

but we can start this by checking the pool:

https://github.com/paradigmxyz/reth/blob/2219d7d23e3b68118652ad5764005b56bb0dd1f3/crates/transaction-pool/src/traits.rs#L335-L340

**Comment by PelleKrab** [comment]
I can take this one.

**Comment by jsvisa** [comment]
Hi @PelleKrab, kindly ask are you been working on this feature, if not may I pick this?

**Comment by PelleKrab** [comment]
> Hi @PelleKrab, kindly ask are you been working on this feature, if not may I pick this?

Yeah, I have been working on it, but I have been busy, so feel free to take it.  I got a little stuck on implementing the function into eth.rs, but I'm not sure if that is the correct approach.  Let me know if you need any help.
