### ISSUE TITLE
Ability to specify labels through `metrics-derive`

### ISSUE THREAD

**Issue by akirillo** [paradigmxyz/reth#892]
### Describe the feature

It'd be nice to have the `metrics-derive` crate expose an ability to instantiate a metrics struct with [labels](https://docs.rs/metrics/latest/metrics/struct.Label.html) specified, in the cases where there are multiple instances of the same metrics struct with the same scope.

An example of this is what's being worked on in #844, where the `BandwidthMeterMetrics` struct is instantiated for each stream with a peer. For each instance, the scope is dynamically set as `"bandwidth_session"`, but it wouldn't help much to set it to something like `"bandwidth_session_{session_id}"` as these would all get picked up as different metrics downstream by Prometheus / other.

### Additional context

I think an approach to this could be to add a function `new_with_labels` to the `quote!` blocks generated for `MetricsScope::Static` and `MetricsScope::Dynamic` in `crates/metrics/metrics-derive/src/expand.rs`, which calls the `#registrar` function with a provided array of K,V tuples for labels as in the [`register_counter` example](https://docs.rs/metrics/latest/metrics/macro.register_counter.html#example):
```rust
// We can also pass labels by giving a vector or slice of key/value pairs.  In this scenario,
// a unit or description can still be passed in their respective positions:
let dynamic_val = "woo";
let labels = [("dynamic_key", format!("{}!", dynamic_val))];
let counter = register_counter!("some_metric_name", &labels);
```

**Comment by mattsse** [comment]
if we have them dynamic, then the number of different metrics would just grow over time?
for example for individual peers

**Comment by akirillo** [comment]
> if we have them dynamic, then the number of different metrics would just grow over time?
> 
> for example for individual peers

Yes, if we use different labels for each instance. This is what we would want, no? W.g. when metering bandwidth per peer.

It makes downstream consumption in e.g. Grafana quite nice because you can perform operations (e.g. aggregations) on a single metric name with arbitrary grouping on the metric's label values
