### ISSUE TITLE
Simplify OptimismGenesis Info extraction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8952]
### Describe the feature

with alloy 0.1.2 we can simplify this:

https://github.com/paradigmxyz/reth/blob/590356b3415cffec09f10189ff0ec006d9447d04/crates/chainspec/src/spec.rs#L1398-L1398

and can use the `Otherfields` API to extract all fields:

https://alloy-rs.github.io/alloy/alloy/rpc/types/serde_helpers/struct.OtherFields.html#method.deserialize_as

**Comment by Vid201** [comment]
I can take this
