### ISSUE TITLE
op-node failed to run in --dev mode

### ISSUE THREAD

**Issue by jsvisa** [paradigmxyz/reth#8956]
### Describe the bug

`op-node --dev --dev.block-time=5s` failed to launch 

### Steps to reproduce

`op-node --dev --dev.block-time=5s` failed to launch 

### Node logs

```text
2024-06-19T15:47:06.529267Z  INFO Starting consensus engine
thread 'tokio-runtime-worker' panicked at crates/evm/execution-types/src/execution_outcome.rs:181:9:
This should not be called in optimism mode. Use `optimism_receipts_root_slow` instead.
stack backtrace:

   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: reth_execution_types::execution_outcome::ExecutionOutcome::receipts_root_slow
   3: <reth_auto_seal_consensus::task::MiningTask<Client,Pool,Executor,Engine> as core::future::future::Future>::poll::{{closure}}
   4: <reth_auto_seal_consensus::task::MiningTask<Client,Pool,Executor,Engine> as core::future::future::Future>::poll
   5: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
   6: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::harness::Harness<T,S>::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::scheduler::multi_thread::worker::Context::run
  11: tokio::runtime::context::runtime::enter_runtime
  12: tokio::runtime::scheduler::multi_thread::worker::run
  13: tokio::runtime::task::core::Core<T,S>::poll
  14: tokio::runtime::task::harness::Harness<T,S>::poll
  15: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


```

seems the `optimism` feature is not enabled in https://github.com/paradigmxyz/reth/blob/590356b3415cffec09f10189ff0ec006d9447d04/crates/consensus/auto-seal/src/lib.rs#L419-L426

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

reth Version: 1.0.0-rc.2-dev
Commit SHA: bf6696c52
Build Timestamp: 2024-06-19T03:39:59.989888000Z
Build Features: jemalloc,optimism
Build Profile: release

### What database version are you on?

2

### Which chain / network are you on?

--dev optimism

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

make build-op

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
ugh, I can't wait until we can get rid of all the op stuff...
