### ISSUE TITLE
sudden spike in pruning time

### ISSUE THREAD

**Issue by krakovia-evm** [paradigmxyz/reth#8957]
### Describe the bug

i noticed a sudden spike in pruning time, from ~15/30ms to 5minutes
Logs are spammed by messages
`failed sending request to peer's session`
and
`request to peer's session failed`
![image](https://github.com/paradigmxyz/reth/assets/90364822/a05ded95-2fee-4b96-816c-d434783d5607)

I've updated to latest 1.1.0-rc2 version, opening this as requested from tg group.
https://t.me/paradigm_reth/29466

Currently, pruning time is around 7seconds, while on beta2 it was around 15ms
No changes has been made to any .toml or docker-compose, only to switch reth version from beta2>1.0.0-rc2
[reth.log](https://github.com/user-attachments/files/15903441/reth.log)

### Steps to reproduce

normal execution since beta.2 release

### Platform(s)

Linux (x86)

### What version/commit are you on?

Reth v0.2.0-beta.2 28f3a2e

### What database version are you on?

2

### Which chain / network are you on?

eth

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
> Logs are spammed by messages
failed sending request to peer's session
and
request to peer's session failed

Just noting that these logs are unrelated to the problem, which is an extremely long commit time. Could you also provide the commit time / tx open time graphs?

**Comment by krakovia-evm** [comment]
![image](https://github.com/paradigmxyz/reth/assets/90364822/b6a405a9-5b97-4745-b58e-86abebed7e26)
Also new logs from the latest version
[reth.log](https://github.com/user-attachments/files/15905200/reth.log)

**Comment by krakovia-evm** [comment]
Closing the issue as the pruning time is back to nominal time by upgrading to reth 1.0.0
![image](https://github.com/paradigmxyz/reth/assets/90364822/ce54e8a2-a87f-429d-93dd-52e13527b9e6)
