### ISSUE TITLE
Compute genesis state root

### ISSUE THREAD

**Issue by leruaa** [paradigmxyz/reth#896]
We should  calculate the genesis state root to be more in line with Geth. 

_Originally posted by @onbjerg in https://github.com/paradigmxyz/reth/pull/747#discussion_r1069267788_

**Comment by gnapoli23** [comment]
Hi @leruaa , i would take this one. Can you give me some guidance? Thanks!

**Comment by leruaa** [comment]
@gnapoli23 I created this issue as requested in [this comment](https://github.com/paradigmxyz/reth/pull/747#discussion_r1069267788), but I don't have more insights on how to do it... Maybe @onbjerg can help here.

In any case, I think it's better to wait #747 to be merged before working on this.

**Comment by gnapoli23** [comment]
> @gnapoli23 I created this issue as requested in [this comment](https://github.com/paradigmxyz/reth/pull/747#discussion_r1069267788), but I don't have more insights on how to do it... Maybe @onbjerg can help here.
> 
> In any case, I think it's better to wait #747 to be merged before working on this.

Oh got it. I didn't notice the ref to #747, btw I'll take a look to it so I can have an idea of the context. Thanks 👍🏻

**Comment by Rjected** [comment]
@gnapoli23 this might be helpful:
#904 was recently merged which contains a helper for calculating the state root given a `HashMap<Address, GenesisAccount>`, which is contained in the `Genesis` struct as `alloc`:
https://github.com/paradigmxyz/reth/blob/dba3b30a42c4b95275028c4f51c3466265bfe02d/crates/primitives/src/genesis.rs#L34-L39

Ideally the state root would be calculated when loading a `genesis.json` based on the information in `alloc`, instead of requiring the `state_root` field already be populated. hopefully this provides some more context - lmk if you have any questions!

**Comment by gnapoli23** [comment]
@Rjected Thanks for the hint, I'll take a look at sources asap and if needed I'll ping you!

**Comment by onbjerg** [comment]
Thanks! I've assigned you to the issue. If you feel stuck, open up a draft PR with your questions and someone will help you. If you are prevented from solving the issue, let me know and I will unassign you :smile:

**Comment by gnapoli23** [comment]
Thanks @onbjerg 
Ok, starting from this
> 
> Ideally the state root would be calculated when loading a `genesis.json` based on the information in `alloc`, instead of requiring the `state_root` field already be populated. hopefully this provides some more context - lmk if you have any questions!

if I'm not wrong, I guess the idea is to use to `node` command an optional parameter such as `--genesis genesis.json` (or maybe add an `init` command such in `geth`) that specifies the `genesis.json` file to use while init-ing and then running the node itself.
If this is right, I saw that in the `node` Command implementation, this line

`let genesis = init_genesis(db.clone(), self.chain.genesis().clone())?;`

writes the genesis state root, if it has not been written yet, passing the `Genesis` struct coming from `ChainSpec`, which `impl From<EthersGenesis>`. In this impl, `alloc` is calculated and then the genesis state root computed basing on it.
So, if a `genesis.json` is specified in input, `alloc` should be computed based on the content of `genesis.json`, loading the pre-funded addresses, writing then the genesis state and then spawning the node according this custom init conf.

Is this correct? If so, where the "custom" alloc should be computed and then passed to the `ChainSpec`?
If I'm on the wrong track, please lmk!
Thanks for your support.

**Comment by Rjected** [comment]
The `From<EthersGenesis>` implementation looks fine currently, and it should already compute the correct state root. The end goal for this PR is to remove the `state_root` field from the `Genesis` struct:
https://github.com/paradigmxyz/reth/blob/b354a17f6570cf534cb8d15fc4c9986bc24581ab/crates/primitives/src/genesis.rs#L37

To do this, we need to calculate the state root instead in the `From<Genesis> for Header` implementation, based on the `alloc` field, using the [`genesis_state_root`](https://github.com/paradigmxyz/reth/blob/b354a17f6570cf534cb8d15fc4c9986bc24581ab/crates/primitives/src/proofs.rs#L77) function:
https://github.com/paradigmxyz/reth/blob/b354a17f6570cf534cb8d15fc4c9986bc24581ab/crates/primitives/src/genesis.rs#L42-L56

Then, `init_genesis` should pick up the state root. What would be nice is to add tests that make sure `init_genesis` computes the correct genesis hash using our existing `res/genesis/mainnet.json`, `res/genesis/goerli.json`, `res/genesis/sepolia.json` files. We would probably need to remove the `stateRoot` field from these files as well.

**Comment by gnapoli23** [comment]
@Rjected Got it! Where should i put the tests?

**Comment by Rjected** [comment]
@gnapoli23 np! they should probably be in `crates/staged-sync/src/utils/init.rs`, since that's where `init_genesis` is
