### ISSUE TITLE
Integrate Node traits into LaunchContextWith 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8967]
### Describe the feature

It would be nice to have access to the `FullNodeComponents` and `FullNodeTypes` traits, so we can also move this into the context:

https://github.com/paradigmxyz/reth/blob/5293a2f58da507abf432d69ff24d165ec49ee224/crates/node/builder/src/launch/mod.rs#L132-L140

this could be done with a new state type, similar to 

https://github.com/paradigmxyz/reth/blob/5293a2f58da507abf432d69ff24d165ec49ee224/crates/node/builder/src/launch/common.rs#L685-L685

but with access to the `FullNodeTypes` trait, either by providing this here

https://github.com/paradigmxyz/reth/blob/5293a2f58da507abf432d69ff24d165ec49ee224/crates/node/builder/src/launch/mod.rs#L130-L130

via `with_blockchain_db::<T>` and then keep the type T in a phantomType for example.

so we can just call `let builder_ctx = ctx.builder_ctx()?`

and later by attaching the adapter via `fn with_components<N: FullNodeComponents>` to the launchcontext with an additional attachment type like `WithMeteredProvider`

https://github.com/paradigmxyz/reth/blob/5293a2f58da507abf432d69ff24d165ec49ee224/crates/node/builder/src/launch/mod.rs#L168-L172

This way, we can push a ton of setup code currently in `fn launch` into the context.

FYI @fgimenez in case you find some time

**Comment by fgimenez** [comment]
> FYI @fgimenez in case you find some time

absolutely, thx!
