### ISSUE TITLE
Move `RethModuleRegistry` functionality into `RpcRegistry`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#8985]
### Describe the feature

Move `RethModuleRegistry` functionality into `RpcRegistry`, which is rn a wrapper around `RethModuleRegistry`.

https://github.com/paradigmxyz/reth/blob/e90b526a6668fae51179541221666894b3ade14b/crates/node/builder/src/rpc.rs#L148-L159

**Comment by tcoratger** [comment]
@emhane Here a few questions:
- Do you plan to keep the `RethModuleRegistry` structure inside the rpc builder and just migrate all the features or do you also plan to completely remove `RethModuleRegistry`?
- If we want to delete `RethModuleRegistry` then we must also migrate the `RpcModuleBuilder` to the node builder and as on the node builder we have an implementation constraint which is `Node: FullNodeComponents`, then we will no longer be able to keep `RpcModuleBuilder `as generic as it is now. I am thinking in particular of the `default()` function which could no longer work as it currently does.

**Comment by emhane** [comment]
> @emhane Here a few questions:
> 
> * Do you plan to keep the `RethModuleRegistry` structure inside the rpc builder and just migrate all the features or do you also plan to completely remove `RethModuleRegistry`?
> * If we want to delete `RethModuleRegistry` then we must also migrate the `RpcModuleBuilder` to the node builder and as on the node builder we have an implementation constraint which is `Node: FullNodeComponents`, then we will no longer be able to keep `RpcModuleBuilder `as generic as it is now. I am thinking in particular of the `default()` function which could no longer work as it currently does.

goal is to follow payload or pool builder pattern, but this issue is blocked rn, would be nice if you can pick up any other 🙏
