### ISSUE TITLE
Implement blockdownloader for p2p

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9011]
The BlockDownloader is responsible for handling download requests

https://github.com/paradigmxyz/reth/blob/83cbcb99aebcb8bdcfce549ab2912e033b402f51/crates/engine/tree/src/download.rs#L8-L8

this new trait, effectively does the same as a subset of the existing type:

https://github.com/paradigmxyz/reth/blob/83cbcb99aebcb8bdcfce549ab2912e033b402f51/crates/consensus/beacon/src/engine/sync.rs#L35-L39 

minus the engine part:

https://github.com/paradigmxyz/reth/blob/83cbcb99aebcb8bdcfce549ab2912e033b402f51/crates/consensus/beacon/src/engine/sync.rs#L42-L43

so that the new type only needs:

https://github.com/paradigmxyz/reth/blob/83cbcb99aebcb8bdcfce549ab2912e033b402f51/crates/consensus/beacon/src/engine/sync.rs#L68-L68

## TODO
* add a standalone BlockDownloader struct with trait impl for the new engine design that only downloads blocks. most of the logic can be reused
* we can duplicate this for new in the new engine/tree crate, not worth refactoring the existing code in `EngineSyncController` because we expect to remove all of this eventually.

**Comment by unclezoro** [comment]
hi, @mattsse , is this part of https://github.com/paradigmxyz/reth/issues/8213, will it implement the `automatically manage the peers and decide to fetch/download block from the best peers.`?

**Comment by mattsse** [comment]
this will eventually be usuable for this feature yes.

currently this functionality is encapsulated in 

https://github.com/paradigmxyz/reth/blob/de6332b51e9d4bdf9d3e75a1523ff1cdfb862686/crates/consensus/beacon/src/engine/sync.rs#L35-L35

the network implementation already manages the peers and decides where to download from
