### ISSUE TITLE
Add metric for blob nonce gap errors

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9018]
### Describe the feature

nonce gaps for blob txs are disallowed:

https://github.com/paradigmxyz/reth/blob/b9b61b377acc40e9c0d54039d212ffb8e1792375/crates/transaction-pool/src/pool/txpool.rs#L1337-L1345

we should add a counter for this in a metric

https://github.com/paradigmxyz/reth/blob/b9b61b377acc40e9c0d54039d212ffb8e1792375/crates/transaction-pool/src/metrics.rs#L100-L100

## TODO
* add metric counter
* integrate into existing grafana dashboard 
https://github.com/paradigmxyz/reth/blob/b9b61b377acc40e9c0d54039d212ffb8e1792375/etc/grafana/dashboards/reth-mempool.json#L1-L1

**Comment by leruaa** [comment]
I can take this on.

**Comment by Rjected** [comment]
@leruaa assigned!
