### ISSUE TITLE
Extend NetworkInfo trait with NetworkStatus

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#902]
### Describe the feature

atm `NetworkInfo` only provides the local_addr

https://github.com/paradigmxyz/reth/blob/55d1db0c1d457770cfa2a3d98c177a17026b439f/crates/net/network-api/src/lib.rs#L16-L19

we also need a way to get the status of the network which should include

* genesis hash
* client name
* protocols
* ...

cc @Evalir 

## TODO
* add NetworkStatus struct
* add NetworkInfo::network_status
* impl for NetworkHandle

**Comment by Kuly14** [comment]
I can help.

**Comment by Evalir** [comment]
I was tagged in the issue so I'd love to take it, but, happy to respect the order of first come first serve for @Kuly14 :)

**Comment by Kuly14** [comment]
Oh, no problem, you can take it. I thought that mention was for tracking purposes.
