### ISSUE TITLE
Refactor code to use reverse walker

### ISSUE THREAD

**Issue by entropidelic** [paradigmxyz/reth#903]
### Describe the feature

Now that the reverse walker functionality has been merged, some code should be refactored to use it. For what I have seen, some of these places are:
* `unwind_table` function in `db.rs`
* `unwind` function in `bodies.rs`
* `check_no_entry_above_by_value` function in `test_db.rs`

**Comment by mpaulucci** [comment]
I'd be interested in taking this one!

**Comment by onbjerg** [comment]
Was this closed in #938?
