### ISSUE TITLE
replace Arc<KzgSettings> with alloy's EnvKzgSettings

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9048]
### Describe the feature

This can be replaced with alloy's EnvKzgSettings
https://github.com/paradigmxyz/reth/blob/42bbafff2c825a7c2a300e5c1156d08fed083162/crates/transaction-pool/src/validate/eth.rs#L437-L438

## TODO
* replace raw usage of `Arc<KzgSettings>` with alloy_eips::EnvKzgSettings

**Comment by DaniPopes** [comment]
cc https://github.com/paradigmxyz/reth/issues/8063

**Comment by rakita** [comment]
This removes a need for `EnvKzgSettings` https://github.com/ethereum/c-kzg-4844/pull/443 as default can be easily added.
