### ISSUE TITLE
Add AnyNode type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9049]
### Describe the feature

similar to #9028 but for the `Node` trait 

https://github.com/paradigmxyz/reth/blob/42bbafff2c825a7c2a300e5c1156d08fed083162/crates/node/builder/src/node.rs#L23-L23

this can be solved similarly but with an actual instance of `C: NodeComponentsBuilder`

struct AnyNode<N =, C = ()>(PhantomType<N>, C);

### Additional context

FYI @leruaa

**Comment by romanroibu** [comment]
hey @mattsse, happy to take this one
