### ISSUE TITLE
add parser functionality to `RethCli`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9083]
with #9082 we now have a rethcli type, we need to integrate args parsing by integrating clap's parser in it.

this can be done by adding functions like

```rust
fn parse_args() -> Self where Self: Parser + Sized

```

https://docs.rs/clap/latest/clap/trait.Parser.html

**Comment by leruaa** [comment]
Not sure if I fully understood what you want, but I can give a try :)

**Comment by mattsse** [comment]
for now we basically should just delegate to the clap::Parser's functions for parse from env args

we also need fn try_parse_from<I, T>(itr: I), then the parse fn simply calls this with the std::env::args_os()
