### ISSUE TITLE
Make node exit future independent of error receiver

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9102]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/270df3eeb807e148d317d0037b2bf1499530a1d1/crates/node-core/src/exit.rs#L12-L17

## TODO
* replace `oneshot::Receiver<Result<(), BeaconConsensusEngineError>>` with a boxed future that returns `eyre::Result<()>` or result with boxed error

**Comment by greged93** [comment]
Hey @mattsse can I try this one?
