### ISSUE TITLE
upstream OptimismGenesisInfo to op-alloy

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9114]
### Describe the feature

move this function
https://github.com/paradigmxyz/reth/blob/b36bd58dbe1f2639ec5bb6bd5bcbc7b5a3cfb6fe/crates/chainspec/src/spec.rs#L1193-L1194

to op-alloy:

https://github.com/alloy-rs/op-alloy/blob/50101118dbfef913b936afa3bd4f10851fd1eafa/crates/rpc-types/src/genesis.rs#L6

**Comment by Vid201** [comment]
I can take this

**Comment by mattsse** [comment]
cool, I think the basefee param is reth native, so configuration of this we can still keep in reth

**Comment by Vid201** [comment]
> cool, I think the basefee param is reth native, so configuration of this we can still keep in reth

You mean `OptimismBaseFeeInfo` ? Because it's already in op-alloy
