### ISSUE TITLE
Conver write_peers_to_file to a function of NetworkManager

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9115]
## TODO

move this function into NetworkManager: `write_peers_to_file(&self`

https://github.com/paradigmxyz/reth/blob/b36bd58dbe1f2639ec5bb6bd5bcbc7b5a3cfb6fe/crates/node-core/src/utils.rs#L43-L46

this should return a result, and then we emit the info! logs here:
https://github.com/paradigmxyz/reth/blob/b36bd58dbe1f2639ec5bb6bd5bcbc7b5a3cfb6fe/crates/node/builder/src/builder/mod.rs#L515-L515
after calling the function

**Comment by Quertyy** [comment]
Can I take this one?

**Comment by mattsse** [comment]
assigned
