### ISSUE TITLE
Helper for walking over table range

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#912]
Currently, in order to walk a range we use the `cursor` -> `walk` -> take_while` pattern. This is nice, but repetiitve and footgun-y. e.g. https://github.com/paradigmxyz/reth/blob/5d45325e43afaf1e7cd60142ae764494db105602/crates/stages/src/stages/execution.rs#L103-L107

```
tx.cursor_read::<tables::StorageChangeSet>()?
            .walk((from_transition_rev, H160::zero()).into())?
            .take_while(|res| {
                res.as_ref()
                    .map(|(TransitionIdAddress((k, _)), _)| *k < to_transition_rev)
                    .unwrap_or_default()
            })
```

It would be nice to instead have a helper which gives us a walker over the range like: `tx.walker_read::<T: Table>(start: impl Into<T::Key>, end: impl Into<T::Key>)` which abstracts that way.

**Comment by jinsankim** [comment]
IMHO, in our patterns we usually don't know `end: impl Into<T::Key>` so I think we need to get the second argument as an `FnMut(&Self::Item) -> bool`. I think it looks like: `tx.walk_while(start_block, |entry| entry.as_ref().map(|e| e.0 <= end_block).unwrap_or_default())`.  HDYT?

**Comment by jinsankim** [comment]
Related w/ #702

**Comment by jinsankim** [comment]
If https://github.com/paradigmxyz/reth/issues/912#issuecomment-1386370589 is acceptable, I'd like to take this one.

**Comment by gakonst** [comment]
You can go for it. Would like to see an example of "not knowing `end`" motivating your API above, i.e. in the above it does look like you can do `walk_range(start_block, end_block)`? 

I was thinking that the generic you apply on the argument can encapsulate the `entry.as_ref().map(|e| e.0 <= end_block)`` part above, but maybe that's wrong

**Comment by jinsankim** [comment]
@gakonst Now I'm WIP on this. At least currently, I think you're right! We might be able to use `walk_range(start_block, end_block)`.

**Comment by jinsankim** [comment]
An exceptional case:
https://github.com/paradigmxyz/reth/blob/ac9f26fcabbc367917775d7db946a2856d546cb0/crates/stages/src/stages/total_difficulty.rs#L59-L61
