### ISSUE TITLE
Integrate CLI runner in CLI trait

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9139]
in reth bin we do

https://github.com/paradigmxyz/reth/blob/d3091cbb58bfff07eca44af61f3ba8ec01e0323c/bin/reth/src/cli/mod.rs#L145-L145

we can integrate this in the CLI crate with a helper function

https://github.com/paradigmxyz/reth/blob/d3091cbb58bfff07eca44af61f3ba8ec01e0323c/crates/cli/cli/src/lib.rs#L21-L21

eg:
```rust
fn with_runner(self, FnOnce(self, CliRunner)

```

can be combined with the parse function, like `execute(FnOnce(Self, CliRunner))`

**Comment by leruaa** [comment]
I can take this on.
