### ISSUE TITLE
Add devcontainers configuration for those of us that prefer to work in isolation

### ISSUE THREAD

**Issue by garyhuntddn** [paradigmxyz/reth#9168]
### Describe the feature

Devcontainers allow for a nicely isolated docker based development environment.

Given the need for careful supply chain management I feel like I want to use devcontainers for any work on reth.

Please see the PR referenced for an initial setup.

I've had to use a Dockerfile rather than the default rust container from MS due to needing clang and rust 1.79.

The devcontainer configuration files live within the main project - but don't get in the way of those that aren't using it.

**Comment by garyhuntddn** [comment]
See PR #9169

**Comment by Rjected** [comment]
Closing per reasoning here: https://github.com/paradigmxyz/reth/pull/9169#issuecomment-2226266728
