### ISSUE TITLE
Revisit `prune_modes` argument for the `BatchExecutor`

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#9173]
### Describe the feature

This API is weird because `prune_modes` feels out of place in it https://github.com/paradigmxyz/reth/blob/3bf3b9e3eccda6572e158a49328651732f930278/crates/evm/src/execute.rs#L173-L175

**Comment by mattsse** [comment]
this is only needed for the execution stage and imo it would be more appropriate if this is applied on the batch output and not handled by the executor.

the tmp mem overhead for full node sync is negligible imo

**Comment by shekhirin** [comment]
What if we just have a separate method that sets the prune modes? Like this one https://github.com/paradigmxyz/reth/blob/5fb81afd20e1799193d0b26a60bfe391c9867010/crates/evm/src/execute.rs#L83-L86
