### ISSUE TITLE
Stream wrapper type for iterators

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#9179]
### Describe the feature

Number one from here https://github.com/paradigmxyz/reth/pull/9123#pullrequestreview-2148251027.

Currently iterates sequentially in sync:

https://github.com/paradigmxyz/reth/blob/d943e782947014a530384c827588cb4db35e86f4/crates/exex/exex/src/backfill.rs#L214-L230

This can be improved because we can execute multiple blocks concurrently

we want a way to receive executed blocks (`execute_block`) in order but async, and a way to process them in parallel.
This is similar to FuturesOrdered but the our stream type needs to spawn the execution jobs and await their responses with some limit for how many blocks can be executed in parallel

## TODO

* add a stream wrapper type for SingleBlockBackfillJob that spawns individual jobs for the range restricted to a value
* restrict the executor and provider types to `Clone` for this new type

### Additional context

kinda similar to
https://docs.rs/futures/latest/futures/stream/fn.iter.html 
and 
https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.buffered

but the range needs to by processed individually and spawned via `tokio::spawn_blocking`
_No response_

**Comment by loocapro** [comment]
May I take over?
