### ISSUE TITLE
Pass `ProviderFactory` to segments instead of `DatabaseProviderRW`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#9183]
### Describe the feature

It's best to take a write lock as late as possible. Therefore, pruner should pass a reference to `ProviderFactory` to segments, instead of take the write lock before calling `Segment::prune`.

This is the first step in making it possible to take only a read lock on db in history pruning.

**Comment by shekhirin** [comment]
I believe it can be closed as not planned @emhane ?
