### ISSUE TITLE
Send pings in `P2PStream.poll_ready`

### ISSUE THREAD

**Issue by akirillo** [paradigmxyz/reth#920]
### Describe the feature

Currently the logic for sending p2p pings is in the `P2PStream`'s `Stream` impl, which may be a violation of abstraction boundaries as we send pings when we poll to read from the stream. We should instead send pings in the `Sink` impl, when we are trying to write to the stream, i.e. in the `poll_ready` method.

**Comment by literallymarvellous** [comment]
I'd like to take this.
I looked through the code, so I guess this involves moving the code below to the poll_ready in ```Sink```

https://github.com/paradigmxyz/reth/blob/78ffd0a7c0ce573e669d0fb0960a7806f279221d/crates/net/eth-wire/src/p2pstream.rs#L283-L305

**Comment by mattsse** [comment]
exactly, just move the match into poll_ready
