### ISSUE TITLE
feat(primitives): move header validation methods from consensus to primitive

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#9207]
### Describe the feature

At the moment, in this file:

https://github.com/paradigmxyz/reth/blob/2a9fa4869e658ca89e050d0d985a7ccbfa360bfa/crates/consensus/common/src/validation.rs

we have a lot of header validation methods like this one:

https://github.com/paradigmxyz/reth/blob/2a9fa4869e658ca89e050d0d985a7ccbfa360bfa/crates/consensus/common/src/validation.rs#L14-L24

I have the impression that rather than keeping these methods here, it would make more sense to integrate them into the `SealedHeader` implementation with a specific error type `HeaderConsensusError` which would group together all possible errors when validating the sealed headers and which would then be passed transparently to the `ConsensusError`.

This would make it possible to make the implementation more structural and to use:

```rust
header.validate_gas();
```

for example.

**Comment by Villegas2003** [comment]
Hi @tcoratger , Are you still in need of support for this issue? I'd be happy to help.
