### ISSUE TITLE
'cargo build' worked, 'make maxperf' failed with following errors 

### ISSUE THREAD

**Issue by jzkunlun** [paradigmxyz/reth#9209]
### Describe the bug

warning: sha3-asm@0.1.1: /home/ubuntu/reth/target/maxperf/build/sha3-asm-87e9065a4551689f/out/keccak1600-armv8.s: Assembler messages:
warning: sha3-asm@0.1.1: /home/ubuntu/reth/target/maxperf/build/sha3-asm-87e9065a4551689f/out/keccak1600-armv8.s:209: Error: invalid operands (*ABS* and *UND* sections) for `*'
warning: sha3-asm@0.1.1: /home/ubuntu/reth/target/maxperf/build/sha3-asm-87e9065a4551689f/out/keccak1600-armv8.s:200: Error: undefined symbol __SIZEOF_POINTER__ used as an immediate value
warning: sha3-asm@0.1.1: /home/ubuntu/reth/target/maxperf/build/sha3-asm-87e9065a4551689f/out/keccak1600-armv8.s:653: Error: undefined symbol __SIZEOF_POINTER__ used as an immediate value
warning: sha3-asm@0.1.1: /home/ubuntu/reth/target/maxperf/build/sha3-asm-87e9065a4551689f/out/keccak1600-armv8.s:802: Error: undefined symbol __SIZEOF_POINTER__ used as an immediate value

error: failed to run custom build command for `sha3-asm v0.1.1`

error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-I" "cryptogams/arm" "-Wall" "-Wextra" "-o" "/home/ubuntu/reth/target/maxperf/build/sha3-asm-87e9065a4551689f/out/884346e9d286f792-keccak1600-armv8.o" "-c" "/home/ubuntu/reth/target/maxperf/build/sha3-asm-87e9065a4551689f/out/keccak1600-armv8.s" with args cc did not execute successfully (status code exit status: 1).

### Steps to reproduce

just run 'make maxperf'

but 'cargo build' worked.   

### Platform(s)

Linux (ARM)

### What version/commit are you on?

/target/debug/reth --version 
reth Version: 1.0.0
Commit SHA: 2a9fa4869e658ca89e050d0d985a7ccbfa360bfa
Build Timestamp: 2024-06-30T23:49:27.800973710Z
Build Features: jemalloc
Build Profile: debug

### What database version are you on?

not started yet

### Which chain / network are you on?

no yet

### What type of node are you running?

Full via --full flag

### What prune config do you use, if any?

not yet

### If you've built Reth from source, provide the full command you used

cargo build and make maxperf   

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this looks like an issue with asm keccak,

you can use `maxperf-no-asm` that builds without that feature

**Comment by shekhirin** [comment]
`asm-keccak` feature isn't supported on Linux ARM yet, see https://github.com/DaniPopes/keccak-asm/issues/4

**Comment by jzkunlun** [comment]
thanks,
