### ISSUE TITLE
Support static peers

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9213]
### Describe the feature

#9201 added a new peerkind: static peers

> // Static nodes are used as pre-configured connections which are always
> // maintained and re-connected on disconnects.

we should prefer connections to static peers by ranking them higher:

https://github.com/paradigmxyz/reth/blob/2a9fa4869e658ca89e050d0d985a7ccbfa360bfa/crates/net/network/src/peers.rs#L804-L814

and only penalize them temporarily like we do for trusted peers:

https://github.com/paradigmxyz/reth/blob/2a9fa4869e658ca89e050d0d985a7ccbfa360bfa/crates/net/network/src/peers.rs#L376-L379

https://github.com/paradigmxyz/reth/blob/2a9fa4869e658ca89e050d0d985a7ccbfa360bfa/crates/net/network/src/peers.rs#L447-L447

## TODO
* add same exemptions for static peers as for trusted wrt banning/reputation
* prefer connections to static peers

**Comment by jsvisa** [comment]
pick this issue

**Comment by mattsse** [comment]
just following up @jsvisa 
do you have bandwidth for this?
this feature is not urgent, just nice to have.

**Comment by jsvisa** [comment]
Sorry not have started yet, I'm going to implement it this week
