### ISSUE TITLE
Add trait for chainspec parsing

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9220]
we have

https://github.com/paradigmxyz/reth/blob/068bf57c06de0764b214e2f10c99e125825947c7/bin/reth/src/commands/p2p/mod.rs#L37-L40

which conflicts with eth and ethereum

https://github.com/paradigmxyz/reth/blob/068bf57c06de0764b214e2f10c99e125825947c7/crates/node/core/src/args/utils.rs#L23-L28

this should be abstracted via a helper trait that
a) defines the default supported traits as const
b) defines a valueparser for the chainspec type

something like:

```rust
trait ChainSpecParser: TypedValueParser< Value = ChainSpec> + Default  {
   const SUPPORTED_CHAINS : ...
} 
```

should be defined in crates/cli/cli crate

**Comment by loocapro** [comment]
Can I?
