### ISSUE TITLE
Add `maxInitCodeSize` txpool test

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#924]
### Describe the feature

An edge case in geth's txpool implementation was recently found, and fixed in [go-ethereum#26504](https://github.com/ethereum/go-ethereum/pull/26504). We should create a test for this case.

The intended behavior of the txpool is to reject transactions where the transaction is a contract creation and the `tx.data` exceeds `maxInitCodeSize`.

The `maxInitCodeSize` and `maxCodeSize`, a related constant, [are listed in geth here](https://github.com/ethereum/go-ethereum/blob/a35b654f25fdac518d5775b55aa064025040b01a/params/protocol_params.go#L127-L128):
```go
	MaxCodeSize     = 24576           // Maximum bytecode to permit for a contract
	MaxInitCodeSize = 2 * MaxCodeSize // Maximum initcode to permit in a creation transaction and create instructions
```

**Comment by jinsankim** [comment]
I'm interested in taking this one.

**Comment by mattsse** [comment]
great,

there's a function that performs these checks:

https://github.com/paradigmxyz/reth/blob/78ffd0a7c0ce573e669d0fb0960a7806f279221d/crates/transaction-pool/src/pool/txpool.rs#L777-L783

**Comment by onbjerg** [comment]
We need to make sure that the `max_init_size` is configurable for other networks

**Comment by mattsse** [comment]
good point, this should be part of the `TransactionValidator` impl trait, never the less we can use this as standalone function

**Comment by jinsankim** [comment]
Do I need to check if initcode size is exceeded? 
When I read the issue first, I thought this issue is just writing a test case.

**Comment by mattsse** [comment]
we'll likely move this check into the `TransactionValidator` trait, which is intended for protocol specific validation.

since `maxInitCodeSize` will always be checked, it should be a standalone function that is basically just `pub fn ensure_max_init_code_size(code: Bytes, max)-> Result`

so this should be pretty straight forward. It should go into the `validate.rs` file
