### ISSUE TITLE
Don't init datadir if it doesn't exist in db command

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9257]
### Describe the feature

this will always initialize the dir:
https://github.com/paradigmxyz/reth/blob/405b73045549611c3381020cef9302b4ee3f483c/crates/cli/commands/src/db/mod.rs#L56-L56

this shouldn't be the case if --datadir does not exist

## TODO
* ensure provided datadir exists in `db` command

### Additional context

running `db` against a non existing datadir will create it:

`reth db --datadir ../does-not-exist clear mdbx StoragesTrie`

**Comment by yutianwu** [comment]
can I take this?

**Comment by mattsse** [comment]
assigned, ty
