### ISSUE TITLE
move cli utils to cli-util crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9260]
## TODO move more utils to commonly used cli-utils crate (new crate)

this includes:

https://github.com/paradigmxyz/reth/blob/5827c25996ad41e7a1ee5941b6df8196874d5d8b/crates/node/core/src/args/mod.rs#L27-L28

various parse fns

https://github.com/paradigmxyz/reth/blob/5827c25996ad41e7a1ee5941b6df8196874d5d8b/crates/node/core/src/args/utils.rs#L121-L121

https://github.com/paradigmxyz/reth/blob/5827c25996ad41e7a1ee5941b6df8196874d5d8b/crates/node/core/src/args/utils.rs#L87-L87

https://github.com/paradigmxyz/reth/blob/5827c25996ad41e7a1ee5941b6df8196874d5d8b/crates/node/core/src/args/utils.rs#L31-L31

cc @loocapro

**Comment by loocapro** [comment]
I can do it!
