### ISSUE TITLE
add eth and optimism cli chainspec parser

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9266]
Add implementations of 

https://github.com/paradigmxyz/reth/blob/d41aac380bfebbbfd4208dff6f8bd0ceda00e9b1/crates/cli/cli/src/chainspec.rs#L10-L10

for ethereum and optimism

basically:

https://github.com/paradigmxyz/reth/blob/d41aac380bfebbbfd4208dff6f8bd0ceda00e9b1/crates/node/core/src/args/utils.rs#L45-L45

but specifically for op and eth

first impl should just reuse this function as is

FYI @loocapro

**Comment by loocapro** [comment]
Up for it!
