### ISSUE TITLE
use op-alloy genesis types for genesis parsing

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9267]
op-alloy-rpc-types https://crates.io/crates/op-alloy-rpc-types/0.1.1 crate now has these types:

https://github.com/paradigmxyz/reth/blob/d41aac380bfebbbfd4208dff6f8bd0ceda00e9b1/crates/chainspec/src/spec.rs#L1084-L1104

## TODO
* replace those with op-alloy-rpc-types and simplify genesis setup:

https://github.com/paradigmxyz/reth/blob/d41aac380bfebbbfd4208dff6f8bd0ceda00e9b1/crates/chainspec/src/spec.rs#L733-L733

unblocks more progress for #9266

FYI @loocapro

**Comment by qiweiii** [comment]
I can take this!

is it just replace? how does it simplify the setup?

**Comment by mattsse** [comment]
thanks @qiweiii 

there's already a pr for #9292 
if you're looking for something else, I opened a few new good first issues
