### ISSUE TITLE
Add trait to subscribe to changed finalized + safe heads

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9269]
### Describe the feature

add a new trait, similar to:

https://github.com/paradigmxyz/reth/blob/08fc298e5565b546eddc8fd968d0bf0790cf69a4/crates/storage/provider/src/traits/chain.rs#L23-L23

but for subscribing to

https://github.com/paradigmxyz/reth/blob/08fc298e5565b546eddc8fd968d0bf0790cf69a4/crates/storage/provider/src/providers/chain_info.rs#L141-L144

**Comment by greged93** [comment]
hey @mattsse, I'm down to work on this if possible

**Comment by mattsse** [comment]
sweet, assigned
