### ISSUE TITLE
Initial pruning should be done in the pipeline

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#9270]
### Describe the feature

In full node, we write senders during the Sender Recovery stage to only delete them in the pruner after the Execution stage and the whole pipeline is completed. It is kinda weird.

Two ideas on how to improve it:
- Introduce a Sender Recovery Cleanup stage that will do the deletion so that pruner isn't doing it during the live sync.
   - Maybe we can do ETL here, but a simple deletion functionality from MDBX should also be fine.
   - What's not ideal here is the wasted I/O that affects the disk health.
- ~~Do not write senders up until the prune mode and recover them for execution right in the execution stage. The change is relatively small because the execution stage already recovers senders in case they're missing.~~
   - ~~It may be not the best idea. The stage executes block by block. the point of staged sync is less overhead on context switching. And recovery is a heavy CPU job.~~
   - ~~I think we should still try it by just skipping the sender recovery stage fully and recovering senders in the execution. It's a one-line change, and we can unwind the node, say for 1M blocks and compare the mgas/s to some previous sync.~~ Tried in https://github.com/paradigmxyz/reth/pull/9372, it will take too long on regular hw.

### Additional context

This additional stage for full nodes, should prune all segments to completion.

_No response_

**Comment by gakonst** [comment]
Should senders go to static files?

**Comment by emhane** [comment]
this is from a recent full node sync. account history pruning takes double the time right after sync.

<img width="857" alt="Screenshot_2024-07-09_at_14 08 00" src="https://github.com/paradigmxyz/reth/assets/58548332/a8e0e414-8ef8-4794-8321-ad48a5114a57">
<img width="857" alt="Screenshot_2024-07-09_at_14 09 22" src="https://github.com/paradigmxyz/reth/assets/58548332/270cce3f-b9f5-470c-a81d-ecabb266ea55">
