### ISSUE TITLE
test: rm unit tests for `calc_next_block_base_fee`

### ISSUE THREAD

**Issue by tcoratger** [paradigmxyz/reth#9275]
### Describe the feature

In the codebase, we still have some places where we unit test the `calc_next_block_base_fee` method:

https://github.com/paradigmxyz/reth/blob/7401f46790f46c87cb1040f2292e38b88e14a07e/crates/chainspec/src/constants/mod.rs#L18-L48

https://github.com/paradigmxyz/reth/blob/7401f46790f46c87cb1040f2292e38b88e14a07e/crates/chainspec/src/constants/optimism.rs#L53-L83

But this method is already widely tested here:

https://github.com/alloy-rs/alloy/blob/ec9e13e6336717b988b6ec2908bb4ceec6e874a5/crates/eips/src/eip1559/helpers.rs#L73-L103

Maybe we could:
- Remove these tests which seem useless on reth
- Add one or two scenarios on alloy if there are any missing but I don't have the impression, the function already seems to be well covered on alloy.

**Comment by mattsse** [comment]
we can remove those, yes

**Comment by tcoratger** [comment]
> ~we can remove those, yes~
> 
> actually, I don't mind having them, especially the op ones.

Maybe we can migrate the op ones to alloy and remove all from reth?

**Comment by mattsse** [comment]
sg!
we can do both prs in parallel
