### ISSUE TITLE
replace network_handle instance with boxed api trait 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9279]
### Describe the feature

This currently requires an instance of networkhandle:

https://github.com/paradigmxyz/reth/blob/7401f46790f46c87cb1040f2292e38b88e14a07e/crates/node/events/src/node.rs#L39-L40

which is only used to get the current number of connected peers

https://github.com/paradigmxyz/reth/blob/7401f46790f46c87cb1040f2292e38b88e14a07e/crates/node/events/src/node.rs#L74-L74

which is called via the `PeersInfo` trait, we can simply use a box<dyn PeersInfo> here to get rid of the handle instance

## TODO

replace

https://github.com/paradigmxyz/reth/blob/7401f46790f46c87cb1040f2292e38b88e14a07e/crates/node/events/src/node.rs#L39-L40

with `Option<Box<dyn PeersInfo>>`

**Comment by nicosanc** [comment]
I'd like to take on this task
