### ISSUE TITLE
gas_throughput log value is too verbose

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9286]
### Describe the feature

> Block added to canonical chain number=1861004 hash=0x87d03a774b0ecb106bbb4fc7392907ec9fe8b9264a0a9daa7e2cce6166cb3c51 peers=11 txs=51 gas="4.198796 Mgas" gas_throughput="76.06841779877305 Mgas/second" full=14.0% base_fee=0.00gwei blobs=2 excess_blobs=0 elapsed=55.197625ms

> gas_throughput="76.06841779877305 Mgas/second"

this should be a lot shorter

https://github.com/paradigmxyz/reth/pull/9247

**Comment by sdfii** [comment]
Let me fix this too.
