### ISSUE TITLE
perf: improve resolve trusted peers

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9290]
### Describe the feature

we currently call this a few times:

https://github.com/paradigmxyz/reth/blob/f0c97cab74a9647c699cdbbcf240c8f25e06fae4/bin/reth/src/commands/p2p.rs#L81-L83

https://github.com/paradigmxyz/reth/blob/f0c97cab74a9647c699cdbbcf240c8f25e06fae4/bin/reth/src/commands/stage/run.rs#L120-L125

we can optimize this with a new function that leverages `futures::try_join_all` in a new function on networkargs

## TODO

* add `NetworkArgs::resolve_trusted_peers -> Result<Vec<NodeRecord>`

**Comment by kamuik16** [comment]
can I take this?

**Comment by mattsse** [comment]
assigned
