### ISSUE TITLE
Integrate Request evm env filling in ethapi

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9296]
creating the `TxEnv` based on the TxRequest is done via:

https://github.com/paradigmxyz/reth/blob/edbbc9636eca770102f6ff33779130deb7b38360/crates/rpc/rpc-eth-types/src/revm_utils.rs#L119-L123

which currently requires OP feature

https://github.com/paradigmxyz/reth/blob/edbbc9636eca770102f6ff33779130deb7b38360/crates/rpc/rpc-eth-types/src/revm_utils.rs#L174-L175

this should be abstracted into a trait, ref:

https://github.com/paradigmxyz/reth/blob/edbbc9636eca770102f6ff33779130deb7b38360/crates/rpc/rpc-eth-api/src/helpers/call.rs#L268-L268

Ideally something new `ConfigureEvmCallEnv` or similar

**Comment by mattsse** [comment]
assigned

**Comment by mattsse** [comment]
@nkysg 
for the initial pr I'm fine with keeping the feature and simply move the function as is into a trait that is implemented on EthApi

**Comment by nkysg** [comment]
@mattsse OK

**Comment by nkysg** [comment]
> @nkysg for the initial pr I'm fine with keeping the feature and simply move the function as is into a trait that is implemented on EthApi

I find that I can't understand that  how processes this method
```
pub fn create_txn_env(block_env: &BlockEnv, request: TransactionRequest) -> EthResult<TxEnv> {
``` 
Abstracted into a trait Call. I don't know how to process  &self on
```
fn create_txn_env(&self, block_env: &BlockEnv, request: TransactionRequest) -> EthResult<TxEnv> {
```

And I thought maybe I need to add a method 
```
   fn build_call_evm_env(
        &self,
        at : BlockId,
        request: TransactionRequest,
    ) -> impl Future<Output = EthResult<EnvWithHandlerCfg>> + Send;
``` 
into trait Call because I can use these code
```
 let (cfg, block_env, at) = self.evm_env_at(at).await?;
```

Could you give me some hints? Thanks. @mattsse

**Comment by nkysg** [comment]
> @nkysg for the initial pr I'm fine with keeping the feature and simply move the function as is into a trait that is implemented on EthApi

@mattsse
I find that I can't understand that  how processes this method
```
pub fn create_txn_env(block_env: &BlockEnv, request: TransactionRequest) -> EthResult<TxEnv> {
```

Abstracted into a trait Call. I don't know how to process  &self on
```
fn create_txn_env(&self, block_env: &BlockEnv, request: TransactionRequest) -> EthResult<TxEnv> {
```

And I thought maybe I need to add a method
```
   fn build_call_evm_env(
        &self,
        at : BlockId,
        request: TransactionRequest,
    ) -> impl Future<Output = EthResult<EnvWithHandlerCfg>> + Send;
```

into trait Call because I can use these code
```
 let (cfg, block_env, at) = self.evm_env_at(at).await?;
```

Could you give me some hints? Thanks.
