### ISSUE TITLE
Extend HeadersClient, BodiesClient with a priority argument

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#932]
### Describe the feature

During downloading we'll encounter bad responses causing a retry request. These should be executed before any other buffered requests, since this request may block further progress in the Downloader.
 

## TODO

* introduce `Priority` enum `High, Normal`
* add new getter function that takes `Priority`
* existing getter function should call this with `Normal`

https://github.com/paradigmxyz/reth/blob/54e9b12e657c1ca900e65ef20f150ebd54c18f42/crates/interfaces/src/p2p/headers/client.rs#L25

**Comment by literallymarvellous** [comment]
I'd like to take this. 

If this new method is added to the HeadersClient & BodiesClient trait.
```rust
async fn get_headers_with_priority(
    &self,
    request: HeadersRequest,
    priority: Priority,
) -> PeerRequestResult<BlockHeaders>;
```
How would the impl work?, would the priority argument be sent across the channel too in ```Download Request```

```rust
impl HeadersClient for FetchClient {
    /// Sends a `GetBlockHeaders` request to an available peer.
    async fn get_headers(&self, request: HeadersRequest) -> PeerRequestResult<BlockHeaders> {
        let (response, rx) = oneshot::channel();
        self.request_tx.send(DownloadRequest::GetBlockHeaders { request, response })?;
        rx.await?.map(WithPeerId::transform)
    }
}
```

**Comment by mattsse** [comment]
the DownloadRequest needs that argument as well, then in the `StateFetcher` we either push_back or push_front depending on priority:

https://github.com/paradigmxyz/reth/blob/013eb5151da0da217be544759d269307e74c0a68/crates/net/network/src/fetch/mod.rs#L162-L163

**Comment by literallymarvellous** [comment]
Alright, Got it.
