### ISSUE TITLE
Add required trait impls for OpEthApi

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9325]
with #9324 we now have a op type for op specific eth API

in order to reuse this type we need this type to be `FullEthApi`:

https://github.com/paradigmxyz/reth/blob/b2bbd002572469a83ae053d0b7b3bc7472673493/crates/rpc/rpc-eth-api/src/helpers/mod.rs#L49-L53

this types needs to implement the Eth traits and all prerequisites.
this can be done incrementally, trait by trait.
at first, all traits should simply delegate to the inner type that also satisfies the trait.

**Comment by emhane** [comment]
rn this code is in https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/eth/helpers/optimism.rs, and must stay there also (i.e. be duplicate) until the type `OpEthApi` can be plugged in (blocked by node builder)

**Comment by shiowp** [comment]
Working on this.
