### ISSUE TITLE
Move `HeadersDirection` to eth-wire-types crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9338]
### Describe the feature

this type belongs in the eth-wire-types crate

https://github.com/paradigmxyz/reth/blob/b3a5593455bd4addde64ef4051c62970294f7e1e/crates/primitives/src/header.rs#L10-L22

## TODO
* move header.rs file to eth-wire-types: https://github.com/paradigmxyz/reth/blob/b3a5593455bd4addde64ef4051c62970294f7e1e/crates/net/eth-wire-types/Cargo.toml#L2-L2

**Comment by qiweiii** [comment]
I'll take this
