### ISSUE TITLE
Create `Network` variant in `reth_interfaces::Error`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#936]
I would also instead convert the error to an `RpcResult` rather than use `expect` here

I notice that we have helpers such as `ToRpcResult`, but this is only implemented for `reth_interfaces::Error`, which does not currently contain a variant for `Network`. This would require a larger refactor than in the scope of this PR

_Originally posted by @Rjected in https://github.com/paradigmxyz/reth/pull/923#discussion_r1081695626_
            
Creating a `Network` variant in `reth_interfaces::Error` would allow us to convert network errors to RPC errors more easily, using helpers such as `ToRpcResult`:
https://github.com/paradigmxyz/reth/blob/2a77e080809ec01371a7db1ff7327e7ed4b95519/crates/net/rpc/src/result.rs#L5-L36

**Comment by literallymarvellous** [comment]
Hi, I'd like to take this.

Just making sure, I've a understanding of the issue using ```network_status()```

Currently ```network_status()``` returns a ```Result<T, Error>``` with ```type error = oneshot::error::RecvError```  which I changed to
```rust
type Error = reth_interfaces::Error;
..
async fn network_status(&self) -> reth_interfaces::Result<NetworkStatus> {
    let status = match self.get_status().await {
        Ok(status) => status,
        Err(_err) => return Err(reth_interfaces::network::Error::SenderDropped.into()),
    };

    Ok(NetworkStatus {
        client_name: "Reth".to_string(),
        eth_protocol_info: EthProtocolInfo {
            difficulty: status.total_difficulty,
            head: status.blockhash,
            network: status.chain.id(),
            genesis: status.genesis,
        },
    })
}
```



so ```node_info()``` would look like this instead

```rust
async fn node_info(&self) -> RpcResult<NodeInfo> {
  let enr = self.network.local_node_record();
  let status = match self.network.network_status().await.map_internal_err(|e| e.to_string()) {
       Ok(status) => status,
       Err(e) => e,
  };

 Ok(NodeInfo::new(enr, status))
}
```

Is this along the lines of what's needed?

**Comment by onbjerg** [comment]
We would need a `Network` variant in the `Error` struct here as well: https://github.com/paradigmxyz/reth/blob/main/crates/interfaces/src/error.rs
