### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by theone-pang** [paradigmxyz/reth#9386]
### Describe the bug

node connect error 

### Steps to reproduce

I configured two nodes on the same machine, n1 and n2,  n1(--port:30303  --bootnodes=enode://yyyy@127.0.0.1:30313)  n2(--port:30313  --bootnodes=enode://xxxx@127.0.0.1:30303), they can connect to each other in previous versions, because the log "Status connected_peers =1". but i start node by same config, id ocur error --discovery.port conflict ,so i add --discovery.port. n1(--port:30303 --discovery.port:30303 --bootnodes=enode://yyyy@127.0.0.1:30313)  n2(--port:30313  --discovery.port:30313 --bootnodes=enode://xxxx@127.0.0.1:30303), the error disappears, but can not connect to each other,why? what should I do?

### Node logs

```text
I configured two nodes on the same machine, n1 and n2,  n1(--port:30303  --bootnodes=enode://yyyy@127.0.0.1:30313)  n2(--port:30313  --bootnodes=enode://xxxx@127.0.0.1:30303), they can connect to each other in previous versions, because the log "Status connected_peers =1". but i start node by same config, id ocur error --discovery.port conflict ,so i add --discovery.port. n1(--port:30303 --discovery.port:30303 --bootnodes=enode://yyyy@127.0.0.1:30313)  n2(--port:30313  --discovery.port:30313 --bootnodes=enode://xxxx@127.0.0.1:30303), the error disappears, but can not connect to each other,why? what should I do?
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

realse 1.0.0

### What database version are you on?

realse 1.0.0

### Which chain / network are you on?

priavte

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by emhane** [comment]
`yyyy@127.0.0.1:30313` is the tcp port (for rlpx), to specify the udp (discovery port) use query string `?discport=30301`. sp `yyyy@127.0.0.1:30303?discport=30313`

**Comment by theone-pang** [comment]
N1

curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1,"method":"admin_nodeInfo","params":[]}' http://localhost:8545

{"jsonrpc":"2.0","result":{"id":"0x23fc99dc5a9411b1f74425cf82d38393f9f0dfa63360848886514eb64f8d61c9","name":"reth/v1.0.0-9542f3bcf/x86_64-unknown-linux-gnu","enode":"enode://23fc99dc5a9411b1f74425cf82d38393f9f0dfa63360848886514eb64f8d61c99a47b52df97afbad20bdbd781086a9e9e228a4d61177d85e28f8cdf5c6ae7738@18.163.16.86:30303?discport=30403",

RUST_LOG=info ./reth node \
    --datadir=/data/reth/datas \
    --chain=/data/reth/genesis.json \
    --http \
    --http.api=admin,net,eth,web3,txpool,rpc,reth,debug,trace,ots \
    --http.corsdomain=* \
    --http.addr=0.0.0.0 \
    --http.port=8545 \
    --ws \
    --ws.addr=0.0.0.0 \
    --ws.port=8546 \
    --ws.origins=* \
    --ws.api=net,eth \
    --port=30303 \
    --discovery.port=30403 \
    --authrpc.port=8551 \
    --authrpc.addr=0.0.0.0 \
    --authrpc.jwtsecret=/data/reth/secrets/jwt.hex \
    --log.file.directory=/data/reth/logs \
    --log.file.filter=info \
    --p2p-secret-key=/data/reth/secrets/p2pn1.hex \
    --ipcdisable \
    --bootnodes=enode://3dafa30585c0db38057f633fd5fc1661648cf9eb9442534bbeee25e998342ddbf3f8db23956ce65cc97e0099103d97576bb8ee030d33e099363de4ddf88a8b44@43.198.108.189:30303?discport=30403


N2 

curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1,"method":"admin_nodeInfo","params":[]}' http://localhost:8545

{"jsonrpc":"2.0","result":{"id":"0x3dafa30585c0db38057f633fd5fc1661648cf9eb9442534bbeee25e998342ddb","name":"reth/v1.0.0-9542f3bcf/x86_64-unknown-linux-gnu","enode":"enode://3dafa30585c0db38057f633fd5fc1661648cf9eb9442534bbeee25e998342ddbf3f8db23956ce65cc97e0099103d97576bb8ee030d33e099363de4ddf88a8b44@43.198.108.189:30303?discport=30403",

RUST_LOG=info ./reth node \
    --datadir=/data/reth/datas \
    --chain=/data/reth/genesis.json \
    --http \
    --http.api=admin,net,eth,web3,txpool,rpc,reth,debug,trace,ots \
    --http.corsdomain=* \
    --http.addr=0.0.0.0 \
    --http.port=8545 \
    --ws \
    --ws.addr=0.0.0.0 \
    --ws.port=8546 \
    --ws.origins=* \
    --ws.api=net,eth \
    --port=30303 \
    --discovery.port=30403 \
    --authrpc.port=8551 \
    --authrpc.addr=0.0.0.0 \
    --authrpc.jwtsecret=/data/reth/secrets/jwt.hex \
    --log.file.directory=/data/reth/logs \
    --log.file.filter=info \
    --p2p-secret-key=/data/reth/secrets/p2pn2.hex \
    --ipcdisable \
    --bootnodes=enode://23fc99dc5a9411b1f74425cf82d38393f9f0dfa63360848886514eb64f8d61c99a47b52df97afbad20bdbd781086a9e9e228a4d61177d85e28f8cdf5c6ae7738@18.163.16.86:30303?discport=30403

 
 Always ： Status connected_peers=0 freelist=2

**Comment by emhane** [comment]
are the nodes behind nat?

**Comment by theone-pang** [comment]
the nodes is in aws, i get enode info in every aws host by  the cmd

**Comment by mattsse** [comment]
could you check if your node's port is reachable

devp2p rlpx ping enode://23fc99dc5a9411b1f74425cf82d38393f9f0dfa63360848886514eb64f8d61c99a47b52df97afbad20bdbd781086a9e9e228a4d61177d85e28f8cdf5c6ae7738@18.163.16.86:30303

**Comment by theone-pang** [comment]
This may be a bug in version 1.0.0, this problem disappeared after I switched to version 1.0.3
