### ISSUE TITLE
Support configurable engine capabilities in engineAPI

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9392]
### Describe the feature

currently we return a constant set of endpoints:

https://github.com/paradigmxyz/reth/blob/05ad783763f263675cbef4796af96210c951fea1/crates/rpc/rpc-engine-api/src/engine_api.rs#L898-L900

we should make this configurable and store as part of 

https://github.com/paradigmxyz/reth/blob/05ad783763f263675cbef4796af96210c951fea1/crates/rpc/rpc-engine-api/src/engine_api.rs#L44-L44

similar to 

https://github.com/paradigmxyz/reth/blob/05ad783763f263675cbef4796af96210c951fea1/crates/rpc/rpc-engine-api/src/engine_api.rs#L57-L58

by default this can be the full list of caps

ref https://github.com/alloy-rs/alloy/pull/1025

**Comment by loocapro** [comment]
May I get this?
