### ISSUE TITLE
Move `HackReceiptFileCodec` into `reth-optimism-cli`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#9393]
### Describe the feature

Move `HackReceiptFileCodec` into `reth-optimism-cli`.
https://github.com/paradigmxyz/reth/blob/d599393771f9d7d137ea4abf271e1bd118184c73/crates/net/downloaders/src/file_codec_ovm_receipt.rs#L12-L47

Requires implementing a mock receipt file codec to replace `HackReceiptFileCodec` in `ReceiptFileClient` tests.
https://github.com/paradigmxyz/reth/blob/d599393771f9d7d137ea4abf271e1bd118184c73/crates/net/downloaders/src/receipt_file_client.rs#L221-L339

**Comment by nkysg** [comment]
can I take this?
