### ISSUE TITLE
Convert `HeadersClient` `BodiesClient` futures into associated types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#940]
### Describe the feature

instead of using async_trait we should use associated types here which let's us implement our future types that don't need to be boxed.

the main future will just be a onceshot::receiver.

this way we can also get rid of the unsafe Sync impl in the Downloader impls.

depends on #891 #905

**Comment by leruaa** [comment]
I would like to take this on when the dependent PR will be merged

**Comment by leruaa** [comment]
I saw both dependants PRs has been merged. Is this issue still relevant? If so I can start to work on it

**Comment by mattsse** [comment]
yes, still relevant.
now that new downloaders have landed we can take this on
