### ISSUE TITLE
enable rust.unnameable-types = "warn" lint

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9401]
## TODO

* add new lint: https://github.com/paradigmxyz/reth/blob/bb8ff671828b2ae9f2ab71edce6e1a1f01c2b649/Cargo.toml#L155-L155
* fix warnings either by making types pub(crate) or exporting them (these fixes can be submitted as separate prs to make them easier to review)

**Comment by kamuik16** [comment]
I can take this one.

**Comment by kamuik16** [comment]
@mattsse this is a larger issue and wouldn't be feasible to do it in a single issue. Should we do it crate wise and then after all the crates we can add the lint to the root Cargo.toml?

**Comment by mattsse** [comment]
> Should we do it crate wise

that sounds great!
