### ISSUE TITLE
add optimism CLI type

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9407]
it's not reasonable to make the top level cli struct reusable, hence we should roll a standalone `struct Cli` for optimism that mimics the current one:

https://github.com/paradigmxyz/reth/blob/7dab636b0488b916d602f890537252a6771d107d/bin/reth/src/cli/mod.rs#L33-L38

this way we can get rid of all op specific commands and can select what commands we actually want for OP.

## TODO
add op cli struct first
1. duplicate `Cli` in optimism-cli crate

In followups we can define the op binary in optimism-bin

FYI @loocapro

**Comment by loocapro** [comment]
May I get this?

**Comment by mattsse** [comment]
I think we should also move the Noargs type to reth-cli-commands first
