### ISSUE TITLE
move sigsegv handler to cli-util crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9409]
as prep for #9408 we need to make the sigsegv handler reusable

https://github.com/paradigmxyz/reth/blob/7dab636b0488b916d602f890537252a6771d107d/bin/reth/src/lib.rs#L184-L185

## TODO
* move this module to https://github.com/paradigmxyz/reth/blob/7dab636b0488b916d602f890537252a6771d107d/crates/cli/util/Cargo.toml#L2-L2

**Comment by TropicalDog17** [comment]
Hi can I work on this issue?

**Comment by mattsse** [comment]
ty, assigned
