### ISSUE TITLE
replace optimism error variant with `Other`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9414]
### Describe the feature

this currently has feature gated op variant:

https://github.com/paradigmxyz/reth/blob/ce20adcd0bde552eba97d6126e2eee8db42ad18f/crates/rpc/rpc-eth-types/src/error.rs#L372-L375

we want this instead

https://github.com/paradigmxyz/reth/blob/ce20adcd0bde552eba97d6126e2eee8db42ad18f/crates/rpc/rpc-eth-types/src/error.rs#L130-L140

## TODO
* replace error variant
* implement ToRpcError for OptimismInvalidTransactionError

**Comment by nkysg** [comment]
May I take this?

**Comment by mattsse** [comment]
assigned
