### ISSUE TITLE
op: keep encoded txs in payload attributes

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9422]
### Describe the feature

for optimism, the CL includes the transactions for the payload via the payloadattributes message:

https://github.com/alloy-rs/alloy/blob/902d847c023d9d96d63b753028731261e0871d34/crates/rpc-types-engine/src/optimism.rs#L14

we convert this into a payload_builder_attributes type:

https://github.com/paradigmxyz/reth/blob/d0f78bdb39adca780c33f15be062f3dbe541c5f0/crates/optimism/payload/src/payload.rs#L29-L40

https://github.com/paradigmxyz/reth/blob/d0f78bdb39adca780c33f15be062f3dbe541c5f0/crates/optimism/payload/src/payload.rs#L49-L76

and throw away the encoded transactions, however to execute OP transactions we need the encoded transactions:

https://github.com/paradigmxyz/reth/blob/d0f78bdb39adca780c33f15be062f3dbe541c5f0/crates/primitives/src/transaction/compat.rs#L12-L17

we can optimize this by keeping the original bytes in the payload builder attributes types

## TODO
1. add helper type that is `struct { TransactionSigned, Bytes }` that is created: https://github.com/paradigmxyz/reth/blob/d0f78bdb39adca780c33f15be062f3dbe541c5f0/crates/optimism/payload/src/payload.rs#L50-L59
2. make use the bytes during execution (should be done in a followup pr because this requires some changes wrt evm txenv handling)

**Comment by martinezjorge** [comment]
I'll take a stab at this

**Comment by martinezjorge** [comment]
Just to clarify, all you want added is a type helper like so:

```rust
/// Optimism Payload Builder Attributes Helper
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OptimismPayloadBuilderAttributesHelper {
    /// An decoded signed transaction
    pub decoded_transaction: TransactionSigned,
    /// An encoded signed transaction
    pub encoded_transaction: Bytes, 
}
```

Did you want a field added to `OptimismPayloadBuilderAttributes` like so:

``` rust
/// Optimism Payload Builder Attributes
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OptimismPayloadBuilderAttributes {
    /// Inner ethereum payload builder attributes
    pub payload_attributes: EthPayloadBuilderAttributes,
    /// `NoTxPool` option for the generated payload
    pub no_tx_pool: bool,
    /// Decoded Transactions for the generated payload
    pub transactions: Vec<TransactionSigned>,
    /// Encoded Transactions for the generated payload
    pub encoded_transactions: Vec<Bytes>,
    /// The gas limit for the generated payload
    pub gas_limit: Option<u64>,
}
```

Or did you want that for a later PR?
