### ISSUE TITLE
support 7702 handling in txpool

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9428]
blocked by #9214 

we need some additional logic for 7702 on the Pooltransaction trait: number of auth lists because this impacts gas accounting which we need for tx validation

## TODO
* add trait functions to trait PoolTransaction that returns the number of authorizations

similar to

https://github.com/paradigmxyz/reth/blob/56cb37123038dec0d9eb9e2da855d652c0b3cc2e/crates/transaction-pool/src/traits.rs#L829-L830

but `fn authorization_count -> usize`

**Comment by leruaa** [comment]
I can take this one once unblocked.

**Comment by mattsse** [comment]
we actually included this in #9214
