### ISSUE TITLE
Bincode deserialization of ExExNotification is broken

### ISSUE THREAD

**Issue by unitezen** [paradigmxyz/reth#9433]
### Describe the bug

The remote ExEx example (https://reth.rs/developers/exex/remote.html) uses bincode (version 1) to serialize/deserialize ExExNotifications across the wire. This used to work when reth v1.0.0 was tagged, but is now broken in the latest v1.0.1 tag. Using bincode to serialize works fine, but breaks when you attempt to deserialize it.

I've tracked it down to an issue deserializing transactions, specifically this commit in alloy-eips: https://github.com/alloy-rs/alloy/commit/194f266fae46c1214004d04d4606010c3807b534 which is included in alloy-eips v0.1.3 onwards. Deserializing TransactionSigned stops working in alloy-eips v0.1.3 and will result in a variety of bincode errors including InvalidTagEncoding and io::UnexpectedEof. Since ExExNotification contains Chain, which contains a BTreeMap<u64, SealedBlockWIthSenders> -> SealedBlock -> Vec of TransactionSigned, this causes deserializing to fail as well.

I've tried patching out the deserialize_with on the storage_key field in AccessListItem in this fork: https://github.com/unitezen/alloy/commit/3d0fb3faf4c79745fa2ce7256f7a1d473667e629 and including the patch in my workspace Cargo.toml:
```
[patch.crates-io]
alloy-eips = { git = "https://github.com/unitezen/alloy.git", branch = "fix-serde-bincode" }
```
and deserialize works again. 

I haven't tried to replicate it with the remote ExEx example but I'm doing something similar -- serializing ExExNotification, send them across process using IPC and deserializing them again using bincode so I'm quite sure that it applies to the example as well. Not sure what the steps to rectify this are though, but tracking this down took quite a bit of time so figure it would help.

### Steps to reproduce

1. Serialize ExExNotification / TransactionSigned using bincode v1 on the latest reth v1.0.1 tag which pulls alloy v0.1.4
2. Deserialize the struct, fails with an Err of InvalidTagEncoding/io::UnexpectedEof

### Platform(s)

Linux (x86)

### What version/commit are you on?

v1.0.1

### What database version are you on?

Not applicable

### Which chain / network are you on?

ETH Mainnet

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

cargo build --profile maxperf --features "jemalloc,asm-keccak"

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
hmm, this sounds like some variant enum issue:

https://github.com/bincode-org/bincode/blob/100685bc28fd3df957d622e7007d7293a3ca2b0b/src/de/mod.rs#L258-L262

so this doesn't not work for bincode:

https://github.com/alloy-rs/alloy/blob/5d8dce4b542a069d0aa2973e7705309422311de6/crates/serde/src/optional.rs#L6C8-L6C23

**Comment by mattsse** [comment]
should be fixed now
