### ISSUE TITLE
replace network generic with box dyn

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9441]
### Describe the feature

the network type is generic because it needs:

https://github.com/paradigmxyz/reth/blob/4e5162cb3f042386244b9268bacb8b6cbe3b5293/crates/net/network/src/swarm.rs#L59-L59

https://github.com/paradigmxyz/reth/blob/4e5162cb3f042386244b9268bacb8b6cbe3b5293/crates/net/network/src/state.rs#L57-L61

now that we have a noop impl available out of the box

https://github.com/paradigmxyz/reth/blob/4e5162cb3f042386244b9268bacb8b6cbe3b5293/crates/net/network/src/config.rs#L454-L460

we can remove this generic entirely, this is only used once per new session, and the value isn't even that useful, so we should simply replace this with `Box<dyn BlockNumReader>` which would make things a bit easier.

## TODO
* replace generic with box dyn

**Comment by loocapro** [comment]
May I?
