### ISSUE TITLE
Remove per block deletion limits in pruner

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#9445]
### Describe the feature

We don't need per-block deletion limits in our pruner, because freelist isn't an issue anymore.

Before, it was introduced to not prune too many blocks, so that data from new blocks occupies >= pages in the database that was pruned.

Now, we don't care about freelist growing, so we can set the deletion limits per run, and remove all logic related to block accounting.

**Comment by emhane** [comment]
why don't we care ab freelist anymore?

**Comment by shekhirin** [comment]
> why don't we care ab freelist anymore?

the size doesn't affect performance anymore, so we can grow it as much as we want, and new data will occupy the freed pages when needed
