### ISSUE TITLE
debug_traceBlockByNumer w/ prestate call tracer inconsistent w/ geth

### ISSUE THREAD

**Issue by kunal365roy** [paradigmxyz/reth#9455]
### Describe the bug

A debugTraceBlockByNumber request w/ preStateTracer using the default mode (amongst other debug family requests) show differing accounts touched with reth showing 23 fewer trie leaf accounts.
Geth output: https://gist.github.com/kunal365roy/0bdac47651dac5538caedd62c2d8f064
Reth output: https://gist.github.com/kunal365roy/3eac829223bc239178de11ec6310f3e2 

### Steps to reproduce

diff request against geth vs. reth nodes

curl --request POST \
     --url <geth endpoint \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '{"jsonrpc": "2.0", "method": "debug_traceBlockByNumber", "params": ["0xccde12", {"tracer": "callTracer", "tracerConfig": {}}], "id": 295501193155072101}'

### Node logs

```text
N/A
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth: 1.0.0
geth: ethereum/client-go:v1.14.3

### What database version are you on?

N/A

### Which chain / network are you on?

mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
> w/ preStateTracer

can you clarify please, because the curl command uses calltracer

**Comment by mattsse** [comment]
this is no longer the case with reth v1.0.1 due to this fix:
https://github.com/bluealloy/revm/commit/9955d9faa5ca4cefc30bde3eb37ba11af7ef474d

now I'm getting the same output for this block
