### ISSUE TITLE
Extract metrics module from node-core to its own crate

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9458]
### Describe the feature

metrics doesn't really belong in there

https://github.com/paradigmxyz/reth/blob/c31d69683dafd78ba751dc45398807bab6e829ea/crates/node/core/src/metrics/mod.rs#L1-L1

## TODO 
* extract this module to a new crate: `node/metrics` reth-node-metrics

### Additional context
blocked by #9459

_No response_

**Comment by shankars99** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/reth).

### My background and how it can be leveraged
I would love to work on this. I have some experience with rust and would like to try my hand at this.

**Comment by mattsse** [comment]
cool, assigned, lmk if you need pointers by opening a draft pr
you can start by
1. add new crate, I recommend simply copy-past core dir then delete other files
2. add new crate to workspace (root cargo.toml)
3. cleanup deps
4. update usage

**Comment by loocapro** [comment]
@shankars99 are you still working on this? May I take over?

**Comment by shankars99** [comment]
@loocapro sorry about that yeah you can take over, i got caught up with some work this week
