### ISSUE TITLE
enforce --no-default-features via cargo hack

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9479]
### Describe the feature

this will resurface again and again #9478

we should enforce this via cargo hack

https://github.com/paradigmxyz/reth/blob/da0efbe0d4d322c3a349ad7bb3ff11ffed274e1b/.github/workflows/lint.yml#L73-L73

## TODO
* add cargo hack step that does check --no-default-features

**Comment by leruaa** [comment]
I can take this on.

**Comment by diegoTech14** [comment]
**Hello @mattsse**,
---

I'm Diego Duarte from Costa Rica and I would like to help with this issue. I am a Web3 learner and I would like to learn about Rust.

Here is my [OD profile](https://app.onlydust.com/u/diegoTech14).

---
**Best regards**,
**Diego Duarte**

Thanks for your consideration!

**Comment by rohankumar17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/reth).

### My background and how it can be leveraged
I am a second-year Software Engineering student with experience in programming languages such as Python, C, and C++. I have completed internships where I applied my skills in these languages. Recently, I have begun learning Rust and have engaged in practical exercises to enhance my proficiency. I am now seeking real-world issues and projects to work on that will motivate me to further develop my Rust skills and put my knowledge into practice.

### How I plan on tackling this issue
To make sure the project builds successfully without relying on default features, I would tweak the CI workflow. I would begin updating the no-test-deps job to use the command cargo hack check --no-default-features. This command tells cargo hack to build the project while excluding any default features defined in the Cargo.toml. Additionally, I would update the lint-success job to include no-test-deps in its dependency list. This way, the overall CI will fail if the build without the default features doesn't pass. By making these changes, I can enforce stricter build requirements within the CI pipeline.
