### ISSUE TITLE
use alloy transaction types

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9484]
the core tx types are quivalent to alloy's:

https://github.com/paradigmxyz/reth/blob/67f617646ce4b68a5096239238aa9209636ff500/crates/primitives/src/transaction/eip1559.rs#L13-L13

the only difference is the codec impl

https://github.com/paradigmxyz/reth/blob/67f617646ce4b68a5096239238aa9209636ff500/crates/primitives/src/transaction/eip1559.rs#L11-L11

we can implement codec by doing the same as for

https://github.com/paradigmxyz/reth/blob/67f617646ce4b68a5096239238aa9209636ff500/crates/storage/codecs/src/alloy/withdrawal.rs#L6-L11

## TODO
- https://github.com/paradigmxyz/reth/pull/9593
- https://github.com/paradigmxyz/reth/pull/10262
- https://github.com/paradigmxyz/reth/pull/10623
- https://github.com/paradigmxyz/reth/pull/10624
- https://github.com/paradigmxyz/reth/pull/10617
- [ ] optimism deposit

This should be done in separate prs and involves
* move existing struct def to https://github.com/paradigmxyz/reth/blob/67f617646ce4b68a5096239238aa9209636ff500/crates/storage/codecs/src/alloy/transaction.rs#L1-L1 impl codec for alloy types via into/from
* phase out primitive transaction defs

there are likely missing/renamed functions in alloy, so we need to surface those and add to alloy if appropriate

**Comment by leruaa** [comment]
I can take this on.

**Comment by mattsse** [comment]
cool, this will likely be a bit painful, see #9485 for ref
we likely need to do some work on rlp for this

**Comment by leruaa** [comment]
@mattsse Looking into this, it seems I will have to convert from reth `Signature` to alloy one at many places. Do you think I should work on migrating reth `Signature` to alloy as a prerequisite to this issue, or converting is ok for now?

For instance in the code below, I would like to call `encoded_len_with_signature()` on alloy `TxLegacy` that takes an alloy signature as a parameter:

https://github.com/paradigmxyz/reth/blob/cbe9a7c5cae12e97e53d54f7738852c56e2530d4/crates/primitives/src/transaction/pooled.rs#L303-L306

**Comment by emhane** [comment]
is the end goal to replace `reth_primitives::PooledTransactionsElement` with `alloy_consensus::TypedTransaction` ? if so we'd be more efficient if we tackle this by making types that use `reth_primitives::PooledTransactionElement` generic over a type `T: alloy_consensus::Transaction`. do we have a complete list of types we want to replace with its alloy equivalent?

**Comment by emhane** [comment]
+ the codec trait, and impl the codec trait for alloy types where we define the codec trait

**Comment by hannahredler** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/reth).

### My background and how it can be leveraged
Hello! I am a software engineer with approx 8 years experience in Python, Java and Typescript. I have recently been learning rust and studying the core program with the Privacy and Scaling Explorations team to learn more about applied ZK.

Whilst new to rust, I have a lot of experience in writing maintainable, tested and clean code and know I can contribute positively to your code base!

### How I plan on tackling this issue
Since it seems like a fairly straightforward migration, I would check the examples that have been given and ensure that I replicate the methodology.

**Comment by klkvr** [comment]
@tcoratger thank you for working on all PRs from here! would you like to work on `TxDeposit` migration to close this?

**Comment by tcoratger** [comment]
> @tcoratger thank you for working on all PRs from here! would you like to work on `TxDeposit` migration to close this?

Mhh not sure we have all the required methods in alloy `TxDeposit` no? like stuffs to do `encoded_len_with_signature` or `payload_len_for_signature` as `SignableTransaction` is not implemented for `TxDeposit` at the moment or did I miss something? (I'm not familiar with the op-alloy codebase so maybe I'm missing something here)

**Comment by klkvr** [comment]
> > @tcoratger thank you for working on all PRs from here! would you like to work on `TxDeposit` migration to close this?
> 
> Mhh not sure we have all the required methods in alloy `TxDeposit` no? like stuffs to do `encoded_len_with_signature` or `payload_len_for_signature` as `SignableTransaction` is not implemented for `TxDeposit` at the moment or did I miss something? (I'm not familiar with the op-alloy codebase so maybe I'm missing something here)

deposit transactions can't be signed, so we won't need those

**Comment by tcoratger** [comment]
> > > @tcoratger thank you for working on all PRs from here! would you like to work on `TxDeposit` migration to close this?
> > 
> > 
> > Mhh not sure we have all the required methods in alloy `TxDeposit` no? like stuffs to do `encoded_len_with_signature` or `payload_len_for_signature` as `SignableTransaction` is not implemented for `TxDeposit` at the moment or did I miss something? (I'm not familiar with the op-alloy codebase so maybe I'm missing something here)
> 
> deposit transactions can't be signed, so we won't need those

And we need to merge this right? https://github.com/alloy-rs/op-alloy/pull/68

**Comment by klkvr** [comment]
> > > > @tcoratger thank you for working on all PRs from here! would you like to work on `TxDeposit` migration to close this?
> > > 
> > > 
> > > Mhh not sure we have all the required methods in alloy `TxDeposit` no? like stuffs to do `encoded_len_with_signature` or `payload_len_for_signature` as `SignableTransaction` is not implemented for `TxDeposit` at the moment or did I miss something? (I'm not familiar with the op-alloy codebase so maybe I'm missing something here)
> > 
> > 
> > deposit transactions can't be signed, so we won't need those
> 
> And we need to merge this right? [alloy-rs/op-alloy#68](https://github.com/alloy-rs/op-alloy/pull/68)

yep

**Comment by tcoratger** [comment]
@klkvr Also previously we had a method like:

```rust
pub(crate) fn payload_len_without_header(&self) -> usize {
    let payload_length = self.fields_len();
    // 'transaction type byte length' + 'header length' + 'payload length'
    1 + length_of_length(payload_length) + payload_length
}
```

which calculates basically `'transaction type byte length' + 'header length' + 'payload length'` but in op alloy we only have:

```rust
fn length(&self) -> usize {
    let payload_length = self.fields_len();
    Header { list: true, payload_length }.length() + payload_length
}
```

but we lack the 'transaction type byte length' so this is also a method to add in op alloy right?

**Comment by klkvr** [comment]
yeah, I think we can add `encoded_len(&self, with_header: bool)` and `encode(&self, &mut dyn BufMut, with_header: bool)`

**Comment by mattsse** [comment]
yes, will track

**Comment by tcoratger** [comment]
> yes, will track

@mattsse If you open an issue please tag me. If I've time, will have a look

**Comment by mattsse** [comment]
https://github.com/paradigmxyz/reth/issues/10687
