### ISSUE TITLE
rename main_codec to reth_codec

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9490]
### Describe the feature

`main_codec` is legacy naming. it was originally named that when we were exploring various codecs and we never updated this.

imo `main_` is very confusing and we should rename

suggesting
* `reth_codec`
* `reth_db_codec`
* ...?

## TODO
* rename https://github.com/paradigmxyz/reth/blob/67f617646ce4b68a5096239238aa9209636ff500/crates/storage/codecs/derive/src/lib.rs#L41-L41

**Comment by PelleKrab** [comment]
I can take.
