### ISSUE TITLE
Optimize eth_sendTransaction implementation

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9491]
### Describe the feature

eth_sendtransaction is effectively not supported because we don't provide any signers, but the implementation still does all necessary preparation steps (fill tx including estimate) and only then try to sign it with a nonexistent signer:

https://github.com/paradigmxyz/reth/blob/67f617646ce4b68a5096239238aa9209636ff500/crates/rpc/rpc-eth-api/src/helpers/transaction.rs#L449-L449

## TODO
this implementation should check first if there's a signer for the `from` address and exit early.

**Comment by Quertyy** [comment]
I would like to take this one

**Comment by mattsse** [comment]
assigned, ty!
