### ISSUE TITLE
TransitionId was not correctly set in execution

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#951]
It was incremented more time than needed, this line needs to go one for loop outside: https://github.com/paradigmxyz/reth/blob/f2ed6e2bbe56a4712b3452fae888de69d969e798/crates/stages/src/stages/execution.rs#L254

Additionally, test that should have checked this was faulty. This line needed to have block number: https://github.com/paradigmxyz/reth/blob/f2ed6e2bbe56a4712b3452fae888de69d969e798/crates/stages/src/stages/execution.rs#L485

**Comment by rakita** [comment]
@loren this would probably explain why the unwind didn't work

**Comment by mattsse** [comment]
Closed per #952
