### ISSUE TITLE
Implement ForkChoiceNotifications trait for BlockchainProvider and NoopProvider

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9521]
### Describe the feature

https://github.com/paradigmxyz/reth/blob/80b02fec0f2976e09e334d17be226a7024252d68/crates/storage/provider/src/traits/chain.rs#L150-L150

similar to

<img width="530" alt="image" src="https://github.com/user-attachments/assets/ad838d9a-ed7c-412e-9d1b-376d89841924">

but implemented for BlockchainProvider and NoopProvider

**Comment by greged93** [comment]
Hey @mattsse im down to work on this if possible

**Comment by royvardhan** [comment]
@mattsse Please assign this to me.

**Comment by royvardhan** [comment]
We can close this? @mattsse
