### ISSUE TITLE
revise nodetypes trait

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9555]
the nodetypes trait

https://github.com/paradigmxyz/reth/blob/6a0060197f9ecb414a0dc1e72dfeacc4b1917bc7/crates/node/api/src/node.rs#L24-L29

already makes certain assumptions, for example it expects engine types, but we might want to support node setups that don't use the engine API.

this should be relaxed in the node builder in such a way that these traits stack (using a single type instead of associated types) and are not associated types

**Comment by tcoratger** [comment]
@mattsse Maybe we could do something like:

```rust
/// The type that configures the essential types of an Ethereum-like node.
///
/// This includes the primitive types of a node.
///
/// This trait is intended to be stateless and only define the types of the node.
pub trait NodeTypes: Send + Sync + Unpin + 'static {
    /// The node's primitive types, defining basic operations and structures.
    type Primitives: NodePrimitives;
}

/// The type that configures an Ethereum-like node with an engine for consensus.
pub trait NodeTypesWithEngine: NodeTypes {
    /// The node's engine types, defining the interaction with the consensus engine.
    type Engine: EngineTypes;
}
```

This would allow for a two-stage implementation while retaining the `Engine` associated type which is used quite a few places in the code, what do you think?

**Comment by mattsse** [comment]
yes, I think this is exactly what we're looking for here
