### ISSUE TITLE
remove serde support from reth-codec

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9558]
### Describe the feature

the reth-codec macro is a bit bloated

https://github.com/paradigmxyz/reth/blob/d5964cae0e18a509e5ef1b08fa094d7278ebd4d1/crates/storage/codecs/derive/src/lib.rs#L48-L54

this does not belong in there.

## TODO
* remove serde auto gen from doce macro and add support natively

**Comment by EmmanuelAR** [comment]
Hello @mattsse 

My name is Emmanuel, a software developer from Costa Rica.  I would be happy to assist with this task. I will review the current implementation and could remove serde auto gen from doce macro and add support natively

Please let me know if this is acceptable.

Best regards,
Emmanuel 😁
