### ISSUE TITLE
remove transaction forwarder trait

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9562]
### Describe the feature

now that we have separate ethapi impls for op and eth, we no longer need this

https://github.com/paradigmxyz/reth/blob/fb6ea8b9249221cbbcc888f393bfc64f9a476d4e/crates/rpc/rpc-eth-api/src/helpers/transaction.rs#L651-L657

## TODO
* remove traits and field in EthAPI https://github.com/paradigmxyz/reth/blob/fb6ea8b9249221cbbcc888f393bfc64f9a476d4e/crates/rpc/rpc/src/eth/core.rs#L56-L56
* integrate Sequencerclient in OpEthApi instead https://github.com/paradigmxyz/reth/blob/fb6ea8b9249221cbbcc888f393bfc64f9a476d4e/crates/optimism/node/src/rpc.rs#L34-L38
https://github.com/paradigmxyz/reth/blob/fb6ea8b9249221cbbcc888f393bfc64f9a476d4e/crates/optimism/rpc/src/eth/mod.rs#L43-L43

**Comment by EmmanuelAR** [comment]
Hello @mattsse 

My name is Emmanuel, a software developer from Costa Rica.  I would be happy to assist with this task. I will review the current implementation and will guide by the comments that you post in the ticket

Please let me know if this is acceptable.

Best regards,
Emmanuel 😁
