### ISSUE TITLE
remove pending block support from OpEthApi

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9563]
### Describe the feature

in optimsim we cant build a local pending block for the "pending" block, in this case we should return the latest block for compat reasons, see also:

https://github.com/ethereum-optimism/op-geth/blob/f2e69450c6eec9c35d56af91389a1c47737206ca/miner/worker.go#L367-L375

## TODO
we should refine the loadpendingblock trait a bit, this trait function is not very nice

https://github.com/paradigmxyz/reth/blob/fb6ea8b9249221cbbcc888f393bfc64f9a476d4e/crates/optimism/rpc/src/eth/pending_block.rs#L30-L33

this exists only to provide a default impl, which we should rethink

for this issue, the only thing we need to do is:

override the

https://github.com/paradigmxyz/reth/blob/fb6ea8b9249221cbbcc888f393bfc64f9a476d4e/crates/rpc/rpc-eth-api/src/helpers/pending_block.rs#L115-L121

and return the latest block instead or override the function that maps the pending blockid, which calls 
https://github.com/paradigmxyz/reth/blob/fb6ea8b9249221cbbcc888f393bfc64f9a476d4e/crates/rpc/rpc-eth-api/src/helpers/block.rs#L222-L222

**Comment by EmmanuelAR** [comment]
Hello @mattsse 

My name is Emmanuel, a software developer from Costa Rica.  I would be happy to assist with this task. I will review the current implementation and will guide by the description that u post.

Please let me know if this is acceptable.

Best regards,
Emmanuel 😁

**Comment by adrianvrj** [comment]
Hi, my name is Adrian Vargas, I am currently trying to introduce myself to web3 and got a bit of experience in rust, I would like to tackle this issue!

**Comment by diegoTech14** [comment]
**Hello @mattsse**,
---

I'm Diego Duarte from Costa Rica, I would be happy to help with this issue. I am currently learning about web 3 and I would like to tackle this task

Here is my [OD profile](https://app.onlydust.com/u/diegoTech14).

---
**Best regards**,
**Diego Duarte**

Thanks for your consideration!

**Comment by adrianvrj** [comment]
Hi, due to some complications I will not be able to finish this
