### ISSUE TITLE
Deprecate Downloader trait

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#957]
### Describe the feature

this trait isn't actually used because we don't need a unified abstraction over Downloaders.

**Comment by rkrasiuk** [comment]
@mattsse i would argue that both dls now have common logic around max concurrency that can be moved to `Downloader` trait

**Comment by mattsse** [comment]
where would we need this?

**Comment by rkrasiuk** [comment]
not to expose externally, but to reuse in impls

**Comment by mattsse** [comment]
can't think of anything where we'd need to abstract over both downloader types, since both are tied to their specific stage.

don't need to over-abstract here imo
