### ISSUE TITLE
Convert Ethservice into stream

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9582]
Currently we're ignoring internal events:

https://github.com/paradigmxyz/reth/blob/ba7aede59f6c4f1acc5c2f43bb3d694bb90d1c04/crates/ethereum/engine/src/service.rs#L73-L85

however some events can be useful for node event handling

blocked by https://github.com/paradigmxyz/reth/pull/9575

## TODO
* convert this into a stream that bubbles up the event

**Comment by mvares** [comment]
Hey @mattsse! #9575 has already been merged. Is this issue still blocked?

**Comment by mattsse** [comment]
hey @mvares this is unblocked now but we need this pr pretty soon, if you have the bandwidth for it please go ahead

**Comment by mvares** [comment]
@mattsse, should I drop the  `impl Future`?

**Comment by mattsse** [comment]
yes

**Comment by mvares** [comment]
@mattsse, sorry about that. Right now, I haven't sufficient skills to this task. I'll try to get other task more easy.

**Comment by mattsse** [comment]
all good!
if you dont find anything, please ping me on tg @mattsse

**Comment by junderw** [comment]
Please let me know what "bubbles up" means in this context. Thanks.
