### ISSUE TITLE
handling additional trace_filter fields

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9608]
### Describe the feature

we're currently ignoring fields after and count:

https://github.com/paradigmxyz/reth/blob/42182f531e94108be3aa9f4a838df6a2edd93185/crates/rpc/rpc/src/trace.rs#L254-L254

ref https://github.com/foundry-rs/foundry/pull/8458

FYI @EdwardJES 

## TODO
* handle count and offset

**Comment by EdwardJES** [comment]
Thanks @mattsse, happy to take this one 🙏
