### ISSUE TITLE
Add more docs for tree engine

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9615]
Need a lot of docs that cover:

* the role of each component
* relationship
* where state is stored, and what happens when
  * committed to disk
  * new block is added

**Comment by mvares** [comment]
- Create a flow (perhaps using Mermaid or DrawIO) explaining some abstractions over database queries
- Explain the hierarchy between calls (e.g., BlockchainProvider2)

**Comment by tcoratger** [comment]
Is there anything to do here or is it closed by https://github.com/paradigmxyz/reth/pull/9686 and https://github.com/paradigmxyz/reth/pull/9748?
