### ISSUE TITLE
TxHash received by Exex is zero for a lot of transactions

### ISSUE THREAD

**Issue by quentinv72** [paradigmxyz/reth#9618]
### Describe the bug

I am currently syncing a Reth node with an Exex that indexes some data into a relational db. One of the fields that I am indexing is the transaction hash. I've noticed that the hash on the transactions contained in the `Chain` sent by the node seems to be set to `0x0000000000000000000000000000000000000000000000000000000000000000` for quite a few transactions... I end up having to recalculate the hash for each transaction in the chain to avoid pkey issues when I write to my table. This is what I do:
```rust
let tx_hash = if tx.hash.is_zero() {
                        warn!("Transaction hash is zero... recalculating it");
                        tx.recalculate_hash().to_string()
                    } else {
                        tx.hash.to_string()
                    };
```
<img width="1908" alt="Screenshot 2024-07-18 at 10 25 51 AM" src="https://github.com/user-attachments/assets/34ed436a-64d2-40c8-b54b-18ae63c6407d">
You can tell from the log count that the amount of zero tx_hash is non negligible.

### Steps to reproduce

I think you should be able to recreate the issue by running a node with an Exex that logs the transaction hashes for each transaction in the chain received from the node.

### Platform(s)

Linux (x86)

### What version/commit are you on?

v1.0.1

### What database version are you on?

Command does not seem to let me pass custom datadir.

### Which chain / network are you on?

mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by shekhirin** [comment]
Does that happen during the pipeline sync (e.g. when Reth does an initial sync) or during the live sync when Reth receives updates from the CL?

It's expected to not get transaction hashes during the pipeline sync, because we recover hashes later on in `TransactionLookup` stage. `Chain` struct isn't generic over transaction, so we re-use the `TransactionSigned` there, when in reality it's `TransactionSignedNoHash`.

During the live sync, we should send transactions with recovered hashes.

Unsure what to do here yet, but we somehow need to distinguish between them.

**Comment by mattsse** [comment]
> Does that happen during the pipeline sync

that's likely and a footgun imo
we should think about converting this to an enum instead or ensure valid hashes during pipeline sync if we have exex

**Comment by quentinv72** [comment]
Yes, it's happening during the pipeline sync. Does this mean that the Exex would receive the same transactions twice? Once without the hashes during the pipeline sync and then again with the hashes duing the Transaction lookup?

**Comment by shekhirin** [comment]
> Does this mean that the Exex would receive the same transactions twice

No, only once without the hashes during the pipeline sync

> Is there a recommended way of handling this for my use case?

Before we fix it, the way you do it seems fine.
