### ISSUE TITLE
Add support for eth_getAccount

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9625]
### Describe the feature

ref https://www.quicknode.com/docs/ethereum/eth_getAccount

## TODO
* add endpoint to trait, like https://github.com/paradigmxyz/reth/blob/390f30aadebcdd509e72cc04327c3b854de076a6/crates/rpc/rpc-eth-api/src/core.rs#L55-L58
* implement it like https://github.com/paradigmxyz/reth/blob/390f30aadebcdd509e72cc04327c3b854de076a6/crates/rpc/rpc-eth-api/src/core.rs#L372-L376

the latter likely needs more work, so this can be two prs where the first just introduces the trait function and when figure out how to get the account's storage root cc @rkrasiuk

**Comment by mvares** [comment]
:shipit:

**Comment by mvares** [comment]
@mattsse, already exists a type for this?
![image](https://github.com/user-attachments/assets/402cee80-e78b-491c-a515-dae2bd706f8a)

**Comment by mvares** [comment]
```mermaid
   graph TD
    A[Get Account]
    B[codeHash]
    C[storageRoot]
    D[balance]
    E[nonce]

    A --> B
    A --> C
    A --> D
    A --> E
```
As was done [here](https://github.com/ethereum/go-ethereum/blob/df3f0a81a7ef6fd56c90675c32b6d732380a9fd2/internal/ethapi/api.go#L724-L725), this can be a starting point to address this the second question of this issue.

**Comment by mattsse** [comment]
@rkrasiuk I assume getting the storageroot at any block number isn't that easy, same issue as eth_getProof?

**Comment by rkrasiuk** [comment]
@mattsse actually, it's much easier since you only need to load storage changes for a given account

**Comment by mattsse** [comment]
could you please add some pointers on where to start, I see we have an AccountReader trait

**Comment by rkrasiuk** [comment]
we would need to expose the interface in `HashedStorage` similar to `HashedPostState::from_revert_range` that only loads storage changes for a single account. then we would be able to initialize storage root with in-memory hashed state
e.g.
```rust
let address = ();
let hashed_address = keccack256(address);
let hashed_storage = HashedStorage::from_revert_range(address, &tx, block_range)?;
let hahed_storage_sorted = hashed_storage.into_sorted();
let root = StorageRoot::new_hashed(
    &tx,
    HashedPostStateStorageCursor::new(
        DatabaseHashedStorageCursor::new(
            tx.cursor_dup_read::<tables::HashedStorages>()?,
            hashed_address,
        ),
        Some(&hashed_storage_sorted)
    ),
    hashed_address,
).root()?
```

**Comment by mvares** [comment]
@rkrasiuk, in the part of `balance`, could we use the `getBalance`? (Already it's created)

**Comment by mvares** [comment]
- Waiting by #9643

**Comment by rkrasiuk** [comment]
@mvares you can just retrieve account information from `HistoricalStateProvider` through `state_at_block_*` fns

**Comment by mvares** [comment]
> @mvares you can just retrieve account information from `HistoricalStateProvider` through `state_at_block_*` fns

Wouldn't it be better to use the `balance` method from `EthApiServer`?

**Comment by greged93** [comment]
hey @mvares are you still working on this? otherwise I'm down to give it a go

**Comment by mvares** [comment]
@greged93 go for it

**Comment by Rjected** [comment]
This should be fixed by https://github.com/paradigmxyz/reth/pull/10369
