### ISSUE TITLE
Add provider function to return a list of all stages and their progress

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9649]
### Describe the feature

with https://github.com/alloy-rs/alloy/pull/1079 we can now emit an list of stages and their processed blocks

which can be obtained from the 

https://github.com/paradigmxyz/reth/blob/9e685163deb57b2a2e1661195c093071d1e85647/crates/storage/storage-api/src/stage_checkpoint.rs#L5-L9

we need a new function here that returns a list of all checkpoints in that table:

we need to iterate over this table and decode its keys to string and the checkpoint

https://github.com/paradigmxyz/reth/blob/9e685163deb57b2a2e1661195c093071d1e85647/crates/storage/provider/src/providers/database/provider.rs#L2507-L2509

## TODO
* add get_all_checkpoints function to trait

this can be done via

https://github.com/paradigmxyz/reth/blob/9e685163deb57b2a2e1661195c093071d1e85647/crates/storage/db-api/src/transaction.rs#L22-L22

and then walk 

https://github.com/paradigmxyz/reth/blob/9e685163deb57b2a2e1661195c093071d1e85647/crates/storage/db-api/src/cursor.rs#L40-L40

FYI @loocapro

**Comment by loocapro** [comment]
Happy to get it!
