### ISSUE TITLE
Enable GZIP compression for JSON-RPC calls

### ISSUE THREAD

**Issue by mvares** [paradigmxyz/reth#9652]
### Describe the feature

Introducing gzip compression for `JSON-RPC` calls can significantly `reduce` the payload size of the requests and responses, leading to faster communication and lower bandwidth usage. This enhancement can be particularly beneficial for applications making frequent or large JSON-RPC calls to the Ethereum network.

```[tasklist]
### Tasks
```

**Comment by shekhirin** [comment]
I believe Geth already does it by default https://github.com/ethereum/go-ethereum/blob/380688c636a654becc8f114438c2a5d93d2db032/node/rpcstack.go#L396-L404, sounds like a good idea.

**Comment by mvares** [comment]
That sounds like a plan :shipit:
