### ISSUE TITLE
PipelineEvent channel should be unbounded

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#968]
### Describe the feature

atm the `Pipeline` supports emitting events optionally.

I think PiplineEvents are critical. So the channel should be converted into an Unbounded channel

Since pipelineEvents are also very cheap and we perhaps need to listen to them on multiple fronts, perhaps we should refactor this to a `Vec<UnboundedSender>` instead 

wdyt @onbjerg ?

**Comment by onbjerg** [comment]
Makes sense to have multiple listeners, especially since we can probably use the pipeline events to update sync state: https://github.com/paradigmxyz/reth/blob/main/crates/interfaces/src/sync.rs#L26

**Comment by mattsse** [comment]
blocked by #963
