### ISSUE TITLE
handle tree errors gracefully

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9688]
we currently have some unwraps:

https://github.com/paradigmxyz/reth/blob/9b3a011cf2dfddd7c9dd0a8de24fb166d7e32fd1/crates/engine/tree/src/tree/mod.rs#L859-L863

## TODO
* handle them gracefully

**Comment by TropicalDog17** [comment]
Hi, can I work on this issue @mattsse

**Comment by mattsse** [comment]
hey @TropicalDog17 

ty, but this is a bit nuanced and moving quickly, and I'm currently on this already.

feel free to pick another good first issue, if you don't find anything, feel free to also ping me on tg
