### ISSUE TITLE
Integrate payloadbuilder handler

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9705]
if the FCU is valid and we have payloadattributes we need to forward them to the payload builder

https://github.com/paradigmxyz/reth/blob/059233327e9ce49490ebf71b6508c7ffc44ff2ec/crates/consensus/beacon/src/engine/mod.rs#L1158-L1163

this functionality is currently missing

**Comment by mvares** [comment]
@mattsse could you give more info about this issue?

**Comment by mattsse** [comment]
hey @mvares this is a bit more delicate because this is moving quickly.

please let me know if you can't find any interesting good first issue, we can figure something out
