### ISSUE TITLE
Got null when getTrasactionReceipt 

### ISSUE THREAD

**Issue by ForLina** [paradigmxyz/reth#9726]
### Describe the bug

same question as 
https://ethereum.stackexchange.com/questions/102945/gettransaction-returns-null-for-old-transactions

### Steps to reproduce

same as the link 

### Platform(s)

Linux (x86)

### What version/commit are you on?

1.0.0

### What database version are you on?

2

### Which chain / network are you on?

1

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by ForLina** [comment]
I'd like to know is there any flags like  --txlookuplimit  in geth?

**Comment by dwinurhadia** [comment]
Is there any update from this issue?
