### ISSUE TITLE
refactor: Use consistent types for Transaction fields

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#976]
### Describe the feature

All transaction types use u128 where possible:

https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/transaction/mod.rs

should be mirrored in the transaction pool implementation:

https://github.com/paradigmxyz/reth/blob/c3261863977a7507727509305447e501fc6780fa/crates/transaction-pool/src/traits.rs#L241

## TODO
* use same types in `PoolTransaction` trait as transaction types

**Comment by mpaulucci** [comment]
Hi, can I take this one?

**Comment by mattsse** [comment]
sure! assigned.
ty!

**Comment by mattsse** [comment]
this mainly applies to `fee` and `gas_price` fields
