### ISSUE TITLE
Make EngineHandler terminate if underlying channels close

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9793]
currently the EngineApiRequestHandler returns pending if the channel closed, this can happen if a task panicked

https://github.com/paradigmxyz/reth/blob/ec9af398c4a717acb8bdca24011a41ed299eb6a8/crates/engine/tree/src/engine.rs#L189-L189

this should return an error instead, I think we can add a FatalError variant to

https://github.com/paradigmxyz/reth/blob/ec9af398c4a717acb8bdca24011a41ed299eb6a8/crates/engine/tree/src/chain.rs#L186-L188

that will be converted to 

https://github.com/paradigmxyz/reth/blob/ec9af398c4a717acb8bdca24011a41ed299eb6a8/crates/engine/tree/src/chain.rs#L158-L159

terminating the service loop

**Comment by mvares** [comment]
:shipit:
