### ISSUE TITLE
Replace `once_cell` with `std::sync`

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#9799]
### Describe the feature

Replace `once_cell::sync::Lazy` with `std::sync::LazyLock`, which is now stable as of [Rust 1.80](https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html#lazycell-and-lazylock)

This requires also increasing MSRV to 1.80

**Comment by tcoratger** [comment]
@DaniPopes is it free? I've a pr ready if needed, let me know

**Comment by Rjected** [comment]
> @DaniPopes is it free? I've a pr ready if needed, let me know

no, @harsh-ps-2003 had one in progress that was already reviewed, and it was only closed due to git issues on their end, per the PR listed above. It would be best to wait for them to re-submit and give them a chance to go through the review process

**Comment by harsh-ps-2003** [comment]
@Rjected @tcoratger thanks for waiting! Really appreciate it!

**Comment by tcoratger** [comment]
@harsh-ps-2003 let me know if you need help
