### ISSUE TITLE
Integrate `chain_id` and `protocol_version` in `NetworkInfo`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#980]
### Describe the feature

for the `eth` namespace we need:

https://github.com/paradigmxyz/reth/blob/681f8a601a7eb4ac9141ebcbf37ba8d52d1f41e0/crates/net/rpc/src/eth/api/mod.rs#L62-L72

this info should be provided via the `NetworkInfo` trait.

I think chain_id should be a separate function and protocol version perhaps part of the `NetworkStatus`.

For chain_id we could create an `Arc<AtomicU64>` in `NetworkInner`

**Comment by leruaa** [comment]
I can take this on

**Comment by leruaa** [comment]
For `protocol_version`, can we use `HelloMessage::protocol_version`?

**Comment by mattsse** [comment]
> protocol_version, can we use HelloMessage::protocol_version

yes

we don't want the entire HelloMessage in there though
