### ISSUE TITLE
Scaffold `debug_` RPC name space Handler implementation

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#981]
### Describe the feature

Introduce missing `DebugApi` type, implementation of rpc functions not possible atm, but can start with the type 

## TODO
* add `DebugApi` struct
* impl `DebugApiServer`
* keep impls as `todo!()`

Similar to:

https://github.com/paradigmxyz/reth/blob/c7289bd9e8b486fa2d6ffbc67084613712223784/crates/net/rpc/src/admin.rs#L12-L28

**Comment by CryptoTurboFish** [comment]
i can help with this and also #982
