### ISSUE TITLE
Expose entire prune config in CLI args

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#9816]
### Describe the feature

Currently only the `--full` flag exists. The entire prune config should be exposed in CLI, that is, a flag for setting the prune setting for each segment individually.

**Comment by emhane** [comment]
exactly, so setting prune modes for each segment with a flag, smthg like `---prune.receipts.full` xor `--prune.receipts.distance <u64>` xor `--prune.receipts.before <u64>`. see `PruneModes` struct and `PruneMode` enum.

**Comment by garwahl** [comment]
Hey @emhane per https://github.com/paradigmxyz/reth/pull/10409#issuecomment-2306872336 could you assign me to this. I'll take a look and come back with a few questions

**Comment by garwahl** [comment]
Hey @emhane could you point me to where the valid values for prune config in `reth.toml` are parsed/used? Ideally want to keep the semantics between how reth.toml and how the CLI args look roughly similar

**Comment by emhane** [comment]
@garwahl <https://github.com/paradigmxyz/reth/blob/e18a46d0a59f776464c0c6905c5e7ef371bc06e3/crates/config/src/config.rs#L373-L382>

**Comment by garwahl** [comment]
Ah sorry I meant where the lines from reth.toml are serialized/mapped into a valid PruneConfig. ie how does say the string `prune.receipts.full` get mapped into a valid `PruneConfig.segments.receipts value`

**Comment by garwahl** [comment]
@emhane Another question, currently `--full` creates a sane default of `PruneConfig`. Once we expose setting PruneModes for each segment, what is the intended behaviour with setting `--full` and for example `prune.receipts.distance <u64>` at the same time? 

Do we expect the sane defaults to be created as it is today, but just the `receipts` part to be overwritten with our new value OR can you not configure any separate segment if --full is specified?

**Comment by garwahl** [comment]
I've raised https://github.com/paradigmxyz/reth/pull/10639 as a draft, let's move discussion there.
