### ISSUE TITLE
Implement Web3 namespace RPC handler

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#983]
### Describe the feature

Add missing `Web3Api` type and implementation of

https://github.com/paradigmxyz/reth/blob/c7289bd9e8b486fa2d6ffbc67084613712223784/crates/net/rpc-api/src/web3.rs#L4-L15

`client_version` should be included in `NetworkInfo` I think

Similar to:

https://github.com/paradigmxyz/reth/blob/c7289bd9e8b486fa2d6ffbc67084613712223784/crates/net/rpc/src/admin.rs#L12-L28

**Comment by leruaa** [comment]
I would like to take this on

**Comment by leruaa** [comment]
@mattsse What do you think is the best to build `client_version`? I was thinking to use `clap::crate_version!()`, and transmit it to `NetworkHandle` via `NetworkConfig`.

**Comment by mattsse** [comment]
hmm I guess this is just the Client name in `NetworkStatus`, we can just use that for now.
