### ISSUE TITLE
Error when using stateOverrides to set sender's balance to 0 

### ISSUE THREAD

**Issue by Otto-AA** [paradigmxyz/reth#9853]
### Describe the bug

When using `debug_traceCall` and setting the balance of the sender to 0 it will result in an `internal blocking task error`.

It's not a useful thing to do and I still have to figure out why my script tried this in the first place. However, a nice error message would still be useful instead of an internal error, at least for me it would have saved me some debugging time :)

For instance, on Erigon:
```
Exception: {'code': -32000, 'message': 'tracing failed: insufficient funds for gas * price + value: address 0x091A851D6C1D4E74FD0FAa9Ddb9Af5B7df9D25ba have 0 want 400000000000000'}
```

### Steps to reproduce

Set the sender's balance to 0, e.g.:

```python3
import requests

provider = 'http://localhost:8124/eth'

def rpc(method: str, params: list):
    data = {
        'id': 1,
        'method': method,
        'params':params,
        'jsonrpc': '2.0',
    }
    res = requests.post(provider, json=data)
    res.raise_for_status()

    res = res.json()
    if 'error' in res:
        raise Exception(res['error'])
    return res['result']

method = 'debug_traceCall'
params = [
    {
        "chainId": "0x1",
        "data": "",
        "from": "0x091A851D6C1D4E74FD0FAa9Ddb9Af5B7df9D25ba",
        "gas": "0x186a0",
        "gasPrice": "0xee6b2800",
        "nonce": "0x0",
        "to": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
        "type": "0x0",
        "value": "0x0"
    },
    "0x12f94cf",
    {
        "stateOverrides": {
            "0x091a851d6c1d4e74fd0faa9ddb9af5b7df9d25ba": {
                "balance": "0x0"
            }
        },
        "tracer": "prestateTracer",
        "tracerConfig": {
            "diffMode": True
        }
    }
]

rpc(method, params)
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth/v1.0.3-1a21d8b0 (I've used http://69.67.151.138:8545).

### What database version are you on?

idk

### Which chain / network are you on?

idk

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks for flagging, this was caused by bad error conversion
