### ISSUE TITLE
staged-sync: use smaller incremental range for subsequent merkle stage runs

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#9860]
## Issue Description

Currently, there are 2 paths for `MerkleExecute` stage: clean trie reconstruction & incremental trie update. The threshold for discarding all previous trie progress and starting from scratch is quite low due to the entire block range being passed as an argument to incremental trie computation and it being memory intensive. Logic in question at L174 below

https://github.com/paradigmxyz/reth/blob/6d036cd95b68b80c5dc40a768c30784eb84162d6/crates/stages/stages/src/stages/merkle.rs#L172-L177

## Desired Behavior

Introduce a new parameter inside `MerkleExecute` stage called `commit_threshold`. Change the behavior of the incremental path to keep running incremental root until completed if entire block range doesn't exceed `clean_threshold`. Increase `clean_threshold` to much bigger number (e.g. >100k TBD).

## Testing requirements

To complete this issue, the contributor is required to perform mainnet sync with new logic, experiment with different values for `commit_threshold` and report them in the PR description.

**Comment by forcodedancing** [comment]
## Case1: normal

<img width="944" alt="Screenshot 2024-07-29 at 14 58 09" src="https://github.com/user-attachments/assets/620f6da2-f024-4c2c-bbf9-e7ac6d1f873a">

avg time for each block: ~3 hours and 40 minutes / 71488

## Case2:  the performance is bad

<img width="942" alt="Screenshot 2024-07-29 at 14 58 22" src="https://github.com/user-attachments/assets/868618ac-c388-4842-89b1-ed4998498b34">

avg time for each block: ~3 hours and 55 minutes / 5005

There is `Rebuilding tire` logs for this execution.

**Comment by siddharth0a** [comment]
I found some weire point that from this check, to_block should be from_block.
`let mut entities_checkpoint = if let Some(checkpoint) =
                checkpoint.as_ref().filter(|c| c.target_block == to_block)`
because the target_block of checkpoint is the last block of the previous range and it should be from_block of current range.

If my hypothesis is right I would like to make another issue or make PR for this one
