### ISSUE TITLE
Rework `OpEthApi` type

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#9868]
### Describe the feature

`OpEthApi` should wrap `EthApiInner<...>`, just like `EthApi` struct does, instead of the generic `Eth`. Calling `Eth::some_trait_method` in implementation of `EthApiServer` helper traits is bug prone, since any default trait method overrides for `OpEthApi`, won't be considered if called inside scope of `Eth::some_trait_method`.

**Comment by mvares** [comment]
:shipit:

**Comment by mvares** [comment]
@emhane, `OpEthApi` would need to add generics to all that implement it.

**Comment by emhane** [comment]
yeah that's right @mvares

**Comment by emhane** [comment]
for OP I can use `FullNodeComponents` though to unify the generics `Provider, Pool, Evm`, we just didn't make that change for `EthApi` because it would require a lot of work fixing existing tests

**Comment by mvares** [comment]
right… thanks for explanation
