### ISSUE TITLE
Add ATs `Network` and `Task` to `FullNodeComponents`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#9872]
### Describe the feature

RPC types use generics `Network` and `Tasks`, which resolve to the type returned by `FullNodeComponents` getters. 

The two should be added as ATs on `FullNodeComponents`, to make them possible to reference in type definitions.

https://github.com/paradigmxyz/reth/blob/f43fd7bd618d76325b9aef7f5ff6e47baca403f0/crates/node/api/src/node.rs#L141-L148

**Comment by mattsse** [comment]
marking this as complete because we don't need a generic for tasks
