### ISSUE TITLE
How to configure to use the intranet address? 

### ISSUE THREAD

**Issue by theone-pang** [paradigmxyz/reth#9889]
### Describe the bug

I want to create a private chain。 How to configure to use the intranet address? I found that if --disable-discovery is set, the intranet address can be used, but in this case, --bootnodes cannot be used to establish a connection.Currently, only external network addresses can be used to establish connections.

### Steps to reproduce

I want to create a private chain。 How to configure to use the intranet address? I found that if --disable-discovery is set, the intranet address can be used, but in this case, --bootnodes cannot be used to establish a connection. Currently, only external network addresses can be used to establish connections.

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth release 1.0.3

### What database version are you on?

reth release 1.0.3

### Which chain / network are you on?

private

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by emhane** [comment]
not sure about discv4, but you can use LAN addresses and localhost with discv5. as long as the ENR address matches the source address in discv5, you're fine. so make sure that your machines only communicate over the interface of the ENR udp address. flags would be `--disable-discv4-discovery` and `--enable-discv5-discovery`, and remember to set the discv5 address explicitly with `--discovery.v5.addr` or `--discovery.v5.addr.ipv6`

**Comment by theone-pang** [comment]
i try , use --trusted-peers can connectted,but  --bootnodes can not

**Comment by emhane** [comment]
which version are you on? should be fixed since https://github.com/paradigmxyz/reth/pull/9885

**Comment by theone-pang** [comment]
--disable-discv4-discovery  --enable-discv5-discovery  --discovery.v5.addr=127.0.0.1  --discovery.v5.port=9001 be config, and use --trusted-peers can connect,but --bootnodes can not in version 1.0.5.
the same config in version 1.0.6 can not connect
