### ISSUE TITLE
[RPC] eth_feeHistory support pending block tag

### ISSUE THREAD

**Issue by mateipopp** [paradigmxyz/reth#9903]
### Describe the bug

The RPC method eth_feeHistory is returning "unknown block number" when querying for the pending block. Geth nodes behave well, returning the proper response:
`{"jsonrpc":"2.0","id":1,"result":{"oldestBlock":"0x137932b","reward":[["0x6188afa","0x3814fea0","0x7d12f742"],["0x3814fea0","0x3b9aca00","0x77359400"],["0x5bed87d","0x3814fea0","0x74d33a00"],["0x57fed58","0x3b9aca00","0x74d33a00"]],"baseFeePerGas":["0x1dcd2f190","0x1dd19920d","0x1d7235b53","0x1d75662a8","0x1b5640456"],"gasUsedRatio":[0.5023143666666666,0.4500165666666667,0.5016923333333333,0.21191126666666665],"baseFeePerBlobGas":["0x1","0x1","0x1","0x1","0x1"],"blobGasUsedRatio":[0.3333333333333333,0.16666666666666666,0.8333333333333334,0.16666666666666666]}}`

### Steps to reproduce

```
curl -X POST localhost:8545 \
     -H "Content-Type: application/json" \
     -d '{
           "jsonrpc": "2.0",
           "method": "eth_feeHistory",
           "params": [4, "pending", [25, 50, 75]],
           "id": 1
         }'

{"jsonrpc":"2.0","error":{"code":-32001,"message":"unknown block number"},"id":1}
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 1.0.3
Commit SHA: 390f30aadebcdd509e72cc04327c3b854de076a6
Build Timestamp: 2024-07-18T22:35:55.248811284Z
Build Features: jemalloc
Build Profile: maxperf

### What database version are you on?

2024-07-30T12:26:49.525589Z  INFO Initialized tracing, debug log directory: /root/.cache/reth/logs/mainnet
Current database version: 2
Local database version: 2

### Which chain / network are you on?

ETh mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
thanks for this,

support for the pending block is indeed missing, #9904 is a hotfix for the error until we have this natively supported

**Comment by mattsse** [comment]
to fix this we need to

1. check if the tag is the pending block https://github.com/paradigmxyz/reth/blob/e3d375a8f3e9e79a9e8afbca6ab28844755ee70d/crates/rpc/rpc-eth-api/src/helpers/fee.rs#L78-L78
2. if so we need to fetch the pending block and receipts
3. manually insert into the fee entries https://github.com/paradigmxyz/reth/blob/e3d375a8f3e9e79a9e8afbca6ab28844755ee70d/crates/rpc/rpc-eth-api/src/helpers/fee.rs#L125-L125
4. or add as an additional entry to the headers https://github.com/paradigmxyz/reth/blob/e3d375a8f3e9e79a9e8afbca6ab28844755ee70d/crates/rpc/rpc-eth-api/src/helpers/fee.rs#L155-L155

maybe @loocapro wants to take this?

**Comment by loocapro** [comment]
I can take this!

**Comment by DmytroShalaiev** [comment]
Same issue, thanks

**Comment by mattsse** [comment]
marking this as resolved because we no longer return an error here and tracking a better solution for this separately
