### ISSUE TITLE
Add OP cli flag to opt-in into discv4 discovery

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9919]
### Describe the feature

see also https://github.com/paradigmxyz/reth/pull/9918

## TODO
* add an op cli flag for `--discovery.v4: bool` that enables discovery v4 if provided

this mirrors op-geth cli settings, see #9918

https://github.com/paradigmxyz/reth/blob/2c2a782bb83a916fba2a2be21e576110fd371fd1/crates/optimism/node/src/args.rs#L8-L8

**Comment by siddharth0a** [comment]
Can I take this??
