### ISSUE TITLE
Support for using `reth-primitives` with SP1

### ISSUE THREAD

**Issue by manav2401** [paradigmxyz/reth#9931]
### Describe the feature

I want to use `reth-primitives` as a dependency in SP1 but it doesn't compile. It'll be great if [this](https://github.com/paradigmxyz/reth/blob/a90fc90df8be565173e6951c315c2ae4d3d73c3c/.github/assets/check_no_std.sh#L22) command worked for`reth-primitives` which is commented above. 

Thanks!

**Comment by manav2401** [comment]
A bit more context behind this. 

I added `reth-primitives`, `alloy-primitives` and `alloy-rlp` as a dependency in my SP1 project. While the root rust program compiles well, SP1's zkVM can't really compile the programme for generating proofs. I had a discussion with their team and they mentioned that they maintain a custom fork for such compatibility changes. I thought it will be great to have those custom changes (which I am not fully aware of) in the main repo itself. They mentioned that they'll create these PRs and they'll also update the CI such that any changes which affects their lifecycle gets caught.

TL;DR: This might be something which their team will take a look into. Thanks!

**Comment by mattsse** [comment]
ah sorry this targets reth-primitives

**Comment by mattsse** [comment]
marking this as resolved because we're deprecating the current version of reth-primitives and are supporting riscv compatibility with the replacement via eth-primitives/op-primitives
