### ISSUE TITLE
Remove PHF from Static Files

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#9946]
### Describe the feature

Fixes https://github.com/paradigmxyz/reth/issues/9939

## Problem
We don't use perfect hash functions for any static file segments, but they cause dependency bloat and compilation errors for Wasm.

## Solution

Remove `ph` dependency from `reth-nippy-jar` crate without breaking backward compatibility of configuration files.

This will require leaving a dummy `phf` field for compatibility reasons https://github.com/paradigmxyz/reth/blob/750eb26256b6fcea0ad378a8cf08fe28f2dc0a7b/crates/storage/nippy-jar/src/lib.rs#L115-L116

**Comment by Parikalp-Bhardwaj** [comment]
I'm new to the open source community and very eager to start contributing! I came across Issue #9946, which involves removing PHF dependencies from static files. From what I understand, the task requires updating the Cargo.toml to remove the ph  dependency from reth-nippy-jar dependency and modifying the code to replace ```phf: Option<Functions> with phf: Option<DummyPhf>``` to maintain compatibility.

I would like to try and resolve this issue. Could I take this on, or would you recommend starting with a different task? Any guidance or additional information you could provide would be greatly appreciated.

**Comment by Parikalp-Bhardwaj** [comment]
Hey @shekhirin, Removing the ph dependency from your project involves replacing the functionality provided by the `GOFunction` and `GOBuildConf` types from the ph crate. 
Replace `GOFunction` with a `HashMap`

Could you explain the key steps and considerations for making this change?
