### ISSUE TITLE
store receipts for local pending block

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9948]
### Describe the feature

currently we don't store the receipts for the pending block we just built

https://github.com/paradigmxyz/reth/blob/750eb26256b6fcea0ad378a8cf08fe28f2dc0a7b/crates/rpc/rpc-eth-types/src/pending_block.rs#L118-L118

and for eth_getBlockreceipts we don't check the local block 

https://github.com/paradigmxyz/reth/blob/750eb26256b6fcea0ad378a8cf08fe28f2dc0a7b/crates/rpc/rpc-eth-api/src/helpers/block.rs#L154-L154

## TODO
* store receipts for locally built block and integrate in `LoadPendingBlock`
 

cc @loocapro

**Comment by malik672** [comment]
@mattsse  assign me

**Comment by Parikalp-Bhardwaj** [comment]
Hi @malik672 are you still working on this issue?

**Comment by malik672** [comment]
yeah
