### ISSUE TITLE
`Network:: get_status` should return `NetworkStatus`

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#996]
Rn `Network:: get_status` returns `Status`:

https://github.com/paradigmxyz/reth/blob/def59c399658caee5a0e2124d9b11cf23f711a97/crates/net/network/src/network.rs#L132-L137

but should return `NetworkStatus` directly

This refactor will make `fn get_status` obsolete, everything should be moved to `fn network_status`
            

cc @leruaa

**Comment by leruaa** [comment]
I'm on it
