### ISSUE TITLE
Compile `zstd` for Wasm

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#9983]
### Describe the feature

`zstd-rs` [can be compiled](https://github.com/gyscos/zstd-rs/blob/fc3a73100b6d3f2ff6dd3da0ff14dd9185ba02f0/zstd-safe/zstd-sys/build.rs#L132-L146) to Wasm targets with `std` support, but it currently fails as if there are no shims were provided:
```console
cargo:warning=zstd/lib/common/zstd_deps.h:29:10: fatal error: 'string.h' file not found
  cargo:warning=   29 | #include <string.h>
  cargo:warning=      |          ^~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 0
  exit status: 1
```

We need to investigate and fix that.

**Comment by Rjected** [comment]
done in https://github.com/paradigmxyz/reth/pull/10032
